      real(r8) :: CARBN(JP,JY,JX),TCUPTK(JP,JY,JX),TCSNC(JP,JY,JX)
     2,TZUPTK(JP,JY,JX),TZSNC(JP,JY,JX),TPUPTK(JP,JY,JX),TPSNC(JP,JY,JX)
     3,TZUPFX(JP,JY,JX),TCO2T(JP,JY,JX),BALC(JP,JY,JX),BALN(JP,JY,JX)
     4,BALP(JP,JY,JX),HCSNC(JP,JY,JX),HZSNC(JP,JY,JX),HPSNC(JP,JY,JX)
     5,HCUPTK(JP,JY,JX),HZUPTK(JP,JY,JX),HPUPTK(JP,JY,JX),ZNPP(JP,JY,JX)
     6,TCSN0(JP,JY,JX),CTRAN(JP,JY,JX),RNH3C(JP,JY,JX),RSETC(JP,JY,JX)
     7,RSETN(JP,JY,JX),RSETP(JP,JY,JX),HVSTC(JP,JY,JX),HVSTN(JP,JY,JX)
     8,HVSTP(JP,JY,JX),THVSTC(JP,JY,JX),THVSTN(JP,JY,JX),TNH3C(JP,JY,JX)
     9,THVSTP(JP,JY,JX),TCO2A(JP,JY,JX),VCO2F(JP,JY,JX),VCH4F(JP,JY,JX)
     1,VOXYF(JP,JY,JX),VNH3F(JP,JY,JX),VN2OF(JP,JY,JX),VPO4F(JP,JY,JX)
     2,TZSN0(JP,JY,JX),TPSN0(JP,JY,JX)

      COMMON/BLK14/CARBN,TCUPTK,TCSNC
     2,TZUPTK,TZSNC,TPUPTK,TPSNC
     3,TZUPFX,TCO2T,BALC,BALN
     4,BALP,HCSNC,HZSNC,HPSNC
     5,HCUPTK,HZUPTK,HPUPTK,ZNPP
     6,TCSN0,CTRAN,RNH3C,RSETC
     7,RSETN,RSETP,HVSTC,HVSTN
     8,HVSTP,THVSTC,THVSTN,TNH3C
     9,THVSTP,TCO2A,VCO2F,VCH4F
     1,VOXYF,VNH3F,VN2OF,VPO4F
     2,TZSN0,TPSN0
