      real(r8) :: ZLSGL(0:JZ,JY,JX),ZHSGL(JZ,JY,JX),ZNSGL(0:JZ,JY,JX)
     2,ZOSGL(0:JZ,JY,JX),POSGL(0:JZ,JY,JX),OCSGL(0:JZ,JY,JX)
     3,ONSGL(0:JZ,JY,JX),OPSGL(0:JZ,JY,JX),OASGL(0:JZ,JY,JX)
     4,Z2SGL(JZ,JY,JX),ZVSGL(0:JZ,JY,JX)
     5,WGSGL(JZ,JY,JX),WGSGW(JS,JY,JX),WGSGR(JY,JX),WGSGA(JY,JX)
     6,SCO2L(0:JZ,JY,JX),SOXYL(0:JZ,JY,JX),SCH4L(0:JZ,JY,JX)
     7,SN2OL(0:JZ,JY,JX),SN2GL(0:JZ,JY,JX),SNH3L(0:JZ,JY,JX)
     8,SH2GL(0:JZ,JY,JX),PSISE(0:JZ,JY,JX),PSISA(0:JZ,JY,JX)
     9,PSISO(0:JZ,JY,JX),PSISH(0:JZ,JY,JX),THETX,THETPI,DENSI,DENSJ
     1,THETY(0:JZ,JY,JX),THETS(0:JZ,JY,JX),VOLQ(0:JZ,JY,JX)
     2,TFNQ(0:JZ,JY,JX),HGSGL(JZ,JY,JX),HLSGL(0:JZ,JY,JX)
     3,THAWR(JY,JX),HTHAWR(JY,JX),FLSW(JS,JY,JX),FLSWH(JS,JY,JX)
     4,HFLSW(JS,JY,JX),FLSWR(JS,JY,JX),HFLSWR(JS,JY,JX)

      COMMON/BLK11B/ZLSGL,ZHSGL,ZNSGL
     2,ZOSGL,POSGL,OCSGL
     3,ONSGL,OPSGL,OASGL
     4,Z2SGL,ZVSGL
     5,WGSGL,WGSGW,WGSGR,WGSGA
     6,SCO2L,SOXYL,SCH4L
     7,SN2OL,SN2GL,SNH3L
     8,SH2GL,PSISE,PSISA
     9,PSISO,PSISH,THETX,THETPI,DENSI,DENSJ
     1,THETY,THETS,VOLQ
     2,TFNQ,HGSGL,HLSGL
     3,THAWR,HTHAWR,FLSW,FLSWH
     4,HFLSW,FLSWR,HFLSWR
