      COMMON/FILEC/DATA,DATAC,DATAP,DATAM,DATAX,DATAY,DATAZ
     2,OUTS,OUTP,OUTFILS,OUTFILP,CHOICE,CDATE,PREFIX

      CHARACTER*16 DATA(30),DATAC(30,250,250),DATAP(JP,JY,JX)
     2,DATAM(JP,JY,JX),DATAX(JP),DATAY(JP),DATAZ(JP,JY,JX)
     3,OUTS(10),OUTP(10),OUTFILS(10,JY,JX),OUTFILP(10,JP,JY,JX)
      CHARACTER*3 CHOICE(102,20)
      CHARACTER*8 CDATE
      CHARACTER*80 PREFIX
