#hourly



class histlist():
    def __init__(self):
        self.hourly_carbon={'SOIL_CO2_FLUX':['YES','g m^-2 h^-1','soil CO2 flux'],
            'ECO_CO2_FLUX':['YES','g m^-2 h^-1','total canopy net CO2 exchange'],
            'CH4_FLUX':['YES','g m^-2 h^-1','soil CH4 flux'],
            'O2_FLUX':['YES','g m^-2 h^-1','soil O2 flux'],
            'CO2_1':['YES','g m^-3','layer-1 aqueous CO2 concentration micropore'],
            'CO2_2':['YES','g m^-3','layer-2 aqueous CO2 concentration micropore'],
            'CO2_3':['YES','g m^-3','layer-3 aqueous CO2 concentration micropore'],
            'CO2_4':['YES','g m^-3','layer-4 aqueous CO2 concentration micropore'],
            'CO2_5':['YES','g m^-3','layer-5 aqueous CO2 concentration micropore'],
            'CO2_6':['YES','g m^-3','layer-6 aqueous CO2 concentration micropore'],
            'CO2_7':['YES','g m^-3','layer-7 aqueous CO2 concentration micropore'],
            'CO2_8':['YES','g m^-3','layer-8 aqueous CO2 concentration micropore'],
            'CO2_9':['YES','g m^-3','layer-9 aqueous CO2 concentration micropore'],
            'CO2_10':['YES','g m^-3','layer-10 aqueous CO2 concentration micropore'],
            'CO2_11':['YES','g m^-3','layer-11 aqueous CO2 concentration micropore'],
            'CO2_12':['YES','g m^-3','layer-12 aqueous CO2 concentration micropore'],
            'CO2_13':['YES','g m^-3','layer-13 aqueous CO2 concentration micropore'],
            'CO2_14':['YES','g m^-3','layer-4 aqueous CO2 concentration micropore'],
            'CO2_LIT':['YES','g m^-3','layer-0 aqueous CO2 concentration micropore'],
            'CH4_1':['YES','g m^-3','layer-1 aqueous CH4 concentration micropore'],
            'CH4_2':['YES','g m^-3','layer-2 aqueous CH4 concentration micropore'],
            'CH4_3':['YES','g m^-3','layer-3 aqueous CH4 concentration micropore'],
            'CH4_4':['YES','g m^-3','layer-4 aqueous CH4 concentration micropore'],
            'CH4_5':['YES','g m^-3','layer-5 aqueous CH4 concentration micropore'],
            'CH4_6':['YES','g m^-3','layer-6 aqueous CH4 concentration micropore'],
            'CH4_7':['YES','g m^-3','layer-7 aqueous CH4 concentration micropore'],
            'CH4_8':['YES','g m^-3','layer-8 aqueous CH4 concentration micropore'],
            'CH4_9':['YES','g m^-3','layer-9 aqueous CH4 concentration micropore'],
            'CH4_10':['YES','g m^-3','layer-10 aqueous CH4 concentration micropore'],
            'CH4_11':['YES','g m^-3','layer-11 aqueous CH4 concentration micropore'],
            'CH4_12':['YES','g m^-3','layer-12 aqueous CH4 concentration micropore'],
            'CH4_13':['YES','g m^-3','layer-13 aqueous CH4 concentration micropore'],
            'CH4_14':['YES','g m^-3','layer-14 aqueous CH4 concentration micropore'],
            'CH4_15':['YES','g m^-3','layer-15 aqueous CH4 concentration micropore'],
            'O2_1':['YES','g m^-3','layer-1 aqueous O2 concentration micropore'],
            'O2_2':['YES','g m^-3','layer-2 aqueous O2 concentration micropore'],
            'O2_3':['YES','g m^-3','layer-3 aqueous O2 concentration micropore'],
            'O2_4':['YES','g m^-3','layer-4 aqueous O2 concentration micropore'],
            'O2_5':['YES','g m^-3','layer-5 aqueous O2 concentration micropore'],
            'O2_6':['YES','g m^-3','layer-6 aqueous O2 concentration micropore'],
            'O2_7':['YES','g m^-3','layer-7 aqueous O2 concentration micropore'],
            'O2_8':['YES','g m^-3','layer-8 aqueous O2 concentration micropore'],
            'O2_9':['YES','g m^-3','layer-9 aqueous O2 concentration micropore'],
            'O2_10':['YES','g m^-3','layer-10 aqueous O2 concentration micropore'],
            'O2_11':['YES','g m^-3','layer-11 aqueous O2 concentration micropore'],
            'O2_12':['YES','g m^-3','layer-12 aqueous O2 concentration micropore'],
            'O2_13':['YES','g m^-3','layer-13 aqueous O2 concentration micropore'],
            'O2_14':['YES','g m^-3','layer-14 aqueous O2 concentration micropore'],
            'O2_15':['YES','g m^-3','layer-15 aqueous O2 concentration micropore'],
            'O2_LIT':['YES','g m^-3','layer-0 aqueous O2 concentration micropore'],
            'CAN_CO2_FLUX':['YES','g m^-2 h^-1','Canopy net CO2 exchange'],
            'CAN_GPP':['YES','g m^-2','Total gross CO2 fixation-GPP'],
            'CAN_RA':['YES','g m^-2','Total autotrophic respiration'],
            '[TNC]':['YES','g m^-2','Canopy nonstructural C concentration'],
            'STOML_RSC':['YES','h m^-1','Canopy stomatal resistance'],
            'BLYR_RSC':['YES','h m^-1','Canopy boundary layer resistance'],
            '[CAN_CO2]':['YES','umol mol^-1','canopy gaesous CO2 concentration'],
            'LAI':['YES','m^2 m^-2','Leaf area index']}

        self.hourly_water={'EVAPN':['YES','m^3 m^-2 h^-1','total evaporation at ground surface'],
            'RUNOFF':['YES','m^3 m^-2 h^-1','surface water runoff'],
            'SEDIMENT':['YES','Mg m^-2','total sediment subsurface flux'],
            'TTL_SWC':['YES','m^3 m^-2','total soil water content'],
            'DISCHG':['YES','m^3 m^-2 h^-1','water discharge'],
            'SNOWPACK':['YES','m^3 m^-2','total water equivalent snow'],
            'WTR_1':['YES','m^3 m^-3','layer-1 volumetric soil micropore water'],
            'WTR_2':['YES','m^3 m^-3','layer-2 volumetric soil micropore water'],
            'WTR_3':['YES','m^3 m^-3','layer-3 volumetric soil micropore water'],
            'WTR_4':['YES','m^3 m^-3','layer-4 volumetric soil micropore water'],
            'WTR_5':['YES','m^3 m^-3','layer-5 volumetric soil micropore water'],
            'WTR_6':['YES','m^3 m^-3','layer-6 volumetric soil micropore water'],
            'WTR_7':['YES','m^3 m^-3','layer-7 volumetric soil micropore water'],
            'WTR_8':['YES','m^3 m^-3','layer-8 volumetric soil micropore water'],
            'WTR_9':['YES','m^3 m^-3','layer-9 volumetric soil micropore water'],
            'WTR_10':['YES','m^3 m^-3','layer-10 volumetric soil micropore water'],
            'WTR_11':['YES','m^3 m^-3','layer-11 volumetric soil micropore water'],
            'WTR_12':['YES','m^3 m^-3','layer-12 volumetric soil micropore water'],
            'WTR_13':['YES','m^3 m^-3','layer-13 volumetric soil micropore water'],
            'WTR_14':['YES','m^3 m^-3','layer-14 volumetric soil micropore water'],
            'WTR_15':['YES','m^3 m^-3','layer-15 volumetric soil micropore water'],
            'WTR_16':['YES','m^3 m^-3','layer-16 volumetric soil micropore water'],
            'WTR_17':['YES','m^3 m^-3','layer-17 volumetric soil micropore water'],
            'WTR_18':['YES','m^3 m^-3','layer-18 volumetric soil micropore water'],
            'WTR_19':['YES','m^3 m^-3','layer-19 volumetric soil micropore water'],
            'WTR_20':['YES','m^3 m^-3','layer-20 volumetric soil micropore water'],
            'SURF_WTR':['YES','m^3 m^-3','layer-0 volumetric soil micropore water'],
            'ICE_1':['YES','m^3 m^-3','layer-1 soil micropore ice content'],
            'ICE_2':['YES','m^3 m^-3','layer-2 soil micropore ice content'],
            'ICE_3':['YES','m^3 m^-3','layer-3 soil micropore ice content'],
            'ICE_4':['YES','m^3 m^-3','layer-4 soil micropore ice content'],
            'ICE_5':['YES','m^3 m^-3','layer-5 soil micropore ice content'],
            'ICE_6':['YES','m^3 m^-3','layer-6 soil micropore ice content'],
            'ICE_7':['YES','m^3 m^-3','layer-7 soil micropore ice content'],
            'ICE_8':['YES','m^3 m^-3','layer-8 soil micropore ice content'],
            'ICE_9':['YES','m^3 m^-3','layer-9 soil micropore ice content'],
            'ICE_10':['YES','m^3 m^-3','layer-10 soil micropore ice content'],
            'ICE_11':['YES','m^3 m^-3','layer-11 soil micropore ice content'],
            'ICE_12':['YES','m^3 m^-3','layer-12 soil micropore ice content'],
            'ICE_13':['YES','m^3 m^-3','layer-13 soil micropore ice content'],
            'ICE_14':['YES','m^3 m^-3','layer-14 soil micropore ice content'],
            'ICE_15':['YES','m^3 m^-3','layer-15 soil micropore ice content'],
            'ICE_16':['YES','m^3 m^-3','layer-16 soil micropore ice content'],
            'ICE_17':['YES','m^3 m^-3','layer-17 soil micropore ice content'],
            'ICE_18':['YES','m^3 m^-3','layer-18 soil micropore ice content'],
            'ICE_19':['YES','m^3 m^-3','layer-19 soil micropore ice content'],
            'ICE_20':['YES','m^3 m^-3','layer-20 soil micropore ice content'],
            'SURF_ICE':['YES','m^3 m^-3','layer-0 soil micropore ice content'],
            'ACTV_LYR':['YES','m','active layer depth counting from soil surface'],
            'WTR_TBL':['YES','m','water table depth counting from soil surface'],
            'PSI_CAN':['YES','MPa','canopy total water potential'],
            'TURG_CAN':['YES','MPa','canopy turgor water potential'],
            'STOM_RSC':['YES','h m^-1','canopy stomatal resistance'],
            'BLYR_RSC':['YES','h m^-1','canopy boundary layer resistance'],
            'TRANSPN':['YES','m^2 m^-2 h^-1','canopy transpiration'],
            'O2_STRESS':['YES','none','plant O2 stress indicator'],
            'PSI_RT_1':['YES','MPa','layer-1 root total water potential'],
            'PSI_RT_2':['YES','MPa','layer-2 root total water potential'],
            'PSI_RT_3':['YES','MPa','layer-3 root total water potential'],
            'PSI_RT_4':['YES','MPa','layer-4 root total water potential'],
            'PSI_RT_5':['YES','MPa','layer-5 root total water potential'],
            'PSI_RT_6':['YES','MPa','layer-6 root total water potential'],
            'PSI_RT_7':['YES','MPa','layer-7 root total water potential'],
            'PSI_RT_8':['YES','MPa','layer-8 root total water potential'],
            'PSI_RT_9':['YES','MPa','layer-9 root total water potential'],
            'PSI_RT_10':['YES','MPa','layer-10 root total water potential'],
            'PSI_RT_11':['YES','MPa','layer-11 root total water potential'],
            'PSI_RT_12':['YES','MPa','layer-12 root total water potential'],
            'PSI_RT_13':['YES','MPa','layer-13 root total water potential'],
            'PSI_RT_14':['YES','MPa','layer-14 root total water potential'],
            'PSI_RT_15':['YES','MPa','layer-15 root total water potential']}

        self.hourly_nitrogen={'N2O_FLUX':['YES','g m^-2 h^-1','soil N2O flux'],
            'N2G_FLUX':['YES','g m^-2 h^-1','soil N2 flux'],
            'NH3_FLUX':['YES','g m^-2 h^-1','soil NH3 flux'],
            'SURF_N_FLUX':['YES','g m^-2','total surface DIN flux'],
            'SUBS_N_FLUX':['YES','g m^-2','total subsurface DIN flux'],
            'N2O_1':['YES','g m^-3','layer-1 aqueous N2O concentration micropore'],
            'N2O_2':['YES','g m^-3','layer-2 aqueous N2O concentration micropore'],
            'N2O_3':['YES','g m^-3','layer-3 aqueous N2O concentration micropore'],
            'N2O_4':['YES','g m^-3','layer-4 aqueous N2O concentration micropore'],
            'N2O_5':['YES','g m^-3','layer-5 aqueous N2O concentration micropore'],
            'N2O_6':['YES','g m^-3','layer-6 aqueous N2O concentration micropore'],
            'N2O_7':['YES','g m^-3','layer-7 aqueous N2O concentration micropore'],
            'N2O_8':['YES','g m^-3','layer-8 aqueous N2O concentration micropore'],
            'N2O_9':['YES','g m^-3','layer-9 aqueous N2O concentration micropore'],
            'N2O_10':['YES','g m^-3','layer-10 aqueous N2O concentration micropore'],
            'N2O_11':['YES','g m^-3','layer-11 aqueous N2O concentration micropore'],
            'N2O_12':['YES','g m^-3','layer-12 aqueous N2O concentration micropore'],
            'N2O_13':['YES','g m^-3','layer-13 aqueous N2O concentration micropore'],
            'N2O_14':['YES','g m^-3','layer-14 aqueous N2O concentration micropore'],
            'N2O_15':['YES','g m^-3','layer-15 aqueous N2O concentration micropore'],
            'NH3_1':['YES','g m^-3','layer-1 NH3 concentration non-band micropore'],
            'NH3_2':['YES','g m^-3','layer-2 NH3 concentration non-band micropore'],
            'NH3_3':['YES','g m^-3','layer-3 NH3 concentration non-band micropore'],
            'NH3_4':['YES','g m^-3','layer-4 NH3 concentration non-band micropore'],
            'NH3_5':['YES','g m^-3','layer-5 NH3 concentration non-band micropore'],
            'NH3_6':['YES','g m^-3','layer-6 NH3 concentration non-band micropore'],
            'NH3_7':['YES','g m^-3','layer-7 NH3 concentration non-band micropore'],
            'NH3_8':['YES','g m^-3','layer-8 NH3 concentration non-band micropore'],
            'NH3_9':['YES','g m^-3','layer-9 NH3 concentration non-band micropore'],
            'NH3_10':['YES','g m^-3','layer-10 NH3 concentration non-band micropore'],
            'NH3_11':['YES','g m^-3','layer-11 NH3 concentration non-band micropore'],
            'NH3_12':['YES','g m^-3','layer-12 NH3 concentration non-band micropore'],
            'NH3_13':['YES','g m^-3','layer-13 NH3 concentration non-band micropore'],
            'NH3_14':['YES','g m^-3','layer-14 NH3 concentration non-band micropore'],
            'NH3_15':['YES','g m^-3','layer-15 NH3 concentration non-band micropore'],
            'N2O_LIT':['YES','g m^-3','layer-0 aqueous N2O concentration micropore'],
            'NH3_LIT':['YES','g m^-3','layer-0 NH3 concentration non-band micropore'],
            'NH4_UPTK':['YES','g m^-2 h^-1','total root uptake of NH4'],
            'NO3_UPTK':['YES','g m^-2 h^-1','total root uptake of NO3'],
            'N2_FIXN':['YES','g m^-2 h^-1','total root N2 fixation'],
            '[TNN]':['YES','g g^-1','canopy nonstructural N concentration'],
            'NH3_FLUX':['YES','g m^-2 h^-1','canopy NH3 flux'],
            'UP_NH4_1':['YES','g m^-2 h^-1','layer-1 total root NH3 uptake'],
            'UP_NH4_2':['YES','g m^-2 h^-1','layer-2 total root NH3 uptake'],
            'UP_NH4_3':['YES','g m^-2 h^-1','layer-3 total root NH3 uptake'],
            'UP_NH4_4':['YES','g m^-2 h^-1','layer-4 total root NH3 uptake'],
            'UP_NH4_5':['YES','g m^-2 h^-1','layer-5 total root NH3 uptake'],
            'UP_NH4_6':['YES','g m^-2 h^-1','layer-6 total root NH3 uptake'],
            'UP_NH4_7':['YES','g m^-2 h^-1','layer-7 total root NH3 uptake'],
            'UP_NH4_8':['YES','g m^-2 h^-1','layer-8 total root NH3 uptake'],
            'UP_NH4_9':['YES','g m^-2 h^-1','layer-9 total root NH3 uptake'],
            'UP_NH4_10':['YES','g m^-2 h^-1','layer-10 total root NH3 uptake'],
            'UP_NH4_11':['YES','g m^-2 h^-1','layer-11 total root NH3 uptake'],
            'UP_NH4_12':['YES','g m^-2 h^-1','layer-12 total root NH3 uptake'],
            'UP_NH4_13':['YES','g m^-2 h^-1','layer-13 total root NH3 uptake'],
            'UP_NH4_14':['YES','g m^-2 h^-1','layer-14 total root NH3 uptake'],
            'UP_NH4_15':['YES','g m^-2 h^-1','layer-15 total root NH3 uptake'],
            'UP_NO3_1':['YES','g m^-2 h^-1','layer-1 total root NO3 uptake'],
            'UP_NO3_2':['YES','g m^-2 h^-1','layer-2 total root NO3 uptake'],
            'UP_NO3_3':['YES','g m^-2 h^-1','layer-3 total root NO3 uptake'],
            'UP_NO3_4':['YES','g m^-2 h^-1','layer-4 total root NO3 uptake'],
            'UP_NO3_5':['YES','g m^-2 h^-1','layer-5 total root NO3 uptake'],
            'UP_NO3_6':['YES','g m^-2 h^-1','layer-6 total root NO3 uptake'],
            'UP_NO3_7':['YES','g m^-2 h^-1','layer-7 total root NO3 uptake'],
            'UP_NO3_8':['YES','g m^-2 h^-1','layer-8 total root NO3 uptake'],
            'UP_NO3_9':['YES','g m^-2 h^-1','layer-9 total root NO3 uptake'],
            'UP_NO3_10':['YES','g m^-2 h^-1','layer-10 total root NO3 uptake'],
            'UP_NO3_11':['YES','g m^-2 h^-1','layer-11 total root NO3 uptake'],
            'UP_NO3_12':['YES','g m^-2 h^-1','layer-12 total root NO3 uptake'],
            'UP_NO3_13':['YES','g m^-2 h^-1','layer-13 total root NO3 uptake'],
            'UP_NO3_14':['YES','g m^-2 h^-1','layer-14 total root NO3 uptake'],
            'UP_NO3_15':['YES','g m^-2 h^-1','layer-15 total root NO3 uptake']}

        self.hourly_phosp={'SURF_P_FLUX':['YES','g m^-2','total surface DIP flux'],
            'SUBS_P_FLUX':['YES','g m^-2','total subsurface DIP flux'],
            'PO4_UPTK':['YES','g m^-2 h^-1','total root uptake of PO4'],
            '[TNP]':['YES','g g^-1','canopy nonstructural P concentration'],
            'UP_PO4_1':['YES','g m^-2 h^-1','layer-1 root uptake of PO4'],
            'UP_PO4_2':['YES','g m^-2 h^-1','layer-2 root uptake of PO4'],
            'UP_PO4_3':['YES','g m^-2 h^-1','layer-3 root uptake of PO4'],
            'UP_PO4_4':['YES','g m^-2 h^-1','layer-4 root uptake of PO4'],
            'UP_PO4_5':['YES','g m^-2 h^-1','layer-5 root uptake of PO4'],
            'UP_PO4_6':['YES','g m^-2 h^-1','layer-6 root uptake of PO4'],
            'UP_PO4_7':['YES','g m^-2 h^-1','layer-7 root uptake of PO4'],
            'UP_PO4_8':['YES','g m^-2 h^-1','layer-8 root uptake of PO4'],
            'UP_PO4_9':['YES','g m^-2 h^-1','layer-9 root uptake of PO4'],
            'UP_PO4_10':['YES','g m^-2 h^-1','layer-10 root uptake of PO4'],
            'UP_PO4_11':['YES','g m^-2 h^-1','layer-11 root uptake of PO4'],
            'UP_PO4_12':['YES','g m^-2 h^-1','layer-12 root uptake of PO4'],
            'UP_PO4_13':['YES','g m^-2 h^-1','layer-13 root uptake of PO4'],
            'UP_PO4_14':['YES','g m^-2 h^-1','layer-14 root uptake of PO4'],
            'UP_PO4_15':['YES','g m^-2 h^-1','layer-15 root uptake of PO4']}

        self.hourly_heat={'SOL_RADN':['YES','MJ m^-2 h^-1','daily solar radiation'],
            'AIR_TEMP':['YES','^oC','air temperature'],
            'HUM':['YES','kPa','vapor pressure'],
            'WIND':['YES','m s^-1','wind speed'],
            'PREC':['YES','mm h-1','total precipitation'],
            'SOIL_RN':['YES','MJ m^-2 h^-1','total net radiation at ground surface'],
            'SOIL_LE':['YES','MJ m^-2 h^-1','total latent heat flux at ground surface'],
            'SOIL_H':['YES','MJ m^-2 h^-1','total sensible heat flux at ground surface'],
            'SOIL_G':['YES','MJ m^-2 h^-1','total ground heat flux at ground surface'],
            'ECO_RN':['YES','MJ m^-2 h^-1','ecosystem net radiation'],
            'ECO_LE':['YES','MJ m^-2 h^-1','ecosystem latent heat flux'],
            'ECO_H':['YES','MJ m^-2 h^-1','ecosystem sensible heat flux'],
            'ECO_G':['YES','MJ m^-2 h^-1','ecosystem storage heat flux'],
            'TEMP_1':['YES','^oC','layer-1 soil temperature'],
            'TEMP_2':['YES','^oC','layer-2 soil temperature'],
            'TEMP_3':['YES','^oC','layer-3 soil temperature'],
            'TEMP_4':['YES','^oC','layer-4 soil temperature'],
            'TEMP_5':['YES','^oC','layer-5 soil temperature'],
            'TEMP_6':['YES','^oC','layer-6 soil temperature'],
            'TEMP_7':['YES','^oC','layer-7 soil temperature'],
            'TEMP_8':['YES','^oC','layer-8 soil temperature'],
            'TEMP_9':['YES','^oC','layer-9 soil temperature'],
            'TEMP_10':['YES','^oC','layer-10 soil temperature'],
            'TEMP_11':['YES','^oC','layer-11 soil temperature'],
            'TEMP_12':['YES','^oC','layer-12 soil temperature'],
            'TEMP_13':['YES','^oC','layer-13 soil temperature'],
            'TEMP_14':['YES','^oC','layer-14 soil temperature'],
            'TEMP_15':['YES','^oC','layer-15 soil temperature'],
            'TEMP_16':['YES','^oC','layer-16 soil temperature'],
            'TEMP_17':['YES','^oC','layer-17 soil temperature'],
            'TEMP_18':['YES','^oC','layer-18 soil temperature'],
            'TEMP_19':['YES','^oC','layer-19 soil temperature'],
            'TEMP_20':['YES','^oC','layer-20 soil temperature'],
            'TEMP_LITTER':['YES','^oC','layer-0 soil temperature'],
            'TEMP_SNOW':['YES','^oC','surface snow temperature'],
            'CAN_RN':['YES','MJ m^-2 h^-1','canopy net radiation '],
            'CAN_LE':['YES','MJ m^-2 h^-1','canopy latent heat flux'],
            'CAN_H':['YES','MJ m^-2 h^-1','canopy sensible heat flux'],
            'CAN_G':['YES','MJ m^-2 h^-1','canopy storage heat flux'],
            'CAN_TEMP':['YES','^oC','canopy temperature'],
            'TEMP_FN':['YES','none','canopy temperature growth function']}

        self.daily_carbon={'RESIDUE_C':['YES','g m^-2','total litter C'],
            'HUMUS_C':['YES','g m^-2','total humus C'],
            'AMENDED_C':['YES','g m^-2','total C amendment'],
            'LITTER_C':['YES','g m^-2','total litterfall C'],
            'CO2_FLUX':['YES','g m^-2','total soil CO2 flux'],
            'O2_FLUX':['YES','g m^-2','total soil O2 flux'],
            'AUTO_RESP':['YES','g m^-2','total soil autotrophic respiration'],
            'MICRO_C':['YES','g m^-2','total micriobial C'],
            'SURF_RES':['YES','g m^-2','surface litter carbon'],
            'CH4_FLUX':['YES','g m^-2','total soil CH4 flux'],
            'SUR_DOC+SED_FLX':['YES','g m^-2','total surface DOC flux'],
            'SUB_DOC_FLX':['YES','g m^-2','total subsurface DOC flux'],
            'SUR_DIC_FLX':['YES','g m^-2','total surface DIC flux'],
            'SUB_DIC_FLX':['YES','g m^-2','total subsurface DIC flux'],
            'ATM_CO2':['YES','umol mol-1','atmospheric CO2 concentration'],
            'NBP':['YES','g m^-2','total NBP'],
            'FIRE_CO2':['YES','g m^-2','total CO2 flux from fire'],
            'SOC_1':['YES','g m^-2','layer-1 total soil organic C'],
            'SOC_2':['YES','g m^-2','layer-2 total soil organic C'],
            'SOC_3':['YES','g m^-2','layer-3 total soil organic C'],
            'SOC_4':['YES','g m^-2','layer-4 total soil organic C'],
            'SOC_5':['YES','g m^-2','layer-5 total soil organic C'],
            'SOC_6':['YES','g m^-2','layer-6 total soil organic C'],
            'SOC_7':['YES','g m^-2','layer-7 total soil organic C'],
            'SOC_8':['YES','g m^-2','layer-8 total soil organic C'],
            'SOC_9':['YES','g m^-2','layer-9 total soil organic C'],
            'SOC_10':['YES','g m^-2','layer-10 total soil organic C'],
            'SOC_11':['YES','g m^-2','layer-11 total soil organic C'],
            'SOC_12':['YES','g m^-2','layer-12 total soil organic C'],
            'SOC_13':['YES','g m^-2','layer-13 total soil organic C'],
            'SOC_14':['YES','g m^-2','layer-14 total soil organic C'],
            'SOC_15':['YES','g m^-2','layer-15 total soil organic C'],
            'H2_FLUX':['YES','g m^-2','total H2 flux'],
            'ECO_HVST_C':['YES','g m^-2','ecosystem harvest C'],
            'ECO_LAI':['YES','m^2 m^-2','total canopy leaf area'],
            'ECO_GPP':['YES','g m^-2 h^-1','ecosystem GPP'],
            'ECO_RA':['YES','g m^-2 h^-1','ecosystem autotrophic respiration'],
            'ECO_NPP':['YES','g m^-2 h^-1','ecosystem NPP'],
            'ECO_RH':['YES','g m^-2 h^-1','ecosystem heterotrophic respiration'],
            'FIRE_CH4':['YES','g m^-2','total CH4 flux from fire'],
            'TTL_DIC':['YES','g m^-2','total soil DIC'],
            'STG_DEAD':['YES','g m^-2','total standing dead C'],
            'SHOOT_C':['YES','g m^-2','canopy shoot C'],
            'LEAF_C':['YES','g m^-2','canopy leaf C'],
            'SHTH_C':['YES','g m^-2','canopy sheath C '],
            'STALK_C':['YES','g m^-2','canopy stalk C'],
            'RESERVE_C':['YES','g m^-2','canopy reserve C'],
            'REPRO_C':['YES','g m^-2','husk C'],
            'GRAIN_C':['YES','g m^-2','canopy grain C'],
            'ROOT_C':['YES','g m^-2','plant root C'],
            'NDL_C':['YES','g m^-2','root total nodule mass'],
            'STORED_C':['YES','g m^-2','plant stored nonstructural C'],
            'GRAIN_NO.':['YES','m^-2','canopy grain number'],
            'LAI':['YES','m2 m^-2','plant leaf area'],
            'GPP':['YES','g m^-2','total gross CO2 fixation'],
            'EXUD_C':['YES','g m^-2','total net root C uptake (+ve) - exudation (-ve)'],
            'LITTER_C':['YES','g m^-2','total plant C litterfall '],
            'SF_LIT_C':['YES','g m^-2','total surface litterfall C'],
            'AUTO_RESP':['YES','g m^-2','total plant respiration'],
            'ABV_GRD_RESP':['YES','g m^-2','total autotrophic respiration'],
            '[SOL._C]':['YES','g m^-2','canopy nonstructural C concentration'],
            'HVST_C':['YES','g m^-2','plant C harvest'],
            'DNS_RT_1':['YES','m m^-3','layer-1 root layer length density'],
            'DNS_RT_2':['YES','m m^-3','layer-2 root layer length density'],
            'DNS_RT_3':['YES','m m^-3','layer-3 root layer length density'],
            'DNS_RT_4':['YES','m m^-3','layer-4 root layer length density'],
            'DNS_RT_5':['YES','m m^-3','layer-5 root layer length density'],
            'DNS_RT_6':['YES','m m^-3','layer-6 root layer length density'],
            'DNS_RT_7':['YES','m m^-3','layer-7 root layer length density'],
            'DNS_RT_8':['YES','m m^-3','layer-8 root layer length density'],
            'DNS_RT_9':['YES','m m^-3','layer-9 root layer length density'],
            'DNS_RT_10':['YES','m m^-3','layer-10 root layer length density'],
            'DNS_RT_11':['YES','m m^-3','layer-11 root layer length density'],
            'DNS_RT_12':['YES','m m^-3','layer-12 root layer length density'],
            'DNS_RT_13':['YES','m m^-3','layer-13 root layer length density'],
            'DNS_RT_14':['YES','m m^-3','layer-14 root layer length density'],
            'DNS_RT_15':['YES','m m^-3','layer-15 root layer length density'],
            'C_BALANCE':['YES','g m^-2','total plant C balance'],
            'STG_DEAD_C':['YES','g m^-2','standing dead C'],
            'FIRE_CO2':['YES','g m^-2','plant CO2 emission from fire'],
            'FIRE_CH4':['YES','g m^-2','plant CH4 emission from fire'],
            'NPP':['YES','g m^-2','total net primary productivity'],
            'CAN_HT':['YES','m','canopy height'],
            'POPN':['YES','m^-2','plant population']}

        self.daily_water={'PRECN':['YES','mm','total precipitation'],
            'ET':['YES','mm','total evaporation'],
            'RUNOFF':['YES','mm','total surface runoff'],
            'WATER':['YES','mm','total soil water content'],
            'DISCHG':['YES','mm','total subsurface water flux'],
            'SNOWPACK':['YES','mm','snowpack depth'],
            'WTR_1':['YES','m^3 m^-3','layer-1 volumetric soil micropore water'],
            'WTR_2':['YES','m^3 m^-3','layer-2 volumetric soil micropore water'],
            'WTR_3':['YES','m^3 m^-3','layer-3 volumetric soil micropore water'],
            'WTR_4':['YES','m^3 m^-3','layer-4 volumetric soil micropore water'],
            'WTR_5':['YES','m^3 m^-3','layer-5 volumetric soil micropore water'],
            'WTR_6':['YES','m^3 m^-3','layer-6 volumetric soil micropore water'],
            'WTR_7':['YES','m^3 m^-3','layer-7 volumetric soil micropore water'],
            'WTR_8':['YES','m^3 m^-3','layer-8 volumetric soil micropore water'],
            'WTR_9':['YES','m^3 m^-3','layer-9 volumetric soil micropore water'],
            'WTR_10':['YES','m^3 m^-3','layer-10 volumetric soil micropore water'],
            'WTR_11':['YES','m^3 m^-3','layer-11 volumetric soil micropore water'],
            'WTR_12':['YES','m^3 m^-3','layer-12 volumetric soil micropore water'],
            'WTR_13':['YES','m^3 m^-3','layer-13 volumetric soil micropore water'],
            'SURF_WTR':['YES','m^3 m^-3','layer-0 volumetric soil micropore water'],
            'ICE_1':['YES','m^3 m^-3','layer-1 volumetric soil micropore ice'],
            'ICE_2':['YES','m^3 m^-3','layer-2 volumetric soil micropore water'],
            'ICE_3':['YES','m^3 m^-3','layer-3 volumetric soil micropore water'],
            'ICE_4':['YES','m^3 m^-3','layer-4 volumetric soil micropore water'],
            'ICE_5':['YES','m^3 m^-3','layer-5 volumetric soil micropore water'],
            'ICE_6':['YES','m^3 m^-3','layer-6 volumetric soil micropore water'],
            'ICE_7':['YES','m^3 m^-3','layer-7 volumetric soil micropore water'],
            'ICE_8':['YES','m^3 m^-3','layer-8 volumetric soil micropore water'],
            'ICE_9':['YES','m^3 m^-3','layer-9 volumetric soil micropore water'],
            'ICE_10':['YES','m^3 m^-3','layer-10 volumetric soil micropore water'],
            'ICE_11':['YES','m^3 m^-3','layer-11 volumetric soil micropore water'],
            'ICE_12':['YES','m^3 m^-3','layer-12 volumetric soil micropore water'],
            'ICE_13':['YES','m^3 m^-3','layer-13 volumetric soil micropore water'],
            'SURF_ICE':['YES','m^3 m^-3','layer-0 volumetric soil micropore water'],
            'PSI_1':['YES','MPa','layer-1 total soil water potential (mactic+osmo)'],
            'PSI_2':['YES','MPa','layer-2 total soil water potential (mactic+osmo)'],
            'PSI_3':['YES','MPa','layer-3 total soil water potential (mactic+osmo)'],
            'PSI_4':['YES','MPa','layer-4 total soil water potential (mactic+osmo)'],
            'PSI_5':['YES','MPa','layer-5 total soil water potential (mactic+osmo)'],
            'PSI_6':['YES','MPa','layer-6 total soil water potential (mactic+osmo)'],
            'PSI_7':['YES','MPa','layer-7 total soil water potential (mactic+osmo)'],
            'PSI_8':['YES','MPa','layer-8 total soil water potential (mactic+osmo)'],
            'PSI_9':['YES','MPa','layer-9 total soil water potential (mactic+osmo)'],
            'PSI_10':['YES','MPa','layer-10 total soil water potential (mactic+osmo)'],
            'PSI_11':['YES','MPa','layer-11 total soil water potential (mactic+osmo)'],
            'SEDIMENT':['YES','Mg m^-2','total sediment subsurface flux'],
            'PSI_SURF':['YES','MPa','layer-0 soil matric water potential'],
            'SURF_ELEV':['YES','m','surface elevation'],
            'ACTV_LYR':['YES','m','active layer depth'],
            'WTR_TBL':['YES','m','water table depth'],
            'TRANSPN':['YES','mm m^-2','total transpiration'],
            'WTR_STRESS':['YES','none','plant water stress indicator (0-1)'],
            'OXY_STRESS':['YES','none','plant oxygen stress']}

        self.daily_nitrogen={'RESIDUE_N':['YES','g m^-2','total litter N'],
            'HUMUS_N':['YES','g m^-2','total humus N'],
            'FERTZR_N':['YES','g m^-2','total fertilizer N amendment'],
            'NET_PL_EXCH_N':['YES','g m^-2','total litterfall N'],
            'NH4':['YES','g m^-2','total soil NH4 + NH3 content'],
            'NO3':['YES','g m^-2','total soil NO3 + NO2 content'],
            'SUR_DON+SED_FLX':['YES','g m^-2','total surface DON flux'],
            'SUB_DON_FLX':['YES','g m^-2','total subsurface DON flux'],
            'SUR_DIN_FLX':['YES','g m^-2','total surface DIN flux'],
            'SUB_DIN_FLX':['YES','g m^-2','total subsurface DIN flux'],
            'N2O_FLUX':['YES','g m^-2','total soil N2O flux'],
            'NH3_FLUX':['YES','g m^-2','total soil NH3 flux'],
            'N2_FIXN':['YES','g m^-2','total N2 fixation'],
            'MICRO_N':['YES','g m^-2','total micriobial N'],
            'NH4_1':['YES','g m^-2','layer-1 soil NH4'],
            'NH4_2':['YES','g m^-2','layer-2 soil NH4'],
            'NH4_3':['YES','g m^-2','layer-3 soil NH4'],
            'NH4_4':['YES','g m^-2','layer-4 soil NH4'],
            'NH4_5':['YES','g m^-2','layer-5 soil NH4'],
            'NH4_6':['YES','g m^-2','layer-6 soil NH4'],
            'NH4_7':['YES','g m^-2','layer-7 soil NH4'],
            'NH4_8':['YES','g m^-2','layer-8 soil NH4'],
            'NH4_9':['YES','g m^-2','layer-9 soil NH4'],
            'NH4_10':['YES','g m^-2','layer-10 soil NH4'],
            'NH4_11':['YES','g m^-2','layer-11 soil NH4'],
            'NH4_12':['YES','g m^-2','layer-12 soil NH4'],
            'NH4_13':['YES','g m^-2','layer-13 soil NH4'],
            'NH4_14':['YES','g m^-2','layer-14 soil NH4'],
            'NH4_15':['YES','g m^-2','layer-15 soil NH4'],
            'NO3_1':['YES','g m^-2','layer-1 soil NO3(-)+NO2(-)'],
            'NO3_2':['YES','g m^-2','layer-2 soil NO3(-)+NO2(-)'],
            'NO3_3':['YES','g m^-2','layer-3 soil NO3(-)+NO2(-)'],
            'NO3_4':['YES','g m^-2','layer-4 soil NO3(-)+NO2(-)'],
            'NO3_5':['YES','g m^-2','layer-5 soil NO3(-)+NO2(-)'],
            'NO3_6':['YES','g m^-2','layer-6 soil NO3(-)+NO2(-)'],
            'NO3_7':['YES','g m^-2','layer-7 soil NO3(-)+NO2(-)'],
            'NO3_8':['YES','g m^-2','layer-8 soil NO3(-)+NO2(-)'],
            'NO3_9':['YES','g m^-2','layer-9 soil NO3(-)+NO2(-)'],
            'NO3_10':['YES','g m^-2','layer-10 soil NO3(-)+NO2(-)'],
            'NO3_11':['YES','g m^-2','layer-11 soil NO3(-)+NO2(-)'],
            'NO3_12':['YES','g m^-2','layer-12 soil NO3(-)+NO2(-)'],
            'NO3_13':['YES','g m^-2','layer-13 soil NO3(-)+NO2(-)'],
            'NO3_14':['YES','g m^-2','layer-14 soil NO3(-)+NO2(-)'],
            'NO3_15':['YES','g m^-2','layer-15 soil NO3(-)+NO2(-)'],
            'NH4_RES':['YES','g m^-2','layer-0 soil NH4'],
            'NO3_RES':['YES','g m^-2','layer-0 soil NO3(-)+NO2(-)'],
            'ECO_HVST_N':['YES','g m^-2','ecosystem harvest N'],
            'NET_N_MIN':['YES','g m^-2','net N mineralization'],
            'FIRE_N':['YES','g m^-2','total NH3 flux from fire'],
            'N2_FLUX':['YES','g m^-2','total soil N2 flux'],
            'SHOOT_N':['YES','g m^-2','canopy  N'],
            'LEAF_N':['YES','g m^-2','canopy leaf N'],
            'SHTH_N':['YES','g m^-2','canopy sheath N'],
            'STALK_N':['YES','g m^-2','canopy stalk N'],
            'RESERVE_N':['YES','g m^-2','canopy reserve N'],
            'HUSK_N':['YES','g m^-2','husk nitrogen'],
            'GRAIN_N':['YES','g m^-2','canopy grain N'],
            'ROOT_N':['YES','g m^-2','total root N '],
            'NDL_N':['YES','g m^-2','total nodule N'],
            'STORED_N':['YES','g m^-2','plant stored nonstructural N'],
            'UPTK_N':['YES','g m^-2','total net root N uptake (+ve) - exudation (-ve)'],
            'LITTER_N':['YES','g m^-2','total plant N litterfall '],
            'TL_N_FIXED':['YES','g m^-2','total plant N2 fixation'],
            '[SOL_N]':['YES','g g^-1','canopy nonstructural N concentration'],
            'N_STRESS':['YES','g g^-1','canopy NC ratio'],
            '[SOL_P]':['YES','g g^-1','canopy nonstructural P concentration'],
            'P_STRESS':['YES','g g^-1','canopy PC ratio'],
            'NH3_FLUX':['YES','g m^-2','total canopy NH3 flux'],
            'HVST_N':['YES','g m^-2','ecosystem harvest N'],
            'N_BALANCE':['YES','g m^-2','plant N balance'],
            'STG_DEAD_N':['YES','g m^-2','standing dead N '],
            'FIRE_N':['YES','g m^-2','plant NH3 emission from fire'],
            'SF_LIT_N':['YES','g m^-2','total surface litterfall N']}

        self.daily_phosp={'RESIDUE_P':['YES','g m^-2','total litter P'],
            'HUMUS_P':['YES','g m^-2','total humus P'],
            'FERTZR_P':['YES','g m^-2','total fertilizer P amendment'],
            'NET_PL_EXCH_P':['YES','g m^-2','total litterfall P'],
            'EXCH_PO4':['YES','g m^-2','total soil PO4 content'],
            'SUR_DOP+SED_FLX':['YES','g m^-2','total surface DOP flux'],
            'SUB_DOP_FLX':['YES','g m^-2','total subsurface DOP flux'],
            'SUR_DIP_FLX':['YES','g m^-2','total surface DIP flux'],
            'SUB_DIP_FLX':['YES','g m^-2','total subsurface DIP flux'],
            'PRECIP_P':['YES','g m^-2','total soil precipited P'],
            'MICRO_P':['YES','g m^-2','total micriobial P'],
            'FIRE_P':['YES','g m^-2','total PO4 flux from fire'],
            'PO4_1':['YES','g m^-2','layer-1 soil PO4 content'],
            'PO4_2':['YES','g m^-2','layer-2 soil PO4 content'],
            'PO4_3':['YES','g m^-2','layer-3 soil PO4 content'],
            'PO4_4':['YES','g m^-2','layer-4 soil PO4 content'],
            'PO4_5':['YES','g m^-2','layer-5 soil PO4 content'],
            'PO4_6':['YES','g m^-2','layer-6 soil PO4 content'],
            'PO4_7':['YES','g m^-2','layer-7 soil PO4 content'],
            'PO4_8':['YES','g m^-2','layer-8 soil PO4 content'],
            'PO4_9':['YES','g m^-2','layer-9 soil PO4 content'],
            'PO4_10':['YES','g m^-2','layer-10 soil PO4 content'],
            'PO4_11':['YES','g m^-2','layer-11 soil PO4 content'],
            'PO4_12':['YES','g m^-2','layer-12 soil PO4 content'],
            'PO4_13':['YES','g m^-2','layer-13 soil PO4 content'],
            'PO4_14':['YES','g m^-2','layer-14 soil PO4 content'],
            'PO4_15':['YES','g m^-2','layer-15 soil PO4 content'],
            'EXCH_P_1':['YES','g g soil^-1','layer-1 exchangeable soil PO4 content'],
            'EXCH_P_2':['YES','g g soil^-1','layer-2 exchangeable soil PO4 content'],
            'EXCH_P_3':['YES','g g soil^-1','layer-3 exchangeable soil PO4 content'],
            'EXCH_P_4':['YES','g g soil^-1','layer-4 exchangeable soil PO4 content'],
            'EXCH_P_5':['YES','g g soil^-1','layer-5 exchangeable soil PO4 content'],
            'EXCH_P_6':['YES','g g soil^-1','layer-6 exchangeable soil PO4 content'],
            'EXCH_P_7':['YES','g g soil^-1','layer-7 exchangeable soil PO4 content'],
            'EXCH_P_8':['YES','g g soil^-1','layer-8 exchangeable soil PO4 content'],
            'EXCH_P_9':['YES','g g soil^-1','layer-9 exchangeable soil PO4 content'],
            'EXCH_P_10':['YES','g g soil^-1','layer-10 exchangeable soil PO4 content'],
            'EXCH_P_11':['YES','g g soil^-1','layer-11 exchangeable soil PO4 content'],
            'EXCH_P_12':['YES','g g soil^-1','layer-12 exchangeable soil PO4 content'],
            'EXCH_P_13':['YES','g g soil^-1','layer-13 exchangeable soil PO4 content'],
            'EXCH_P_14':['YES','g g soil^-1','layer-14 exchangeable soil PO4 content'],
            'EXCH_P_15':['YES','g g soil^-1','layer-15 exchangeable soil PO4 content'],
            'PO4_RES':['YES','g g residue^-1','PO4 concentration in surface residual'],
            'EXCH_P_RES':['YES','g g soil^-1','layer-0 exchangeable soil PO4 content'],
            'ECO_HVST_P':['YES','g m^-2','ecosystem harvest P'],
            'NET_P_MIN':['YES','g m^-2','net P mineralization'],
            'SHOOT_P':['YES','g m^-2','canopy total P'],
            'LEAF_P':['YES','g m^-2','canopy leaf P'],
            'SHTH_P':['YES','g m^-2','canopy sheath P'],
            'STALK_P':['YES','g m^-2','canopy stalk P'],
            'RESERVE_P':['YES','g m^-2','canopy reserve P'],
            'HUSK_P':['YES','g m^-2','husk P'],
            'GRAIN_P':['YES','g m^-2','canopy grain P'],
            'ROOT_P':['YES','g m^-2','root total P'],
            'NDL_P':['YES','g m^-2','total nodule P'],
            'STORED_P':['YES','g m^-2','plant stored nonstructural P'],
            'UPTK_P':['YES','g m^-2','total net root P uptake (+ve) - exudation (-ve)'],
            'LITTER_P':['YES','g m^-2','total plant P litterfall '],
            '[SOL_P]':['YES','g g^-1','canopy nonstructural P concentration'],
            'P_STRESS':['YES','none','plant P stress (PC ratio)'],
            'HVST_P':['YES','g m^-2','plant P harvest'],
            'P_BALANCE':['YES','g m^-2','total plant P balance'],
            'STG_DEAD_P':['YES','g m^-2','standing dead P '],
            'FIRE_P':['YES','g m^-2','plant PO4 emission from fire'],
            'SF_LIT_P':['YES','g m^-2','total surface litterfall P']}

        self.daily_heat={'RADN':['YES','MJ d^-1','total daily solar radiation'],
            'TMAX_AIR':['YES','^oC','daily maximum air temperature '],
            'TMIN_AIR':['YES','^oC','daily minimum air temperature '],
            'HMAX_AIR':['YES','kPa','daily maximum vapor pressure '],
            'HMIN_AIR':['YES','kPa','daily minimum vapor pressure '],
            'WIND':['YES','km d^-1','total daily wind travel'],
            'PRECN':['YES','m d^-1','total daily precipitation'],
            'TMAX_SOIL_1':['YES','^oC','layer-1 daily maximum soil temperature'],
            'TMIN_SOIL_1':['YES','^oC','layer-1 daily minimum soil temperature'],
            'TMAX_SOIL_2':['YES','^oC','layer-2 daily maximum soil temperature'],
            'TMIN_SOIL_2':['YES','^oC','layer-2 daily minimum soil temperature'],
            'TMAX_SOIL_3':['YES','^oC','layer-3 daily maximum soil temperature'],
            'TMIN_SOIL_3':['YES','^oC','layer-3 daily minimum soil temperature'],
            'TMAX_SOIL_4':['YES','^oC','layer-4 daily maximum soil temperature'],
            'TMIN_SOIL_4':['YES','^oC','layer-4 daily minimum soil temperature'],
            'TMAX_SOIL_5':['YES','^oC','layer-5 daily maximum soil temperature'],
            'TMIN_SOIL_5':['YES','^oC','layer-5 daily minimum soil temperature'],
            'TMAX_SOIL_6':['YES','^oC','layer-6 daily maximum soil temperature'],
            'TMIN_SOIL_6':['YES','^oC','layer-6 daily minimum soil temperature'],
            'TMAX_SOIL_7':['YES','^oC','layer-7 daily maximum soil temperature'],
            'TMIN_SOIL_7':['YES','^oC','layer-7 daily minimum soil temperature'],
            'TMAX_SOIL_8':['YES','^oC','layer-8 daily maximum soil temperature'],
            'TMIN_SOIL_8':['YES','^oC','layer-8 daily minimum soil temperature'],
            'TMAX_SOIL_9':['YES','^oC','layer-9 daily maximum soil temperature'],
            'TMIN_SOIL_9':['YES','^oC','layer-9 daily minimum soil temperature'],
            'TMAX_SOIL_10':['YES','^oC','layer-10 daily maximum soil temperature'],
            'TMIN_SOIL_10':['YES','^oC','layer-10 daily minimum soil temperature'],
            'TMAX_SOIL_11':['YES','^oC','layer-11 daily maximum soil temperature'],
            'TMIN_SOIL_11':['YES','^oC','layer-11 daily minimum soil temperature'],
            'TMAX_SOIL_12':['YES','^oC','layer-12 daily maximum soil temperature'],
            'TMIN_SOIL_12':['YES','^oC','layer-12 daily minimum soil temperature'],
            'TMAX_SOIL_13':['YES','^oC','layer-13 daily maximum soil temperature'],
            'TMIN_SOIL_13':['YES','^oC','layer-13 daily minimum soil temperature'],
            'TMAX_SOIL_14':['YES','^oC','layer-14 daily maximum soil temperature'],
            'TMIN_SOIL_14':['YES','^oC','layer-14 daily minimum soil temperature'],
            'TMAX_LITTER':['YES','^oC','layer-0 daily maximum soil temperature'],
            'TMIN_LITTER':['YES','^oC','layer-0 daily minimum soil temperature'],
            'ECND_1':['YES','dS m^-1','layer-1 daily mean electrical conductivity'],
            'ECND_2':['YES','dS m^-1','layer-2 daily mean electrical conductivity'],
            'ECND_3':['YES','dS m^-1','layer-3 daily mean electrical conductivity'],
            'ECND_4':['YES','dS m^-1','layer-4 daily mean electrical conductivity'],
            'ECND_5':['YES','dS m^-1','layer-5 daily mean electrical conductivity'],
            'ECND_6':['YES','dS m^-1','layer-6 daily mean electrical conductivity'],
            'ECND_7':['YES','dS m^-1','layer-7 daily mean electrical conductivity'],
            'ECND_8':['YES','dS m^-1','layer-8 daily mean electrical conductivity'],
            'ECND_9':['YES','dS m^-1','layer-9 daily mean electrical conductivity'],
            'ECND_10':['YES','dS m^-1','layer-10 daily mean electrical conductivity'],
            'ECND_11':['YES','dS m^-1','layer-11 daily mean electrical conductivity'],
            'ECND_12':['YES','dS m^-1','layer-12 daily mean electrical conductivity'],
            'TTL_SALT_DISCHG':['YES','mol m^-2','total subsurface ion flux'],
            'GROWTH_STG':['YES','','current growth stage'],
            'BRANCH_NO.':['YES','','branch number'],
            'NODE_NO.':['YES','','leaf number'],
            'RUB_ACTVN':['YES','','branch down-regulation of CO2 fixation'],
            'LEAF_N/C':['YES','','leaf C to N ratio'],
            'LEAF_P/C':['YES','','leaf P to C ratio'],
            'MIN_LWP':['YES','MPa','minimum daily canopy water potential'],
            'O2_STRESS':['YES','','plant O2 stress indicator'],
            'TEMP_STRESS':['YES','none','canopy temperature growth functiom']}

    def disp(self):
        """
        display the list of variables for history output
        """
        print("hourly carbon variables")
        for key,value in self.hourly_carbon.items():
            print(key)
        print("hourly water variables")
        for key,value in self.hourly_water.items():
            print(key)
        print("hourly nitrogen variables")
        for key,value in self.hourly_nitrogen.items():
            print(key)
        print("hourly phosphorus variables")
        for key,value in self.hourly_phosp.items():
            print(key)
        print("hourly heat variables")
        for key,value in self.hourly_heat.items():
            print(key)

        print("daily carbon variables")
        for key,value in self.daily_carbon.items():
            print(key)
        print("daily water variables")
        for key,value in self.daily_water.items():
            print(key)
        print("daily nitrogen variables")
        for key,value in self.daily_nitrogen.items():
            print(key)
        print("daily phosphorus variables")
        for key,value in self.daily_phosp.items():
            print(key)
        print("daily heat variables")
        for key,value in self.daily_heat.items():
            print(key)

hist=histlist()

hist.disp()
