module HistIdTypeMod
!
! this module is an intermediate step to support ascii output
! when output is done with netcdf, no id is needed.
implicit none

  type, public :: histid_type
  integer :: id_CAN_CO2_FLUX !'CAN_CO2_FLUX'
  integer :: id_CAN_GPP      !'CAN_GPP'
  integer :: id_CAN_RA       !'CAN_RA'
  integer :: id_cTNC         !'[TNC]'
  integer :: id_STOML_RSC    !'STOML_RSC'
  integer :: id_BLYR_RSC     !'BLYR_RSC'
  integer :: id_CAN_CO2      !'CAN_CO2'
  integer :: id_LAI          !'LAI'
  integer :: id_PSI_CAN      !'PSI_CAN'
  integer :: id_TURG_CAN     !'TURG_CAN'
  integer :: id_STOM_RSC     !'STOM_RSC'
  integer :: id_BLYR_RSC     !'BLYR_RSC'
  integer :: id_TRANSPN      !'TRANSPN'
  integer :: id_O2_STRESS    !'O2_STRESS'
  integer :: id_PSI_RT_1     !'PSI_RT_1'
  integer :: id_PSI_RT_2     !'PSI_RT_2'
  integer :: id_PSI_RT_3     !'PSI_RT_3'
  integer :: id_PSI_RT_4     !'PSI_RT_4'
  integer :: id_PSI_RT_5     !'PSI_RT_5'
  integer :: id_PSI_RT_6     !'PSI_RT_6'
  integer :: id_PSI_RT_7     !'PSI_RT_7'
  integer :: id_PSI_RT_6     !'PSI_RT_8'
  integer :: id_PSI_RT_7     !'PSI_RT_9'
  integer :: id_PSI_RT_9     !'PSI_RT_10'
  integer :: id_PSI_RT_10    !'PSI_RT_11'
  integer :: id_PSI_RT_11    !'PSI_RT_12'
  integer :: id_PSI_RT_12    !'PSI_RT_13'
  integer :: id_PSI_RT_13    !'PSI_RT_13'
  integer :: id_PSI_RT_14    !'PSI_RT_14'
  integer :: id_PSI_RT_15    !'PSI_RT_15'

  integer :: id_NH4_UPTK     !'NH4_UPTK'
  integer :: id_NO3_UPTK     !'NO3_UPTK'
  integer :: id_N2_FIXN      !'N2_FIXN'
  integer :: id_cTNN         !'[TNN]'
  integer :: id_NH3_FLUX     !'NH3_FLUX'
  integer :: id_UP_NH4_1     !'UP_NH4_1'
  integer :: id_UP_NH4_2     !'UP_NH4_2'
  integer :: id_UP_NH4_3     !'UP_NH4_3'
  integer :: id_UP_NH4_4     !'UP_NH4_4'
  integer :: id_UP_NH4_5     !'UP_NH4_5'
  integer :: id_UP_NH4_6     !'UP_NH4_6'
  integer :: id_UP_NH4_7     !'UP_NH4_7'
  integer :: id_UP_NH4_8     !'UP_NH4_8'
  integer :: id_UP_NH4_9     !'UP_NH4_9'
  integer :: id_UP_NH4_10    !'UP_NH4_10'
  integer :: id_UP_NH4_11    !'UP_NH4_11'
  integer :: id_UP_NH4_12    !'UP_NH4_12'
  integer :: id_UP_NH4_13    !'UP_NH4_13'
  integer :: id_UP_NH4_14    !'UP_NH4_14'
  integer :: id_UP_NH4_15    !'UP_NH4_15'
  integer :: id_UP_NO3_1     !'UP_NO3_1'
  integer :: id_UP_NO3_2     !'UP_NO3_2'
  integer :: id_UP_NO3_3     !'UP_NO3_3'
  integer :: id_UP_NO3_4     !'UP_NO3_4'
  integer :: id_UP_NO3_5     !'UP_NO3_5'
  integer :: id_UP_NO3_6     !'UP_NO3_6'
  integer :: id_UP_NO3_7     !'UP_NO3_7'
  integer :: id_UP_NO3_8     !'UP_NO3_8'
  integer :: id_UP_NO3_9     !'UP_NO3_9'
  integer :: id_UP_NO3_10    !'UP_NO3_10'
  integer :: id_UP_NO3_11    !'UP_NO3_11'
  integer :: id_UP_NO3_12    !'UP_NO3_12'
  integer :: id_UP_NO3_13    !'UP_NO3_13'
  integer :: id_UP_NO3_14    !'UP_NO3_14'
  integer :: id_UP_NO3_15    !'UP_NO3_15'

  integer :: id_PO4_UPTK     !'PO4_UPTK'
  integer :: id_cTNP         !'[TNP]'
  integer :: id_UP_PO4_1     !'UP_PO4_1'
  integer :: id_UP_PO4_2     !'UP_PO4_2'
  integer :: id_UP_PO4_3     !'UP_PO4_3'
  integer :: id_UP_PO4_4     !'UP_PO4_4'
  integer :: id_UP_PO4_5     !'UP_PO4_5'
  integer :: id_UP_PO4_6     !'UP_PO4_6'
  integer :: id_UP_PO4_7     !'UP_PO4_7'
  integer :: id_UP_PO4_8     !'UP_PO4_8'
  integer :: id_UP_PO4_9     !'UP_PO4_9'
  integer :: id_UP_PO4_10    !'UP_PO4_10'
  integer :: id_UP_PO4_11    !'UP_PO4_11'
  integer :: id_UP_PO4_12    !'UP_PO4_12'
  integer :: id_UP_PO4_13    !'UP_PO4_13'
  integer :: id_UP_PO4_14    !'UP_PO4_14'
  integer :: id_UP_PO4_15    !'UP_PO4_15'

  integer :: id_CAN_RN       !'CAN_RN'
  integer :: id_CAN_LE       !'CAN_LE'
  integer :: id_CAN_H        !'CAN_H'
  integer :: id_CAN_G        !'CAN_G'
  integer :: id_CAN_TEMP     !'CAN_TEMP'
  integer :: id_TEMP_FN      !'TEMP_FN'

  integer :: id_SHOOT_C      !'SHOOT_C'
  integer :: id_LEAF_C       !'LEAF_C'
  integer :: id_SHTH_C       !'SHTH_C'
  integer :: id_STALK_C      !'STALK_C'
  integer :: id_RESERVE_C    !'RESERVE_C'
  integer :: id_REPRO_C      !'REPRO_C'
  integer :: id_GRAIN_C      !'GRAIN_C'
  integer :: id_ROOT_C       !'ROOT_C'
  integer :: id_NDL_C        !'NDL_C'
  integer :: id_STORED_C     !'STORED_C'
  integer :: id_GRAIN_NO     !'GRAIN_NO.'
  integer :: id_LAI          !'LAI'
  integer :: id_GPP          !'GPP'
  integer :: id_EXUD_C       !'EXUD_C'
  integer :: id_LITTER_C     !'LITTER_C'
  integer :: id_SF_LIT_C     !'SF_LIT_C'
  integer :: id_AUTO_RESP    !'AUTO_RESP'
  integer :: id_ABV_GRD_RESP !'ABV_GRD_RESP'
  integer :: id_cSOL_C       !'[SOL._C]'
  integer :: id_HVST_C       !'HVST_C'
  integer :: id_DNS_RT_1     !'DNS_RT_1'

            IF(L.EQ.72)HEAD(M)='DNS_RT_2'
            IF(L.EQ.73)HEAD(M)='DNS_RT_3'
            IF(L.EQ.74)HEAD(M)='DNS_RT_4'
            IF(L.EQ.75)HEAD(M)='DNS_RT_5'
            IF(L.EQ.76)HEAD(M)='DNS_RT_6'
            IF(L.EQ.77)HEAD(M)='DNS_RT_7'
            IF(L.EQ.78)HEAD(M)='DNS_RT_8'
            IF(L.EQ.79)HEAD(M)='DNS_RT_9'
            IF(L.EQ.80)HEAD(M)='DNS_RT_10'
            IF(L.EQ.81)HEAD(M)='DNS_RT_11'
            IF(L.EQ.82)HEAD(M)='DNS_RT_12'
            IF(L.EQ.83)HEAD(M)='DNS_RT_13'
            IF(L.EQ.84)HEAD(M)='DNS_RT_14'
            IF(L.EQ.85)HEAD(M)='DNS_RT_15'
            IF(L.EQ.86)HEAD(M)='C_BALANCE'
            IF(L.EQ.87)HEAD(M)='STG_DEAD_C'
            IF(L.EQ.88)HEAD(M)='FIRE_CO2'
            IF(L.EQ.89)HEAD(M)='FIRE_CH4'
            IF(L.EQ.90)HEAD(M)='NPP'
            IF(L.EQ.91)HEAD(M)='CAN_HT'
            IF(L.EQ.92)HEAD(M)='POPN'


  end type histid_type
end module HistIdTypeMod
