module HistDataType
  ! Public history state and interfaces. Implementations in sibling submodules
  ! compile independently; process-state dependencies belong to those files.
  use data_kind_mod, only: r8 => DAT_KIND_R8
  use GridConsts, only: bounds_type
  implicit none
  private

  type, public :: histdata_type

  real(r8), pointer :: h1d_TEMP60cm_col(:) 
  real(r8), pointer :: h1d_THETW60cm_col(:)
  real(r8), pointer :: h1d_O2wConc60cm_col(:) 
  real(r8), pointer :: h1d_AcetConc60cm_col(:)
  real(r8), pointer :: h1d_H2wConc60cm_col(:)
  real(r8), pointer :: h1d_CH4wConc60cm_col(:)
  real(r8), pointer :: h1d_DOCConc60cm_col(:)
  real(r8), pointer :: h1d_AcetMGC60cm_col(:)
  real(r8), pointer :: h1d_H2MGC60cm_col(:)
  real(r8), pointer :: h1d_FermC60cm_col(:)
  real(r8), pointer :: h1d_AeroMOC60cm_col(:)
  real(r8), pointer :: h1d_AeroHRFungC60cm_col(:)
  real(r8), pointer :: h1d_AeroHRBactC60cm_col(:)
  real(r8), pointer :: h1d_RAeroCH4Oxi60cm_col(:)
  real(r8), pointer :: h1d_RCH4ProdAcet60cm_col(:)
  real(r8), pointer :: h1d_RCH4ProdHG60cm_col(:)
  real(r8), pointer :: h1d_RFerment60cm_col(:)
  real(r8), pointer :: h1d_RCO2Ht60cm_col(:)
  real(r8), pointer :: h1d_TEMP30cm_col(:) 
  real(r8), pointer :: h1d_THETW30cm_col(:)
  real(r8), pointer :: h1d_O2wConc30cm_col(:) 
  real(r8), pointer :: h1d_AcetConc30cm_col(:)
  real(r8), pointer :: h1d_H2wConc30cm_col(:)
  real(r8), pointer :: h1d_CH4wConc30cm_col(:)
  real(r8), pointer :: h1d_DOCConc30cm_col(:)
  real(r8), pointer :: h1d_AcetMGC30cm_col(:)
  real(r8), pointer :: h1d_H2MGC30cm_col(:)
  real(r8), pointer :: h1d_FermC30cm_col(:)
  real(r8), pointer :: h1d_AeroMOC30cm_col(:)
  real(r8), pointer :: h1d_AeroHRFungC30cm_col(:)
  real(r8), pointer :: h1d_AeroHRBactC30cm_col(:)
  real(r8), pointer :: h1d_RAeroCH4Oxi30cm_col(:)
  real(r8), pointer :: h1d_RCH4ProdAcet30cm_col(:)
  real(r8), pointer :: h1d_RCH4ProdHG30cm_col(:)
  real(r8), pointer :: h1d_RFerment30cm_col(:)
  real(r8), pointer :: h1d_RCO2Ht30cm_col(:)

  real(r8),pointer   :: h1D_cumFIRE_CO2_col(:)    
  real(r8),pointer   :: h1D_cumFIRE_CH4_col(:)    
  real(r8),pointer   :: h1D_cNH4_LITR_col(:)    
  real(r8),pointer   :: h1D_cNO3_LITR_col(:)    
  real(r8),pointer   :: h1D_ECO_HVST_N_col(:)   
  real(r8),pointer   :: h1D_NET_N_MIN_col(:)    
  real(r8),pointer   :: h1D_tLITR_P_col(:)   
  real(r8),pointer   :: h1D_HUMUS_C_col(:)   
  real(r8),pointer   :: h1D_HUMUS_N_col(:)   
  real(r8),pointer   :: h1D_HUMUS_P_col(:)   
  real(r8),pointer   :: h1D_AMENDED_P_col(:)    
  real(r8),pointer   :: h1D_tLITRf_P_FLX_col(:) 
  real(r8),pointer   :: h1D_tEXCH_PO4_col(:)    
  real(r8),pointer   :: h1D_SUR_DOP_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DOP_FLX_col(:)  
  real(r8),pointer   :: h1D_SUR_DIP_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DIP_FLX_col(:)  
  real(r8),pointer   :: h1D_HeatFlx2Grnd_col(:)  
  real(r8),pointer   :: h1D_CumDryDepoOM_col(:)
  real(r8),pointer   :: h1D_cyanoBactC_col(:)
  real(r8),pointer   :: h1D_RadSW_Grnd_col(:)  
  real(r8),pointer   :: h1D_RadPAR_Grnd_col(:)
  real(r8),pointer   :: h1D_RadPAR2Soil_col(:)
  real(r8),pointer   :: h1D_RadPAR2LitR_col(:)
  real(r8),pointer   :: h1D_Qinfl2soi_col(:)   
  real(r8),pointer   :: h1D_QTRANSP_col(:)
  real(r8),pointer   :: h1D_Qdrain_col(:)            
  real(r8),pointer   :: h1D_tPREC_P_col(:)     
  real(r8),pointer   :: h1D_SnowCanopy_col(:)
  real(r8),pointer   :: h1D_fSnowCan_ptc(:)
  real(r8),pointer   :: h1D_PTSHTR_ptc(:)
  real(r8),pointer   :: h1D_tMICRO_P_col(:)    
  real(r8),pointer   :: h1D_tSoilOrgC_col(:)
  real(r8),pointer   :: h1D_tSoilOrgN_col(:)
  real(r8),pointer   :: h1D_tSoilOrgP_col(:)
  real(r8),pointer   :: h1D_PO4_FIRE_col(:)    
  real(r8),pointer   :: h1D_cPO4_LITR_col(:)    
  real(r8),pointer   :: h1D_cEXCH_P_LITR_col(:) 
  real(r8),pointer   :: h1D_ECO_HVST_P_col(:)   
  real(r8),pointer   :: h1D_NET_P_MIN_col(:)    
  real(r8),pointer   :: h1D_tSALT_DISCHG_FLX_col(:) 
  real(r8),pointer   :: h1D_PSI_SURF_col(:)     
  real(r8),pointer   :: h1D_SURF_ELEV_col(:)    
  real(r8),pointer   :: h1D_tLITR_N_col(:)      
  real(r8),pointer   :: h2D_RootAR_vr(:,:)      
  real(r8),pointer   :: h2D_PAR_RAD_vr(:,:)
  real(r8),pointer   :: h1D_RootAR_col(:)  
  real(r8),pointer   :: h1D_RootAR_ptc(:)
  real(r8),pointer   :: h1D_RootLenPerPlant_ptc(:)
  real(r8),pointer   :: h1D_RootCO2Relez_col(:)     
  real(r8),pointer   :: h2D_BotDEPZ_vr(:,:)
  real(r8),pointer   :: h1D_tRAD_col(:)
  real(r8),pointer   :: h1D_AMENDED_N_col(:)    
  real(r8),pointer   :: h1D_tLITRf_N_FLX_col(:) 
  real(r8),pointer   :: h1D_tLITRf_C_FLX_col(:) 
  real(r8),pointer   :: h1D_tNH4X_col(:)        
  real(r8),pointer   :: h1D_tNO3_col(:)         
  real(r8),pointer   :: h1D_SUR_DON_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DON_FLX_col(:)  
  real(r8),pointer   :: h1D_SUR_DIN_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DIN_FLX_col(:)  
  real(r8),pointer   :: h1D_tMICRO_N_col(:)     
  real(r8),pointer   :: h1D_TEMP_LITR_col(:)    
  real(r8),pointer   :: h1D_TEMP_surf_col(:)
  real(r8),pointer   :: h1D_TEMP_SNOW_col(:)    
  real(r8),pointer   :: h1D_FracBySnow_col(:)   
  real(r8),pointer   :: h1D_FracByLitr_col(:)   
  real(r8),pointer   :: h1D_tLITR_C_col(:)      
  real(r8),pointer   :: h1D_AMENDED_C_col(:)    
  real(r8),pointer   :: h1D_tMICRO_C_col(:)     
  real(r8),pointer   :: h1D_OMC_LITR_col(:)     
  real(r8),pointer   :: h1D_OMN_LITR_col(:)     
  real(r8),pointer   :: h1D_OMP_LITR_col(:)     
  real(r8),pointer   :: h1D_SUR_DOC_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DOC_FLX_col(:)  
  real(r8),pointer   :: h1D_SUR_DIC_FLX_col(:)  
  real(r8),pointer   :: h1D_SUB_DIC_FLX_col(:)  
  real(r8),pointer   :: h1D_ATM_CO2_col(:)      
  real(r8),pointer   :: h1D_ATM_CH4_col(:)      
  real(r8),pointer   :: h1D_NBP_col(:)          
  real(r8),pointer   :: h1D_CanSWRad_col(:)
  real(r8),pointer   :: h1D_ECO_HVST_C_col(:)  
  real(r8),pointer   :: h1D_ECO_LAI_col(:)
  real(r8),pointer   :: h1D_ECO_SAI_col(:)
  real(r8),pointer   :: h1D_Eco_GPP_CumYr_col(:)   
  real(r8),pointer   :: h1D_ECO_RA_col(:)        
  real(r8),pointer   :: h1D_Eco_NPP_CumYr_col(:) 
  real(r8),pointer   :: h1D_Eco_HR_CumYr_col(:)  
  real(r8),pointer   :: h1D_Eco_HR_CO2_col(:)   
  real(r8),pointer   :: h1D_Eco_HR_CO2_litr_col(:)   
  real(r8),pointer   :: h2D_Eco_HR_CO2_vr(:,:)   
  real(r8),pointer   :: h2D_Gchem_CO2_prod_vr(:,:)
  real(r8),pointer   :: h1D_tDIC_col(:)       
  real(r8),pointer   :: h1D_tSTANDING_DEAD_C_col(:)  
  real(r8),pointer   :: h1D_tSTANDING_DEAD_N_col(:)  
  real(r8),pointer   :: h1D_tSTANDING_DEAD_P_col(:)  
  real(r8),pointer   :: h1D_tPRECIP_col(:)        
  real(r8),pointer   :: h1D_ECO_ET_col(:)         
  real(r8),pointer   :: h1D_trcg_Ar_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_CO2_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_CH4_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_O2_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_N2_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_NH3_cumerr_col(:)
  real(r8),pointer   :: h1D_trcg_H2_cumerr_col(:)
  real(r8),pointer   :: h1D_ECO_RADSW_col(:)
  real(r8),pointer   :: h1d_CAN_NEE_col(:)
  real(r8),pointer   :: h1D_N2O_LITR_col(:)     
  real(r8),pointer   :: h1D_NH3_LITR_col(:)     
  real(r8),pointer   :: h1D_SOL_RADN_col(:)     
  real(r8),pointer   :: h1D_AIR_TEMP_col(:)     
  real(r8),pointer   :: h1D_FreeNFix_col(:)
  real(r8),pointer   :: h1D_PATM_col(:)         
  real(r8),pointer   :: h1D_HUM_col(:)          
  real(r8),pointer   :: h1D_WIND_col(:)         
  real(r8),pointer   :: h1D_Snofall_col(:)
  real(r8),pointer   :: h1D_PREC_col(:)   
  real(r8),pointer   :: h1D_LWSky_col(:)
  real(r8),pointer   :: h1D_SOIL_RN_col(:)      
  real(r8),pointer   :: h1D_SOIL_LE_col(:)      
  real(r8),pointer   :: h1D_SOIL_H_col(:)       
  real(r8),pointer   :: h1D_SOIL_G_col(:)       
  real(r8),pointer   :: h1D_ECO_RN_col(:)       
  real(r8),pointer   :: h1D_ECO_LE_col(:)       
  real(r8),pointer   :: h1D_Eco_HeatSen_col(:)  
  real(r8),pointer   :: h1D_ECO_Heat2G_col(:)   
  real(r8),pointer   :: h1D_O2_LITR_col(:)      
  real(r8),pointer   :: h1D_MIN_LWP_ptc(:)      
  real(r8),pointer   :: h1D_AR_SEMIS_FLX_col(:)   
  real(r8),pointer   :: h1D_CO2_SEMIS_FLX_col(:)  
  real(r8),pointer   :: h1D_ECO_CO2_FLX_col(:)  
  real(r8),pointer   :: h1D_CH4_SEMIS_FLX_col(:)
  real(r8),pointer   :: h1D_CH4_EBU_flx_col(:)
  real(r8),pointer   :: h1D_Ar_EBU_flx_col(:)
  real(r8),pointer   :: h1D_CO2_TPR_err_col(:)
  real(r8),pointer   :: h1D_CO2_Drain_flx_col(:)
  real(r8),pointer   :: h1D_NO3_hydloss_flx_col(:)
  real(r8),pointer   :: h1D_NH3_hydloss_flx_col(:)
  real(r8),pointer   :: h1D_CO2_hydloss_flx_col(:)
  real(r8),pointer   :: h1D_Ar_TPR_err_col(:)
  real(r8),pointer   :: h1D_AR_PLTROOT_flx_col(:)  
  real(r8),pointer   :: h1D_CH4_PLTROOT_flx_col(:)
  real(r8),pointer   :: h1D_CO2_PLTROOT_flx_col(:)
  real(r8),pointer   :: h1D_O2_PLTROOT_flx_col(:)
  real(r8),pointer   :: h1D_VPQ_col(:)
  real(r8),pointer   :: h1D_TKQ_col(:)
  real(r8),pointer   :: h1D_CO2_DIF_flx_col(:)
  real(r8),pointer   :: h1D_O2_DIF_flx_col(:)  
  real(r8),pointer   :: h1D_Ar_DIF_flx_col(:)
  real(r8),pointer   :: h1D_RoughnessLength_col(:)
  real(r8),pointer   :: h1D_ZeroPlaneDisplacem_col(:)
  real(r8),pointer   :: h1D_CH4_DIF_flx_col(:)
  real(r8),pointer   :: h1D_NH3_DIF_flx_col(:)
  real(r8),pointer   :: h1D_Ar_soilMass_col(:)
  real(r8),pointer   :: h1D_O2_SEMIS_FLX_col(:)  
  real(r8),pointer   :: h1D_CO2_LITR_col(:)      
  real(r8),pointer   :: h1D_EVAPG_col(:)         
  real(r8),pointer   :: h1D_CANET_col(:)         
  real(r8),pointer   :: h1D_CanopyEvap_col(:)
  real(r8),pointer   :: h1D_RUNOFF_FLX_col(:)    
  real(r8),pointer   :: h1D_SEDIMENT_FLX_col(:)  
  real(r8),pointer   :: h1D_tSWC_col(:)       
  real(r8),pointer   :: h1D_tHeat_col(:) 
  real(r8),pointer   :: h1D_QDISCHG_FLX_col(:)  
  real(r8),pointer   :: h1D_HeatDISCHG_FLX_col(:)
  real(r8),pointer   :: h1D_SNOWPACK_col(:)    
  real(r8),pointer   :: h1D_SNOWDENS_col(:) 
  real(r8),pointer   :: h1D_SURF_WTR_col(:)     
  real(r8),pointer   :: h1D_ThetaW_litr_col(:)  
  real(r8),pointer   :: h1D_ThetaI_litr_col(:)    
  real(r8),pointer   :: h1D_SURF_ICE_col(:)     
  real(r8),pointer   :: h1D_ACTV_LYR_col(:)     
  real(r8),pointer   :: h1D_WTR_TBL_col(:)      
  real(r8),pointer   :: h1D_CO2_WetDep_FLX_col(:)
  real(r8),pointer   :: h1D_RootN_Fix_col(:)
  real(r8),pointer   :: h1D_AR_WetDep_FLX_col(:)
  real(r8),pointer   :: h1D_NWetDep_flx_col(:)
  real(r8),pointer   :: h1D_RootXO2_flx_col(:)
  real(r8),pointer   :: h1D_N2O_SEMIS_FLX_col(:)     
  real(r8),pointer   :: h1D_N2_SEMIS_FLX_col(:)      
  real(r8),pointer   :: h1D_NH3_SEMIS_FLX_col(:)     
  real(r8),pointer   :: h1D_H2_SEMIS_FLX_col(:)
  real(r8),pointer   :: h1D_frcPARabs_ptc(:)  
  real(r8),pointer   :: h1D_PAR_CAN_ptc(:)    
  real(r8),pointer   :: h1D_PAR_col(:)        
  real(r8),pointer   :: h1d_fPAR_col(:)
  real(r8),pointer   :: h1D_RNodeInitiate_ptc(:)
  real(r8),pointer   :: h1D_RLeafAppear_ptc(:)
  real(r8),pointer   :: h1D_Plant_C_ptc(:)    
  real(r8),pointer   :: h1D_Plant_N_ptc(:)    
  real(r8),pointer   :: h1D_Plant_P_ptc(:)    
  real(r8),pointer   :: h1D_stomatal_stress_ptc(:)
  real(r8),pointer   :: h1D_CANDew_ptc(:)
  real(r8),pointer   :: h1D_VHeatCap_litr_col(:)
  real(r8),pointer   :: h1D_LEAF_PC_ptc(:)    
  real(r8),pointer   :: h3D_SOC_Cps_vr(:,:,:)  
  real(r8),pointer   :: h2D_tSOC_vr(:,:)      
  real(r8),pointer   :: h2D_POM_C_vr(:,:)
  real(r8),pointer   :: h2D_MAOM_C_vr(:,:)
  real(r8),pointer   :: h2D_microbC_vr(:,:)
  real(r8),pointer   :: h2D_microbN_vr(:,:)
  real(r8),pointer   :: h2D_microbP_vr(:,:)
  real(r8),pointer   :: h2D_AeroBact_PrimS_lim_vr(:,:)
  real(r8),pointer   :: h2D_AeroFung_PrimS_lim_vr(:,:)
  real(r8),pointer   :: h2D_tSOCL_vr(:,:)
  real(r8),pointer   :: h2D_fTRootGro_pvr(:,:) !
  real(r8),pointer   :: h2D_fRootGrowPSISense_pvr(:,:)  !
  real(r8),pointer   :: h2D_litrC_vr(:,:)
  real(r8),pointer   :: h2D_litrN_vr(:,:)
  real(r8),pointer   :: h2D_litrP_vr(:,:)
  real(r8),pointer   :: h2D_tSON_vr(:,:)
  real(r8),pointer   :: h2D_tSOP_vr(:,:)  
  real(r8),pointer   :: h2D_NO3_vr(:,:)
  real(r8),pointer   :: h2D_NH4_vr(:,:)
  real(r8),pointer   :: h2D_VHeatCap_vr(:,:)  
  real(r8),pointer   :: h2D_DOC_vr(:,:)
  real(r8),pointer   :: h2D_DON_vr(:,:)
  real(r8),pointer   :: h2D_DOP_vr(:,:)
  real(r8),pointer   :: h2D_acetate_vr(:,:)
  real(r8),pointer   :: h1D_tDOC_soil_col(:)
  real(r8),pointer   :: h1D_tDON_soil_col(:)
  real(r8),pointer   :: h1D_tDOP_soil_col(:)
  real(r8),pointer   :: h1D_tAcetate_soil_col(:)
  real(r8),pointer   :: h1D_DOC_litr_col(:)
  real(r8),pointer   :: h1D_DON_litr_col(:)
  real(r8),pointer   :: h1D_DOP_litr_col(:)
  real(r8),pointer   :: h1D_acetate_litr_col(:)
  real(r8),pointer   :: h1D_CAN_RN_ptc(:)     
  real(r8),pointer   :: h1D_CAN_LE_ptc(:)     
  real(r8),pointer   :: h1D_CAN_H_ptc(:)      
  real(r8),pointer   :: h1D_CAN_G_ptc(:)      
  real(r8),pointer   :: h1D_CAN_TEMPC_ptc(:)  
  real(r8),pointer   :: h1D_CAN_TEMPFN_ptc(:)  
  real(r8),pointer   :: h1D_CAN_CO2_FLX_ptc(:) 
  real(r8),pointer   :: h1D_CAN_GPP_ptc(:)     
  real(r8),pointer   :: h1D_CAN_cumGPP_ptc(:)       
  real(r8),pointer   :: h1D_dCAN_GPP_CLIM_ptc(:)
  real(r8),pointer   :: h1D_dCAN_GPP_eLIM_ptc(:)  
  real(r8),pointer   :: h1D_CAN_RA_ptc(:)    
  real(r8),pointer   :: h1D_TurgEff4CanopyResp_ptc(:)  
  real(r8),pointer   :: h1D_CAN_GROWTH_ptc(:)
  real(r8),pointer   :: h1D_cTNC_ptc(:)        
  real(r8),pointer   :: h1D_cTNN_ptc(:)       
  real(r8),pointer   :: h1D_cTNP_ptc(:)    
  real(r8),pointer   :: h1D_CanNonstBConc_ptc(:)      
  real(r8),pointer   :: h1D_STOML_RSC_CO2_ptc(:)
  real(r8),pointer   :: h1D_STOML_Min_RSC_CO2_ptc(:)
  real(r8),pointer   :: h1D_Km_CO2_carboxy_ptc(:)
  real(r8),pointer   :: h1D_DynCi2CaRatio_ptc(:)
  real(r8),pointer   :: h1D_BLYR_RSC_CO2_ptc(:) 
  real(r8),pointer   :: h1D_CAN_CO2_ptc(:)      
  real(r8),pointer   :: h1D_O2L_ptc(:)
  real(r8),pointer   :: h1D_LAI_ptc(:)          
  real(r8),pointer   :: h1D_CanPhenol_WSTRSS_ptc(:)
  real(r8),pointer   :: h1D_CanPhenol_TSTRSS_ptc(:)
  real(r8),pointer   :: h1D_PSI_CAN_ptc(:)      
  real(r8),pointer   :: h1D_TURG_CAN_ptc(:)     
  real(r8),pointer   :: h1D_STOML_RSC_H2O_ptc(:) 
  real(r8),pointer   :: h1D_BLYR_RSC_H2O_ptc(:) 
  real(r8),pointer   :: h1D_CdH2ORootxSoil_ptc(:)
  real(r8),pointer   :: h1D_TRANSPN_ptc(:)      
  real(r8),pointer   :: h1D_NH4_UPTK_FLX_ptc(:)  
  real(r8),pointer   :: h1D_NO3_UPTK_FLX_ptc(:)  
  real(r8),pointer   :: h1D_N2_FIXN_FLX_ptc(:)   
  real(r8),pointer   :: h1D_cNH3_FLX_ptc(:)      
  real(r8),pointer   :: h1D_RNFixCO2_ptc(:)
  real(r8),pointer   :: h1D_PO4_UPTK_FLX_ptc(:)   
  real(r8),pointer   :: h1D_TC_Groth_ptc(:)
  real(r8),pointer   :: h2D_SoilBulkStress_vr(:,:)
  real(r8),pointer   :: h2D_RootNonstBConc_pvr(:,:)   
  real(r8),pointer   :: h2D_Root1stStrutC_pvr(:,:)
  real(r8),pointer   :: h2D_Cytok_scalar_pvr(:,:)
  real(r8),pointer   :: h2D_CRootLumenArea_pvr(:,:)
  real(r8),pointer   :: h2D_Cytokinin1stConc_pvr(:,:) 
  real(r8),pointer   :: h2D_Root1stStrutN_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stStrutP_pvr(:,:)
  real(r8),pointer   :: h2D_Root2ndStrutC_pvr(:,:)
  real(r8),pointer   :: h2D_Root2ndStrutN_pvr(:,:)
  real(r8),pointer   :: h2D_Root2ndStrutP_pvr(:,:)
  real(r8),pointer   :: h2D_QDrainloss_vr(:,:)  
  real(r8),pointer   :: h1D_SHOOT_C_ptc(:)      
  real(r8),pointer   :: h1D_RCanMaintDef_CO2_pft(:)           
  real(r8),pointer   :: h1D_LEAF_C_ptc(:)       
  real(r8),pointer   :: h1D_Petole_C_ptc(:)     
  real(r8),pointer   :: h1D_STALK_C_ptc(:)      
  real(r8),pointer   :: h1D_RESERVE_C_ptc(:)    
  real(r8),pointer   :: h1D_HUSK_C_ptc(:)       
  real(r8),pointer   :: h1D_GRAIN_C_ptc(:)      
  real(r8),pointer   :: h1D_MycorrizhalBiomC_ptc(:)
  real(r8),pointer   :: h1D_RootMeDStrutC_ptc(:)
  real(r8),pointer   :: h1D_Root1stStrutC_ptc(:)
  real(r8),pointer   :: h1D_Root1stStrutN_ptc(:)  
  real(r8),pointer   :: h1D_Root2ndStrutC_ptc(:)
  real(r8),pointer   :: h1D_ROOT_NONSTC_ptc(:)
  real(r8),pointer   :: h1D_ROOT_NONSTN_ptc(:)
  real(r8),pointer   :: h1D_ROOT_NONSTP_ptc(:)
  real(r8),pointer   :: h1D_ROOT_C_ptc(:)       
  real(r8),pointer   :: h1D_ROOTST_C_ptc(:)     
  real(r8),pointer   :: h1D_ROOTST_N_ptc(:) 
  real(r8),pointer   :: h1D_ROOTST_P_ptc(:) 
  real(r8),pointer   :: h1D_ShootNodule_C_ptc(:)     
  real(r8),pointer   :: h1D_ShootNodule_N_ptc(:)     
  real(r8),pointer   :: h1D_ShootNodule_P_ptc(:)             
  real(r8),pointer   :: h1D_RootNodule_C_ptc(:)     
  real(r8),pointer   :: h1D_STORED_C_ptc(:)     
  real(r8),pointer   :: h1D_GRAIN_NO_ptc(:)     
  real(r8),pointer   :: h1D_CondGasXSurf_col(:)
  real(r8),pointer   :: h1D_LAIb_ptc(:)         
  real(r8),pointer   :: h1D_EXUD_CumYr_C_FLX_ptc(:)   
  real(r8),pointer   :: h1D_LITRf_C_FLX_ptc(:)     
  real(r8),pointer   :: h1D_LITRf_P_FLX_ptc(:)     
  real(r8),pointer   :: h1D_SURF_LITRf_C_FLX_ptc(:)
  real(r8),pointer   :: h1D_AUTO_RESP_FLX_ptc(:)   
  real(r8),pointer   :: h1D_HVST_C_FLX_ptc(:)      
  real(r8),pointer   :: h1D_RootAct1stC_ptc(:)
  real(r8),pointer   :: h1D_PLANT_BALANCE_C_ptc(:) 
  real(r8),pointer   :: h1D_MainBranchNodeNumber_ptc(:)
  real(r8),pointer   :: h1D_ShootNodeNumber_ptc(:)
  real(r8),pointer   :: h1D_STANDING_DEAD_C_ptc(:) 
  real(r8),pointer   :: h1D_FIREp_CO2_FLX_ptc(:)   
  real(r8),pointer   :: h1D_FIREp_CH4_FLX_ptc(:)   
  real(r8),pointer   :: h1D_NPP_ptc(:)        
  real(r8),pointer   :: h1D_Stalk_HT_ptc(:)
  real(r8),pointer   :: h1D_CAN_HT_ptc(:)     
  real(r8),pointer   :: h1D_EmergeHeight_ptc(:)
  real(r8),pointer   :: h1D_CanopyCutProxy_ptc(:)
  real(r8),pointer   :: h1D_POPN_ptc(:)       
  real(r8),pointer   :: h1D_tTRANSPN_ptc(:)   
  real(r8),pointer   :: h1D_WTR_STRESS_ptc(:) 
  real(r8),pointer   :: h1D_OXY_STRESS_ptc(:) 
  real(r8),pointer   :: h1D_SHOOT_N_ptc(:)    
  real(r8),pointer   :: h1D_LEAF_N_ptc(:)  
  real(r8),pointer   :: h1D_fCNLFW_ptc(:)  
  real(r8),pointer   :: h1D_fCPLFW_ptc(:)    
  real(r8),pointer   :: h1D_LeafNperm2LAI_ptc(:)
  real(r8),pointer   :: h1D_Petole_N_ptc(:)   
  real(r8),pointer   :: h1D_STALK_N_ptc(:)    
  real(r8),pointer   :: h1D_RESERVE_N_ptc(:)  
  real(r8),pointer   :: h1D_HUSK_N_ptc(:)     
  real(r8),pointer   :: h1D_GRAIN_N_ptc(:)    
  real(r8),pointer   :: h1D_ROOT_N_ptc(:)     
  real(r8),pointer   :: h1D_RootNodule_N_ptc(:)   
  real(r8),pointer   :: h1D_STORED_N_ptc(:)   
  real(r8),pointer   :: h1D_EXUD_N_FLX_ptc(:)
  real(r8),pointer   :: h1D_Uptk_NMIN_Flx_ptc(:)
  real(r8),pointer   :: h1D_Uptk_PMIN_Flx_ptc(:)
  real(r8),pointer   :: h1D_Uptk_N_Flx_ptc(:)
  real(r8),pointer   :: h1D_Uptk_P_Flx_ptc(:)
  real(r8),pointer   :: h1D_LITRf_N_FLX_ptc(:)    
  real(r8),pointer   :: h1D_cum_N_FIXED_ptc(:) 
  real(r8),pointer   :: h1D_TreeRingRadius_ptc(:)
  real(r8),pointer   :: h1D_HVST_N_FLX_ptc(:)     
  real(r8),pointer   :: h1D_NH3can_FLX_ptc(:)   
  real(r8),pointer   :: h1D_PLANT_BALANCE_N_ptc(:)  
  real(r8),pointer   :: h1D_STANDING_DEAD_N_ptc(:)  
  real(r8),pointer   :: h1D_FIREp_N_FLX_ptc(:)      
  real(r8),pointer   :: h1D_VcMaxRubisco_ptc(:)
  real(r8),pointer   :: h1D_LeafProteinNperm2_ptc(:)
  real(r8),pointer   :: h1D_PARSunlit_ptc(:)
  real(r8),pointer   :: h1D_PARSunsha_ptc(:)
  real(r8),pointer   :: h1D_CH2OSunlit_ptc(:)
  real(r8),pointer   :: h1D_CH2OSunsha_ptc(:)  
  real(r8),pointer   :: h1D_VoMaxRubisco_ptc(:)  
  real(r8),pointer   :: h1D_VcMaxPEP_ptc(:)  
  real(r8),pointer   :: h1D_JMaxPhoto_ptc(:)
  real(r8),pointer   :: h1D_TFN_Carboxy_ptc(:)
  real(r8),pointer   :: h1D_SLA_ptc(:)
  real(r8),pointer   :: h1D_TFN_Oxygen_ptc(:)
  real(r8),pointer   :: h1D_TFN_eTranspt_ptc(:)  
  real(r8),pointer   :: h1D_LeafAreaSunlit_ptc(:)
  real(r8),pointer   :: h1D_fClump_ptc(:)
  real(r8),pointer   :: h1D_SURF_LITRf_N_FLX_ptc(:) 
  real(r8),pointer   :: h1D_Root1stTipSinkWt_ptc(:)
  real(r8),pointer   :: h1D_SHOOT_P_ptc(:)     
  real(r8),pointer   :: h1D_LEAF_P_ptc(:)      
  real(r8),pointer   :: h1D_Petole_P_ptc(:)    
  real(r8),pointer   :: h1D_STALK_P_ptc(:)     
  real(r8),pointer   :: h1D_RESERVE_P_ptc(:)  
  real(r8),pointer   :: h1D_HUSK_P_ptc(:)     
  real(r8),pointer   :: h1D_GRAIN_P_ptc(:)    
  real(r8),pointer   :: h1D_ROOT_P_ptc(:)     
  real(r8),pointer   :: h1D_RootNodule_P_ptc(:)   
  real(r8),pointer   :: h1D_STORED_P_ptc(:)    
  real(r8),pointer   :: h1D_EXUD_P_FLX_ptc(:)  
  real(r8),pointer   :: h1D_LITTERf_P_ptc(:)   
  real(r8),pointer   :: h1D_HVST_P_FLX_ptc(:)    
  real(r8),pointer   :: h1D_PLANT_BALANCE_P_ptc(:)   
  real(r8),pointer   :: h1D_STANDING_DEAD_P_ptc(:)   
  real(r8),pointer   :: h1D_FIREp_P_FLX_ptc(:)       
  real(r8),pointer   :: h1D_SURF_LITRf_P_FLX_ptc(:) 
  real(r8),pointer   :: h1D_ShootRootXferC_ptc(:)
  real(r8),pointer   :: h1D_ShootRootXferN_ptc(:)
  real(r8),pointer   :: h1D_ShootRootXferP_ptc(:)    
  real(r8),pointer   :: h2D_RootMaintDef_CO2_pvr(:,:)
  real(r8),pointer   :: h2D_RootAbsorbAreaPP_pvr(:,:)
  real(r8),pointer   :: h1D_RootAbsorbAreaPP_pft(:)
  real(r8),pointer   :: h2D_ROOTNLim_rpvr(:,:)
  real(r8),pointer   :: h2D_ROOTPLim_rpvr(:,:)  
  real(r8),pointer   :: h2D_RootNonstC_rpvr(:,:)
  real(r8),pointer   :: h2D_RootMSinkWeight_pvr(:,:)
  real(r8),pointer   :: h2D_RootSinkWeight_pvr(:,:)
  real(r8),pointer   :: h2D_Root2ndSinkWeight_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stSinkWeight_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stRadius_rpvr(:,:)
  real(r8),pointer   :: h1D_RootMaintDef_CO2_pft(:)
  real(r8),pointer   :: h1D_NumPrimeRootAxes_ptc(:)
  real(r8),pointer   :: h1D_BRANCH_NO_ptc(:)    
  real(r8),pointer   :: h1D_SHOOT_NONSTC_ptc(:) 
  real(r8),pointer   :: h1D_SHOOT_NONSTN_ptc(:)  
  real(r8),pointer   :: h1D_SHOOT_NONSTP_ptc(:) 
  real(r8),pointer   :: h1D_LeafChlCperm2LA_ptc(:) 
  real(r8),pointer   :: h1D_LeafC4ChlCperm2LA_ptc(:) 
  real(r8),pointer   :: h1D_LeafRubiscoNperm2LA_ptc(:)
  real(r8),pointer   :: h1D_LeafPEPCNperm2LA_ptc(:)    
!  real(r8),pointer   :: h1D_CFIX_lmtf_ptc(:)
  real(r8),pointer   :: h1D_MainBranchNO_ptc(:)
  real(r8),pointer   :: h1D_Ar_mass_col(:)       
  real(r8),pointer   :: h1D_CO2_mass_col(:)
  real(r8),pointer   :: h1D_Gchem_CO2_prod_col(:)
  real(r8),pointer   :: h1D_LEAF_NC_ptc(:)      
  real(r8),pointer   :: h1D_Growth_Stage_ptc(:) 
  real(r8),pointer   :: h1D_Num_Leaves_ptc(:) 
  real(r8),pointer   :: h1D_RUB_ACTVN_ptc(:)    
  real(r8),pointer   :: h1D_CanopyNLim_ptc(:)
  real(r8),pointer   :: h1D_CanopyPLim_ptc(:)
  real(r8),pointer   :: h3D_PARTS_ptc(:,:,:)      
  real(r8),pointer   :: h2D_Gas_Pressure_vr(:,:)
  real(r8),pointer   :: h2D_N2O_Gas_ppmv_vr(:,:)  
  real(r8),pointer   :: h2D_CO2_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_CH4_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_H2_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_N2_Gas_ppmv_vr(:,:)  
  real(r8),pointer   :: h2D_Ar_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_O2_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_NH3_Gas_ppmv_vr(:,:)
  real(r8),pointer   :: h2D_cyanoBactC_vr(:,:)

  real(r8),pointer   :: h2D_AeroHrBactC_vr(:,:)   
  real(r8),pointer   :: h2D_AeroHrFungC_vr(:,:)   
  real(r8),pointer   :: h2D_faculDenitC_vr(:,:)  
  real(r8),pointer   :: h2D_fermentorC_vr(:,:)  
  real(r8),pointer   :: h2D_acetometgC_vr(:,:)  
  real(r8),pointer   :: h2D_fermentor_frac_vr(:,:)
  real(r8),pointer   :: h2D_acetometh_frac_vr(:,:)  
  real(r8),pointer   :: h2D_hydrogMeth_frac_vr(:,:)
  real(r8),pointer   :: h2D_aeroN2fixC_vr(:,:)  
  real(r8),pointer   :: h2D_anaeN2FixC_vr(:,:)  
  real(r8),pointer   :: h2D_NH3OxiBactC_vr(:,:)
  real(r8),pointer   :: h2D_NO2OxiBactC_vr(:,:)
  real(r8),pointer   :: h2D_CH4AeroOxiC_vr(:,:)
  real(r8),pointer   :: h2D_H2MethogenC_vr(:,:)
  real(r8),pointer   :: h2D_tOMActCDens_vr(:,:)
  real(r8),pointer   :: h1D_tOMActCDens_litr_col(:)  
  real(r8),pointer   :: h2D_TSolidOMActC_vr(:,:)
  real(r8),pointer   :: h2D_TSolidOMActCDens_vr(:,:)
  real(r8),pointer   :: h2D_RCH4ProdHydrog_vr(:,:)
  real(r8),pointer   :: h2D_RCH4ProdAcetcl_vr(:,:)
  real(r8),pointer   :: h2D_RCH4Oxi_aero_vr(:,:)
  real(r8),pointer   :: h1D_RCH4Oxi_aero_col(:)
  real(r8),pointer   :: h2D_RCH4Oxi_anmo_vr(:,:)
  real(r8),pointer   :: h1D_RCH4Oxi_anmo_col(:)
  real(r8),pointer   :: h2D_RFerment_vr(:,:)
  real(r8),pointer   :: h2D_nh3oxi_vr(:,:)
  real(r8),pointer   :: h2D_RNit_NO2toNO3_vr(:,:)
  real(r8),pointer   :: h2D_RDen_NO3toNO2_vr(:,:)
  real(r8),pointer   :: h2D_n2oprod_vr(:,:)
  real(r8),pointer   :: h2D_RootMassC_vr(:,:)
  real(r8),pointer   :: h2D_RootMassC_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stDepz_ptc(:,:) 
  real(r8),pointer   :: h2D_RootPop_pvr(:,:)
  real(r8),pointer   :: h2D_MycoPop_pvr(:,:)
  real(r8),pointer   :: h2D_MycoBiomC_pvr(:,:)
  real(r8),pointer   :: h2D_RootRadialKond2H2O_pvr(:,:)  
  real(r8),pointer   :: h2D_RootAxialKond2H2O_pvr(:,:)
  real(r8),pointer   :: h2D_VmaxNH4Root_pvr(:,:)
  real(r8),pointer   :: h2D_VmaxNO3Root_pvr(:,:)
  real(r8),pointer   :: h2D_RootMassN_vr(:,:)
  real(r8),pointer   :: h2D_RootMassP_vr(:,:)
  real(r8),pointer   :: h1D_TSolidOMActC_litr_col(:)  
  real(r8),pointer   :: h1D_TSolidOMActCDens_litr_col(:)
  real(r8),pointer   :: h1D_RCH4ProdHydrog_litr_col(:)
  real(r8),pointer   :: h1D_RCH4ProdAcetcl_litr_col(:)  
  real(r8),pointer   :: h1D_RCH4Oxi_aero_litr_col(:)
  real(r8),pointer   :: h1D_RCH4Oxi_anmo_litr_col(:)  
  real(r8),pointer   :: h1D_RFermen_litr_col(:)
  real(r8),pointer   :: h1D_NH3oxi_litr_col(:)
  real(r8),pointer   :: h1D_RDen_NO3toNO2_col(:)
  real(r8),pointer   :: h1D_NO2Oxi_litr_col(:)
  real(r8),pointer   :: h1D_N2oprod_litr_col(:)
  real(r8),pointer   :: h1D_RDECOMPC_SOM_litr_col(:)
  real(r8),pointer   :: h1D_MicrobAct_litr_col(:)
  real(r8),pointer   :: h1D_RDECOMPC_BReSOM_litr_col(:)
  real(r8),pointer   :: h1D_RDECOMPC_SorpSOM_litr_col(:)
  real(r8),pointer   :: h1D_tRespGrossHete_litr_col(:)
  real(r8),pointer   :: h1D_tRespGrossHeteUlm_litr_col(:)

  real(r8),pointer   :: h2D_AeroHrBactN_vr(:,:)  
  real(r8),pointer   :: h2D_AeroHrFungN_vr(:,:)  
  real(r8),pointer   :: h2D_faculDenitN_vr(:,:)  
  real(r8),pointer   :: h2D_fermentorN_vr(:,:) 
  real(r8),pointer   :: h2D_acetometgN_vr(:,:) 
  real(r8),pointer   :: h2D_aeroN2fixN_vr(:,:) 
  real(r8),pointer   :: h2D_anaeN2FixN_vr(:,:) 
  real(r8),pointer   :: h2D_NH3OxiBactN_vr(:,:)
  real(r8),pointer   :: h2D_NO2OxiBactN_vr(:,:)
  real(r8),pointer   :: h2D_CH4AeroOxiN_vr(:,:)
  real(r8),pointer   :: h2D_H2MethogenN_vr(:,:)
  real(r8),pointer   :: h2D_tRespGrossHeter_vr(:,:)
  real(r8),pointer   :: h2D_tRespGrossHeterUlm_vr(:,:)
  real(r8),pointer   :: h2D_FermOXYI_vr(:,:)
  real(r8),pointer   :: h2D_RDECOMPC_SOM_vr(:,:)
  real(r8),pointer   :: h2D_RDECOMPC_BReSOM_vr(:,:)
  real(r8),pointer   :: h2D_RDECOMPC_SorpSOM_vr(:,:)
  real(r8),pointer   :: h2D_MicrobAct_vr(:,:)
  real(r8),pointer   :: h3D_SOMHydrylScalCps_vr(:,:,:)
  real(r8),pointer   :: h3D_MicrobActCps_vr(:,:,:)
  real(r8),pointer   :: h3D_HydrolCSOMCps_vr(:,:,:)
  real(r8),pointer   :: h3D_Aerobic_Bacteria_vr(:,:,:)
  real(r8),pointer   :: h3D_Aerobic_Fungi_vr(:,:,:)
  real(r8),pointer   :: h3D_Facult_Denitf_vr(:,:,:)
  real(r8),pointer   :: h2D_AeroHrBactP_vr(:,:)   
  real(r8),pointer   :: h2D_AeroHrFungP_vr(:,:)   
  real(r8),pointer   :: h2D_faculDenitP_vr(:,:)  
  real(r8),pointer   :: h2D_fermentorP_vr(:,:)  
  real(r8),pointer   :: h2D_acetometgP_vr(:,:)  
  real(r8),pointer   :: h2D_aeroN2fixP_vr(:,:)  
  real(r8),pointer   :: h2D_anaeN2FixP_vr(:,:)  
  real(r8),pointer   :: h2D_NH3OxiBactP_vr(:,:)
  real(r8),pointer   :: h2D_NO2OxiBactP_vr(:,:)
  real(r8),pointer   :: h2D_CH4AeroOxiP_vr(:,:)
  real(r8),pointer   :: h2D_H2MethogenP_vr(:,:)
  real(r8),pointer   :: h2D_CanopyLAIZ_plyr(:,:)
  real(r8),pointer   :: h2D_MicroBiomeE_litr_col(:,:) 
  real(r8),pointer   :: h2D_AeroHrBactE_litr_col(:,:) 
  real(r8),pointer   :: h2D_AeroHrFungE_litr_col(:,:) 
  real(r8),pointer   :: h2D_faculDenitE_litr_col(:,:) 
  real(r8),pointer   :: h2D_fermentorE_litr_col(:,:) 
  real(r8),pointer   :: h2D_cyanoBactC_litr_col(:,:)
  real(r8),pointer   :: h2D_acetometgE_litr_col(:,:) 
  real(r8),pointer   :: h2D_aeroN2fixE_litr_col(:,:) 
  real(r8),pointer   :: h2D_anaeN2FixE_litr_col(:,:)  
  real(r8),pointer   :: h2D_NH3OxiBactE_litr_col(:,:)
  real(r8),pointer   :: h2D_NO2OxiBactE_litr_col(:,:)
  real(r8),pointer   :: h2D_CH4AeroOxiE_litr_col(:,:)
  real(r8),pointer   :: h2D_H2MethogenE_litr_col(:,:)
  real(r8),pointer   :: h2D_O2_rootconduct_pvr(:,:)
  real(r8),pointer   :: h2D_CO2_rootconduct_pvr(:,:)
  real(r8),pointer   :: h2D_ProteinNperm2LeafArea_pnd(:,:) !by node
  real(r8),pointer   :: h2D_Root_CO2_vr(:,:)
  real(r8),pointer   :: h2D_Aqua_CO2_vr(:,:)     
  real(r8),pointer   :: h2D_Aqua_CH4_vr(:,:)     
  real(r8),pointer   :: h2D_Aqua_O2_vr(:,:)      
  real(r8),pointer   :: h2D_Aqua_N2_vr(:,:)        
  real(r8),pointer   :: h2D_Aqua_H2_vr(:,:)        
  real(r8),pointer   :: h2D_Aqua_Ar_vr(:,:)        
  real(r8),pointer   :: h2D_Aqua_N2O_vr(:,:)     
  real(r8),pointer   :: h2D_Aqua_NH3_vr(:,:)     
  real(r8),pointer   :: h2D_RootAR2soil_vr(:,:)  
  real(r8),pointer   :: h2D_RootAR2Root_vr(:,:)
  real(r8),pointer   :: h2D_TEMP_vr(:,:)      
  real(r8),pointer   :: h2D_decomp_OStress_vr(:,:) 
  real(r8),pointer   :: h2D_RO2Decomp_vr(:,:)
  real(r8),pointer   :: h2D_Decomp_temp_FN_vr(:,:)
  real(r8),pointer   :: h1D_Decomp_temp_FN_litr_col(:)
  real(r8),pointer   :: h1D_FracLitMix_litr_col(:)
  real(r8),pointer   :: h2D_FracLitMix_vr(:,:)
  real(r8),pointer   :: h2D_Decomp_Moist_FN_vr(:,:)
  real(r8),pointer   :: h1D_Decomp_Moist_FN_litr_col(:)
  real(r8),pointer   :: h1D_decomp_OStress_litr_col(:)
  real(r8),pointer   :: h1D_RO2Decomp_litr_col(:)  
  real(r8),pointer   :: h2D_HeatUptk_vr(:,:)   
  real(r8),pointer   :: h2D_HeatFlow_vr(:,:)   
  real(r8),pointer   :: h2D_VSPore_vr(:,:)
  real(r8),pointer   :: h2D_FLO_MICP_vr(:,:)
  real(r8),pointer   :: h2D_FLO_MACP_vr(:,:)
  real(r8),pointer   :: h2D_rVSM_vr(:,:)    
  real(r8),pointer   :: h2D_rVSICE_vr(:,:)   
  real(r8),pointer   :: h2D_PSI_vr(:,:)        
  real(r8),pointer   :: h2D_PsiO_vr(:,:)
  real(r8),pointer   :: h2D_cNH4t_vr(:,:)                                                     
  real(r8),pointer   :: h2D_RootH2OUP_vr(:,:)  
  real(r8),pointer   :: h2D_cNO3t_vr(:,:)                                                     
  real(r8),pointer   :: h2D_cPO4_vr(:,:)       
  real(r8),pointer   :: h2D_cEXCH_P_vr(:,:)    
  real(r8),pointer   :: h2D_microb_N2fix_vr(:,:)
  real(r8),pointer   :: h2D_ElectricConductivity_vr(:,:) 
  real(r8),pointer   :: h2D_HydCondSoil_vr(:,:)
  real(r8),pointer   :: h2D_PSI_RT_pvr(:,:)     
  real(r8),pointer   :: h2D_RootH2OUptkStress_pvr(:,:)
  real(r8),pointer   :: h2D_RootH2OUptk_pvr(:,:)
  real(r8),pointer   :: h2D_RootMedC_pvr(:,:)
  real(r8),pointer   :: h2D_RootAct1stC_pvr(:,:)
  real(r8),pointer   :: h2D_NonstC_conc_pvr(:,:)
  real(r8),pointer   :: h2D_RootLig1stC_pvr(:,:)
  real(r8),pointer   :: h2D_RootShootExchC_pvr(:,:)
  real(r8),pointer   :: h2D_RootShootExchN_pvr(:,:)
  real(r8),pointer   :: h2D_RootShootExchP_pvr(:,:)
  real(r8),pointer   :: h2D_SapFlowVlinear_pvr(:,:)
  real(r8),pointer   :: h2D_ROOT_OSTRESS_pvr(:,:)
  real(r8),pointer   :: h2D_prtUP_NH4_pvr(:,:)                                                                     
  real(r8),pointer   :: h2D_prtUP_NO3_pvr(:,:)  
  real(r8),pointer   :: h2D_prtUP_PO4_pvr(:,:)                                                  
  real(r8),pointer   :: h2D_DNS_RT_pvr(:,:)   
  real(r8),pointer   :: h2D_RootNutupk_fClim_pvr(:,:)
  real(r8),pointer   :: h2D_RootNutupk_fNlim_pvr(:,:)
  real(r8),pointer   :: h2D_RootNutupk_fPlim_pvr(:,:)
  real(r8),pointer   :: h2D_RootNutupk_fProtC_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stSArea4GasTP_pvr(:,:)
  real(r8),pointer   :: h2D_RootProteinC_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stLenPP_pvr(:,:)
  real(r8),pointer   :: h2D_Rootmedlength_pvr(:,:)  
  real(r8),pointer   :: h2D_RootmedRadius_pvr(:,:)  
  real(r8),pointer   :: h2D_RootMedAxesNumL_pvr(:,:)
  real(r8),pointer   :: h2D_Root1stAxesNumL_pvr(:,:)
  real(r8),pointer   :: h2D_Root2ndAxesNumL_pvr(:,:)
  REAL(R8),pointer   :: h2D_RootKond2H2O_pvr(:,:)
  contains
    procedure, public :: Init  => init_hist_data
    procedure, public :: hist_update
    procedure, private :: ZeroPlantHistVars
  end type histdata_type

  type(histdata_type),public :: hist_ecosim

  interface
    module subroutine hist_update(this,I,J,bounds)
      class(histdata_type) :: this
      integer, intent(in) :: I,J
      type(bounds_type), intent(in) :: bounds
    end subroutine hist_update

    module subroutine ZeroPlantHistVars(this,nptc)
      class(histdata_type) :: this
      integer, intent(in) :: nptc
    end subroutine ZeroPlantHistVars

    module subroutine allocate_hist_columns(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine allocate_hist_columns

    module subroutine allocate_hist_plants(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine allocate_hist_plants

    module subroutine allocate_hist_profiles(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine allocate_hist_profiles

    module subroutine register_hist_columns(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine register_hist_columns

    module subroutine register_hist_plants(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine register_hist_plants

    module subroutine register_hist_soil_bgc(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine register_hist_soil_bgc

    module subroutine register_hist_soil_phys_root(this,bounds)
      class(histdata_type) :: this
      type(bounds_type), intent(in) :: bounds
    end subroutine register_hist_soil_phys_root

    module subroutine update_hist_columns(this,I,J,NY,NX,ncol)
      class(histdata_type) :: this
      integer, intent(in) :: I,J,NY,NX,ncol
    end subroutine update_hist_columns

    module subroutine update_hist_soil(this,I,J,NY,NX,ncol)
      class(histdata_type) :: this
      integer, intent(in) :: I,J,NY,NX,ncol
    end subroutine update_hist_soil

    module subroutine update_hist_plants(this,I,J,NY,NX,ncol)
      class(histdata_type) :: this
      integer, intent(in) :: I,J,NY,NX,ncol
    end subroutine update_hist_plants
  end interface

contains

  subroutine init_hist_data(this,bounds)
    class(histdata_type) :: this
    type(bounds_type), intent(in) :: bounds

    ! Preserve the original allocation and field-registration order. Allocation
    ! finishes before registration; registration order determines field indices.
    call allocate_hist_columns(this,bounds)
    call allocate_hist_plants(this,bounds)
    call allocate_hist_profiles(this,bounds)
    call register_hist_columns(this,bounds)
    call register_hist_plants(this,bounds)
    call register_hist_soil_bgc(this,bounds)
    call register_hist_soil_phys_root(this,bounds)
  end subroutine init_hist_data

end module HistDataType
