      real(r8) :: HVST(05,366,JY,JX),GROUPI(JP,JY,JX),PPI(JP,JY,JX)
     2,GROUPX(JP,JY,JX),RTFQ(JP,JY,JX)
     3,SDPTH(JP,JY,JX),SDVL(JP,JY,JX),SDLG(JP,JY,JX)
     4,SDAR(JP,JY,JX),ANGBR(JP,JY,JX),ANGSH(JP,JY,JX),CNWS(JP,JY,JX)
     5,CPWS(JP,JY,JX),CWSRT(JP,JY,JX),WTSTDI(JP,JY,JX),PPX(JP,JY,JX)
     6,THIN(05,366,JY,JX),EHVST(2,4,05,366,JY,JX),PORTX(2,JP,JY,JX)
      integer :: IYR0(JP,JY,JX),IYRH(JP,JY,JX),IDAY0(JP,JY,JX)
     8,IDAYH(JP,JY,JX),IHVST(05,366,JY,JX),JHVST(05,366,JY,JX)
     9,IDTH(JP,JY,JX),IYRX(JP,JY,JX),IDAYX(JP,JY,JX),IYRY(JP,JY,JX)
     1,IDAYY(JP,JY,JX)

      COMMON/BLK9C/HVST,GROUPI,PPI
     2,GROUPX,RTFQ
     3,SDPTH,SDVL,SDLG
     4,SDAR,ANGBR,ANGSH,CNWS
     5,CPWS,CWSRT,WTSTDI,PPX
     6,THIN,EHVST,PORTX
     7,IYR0,IYRH,IDAY0,IDAYH
     8,IHVST,JHVST
     9,IDTH,IYRX,IDAYX,IYRY
     1,IDAYY
