module PlantAPI

  use data_kind_mod, only : r8 => SHR_KIND_R8
  use ExtractsMod   , only : extracts
  use grosubsMod    , only : grosubs
  use HfuncsMod    , only : hfuncs
  use EcoSIMSolverPar
  use UptakesMod    , only : uptakes
  use PlantDisturbMod, only : PrepLandscapeGrazing
  use timings      , only : start_timer, end_timer
  use EcoSIMHistMod
  use SnowDataType
  use SoilPhysDataType, only : ALBX
  use SurfLitterDataType
  use LandSurfDataType
  use SoilPropertyDataType
  use ChemTranspDataType
  use EcoSimSumDataType
  use SoilHeatDataType
  use SOMDataType
  use ClimForcDataType
  use EcoSIMCtrlDataType
  use GridDataType
  use RootDataType
  use SoilWaterDataType
  use CanopyDataType
  use PlantDataRateType
  use PlantTraitDataType
  use CanopyRadDataType
  use FlagDataType
  use EcosysBGCFluxType
  use FertilizerDataType
  use SoilBGCDataType
  use PlantMngmtDataType
  use PlantAPIData
implicit none

  private
  public :: PlantModel
  public :: PlantCanopyRadsModel

  contains


  subroutine PlantModel(I,J,NHW,NHE,NVN,NVS)


  implicit none
  integer, intent(in) :: I,J
  integer, intent(in) :: NHW,NHE,NVN,NVS
  real(r8) :: t1
  integer :: NY,NX

333   FORMAT(A8)

  call PrepLandscapeGrazing(I,J,NHW,NHE,NVN,NVS)

  TBALCs1=TBALC
  TBALNs1=TBALN
  TBALPs1=TBALP
  DO NX=NHW,NHE
    DO NY=NVN,NVS

    call  PlantAPISend(I,J,NY,NX)

!   UPDATE PLANT PHENOLOGY IN 'HFUNC'
!
    !if(lverb)WRITE(*,333)'HFUNC'
    !call start_timer(t1)

      CALL HFUNCs(I,J)
    !call end_timer('HFUNC',t1)

      CALL UPTAKES(I,J)

      CALL GROSUBs(I,J)

      CALL EXTRACTs(I,J)

      call PlantAPIRecv(I,J,NY,NX)
    ENDDO
  ENDDO
  TBALC=TBALCs1
  TBALN=TBALNs1
  TBALP=TBALPs1


  end subroutine PlantModel
!------------------------------------------------------------------------------------------

  subroutine PlantCanopyRadsModel(I,J,NY,NX,DPTH0s1)
  use CanopyCondsMod
  implicit none
  integer, intent(in) :: I,J,NY,NX
  real(r8), intent(in) :: DPTH0s1

  call PlantAPICanMSend(NY,NX)

  call CanopyConditionModel(I,J,DPTH0s1)

  call PlantAPICanMRecv(NY,NX)

  end subroutine PlantCanopyRadsModel
!------------------------------------------------------------------------------------------

  subroutine PlantAPIRecv(I,J,NY,NX)
  use PlantAPIData, only : plt_rad
  implicit none
  integer, intent(in) :: I,J,NY,NX

  integer :: NB,NR,NZ,K,L,M,N,I1
  I1=I+1;if(I1>LYRC)I1=1
  IFLGT(NY,NX)=IFLGTs1
  PPT(NY,NX)=PPTs1
  RECO(NY,NX)=RECOs1
  TNBP(NY,NX)=TNBPs1
  TGPP(NY,NX)=TGPPs1
  TLEC(NY,NX)=TLECs1
  TSHC(NY,NX)=TSHCs1
  TRAU(NY,NX)=TRAUs1
  ZPSNC(NY,NX)=ZPSNCs1
  ZZSNC(NY,NX)=ZZSNCs1
  ZCSNC(NY,NX)=ZCSNCs1
  TVOLWC(NY,NX)=TVOLWCs1
  TSH(NY,NX)=TSHs1
  WTSTGT(NY,NX)=WTSTGTs1
  UVOLO(NY,NX)=UVOLOs1
  ARSTC(NY,NX)=plt_morph%ARSTCs1
  XHVSTC(NY,NX)=XHVSTCs1
  XHVSTN(NY,NX)=XHVSTNs1
  XHVSTP(NY,NX)=XHVSTPs1
  ARLFC(NY,NX)=plt_morph%ARLFCs1
  TRN(NY,NX)=plt_rad%TRNs1
  TLE(NY,NX)=TLEs1
  TGH(NY,NX)=TGHs1
  TEVAPP(NY,NX)=TEVAPPs1
  TH2GZ(NY,NX)=TH2GZs1
  THRMC(NY,NX)=THRMCs1
  TN2OZ(NY,NX)=TN2OZs1
  TCO2Z(NY,NX)=TCO2Zs1
  TEVAPC(NY,NX)=TEVAPCs1
  THFLXC(NY,NX)=THFLXCs1
  TNH3Z(NY,NX)=TNH3Zs1
  TOXYZ(NY,NX)=TOXYZs1
  TVOLWP(NY,NX)=TVOLWPs1
  TCCAN(NY,NX)=TCCANs1
  TCH4Z(NY,NX)=TCH4Zs1
  TENGYC(NY,NX)=TENGYCs1

  FERT(17:19,I1,NY,NX)=FERTs1(17:19)
  FERT(3,I1,NY,NX)=FERTs1(3)
  IYTYP(2,I1,NY,NX)=IYTYPs1
  FWOOD(:)=FWOODs1(:)
  FWOODN(:)=FWOODNs1(:)
  FWOODP(:)=FWOODPs1(:)
  FWODR(:)=FWODRs1(:)
  FWODRN(:)=FWODRNs1(:)
  FWODRP(:)=FWODRPs1(:)
  FWODSN(:)=FWODSNs1(:)
  FWODSP(:)=FWODSPs1(:)
  FWODB(:)=FWODBs1(:)
  FWODLP(:)=FWODLPs1(:)
  FWODLN(:)=FWODLNs1(:)
  VOLWOU=VOLWOUs1
  DO L=1,JC
    WGLFT(L,NY,NX)=WGLFTs1(L)
    ARSTT(L,NY,NX)=plt_morph%ARSTTs1(L)
    ARLFT(L,NY,NX)=plt_morph%ARLFTs1(L)
  ENDDO
  DO L=NU(NY,NX),NL(NY,NX)
    DO K=0,jcplx1
      XOQCS(K,L,NY,NX)=XOQCSs1(K,L)
      XOQNS(K,L,NY,NX)=XOQNSs1(K,L)
      XOQPS(K,L,NY,NX)=XOQPSs1(K,L)
    ENDDO
    DO M=1,NPH
      ROXSK(M,L,NY,NX)=ROXSKs1(M,L)
    ENDDO
  ENDDO

  DO L=0,JZ
    RPOBX(L,NY,NX)=RPOBXs1(L)
    RP1BX(L,NY,NX)=RP1BXs1(L)
    RN3BX(L,NY,NX)=RN3BXs1(L)
    RNHBX(L,NY,NX)=RNHBXs1(L)
    RP14X(L,NY,NX)=RP14Xs1(L)
    RPO4X(L,NY,NX)=RPO4Xs1(L)
    RNO3X(L,NY,NX)=RNO3Xs1(L)
    RNH4X(L,NY,NX)=RNH4Xs1(L)
    ROXYX(L,NY,NX)=ROXYXs1(L)
    TUPHT(L,NY,NX)=TUPHTs1(L)
    TUPWTR(L,NY,NX)=TUPWTRs1(L)
    DO  N=0,1
      DO  K=1,jcplx1
        CSNT(K,N,L,NY,NX)=CSNTs1(K,N,L)
        ZSNT(K,N,L,NY,NX)=ZSNTs1(K,N,L)
        PSNT(K,N,L,NY,NX)=PSNTs1(K,N,L)
      ENDDO
    ENDDO
  ENDDO

  DO L=1,JZ
    TUPNF(L,NY,NX)=TUPNFs1(L)
    RTDNT(L,NY,NX)=RTDNTs1(L)
    TLOXYP(L,NY,NX)=TLOXYPs1(L)
    TLCO2P(L,NY,NX)=TLCO2Ps1(L)
    TLCH4P(L,NY,NX)=TLCH4Ps1(L)
    TLN2OP(L,NY,NX)=TLN2OPs1(L)
    TLNH3P(L,NY,NX)=TLNH3Ps1(L)
    TLH2GP(L,NY,NX)=TLH2GPs1(L)
    TCOFLA(L,NY,NX)=TCOFLAs1(L)
    TOXFLA(L,NY,NX)=TOXFLAs1(L)
    TCHFLA(L,NY,NX)=TCHFLAs1(L)
    TN2FLA(L,NY,NX)=TN2FLAs1(L)
    TNHFLA(L,NY,NX)=TNHFLAs1(L)
    THGFLA(L,NY,NX)=THGFLAs1(L)
    TCO2P(L,NY,NX)=TCO2Ps1(L)
    TUPOXP(L,NY,NX)=TUPOXPs1(L)
    TCO2S(L,NY,NX)=TCO2Ss1(L)
    TUPOXS(L,NY,NX)=TUPOXSs1(L)
    TUPCHS(L,NY,NX)=TUPCHSs1(L)
    TUPN2S(L,NY,NX)=TUPN2Ss1(L)
    TUPN3S(L,NY,NX)=TUPN3Ss1(L)
    TUPN3B(L,NY,NX)=TUPN3Bs1(L)
    TUPHGS(L,NY,NX)=TUPHGSs1(L)
    TUPNH4(L,NY,NX)=TUPNH4s1(L)
    TUPNO3(L,NY,NX)=TUPNO3s1(L)
    TUPH1B(L,NY,NX)=TUPH1Bs1(L)
    TUPH2B(L,NY,NX)=TUPH2Bs1(L)
    TUPNHB(L,NY,NX)=TUPNHBs1(L)
    TUPNOB(L,NY,NX)=TUPNOBs1(L)
    TUPH1P(L,NY,NX)=TUPH1Ps1(L)
    TUPH2P(L,NY,NX)=TUPH2Ps1(L)
    DO  K=0,jcplx1
      TDFOMP(K,L,NY,NX)=TDFOMPs1(K,L)
      TDFOMN(K,L,NY,NX)=TDFOMNs1(K,L)
      TDFOMC(K,L,NY,NX)=TDFOMCs1(K,L)
    ENDDO
  ENDDO
  DO NZ=1,NP0(NY,NX)
    WTRT(NZ,NY,NX)=WTRTs1(NZ)
    ARLFP(NZ,NY,NX)=plt_morph%ARLFPs1(NZ)
    ARSTP(NZ,NY,NX)=plt_morph%ARSTPs1(NZ)
    BALC(NZ,NY,NX)=BALCs1(NZ)
    BALN(NZ,NY,NX)=BALNs1(NZ)
    BALP(NZ,NY,NX)=BALPs1(NZ)
    CPOOLP(NZ,NY,NX)=CPOOLPs1(NZ)
    CPOLNP(NZ,NY,NX)=CPOLNPs1(NZ)
    CCPOLP(NZ,NY,NX)=CCPOLPs1(NZ)
    CCPLNP(NZ,NY,NX)=CCPLNPs1(NZ)
    CZPOLP(NZ,NY,NX)=CZPOLPs1(NZ)
    CPPOLP(NZ,NY,NX)=CPPOLPs1(NZ)
    CNET(NZ,NY,NX)=CNETs1(NZ)
    CO2Q(NZ,NY,NX)=CO2Qs1(NZ)
    CO2I(NZ,NY,NX)=plt_photo%CO2Is1(NZ)
    CO2L(NZ,NY,NX)=plt_photo%CO2Ls1(NZ)
    CF(NZ,NY,NX)=plt_morph%CFs1(NZ)
    CNWS(NZ,NY,NX)=CNWSs1(NZ)
    CPWS(NZ,NY,NX)=CPWSs1(NZ)
    CWSRT(NZ,NY,NX)=CWSRTs1(NZ)
    CNRTS(NZ,NY,NX)=CNRTSs1(NZ)
    CPRTS(NZ,NY,NX)=CPRTSs1(NZ)
    CTRAN(NZ,NY,NX)=CTRANs1(NZ)
    CARBN(NZ,NY,NX)=CARBNs1(NZ)
    CHILL(NZ,NY,NX)=CHILLs1(NZ)
    DCO2(NZ,NY,NX)=DCO2s1(NZ)
    DTKC(NZ,NY,NX)=DTKCs1(NZ)
    ENGYX(NZ,NY,NX)=ENGYXs1(NZ)
    EP(NZ,NY,NX)=EPs1(NZ)
    EVAPC(NZ,NY,NX)=EVAPCs1(NZ)
    EFLXC(NZ,NY,NX)=EFLXCs1(NZ)
    FMOL(NZ,NY,NX)=FMOLs1(NZ)
    FRADP(NZ,NY,NX)=plt_rad%FRADPs1(NZ)
    FNOD(NZ,NY,NX)=FNODs1(NZ)
    GRNO(NZ,NY,NX)=plt_morph%GRNOs1(NZ)
    HCSNC(NZ,NY,NX)=HCSNCs1(NZ)
    HZSNC(NZ,NY,NX)=HZSNCs1(NZ)
    HPSNC(NZ,NY,NX)=HPSNCs1(NZ)
    HCUPTK(NZ,NY,NX)=HCUPTKs1(NZ)
    HZUPTK(NZ,NY,NX)=HZUPTKs1(NZ)
    HPUPTK(NZ,NY,NX)=HPUPTKs1(NZ)
    HTCTL(NZ,NY,NX)=HTCTLs1(NZ)
    HVSTC(NZ,NY,NX)=HVSTCs1(NZ)
    HVSTN(NZ,NY,NX)=HVSTNs1(NZ)
    HVSTP(NZ,NY,NX)=HVSTPs1(NZ)
    HTC(NZ,NY,NX)=HTCs1(NZ)
    HFLXC(NZ,NY,NX)=HFLXCs1(NZ)
    HTSTZ(NZ,NY,NX)=HTSTZs1(NZ)
    IFLGC(NZ,NY,NX)=IFLGCs1(NZ)
    IDTH(NZ,NY,NX)=IDTHs1(NZ)
    IDTHP(NZ,NY,NX)=plt_pheno%IDTHPs1(NZ)
    IDTHR(NZ,NY,NX)=plt_pheno%IDTHRs1(NZ)
    IDAY0(NZ,NY,NX)=IDAY0s1(NZ)
    IYR0(NZ,NY,NX)=IYR0s1(NZ)
    IFLGI(NZ,NY,NX)=plt_pheno%IFLGIs1(NZ)
    IDAYH(NZ,NY,NX)=IDAYHs1(NZ)
    IYRH(NZ,NY,NX)=IYRHs1(NZ)
    NIX(NZ,NY,NX)=plt_morph%NIXs1(NZ)
    NBT(NZ,NY,NX)=plt_morph%NBTs1(NZ)
    NBR(NZ,NY,NX)=plt_morph%NBRs1(NZ)
    NRT(NZ,NY,NX)=plt_morph%NRTs1(NZ)
    NI(NZ,NY,NX)=plt_morph%NIs1(NZ)
    NG(NZ,NY,NX)=plt_morph%NGs1(NZ)
    NB1(NZ,NY,NX)=plt_morph%NB1s1(NZ)
    NNOD(NZ,NY,NX)=plt_morph%NNODs1(NZ)
    O2L(NZ,NY,NX)=O2Ls1(NZ)
    O2I(NZ,NY,NX)=plt_photo%O2Is1(NZ)
    OFFST(NZ,NY,NX)=OFFSTs1(NZ)
    OSTR(NZ,NY,NX)=OSTRs1(NZ)
    PPOOLP(NZ,NY,NX)=PPOOLPs1(NZ)
    PPOLNP(NZ,NY,NX)=PPOLNPs1(NZ)
    PPX(NZ,NY,NX)=PPXs1(NZ)
    PP(NZ,NY,NX)=PPs1(NZ)
    PPI(NZ,NY,NX)=PPIs1(NZ)
    PSILT(NZ,NY,NX)=PSILTs1(NZ)
    PSILO(NZ,NY,NX)=PSILOs1(NZ)
    PSILG(NZ,NY,NX)=PSILGs1(NZ)
    PSILZ(NZ,NY,NX)=PSILZs1(NZ)
    RCO2Z(NZ,NY,NX)=RCO2Zs1(NZ)
    ROXYZ(NZ,NY,NX)=ROXYZs1(NZ)
    RCH4Z(NZ,NY,NX)=RCH4Zs1(NZ)
    RN2OZ(NZ,NY,NX)=RN2OZs1(NZ)
    RNH3Z(NZ,NY,NX)=RNH3Zs1(NZ)
    RH2GZ(NZ,NY,NX)=RH2GZs1(NZ)
    RSMN(NZ,NY,NX)=RSMNs1(NZ)
    RSMH(NZ,NY,NX)=plt_photo%RSMHs1(NZ)
    RCMX(NZ,NY,NX)=RCMXs1(NZ)
    RNH3C(NZ,NY,NX)=RNH3Cs1(NZ)
    RSETC(NZ,NY,NX)=RSETCs1(NZ)
    RSETN(NZ,NY,NX)=RSETNs1(NZ)
    RSETP(NZ,NY,NX)=RSETPs1(NZ)
    RAD1(NZ,NY,NX)=plt_rad%RAD1s1(NZ)
    RAZ(NZ,NY,NX)=RAZs1(NZ)
    RC(NZ,NY,NX)=RCs1(NZ)
    RA(NZ,NY,NX)=RAs1(NZ)
    SDPTHI(NZ,NY,NX)=plt_morph%SDPTHIs1(NZ)
    SCO2(NZ,NY,NX)=SCO2s1(NZ)
    SO2(NZ,NY,NX)=SO2s1(NZ)
    SSTX(NZ,NY,NX)=SSTXs1(NZ)
    SDVL(NZ,NY,NX)=plt_morph%SDVLs1(NZ)
    SDLG(NZ,NY,NX)=plt_morph%SDLGs1(NZ)
    SDAR(NZ,NY,NX)=plt_morph%SDARs1(NZ)
    SDPTH(NZ,NY,NX)=plt_morph%SDPTHs1(NZ)
    SFLXC(NZ,NY,NX)=SFLXCs1(NZ)
    TCO2T(NZ,NY,NX)=TCO2Ts1(NZ)
    TCO2A(NZ,NY,NX)=TCO2As1(NZ)
    TCSN0(NZ,NY,NX)=TCSN0s1(NZ)
    TZSN0(NZ,NY,NX)=TZSN0s1(NZ)
    TPSN0(NZ,NY,NX)=TPSN0s1(NZ)
    TCSNC(NZ,NY,NX)=TCSNCs1(NZ)
    TZSNC(NZ,NY,NX)=TZSNCs1(NZ)
    TPSNC(NZ,NY,NX)=TPSNCs1(NZ)
    TCZ(NZ,NY,NX)=TCZs1(NZ)
    TCX(NZ,NY,NX)=TCXs1(NZ)
    TNH3C(NZ,NY,NX)=TNH3Cs1(NZ)
    THVSTC(NZ,NY,NX)=THVSTCs1(NZ)
    THVSTN(NZ,NY,NX)=THVSTNs1(NZ)
    THVSTP(NZ,NY,NX)=THVSTPs1(NZ)
    TCUPTK(NZ,NY,NX)=TCUPTKs1(NZ)
    TZUPTK(NZ,NY,NX)=TZUPTKs1(NZ)
    TPUPTK(NZ,NY,NX)=TPUPTKs1(NZ)
    TZUPFX(NZ,NY,NX)=TZUPFXs1(NZ)
    TKC(NZ,NY,NX)=TKCs1(NZ)
    TCC(NZ,NY,NX)=TCCs1(NZ)
    THRM1(NZ,NY,NX)=plt_rad%THRM1s1(NZ)
    TKCZ(NZ,NY,NX)=TKCZs1(NZ)
    TKG(NZ,NY,NX)=TKGs1(NZ)
    TCG(NZ,NY,NX)=TCGs1(NZ)
    TFN3(NZ,NY,NX)=TFN3s1(NZ)
    UPNF(NZ,NY,NX)=UPNFs1(NZ)
    UPOMC(NZ,NY,NX)=UPOMCs1(NZ)
    UPOMN(NZ,NY,NX)=UPOMNs1(NZ)
    UPOMP(NZ,NY,NX)=UPOMPs1(NZ)
    UPNH4(NZ,NY,NX)=UPNH4s1(NZ)
    UPNO3(NZ,NY,NX)=UPNO3s1(NZ)
    UPH2P(NZ,NY,NX)=UPH2Ps1(NZ)
    UPH1P(NZ,NY,NX)=UPH1Ps1(NZ)
    VHCPC(NZ,NY,NX)=VHCPCs1(NZ)
    VOLWP(NZ,NY,NX)=VOLWPs1(NZ)
    VCO2F(NZ,NY,NX)=VCO2Fs1(NZ)
    VCH4F(NZ,NY,NX)=VCH4Fs1(NZ)
    VOXYF(NZ,NY,NX)=VOXYFs1(NZ)
    VNH3F(NZ,NY,NX)=VNH3Fs1(NZ)
    VN2OF(NZ,NY,NX)=VN2OFs1(NZ)
    VPO4F(NZ,NY,NX)=VPO4Fs1(NZ)
    VOLWC(NZ,NY,NX)=VOLWCs1(NZ)
    WSTR(NZ,NY,NX)=WSTRs1(NZ)
    WTSTG(NZ,NY,NX)=WTSTGs1(NZ)
    WTSTGN(NZ,NY,NX)=WTSTGNs1(NZ)
    WTSTGP(NZ,NY,NX)=WTSTGPs1(NZ)
    WTRVC(NZ,NY,NX)=WTRVCs1(NZ)
    WTRVN(NZ,NY,NX)=WTRVNs1(NZ)
    WTRVP(NZ,NY,NX)=WTRVPs1(NZ)
    WTRVX(NZ,NY,NX)=WTRVXs1(NZ)
    WTSHT(NZ,NY,NX)=WTSHTs1(NZ)
    WTSHN(NZ,NY,NX)=WTSHNs1(NZ)
    WTSHP(NZ,NY,NX)=WTSHPs1(NZ)
    WTLF(NZ,NY,NX)=WTLFs1(NZ)
    WTSHE(NZ,NY,NX)=WTSHEs1(NZ)
    WTSTK(NZ,NY,NX)=WTSTKs1(NZ)
    WVSTK(NZ,NY,NX)=WVSTKs1(NZ)
    WTRSV(NZ,NY,NX)=WTRSVs1(NZ)
    WTHSK(NZ,NY,NX)=WTHSKs1(NZ)
    WTEAR(NZ,NY,NX)=WTEARs1(NZ)
    WTGR(NZ,NY,NX)=WTGRs1(NZ)
    WTRT(NZ,NY,NX)=WTRTts1(NZ)
    WTRTS(NZ,NY,NX)=WTRTSs1(NZ)
    WTRTSN(NZ,NY,NX)=WTRTSNs1(NZ)
    WTRTSP(NZ,NY,NX)=WTRTSPs1(NZ)
    WTRTN(NZ,NY,NX)=WTRTNs1(NZ)
    WTRTP(NZ,NY,NX)=WTRTPs1(NZ)
    WTLFN(NZ,NY,NX)=WTLFNs1(NZ)
    WTSHEN(NZ,NY,NX)=WTSHENs1(NZ)
    WTSTKN(NZ,NY,NX)=WTSTKNs1(NZ)
    WTRSVN(NZ,NY,NX)=WTRSVNs1(NZ)
    WTHSKN(NZ,NY,NX)=WTHSKNs1(NZ)
    WTEARN(NZ,NY,NX)=WTEARNs1(NZ)
    WTGRNN(NZ,NY,NX)=WTGRNNs1(NZ)
    WTLFP(NZ,NY,NX)=WTLFPs1(NZ)
    WTSHEP(NZ,NY,NX)=WTSHEPs1(NZ)
    WTSTKP(NZ,NY,NX)=WTSTKPs1(NZ)
    WTRSVP(NZ,NY,NX)=WTRSVPs1(NZ)
    WTHSKP(NZ,NY,NX)=WTHSKPs1(NZ)
    WTEARP(NZ,NY,NX)=WTEARPs1(NZ)
    WTGRNP(NZ,NY,NX)=WTGRNPs1(NZ)
    WTND(NZ,NY,NX)=WTNDs1(NZ)
    WTNDN(NZ,NY,NX)=WTNDNs1(NZ)
    WTNDP(NZ,NY,NX)=WTNDPs1(NZ)
    WTLS(NZ,NY,NX)=WTLSs1(NZ)
    WTRTA(NZ,NY,NX)=WTRTAs1(NZ)
    XKCO2L(NZ,NY,NX)=plt_photo%XKCO2Ls1(NZ)
    XKCO2O(NZ,NY,NX)=plt_photo%XKCO2Os1(NZ)
    ZPOOLP(NZ,NY,NX)=ZPOOLPs1(NZ)
    ZPOLNP(NZ,NY,NX)=ZPOLNPs1(NZ)
    ZC(NZ,NY,NX)=plt_morph%ZCs1(NZ)
    ZNPP(NZ,NY,NX)=ZNPPs1(NZ)
    ZEROP(NZ,NY,NX)=ZEROPs1(NZ)
    ZEROQ(NZ,NY,NX)=ZEROQs1(NZ)
    ZEROL(NZ,NY,NX)=ZEROLs1(NZ)
    ZTYP(NZ,NY,NX)=ZTYPs1(NZ)
    HVST(NZ,I,NY,NX)=HVSTs1(NZ)
    IHVST(NZ,I,NY,NX)=IHVSTs1(NZ)
    JHVST(NZ,I,NY,NX)=JHVSTs1(NZ)
    THIN(NZ,I,NY,NX)=THINs1(NZ)
    DO L=1,JZ
      WTNDL(L,NZ,NY,NX)=WTNDLs1(L,NZ)
      WTNDLN(L,NZ,NY,NX)=WTNDLNs1(L,NZ)
      WTNDLP(L,NZ,NY,NX)=WTNDLPs1(L,NZ)
      CPOOLN(L,NZ,NY,NX)=CPOOLNs1(L,NZ)
      ZPOOLN(L,NZ,NY,NX)=ZPOOLNs1(L,NZ)
      PPOOLN(L,NZ,NY,NX)=PPOOLNs1(L,NZ)
      RUPNF(L,NZ,NY,NX)=RUPNFs1(L,NZ)
      TFN4(L,NZ,NY,NX)=TFN4s1(L,NZ)
    ENDDO
    DO L=1,JC
      ARLFV(L,NZ,NY,NX)=plt_morph%ARLFVs1(L,NZ)
      WGLFV(L,NZ,NY,NX)=WGLFVs1(L,NZ)
      ARSTV(L,NZ,NY,NX)=plt_morph%ARSTVs1(L,NZ)
    ENDDO
    DO L=0,JZ
      DO K=0,1
        DO M=1,4
          CSNC(M,K,L,NZ,NY,NX)=CSNCs1(M,K,L,NZ)
          PSNC(M,K,L,NZ,NY,NX)=PSNCs1(M,K,L,NZ)
          ZSNC(M,K,L,NZ,NY,NX)=ZSNCs1(M,K,L,NZ)
        ENDDO
      ENDDO
    ENDDO

    DO NB=1,NBR(NZ,NY,NX)
      DO L=1,JC
        ARSTK(L,NB,NZ,NY,NX)=plt_morph%ARSTKs1(L,NB,NZ)
      ENDDO
      ATRP(NB,NZ,NY,NX)=plt_pheno%ATRPs1(NB,NZ)
      ARLFB(NB,NZ,NY,NX)=plt_morph%ARLFBs1(NB,NZ)
      ARLFZ(NB,NZ,NY,NX)=plt_morph%ARLFZs1(NB,NZ)
      CCPOLB(NB,NZ,NY,NX)=CCPOLBs1(NB,NZ)
      CZPOLB(NB,NZ,NY,NX)=CZPOLBs1(NB,NZ)
      CPPOLB(NB,NZ,NY,NX)=CPPOLBs1(NB,NZ)
      CPOLNB(NB,NZ,NY,NX)=CPOLNBs1(NB,NZ)
      CPOOL(NB,NZ,NY,NX)=CPOOLs1(NB,NZ)
      DGSTGI(NB,NZ,NY,NX)=plt_pheno%DGSTGIs1(NB,NZ)
      DGSTGF(NB,NZ,NY,NX)=plt_pheno%DGSTGFs1(NB,NZ)
      FLG4(NB,NZ,NY,NX)=plt_pheno%FLG4s1(NB,NZ)
      FDBK(NB,NZ,NY,NX)=plt_photo%FDBKs1(NB,NZ)
      FDBKX(NB,NZ,NY,NX)=plt_photo%FDBKXs1(NB,NZ)
      FLGZ(NB,NZ,NY,NX)=plt_pheno%FLGZs1(NB,NZ)
      GROUP(NB,NZ,NY,NX)=plt_pheno%GROUPs1(NB,NZ)
      GSTGI(NB,NZ,NY,NX)=plt_pheno%GSTGIs1(NB,NZ)
      GSTGF(NB,NZ,NY,NX)=plt_pheno%GSTGFs1(NB,NZ)
      GRNXB(NB,NZ,NY,NX)=plt_morph%GRNXBs1(NB,NZ)
      GRNOB(NB,NZ,NY,NX)=plt_morph%GRNOBs1(NB,NZ)
      GRWTB(NB,NZ,NY,NX)=GRWTBs1(NB,NZ)
      HTSHEX(NB,NZ,NY,NX)=plt_morph%HTSHEXs1(NB,NZ)
      IFLGP(NB,NZ,NY,NX)=plt_pheno%IFLGPs1(NB,NZ)
      IDTHB(NB,NZ,NY,NX)=plt_pheno%IDTHBs1(NB,NZ)
      IFLGF(NB,NZ,NY,NX)=plt_pheno%IFLGFs1(NB,NZ)
      IFLGE(NB,NZ,NY,NX)=plt_pheno%IFLGEs1(NB,NZ)
      IFLGA(NB,NZ,NY,NX)=plt_pheno%IFLGAs1(NB,NZ)
      IFLGG(NB,NZ,NY,NX)=plt_pheno%IFLGGs1(NB,NZ)
      IFLGR(NB,NZ,NY,NX)=plt_pheno%IFLGRs1(NB,NZ)
      IFLGQ(NB,NZ,NY,NX)=plt_pheno%IFLGQs1(NB,NZ)
      KVSTG(NB,NZ,NY,NX)=plt_pheno%KVSTGs1(NB,NZ)
      KLEAF(NB,NZ,NY,NX)=plt_morph%KLEAFs1(NB,NZ)
      KLEAFX(NB,NZ,NY,NX)=plt_morph%KLEAFXs1(NB,NZ)
      KVSTGN(NB,NZ,NY,NX)=plt_pheno%KVSTGNs1(NB,NZ)
      NBTB(NB,NZ,NY,NX)=plt_morph%NBTBs1(NB,NZ)
      PSTG(NB,NZ,NY,NX)=plt_morph%PSTGs1(NB,NZ)
      PSTGI(NB,NZ,NY,NX)=plt_morph%PSTGIs1(NB,NZ)
      PSTGF(NB,NZ,NY,NX)=plt_morph%PSTGFs1(NB,NZ)
      PPOLNB(NB,NZ,NY,NX)=PPOLNBs1(NB,NZ)
      PPOOL(NB,NZ,NY,NX)=PPOOLs1(NB,NZ)
      RCCLX(NB,NZ,NY,NX)=RCCLXs1(NB,NZ)
      RCZLX(NB,NZ,NY,NX)=RCZLXs1(NB,NZ)
      RCPLX(NB,NZ,NY,NX)=RCPLXs1(NB,NZ)
      RCCSX(NB,NZ,NY,NX)=RCCSXs1(NB,NZ)
      RCZSX(NB,NZ,NY,NX)=RCZSXs1(NB,NZ)
      RCPSX(NB,NZ,NY,NX)=RCPSXs1(NB,NZ)
      RNH3B(NB,NZ,NY,NX)=RNH3Bs1(NB,NZ)
      TGSTGI(NB,NZ,NY,NX)=plt_pheno%TGSTGIs1(NB,NZ)
      TGSTGF(NB,NZ,NY,NX)=plt_pheno%TGSTGFs1(NB,NZ)
      VRNY(NB,NZ,NY,NX)=plt_pheno%VRNYs1(NB,NZ)
      VRNZ(NB,NZ,NY,NX)=plt_pheno%VRNZs1(NB,NZ)
      VRNS(NB,NZ,NY,NX)=plt_pheno%VRNSs1(NB,NZ)
      VRNF(NB,NZ,NY,NX)=plt_pheno%VRNFs1(NB,NZ)
      VSTG(NB,NZ,NY,NX)=plt_morph%VSTGs1(NB,NZ)
      VSTGX(NB,NZ,NY,NX)=plt_pheno%VSTGXs1(NB,NZ)
      WTNDB(NB,NZ,NY,NX)=WTNDBs1(NB,NZ)
      WTNDBN(NB,NZ,NY,NX)=WTNDBNs1(NB,NZ)
      WTNDBP(NB,NZ,NY,NX)=WTNDBPs1(NB,NZ)
      WTLSB(NB,NZ,NY,NX)=WTLSBs1(NB,NZ)
      WTLFB(NB,NZ,NY,NX)=WTLFBs1(NB,NZ)
      WTSHEB(NB,NZ,NY,NX)=WTSHEBs1(NB,NZ)
      WTSTKB(NB,NZ,NY,NX)=WTSTKBs1(NB,NZ)
      WTRSVB(NB,NZ,NY,NX)=WTRSVBs1(NB,NZ)
      WTHSKB(NB,NZ,NY,NX)=WTHSKBs1(NB,NZ)
      WTEARB(NB,NZ,NY,NX)=WTEARBs1(NB,NZ)
      WTLFBN(NB,NZ,NY,NX)=WTLFBNs1(NB,NZ)
      WTSHBN(NB,NZ,NY,NX)=WTSHBNs1(NB,NZ)
      WTSTBN(NB,NZ,NY,NX)=WTSTBNs1(NB,NZ)
      WTRSBN(NB,NZ,NY,NX)=WTRSBNs1(NB,NZ)
      WTHSBN(NB,NZ,NY,NX)=WTHSBNs1(NB,NZ)
      WTEABN(NB,NZ,NY,NX)=WTEABNs1(NB,NZ)
      WTLFBP(NB,NZ,NY,NX)=WTLFBPs1(NB,NZ)
      WTSHBP(NB,NZ,NY,NX)=WTSHBPs1(NB,NZ)
      WTSTBP(NB,NZ,NY,NX)=WTSTBPs1(NB,NZ)
      WTRSBP(NB,NZ,NY,NX)=WTRSBPs1(NB,NZ)
      WTHSBP(NB,NZ,NY,NX)=WTHSBPs1(NB,NZ)
      WTEABP(NB,NZ,NY,NX)=WTEABPs1(NB,NZ)
      WGLFX(NB,NZ,NY,NX)=WGLFXs1(NB,NZ)
      WGLFNX(NB,NZ,NY,NX)=WGLFNXs1(NB,NZ)
      WGLFPX(NB,NZ,NY,NX)=WGLFPXs1(NB,NZ)
      WGSHEX(NB,NZ,NY,NX)=WGSHEXs1(NB,NZ)
      WGSHNX(NB,NZ,NY,NX)=WGSHNXs1(NB,NZ)
      WGSHPX(NB,NZ,NY,NX)=WGSHPXs1(NB,NZ)
      WTSTXB(NB,NZ,NY,NX)=WTSTXBs1(NB,NZ)
      WTSTXN(NB,NZ,NY,NX)=WTSTXNs1(NB,NZ)
      WTSTXP(NB,NZ,NY,NX)=WTSTXPs1(NB,NZ)
      WTSHTB(NB,NZ,NY,NX)=WTSHTBs1(NB,NZ)
      WTSHTN(NB,NZ,NY,NX)=WTSHTNs1(NB,NZ)
      WTSHTP(NB,NZ,NY,NX)=WTSHTPs1(NB,NZ)
      WVSTKB(NB,NZ,NY,NX)=WVSTKBs1(NB,NZ)
      WTGRB(NB,NZ,NY,NX)=WTGRBs1(NB,NZ)
      WTGRBN(NB,NZ,NY,NX)=WTGRBNs1(NB,NZ)
      WTGRBP(NB,NZ,NY,NX)=WTGRBPs1(NB,NZ)
      ZPOLNB(NB,NZ,NY,NX)=ZPOLNBs1(NB,NZ)
      ZPOOL(NB,NZ,NY,NX)=ZPOOLs1(NB,NZ)


      DO K=0,JNODS
        ARLF(K,NB,NZ,NY,NX)=plt_morph%ARLF1s1(K,NB,NZ)
        HTNODX(K,NB,NZ,NY,NX)=plt_morph%HTNODXs1(K,NB,NZ)
        HTNODE(K,NB,NZ,NY,NX)=plt_morph%HTNODEs1(K,NB,NZ)
        HTSHE(K,NB,NZ,NY,NX)=plt_morph%HTSHEs1(K,NB,NZ)
        WGNODE(K,NB,NZ,NY,NX)=WGNODEs1(K,NB,NZ)
        WGNODN(K,NB,NZ,NY,NX)=WGNODNs1(K,NB,NZ)
        WGNODP(K,NB,NZ,NY,NX)=WGNODPs1(K,NB,NZ)
        WGLF(K,NB,NZ,NY,NX)=WGLFs1(K,NB,NZ)
        WGLFN(K,NB,NZ,NY,NX)=WGLFNs1(K,NB,NZ)
        WGLFP(K,NB,NZ,NY,NX)=WGLFPs1(K,NB,NZ)
        WSLF(K,NB,NZ,NY,NX)=WSLFs1(K,NB,NZ)
        WGSHE(K,NB,NZ,NY,NX)=WGSHEs1(K,NB,NZ)
        WGSHN(K,NB,NZ,NY,NX)=WGSHNs1(K,NB,NZ)
        WGSHP(K,NB,NZ,NY,NX)=WGSHPs1(K,NB,NZ)
        WSSHE(K,NB,NZ,NY,NX)=WSSHEs1(K,NB,NZ)
      ENDDO
      DO  L=1,JC
        DO N=1,JLI
          SURFB(N,L,NB,NZ,NY,NX)=plt_morph%SURFBs1(N,L,NB,NZ)
        ENDDO
      ENDDO
      DO K=0,JNODS
        DO  L=1,JC
          ARLFL(L,K,NB,NZ,NY,NX)=plt_morph%ARLFLs1(L,K,NB,NZ)
          WGLFL(L,K,NB,NZ,NY,NX)=WGLFLs1(L,K,NB,NZ)
          WGLFLN(L,K,NB,NZ,NY,NX)=WGLFLNs1(L,K,NB,NZ)
          WGLFLP(L,K,NB,NZ,NY,NX)=WGLFLPs1(L,K,NB,NZ)
        ENDDO
      ENDDO
      DO M=1,10
        IDAY(M,NB,NZ,NY,NX)=plt_pheno%IDAYs1(M,NB,NZ)
      ENDDO
      DO K=1,JNODS
        DO  L=1,JC
          DO N=1,JLI
            SURF(N,L,K,NB,NZ,NY,NX)=plt_morph%SURFs1(N,L,K,NB,NZ)
            SURFX(N,L,K,NB,NZ,NY,NX)=SURFXs1(N,L,K,NB,NZ)
          ENDDO
        ENDDO
        CPOOL3(K,NB,NZ,NY,NX)=CPOOL3s1(K,NB,NZ)
        CPOOL4(K,NB,NZ,NY,NX)=CPOOL4s1(K,NB,NZ)
        CO2B(K,NB,NZ,NY,NX)=CO2Bs1(K,NB,NZ)
        COMPL(K,NB,NZ,NY,NX)=COMPLs1(K,NB,NZ)
        CBXN(K,NB,NZ,NY,NX)=CBXNs1(K,NB,NZ)
        CBXN4(K,NB,NZ,NY,NX)=CBXN4s1(K,NB,NZ)
        ETGRO(K,NB,NZ,NY,NX)=ETGROs1(K,NB,NZ)
        ETGR4(K,NB,NZ,NY,NX)=ETGR4s1(K,NB,NZ)
        FDBK4(K,NB,NZ,NY,NX)=FDBK4s1(K,NB,NZ)
        HCOB(K,NB,NZ,NY,NX)=HCOBs1(K,NB,NZ)
        VCGRO(K,NB,NZ,NY,NX)=VCGROs1(K,NB,NZ)
        VGRO(K,NB,NZ,NY,NX)=VGROs1(K,NB,NZ)
        VCGR4(K,NB,NZ,NY,NX)=VCGR4s1(K,NB,NZ)
        VGRO4(K,NB,NZ,NY,NX)=VGRO4s1(K,NB,NZ)
      ENDDO
    ENDDO
    DO M=1,4
      WTSTDG(M,NZ,NY,NX)=WTSTDGs1(M,NZ)
      WTSTDN(M,NZ,NY,NX)=WTSTDNs1(M,NZ)
      WTSTDP(M,NZ,NY,NX)=WTSTDPs1(M,NZ)
    ENDDO

    DO  L=1,JZ
      DO N=1,2
        CCPOLR(N,L,NZ,NY,NX)=CCPOLRs1(N,L,NZ)
        CZPOLR(N,L,NZ,NY,NX)=CZPOLRs1(N,L,NZ)
        CPPOLR(N,L,NZ,NY,NX)=CPPOLRs1(N,L,NZ)
        CO2A(N,L,NZ,NY,NX)=CO2As1(N,L,NZ)
        CH4A(N,L,NZ,NY,NX)=CH4As1(N,L,NZ)
        CO2P(N,L,NZ,NY,NX)=CO2Ps1(N,L,NZ)
        CH4P(N,L,NZ,NY,NX)=CH4Ps1(N,L,NZ)
        CPOOLR(N,L,NZ,NY,NX)=CPOOLRs1(N,L,NZ)
        CWSRTL(N,L,NZ,NY,NX)=CWSRTLs1(N,L,NZ)
        H2GA(N,L,NZ,NY,NX)=H2GAs1(N,L,NZ)
        H2GP(N,L,NZ,NY,NX)=H2GPs1(N,L,NZ)
        OXYA(N,L,NZ,NY,NX)=OXYAs1(N,L,NZ)
        OXYP(N,L,NZ,NY,NX)=OXYPs1(N,L,NZ)
        PPOOLR(N,L,NZ,NY,NX)=PPOOLRs1(N,L,NZ)
        PSIRT(N,L,NZ,NY,NX)=PSIRTs1(N,L,NZ)
        PSIRO(N,L,NZ,NY,NX)=PSIROs1(N,L,NZ)
        PSIRG(N,L,NZ,NY,NX)=PSIRGs1(N,L,NZ)
        RTN1(N,L,NZ,NY,NX)=RTN1s1(N,L,NZ)
        RTNL(N,L,NZ,NY,NX)=RTNLs1(N,L,NZ)
        RTLGP(N,L,NZ,NY,NX)=RTLGPs1(N,L,NZ)
        RTDNP(N,L,NZ,NY,NX)=RTDNPs1(N,L,NZ)
        RTVLP(N,L,NZ,NY,NX)=RTVLPs1(N,L,NZ)
        RTVLW(N,L,NZ,NY,NX)=RTVLWs1(N,L,NZ)
        RRAD1(N,L,NZ,NY,NX)=RRAD1s1(N,L,NZ)
        RRAD2(N,L,NZ,NY,NX)=RRAD2s1(N,L,NZ)
        RTARP(N,L,NZ,NY,NX)=RTARPs1(N,L,NZ)
        RTLGA(N,L,NZ,NY,NX)=RTLGAs1(N,L,NZ)
        RCO2M(N,L,NZ,NY,NX)=RCO2Ms1(N,L,NZ)
        RCO2N(N,L,NZ,NY,NX)=RCO2Ns1(N,L,NZ)
        RCO2A(N,L,NZ,NY,NX)=RCO2As1(N,L,NZ)
        RCO2P(N,L,NZ,NY,NX)=RCO2Ps1(N,L,NZ)
        RUPOXP(N,L,NZ,NY,NX)=RUPOXPs1(N,L,NZ)
        RCO2S(N,L,NZ,NY,NX)=RCO2Ss1(N,L,NZ)
        RUPOXS(N,L,NZ,NY,NX)=RUPOXSs1(N,L,NZ)
        RUPCHS(N,L,NZ,NY,NX)=RUPCHSs1(N,L,NZ)
        RUPN2S(N,L,NZ,NY,NX)=RUPN2Ss1(N,L,NZ)
        RUPN3S(N,L,NZ,NY,NX)=RUPN3Ss1(N,L,NZ)
        RUPN3B(N,L,NZ,NY,NX)=RUPN3Bs1(N,L,NZ)
        RUPHGS(N,L,NZ,NY,NX)=RUPHGSs1(N,L,NZ)
        RCOFLA(N,L,NZ,NY,NX)=RCOFLAs1(N,L,NZ)
        ROXFLA(N,L,NZ,NY,NX)=ROXFLAs1(N,L,NZ)
        RCHFLA(N,L,NZ,NY,NX)=RCHFLAs1(N,L,NZ)
        RN2FLA(N,L,NZ,NY,NX)=RN2FLAs1(N,L,NZ)
        RNHFLA(N,L,NZ,NY,NX)=RNHFLAs1(N,L,NZ)
        RHGFLA(N,L,NZ,NY,NX)=RHGFLAs1(N,L,NZ)
        RCODFA(N,L,NZ,NY,NX)=RCODFAs1(N,L,NZ)
        ROXDFA(N,L,NZ,NY,NX)=ROXDFAs1(N,L,NZ)
        RCHDFA(N,L,NZ,NY,NX)=RCHDFAs1(N,L,NZ)
        RN2DFA(N,L,NZ,NY,NX)=RN2DFAs1(N,L,NZ)
        RNHDFA(N,L,NZ,NY,NX)=RNHDFAs1(N,L,NZ)
        RHGDFA(N,L,NZ,NY,NX)=RHGDFAs1(N,L,NZ)
        RUNNHP(N,L,NZ,NY,NX)=RUNNHPs1(N,L,NZ)
        RUPNH4(N,L,NZ,NY,NX)=RUPNH4s1(N,L,NZ)
        RUONH4(N,L,NZ,NY,NX)=RUONH4s1(N,L,NZ)
        RUCNH4(N,L,NZ,NY,NX)=RUCNH4s1(N,L,NZ)
        RUNNBP(N,L,NZ,NY,NX)=RUNNBPs1(N,L,NZ)
        RUPNHB(N,L,NZ,NY,NX)=RUPNHBs1(N,L,NZ)
        RUONHB(N,L,NZ,NY,NX)=RUONHBs1(N,L,NZ)
        RUCNHB(N,L,NZ,NY,NX)=RUCNHBs1(N,L,NZ)
        RUNNOP(N,L,NZ,NY,NX)=RUNNOPs1(N,L,NZ)
        RUPNO3(N,L,NZ,NY,NX)=RUPNO3s1(N,L,NZ)
        RUONO3(N,L,NZ,NY,NX)=RUONO3s1(N,L,NZ)
        RUCNO3(N,L,NZ,NY,NX)=RUCNO3s1(N,L,NZ)
        RUNNXP(N,L,NZ,NY,NX)=RUNNXPs1(N,L,NZ)
        RUPNOB(N,L,NZ,NY,NX)=RUPNOBs1(N,L,NZ)
        RUONOB(N,L,NZ,NY,NX)=RUONOBs1(N,L,NZ)
        RUCNOB(N,L,NZ,NY,NX)=RUCNOBs1(N,L,NZ)
        RUPP2P(N,L,NZ,NY,NX)=RUPP2Ps1(N,L,NZ)
        RUPH2P(N,L,NZ,NY,NX)=RUPH2Ps1(N,L,NZ)
        RUOH2P(N,L,NZ,NY,NX)=RUOH2Ps1(N,L,NZ)
        RUCH2P(N,L,NZ,NY,NX)=RUCH2Ps1(N,L,NZ)
        RUPP2B(N,L,NZ,NY,NX)=RUPP2Bs1(N,L,NZ)
        RUPH2B(N,L,NZ,NY,NX)=RUPH2Bs1(N,L,NZ)
        RUOH2B(N,L,NZ,NY,NX)=RUOH2Bs1(N,L,NZ)
        RUCH2B(N,L,NZ,NY,NX)=RUCH2Bs1(N,L,NZ)
        RUPP1P(N,L,NZ,NY,NX)=RUPP1Ps1(N,L,NZ)
        RUPH1P(N,L,NZ,NY,NX)=RUPH1Ps1(N,L,NZ)
        RUOH1P(N,L,NZ,NY,NX)=RUOH1Ps1(N,L,NZ)
        RUCH1P(N,L,NZ,NY,NX)=RUCH1Ps1(N,L,NZ)
        RUPP1B(N,L,NZ,NY,NX)=RUPP1Bs1(N,L,NZ)
        RUPH1B(N,L,NZ,NY,NX)=RUPH1Bs1(N,L,NZ)
        RUOH1B(N,L,NZ,NY,NX)=RUOH1Bs1(N,L,NZ)
        RUCH1B(N,L,NZ,NY,NX)=RUCH1Bs1(N,L,NZ)
        ROXYP(N,L,NZ,NY,NX)=ROXYPs1(N,L,NZ)
        UPWTR(N,L,NZ,NY,NX)=UPWTRs1(N,L,NZ)
        WTRTL(N,L,NZ,NY,NX)=WTRTLs1(N,L,NZ)
        WTRTD(N,L,NZ,NY,NX)=WTRTDs1(N,L,NZ)
        WSRTL(N,L,NZ,NY,NX)=WSRTLs1(N,L,NZ)
        WFR(N,L,NZ,NY,NX)=WFRs1(N,L,NZ)
        Z2OA(N,L,NZ,NY,NX)=Z2OAs1(N,L,NZ)
        ZH3A(N,L,NZ,NY,NX)=ZH3As1(N,L,NZ)
        Z2OP(N,L,NZ,NY,NX)=Z2OPs1(N,L,NZ)
        ZH3P(N,L,NZ,NY,NX)=ZH3Ps1(N,L,NZ)
        ZPOOLR(N,L,NZ,NY,NX)=ZPOOLRs1(N,L,NZ)
      ENDDO
    ENDDO

    DO NR=1,NRT(NZ,NY,NX)
      NINR(NR,NZ,NY,NX)=plt_morph%NINRs1(NR,NZ)
      DO N=1,2
        RTWT1(N,NR,NZ,NY,NX)=RTWT1s1(N,NR,NZ)
        RTWT1N(N,NR,NZ,NY,NX)=RTWT1Ns1(N,NR,NZ)
        RTWT1P(N,NR,NZ,NY,NX)=RTWT1Ps1(N,NR,NZ)
        RTDP1(N,NR,NZ,NY,NX)=RTDP1s1(N,NR,NZ)
      ENDDO
      DO L=1,JZ
        DO N=1,2
          WTRT1(N,L,NR,NZ,NY,NX)=WTRT1s1(N,L,NR,NZ)
          WTRT1N(N,L,NR,NZ,NY,NX)=WTRT1Ns1(N,L,NR,NZ)
          WTRT1P(N,L,NR,NZ,NY,NX)=WTRT1Ps1(N,L,NR,NZ)
          WTRT2(N,L,NR,NZ,NY,NX)=WTRT2s1(N,L,NR,NZ)
          WTRT2N(N,L,NR,NZ,NY,NX)=WTRT2Ns1(N,L,NR,NZ)
          WTRT2P(N,L,NR,NZ,NY,NX)=WTRT2Ps1(N,L,NR,NZ)
          RTLG1(N,L,NR,NZ,NY,NX)=RTLG1s1(N,L,NR,NZ)
          RTLG2(N,L,NR,NZ,NY,NX)=RTLG2s1(N,L,NR,NZ)
          RTN2(N,L,NR,NZ,NY,NX)=RTN2s1(N,L,NR,NZ)
        ENDDO
      ENDDO
    ENDDO

    EHVST(1:2,1:4,NZ,I,NY,NX)=EHVSTs1(1:2,1:4,NZ)


    DO L=NU(NY,NX),NI(NZ,NY,NX)

      DO K=0,jcplx1
        DO N=1,2
          RDFOMC(N,K,L,NZ,NY,NX)=RDFOMCs1(N,K,L,NZ)
          RDFOMN(N,K,L,NZ,NY,NX)=RDFOMNs1(N,K,L,NZ)
          RDFOMP(N,K,L,NZ,NY,NX)=RDFOMPs1(N,K,L,NZ)
        ENDDO
      ENDDO
    ENDDO

    DO M=1,4
      DO N=0,5
        CFOPC(N,M,NZ,NY,NX)=CFOPCs1(N,M,NZ)
        CFOPN(N,M,NZ,NY,NX)=CFOPNs1(N,M,NZ)
        CFOPP(N,M,NZ,NY,NX)=CFOPPs1(N,M,NZ)
      enddo
    enddo
    RRAD1M(2,NZ,NY,NX)=RRAD1Ms1(2,NZ)
    RRAD2M(2,NZ,NY,NX)=RRAD2Ms1(2,NZ)
    PORT(2,NZ,NY,NX)=PORTs1(2,NZ)
    UPMXZH(2,NZ,NY,NX)=UPMXZHs1(2,NZ)
    UPKMZH(2,NZ,NY,NX)=UPKMZHs1(2,NZ)
    UPMNZH(2,NZ,NY,NX)=UPMNZHs1(2,NZ)
    UPMXZO(2,NZ,NY,NX)=UPMXZOs1(2,NZ)
    UPKMZO(2,NZ,NY,NX)=UPKMZOs1(2,NZ)
    UPMNZO(2,NZ,NY,NX)=UPMNZOs1(2,NZ)
    UPMXPO(2,NZ,NY,NX)=UPMXPOs1(2,NZ)
    UPKMPO(2,NZ,NY,NX)=UPKMPOs1(2,NZ)
    UPMNPO(2,NZ,NY,NX)=UPMNPOs1(2,NZ)
    RSRR(2,NZ,NY,NX)=RSRRs1(2,NZ)
    RSRA(2,NZ,NY,NX)=RSRAs1(2,NZ)
    DO N=1,2
      PORTX(N,NZ,NY,NX)=PORTXs1(N,NZ)
      RRADP(N,NZ,NY,NX)=RRADPs1(N,NZ)
      DMVL(N,NZ,NY,NX)=DMVLs1(N,NZ)
      RTLG1X(N,NZ,NY,NX)=RTLG1Xs1(N,NZ)
      RTLG2X(N,NZ,NY,NX)=RTLG2Xs1(N,NZ)
      RRAD1X(N,NZ,NY,NX)=RRAD1Xs1(N,NZ)
      RRAD2X(N,NZ,NY,NX)=RRAD2Xs1(N,NZ)
      RTAR1X(N,NZ,NY,NX)=RTAR1Xs1(N,NZ)
      RTAR2X(N,NZ,NY,NX)=RTAR2Xs1(N,NZ)
    enDDO
  ENDDO

  end subroutine PlantAPIRecv



!------------------------------------------------------------------------------------------

  subroutine PlantAPISend(I,J,NY,NX)
  use PlantAPIData, only : plt_rad
  implicit none
  integer, intent(in) :: I,J,NY,NX
  integer :: K,L,M,N,NB,NZ,NR,I1

  LYRCs1=LYRC
  I1=I+1;if(I1>LYRC)I1=1
  ZEROs1=ZERO
  ZERO2s1=ZERO2
  ALATs1=ALAT(NY,NX)
  ATCAs1=ATCA(NY,NX)
  plt_morph%ARLSSs1=ARLSS(NY,NX)
  plt_morph%ARLFCs1=ARLFC(NY,NX)
  ALTs1=ALT(NY,NX)
  CCO2EIs1=CCO2EI(NY,NX)
  CO2EIs1=CO2EI(NY,NX)
  COXYEs1=COXYE(NY,NX)
  CNETXs1=CNETX(NY,NX)
  CO2Es1=CO2E(NY,NX)
  CCO2Es1=CCO2E(NY,NX)
  CCH4Es1=CCH4E(NY,NX)
  CZ2OEs1=CZ2OE(NY,NX)
  CH2GEs1=CH2GE(NY,NX)
  CNH3Es1=CNH3E(NY,NX)
  DYLXs1=DYLX(NY,NX)
  DYLNs1=DYLN(NY,NX)
  DPTHSs1=DPTHS(NY,NX)
  DYLMs1=DYLM(NY,NX)
  IETYPs1=IETYP(NY,NX)
  IYRCs1=IYRC
  NLs1=NL(NY,NX)
  NP0s1=NP0(NY,NX)
  NJs1=NJ(NY,NX)
  NPs1=NP(NY,NX)
  NUs1=NU(NY,NX)
  OXYEs1=OXYE(NY,NX)
  RABs1=RAB(NY,NX)
  RIBs1=RIB(NY,NX)
  plt_rad%SSINNs1=SSINN(NY,NX)
  plt_rad%SSINs1=SSIN(NY,NX)
  TKWs1=TKW(1,NY,NX)
  TKAs1=TKA(NY,NX)
  plt_rad%THRMGXs1=THRMGX(NY,NX)
  plt_rad%THSs1=THS(NY,NX)
  VPAs1=VPA(NY,NX)
  XCORPs1=XCORP(NY,NX)
  ZNOONs1=ZNOON(NY,NX)
  ZEROS2s1=ZEROS2(NY,NX)
  ZEROSs1=ZEROS(NY,NX)
  ZRs1=ZR(NY,NX)
  plt_morph%ZTs1=ZT(NY,NX)
  ZDs1=ZD(NY,NX)
  IDATAs1(:)=IDATA(:)
  DCORPs1=DCORP(I,NY,NX)
  ITILLs1=ITILL(I,NY,NX)

  plt_morph%ZLs1(0)=ZL(0,NY,NX)
  DO  L=1,JC
    plt_morph%ZLs1(L)=ZL(L,NY,NX)
    plt_rad%TAUSs1(L)=TAUS(L,NY,NX)
    plt_rad%TAU0s1(L)=TAU0(L,NY,NX)
  ENDDO
  plt_rad%TAUSs1(JC+1)=TAUS(JC+1,NY,NX)
  plt_rad%TAU0s1(JC+1)=TAU0(JC+1,NY,NX)

  DO N=1,JLI
    plt_rad%ZSINs1(N)=ZSIN(N)
  ENDDO

  DO L=1,NL(NY,NX)
    CNDUs1(L)=CNDU(L,NY,NX)
    CGSGLs1(L)=CGSGL(L,NY,NX)
    CHSGLs1(L)=CHSGL(L,NY,NX)
    HGSGLs1(L)=HGSGL(L,NY,NX)
    OGSGLs1(L)=OGSGL(L,NY,NX)
    RSCSs1(L)=RSCS(L,NY,NX)
    Z2SGLs1(L)=Z2SGL(L,NY,NX)
    ZHSGLs1(L)=ZHSGL(L,NY,NX)
    DPTHZs1(L)=DPTHZ(L,NY,NX)
  ENDDO
  FVRNs1(:) = FVRN(:)
  DO L=1,NL(NY,NX)
    CO2Gs1(L)=CO2G(L,NY,NX)
    OXYGs1(L)=OXYG(L,NY,NX)
  ENDDO

  DO L=0,NL(NY,NX)
    AREA3s1(L)=AREA(3,L,NY,NX)
    BKDSs1(L)=BKDS(L,NY,NX)
    CH2P4s1(L)=CH2P4(L,NY,NX)
    CH1P4Bs1(L)=CH1P4B(L,NY,NX)
    CH2P4Bs1(L)=CH2P4B(L,NY,NX)
    CNO3Ss1(L)=CNO3S(L,NY,NX)
    CH1P4s1(L)=CH1P4(L,NY,NX)
    CNO3Bs1(L)=CNO3B(L,NY,NX)
    CNH4Ss1(L)=CNH4S(L,NY,NX)
    CNH4Bs1(L)=CNH4B(L,NY,NX)
    CO2Ss1(L)=CO2S(L,NY,NX)
    CH4Ss1(L)=CH4S(L,NY,NX)
    CCH4Ss1(L)=CCH4S(L,NY,NX)
    CZ2OSs1(L)=CZ2OS(L,NY,NX)
    CNH3Ss1(L)=CNH3S(L,NY,NX)
    CNH3Bs1(L)=CNH3B(L,NY,NX)
    CH2GSs1(L)=CH2GS(L,NY,NX)
    CLSGLs1(L)=CLSGL(L,NY,NX)
    CQSGLs1(L)=CQSGL(L,NY,NX)
    CCH4Gs1(L)=CCH4G(L,NY,NX)
    CZ2OGs1(L)=CZ2OG(L,NY,NX)
    CNH3Gs1(L)=CNH3G(L,NY,NX)
    CH2GGs1(L)=CH2GG(L,NY,NX)
    CORGCs1(L)=CORGC(L,NY,NX)
    CDPTHZs1(L)=CDPTHZ(L,NY,NX)
    FMPRs1(L)=FMPR(L,NY,NX)
    H1PO4s1(L)=H1PO4(L,NY,NX)
    H2PO4s1(L)=H2PO4(L,NY,NX)
    H1POBs1(L)=H1POB(L,NY,NX)
    H2POBs1(L)=H2POB(L,NY,NX)
    H2GSs1(L)=H2GS(L,NY,NX)
    HLSGLs1(L)=HLSGL(L,NY,NX)
    OXYSs1(L)=OXYS(L,NY,NX)
    OLSGLs1(L)=OLSGL(L,NY,NX)
    POSGLs1(L)=POSGL(L,NY,NX)
    PSISTs1(L)=PSIST(L,NY,NX)
    RPO4Ys1(L)=RPO4Y(L,NY,NX)
    RPOBYs1(L)=RPOBY(L,NY,NX)
    RP14Ys1(L)=RP14Y(L,NY,NX)
    RP1BYs1(L)=RP1BY(L,NY,NX)
    RNO3Ys1(L)=RNO3Y(L,NY,NX)
    RNH4Ys1(L)=RNH4Y(L,NY,NX)
    RNHBYs1(L)=RNHBY(L,NY,NX)
    RN3BYs1(L)=RN3BY(L,NY,NX)
    ROXYFs1(L)=ROXYF(L,NY,NX)
    RCO2Fs1(L)=RCO2F(L,NY,NX)
    ROXYLs1(L)=ROXYL(L,NY,NX)
    ROXYYs1(L)=ROXYY(L,NY,NX)
    SCO2Ls1(L)=SCO2L(L,NY,NX)
    SOXYLs1(L)=SOXYL(L,NY,NX)
    SCH4Ls1(L)=SCH4L(L,NY,NX)
    SN2OLs1(L)=SN2OL(L,NY,NX)
    SNH3Ls1(L)=SNH3L(L,NY,NX)
    SH2GLs1(L)=SH2GL(L,NY,NX)
    THETWs1(L)=THETW(L,NY,NX)
    THETYs1(L)=THETY(L,NY,NX)
    TKSs1(L)=TKS(L,NY,NX)
    TFNDs1(L)=TFND(L,NY,NX)
    VOLXs1(L)=VOLX(L,NY,NX)
    VLPOBs1(L)=VLPOB(L,NY,NX)
    VLNO3s1(L)=VLNO3(L,NY,NX)
    VLPO4s1(L)=VLPO4(L,NY,NX)
    VOLYs1(L)=VOLY(L,NY,NX)
    VOLIs1(L)=VOLI(L,NY,NX)
    VOLWs1(L)=VOLW(L,NY,NX)
    VOLAs1(L)=VOLA(L,NY,NX)
    VLNOBs1(L)=VLNOB(L,NY,NX)
    VLNH4s1(L)=VLNH4(L,NY,NX)
    VLNHBs1(L)=VLNHB(L,NY,NX)
    ZOSGLs1(L)=ZOSGL(L,NY,NX)
    ZNO3Ss1(L)=ZNO3S(L,NY,NX)
    ZNO3Bs1(L)=ZNO3B(L,NY,NX)
    ZNSGLs1(L)=ZNSGL(L,NY,NX)
    ZNH4Ss1(L)=ZNH4S(L,NY,NX)
    ZNH4Bs1(L)=ZNH4B(L,NY,NX)
    Z2OSs1(L)=Z2OS(L,NY,NX)
    ZNH3Ss1(L)=ZNH3S(L,NY,NX)
    ZNH3Bs1(L)=ZNH3B(L,NY,NX)
    ZVSGLs1(L)=ZVSGL(L,NY,NX)
    DLYR3s1(L)=DLYR(3,L,NY,NX)
    DO K=0,jcplx1
      FOSRHs1(K,L)=FOSRH(K,L,NY,NX)
      OQCs1(K,L)=OQC(K,L,NY,NX)
      OQNs1(K,L)=OQN(K,L,NY,NX)
      OQPs1(K,L)=OQP(K,L,NY,NX)
    ENDDO
  ENDDO

  DO NZ=1,NP0(NY,NX)
!plant properties begin
    ICTYPs1(NZ)=ICTYP(NZ,NY,NX)
    plt_pheno%IGTYPs1(NZ)=IGTYP(NZ,NY,NX)
    plt_pheno%ISTYPs1(NZ)=ISTYP(NZ,NY,NX)
    plt_pheno%IDTYPs1(NZ)=IDTYP(NZ,NY,NX)
    INTYPs1(NZ)=INTYP(NZ,NY,NX)
    plt_pheno%IWTYPs1(NZ)=IWTYP(NZ,NY,NX)
    plt_pheno%IPTYPs1(NZ)=IPTYP(NZ,NY,NX)
    plt_pheno%IBTYPs1(NZ)=IBTYP(NZ,NY,NX)
    IRTYPs1(NZ)=IRTYP(NZ,NY,NX)
    MYs1(NZ)=MY(NZ,NY,NX)
    ZTYPIs1(NZ)=ZTYPI(NZ,NY,NX)
    plt_photo%VCMXs1(NZ)=VCMX(NZ,NY,NX)
    plt_photo%VOMXs1(NZ)=VOMX(NZ,NY,NX)
    plt_photo%VCMX4s1(NZ)=VCMX4(NZ,NY,NX)
    plt_photo%XKCO2s1(NZ)=XKCO2(NZ,NY,NX)
    plt_photo%XKO2s1(NZ)=XKO2(NZ,NY,NX)
    XKCO24s1(NZ)=XKCO24(NZ,NY,NX)
    plt_photo%RUBPs1(NZ)=RUBP(NZ,NY,NX)
    plt_photo%PEPCs1(NZ)=PEPC(NZ,NY,NX)
    plt_photo%ETMXs1(NZ)=ETMX(NZ,NY,NX)
    plt_photo%CHLs1(NZ)=CHL(NZ,NY,NX)
    plt_photo%CHL4s1(NZ)=CHL4(NZ,NY,NX)
    plt_photo%FCO2s1(NZ)=FCO2(NZ,NY,NX)

    plt_pheno%XRNIs1(NZ)=XRNI(NZ,NY,NX)
    plt_pheno%XRLAs1(NZ)=XRLA(NZ,NY,NX)
    CTCs1(NZ)=CTC(NZ,NY,NX)
    WDLFs1(NZ)=WDLF(NZ,NY,NX)
    PBs1(NZ)=PB(NZ,NY,NX)
    plt_morph%XTLIs1(NZ)=XTLI(NZ,NY,NX)
    plt_pheno%XDLs1(NZ)=XDL(NZ,NY,NX)
    plt_pheno%XPPDs1(NZ)=XPPD(NZ,NY,NX)
    plt_morph%SLA1s1(NZ)=SLA1(NZ,NY,NX)
    plt_morph%SSL1s1(NZ)=SSL1(NZ,NY,NX)
    plt_morph%SNL1s1(NZ)=SNL1(NZ,NY,NX)
    DO  N=1,JLI
      plt_morph%CLASSs1(N,NZ)=CLASS(N,NZ,NY,NX)
    ENDDO
    CFIs1(NZ)=CFI(NZ,NY,NX)
    plt_morph%ANGBRs1(NZ)=ANGBR(NZ,NY,NX)
    plt_morph%ANGSHs1(NZ)=ANGSH(NZ,NY,NX)
    STMXs1(NZ)=STMX(NZ,NY,NX)
    SDMXs1(NZ)=SDMX(NZ,NY,NX)
    GRMXs1(NZ)=GRMX(NZ,NY,NX)
    GRDMs1(NZ)=GRDM(NZ,NY,NX)
    GFILLs1(NZ)=GFILL(NZ,NY,NX)
    WTSTDIs1(NZ)=WTSTDI(NZ,NY,NX)

!initial root values
    DO N=1,MY(NZ,NY,NX)
      RRAD1Ms1(N,NZ)=RRAD1M(N,NZ,NY,NX)
      RRAD2Ms1(N,NZ)=RRAD2M(N,NZ,NY,NX)
      PORTs1(N,NZ)=PORT(N,NZ,NY,NX)
      RSRRs1(N,NZ)=RSRR(N,NZ,NY,NX)
      RSRAs1(N,NZ)=RSRA(N,NZ,NY,NX)
      UPMXZHs1(N,NZ)=UPMXZH(N,NZ,NY,NX)
      UPKMZHs1(N,NZ)=UPKMZH(N,NZ,NY,NX)
      UPMNZHs1(N,NZ)=UPMNZH(N,NZ,NY,NX)
      UPMXZOs1(N,NZ)=UPMXZO(N,NZ,NY,NX)
      UPKMZOs1(N,NZ)=UPKMZO(N,NZ,NY,NX)
      UPMNZOs1(N,NZ)=UPMNZO(N,NZ,NY,NX)
      UPMXPOs1(N,NZ)=UPMXPO(N,NZ,NY,NX)
      UPKMPOs1(N,NZ)=UPKMPO(N,NZ,NY,NX)
      UPMNPOs1(N,NZ)=UPMNPO(N,NZ,NY,NX)
    ENDDO
    PRs1(NZ)=PR(NZ,NY,NX)
    PTSHTs1(NZ)=PTSHT(NZ,NY,NX)
    RTFQs1(NZ)=RTFQ(NZ,NY,NX)
    OSMOs1(NZ)=OSMO(NZ,NY,NX)
    plt_photo%RCSs1(NZ)=RCS(NZ,NY,NX)
    RSMXs1(NZ)=RSMX(NZ,NY,NX)

    DMLFs1(NZ)=DMLF(NZ,NY,NX)
    DMSHEs1(NZ)=DMSHE(NZ,NY,NX)
    DMSTKs1(NZ)=DMSTK(NZ,NY,NX)
    DMRSVs1(NZ)=DMRSV(NZ,NY,NX)
    DMHSKs1(NZ)=DMHSK(NZ,NY,NX)
    DMEARs1(NZ)=DMEAR(NZ,NY,NX)
    DMGRs1(NZ)=DMGR(NZ,NY,NX)
    DMRTs1(NZ)=DMRT(NZ,NY,NX)
    DMNDs1(NZ)=DMND(NZ,NY,NX)
    CNLFs1(NZ)=CNLF(NZ,NY,NX)
    CNSHEs1(NZ)=CNSHE(NZ,NY,NX)
    CNSTKs1(NZ)=CNSTK(NZ,NY,NX)
    CNRSVs1(NZ)=CNRSV(NZ,NY,NX)
    CNHSKs1(NZ)=CNHSK(NZ,NY,NX)
    CNEARs1(NZ)=CNEAR(NZ,NY,NX)
    CNGRs1(NZ)=CNGR(NZ,NY,NX)
    CNRTs1(NZ)=CNRT(NZ,NY,NX)
    CNNDs1(NZ)=CNND(NZ,NY,NX)
    CPLFs1(NZ)=CPLF(NZ,NY,NX)
    CPSHEs1(NZ)=CPSHE(NZ,NY,NX)
    CPSTKs1(NZ)=CPSTK(NZ,NY,NX)
    CPRSVs1(NZ)=CPRSV(NZ,NY,NX)
    CPHSKs1(NZ)=CPHSK(NZ,NY,NX)
    CPEARs1(NZ)=CPEAR(NZ,NY,NX)
    CPGRs1(NZ)=CPGR(NZ,NY,NX)
    CPRTs1(NZ)=CPRT(NZ,NY,NX)
    CPNDs1(NZ)=CPND(NZ,NY,NX)

!plant properties end
    plt_morph%ARLFSs1(NZ)=ARLFS(NZ,NY,NX)
    plt_rad%RADCs1(NZ)=RADC(NZ,NY,NX)
    FLWCs1(NZ)=FLWC(NZ,NY,NX)
    IYRXs1(NZ)=IYRX(NZ,NY,NX)
    IDAYXs1(NZ)=IDAYX(NZ,NY,NX)
    plt_rad%RADPs1(NZ)=RADP(NZ,NY,NX)
    IYRYs1(NZ)=IYRY(NZ,NY,NX)
    PPZs1(NZ)=PPZ(NZ,NY,NX)
    IDAYYs1(NZ)=IDAYY(NZ,NY,NX)
    CFXs1(NZ)=CFX(NZ,NY,NX)
    DATAPs1(NZ)=DATAP(NZ,NY,NX)
    GROUPIs1(NZ)=GROUPI(NZ,NY,NX)
    WTSHTAs1(NZ)=WTSHTA(NZ,NY,NX)


    DO NB=1,NBR(NZ,NY,NX)
      plt_pheno%VRNLs1(NB,NZ)=VRNL(NB,NZ,NY,NX)
      plt_pheno%VRNXs1(NB,NZ)=VRNX(NB,NZ,NY,NX)
    ENDDO

    DO L=1,JC
      DO  M=1,JSA
        DO  N=1,JLI
          PARs1(N,M,L,NZ)=PAR(N,M,L,NZ,NY,NX)
          PARDIFs1(N,M,L,NZ)=PARDIF(N,M,L,NZ,NY,NX)
        ENDDO
      ENDDO
    ENDDO
  ENDDO

  DO L=1,NL(NY,NX)
    DO M=1,NPH
      VOLWMs1(M,L)=VOLWM(M,L,NY,NX)
      VOLPMs1(M,L)=VOLPM(M,L,NY,NX)
      TORTs1(M,L)=TORT(M,L,NY,NX)
      FILMs1(M,L)=FILM(M,L,NY,NX)
      DFGSs1(M,L)=DFGS(M,L,NY,NX)
    ENDDO
  ENDDO

! sent variables also modified
  IFLGTs1=IFLGT(NY,NX)
  VOLWOUs1=VOLWOU
  PPTs1=PPT(NY,NX)
  RECOs1=RECO(NY,NX)
  WTSTGTs1=WTSTGT(NY,NX)
  ZCSNCs1=ZCSNC(NY,NX)
  ZZSNCs1=ZZSNC(NY,NX)
  ZPSNCs1=ZPSNC(NY,NX)
  plt_morph%ARSTCs1=ARSTC(NY,NX)
  TSHs1=TSH(NY,NX)
  TVOLWCs1=TVOLWC(NY,NX)
  TNBPs1=TNBP(NY,NX)
  TGPPs1=TGPP(NY,NX)
  TLECs1=TLEC(NY,NX)
  TSHCs1=TSHC(NY,NX)
  TRAUs1=TRAU(NY,NX)
  UVOLOs1=UVOLO(NY,NX)
  XHVSTCs1=XHVSTC(NY,NX)
  XHVSTNs1=XHVSTN(NY,NX)
  XHVSTPs1=XHVSTP(NY,NX)
  plt_rad%TRNs1=TRN(NY,NX)
  TN2OZs1=TN2OZ(NY,NX)
  TEVAPCs1=TEVAPC(NY,NX)
  TLEs1=TLE(NY,NX)
  TCO2Zs1=TCO2Z(NY,NX)
  TGHs1=TGH(NY,NX)
  TEVAPPs1=TEVAPP(NY,NX)
  TH2GZs1=TH2GZ(NY,NX)
  THFLXCs1=THFLXC(NY,NX)
  THRMCs1=THRMC(NY,NX)
  TOXYZs1=TOXYZ(NY,NX)
  TNH3Zs1=TNH3Z(NY,NX)
  TVOLWPs1=TVOLWP(NY,NX)
  TENGYCs1=TENGYC(NY,NX)
  TCCANs1=TCCAN(NY,NX)
  TCH4Zs1=TCH4Z(NY,NX)
  FERTs1(1:20)=FERT(1:20,I1,NY,NX)

  DO  L=1,JC
    plt_morph%ARSTTs1(L)=ARSTT(L,NY,NX)
    WGLFTs1(L)=WGLFT(L,NY,NX)
    plt_morph%ARLFTs1(L)=ARLFT(L,NY,NX)
  ENDDO

  FWOODs1(:)=FWOOD(:)
  FWOODNs1(:)=FWOODN(:)
  FWOODPs1(:)=FWOODP(:)
  FWODRs1(:)=FWODR(:)
  FWODRNs1(:)=FWODRN(:)
  FWODSNs1(:)=FWODSN(:)
  FWODRPs1(:)=FWODRP(:)
  FWODSPs1(:)=FWODSP(:)
  FWODBs1(:)=FWODB(:)
  FWODLPs1(:)=FWODLP(:)
  FWODLNs1(:)=FWODLN(:)

  DO L=0,NL(NY,NX)
    DO K=0,jcplx1
      XOQCSs1(K,L)=XOQCS(K,L,NY,NX)
      XOQNSs1(K,L)=XOQNS(K,L,NY,NX)
      XOQPSs1(K,L)=XOQPS(K,L,NY,NX)
    ENDDO
  ENDDO

  DO L=0,JZ
    RPOBXs1(L)=RPOBX(L,NY,NX)
    RP1BXs1(L)=RP1BX(L,NY,NX)
    RN3BXs1(L)=RN3BX(L,NY,NX)
    RNHBXs1(L)=RNHBX(L,NY,NX)
    RP14Xs1(L)=RP14X(L,NY,NX)
    RPO4Xs1(L)=RPO4X(L,NY,NX)
    RNO3Xs1(L)=RNO3X(L,NY,NX)
    RNH4Xs1(L)=RNH4X(L,NY,NX)
    ROXYXs1(L)=ROXYX(L,NY,NX)
    TUPHTs1(L)=TUPHT(L,NY,NX)
    TUPWTRs1(L)=TUPWTR(L,NY,NX)
    DO  N=0,1
      DO  K=1,jcplx1
        CSNTs1(K,N,L)=CSNT(K,N,L,NY,NX)
        ZSNTs1(K,N,L)=ZSNT(K,N,L,NY,NX)
        PSNTs1(K,N,L)=PSNT(K,N,L,NY,NX)
      ENDDO
    ENDDO
  ENDDO
  DO L=1,JZ
    TUPNFs1(L)=TUPNF(L,NY,NX)
    RTDNTs1(L)=RTDNT(L,NY,NX)
    TLOXYPs1(L)=TLOXYP(L,NY,NX)
    TLCO2Ps1(L)=TLCO2P(L,NY,NX)
    TLCH4Ps1(L)=TLCH4P(L,NY,NX)
    TLN2OPs1(L)=TLN2OP(L,NY,NX)
    TLNH3Ps1(L)=TLNH3P(L,NY,NX)
    TLH2GPs1(L)=TLH2GP(L,NY,NX)
    TCOFLAs1(L)=TCOFLA(L,NY,NX)
    TOXFLAs1(L)=TOXFLA(L,NY,NX)
    TCHFLAs1(L)=TCHFLA(L,NY,NX)
    TN2FLAs1(L)=TN2FLA(L,NY,NX)
    TNHFLAs1(L)=TNHFLA(L,NY,NX)
    THGFLAs1(L)=THGFLA(L,NY,NX)
    TCO2Ps1(L)=TCO2P(L,NY,NX)
    TUPOXPs1(L)=TUPOXP(L,NY,NX)
    TCO2Ss1(L)=TCO2S(L,NY,NX)
    TUPOXSs1(L)=TUPOXS(L,NY,NX)
    TUPCHSs1(L)=TUPCHS(L,NY,NX)
    TUPN2Ss1(L)=TUPN2S(L,NY,NX)
    TUPN3Ss1(L)=TUPN3S(L,NY,NX)
    TUPN3Bs1(L)=TUPN3B(L,NY,NX)
    TUPHGSs1(L)=TUPHGS(L,NY,NX)
    TUPNH4s1(L)=TUPNH4(L,NY,NX)
    TUPNO3s1(L)=TUPNO3(L,NY,NX)
    TUPH1Bs1(L)=TUPH1B(L,NY,NX)
    TUPH2Bs1(L)=TUPH2B(L,NY,NX)
    TUPNHBs1(L)=TUPNHB(L,NY,NX)
    TUPNOBs1(L)=TUPNOB(L,NY,NX)
    TUPH1Ps1(L)=TUPH1P(L,NY,NX)
    TUPH2Ps1(L)=TUPH2P(L,NY,NX)
    DO  K=0,jcplx1
      TDFOMPs1(K,L)=TDFOMP(K,L,NY,NX)
      TDFOMNs1(K,L)=TDFOMN(K,L,NY,NX)
      TDFOMCs1(K,L)=TDFOMC(K,L,NY,NX)
    ENDDO
  ENDDO


  DO NZ=1,NP0(NY,NX)
    TKCZs1(NZ)=TKCZ(NZ,NY,NX)
    SO2s1(NZ)=SO2(NZ,NY,NX)
    PSILZs1(NZ)=PSILZ(NZ,NY,NX)
    HFLXCs1(NZ)=HFLXC(NZ,NY,NX)
    CO2Qs1(NZ)=CO2Q(NZ,NY,NX)
    O2Ls1(NZ)=O2L(NZ,NY,NX)
    WTRTs1(NZ)=WTRT(NZ,NY,NX)

    plt_photo%CO2Ls1(NZ)=CO2L(NZ,NY,NX)
    EHVSTs1(1:2,1:4,NZ)=EHVST(1:2,1:4,NZ,I,NY,NX)

    IDTHs1(NZ)=IDTH(NZ,NY,NX)
    IYR0s1(NZ)=IYR0(NZ,NY,NX)
    plt_morph%NNODs1(NZ)=NNOD(NZ,NY,NX)

    plt_pheno%IDTHPs1(NZ)=IDTHP(NZ,NY,NX)
    plt_pheno%IDTHRs1(NZ)=IDTHR(NZ,NY,NX)
    CNRTSs1(NZ)=CNRTS(NZ,NY,NX)
    CPRTSs1(NZ)=CPRTS(NZ,NY,NX)

    ZEROQs1(NZ)=ZEROQ(NZ,NY,NX)
    SSTXs1(NZ)=SSTX(NZ,NY,NX)
    plt_rad%FRADPs1(NZ)=FRADP(NZ,NY,NX)
    RNH3Cs1(NZ)=RNH3C(NZ,NY,NX)
    DTKCs1(NZ)=DTKC(NZ,NY,NX)
    ZTYPs1(NZ)=ZTYP(NZ,NY,NX)
    HTCs1(NZ)=HTC(NZ,NY,NX)

    WTLFs1(NZ)=WTLF(NZ,NY,NX)
    EPs1(NZ)=EP(NZ,NY,NX)
    WTEARs1(NZ)=WTEAR(NZ,NY,NX)
    WTRTSs1(NZ)=WTRTS(NZ,NY,NX)
    WTRTSNs1(NZ)=WTRTSN(NZ,NY,NX)
    WTRTSPs1(NZ)=WTRTSP(NZ,NY,NX)
    WTHSKs1(NZ)=WTHSK(NZ,NY,NX)
    WTRSVs1(NZ)=WTRSV(NZ,NY,NX)
    WVSTKs1(NZ)=WVSTK(NZ,NY,NX)
    WTSTKs1(NZ)=WTSTK(NZ,NY,NX)
    CHILLs1(NZ)=CHILL(NZ,NY,NX)
    WTSHEs1(NZ)=WTSHE(NZ,NY,NX)
    PSILOs1(NZ)=PSILO(NZ,NY,NX)

    WTGRs1(NZ)=WTGR(NZ,NY,NX)
    TCCs1(NZ)=TCC(NZ,NY,NX)
    CWSRTs1(NZ)=CWSRT(NZ,NY,NX)
    plt_photo%RSMHs1(NZ)=RSMH(NZ,NY,NX)
    WTRTAs1(NZ)=WTRTA(NZ,NY,NX)
    plt_morph%CFs1(NZ)=CF(NZ,NY,NX)

    PPIs1(NZ)=PPI(NZ,NY,NX)
    PPXs1(NZ)=PPX(NZ,NY,NX)
    VOXYFs1(NZ)=VOXYF(NZ,NY,NX)
    ENGYXs1(NZ)=ENGYX(NZ,NY,NX)
    TCO2As1(NZ)=TCO2A(NZ,NY,NX)
    CTRANs1(NZ)=CTRAN(NZ,NY,NX)

    plt_morph%NBTs1(NZ)=NBT(NZ,NY,NX)
    plt_morph%NGs1(NZ)=NG(NZ,NY,NX)
    plt_pheno%IFLGIs1(NZ)=IFLGI(NZ,NY,NX)
    plt_morph%NIXs1(NZ)=NIX(NZ,NY,NX)
    plt_morph%NRTs1(NZ)=NRT(NZ,NY,NX)
    plt_morph%NB1s1(NZ)=NB1(NZ,NY,NX)
    plt_morph%NBRs1(NZ)=NBR(NZ,NY,NX)

    IFLGCs1(NZ)=IFLGC(NZ,NY,NX)
    IDAY0s1(NZ)=IDAY0(NZ,NY,NX)
    IDAYHs1(NZ)=IDAYH(NZ,NY,NX)
    IYRHs1(NZ)=IYRH(NZ,NY,NX)


    HVSTs1(NZ)=HVST(NZ,I,NY,NX)
    IHVSTs1(NZ)=IHVST(NZ,I,NY,NX)
    JHVSTs1(NZ)=JHVST(NZ,I,NY,NX)
    THINs1(NZ)=THIN(NZ,I,NY,NX)
    plt_morph%ARSTPs1(NZ)=ARSTP(NZ,NY,NX)
    plt_morph%ARLFPs1(NZ)=ARLFP(NZ,NY,NX)
    BALCs1(NZ)=BALC(NZ,NY,NX)
    BALNs1(NZ)=BALN(NZ,NY,NX)
    BALPs1(NZ)=BALP(NZ,NY,NX)
    plt_photo%O2Is1(NZ)=O2I(NZ,NY,NX)
    plt_photo%CO2Is1(NZ)=CO2I(NZ,NY,NX)
    CCPOLPs1(NZ)=CCPOLP(NZ,NY,NX)
    CPOOLPs1(NZ)=CPOOLP(NZ,NY,NX)
    CPOLNPs1(NZ)=CPOLNP(NZ,NY,NX)
    CCPLNPs1(NZ)=CCPLNP(NZ,NY,NX)
    CZPOLPs1(NZ)=CZPOLP(NZ,NY,NX)
    CPPOLPs1(NZ)=CPPOLP(NZ,NY,NX)
    CNETs1(NZ)=CNET(NZ,NY,NX)
    CARBNs1(NZ)=CARBN(NZ,NY,NX)

    CNWSs1(NZ)=CNWS(NZ,NY,NX)
    CPWSs1(NZ)=CPWS(NZ,NY,NX)

    DCO2s1(NZ)=DCO2(NZ,NY,NX)
    FMOLs1(NZ)=FMOL(NZ,NY,NX)
    FNODs1(NZ)=FNOD(NZ,NY,NX)

    HTCTLs1(NZ)=HTCTL(NZ,NY,NX)
    HCSNCs1(NZ)=HCSNC(NZ,NY,NX)
    HZSNCs1(NZ)=HZSNC(NZ,NY,NX)
    HPSNCs1(NZ)=HPSNC(NZ,NY,NX)
    HVSTCs1(NZ)=HVSTC(NZ,NY,NX)
    HVSTNs1(NZ)=HVSTN(NZ,NY,NX)
    HVSTPs1(NZ)=HVSTP(NZ,NY,NX)
    HCUPTKs1(NZ)=HCUPTK(NZ,NY,NX)
    HZUPTKs1(NZ)=HZUPTK(NZ,NY,NX)
    HPUPTKs1(NZ)=HPUPTK(NZ,NY,NX)
    HTSTZs1(NZ)=HTSTZ(NZ,NY,NX)
    plt_morph%NIs1(NZ)=NI(NZ,NY,NX)
    RAs1(NZ)=RA(NZ,NY,NX)
    RCs1(NZ)=RC(NZ,NY,NX)
    TKCs1(NZ)=TKC(NZ,NY,NX)
    SFLXCs1(NZ)=SFLXC(NZ,NY,NX)
    plt_rad%RAD1s1(NZ)=RAD1(NZ,NY,NX)
    plt_rad%THRM1s1(NZ)=THRM1(NZ,NY,NX)
    EFLXCs1(NZ)=EFLXC(NZ,NY,NX)
    EVAPCs1(NZ)=EVAPC(NZ,NY,NX)
    RSMNs1(NZ)=RSMN(NZ,NY,NX)
    OFFSTs1(NZ)=OFFST(NZ,NY,NX)
    OSTRs1(NZ)=OSTR(NZ,NY,NX)
    PPs1(NZ)=PP(NZ,NY,NX)
    PSILTs1(NZ)=PSILT(NZ,NY,NX)
    PPOOLPs1(NZ)=PPOOLP(NZ,NY,NX)
    PPOLNPs1(NZ)=PPOLNP(NZ,NY,NX)
    PSILGs1(NZ)=PSILG(NZ,NY,NX)
    RCMXs1(NZ)=RCMX(NZ,NY,NX)
    RCO2Zs1(NZ)=RCO2Z(NZ,NY,NX)
    ROXYZs1(NZ)=ROXYZ(NZ,NY,NX)
    RCH4Zs1(NZ)=RCH4Z(NZ,NY,NX)
    RN2OZs1(NZ)=RN2OZ(NZ,NY,NX)
    RNH3Zs1(NZ)=RNH3Z(NZ,NY,NX)
    RH2GZs1(NZ)=RH2GZ(NZ,NY,NX)
    RSETCs1(NZ)=RSETC(NZ,NY,NX)
    RSETNs1(NZ)=RSETN(NZ,NY,NX)
    RSETPs1(NZ)=RSETP(NZ,NY,NX)
    RAZs1(NZ)=RAZ(NZ,NY,NX)
    SCO2s1(NZ)=SCO2(NZ,NY,NX)
    plt_morph%SDPTHs1(NZ)=SDPTH(NZ,NY,NX)
    plt_morph%SDPTHIs1(NZ)=SDPTHI(NZ,NY,NX)
    plt_morph%SDLGs1(NZ)=SDLG(NZ,NY,NX)
    plt_morph%SDVLs1(NZ)=SDVL(NZ,NY,NX)
    plt_morph%SDARs1(NZ)=SDAR(NZ,NY,NX)
    TCZs1(NZ)=TCZ(NZ,NY,NX)
    TCGs1(NZ)=TCG(NZ,NY,NX)
    TCXs1(NZ)=TCX(NZ,NY,NX)
    TKGs1(NZ)=TKG(NZ,NY,NX)
    TFN3s1(NZ)=TFN3(NZ,NY,NX)
    TCSN0s1(NZ)=TCSN0(NZ,NY,NX)
    TZSN0s1(NZ)=TZSN0(NZ,NY,NX)
    TPSN0s1(NZ)=TPSN0(NZ,NY,NX)
    TCSNCs1(NZ)=TCSNC(NZ,NY,NX)
    TZSNCs1(NZ)=TZSNC(NZ,NY,NX)
    TPSNCs1(NZ)=TPSNC(NZ,NY,NX)
    TCO2Ts1(NZ)=TCO2T(NZ,NY,NX)
    plt_photo%XKCO2Ls1(NZ)=XKCO2L(NZ,NY,NX)
    plt_photo%XKCO2Os1(NZ)=XKCO2O(NZ,NY,NX)
    TCUPTKs1(NZ)=TCUPTK(NZ,NY,NX)
    THVSTCs1(NZ)=THVSTC(NZ,NY,NX)
    TNH3Cs1(NZ)=TNH3C(NZ,NY,NX)
    TZUPTKs1(NZ)=TZUPTK(NZ,NY,NX)
    THVSTNs1(NZ)=THVSTN(NZ,NY,NX)
    TZUPFXs1(NZ)=TZUPFX(NZ,NY,NX)
    TPUPTKs1(NZ)=TPUPTK(NZ,NY,NX)
    THVSTPs1(NZ)=THVSTP(NZ,NY,NX)
    UPOMCs1(NZ)=UPOMC(NZ,NY,NX)
    UPNFs1(NZ)=UPNF(NZ,NY,NX)
    UPNO3s1(NZ)=UPNO3(NZ,NY,NX)
    UPNH4s1(NZ)=UPNH4(NZ,NY,NX)
    UPOMNs1(NZ)=UPOMN(NZ,NY,NX)
    UPH1Ps1(NZ)=UPH1P(NZ,NY,NX)
    UPH2Ps1(NZ)=UPH2P(NZ,NY,NX)
    UPOMPs1(NZ)=UPOMP(NZ,NY,NX)
    VOLWCs1(NZ)=VOLWC(NZ,NY,NX)
    VHCPCs1(NZ)=VHCPC(NZ,NY,NX)
    VCH4Fs1(NZ)=VCH4F(NZ,NY,NX)
    VCO2Fs1(NZ)=VCO2F(NZ,NY,NX)
    VN2OFs1(NZ)=VN2OF(NZ,NY,NX)
    VNH3Fs1(NZ)=VNH3F(NZ,NY,NX)
    VPO4Fs1(NZ)=VPO4F(NZ,NY,NX)
    VOLWPs1(NZ)=VOLWP(NZ,NY,NX)
    WSTRs1(NZ)=WSTR(NZ,NY,NX)
    WTRVXs1(NZ)=WTRVX(NZ,NY,NX)
    WTRVCs1(NZ)=WTRVC(NZ,NY,NX)
    WTLSs1(NZ)=WTLS(NZ,NY,NX)
    WTSHTs1(NZ)=WTSHT(NZ,NY,NX)
    WTSTGs1(NZ)=WTSTG(NZ,NY,NX)
    WTSTGNs1(NZ)=WTSTGN(NZ,NY,NX)
    WTSTGPs1(NZ)=WTSTGP(NZ,NY,NX)
    WTNDs1(NZ)=WTND(NZ,NY,NX)
    WTNDNs1(NZ)=WTNDN(NZ,NY,NX)
    WTRTNs1(NZ)=WTRTN(NZ,NY,NX)
    WTSHNs1(NZ)=WTSHN(NZ,NY,NX)
    WTRVNs1(NZ)=WTRVN(NZ,NY,NX)
    WTNDPs1(NZ)=WTNDP(NZ,NY,NX)
    WTRTPs1(NZ)=WTRTP(NZ,NY,NX)
    WTSHPs1(NZ)=WTSHP(NZ,NY,NX)
    WTRVPs1(NZ)=WTRVP(NZ,NY,NX)

    ZPOOLPs1(NZ)=ZPOOLP(NZ,NY,NX)
    ZPOLNPs1(NZ)=ZPOLNP(NZ,NY,NX)
    ZEROLs1(NZ)=ZEROL(NZ,NY,NX)
    ZEROPs1(NZ)=ZEROP(NZ,NY,NX)
    plt_morph%ZCs1(NZ)=ZC(NZ,NY,NX)
    ZNPPs1(NZ)=ZNPP(NZ,NY,NX)


    DO L=1,NL(NY,NX)
      DO K=0,jcplx1
        DO N=1,2
          RDFOMCs1(N,K,L,NZ)=RDFOMC(N,K,L,NZ,NY,NX)
          RDFOMNs1(N,K,L,NZ)=RDFOMN(N,K,L,NZ,NY,NX)
          RDFOMPs1(N,K,L,NZ)=RDFOMP(N,K,L,NZ,NY,NX)
        ENDDO
      ENDDO
    ENDDO

    DO NB=1,NBR(NZ,NY,NX)
      plt_photo%FDBKs1(NB,NZ)=FDBK(NB,NZ,NY,NX)
      plt_photo%FDBKXs1(NB,NZ)=FDBKX(NB,NZ,NY,NX)
      plt_pheno%ATRPs1(NB,NZ)=ATRP(NB,NZ,NY,NX)
      plt_morph%ARLFZs1(NB,NZ)=ARLFZ(NB,NZ,NY,NX)
      plt_morph%ARLFBs1(NB,NZ)=ARLFB(NB,NZ,NY,NX)
      CPOOLs1(NB,NZ)=CPOOL(NB,NZ,NY,NX)
      CPOLNBs1(NB,NZ)=CPOLNB(NB,NZ,NY,NX)
      CCPOLBs1(NB,NZ)=CCPOLB(NB,NZ,NY,NX)
      CZPOLBs1(NB,NZ)=CZPOLB(NB,NZ,NY,NX)
      CPPOLBs1(NB,NZ)=CPPOLB(NB,NZ,NY,NX)
      plt_pheno%DGSTGIs1(NB,NZ)=DGSTGI(NB,NZ,NY,NX)
      plt_pheno%DGSTGFs1(NB,NZ)=DGSTGF(NB,NZ,NY,NX)
      plt_pheno%FLG4s1(NB,NZ)=FLG4(NB,NZ,NY,NX)
      plt_pheno%FLGZs1(NB,NZ)=FLGZ(NB,NZ,NY,NX)
      plt_pheno%GROUPs1(NB,NZ)=GROUP(NB,NZ,NY,NX)
      plt_pheno%GSTGIs1(NB,NZ)=GSTGI(NB,NZ,NY,NX)
      plt_pheno%GSTGFs1(NB,NZ)=GSTGF(NB,NZ,NY,NX)
      plt_morph%GRNXBs1(NB,NZ)=GRNXB(NB,NZ,NY,NX)
      plt_morph%GRNOBs1(NB,NZ)=GRNOB(NB,NZ,NY,NX)
      GRWTBs1(NB,NZ)=GRWTB(NB,NZ,NY,NX)
      plt_morph%HTSHEXs1(NB,NZ)=HTSHEX(NB,NZ,NY,NX)
      plt_pheno%IDTHBs1(NB,NZ)=IDTHB(NB,NZ,NY,NX)
      plt_pheno%IFLGPs1(NB,NZ)=IFLGP(NB,NZ,NY,NX)
      plt_pheno%IFLGFs1(NB,NZ)=IFLGF(NB,NZ,NY,NX)
      plt_pheno%IFLGEs1(NB,NZ)=IFLGE(NB,NZ,NY,NX)
      plt_pheno%IFLGAs1(NB,NZ)=IFLGA(NB,NZ,NY,NX)
      plt_pheno%IFLGGs1(NB,NZ)=IFLGG(NB,NZ,NY,NX)
      plt_pheno%IFLGRs1(NB,NZ)=IFLGR(NB,NZ,NY,NX)
      plt_pheno%IFLGQs1(NB,NZ)=IFLGQ(NB,NZ,NY,NX)
      plt_pheno%KVSTGs1(NB,NZ)=KVSTG(NB,NZ,NY,NX)
      plt_pheno%KVSTGNs1(NB,NZ)=KVSTGN(NB,NZ,NY,NX)
      plt_morph%NBTBs1(NB,NZ)=NBTB(NB,NZ,NY,NX)
      plt_morph%PSTGs1(NB,NZ)=PSTG(NB,NZ,NY,NX)
      plt_morph%PSTGIs1(NB,NZ)=PSTGI(NB,NZ,NY,NX)
      plt_morph%PSTGFs1(NB,NZ)=PSTGF(NB,NZ,NY,NX)
      PPOOLs1(NB,NZ)=PPOOL(NB,NZ,NY,NX)
      PPOLNBs1(NB,NZ)=PPOLNB(NB,NZ,NY,NX)
      RCCLXs1(NB,NZ)=RCCLX(NB,NZ,NY,NX)
      RCZLXs1(NB,NZ)=RCZLX(NB,NZ,NY,NX)
      RCPLXs1(NB,NZ)=RCPLX(NB,NZ,NY,NX)
      RCCSXs1(NB,NZ)=RCCSX(NB,NZ,NY,NX)
      RCZSXs1(NB,NZ)=RCZSX(NB,NZ,NY,NX)
      RCPSXs1(NB,NZ)=RCPSX(NB,NZ,NY,NX)
      RNH3Bs1(NB,NZ)=RNH3B(NB,NZ,NY,NX)
      plt_pheno%TGSTGIs1(NB,NZ)=TGSTGI(NB,NZ,NY,NX)
      plt_pheno%TGSTGFs1(NB,NZ)=TGSTGF(NB,NZ,NY,NX)
      plt_pheno%VSTGXs1(NB,NZ)=VSTGX(NB,NZ,NY,NX)
      plt_morph%VSTGs1(NB,NZ)=VSTG(NB,NZ,NY,NX)
      plt_pheno%VRNYs1(NB,NZ)=VRNY(NB,NZ,NY,NX)
      plt_pheno%VRNZs1(NB,NZ)=VRNZ(NB,NZ,NY,NX)
      plt_pheno%VRNSs1(NB,NZ)=VRNS(NB,NZ,NY,NX)
      plt_pheno%VRNFs1(NB,NZ)=VRNF(NB,NZ,NY,NX)
      WTLSBs1(NB,NZ)=WTLSB(NB,NZ,NY,NX)
      WTRSVBs1(NB,NZ)=WTRSVB(NB,NZ,NY,NX)
      WTLFBs1(NB,NZ)=WTLFB(NB,NZ,NY,NX)
      WTNDBs1(NB,NZ)=WTNDB(NB,NZ,NY,NX)
      WTSHEBs1(NB,NZ)=WTSHEB(NB,NZ,NY,NX)
      WTEARBs1(NB,NZ)=WTEARB(NB,NZ,NY,NX)
      WTHSKBs1(NB,NZ)=WTHSKB(NB,NZ,NY,NX)
      WTRSBNs1(NB,NZ)=WTRSBN(NB,NZ,NY,NX)
      WTLFBNs1(NB,NZ)=WTLFBN(NB,NZ,NY,NX)
      WTNDBNs1(NB,NZ)=WTNDBN(NB,NZ,NY,NX)
      WTSHBNs1(NB,NZ)=WTSHBN(NB,NZ,NY,NX)
      WTEABNs1(NB,NZ)=WTEABN(NB,NZ,NY,NX)
      WTHSBNs1(NB,NZ)=WTHSBN(NB,NZ,NY,NX)
      WTRSBPs1(NB,NZ)=WTRSBP(NB,NZ,NY,NX)
      WTLFBPs1(NB,NZ)=WTLFBP(NB,NZ,NY,NX)
      WTNDBPs1(NB,NZ)=WTNDBP(NB,NZ,NY,NX)
      WTSHBPs1(NB,NZ)=WTSHBP(NB,NZ,NY,NX)
      WTEABPs1(NB,NZ)=WTEABP(NB,NZ,NY,NX)
      WTHSBPs1(NB,NZ)=WTHSBP(NB,NZ,NY,NX)
      WTGRBs1(NB,NZ)=WTGRB(NB,NZ,NY,NX)
      WTGRBNs1(NB,NZ)=WTGRBN(NB,NZ,NY,NX)
      WTGRBPs1(NB,NZ)=WTGRBP(NB,NZ,NY,NX)
      WTSTKBs1(NB,NZ)=WTSTKB(NB,NZ,NY,NX)
      WTSTBNs1(NB,NZ)=WTSTBN(NB,NZ,NY,NX)
      WTSTBPs1(NB,NZ)=WTSTBP(NB,NZ,NY,NX)
      WTSHTBs1(NB,NZ)=WTSHTB(NB,NZ,NY,NX)
      WTSHTNs1(NB,NZ)=WTSHTN(NB,NZ,NY,NX)
      WTSHTPs1(NB,NZ)=WTSHTP(NB,NZ,NY,NX)
      WGLFXs1(NB,NZ)=WGLFX(NB,NZ,NY,NX)
      WGLFNXs1(NB,NZ)=WGLFNX(NB,NZ,NY,NX)
      WGLFPXs1(NB,NZ)=WGLFPX(NB,NZ,NY,NX)
      WGSHEXs1(NB,NZ)=WGSHEX(NB,NZ,NY,NX)
      WGSHNXs1(NB,NZ)=WGSHNX(NB,NZ,NY,NX)
      WGSHPXs1(NB,NZ)=WGSHPX(NB,NZ,NY,NX)
      WTSTXBs1(NB,NZ)=WTSTXB(NB,NZ,NY,NX)
      WTSTXNs1(NB,NZ)=WTSTXN(NB,NZ,NY,NX)
      WTSTXPs1(NB,NZ)=WTSTXP(NB,NZ,NY,NX)
      WVSTKBs1(NB,NZ)=WVSTKB(NB,NZ,NY,NX)
      ZPOOLs1(NB,NZ)=ZPOOL(NB,NZ,NY,NX)
      ZPOLNBs1(NB,NZ)=ZPOLNB(NB,NZ,NY,NX)
      DO M=1,10
        plt_pheno%IDAYs1(M,NB,NZ)=IDAY(M,NB,NZ,NY,NX)
      ENDDO
      DO K=1,JNODS
        DO  L=1,JC
          DO N=1,JLI
            plt_morph%SURFs1(N,L,K,NB,NZ)=SURF(N,L,K,NB,NZ,NY,NX)
            SURFXs1(N,L,K,NB,NZ)=SURFX(N,L,K,NB,NZ,NY,NX)
          ENDDO
        ENDDO
        CPOOL3s1(K,NB,NZ)=CPOOL3(K,NB,NZ,NY,NX)
        CPOOL4s1(K,NB,NZ)=CPOOL4(K,NB,NZ,NY,NX)
        CO2Bs1(K,NB,NZ)=CO2B(K,NB,NZ,NY,NX)
        COMPLs1(K,NB,NZ)=COMPL(K,NB,NZ,NY,NX)
        CBXNs1(K,NB,NZ)=CBXN(K,NB,NZ,NY,NX)
        CBXN4s1(K,NB,NZ)=CBXN4(K,NB,NZ,NY,NX)
        ETGROs1(K,NB,NZ)=ETGRO(K,NB,NZ,NY,NX)
        ETGR4s1(K,NB,NZ)=ETGR4(K,NB,NZ,NY,NX)
        FDBK4s1(K,NB,NZ)=FDBK4(K,NB,NZ,NY,NX)
        HCOBs1(K,NB,NZ)=HCOB(K,NB,NZ,NY,NX)
        VCGROs1(K,NB,NZ)=VCGRO(K,NB,NZ,NY,NX)
        VGROs1(K,NB,NZ)=VGRO(K,NB,NZ,NY,NX)
        VCGR4s1(K,NB,NZ)=VCGR4(K,NB,NZ,NY,NX)
        VGRO4s1(K,NB,NZ)=VGRO4(K,NB,NZ,NY,NX)
      ENDDO
      DO K=0,JNODS
        plt_morph%ARLF1s1(K,NB,NZ)=ARLF(K,NB,NZ,NY,NX)
        plt_morph%HTNODXs1(K,NB,NZ)=HTNODX(K,NB,NZ,NY,NX)
        plt_morph%HTSHEs1(K,NB,NZ)=HTSHE(K,NB,NZ,NY,NX)
        plt_morph%HTNODEs1(K,NB,NZ)=HTNODE(K,NB,NZ,NY,NX)
        WGNODEs1(K,NB,NZ)=WGNODE(K,NB,NZ,NY,NX)
        WGNODNs1(K,NB,NZ)=WGNODN(K,NB,NZ,NY,NX)
        WGNODPs1(K,NB,NZ)=WGNODP(K,NB,NZ,NY,NX)
        WGLFs1(K,NB,NZ)=WGLF(K,NB,NZ,NY,NX)
        WGLFNs1(K,NB,NZ)=WGLFN(K,NB,NZ,NY,NX)
        WGLFPs1(K,NB,NZ)=WGLFP(K,NB,NZ,NY,NX)
        WSLFs1(K,NB,NZ)=WSLF(K,NB,NZ,NY,NX)
        WGSHEs1(K,NB,NZ)=WGSHE(K,NB,NZ,NY,NX)
        WGSHNs1(K,NB,NZ)=WGSHN(K,NB,NZ,NY,NX)
        WGSHPs1(K,NB,NZ)=WGSHP(K,NB,NZ,NY,NX)
        WSSHEs1(K,NB,NZ)=WSSHE(K,NB,NZ,NY,NX)
      ENDDO

      DO K=0,JNODS
        DO  L=1,JC
          plt_morph%ARLFLs1(L,K,NB,NZ)=ARLFL(L,K,NB,NZ,NY,NX)
          WGLFLs1(L,K,NB,NZ)=WGLFL(L,K,NB,NZ,NY,NX)
          WGLFLNs1(L,K,NB,NZ)=WGLFLN(L,K,NB,NZ,NY,NX)
          WGLFLPs1(L,K,NB,NZ)=WGLFLP(L,K,NB,NZ,NY,NX)
        ENDDO
      ENDDO
      DO  L=1,JC
        plt_morph%ARSTKs1(L,NB,NZ)=ARSTK(L,NB,NZ,NY,NX)
      ENDDO
    enddo

    DO L=1,NL(NY,NX)
      DO N=1,MY(NZ,NY,NX)
        CPOOLRs1(N,L,NZ)=CPOOLR(N,L,NZ,NY,NX)
        CCPOLRs1(N,L,NZ)=CCPOLR(N,L,NZ,NY,NX)
        CZPOLRs1(N,L,NZ)=CZPOLR(N,L,NZ,NY,NX)
        CPPOLRs1(N,L,NZ)=CPPOLR(N,L,NZ,NY,NX)
        CO2Ps1(N,L,NZ)=CO2P(N,L,NZ,NY,NX)
        CO2As1(N,L,NZ)=CO2A(N,L,NZ,NY,NX)
        CH4Ps1(N,L,NZ)=CH4P(N,L,NZ,NY,NX)
        CH4As1(N,L,NZ)=CH4A(N,L,NZ,NY,NX)
        CWSRTLs1(N,L,NZ)=CWSRTL(N,L,NZ,NY,NX)
        H2GPs1(N,L,NZ)=H2GP(N,L,NZ,NY,NX)
        H2GAs1(N,L,NZ)=H2GA(N,L,NZ,NY,NX)
        OXYPs1(N,L,NZ)=OXYP(N,L,NZ,NY,NX)
        OXYAs1(N,L,NZ)=OXYA(N,L,NZ,NY,NX)
        PSIRTs1(N,L,NZ)=PSIRT(N,L,NZ,NY,NX)
        PSIROs1(N,L,NZ)=PSIRO(N,L,NZ,NY,NX)
        PSIRGs1(N,L,NZ)=PSIRG(N,L,NZ,NY,NX)
        PPOOLRs1(N,L,NZ)=PPOOLR(N,L,NZ,NY,NX)
        RUPNHBs1(N,L,NZ)=RUPNHB(N,L,NZ,NY,NX)
        RUPNH4s1(N,L,NZ)=RUPNH4(N,L,NZ,NY,NX)
        RUPH2Ps1(N,L,NZ)=RUPH2P(N,L,NZ,NY,NX)
        RUPNOBs1(N,L,NZ)=RUPNOB(N,L,NZ,NY,NX)
        RUPNO3s1(N,L,NZ)=RUPNO3(N,L,NZ,NY,NX)
        RUPH1Bs1(N,L,NZ)=RUPH1B(N,L,NZ,NY,NX)
        RUPH1Ps1(N,L,NZ)=RUPH1P(N,L,NZ,NY,NX)
        RUPH2Bs1(N,L,NZ)=RUPH2B(N,L,NZ,NY,NX)
        RUONHBs1(N,L,NZ)=RUONHB(N,L,NZ,NY,NX)
        RUONH4s1(N,L,NZ)=RUONH4(N,L,NZ,NY,NX)
        RUOH2Ps1(N,L,NZ)=RUOH2P(N,L,NZ,NY,NX)
        RUONOBs1(N,L,NZ)=RUONOB(N,L,NZ,NY,NX)
        RUONO3s1(N,L,NZ)=RUONO3(N,L,NZ,NY,NX)
        RUOH1Bs1(N,L,NZ)=RUOH1B(N,L,NZ,NY,NX)
        RUOH1Ps1(N,L,NZ)=RUOH1P(N,L,NZ,NY,NX)
        RUOH2Bs1(N,L,NZ)=RUOH2B(N,L,NZ,NY,NX)
        RUCNHBs1(N,L,NZ)=RUCNHB(N,L,NZ,NY,NX)
        RUCNH4s1(N,L,NZ)=RUCNH4(N,L,NZ,NY,NX)
        RUCH2Ps1(N,L,NZ)=RUCH2P(N,L,NZ,NY,NX)
        RUCNOBs1(N,L,NZ)=RUCNOB(N,L,NZ,NY,NX)
        RUCNO3s1(N,L,NZ)=RUCNO3(N,L,NZ,NY,NX)
        RUCH1Bs1(N,L,NZ)=RUCH1B(N,L,NZ,NY,NX)
        RUCH1Ps1(N,L,NZ)=RUCH1P(N,L,NZ,NY,NX)
        RUCH2Bs1(N,L,NZ)=RUCH2B(N,L,NZ,NY,NX)
        RCO2Ms1(N,L,NZ)=RCO2M(N,L,NZ,NY,NX)
        RCO2Ns1(N,L,NZ)=RCO2N(N,L,NZ,NY,NX)
        RCO2As1(N,L,NZ)=RCO2A(N,L,NZ,NY,NX)
        RTN1s1(N,L,NZ)=RTN1(N,L,NZ,NY,NX)
        RTNLs1(N,L,NZ)=RTNL(N,L,NZ,NY,NX)
        RTLGPs1(N,L,NZ)=RTLGP(N,L,NZ,NY,NX)
        RTDNPs1(N,L,NZ)=RTDNP(N,L,NZ,NY,NX)
        RTVLPs1(N,L,NZ)=RTVLP(N,L,NZ,NY,NX)
        RTVLWs1(N,L,NZ)=RTVLW(N,L,NZ,NY,NX)
        RRAD1s1(N,L,NZ)=RRAD1(N,L,NZ,NY,NX)
        RRAD2s1(N,L,NZ)=RRAD2(N,L,NZ,NY,NX)
        RTARPs1(N,L,NZ)=RTARP(N,L,NZ,NY,NX)
        RTLGAs1(N,L,NZ)=RTLGA(N,L,NZ,NY,NX)
        RCO2Ps1(N,L,NZ)=RCO2P(N,L,NZ,NY,NX)
        RUPOXPs1(N,L,NZ)=RUPOXP(N,L,NZ,NY,NX)
        RCO2Ss1(N,L,NZ)=RCO2S(N,L,NZ,NY,NX)
        RUPOXSs1(N,L,NZ)=RUPOXS(N,L,NZ,NY,NX)
        RUPCHSs1(N,L,NZ)=RUPCHS(N,L,NZ,NY,NX)
        RUPN2Ss1(N,L,NZ)=RUPN2S(N,L,NZ,NY,NX)
        RUPN3Ss1(N,L,NZ)=RUPN3S(N,L,NZ,NY,NX)
        RUPN3Bs1(N,L,NZ)=RUPN3B(N,L,NZ,NY,NX)
        RUPHGSs1(N,L,NZ)=RUPHGS(N,L,NZ,NY,NX)
        RCOFLAs1(N,L,NZ)=RCOFLA(N,L,NZ,NY,NX)
        ROXFLAs1(N,L,NZ)=ROXFLA(N,L,NZ,NY,NX)
        RCHFLAs1(N,L,NZ)=RCHFLA(N,L,NZ,NY,NX)
        RN2FLAs1(N,L,NZ)=RN2FLA(N,L,NZ,NY,NX)
        RNHFLAs1(N,L,NZ)=RNHFLA(N,L,NZ,NY,NX)
        RHGFLAs1(N,L,NZ)=RHGFLA(N,L,NZ,NY,NX)
        RCODFAs1(N,L,NZ)=RCODFA(N,L,NZ,NY,NX)
        ROXDFAs1(N,L,NZ)=ROXDFA(N,L,NZ,NY,NX)
        RCHDFAs1(N,L,NZ)=RCHDFA(N,L,NZ,NY,NX)
        RN2DFAs1(N,L,NZ)=RN2DFA(N,L,NZ,NY,NX)
        RNHDFAs1(N,L,NZ)=RNHDFA(N,L,NZ,NY,NX)
        RHGDFAs1(N,L,NZ)=RHGDFA(N,L,NZ,NY,NX)
        ROXYPs1(N,L,NZ)=ROXYP(N,L,NZ,NY,NX)
        RUNNHPs1(N,L,NZ)=RUNNHP(N,L,NZ,NY,NX)
        RUNNBPs1(N,L,NZ)=RUNNBP(N,L,NZ,NY,NX)
        RUNNOPs1(N,L,NZ)=RUNNOP(N,L,NZ,NY,NX)
        RUNNXPs1(N,L,NZ)=RUNNXP(N,L,NZ,NY,NX)
        RUPP2Ps1(N,L,NZ)=RUPP2P(N,L,NZ,NY,NX)
        RUPP2Bs1(N,L,NZ)=RUPP2B(N,L,NZ,NY,NX)
        RUPP1Ps1(N,L,NZ)=RUPP1P(N,L,NZ,NY,NX)
        RUPP1Bs1(N,L,NZ)=RUPP1B(N,L,NZ,NY,NX)
        UPWTRs1(N,L,NZ)=UPWTR(N,L,NZ,NY,NX)
        WFRs1(N,L,NZ)=WFR(N,L,NZ,NY,NX)
        WTRTLs1(N,L,NZ)=WTRTL(N,L,NZ,NY,NX)
        WTRTDs1(N,L,NZ)=WTRTD(N,L,NZ,NY,NX)
        WSRTLs1(N,L,NZ)=WSRTL(N,L,NZ,NY,NX)
        ZPOOLRs1(N,L,NZ)=ZPOOLR(N,L,NZ,NY,NX)
        Z2OPs1(N,L,NZ)=Z2OP(N,L,NZ,NY,NX)
        Z2OAs1(N,L,NZ)=Z2OA(N,L,NZ,NY,NX)
        ZH3Ps1(N,L,NZ)=ZH3P(N,L,NZ,NY,NX)
        ZH3As1(N,L,NZ)=ZH3A(N,L,NZ,NY,NX)
      enddo
      CPOOLNs1(L,NZ)=CPOOLN(L,NZ,NY,NX)
      PPOOLNs1(L,NZ)=PPOOLN(L,NZ,NY,NX)
      RUPNFs1(L,NZ)=RUPNF(L,NZ,NY,NX)
      TFN4s1(L,NZ)=TFN4(L,NZ,NY,NX)
      WTNDLNs1(L,NZ)=WTNDLN(L,NZ,NY,NX)
      WTNDLs1(L,NZ)=WTNDL(L,NZ,NY,NX)
      WTNDLPs1(L,NZ)=WTNDLP(L,NZ,NY,NX)
      ZPOOLNs1(L,NZ)=ZPOOLN(L,NZ,NY,NX)
    ENDDO
    DO L=1,JC
      plt_morph%ARSTVs1(L,NZ)=ARSTV(L,NZ,NY,NX)
      plt_morph%ARLFVs1(L,NZ)=ARLFV(L,NZ,NY,NX)
      WGLFVs1(L,NZ)=WGLFV(L,NZ,NY,NX)
    ENDDO
    DO N=1,MY(NZ,NY,NX)
      DMVLs1(N,NZ)=DMVL(N,NZ,NY,NX)
      PORTXs1(N,NZ)=PORTX(N,NZ,NY,NX)
      RTAR2Xs1(N,NZ)=RTAR2X(N,NZ,NY,NX)
      RTAR1Xs1(N,NZ)=RTAR1X(N,NZ,NY,NX)
      RRAD1Xs1(N,NZ)=RRAD1X(N,NZ,NY,NX)
      RRAD2Xs1(N,NZ)=RRAD2X(N,NZ,NY,NX)
      RTLG1Xs1(N,NZ)=RTLG1X(N,NZ,NY,NX)
      RRADPs1(N,NZ)=RRADP(N,NZ,NY,NX)
      RTLG2Xs1(N,NZ)=RTLG2X(N,NZ,NY,NX)
    ENDDO

    DO NR=1,NRT(NZ,NY,NX)
      plt_morph%NINRs1(NR,NZ)=NINR(NR,NZ,NY,NX)
      DO L=1,NJ(NY,NX)
        DO N=1,MY(NZ,NY,NX)
          RTLG1s1(N,L,NR,NZ)=RTLG1(N,L,NR,NZ,NY,NX)
          RTLG2s1(N,L,NR,NZ)=RTLG2(N,L,NR,NZ,NY,NX)
          RTN2s1(N,L,NR,NZ)=RTN2(N,L,NR,NZ,NY,NX)
          WTRT2s1(N,L,NR,NZ)=WTRT2(N,L,NR,NZ,NY,NX)
          WTRT1s1(N,L,NR,NZ)=WTRT1(N,L,NR,NZ,NY,NX)
          WTRT2Ns1(N,L,NR,NZ)=WTRT2N(N,L,NR,NZ,NY,NX)
          WTRT1Ns1(N,L,NR,NZ)=WTRT1N(N,L,NR,NZ,NY,NX)
          WTRT2Ps1(N,L,NR,NZ)=WTRT2P(N,L,NR,NZ,NY,NX)
          WTRT1Ps1(N,L,NR,NZ)=WTRT1P(N,L,NR,NZ,NY,NX)
        enddo
      enddo
      DO N=1,MY(NZ,NY,NX)
        RTDP1s1(N,NR,NZ)=RTDP1(N,NR,NZ,NY,NX)
        RTWT1s1(N,NR,NZ)=RTWT1(N,NR,NZ,NY,NX)
        RTWT1Ns1(N,NR,NZ)=RTWT1N(N,NR,NZ,NY,NX)
        RTWT1Ps1(N,NR,NZ)=RTWT1P(N,NR,NZ,NY,NX)
      enddo
    enddo
    DO M=1,4
      WTSTDGs1(M,NZ)=WTSTDG(M,NZ,NY,NX)
      WTSTDNs1(M,NZ)=WTSTDN(M,NZ,NY,NX)
      WTSTDPs1(M,NZ)=WTSTDP(M,NZ,NY,NX)
    ENDDO

    DO L=0,NJ(NY,NX)
      DO K=0,1
        DO M=1,4
          CSNCs1(M,K,L,NZ)=CSNC(M,K,L,NZ,NY,NX)
          PSNCs1(M,K,L,NZ)=PSNC(M,K,L,NZ,NY,NX)
          ZSNCs1(M,K,L,NZ)=ZSNC(M,K,L,NZ,NY,NX)
        enddo
      enddo
    ENDDO
    DO M=1,4
      DO N=0,5
        CFOPCs1(N,M,NZ)=CFOPC(N,M,NZ,NY,NX)
        CFOPNs1(N,M,NZ)=CFOPN(N,M,NZ,NY,NX)
        CFOPPs1(N,M,NZ)=CFOPP(N,M,NZ,NY,NX)
      enddo
    enddo
  ENDDO

  DO L=1,NL(NY,NX)
    DO M=1,NPH
      ROXSKs1(M,L)=ROXSK(M,L,NY,NX)
      THETPMs1(M,L)=THETPM(M,L,NY,NX)
    ENDDO
  ENDDO
  end subroutine PlantAPISend


!------------------------------------------------------------------------------------------

  subroutine PlantAPICanMSend(NY,NX)
  implicit none
  integer, intent(in) :: NY,NX

  integer :: L,N,M,NN,NZ,K,NB
!  Integers
  IETYPs1=IETYP(NY,NX)
  NPs1=NP(NY,NX)
  NUs1=NU(NY,NX)
  plt_morph%ARSTCs1=ARSTC(NY,NX)
  plt_morph%ARLFCs1=ARLFC(NY,NX)
  ZEROSs1=ZEROS(NY,NX)
  ZEROs1=ZERO
  DPTHSs1=DPTHS(NY,NX)
  TKAs1=TKA(NY,NX)
  plt_morph%ZTs1=ZT(NY,NX)
  Z0s1=Z0(NY,NX)
  ZDs1=ZD(NY,NX)
  UAs1=UA(NY,NX)
  VHCPWXs1=VHCPWX(NY,NX)
  VHCPW1s1=VHCPW(1,NY,NX)
  plt_morph%ZLs1(0)=ZL(0,NY,NX)
  DO L=1,JC
    plt_morph%ARSTTs1(L)=ARSTT(L,NY,NX)
    plt_morph%ARLFTs1(L)=ARLFT(L,NY,NX)
    plt_morph%ZLs1(L)=ZL(L,NY,NX)
    plt_rad%TAUSs1(L)=TAUS(L,NY,NX)
  ENDDO
  plt_rad%TAUSs1(JC+1)=TAUS(JC+1,NY,NX)

  DO L=0,NL(NY,NX)
    AREA3s1(L)=AREA(3,L,NY,NX)
    VOLXs1(L)=VOLX(L,NY,NX)
    VOLYs1(L)=VOLY(L,NY,NX)
    VOLWs1(L)=VOLW(L,NY,NX)
  ENDDO
  plt_rad%SSINs1=SSIN(NY,NX)
  ZNOONs1=ZNOON(NY,NX)
  plt_morph%ARLSSs1=ARLSS(NY,NX)
  plt_rad%GAZIs1=GAZI(NY,NX)
  plt_rad%GCOSs1=GCOS(NY,NX)
  plt_rad%GSINs1=GSIN(NY,NX)
  plt_rad%RADYs1=RADY(NY,NX)
  plt_rad%RAPYs1=RAPY(NY,NX)
  plt_rad%RADSs1=RADS(NY,NX)
  plt_rad%RAPSs1=RAPS(NY,NX)
  ZSs1=ZS(NY,NX)
  VOLWSs1=VOLWS(NY,NX)
  VOLISs1=VOLIS(NY,NX)
  VOLSSs1=VOLSS(NY,NX)
  plt_rad%TYSINs1=TYSIN
  plt_rad%ALBSs1=ALBS(NY,NX)
  plt_rad%ALBXs1=ALBX(NY,NX)
  ZEROS2s1=ZEROS2(NY,NX)
  POROS1s1=POROS(NU(NY,NX),NY,NX)
  DO NZ=1,NP(NY,NX)
    plt_morph%ARLFPs1(NZ)=ARLFP(NZ,NY,NX)
    plt_morph%ZCs1(NZ)=ZC(NZ,NY,NX)
    CFXs1(NZ)=CFX(NZ,NY,NX)
    plt_rad%ABSRs1(NZ)=ABSR(NZ,NY,NX)
    plt_rad%ABSPs1(NZ)=ABSP(NZ,NY,NX)
    plt_rad%TAURs1(NZ)=TAUR(NZ,NY,NX)
    plt_rad%ALBRs1(NZ)=ALBR(NZ,NY,NX)
    plt_rad%TAUPs1(NZ)=TAUP(NZ,NY,NX)
    plt_rad%ALBPs1(NZ)=ALBP(NZ,NY,NX)
    plt_morph%NBRs1(NZ)=NBR(NZ,NY,NX)
    plt_morph%CFs1(NZ)=CF(NZ,NY,NX)
    DO NB=1,NBR(NZ,NY,NX)
      DO K=0,JNODS
        DO  L=1,JC
          plt_morph%ARLFLs1(L,K,NB,NZ)=ARLFL(L,K,NB,NZ,NY,NX)
        ENDDO
      ENDDO
      DO  L=1,JC
        plt_morph%ARSTKs1(L,NB,NZ)=ARSTK(L,NB,NZ,NY,NX)
      ENDDO
      DO K=1,JNODS
        DO  L=1,JC
          DO N=1,JLI
            plt_morph%SURFs1(N,L,K,NB,NZ)=SURF(N,L,K,NB,NZ,NY,NX)
          ENDDO
        ENDDO
      ENDDO
      DO  L=1,JC
        DO N=1,JLI
          plt_morph%SURFBs1(N,L,NB,NZ)=SURFB(N,L,NB,NZ,NY,NX)
        ENDDO
      ENDDO
    ENDDO
  ENDDO
  DO N=1,JSA
    plt_rad%OMEGAGs1(N)=OMEGAG(N,NY,NX)
  ENDDO
  DO N=1,JLI
    plt_rad%ZCOSs1(N)=ZCOS(N)
    plt_rad%ZSINs1(N)=ZSIN(N)
  ENDDO
  DO NN=1,JLA
    DO M=1,JLI
      DO N=1,JSA
        plt_rad%OMEGAs1(N,M,NN)=OMEGA(N,M,NN)
        plt_rad%OMEGXs1(N,M,NN)=OMEGX(N,M,NN)
        plt_rad%IALBYs1(N,M,NN)=IALBY(N,M,NN)
      ENDDO
    ENDDO
  ENDDO

  end subroutine PlantAPICanMSend

!------------------------------------------------------------------------------------------

  subroutine PlantAPICanMRecv(NY,NX)

  implicit none
  integer, intent(in) :: NY,NX

  integer :: N,M,NN,L,NZ,K,NB

  ZD(NY,NX)=ZDs1
  ZR(NY,NX)=ZRs1
  RAB(NY,NX)=RABs1
  RIB(NY,NX)=RIBs1
  ZT(NY,NX)=plt_morph%ZTs1
  RADS(NY,NX)=plt_rad%RADSs1
  RADY(NY,NX)=plt_rad%RADYs1
  RAPS(NY,NX)=plt_rad%RAPSs1
  RAPY(NY,NX)=plt_rad%RAPYs1
  RADG(NY,NX)=plt_rad%RADGs1
  FRADG(NY,NX)=plt_rad%FRADGs1
  RAD(NY,NX)=plt_rad%RAD0s1
  RAP(NY,NX)=plt_rad%RAP0s1
  DO L=0,JC
    ZL(L,NY,NX)=plt_morph%ZLs1(L)
  ENDDO
  DO L=1,JC
    TAUS(L,NY,NX)=plt_rad%TAUSs1(L)
    TAU0(L,NY,NX)=plt_rad%TAU0s1(L)
  ENDDO
  ARLSS(NY,NX)=plt_morph%ARLSSs1
  DO NZ=1,NP(NY,NX)
    ARLFS(NZ,NY,NX)=plt_morph%ARLFSs1(NZ)
    RADC(NZ,NY,NX)=plt_rad%RADCs1(NZ)
    RADP(NZ,NY,NX)=plt_rad%RADPs1(NZ)
    CFX(NZ,NY,NX)=CFXs1(NZ)
    FRADP(NZ,NY,NX)=plt_rad%FRADPs1(NZ)

    DO L=1,JC
      DO M=1,JSA
        DO  N=1,JLI
          PARDIF(N,M,L,NZ,NY,NX)=PARDIFs1(N,M,L,NZ)
          PAR(N,M,L,NZ,NY,NX)=PARs1(N,M,L,NZ)
        ENDDO
      ENDDO
    ENDDO
  ENDDO

  end subroutine PlantAPICanMRecv

end module PlantAPI
