module PlantStateTransferMod
  ! Ordered state transfers used by PlantAPISend/PlantAPIRecv.
  use data_kind_mod,    only: r8 => DAT_KIND_R8,yearIJ_type
  use EcoSiMParDataMod, only: micpar, pltpar
  use SoilPhysDataType, only: SurfAlbedo_col,SoilSurfDepZ_col
  use MiniMathMod,      only: AZMAX1,safe_adb
  use DebugToolMod,     only: PrintInfo
  use NumericalAuxMod
  use EcoSIMSolverPar
  use EcoSIMHistMod
  use SnowDataType
  use TracerIDMod
  use SurfLitterDataType
  use LandSurfDataType
  use SoilPropertyDataType
  use ChemTranspDataType
  use EcoSimSumDataType
  use SoilHeatDataType
  use SOMDataType
  use ClimForcDataType
  use EcoSIMCtrlDataType
  use GridDataType
  use RootDataType
  use SoilWaterDataType
  use CanopyDataType
  use PlantDataRateType
  use PlantTraitDataType
  use CanopyRadDataType
  use FlagDataType
  use EcosimBGCFluxType
  use FertilizerDataType
  use SoilBGCDataType
  use PlantMgmtDataType
  use PlantAPICommonData
  use PlantSiteAPIData, only : plt_site
  use PlantPhotosynthesisAPIData, only : plt_photo
  use PlantRadiationAPIData, only : plt_rad
  use PlantMorphologyAPIData, only : plt_morph
  use PlantPhenologyAPIData, only : plt_pheno
  use PlantAllometryAPIData, only : plt_allom
  use PlantBiomassAPIData, only : plt_biom
  use PlantEnergyWaterAPIData, only : plt_ew
  use PlantDisturbanceAPIData, only : plt_distb
  use PlantBGCRatesAPIData, only : plt_bgcr
  use PlantRootBGCAPIData, only : plt_rbgc
  implicit none
  private
  public :: ReceivePlantState
  public :: SendPlantState
contains

  subroutine ReceivePlantState(I,NY,NX,NZ)
  use EcoSIMConfig, only : jsken=>jskenc,jcplx=>jcplxc
  integer, intent(in) :: I,NY,NX,NZ

    fNCLFW_pft(NZ,NY,NX) = plt_pheno%fNCLFW_pft(NZ)
    fPCLFW_pft(NZ,NY,NX) = plt_pheno%fPCLFW_pft(NZ)
    Eco_GPP_CumYr_col(NY,NX)                            = Eco_GPP_CumYr_col(NY,NX)+plt_bgcr%GrossCO2Fix_pft(NZ)
    PARTS_brch(1:pltpar%NumOfPlantMorphUnits,1:pltpar%MaxNumBranches,NZ,NY,NX)= &
      plt_morph%PARTS_brch(1:pltpar%NumOfPlantMorphUnits,1:pltpar%MaxNumBranches,NZ)
    QdewCanopy_CumYr_pft(NZ,NY,NX)                              = QdewCanopy_CumYr_pft(NZ,NY,NX)+plt_ew%QdewCanopy_pft(NZ)
    RootUptk_N_CumYr_pft(NZ,NY,NX)                              = plt_rbgc%RootUptk_N_CumYr_pft(NZ)
    RootUptk_P_CumYr_pft(NZ,NY,NX)                              = plt_rbgc%RootUptk_P_CumYr_pft(NZ)
    RootUptk_Nmin_cumYr_pft(NZ,NY,NX) = RootUptk_Nmin_cumYr_pft(NZ,NY,NX)+plt_rbgc%RootNutUptakeN_pft(NZ)
    RootUptk_Pmin_cumYr_pft(NZ,NY,NX) = RootUptk_Pmin_cumYr_pft(NZ,NY,NX)+plt_rbgc%RootNutUptakeP_pft(NZ)
    RootNoduleElms_pft(1:NumPlantChemElms,NZ,NY,NX)             = plt_biom%RootNoduleElms_pft(1:NumPlantChemElms,NZ)
    RootElms_pft(1:NumPlantChemElms,NZ,NY,NX)                   = plt_biom%RootElms_pft(1:NumPlantChemElms,NZ)
    PlantElmBalCum_pft(1:NumPlantChemElms,NZ,NY,NX)             = plt_site%PlantElmBalCum_pft(1:NumPlantChemElms,NZ)
    CanopyNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)            = plt_biom%CanopyNonstElms_pft(1:NumPlantChemElms,NZ)
    CanopyNodulNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)       = plt_biom%CanopyNodulNonstElms_pft(1:NumPlantChemElms,NZ)
    CanopyNonstElmConc_pft(1:NumPlantChemElms,NZ,NY,NX)         = plt_biom%CanopyNonstElmConc_pft(1:NumPlantChemElms,NZ)
    LitrfallElms_pft(1:NumPlantChemElms,NZ,NY,NX)               = plt_bgcr%LitrfallElms_pft(1:NumPlantChemElms,NZ)
    EcoHavstElmnt_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)        = plt_distb%EcoHavstElmnt_CumYr_pft(1:NumPlantChemElms,NZ)
    NetCumElmntFlx2Plant_pft(1:NumPlantChemElms,NZ,NY,NX)       = plt_pheno%NetCumElmntFlx2Plant_pft(1:NumPlantChemElms,NZ)
    SurfLitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX) = plt_bgcr%SurfLitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ)
    LitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)     = plt_bgcr%LitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ)
    EcoHavstElmntCum_pft(1:NumPlantChemElms,NZ,NY,NX)           = plt_distb%EcoHavstElmntCum_pft(1:NumPlantChemElms,NZ)
    PlantExudElm_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)         = plt_rbgc%PlantExudElm_CumYr_pft(1:NumPlantChemElms,NZ)
    Soil2RootMycoExudE_pft(1:NumPlantChemElms,NZ,NY,NX)         = plt_rbgc%Soil2RootMycoExudE_pft(1:NumPlantChemElms,NZ)
    StandDeadStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)         = plt_biom%StandDeadStrutElms_pft(1:NumPlantChemElms,NZ)
    SeasonalNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)          = plt_biom%SeasonalNonstElms_pft(1:NumPlantChemElms,NZ)
    SeasonalNonstCDayAve_pft(NZ,NY,NX)                          = plt_biom%SeasonalNonstCDayAve_pft(NZ)
    Days4FalseBreak_pft(NZ,NY,NX)                              = plt_pheno%Days4FalseBreak_pft(NZ)
    ShootElms_pft(1:NumPlantChemElms,NZ,NY,NX)                  = plt_biom%ShootElms_pft(1:NumPlantChemElms,NZ)
    LeafStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)              = plt_biom%LeafStrutElms_pft(1:NumPlantChemElms,NZ)
    PetolShethStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)        = plt_biom%PetolShethStrutElms_pft(1:NumPlantChemElms,NZ)
    StalkStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)             = plt_biom%StalkStrutElms_pft(1:NumPlantChemElms,NZ)
    StalkRsrvElms_pft(1:NumPlantChemElms,NZ,NY,NX)              = plt_biom%StalkRsrvElms_pft(1:NumPlantChemElms,NZ)
    HuskStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)              = plt_biom%HuskStrutElms_pft(1:NumPlantChemElms,NZ)
    EarStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)               = plt_biom%EarStrutElms_pft(1:NumPlantChemElms,NZ)
    GrainStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)             = plt_biom%GrainStrutElms_pft(1:NumPlantChemElms,NZ)
    RootStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)              = plt_biom%RootStrutElms_pft(1:NumPlantChemElms,NZ)
    PlantRootSoilElmNetX_pft(1:NumPlantChemElms,NZ,NY,NX)       = plt_rbgc%PlantRootSoilElmNetX_pft(1:NumPlantChemElms,NZ)
    CanopyLeafArea_pft(NZ,NY,NX)                                = plt_morph%CanopyLeafArea_pft(NZ)
    CanopyLeafAreaMax_pft(NZ,NY,NX)                             = plt_morph%CanopyLeafAreaMax_pft(NZ)
    ShootNoduleElms_pft(1:NumPlantChemElms,NZ,NY,NX)            = plt_biom%ShootNoduleElms_pft(1:NumPlantChemElms,NZ)
    TotEndVegE_pft(1:NumPlantChemElms,NZ,NY,NX)                 = plt_biom%TotEndVegE_pft(1:NumPlantChemElms,NZ)
    TotBegVegE_pft(1:NumPlantChemElms,NZ,NY,NX)                 = plt_biom%TotBegVegE_pft(1:NumPlantChemElms,NZ)
    ShootRootXferElm_pft(1:NumPlantChemElms,NZ,NY,NX)           = plt_bgcr%ShootRootXferElm_pft(1:NumPlantChemElms,NZ)
    DynCi2CaRatio_pft(NZ,NY,NX)        = plt_photo%DynCi2CaRatio_pft(NZ)
    CH2OSunlit_pft(NZ,NY,NX)            = plt_photo%CH2OSunlit_pft(NZ)
    CH2OSunsha_pft(NZ,NY,NX)            = plt_photo%CH2OSunsha_pft(NZ)
    CanopyMassC_pft(NZ,NY,NX)           = plt_biom%CanopyMassC_pft(NZ)
    CanopyStemSurfArea_pft(NZ,NY,NX)        = plt_morph%CanopyStemSurfArea_pft(NZ)
    CanopyNoduleNonstCConc_pft(NZ,NY,NX)  = plt_biom%CanopyNoduleNonstCConc_pft(NZ)
    CO2NetFix_pft(NZ,NY,NX)             = plt_bgcr%CO2NetFix_pft(NZ)
    RCanMaintDef_CO2_pft(NZ,NY,NX)      = plt_bgcr%RCanMaintDef_CO2_pft(NZ)
    CanopyVcMaxRubisco25C_pft(NZ,NY,NX)    = plt_photo%CanopyVcMaxRubisco25C_pft(NZ)
    CanopyVoMaxRubisco25C_pft(NZ,NY,NX)    = plt_photo%CanopyVoMaxRubisco25C_pft(NZ)
    CanopyVcMaxPEP25C_pft(NZ,NY,NX)        = plt_photo%CanopyVcMaxPEP25C_pft(NZ)
    ElectronTransptJmax25C_pft(NZ,NY,NX) = plt_photo%ElectronTransptJmax25C_pft(NZ)
    TFN_Carboxy_pft(NZ,NY,NX)           = plt_photo%TFN_Carboxy_pft(NZ)
    TFN_Oxygen_pft(NZ,NY,NX)            = plt_photo%TFN_Oxygen_pft(NZ)
    TFN_eTranspt_pft(NZ,NY,NX)          = plt_photo%TFN_eTranspt_pft(NZ)
    CanopyGasCO2_pft(NZ,NY,NX)          = plt_photo%CanopyGasCO2_pft(NZ)
    LeafIntracellularCO2_pft(NZ,NY,NX)  = plt_photo%LeafIntracellularCO2_pft(NZ)
    aquCO2Intraleaf_pft(NZ,NY,NX)       = plt_photo%aquCO2Intraleaf_pft(NZ)
    ClumpFactor_pft(NZ,NY,NX)           = plt_morph%ClumpFactor_pft(NZ)
    RootProteinCMax_pft(NZ,NY,NX)       = plt_allom%RootProteinCMax_pft(NZ)
    CNRTS_pft(NZ,NY,NX)                 = plt_allom%CNRTS_pft(NZ)
    CPRTS_pft(NZ,NY,NX)                 = plt_allom%CPRTS_pft(NZ)
    ETCanopy_CumYr_pft(NZ,NY,NX)        = plt_ew%ETCanopy_CumYr_pft(NZ)
    GrossCO2Fix_pft(NZ,NY,NX)           = plt_bgcr%GrossCO2Fix_pft(NZ)
    GrossCO2Fix_CumYr_pft(NZ,NY,NX)     = GrossCO2Fix_CumYr_pft(NZ,NY,NX)+GrossCO2Fix_pft(NZ,NY,NX)
    ChillHours_pft(NZ,NY,NX)            = plt_photo%ChillHours_pft(NZ)
    DiffCO2Atmos2Intracel_pft(NZ,NY,NX) = plt_photo%DiffCO2Atmos2Intracel_pft(NZ)
    DeltaTKC_pft(NZ,NY,NX)              = plt_ew%DeltaTKC_pft(NZ)
    DynCi2CaRatio_pft(NZ,NY,NX)         = plt_photo%DynCi2CaRatio_pft(NZ)
    ENGYX_pft(NZ,NY,NX)                 = plt_ew%ENGYX_pft(NZ)
    CdH2ORootxSoil_pft(NZ,NY,NX)        = AZMAX1(plt_ew%CdH2ORootxSoil_pft(NZ))
    Transpiration_pft(NZ,NY,NX)         = plt_ew%Transpiration_pft(NZ)
    VapXAir2Canopy_pft(NZ,NY,NX)        = plt_ew%VapXAir2Canopy_pft(NZ)
    CanopyEvapTransLHeat_pft(NZ,NY,NX)         = plt_ew%CanopyEvapTransLHeat_pft(NZ)
    AirConc_pft(NZ,NY,NX)               = plt_photo%AirConc_pft(NZ)
    FracPARads2Canopy_pft(NZ,NY,NX)     = plt_rad%FracPARads2Canopy_pft(NZ)
    FracPARads2LiveCanopy_pft(NZ,NY,NX) = plt_rad%FracPARads2LiveCanopy_pft(NZ)
    FracGroth2Node_pft(NZ,NY,NX)        = plt_allom%FracGroth2Node_pft(NZ)
    CanopySeedNum_pft(NZ,NY,NX)         = plt_morph%CanopySeedNum_pft(NZ)
    CanopySeedNumX_pft(NZ,NY,NX)         = plt_morph%CanopySeedNumX_pft(NZ)
    HypocotHeight_pft(NZ,NY,NX)         = plt_morph%HypocotHeight_pft(NZ)
    HighTempLimitSeed_pft(NZ,NY,NX)     = plt_pheno%HighTempLimitSeed_pft(NZ)
    HeatStorCanopy_pft(NZ,NY,NX)        = plt_ew%HeatStorCanopy_pft(NZ)
    canopy_growth_pft(NZ,NY,NX)         = plt_rbgc%canopy_growth_pft(NZ)
    CanopyHeight4WatUptake_pft(NZ,NY,NX)      = plt_morph%CanopyHeight4WatUptake_pft(NZ)
    IsPlantActive_pft(NZ,NY,NX)         = plt_pheno%IsPlantActive_pft(NZ)
    iPlantStateLive_pft(NZ,NY,NX)           = plt_pheno%iPlantStateLive_pft(NZ)
    isPlantShootAlive_pft(NZ,NY,NX)      = plt_pheno%isPlantShootAlive_pft(NZ)
    isPlantRootAlive_pft(NZ,NY,NX)       = plt_pheno%isPlantRootAlive_pft(NZ)
    iDayPlanting_pft(NZ,NY,NX)          = plt_distb%iDayPlanting_pft(NZ)
    iYearPlanting_pft(NZ,NY,NX)         = plt_distb%iYearPlanting_pft(NZ)
    doInitPlant_pft(NZ,NY,NX)           = plt_pheno%doInitPlant_pft(NZ)
    iDayPlantHarvest_pft(NZ,NY,NX)      = plt_distb%iDayPlantHarvest_pft(NZ)
    iYearPlantHarvest_pft(NZ,NY,NX)     = plt_distb%iYearPlantHarvest_pft(NZ)
    NMaxRootBotLayer_pft(NZ,NY,NX)       = plt_morph%NMaxRootBotLayer_pft(NZ)
    BranchNumber_pft(NZ,NY,NX)          = plt_morph%BranchNumber_pft(NZ)
    NumOfBranches_pft(NZ,NY,NX)         = plt_morph%NumOfBranches_pft(NZ)
    NumStructuralRootAxes_pft(NZ,NY,NX)      = plt_morph%NumStructuralRootAxes_pft(NZ)
    MaxSoilLays4Root_pft(NZ,NY,NX)          = plt_morph%MaxSoilLays4Root_pft(NZ)
    NGTopRootLayer_pft(NZ,NY,NX)        = plt_morph%NGTopRootLayer_pft(NZ)
    MainBranchNum_pft(NZ,NY,NX)         = plt_morph%MainBranchNum_pft(NZ)
    NumCogrowthNode_pft(NZ,NY,NX)        = plt_morph%NumCogrowthNode_pft(NZ)
    O2L_pft(NZ,NY,NX)                                       = plt_photo%O2L_pft(NZ)
    O2I_pft(NZ,NY,NX)                                       = plt_photo%O2I_pft(NZ)
    CanPhenoMoistStress_pft(NZ,NY,NX) = plt_pheno%CanPhenoMoistStress_pft(NZ)
    CanPhenoTempStress_pft(NZ,NY,NX) =  plt_pheno%CanPhenoTempStress_pft(NZ)
    TempOffset_pft(NZ,NY,NX)                            = plt_pheno%TempOffset_pft(NZ)
    PlantO2Stress_pft(NZ,NY,NX)                         = plt_pheno%PlantO2Stress_pft(NZ)
    PPX_pft(NZ,NY,NX)                                   = plt_site%PPX_pft(NZ)
    PPatSeeding_pft(NZ,NY,NX)                           = plt_site%PPatSeeding_pft(NZ)
    PlantPopuLive_pft(NZ,NY,NX)                         = plt_site%PlantPopuLive_pft(NZ)
    PlantPopuDead_pft(NZ,NY,NX)                         = plt_site%PlantPopuDead_pft(NZ)
    PPI_pft(NZ,NY,NX)                                   = plt_site%PPI_pft(NZ)
    RLeafAppear_pft(NZ,NY,NX)                           = plt_rbgc%RLeafAppear_pft(NZ)
    RNodeInitiate_pft(NZ,NY,NX)                         = plt_rbgc%RNodeInitiate_pft(NZ)
    PSICanopy_pft(NZ,NY,NX)                             = plt_ew%PSICanopy_pft(NZ)
    PSICanopyOsmo_pft(NZ,NY,NX)                         = plt_ew%PSICanopyOsmo_pft(NZ)
    PSICanopyTurg_pft(NZ,NY,NX)                         = plt_ew%PSICanopyTurg_pft(NZ)
    PSICanPDailyMin_pft(NZ,NY,NX)                       = plt_ew%PSICanPDailyMin_pft(NZ)
    CO2FixCL_pft(NZ,NY,NX)                              = plt_rbgc%CO2FixCL_pft(NZ)
    CO2FixLL_pft(NZ,NY,NX)                              = plt_rbgc%CO2FixLL_pft(NZ)
    RootGasLossDisturb_pft(idg_beg:idg_NH3,NZ,NY,NX)    = plt_bgcr%RootGasLossDisturb_pft(idg_beg:idg_NH3,NZ)
    CanopyMinStomaResistH2O_pft(NZ,NY,NX)               = plt_photo%CanopyMinStomaResistH2O_pft(NZ)
    H2OCuticleResist_pft(NZ,NY,NX)                      = plt_photo%H2OCuticleResist_pft(NZ)
    CO2CuticleResist_pft(NZ,NY,NX)                      = plt_photo%CO2CuticleResist_pft(NZ)
    NH3Dep2Can_pft(NZ,NY,NX)                            = plt_bgcr%NH3Dep2Can_pft(NZ)
    RadNet2Canopy_pft(NZ,NY,NX)                         = plt_rad%RadNet2Canopy_pft(NZ)
    RawIsoTCanopy2Atm_pft(NZ,NY,NX)                     = plt_ew%RawIsoTCanopy2Atm_pft(NZ)
    CanPStomaResistH2O_pft(NZ,NY,NX)                    = plt_photo%CanPStomaResistH2O_pft(NZ)
    RawCanopy2Atm_pft(NZ,NY,NX)                         = plt_photo%RawCanopy2Atm_pft(NZ)
    PlantinDepz_pft(NZ,NY,NX)                           = plt_morph%PlantinDepz_pft(NZ)
    CO2Solubility_pft(NZ,NY,NX)                         = plt_photo%CO2Solubility_pft(NZ)
    LeafO2Solubility_pft(NZ,NY,NX)                      = plt_photo%LeafO2Solubility_pft(NZ)
    SeedTempSens_pft(NZ,NY,NX)                          = plt_pheno%SeedTempSens_pft(NZ)
    SeedVolumeMean_pft(NZ,NY,NX)                        = plt_morph%SeedVolumeMean_pft(NZ)
    SeedMeanLen_pft(NZ,NY,NX)                           = plt_morph%SeedMeanLen_pft(NZ)
    SeedAreaMean_pft(NZ,NY,NX)                          = plt_morph%SeedAreaMean_pft(NZ)
    SeedDepth_pft(NZ,NY,NX)                             = plt_morph%SeedDepth_pft(NZ)
    HeatXAir2PCan_pft(NZ,NY,NX)                         = plt_ew%HeatXAir2PCan_pft(NZ)
    GrossResp_pft(NZ,NY,NX)                             = plt_bgcr%GrossResp_pft(NZ)
    GrossRespC_CumYr_pft(NZ,NY,NX)                      = GrossRespC_CumYr_pft(NZ,NY,NX)+GrossResp_pft(NZ,NY,NX)
    CanopyRespC_CumYr_pft(NZ,NY,NX)                     = plt_bgcr%CanopyRespC_CumYr_pft(NZ)
    TC4LeafOut_pft(NZ,NY,NX)                            = plt_pheno%TC4LeafOut_pft(NZ)
    TC4LeafOff_pft(NZ,NY,NX)                            = plt_pheno%TC4LeafOff_pft(NZ)
    NH3Emis_CumYr_pft(NZ,NY,NX)                         = plt_bgcr%NH3Emis_CumYr_pft(NZ)
    NodulInfectElms_pft(1:NumPlantChemElms,NZ,NY,NX)    = plt_bgcr%NodulInfectElms_pft(1:NumPlantChemElms,NZ)
    PlantN2Fix_CumYr_pft(NZ,NY,NX)                      = plt_bgcr%PlantN2Fix_CumYr_pft(NZ)
    TKC_pft(NZ,NY,NX)                                   = plt_ew%TKC_pft(NZ)
    LeafProteinCperm2LA_pft(NZ,NY,NX)          = plt_biom%LeafProteinCperm2LA_pft(NZ)
    TdegCCanopy_pft(NZ,NY,NX)                  = plt_ew%TdegCCanopy_pft(NZ)
    LWRadCanopy_pft(NZ,NY,NX)                  = plt_rad%LWRadCanopy_pft(NZ)
    TKCanopy_pft(NZ,NY,NX)                     = plt_ew%TKCanopy_pft(NZ)
    TKGroth_pft(NZ,NY,NX)                      = plt_pheno%TKGroth_pft(NZ)
    TCGroth_pft(NZ,NY,NX)                      = plt_pheno%TCGroth_pft(NZ)
    fTCanopyGroth_pft(NZ,NY,NX)                = plt_pheno%fTCanopyGroth_pft(NZ)
    CanopyN2Fix_pft(NZ,NY,NX)                  = plt_rbgc%CanopyN2Fix_pft(NZ)
    RootN2Fix_pft(NZ,NY,NX)                    = plt_rbgc%RootN2Fix_pft(NZ)
    RootNH4Uptake_pft(NZ,NY,NX)                = plt_rbgc%RootNH4Uptake_pft(NZ)
    RootNO3Uptake_pft(NZ,NY,NX)                = plt_rbgc%RootNO3Uptake_pft(NZ)
    RootH2PO4Uptake_pft(NZ,NY,NX)              = plt_rbgc%RootH2PO4Uptake_pft(NZ)
    RootHPO4Uptake_pft(NZ,NY,NX)               = plt_rbgc%RootHPO4Uptake_pft(NZ)
    WatHeldOnCanopy_pft(NZ,NY,NX)              = plt_ew%WatHeldOnCanopy_pft(NZ)
    SnowOnCanopy_pft(NZ,NY,NX)                 = plt_ew%SnowOnCanopy_pft(NZ)
    CanopyBiomWater_pft(NZ,NY,NX)              = plt_ew%CanopyBiomWater_pft(NZ)
    CO2ByFire_CumYr_pft(NZ,NY,NX)              = plt_distb%CO2ByFire_CumYr_pft(NZ)
    CH4ByFire_CumYr_pft(NZ,NY,NX)              = plt_distb%CH4ByFire_CumYr_pft(NZ)
    O2ByFire_CumYr_pft(NZ,NY,NX)               = plt_distb%O2ByFire_CumYr_pft(NZ)
    NH3byFire_CumYr_pft(NZ,NY,NX)              = plt_distb%NH3byFire_CumYr_pft(NZ)
    N2ObyFire_CumYr_pft(NZ,NY,NX)              = plt_distb%N2ObyFire_CumYr_pft(NZ)
    PO4byFire_CumYr_pft(NZ,NY,NX)              = plt_distb%PO4byFire_CumYr_pft(NZ)
    VHeatCapCanopy_pft(NZ,NY,NX)               = plt_ew%VHeatCapCanopy_pft(NZ)
    HoursTooLowPsiCan_pft(NZ,NY,NX)            = plt_pheno%HoursTooLowPsiCan_pft(NZ)
    SeedPlantedElm_pft(:,NZ,NY,NX)             = plt_biom%SeedPlantedElm_pft(:,NZ)
    CanopySapwoodC_pft(NZ,NY,NX)               = plt_biom%CanopySapwoodC_pft(NZ)
    CanopyLeafSheathC_pft(NZ,NY,NX)             = plt_biom%CanopyLeafSheathC_pft(NZ)
    RootBiomCPerPlant_pft(NZ,NY,NX)            = plt_biom%RootBiomCPerPlant_pft(NZ)
    Km4LeafaqCO2_pft(NZ,NY,NX)                 = plt_photo%Km4LeafaqCO2_pft(NZ)
    RNFixCO2_pft(NZ,NY,NX)                     = plt_bgcr%RNFixCO2_pft(NZ)
    Km4RubiscoCarboxy_pft(NZ,NY,NX)            = plt_photo%Km4RubiscoCarboxy_pft(NZ)
    CanopyHeightDead_pft(NZ,NY,NX)             = plt_morph%CanopyHeightDead_pft(NZ)
    CanopyHeightLive_pft(NZ,NY,NX)             = plt_morph%CanopyHeightLive_pft(NZ)
    StalkHeight_pft(NZ,NY,NX)                  = plt_morph%StalkHeight_pft(NZ)
    StalkAveRadius_pft(NZ,NY,NX)               = plt_morph%StalkAveRadius_pft(NZ)
    NetPrimProduct_pft(NZ,NY,NX)               = plt_bgcr%NetPrimProduct_pft(NZ)
    cumNPP_pft(NZ,NY,NX)                       = cumNPP_pft(NZ,NY,NX) + NetPrimProduct_pft(NZ,NY,NX)
    ZERO4Groth_pft(NZ,NY,NX)                   = plt_biom%ZERO4Groth_pft(NZ)
    ZERO4Uptk_pft(NZ,NY,NX)                    = plt_rbgc%ZERO4Uptk_pft(NZ)
    ZERO4LeafVar_pft(NZ,NY,NX)                 = plt_biom%ZERO4LeafVar_pft(NZ)
    rPlantThermoAdaptZone_pft(NZ,NY,NX)        = plt_pheno%rPlantThermoAdaptZone_pft(NZ)
    FireReSet_pft(NZ,NY,NX)                    = plt_pheno%FireReSet_pft(NZ)
    PTSHTR_pft(NZ,NY,NX)                       = plt_bgcr%PTSHTR_pft(NZ)
    if(plt_distb%iHarvstType_pft(NZ).GT.0)then
      CanopyCutProxy_pft(NZ,I,NY,NX)            = plt_distb%CanopyCutProxy_pft(NZ)
      iHarvstType_pft(NZ,I,NY,NX)                = plt_distb%iHarvstType_pft(NZ)
      jHarvstType_pft(NZ,I,NY,NX)                = plt_distb%jHarvstType_pft(NZ)
      THIN_pft(NZ,I,NY,NX)                       = plt_distb%THIN_pft(NZ)
      FracBiomHarvsted(1:2,1:4,NZ,I,NY,NX)=plt_distb%FracBiomHarvsted(1:2,1:4,NZ)
    endif
    ShootElms_pft(1:NumPlantChemElms,NZ,NY,NX) = plt_biom%ShootElms_pft(1:NumPlantChemElms,NZ)
    TurgEff4CanopyResp_pft(NZ,NY,NX)           = plt_rbgc%TurgEff4CanopyResp_pft(NZ)
    CanopyGrosRCO2_pft(NZ,NY,NX)               = plt_bgcr%CanopyGrosRCO2_pft(NZ)
    LeafC3ChlCperm2LA_pft(NZ,NY,NX)            = plt_biom%LeafC3ChlCperm2LA_pft(NZ)
    LeafC4ChlCperm2LA_pft(NZ,NY,NX)            = plt_biom%LeafC4ChlCperm2LA_pft(NZ)
    LeafRubiscoCperm2LA_pft(NZ,NY,NX)          = plt_biom%LeafRubiscoCperm2LA_pft(NZ)
    LeafPEPCperm2LA_pft(NZ,NY,NX)              = plt_biom%LeafPEPCperm2LA_pft(NZ)
    SpecificLeafArea_pft(NZ,NY,NX)             = plt_biom%SpecificLeafArea_pft(NZ)
    Root1stTipSinkWeight_pft(NZ,NY,NX)         = plt_morph%Root1stTipSinkWeight_pft(NZ)
  end subroutine ReceivePlantState

  subroutine SendPlantState(I,NY,NX,NZ)
  use EcoSIMConfig, only : jsken=>jskenc,jcplx=>jcplxc
  integer, intent(in) :: I,NY,NX,NZ

    plt_biom%RootNoduleElms_pft(1:NumPlantChemElms,NZ)             = RootNoduleElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%ShootNoduleElms_pft(1:NumPlantChemElms,NZ)            = ShootNoduleElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%RootElms_pft(1:NumPlantChemElms,NZ)                   = RootElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%ShootElms_pft(1:NumPlantChemElms,NZ)                  = ShootElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%LeafStrutElms_pft(1:NumPlantChemElms,NZ)              = LeafStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%EarStrutElms_pft(1:NumPlantChemElms,NZ)               = EarStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%RootStrutElms_pft(1:NumPlantChemElms,NZ)              = RootStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%HuskStrutElms_pft(1:NumPlantChemElms,NZ)              = HuskStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%StalkRsrvElms_pft(1:NumPlantChemElms,NZ)              = StalkRsrvElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%StalkStrutElms_pft(1:NumPlantChemElms,NZ)             = StalkStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%PetolShethStrutElms_pft(1:NumPlantChemElms,NZ)            = PetolShethStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%GrainStrutElms_pft(1:NumPlantChemElms,NZ)             = GrainStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%CanopyNonstElmConc_pft(1:NumPlantChemElms,NZ)         = CanopyNonstElmConc_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%CanopyNonstElms_pft(1:NumPlantChemElms,NZ)            = CanopyNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%CanopyNodulNonstElms_pft(1:NumPlantChemElms,NZ)       = CanopyNodulNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%SeasonalNonstElms_pft(1:NumPlantChemElms,NZ)          = SeasonalNonstElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%SeasonalNonstCDayAve_pft(NZ)                         = SeasonalNonstCDayAve_pft(NZ,NY,NX)
    plt_pheno%Days4FalseBreak_pft(NZ)                            = Days4FalseBreak_pft(NZ,NY,NX)
    plt_biom%ShootElms_pft(1:NumPlantChemElms,NZ)                 = ShootElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_biom%StandDeadStrutElms_pft(1:NumPlantChemElms,NZ)        = StandDeadStrutElms_pft(1:NumPlantChemElms,NZ,NY,NX)

    plt_site%PlantElmBalCum_pft(1:NumPlantChemElms,NZ)              = PlantElmBalCum_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_bgcr%LitrfallElms_pft(1:NumPlantChemElms,NZ)           = LitrfallElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_distb%EcoHavstElmnt_CumYr_pft(1:NumPlantChemElms,NZ)       = EcoHavstElmnt_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_pheno%NetCumElmntFlx2Plant_pft(1:NumPlantChemElms,NZ)      = NetCumElmntFlx2Plant_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_bgcr%SurfLitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ) = SurfLitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_bgcr%LitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ)     = LitrfalStrutElms_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_rbgc%PlantExudElm_CumYr_pft(1:NumPlantChemElms,NZ)         = PlantExudElm_CumYr_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_rbgc%RootUptk_N_CumYr_pft(NZ)                              = RootUptk_N_CumYr_pft(NZ,NY,NX)
    plt_rbgc%RootUptk_P_CumYr_pft(NZ)                              = RootUptk_P_CumYr_pft(NZ,NY,NX)
    plt_distb%EcoHavstElmntCum_pft(1:NumPlantChemElms,NZ)          = EcoHavstElmntCum_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_rbgc%Soil2RootMycoExudE_pft(1:NumPlantChemElms,NZ)           = Soil2RootMycoExudE_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_ew%TKCanopy_pft(NZ)            = TKCanopy_pft(NZ,NY,NX)
    plt_photo%LeafO2Solubility_pft(NZ) = LeafO2Solubility_pft(NZ,NY,NX)
    plt_ew%PSICanPDailyMin_pft(NZ)         = PSICanPDailyMin_pft(NZ,NY,NX)
    plt_ew%HeatStorCanopy_pft(NZ)      = HeatStorCanopy_pft(NZ,NY,NX)
    plt_photo%CanopyGasCO2_pft(NZ)     = CanopyGasCO2_pft(NZ,NY,NX)
    plt_photo%O2L_pft(NZ)                  = O2L_pft(NZ,NY,NX)

    plt_photo%aquCO2Intraleaf_pft(NZ)      = aquCO2Intraleaf_pft(NZ,NY,NX)
    plt_distb%FracBiomHarvsted(1:2,1:4,NZ) = FracBiomHarvsted(1:2,1:4,NZ,I,NY,NX)
    plt_morph%enh_cyto_pft(NZ)  = enh_cyto_pft(NZ,NY,NX)
    plt_pheno%iPlantStateLive_pft(NZ)    = iPlantStateLive_pft(NZ,NY,NX)
    plt_distb%iYearPlanting_pft(NZ)  = iYearPlanting_pft(NZ,NY,NX)
    plt_morph%NumCogrowthNode_pft(NZ) = NumCogrowthNode_pft(NZ,NY,NX)

    plt_pheno%isPlantShootAlive_pft(NZ) = isPlantShootAlive_pft(NZ,NY,NX)
    plt_pheno%isPlantRootAlive_pft(NZ)  = isPlantRootAlive_pft(NZ,NY,NX)
    plt_allom%CNRTS_pft(NZ)            = CNRTS_pft(NZ,NY,NX)
    plt_allom%CPRTS_pft(NZ)            = CPRTS_pft(NZ,NY,NX)

    plt_rbgc%ZERO4Uptk_pft(NZ)              = ZERO4Uptk_pft(NZ,NY,NX)
    plt_pheno%SeedTempSens_pft(NZ)          = SeedTempSens_pft(NZ,NY,NX)
    plt_rad%FracPARads2Canopy_pft(NZ)       = FracPARads2Canopy_pft(NZ,NY,NX)
    plt_rad%FracPARads2LiveCanopy_pft(NZ)   = FracPARads2LiveCanopy_pft(NZ,NY,NX)
    plt_bgcr%NH3Dep2Can_pft(NZ)             = NH3Dep2Can_pft(NZ,NY,NX)
    plt_ew%DeltaTKC_pft(NZ)                 = DeltaTKC_pft(NZ,NY,NX)
    plt_pheno%rPlantThermoAdaptZone_pft(NZ) = rPlantThermoAdaptZone_pft(NZ,NY,NX)
    plt_pheno%HighTempLimitSeed_pft(NZ)     = HighTempLimitSeed_pft(NZ,NY,NX)
    plt_ew%Transpiration_pft(NZ)            = Transpiration_pft(NZ,NY,NX)
    plt_pheno%FireReSet_pft(NZ)             = FireReSet_pft(NZ,NY,NX)
    plt_biom%CanopyMassC_pft(NZ)          = CanopyMassC_pft(NZ,NY,NX)
    plt_biom%CanopyNoduleNonstCConc_pft(NZ) = CanopyNoduleNonstCConc_pft(NZ,NY,NX)
    plt_biom%RootBiomCPerPlant_pft(NZ)      = RootBiomCPerPlant_pft(NZ,NY,NX)
    plt_biom%CanopySapwoodC_pft(NZ) = CanopySapwoodC_pft(NZ,NY,NX)
    plt_photo%ChillHours_pft(NZ) = ChillHours_pft(NZ,NY,NX)
    plt_ew%PSICanopyOsmo_pft(NZ) = PSICanopyOsmo_pft(NZ,NY,NX)
    plt_morph%CRootActVolPerMassC_pft(NZ) = CRootActVolPerMassC_pft(NZ,NY,NX)
    plt_morph%CRootLigVolPerMassC_pft(NZ) = CRootLigVolPerMassC_pft(NZ,NY,NX)
    plt_ew%TdegCCanopy_pft(NZ)           = TdegCCanopy_pft(NZ,NY,NX)
    plt_allom%RootProteinCMax_pft(NZ) = RootProteinCMax_pft(NZ,NY,NX)
    plt_photo%H2OCuticleResist_pft(NZ)      = H2OCuticleResist_pft(NZ,NY,NX)
    plt_morph%ClumpFactor_pft(NZ)           = ClumpFactor_pft(NZ,NY,NX)
    plt_site%PPI_pft(NZ)               = PPI_pft(NZ,NY,NX)
    plt_site%PPX_pft(NZ)               = PPX_pft(NZ,NY,NX)
    plt_distb%O2ByFire_CumYr_pft(NZ)   = O2ByFire_CumYr_pft(NZ,NY,NX)
    plt_ew%ENGYX_pft(NZ)               = ENGYX_pft(NZ,NY,NX)
    plt_bgcr%CanopyRespC_CumYr_pft(NZ) = CanopyRespC_CumYr_pft(NZ,NY,NX)
    plt_ew%ETCanopy_CumYr_pft(NZ)      = ETCanopy_CumYr_pft(NZ,NY,NX)

    plt_morph%BranchNumber_pft(NZ)    = BranchNumber_pft(NZ,NY,NX)
    plt_morph%NGTopRootLayer_pft(NZ)  = NGTopRootLayer_pft(NZ,NY,NX)
    plt_pheno%doInitPlant_pft(NZ)     = doInitPlant_pft(NZ,NY,NX)
    plt_morph%NMaxRootBotLayer_pft(NZ) = NMaxRootBotLayer_pft(NZ,NY,NX)
    plt_morph%NumStructuralRootAxes_pft(NZ)     = NumStructuralRootAxes_pft(NZ,NY,NX)
    plt_morph%MainBranchNum_pft(NZ)   = MainBranchNum_pft(NZ,NY,NX)
    plt_morph%NumOfBranches_pft(NZ)   = NumOfBranches_pft(NZ,NY,NX)

    plt_pheno%IsPlantActive_pft(NZ)     = IsPlantActive_pft(NZ,NY,NX)
    plt_distb%iDayPlanting_pft(NZ)      = iDayPlanting_pft(NZ,NY,NX)
    plt_distb%iDayPlantHarvest_pft(NZ)  = iDayPlantHarvest_pft(NZ,NY,NX)
    plt_distb%iYearPlantHarvest_pft(NZ) = iYearPlantHarvest_pft(NZ,NY,NX)

    plt_distb%CanopyCutProxy_pft(NZ) = CanopyCutProxy_pft(NZ,I,NY,NX)
    plt_distb%iHarvstType_pft(NZ)         = iHarvstType_pft(NZ,I,NY,NX)
    plt_distb%jHarvstType_pft(NZ)         = jHarvstType_pft(NZ,I,NY,NX)

    plt_distb%THIN_pft(NZ)                = THIN_pft(NZ,I,NY,NX)
    plt_morph%CanopyStemSurfArea_pft(NZ)  = CanopyStemSurfArea_pft(NZ,NY,NX)
    plt_morph%CanopyLeafArea_pft(NZ)      = CanopyLeafArea_pft(NZ,NY,NX)
    plt_morph%CanopyLeafAreaMax_pft(NZ)   = CanopyLeafAreaMax_pft(NZ,NY,NX)

    plt_photo%O2I_pft(NZ)                      = O2I_pft(NZ,NY,NX)
    plt_photo%LeafIntracellularCO2_pft(NZ) = LeafIntracellularCO2_pft(NZ,NY,NX)
    plt_bgcr%CO2NetFix_pft(NZ)            = CO2NetFix_pft(NZ,NY,NX)

    plt_allom%rProteinC2RootP_pft(NZ) = rProteinC2RootP_pft(NZ,NY,NX)
    plt_allom%rProteinC2RootN_pft(NZ) = rProteinC2RootN_pft(NZ,NY,NX)
    plt_allom%rProteinC2LeafN_pft(NZ) = rProteinC2LeafN_pft(NZ,NY,NX)
    plt_allom%rProteinC2LeafP_pft(NZ) = rProteinC2LeafP_pft(NZ,NY,NX)

    plt_photo%DiffCO2Atmos2Intracel_pft(NZ) = DiffCO2Atmos2Intracel_pft(NZ,NY,NX)
    plt_photo%AirConc_pft(NZ)               = AirConc_pft(NZ,NY,NX)
    plt_allom%FracGroth2Node_pft(NZ)        = FracGroth2Node_pft(NZ,NY,NX)
    plt_morph%CanopySeedNumX_pft(NZ)    = CanopySeedNumX_pft(NZ,NY,NX)
    plt_morph%HypocotHeight_pft(NZ)                          = HypocotHeight_pft(NZ,NY,NX)
    plt_rbgc%PlantRootSoilElmNetX_pft(1:NumPlantChemElms,NZ) = PlantRootSoilElmNetX_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_morph%CanopyHeight4WatUptake_pft(NZ)                       = CanopyHeight4WatUptake_pft(NZ,NY,NX)
    plt_morph%MaxSoilLays4Root_pft(NZ)                           = MaxSoilLays4Root_pft(NZ,NY,NX)
    plt_photo%RawCanopy2Atm_pft(NZ)                       = RawCanopy2Atm_pft(NZ,NY,NX)
    plt_photo%CanPStomaResistH2O_pft(NZ)                     = CanPStomaResistH2O_pft(NZ,NY,NX)
    plt_ew%TKC_pft(NZ)                                           = TKC_pft(NZ,NY,NX)
    plt_ew%HeatXAir2PCan_pft(NZ)                             = HeatXAir2PCan_pft(NZ,NY,NX)
    plt_rad%RadNet2Canopy_pft(NZ)                            = RadNet2Canopy_pft(NZ,NY,NX)
    plt_rad%LWRadCanopy_pft(NZ)                              = LWRadCanopy_pft(NZ,NY,NX)
    plt_ew%CanopyEvapTransLHeat_pft(NZ)                             = CanopyEvapTransLHeat_pft(NZ,NY,NX)
    plt_ew%VapXAir2Canopy_pft(NZ)                            = VapXAir2Canopy_pft(NZ,NY,NX)
    plt_photo%CanopyMinStomaResistH2O_pft(NZ)                = CanopyMinStomaResistH2O_pft(NZ,NY,NX)
    plt_pheno%TempOffset_pft(NZ)                             = TempOffset_pft(NZ,NY,NX)

    plt_pheno%PlantO2Stress_pft(NZ) = PlantO2Stress_pft(NZ,NY,NX)
    plt_site%PlantPopuLive_pft(NZ)  = PlantPopuLive_pft(NZ,NY,NX)
    plt_site%PlantPopuDead_pft(NZ)  = PlantPopuDead_pft(NZ,NY,NX)
    plt_ew%PSICanopy_pft(NZ)                              = PSICanopy_pft(NZ,NY,NX)
    plt_ew%PSICanopyTurg_pft(NZ)                          = PSICanopyTurg_pft(NZ,NY,NX)
    plt_photo%CO2CuticleResist_pft(NZ)                    = CO2CuticleResist_pft(NZ,NY,NX)
    plt_bgcr%RootGasLossDisturb_pft(idg_beg:idg_NH3,NZ) = RootGasLossDisturb_pft(idg_beg:idg_NH3,NZ,NY,NX)
    plt_ew%RawIsoTCanopy2Atm_pft(NZ)                        = RawIsoTCanopy2Atm_pft(NZ,NY,NX)
    plt_photo%CO2Solubility_pft(NZ)                       = CO2Solubility_pft(NZ,NY,NX)
    plt_morph%SeedDepth_pft(NZ)                           = SeedDepth_pft(NZ,NY,NX)
    plt_morph%PlantinDepz_pft(NZ)                         = PlantinDepz_pft(NZ,NY,NX)
    plt_morph%SeedMeanLen_pft(NZ)                         = SeedMeanLen_pft(NZ,NY,NX)
    plt_morph%SeedVolumeMean_pft(NZ)                      = SeedVolumeMean_pft(NZ,NY,NX)
    plt_morph%SeedAreaMean_pft(NZ)                        = SeedAreaMean_pft(NZ,NY,NX)
    plt_pheno%TC4LeafOut_pft(NZ)                          = TC4LeafOut_pft(NZ,NY,NX)
    plt_pheno%TCGroth_pft(NZ)                             = TCGroth_pft(NZ,NY,NX)
    plt_pheno%TC4LeafOff_pft(NZ)                          = TC4LeafOff_pft(NZ,NY,NX)
    plt_pheno%TKGroth_pft(NZ)                             = TKGroth_pft(NZ,NY,NX)
    plt_pheno%fTCanopyGroth_pft(NZ)                       = fTCanopyGroth_pft(NZ,NY,NX)
    plt_pheno%MorphogenBase_pft(NZ)                       = MorphogenBase_pft(NZ,NY,NX)
    plt_photo%Km4LeafaqCO2_pft(NZ)                         = Km4LeafaqCO2_pft(NZ,NY,NX)
    plt_photo%Km4RubiscoCarboxy_pft(NZ)                    = Km4RubiscoCarboxy_pft(NZ,NY,NX)
    plt_bgcr%NH3Emis_CumYr_pft(NZ)                         = NH3Emis_CumYr_pft(NZ,NY,NX)
    plt_bgcr%NodulInfectElms_pft(1:NumPlantChemElms,NZ)    = NodulInfectElms_pft(1:NumPlantChemElms,NZ,NY,NX)
    plt_bgcr%PlantN2Fix_CumYr_pft(NZ)                      = PlantN2Fix_CumYr_pft(NZ,NY,NX)
    plt_rbgc%RootNO3Uptake_pft(NZ)                         = RootNO3Uptake_pft(NZ,NY,NX)
    plt_rbgc%RootNH4Uptake_pft(NZ)                         = RootNH4Uptake_pft(NZ,NY,NX)
    plt_rbgc%RootHPO4Uptake_pft(NZ)                        = RootHPO4Uptake_pft(NZ,NY,NX)
    plt_rbgc%RootH2PO4Uptake_pft(NZ)                       = RootH2PO4Uptake_pft(NZ,NY,NX)
    plt_ew%WatHeldOnCanopy_pft(NZ)                         = WatHeldOnCanopy_pft(NZ,NY,NX)
    plt_ew%SnowOnCanopy_pft(NZ)                            = SnowOnCanopy_pft(NZ,NY,NX)
    plt_ew%VHeatCapCanopy_pft(NZ)                          = VHeatCapCanopy_pft(NZ,NY,NX)
    plt_distb%CH4ByFire_CumYr_pft(NZ)                      = CH4ByFire_CumYr_pft(NZ,NY,NX)
    plt_distb%CO2ByFire_CumYr_pft(NZ)                      = CO2ByFire_CumYr_pft(NZ,NY,NX)
    plt_distb%N2ObyFire_CumYr_pft(NZ)                      = N2ObyFire_CumYr_pft(NZ,NY,NX)
    plt_distb%NH3byFire_CumYr_pft(NZ)                      = NH3byFire_CumYr_pft(NZ,NY,NX)
    plt_distb%PO4byFire_CumYr_pft(NZ)                      = PO4byFire_CumYr_pft(NZ,NY,NX)
    plt_ew%CanopyBiomWater_pft(NZ)                         = CanopyBiomWater_pft(NZ,NY,NX)
    plt_pheno%HoursTooLowPsiCan_pft(NZ)                    = HoursTooLowPsiCan_pft(NZ,NY,NX)
    plt_biom%CanopyLeafSheathC_pft(NZ)                      = CanopyLeafSheathC_pft(NZ,NY,NX)

    plt_biom%ZERO4LeafVar_pft(NZ)   = ZERO4LeafVar_pft(NZ,NY,NX)
    plt_biom%ZERO4Groth_pft(NZ)     = ZERO4Groth_pft(NZ,NY,NX)
    plt_morph%CanopyHeightDead_pft(NZ) = CanopyHeightDead_pft(NZ,NY,NX)
    plt_morph%CanopyHeightLive_pft(NZ)  = CanopyHeightLive_pft(NZ,NY,NX)
    plt_morph%StalkHeight_pft(NZ)   = StalkHeight_pft(NZ,NY,NX)
  end subroutine SendPlantState
end module PlantStateTransferMod
