module AqueChemDatatype
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridConsts
  implicit none
  public
  save
  character(len=*), private, parameter :: mod_filename = __FILE__


  real(r8) :: CAL(JZ,JY,JX)                     !soil Al content, [mg kg-1]
  real(r8) :: CFE(JZ,JY,JX)                     !soil Fe content, [mg kg-1]
  real(r8) :: CCA(JZ,JY,JX)                     !soil Ca content, [mg kg-1]
  real(r8) :: CMG(JZ,JY,JX)                     !soil Mg content, [mg kg-1]
  real(r8) :: CNA(JZ,JY,JX)                     !soil Na content, [mg kg-1]
  real(r8) :: CKA(JZ,JY,JX)                     !soil K content, [mg kg-1]
  real(r8) :: CSO4(JZ,JY,JX)                    !soil SO4 content, [mg kg-1]
  real(r8) :: CCL(JZ,JY,JX)                     !soil Cl content, [mg kg-1]
  real(r8) :: CALOH(JZ,JY,JX)                   !soil AlOH3 content, [mg kg-1]
  real(r8) :: CFEOH(JZ,JY,JX)                   !soil FeOH3 content, [mg kg-1]
  real(r8) :: CCACO(JZ,JY,JX)                   !soil CaCO3 content, [mg kg-1]
  real(r8) :: CCASO(JZ,JY,JX)                   !soil CaSO4 content, [mg kg-1]
  real(r8) :: CALPO(JZ,JY,JX)                   !soil AlPO4 content, [mg kg-1]
  real(r8) :: CFEPO(JZ,JY,JX)                   !soil FePO4 content, [mg kg-1]
  real(r8) :: CCAPD(JZ,JY,JX)                   !soil CaHPO4 content, [mg kg-1]
  real(r8) :: CCAPH(JZ,JY,JX)                   !soil apatite content, [mg kg-1]

  real(r8) :: GKC4(JZ,JY,JX)                    !Ca-NH4 Gapon selectivity coefficient, [-]
  real(r8) :: GKCH(JZ,JY,JX)                    !Ca-H Gapon selectivity coefficient, [-]
  real(r8) :: GKCA(JZ,JY,JX)                    !Ca-Al Gapon selectivity coefficient, [-]
  real(r8) :: GKCM(JZ,JY,JX)                    !Ca-Mg Gapon selectivity coefficient, [-]
  real(r8) :: GKCN(JZ,JY,JX)                    !Ca-Na Gapon selectivity coefficient, [-]
  real(r8) :: GKCK(JZ,JY,JX)                    !Ca-K Gapon selectivity coefficient, [-]

  real(r8) :: ZCO3(0:JZ,JY,JX)                  !soil aqueous CO3 content micropore, [mol d-2]
  real(r8) :: ZHCO3(0:JZ,JY,JX)                 !soil aqueous HCO3 content micropore, [mol d-2]
  real(r8) :: XN4(0:JZ,JY,JX)                   !exchangeable NH4 non-band, [mol d-2]
  real(r8) :: XNB(0:JZ,JY,JX)                   !exchangeable NH4 band, [mol d-2]
  real(r8) :: ZAL(0:JZ,JY,JX)                   !soil aqueous Al content micropore, [mol d-2]
  real(r8) :: ZFE(0:JZ,JY,JX)                   !soil aqueous Fe content micropore, [mol d-2]
  real(r8) :: ZHY(0:JZ,JY,JX)                   !soil aqueous H content micropore, [mol d-2]
  real(r8) :: ZCA(0:JZ,JY,JX)                   !soil aqueous Ca content micropore, [mol d-2]
  real(r8) :: ZMG(0:JZ,JY,JX)                   !soil aqueous Mg content micropore, [mol d-2]
  real(r8) :: ZNA(0:JZ,JY,JX)                   !soil aqueous Na content micropore, [mol d-2]
  real(r8) :: ZKA(0:JZ,JY,JX)                   !soil aqueous K content micropore, [mol d-2]
  real(r8) :: ZOH(0:JZ,JY,JX)                   !soil aqueous OH content micropore, [mol d-2]
  real(r8) :: ZSO4(0:JZ,JY,JX)                  !soil aqueous SO4 content micropore, [mol d-2]
  real(r8) :: ZCL(0:JZ,JY,JX)                   !soil aqueous Cl content micropore, [mol d-2]
  real(r8) :: ZALOH1(0:JZ,JY,JX)                !soil aqueous AlOH content micropore, [mol d-2]
  real(r8) :: ZALOH2(0:JZ,JY,JX)                !soil aqueous AlOH2 content micropore, [mol d-2]
  real(r8) :: ZALOH3(0:JZ,JY,JX)                !soil aqueous AlOH3 content micropore, [mol d-2]
  real(r8) :: ZALOH4(0:JZ,JY,JX)                !soil aqueous AlOH4 content micropore, [mol d-2]
  real(r8) :: ZALS(0:JZ,JY,JX)                  !soil aqueous AlSO4 content micropore, [mol d-2]
  real(r8) :: ZFEOH1(0:JZ,JY,JX)                !soil aqueous FeOH content micropore, [mol d-2]
  real(r8) :: ZFEOH2(0:JZ,JY,JX)                !soil aqueous FeOH2 content micropore, [mol d-2]
  real(r8) :: ZFEOH3(0:JZ,JY,JX)                !soil aqueous FeOH3 content micropore, [mol d-2]
  real(r8) :: ZFEOH4(0:JZ,JY,JX)                !soil aqueous FeOH4 content micropore, [mol d-2]
  real(r8) :: ZFES(0:JZ,JY,JX)                  !soil aqueous FeSO4 content micropore, [mol d-2]
  real(r8) :: ZCAO(0:JZ,JY,JX)                  !soil aqueous CaOH2 content micropore, [mol d-2]
  real(r8) :: ZCAC(0:JZ,JY,JX)                  !soil aqueous CACO3 content micropore, [mol d-2]
  real(r8) :: ZCAH(0:JZ,JY,JX)                  !soil aqueous CaHCO3 content micropore, [mol d-2]
  real(r8) :: ZCAS(0:JZ,JY,JX)                  !soil aqueous CaSO4 content micropore, [mol d-2]
  real(r8) :: ZMGO(0:JZ,JY,JX)                  !soil aqueous MgOH content micropore, [mol d-2]
  real(r8) :: ZMGC(0:JZ,JY,JX)                  !soil aqueous MgCO3 content micropore, [mol d-2]
  real(r8) :: ZMGH(0:JZ,JY,JX)                  !soil aqueous MgHCO3 content micropore, [mol d-2]
  real(r8) :: ZMGS(0:JZ,JY,JX)                  !soil aqueous MgSO4 content micropore, [mol d-2]
  real(r8) :: ZNAC(0:JZ,JY,JX)                  !soil aqueous NaCO3 content micropore, [mol d-2]
  real(r8) :: ZNAS(0:JZ,JY,JX)                  !soil aqueous NaSO4 content micropore, [mol d-2]
  real(r8) :: ZKAS(0:JZ,JY,JX)                  !soil aqueous KSO4 content micropore, [mol d-2]
  real(r8) :: H0PO4(0:JZ,JY,JX)                 !soil aqueous PO4 content micropore non-band, [mol d-2]
  real(r8) :: H3PO4(0:JZ,JY,JX)                 !soil aqueous H3PO4 content micropore non-band, [mol d-2]
  real(r8) :: ZFE1P(0:JZ,JY,JX)                 !soil aqueous FeHPO4 content micropore non-band, [mol d-2]
  real(r8) :: ZFE2P(0:JZ,JY,JX)                 !soil aqueous FeH2PO4 content micropore non-band, [mol d-2]
  real(r8) :: ZCA0P(0:JZ,JY,JX)                 !soil aqueous CaPO4 content micropore non-band, [mol d-2]
  real(r8) :: ZCA1P(0:JZ,JY,JX)                 !soil aqueous CaHPO4 content micropore non-band, [mol d-2]
  real(r8) :: ZCA2P(0:JZ,JY,JX)                 !soil aqueous CaH2PO4 content micropore non-band, [mol d-2]
  real(r8) :: ZMG1P(0:JZ,JY,JX)                 !soil aqueous MgHPO4 content micropore non-band, [mol d-2]
  real(r8) :: H0POB(JZ,JY,JX)                   !soil aqueous PO4 content micropore band, [mol d-2]
  real(r8) :: H3POB(JZ,JY,JX)                   !soil aqueous H3PO4 content micropore band, [mol d-2]
  real(r8) :: ZFE1PB(JZ,JY,JX)                  !soil aqueous FeHPO4 content micropore band, [mol d-2]
  real(r8) :: ZFE2PB(JZ,JY,JX)                  !soil aqueous FeH2PO4 content micropore band, [mol d-2]
  real(r8) :: ZCA0PB(JZ,JY,JX)                  !soil aqueous CaPO4 content micropore band, [mol d-2]
  real(r8) :: ZCA1PB(JZ,JY,JX)                  !soil aqueous CaHPO4 content micropore band, [mol d-2]
  real(r8) :: ZCA2PB(JZ,JY,JX)                  !soil aqueous CaH2PO4 content micropore band, [mol d-2]
  real(r8) :: ZMG1PB(JZ,JY,JX)                  !soil aqueous MgHPO4 content micropore band, [mol d-2]
  real(r8) :: XHY(JZ,JY,JX)                     !exchangeable H , [mol d-2]
  real(r8) :: XAL(JZ,JY,JX)                     !exchangeable Al, [mol d-2]
  real(r8) :: XCA(JZ,JY,JX)                     !exchangeable Ca, [mol d-2]
  real(r8) :: XMG(JZ,JY,JX)                     !exchangeable Mg , [mol d-2]
  real(r8) :: XNA(JZ,JY,JX)                     !exchangeable Na, [mol d-2]
  real(r8) :: XKA(JZ,JY,JX)                     !exchangeable K, [mol d-2]
  real(r8) :: XHC(JZ,JY,JX)                     !exchangeable COOH , [mol d-2]
  real(r8) :: XALO2(JZ,JY,JX)                   !exchangeable AlOH2 , [mol d-2]
  real(r8) :: XOH0(0:JZ,JY,JX)                  !exchangeable OH- non-band, [mol d-2]
  real(r8) :: XOH1(0:JZ,JY,JX)                  !exchangeable OH  non-band, [mol d-2]
  real(r8) :: XOH2(0:JZ,JY,JX)                  !exchangeable OH2  non-band, [mol d-2]
  real(r8) :: XH1P(0:JZ,JY,JX)                  !exchangeable HPO4  non-band, [mol d-2]
  real(r8) :: XH2P(0:JZ,JY,JX)                  !exchangeable H2PO4  non-band, [mol d-2]
  real(r8) :: XOH0B(0:JZ,JY,JX)                 !exchangeable OH- band, [mol d-2]
  real(r8) :: XFE(JZ,JY,JX)                     !exchangeable Fe, [mol d-2]
  real(r8) :: XFEO2(JZ,JY,JX)                   !exchangeable Fe(OH)2, [mol d-2]
  real(r8) :: XOH1B(0:JZ,JY,JX)                 !exchangeable OH  band, [mol d-2]
  real(r8) :: XOH2B(0:JZ,JY,JX)                 !exchangeable OH2  band, [mol d-2]
  real(r8) :: XH1PB(0:JZ,JY,JX)                 !exchangeable HPO4  band, [mol d-2]
  real(r8) :: XH2PB(0:JZ,JY,JX)                 !exchangeable H2PO4  band, [mol d-2]

  real(r8) :: PCAPD(0:JZ,JY,JX)                 !precipitated CaHPO4 non-band, [mol d-2]
  real(r8) :: PCAPH(0:JZ,JY,JX)                 !precipitated hydroxyapatite non-band, [mol d-2]
  real(r8) :: PALOH(JZ,JY,JX)                   !precipitated AlOH3, [mol d-2]
  real(r8) :: PFEOH(JZ,JY,JX)                   !precipitated FeOH3, [mol d-2]
  real(r8) :: PCACO(JZ,JY,JX)                   !precipitated CaCO3, [mol d-2]
  real(r8) :: PCASO(JZ,JY,JX)                   !precipitated CaSO4, [mol d-2]
  real(r8) :: PALPO(0:JZ,JY,JX)                 !precipitated AlPO4 non-band, [mol d-2]
  real(r8) :: PFEPO(0:JZ,JY,JX)                 !precipitated FePO4 non-band, [mol d-2]
  real(r8) :: PCAPM(0:JZ,JY,JX)                 !precipitated CaH2PO4 non-band, [mol d-2]
  real(r8) :: PALPB(0:JZ,JY,JX)                 !precipitated AlPO4 band, [mol d-2]
  real(r8) :: PFEPB(0:JZ,JY,JX)                 !precipitated FePO4 band, [mol d-2]
  real(r8) :: PCPDB(0:JZ,JY,JX)                 !precipitated CaHPO4 band, [mol d-2]
  real(r8) :: PCPMB(0:JZ,JY,JX)                 !precipitated CaH2PO4 , [mol d-2]

  real(r8) :: ECND(JZ,JY,JX)                    !electrical conductivity , [dS m-1]
  real(r8) :: CSTR(JZ,JY,JX)                    !solution ion strength, [mol m-3]
  real(r8) :: CION(JZ,JY,JX)                    !solution ion concentratiom, [mol m-3]
  real(r8) :: XCEC(JZ,JY,JX)                    !cation exchange capacity, [mol d-2]
  real(r8) :: XAEC(JZ,JY,JX)                    !anion exchange capacity, [mol d-2]

  real(r8) :: ZALH(JZ,JY,JX)                    !aqueous Al content macropore, [mol d-2]
  real(r8) :: ZFEH(JZ,JY,JX)                    !aqueous Fe content macropore, [mol d-2]
  real(r8) :: ZHYH(JZ,JY,JX)                    !aqueous H content macropore, [mol d-2]
  real(r8) :: ZCCH(JZ,JY,JX)                    !aqueous CO3 content macropore, [mol d-2]
  real(r8) :: ZMAH(JZ,JY,JX)                    !aqueous Mg content macropore, [mol d-2]
  real(r8) :: ZNAH(JZ,JY,JX)                    !aqueous Na content macropore, [mol d-2]
  real(r8) :: ZKAH(JZ,JY,JX)                    !aqueous K content macropore, [mol d-2]
  real(r8) :: ZOHH(JZ,JY,JX)                    !aqueous OH content macropore, [mol d-2]
  real(r8) :: ZSO4H(JZ,JY,JX)                   !aqueous SO4 content macropore, [mol d-2]
  real(r8) :: ZCLH(JZ,JY,JX)                    !aqueous Cl content macropore, [mol d-2]
  real(r8) :: ZCO3H(JZ,JY,JX)                   !aqueous CO3 content macropore, [mol d-2]
  real(r8) :: ZHCO3H(JZ,JY,JX)                  !aqueous HCO3 content macropore, [mol d-2]
  real(r8) :: ZALO1H(JZ,JY,JX)                  !aqueous AlOH content macropore, [mol d-2]
  real(r8) :: ZALO2H(JZ,JY,JX)                  !aqueous AlOH2 content macropore, [mol d-2]
  real(r8) :: ZALO3H(JZ,JY,JX)                  !aqueous AlOH3 content macropore, [mol d-2]
  real(r8) :: ZALO4H(JZ,JY,JX)                  !aqueous AlOH4 content macropore, [mol d-2]
  real(r8) :: ZALSH(JZ,JY,JX)                   !aqueous AlSO4 content macropore, [mol d-2]
  real(r8) :: ZFEO1H(JZ,JY,JX)                  !aqueous FeOH content macropore, [mol d-2]
  real(r8) :: ZFEO2H(JZ,JY,JX)                  !aqueous FeOH2 content macropore, [mol d-2]
  real(r8) :: ZFEO3H(JZ,JY,JX)                  !aqueous FeOH3 content macropore, [mol d-2]
  real(r8) :: ZFEO4H(JZ,JY,JX)                  !aqueous FeOH4 content macropore, [mol d-2]
  real(r8) :: ZFESH(JZ,JY,JX)                   !aqueous FeSO4 content macropore, [mol d-2]
  real(r8) :: ZCAOH(JZ,JY,JX)                   !aqueous CaOH content macropore, [mol d-2]
  real(r8) :: ZCACH(JZ,JY,JX)                   !aqueous CaCO3 content macropore, [mol d-2]
  real(r8) :: ZCAHH(JZ,JY,JX)                   !aqueous CaHCO3 content macropore, [mol d-2]
  real(r8) :: ZCASH(JZ,JY,JX)                   !aqueous CaSO4 content macropore, [mol d-2]
  real(r8) :: PCPHB(0:JZ,JY,JX)                 !precipitated hydroxyapatite band, [mol d-2]
  real(r8) :: ZMGOH(JZ,JY,JX)                   !aqueous MgOH content macropore, [mol d-2]
  real(r8) :: ZMGCH(JZ,JY,JX)                   !aqueous MgCO3 content macropore, [mol d-2]
  real(r8) :: ZMGHH(JZ,JY,JX)                   !aqueous MgHCO3 content macropore, [mol d-2]
  real(r8) :: ZMGSH(JZ,JY,JX)                   !aqueous MgSO4 content macropore, [mol d-2]
  real(r8) :: ZNACH(JZ,JY,JX)                   !aqueous NaCO3 content macropore, [mol d-2]
  real(r8) :: ZNASH(JZ,JY,JX)                   !aqueous NaSO4 content macropore, [mol d-2]
  real(r8) :: ZKASH(JZ,JY,JX)                   !aqueous KSO4 content macropore, [mol d-2]
  real(r8) :: H0PO4H(JZ,JY,JX)                  !soil aqueous PO4 content non-band macropore , [mol d-2]
  real(r8) :: H3PO4H(JZ,JY,JX)                  !soil aqueous H3PO4 content non-band macropore, [mol d-2]
  real(r8) :: ZFE1PH(JZ,JY,JX)                  !soil aqueous FeHPO4 content non-band macropore, [mol d-2]
  real(r8) :: ZFE2PH(JZ,JY,JX)                  !soil aqueous FeH2PO4 content non-band macropore, [mol d-2]
  real(r8) :: ZCA0PH(JZ,JY,JX)                  !soil aqueous CaPO4 content non-band macropore, [mol d-2]
  real(r8) :: ZCA1PH(JZ,JY,JX)                  !soil aqueous CaHPO4 content non-band macropore, [mol d-2]
  real(r8) :: ZCA2PH(JZ,JY,JX)                  !soil aqueous CaH2PO4 content non-band macropore, [mol d-2]
  real(r8) :: ZMG1PH(JZ,JY,JX)                  !soil aqueous MgHPO4 content non-band macropore, [mol d-2]
  real(r8) :: H0POBH(JZ,JY,JX)                  !soil aqueous PO4 content band macropore , [mol d-2]
  real(r8) :: H3POBH(JZ,JY,JX)                  !soil aqueous H3PO4 content band macropore, [mol d-2]
  real(r8) :: ZFE1BH(JZ,JY,JX)                  !soil aqueous FeHPO4 content band macropore, [mol d-2]
  real(r8) :: ZFE2BH(JZ,JY,JX)                  !soil aqueous FeH2PO4 content band macropore, [mol d-2]
  real(r8) :: ZCA0BH(JZ,JY,JX)                  !soil aqueous CaPO4 content band macropore, [mol d-2]
  real(r8) :: ZCA1BH(JZ,JY,JX)                  !soil aqueous CaHPO4 content band macropore, [mol d-2]
  real(r8) :: ZCA2BH(JZ,JY,JX)                  !soil aqueous CaH2PO4 content band macropore, [mol d-2]
  real(r8) :: ZMG1BH(JZ,JY,JX)                  !soil aqueous MgHPO4 content band macropore, [mol d-2]

  real(r8) :: XALFLS(3,0:JD,JV,JH)              !total Al in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFEFLS(3,0:JD,JV,JH)              !total Fe in micropore water flux, [mol d-2 h-1]
  real(r8) :: XHYFLS(3,0:JD,JV,JH)              !total H in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCAFLS(3,0:JD,JV,JH)              !total Ca in micropore water flux, [mol d-2 h-1]
  real(r8) :: XMGFLS(3,0:JD,JV,JH)              !total Mg in micropore water flux, [mol d-2 h-1]
  real(r8) :: XNAFLS(3,0:JD,JV,JH)              !total Na in micropore water flux, [mol d-2 h-1]
  real(r8) :: XKAFLS(3,0:JD,JV,JH)              !total K in micropore water flux, [mol d-2 h-1]
  real(r8) :: XOHFLS(3,0:JD,JV,JH)              !total OH in micropore water flux, [mol d-2 h-1]
  real(r8) :: XSOFLS(3,0:JD,JV,JH)              !total SO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCLFLS(3,0:JD,JV,JH)              !total Cl in micropore water flux, [mol d-2 h-1]
  real(r8) :: XC3FLS(3,0:JD,JV,JH)              !total CO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XHCFLS(3,0:JD,JV,JH)              !total HCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XAL1FS(3,0:JD,JV,JH)              !total AlOH in micropore water flux, [mol d-2 h-1]
  real(r8) :: XAL2FS(3,0:JD,JV,JH)              !total AlOH2 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XAL3FS(3,0:JD,JV,JH)              !total AlOH3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XAL4FS(3,0:JD,JV,JH)              !total AlOH4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XALSFS(3,0:JD,JV,JH)              !total AlSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFE1FS(3,0:JD,JV,JH)              !total FeOH in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFE2FS(3,0:JD,JV,JH)              !total FeOH2 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFE3FS(3,0:JD,JV,JH)              !total FeOH3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFE4FS(3,0:JD,JV,JH)              !total FeOH4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XFESFS(3,0:JD,JV,JH)              !total FeSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCAOFS(3,0:JD,JV,JH)              !total CaOH in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCACFS(3,0:JD,JV,JH)              !total CaCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCAHFS(3,0:JD,JV,JH)              !total CaHCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XCASFS(3,0:JD,JV,JH)              !total CaSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XMGOFS(3,0:JD,JV,JH)              !total MgOH in micropore water flux, [mol d-2 h-1]
  real(r8) :: XMGCFS(3,0:JD,JV,JH)              !total MgCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XMGHFS(3,0:JD,JV,JH)              !total MgHCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XMGSFS(3,0:JD,JV,JH)              !total MgSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XNACFS(3,0:JD,JV,JH)              !total NaCO3 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XNASFS(3,0:JD,JV,JH)              !total NaSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XKASFS(3,0:JD,JV,JH)              !total KSO4 in micropore water flux, [mol d-2 h-1]
  real(r8) :: XH0PFS(3,0:JD,JV,JH)              !total PO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH3PFS(3,0:JD,JV,JH)              !total H3PO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XF1PFS(3,0:JD,JV,JH)              !total FeHPO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XF2PFS(3,0:JD,JV,JH)              !total FeH2PO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC0PFS(3,0:JD,JV,JH)              !total CaPO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC1PFS(3,0:JD,JV,JH)              !total CaHPO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC2PFS(3,0:JD,JV,JH)              !total CaH2PO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XM1PFS(3,0:JD,JV,JH)              !total MgHPO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH0BFB(3,0:JD,JV,JH)              !total PO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XH3BFB(3,0:JD,JV,JH)              !total H3PO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XF1BFB(3,0:JD,JV,JH)              !total FeHPO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XF2BFB(3,0:JD,JV,JH)              !total FeH2PO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XC0BFB(3,0:JD,JV,JH)              !total CaPO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XC1BFB(3,0:JD,JV,JH)              !total CaHPO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XC2BFB(3,0:JD,JV,JH)              !total CaH2PO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XM1BFB(3,0:JD,JV,JH)              !total MgHPO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XALFHS(3,JD,JV,JH)                !total Al in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFEFHS(3,JD,JV,JH)                !total Fe in macropore water flux, [mol d-2 h-1]
  real(r8) :: XHYFHS(3,JD,JV,JH)                !total H in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCAFHS(3,JD,JV,JH)                !total Ca in macropore water flux, [mol d-2 h-1]
  real(r8) :: XMGFHS(3,JD,JV,JH)                !total Mg in macropore water flux, [mol d-2 h-1]
  real(r8) :: XNAFHS(3,JD,JV,JH)                !total Na in macropore water flux, [mol d-2 h-1]
  real(r8) :: XKAFHS(3,JD,JV,JH)                !total K in macropore water flux, [mol d-2 h-1]
  real(r8) :: XOHFHS(3,JD,JV,JH)                !total OH in macropore water flux, [mol d-2 h-1]
  real(r8) :: XSOFHS(3,JD,JV,JH)                !total SO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCLFHS(3,JD,JV,JH)                !total Cl in macropore water flux, [mol d-2 h-1]
  real(r8) :: XC3FHS(3,JD,JV,JH)                !total CO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XHCFHS(3,JD,JV,JH)                !total HCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XAL1HS(3,JD,JV,JH)                !total AlOH in macropore water flux, [mol d-2 h-1]
  real(r8) :: XAL2HS(3,JD,JV,JH)                !total AlOH2 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XAL3HS(3,JD,JV,JH)                !total AlOH3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XAL4HS(3,JD,JV,JH)                !total AlOH4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XALSHS(3,JD,JV,JH)                !total AlSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFE1HS(3,JD,JV,JH)                !total FeOH in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFE2HS(3,JD,JV,JH)                !total FeOH2 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFE3HS(3,JD,JV,JH)                !total FeOH3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFE4HS(3,JD,JV,JH)                !total FeOH4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XFESHS(3,JD,JV,JH)                !total FeSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCAOHS(3,JD,JV,JH)                !total CaOH in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCACHS(3,JD,JV,JH)                !total CaCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCAHHS(3,JD,JV,JH)                !total CaHCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XCASHS(3,JD,JV,JH)                !total CaSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XMGOHS(3,JD,JV,JH)                !total MgOH in macropore water flux, [mol d-2 h-1]
  real(r8) :: XMGCHS(3,JD,JV,JH)                !total MgCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XMGHHS(3,JD,JV,JH)                !total MgHCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XMGSHS(3,JD,JV,JH)                !total MgSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XNACHS(3,JD,JV,JH)                !total NaCO3 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XNASHS(3,JD,JV,JH)                !total NaSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XKASHS(3,JD,JV,JH)                !total KSO4 in macropore water flux, [mol d-2 h-1]
  real(r8) :: XH0PHS(3,JD,JV,JH)                !total PO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH3PHS(3,JD,JV,JH)                !total H3PO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XF1PHS(3,JD,JV,JH)                !total FeHPO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XF2PHS(3,JD,JV,JH)                !total FeH2PO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC0PHS(3,JD,JV,JH)                !total CaPO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC1PHS(3,JD,JV,JH)                !total CaHPO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XC2PHS(3,JD,JV,JH)                !total CaH2PO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XM1PHS(3,JD,JV,JH)                !total MgHPO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH0BHB(3,JD,JV,JH)                !total PO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XH3BHB(3,JD,JV,JH)                !total H3PO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XF1BHB(3,JD,JV,JH)                !total FeHPO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XF2BHB(3,JD,JV,JH)                !total FeH2PO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XC0BHB(3,JD,JV,JH)                !total CaPO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XC1BHB(3,JD,JV,JH)                !total CaHPO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XC2BHB(3,JD,JV,JH)                !total CaH2PO4 in macropore water flux band, [mol d-2 h-1]
  real(r8) :: XM1BHB(3,JD,JV,JH)                !total MgHPO4 in macropore water flux band, [mol d-2 h-1]

  real(r8) :: XOCFXS(0:jcplx1,JZ,JY,JX)              !total DOC micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XONFXS(0:jcplx1,JZ,JY,JX)              !total DON micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XOPFXS(0:jcplx1,JZ,JY,JX)              !total DOP micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XOAFXS(0:jcplx1,JZ,JY,JX)              !total acetate micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCOFXS(JZ,JY,JX)                  !total CO2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCHFXS(JZ,JY,JX)                  !total CH4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XOXFXS(JZ,JY,JX)                  !total O2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XHGFXS(JZ,JY,JX)                  !total H2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XNGFXS(JZ,JY,JX)                  !total N2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XN2FXS(JZ,JY,JX)                  !total N2O micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XN4FXW(JZ,JY,JX)                  !total NH4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XN3FXW(JZ,JY,JX)                  !total NH3 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XNOFXW(JZ,JY,JX)                  !total NO3 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XH2PXS(JZ,JY,JX)                  !total H2PO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XN4FXB(JZ,JY,JX)                  !total NH4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XN3FXB(JZ,JY,JX)                  !total NH3 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XNOFXB(JZ,JY,JX)                  !total NO3 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XH2BXB(JZ,JY,JX)                  !total H2PO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XNXFXS(JZ,JY,JX)                  !total NO2 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XH1PXS(JZ,JY,JX)                  !total HPO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XH1BXB(JZ,JY,JX)                  !total HPO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XH0PXS(JZ,JY,JX)                  !total PO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XH3PXS(JZ,JY,JX)                  !total H3PO4 micropore-macropore transfer non-band, [g d-2 h-1]


  real(r8) :: XALFXS(JZ,JY,JX)                  !total Al micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFEFXS(JZ,JY,JX)                  !total Fe micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XHYFXS(JZ,JY,JX)                  !total H micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCAFXS(JZ,JY,JX)                  !total Ca micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XMGFXS(JZ,JY,JX)                  !total Mg micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XNAFXS(JZ,JY,JX)                  !total Na micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XKAFXS(JZ,JY,JX)                  !total K micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XOHFXS(JZ,JY,JX)                  !total OH micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XSOFXS(JZ,JY,JX)                  !total SO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCLFXS(JZ,JY,JX)                  !total Cl micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XC3FXS(JZ,JY,JX)                  !total CO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XHCFXS(JZ,JY,JX)                  !total HCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XAL1XS(JZ,JY,JX)                  !total AlOH micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XAL2XS(JZ,JY,JX)                  !total AlOH2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XAL3XS(JZ,JY,JX)                  !total AlOH3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XAL4XS(JZ,JY,JX)                  !total AlOH4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XALSXS(JZ,JY,JX)                  !total AlSO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFE1XS(JZ,JY,JX)                  !total FeOH micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFE2XS(JZ,JY,JX)                  !total FeOH2 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFE3XS(JZ,JY,JX)                  !total FeOH3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFE4XS(JZ,JY,JX)                  !total FeOH4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XFESXS(JZ,JY,JX)                  !total FeSO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCAOXS(JZ,JY,JX)                  !total CaOH micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCACXS(JZ,JY,JX)                  !total CaCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCAHXS(JZ,JY,JX)                  !total CaHCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XCASXS(JZ,JY,JX)                  !total CaSO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XMGOXS(JZ,JY,JX)                  !total MgOH micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XMGCXS(JZ,JY,JX)                  !total MgCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XMGHXS(JZ,JY,JX)                  !total MgHCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XMGSXS(JZ,JY,JX)                  !total MgSO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XNACXS(JZ,JY,JX)                  !total NaCO3 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XNASXS(JZ,JY,JX)                  !total NaSO4 micropore-macropore transfer, [g d-2 h-1]
  real(r8) :: XKASXS(JZ,JY,JX)                  !total KSO4 micropore-macropore transfer, [g d-2 h-1]

  real(r8) :: XF1PXS(JZ,JY,JX)                  !total FeHPO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XF2PXS(JZ,JY,JX)                  !total FeH2PO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XC0PXS(JZ,JY,JX)                  !total CaPO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XC1PXS(JZ,JY,JX)                  !total CaHPO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XC2PXS(JZ,JY,JX)                  !total CaH2PO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XM1PXS(JZ,JY,JX)                  !total MgHPO4 micropore-macropore transfer non-band, [g d-2 h-1]
  real(r8) :: XH0BXB(JZ,JY,JX)                  !total PO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XH3BXB(JZ,JY,JX)                  !total H3PO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XF1BXB(JZ,JY,JX)                  !total FeHPO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XF2BXB(JZ,JY,JX)                  !total FeH2PO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XC0BXB(JZ,JY,JX)                  !total CaPO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XC1BXB(JZ,JY,JX)                  !total CaHPO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XC2BXB(JZ,JY,JX)                  !total CaH2PO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XM1BXB(JZ,JY,JX)                  !total MgHPO4 micropore-macropore transfer band, [g d-2 h-1]
  real(r8) :: XNXFXB(JZ,JY,JX)                  !total MgHPO4 micropore-macropore transfer band, [g d-2 h-1]


  real(r8) :: TRN4S(0:JZ,JY,JX)                 !total solute NH4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRN3S(0:JZ,JY,JX)                 !total solute NH3 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRN4B(JZ,JY,JX)                   !total solute NH4 transformation band, [mol d-2 h-1]
  real(r8) :: TRNO3(0:JZ,JY,JX)                 !total solute NO3 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRN3B(JZ,JY,JX)                   !total solute NH3 transformation band, [mol d-2 h-1]
  real(r8) :: TRNOB(JZ,JY,JX)                   !total solute NO3 transformation band, [mol d-2 h-1]
  real(r8) :: TRH0P(JZ,JY,JX)                   !total solute PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRH1P(0:JZ,JY,JX)                 !total solute HPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRH2P(0:JZ,JY,JX)                 !total solute H2PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRH3P(JZ,JY,JX)                   !total solute H3PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRH0B(JZ,JY,JX)                   !total solute PO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRH1B(JZ,JY,JX)                   !total solute HPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRH2B(JZ,JY,JX)                   !total solute H2PO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRH3B(JZ,JY,JX)                   !total solute H3PO4 transformation band, [mol d-2 h-1]

  real(r8) :: TRAL(JZ,JY,JX)                    !total solute Al transformation, [mol d-2 h-1]
  real(r8) :: TRFE(JZ,JY,JX)                    !total solute Fe transformation, [mol d-2 h-1]
  real(r8) :: TRHY(JZ,JY,JX)                    !total solute H transformation, [mol d-2 h-1]
  real(r8) :: TRCA(JZ,JY,JX)                    !total solute Ca transformation, [mol d-2 h-1]
  real(r8) :: TRMG(JZ,JY,JX)                    !total solute Mg transformation, [mol d-2 h-1]
  real(r8) :: TRNA(JZ,JY,JX)                    !total solute Na transformation, [mol d-2 h-1]
  real(r8) :: TRKA(JZ,JY,JX)                    !total solute K transformation, [mol d-2 h-1]
  real(r8) :: TROH(JZ,JY,JX)                    !total solute OH transformation, [mol d-2 h-1]
  real(r8) :: TRSO4(JZ,JY,JX)                   !total solute SO4 transformation, [mol d-2 h-1]
  real(r8) :: TRCO3(JZ,JY,JX)                   !total solute CO3 transformation, [mol d-2 h-1]
  real(r8) :: TRHCO(JZ,JY,JX)                   !total solute HCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRCO2(JZ,JY,JX)                   !total solute CO2 transformation, [mol d-2 h-1]
  real(r8) :: TRH2O(0:JZ,JY,JX)                 !total solute H2O transformation, [mol d-2 h-1]
  real(r8) :: TRAL1(JZ,JY,JX)                   !total solute AlOH transformation, [mol d-2 h-1]
  real(r8) :: TRAL2(JZ,JY,JX)                   !total solute AlOH2 transformation, [mol d-2 h-1]
  real(r8) :: TRAL3(JZ,JY,JX)                   !total solute AlOH3 transformation, [mol d-2 h-1]
  real(r8) :: TRAL4(JZ,JY,JX)                   !total solute AlOH4 transformation, [mol d-2 h-1]
  real(r8) :: TRALS(JZ,JY,JX)                   !total solute AlSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRFE1(JZ,JY,JX)                   !total solute FeOH transformation, [mol d-2 h-1]
  real(r8) :: TRFE2(JZ,JY,JX)                   !total solute FeOH2 transformation, [mol d-2 h-1]
  real(r8) :: TRFE3(JZ,JY,JX)                   !total solute FeOH3 transformation, [mol d-2 h-1]
  real(r8) :: TRFE4(JZ,JY,JX)                   !total solute FeOH4 transformation, [mol d-2 h-1]
  real(r8) :: TRFES(JZ,JY,JX)                   !total solute FeSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRCAO(JZ,JY,JX)                   !total solute CaOH transformation, [mol d-2 h-1]
  real(r8) :: TRCAC(JZ,JY,JX)                   !total solute CaCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRCAH(JZ,JY,JX)                   !total solute CaHCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRCAS(JZ,JY,JX)                   !total solute CaSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRMGO(JZ,JY,JX)                   !total solute MgOH transformation, [mol d-2 h-1]
  real(r8) :: TRMGC(JZ,JY,JX)                   !total solute MgCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRMGH(JZ,JY,JX)                   !total solute MgHCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRMGS(JZ,JY,JX)                   !total solute MgSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRNAC(JZ,JY,JX)                   !total solute NaCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRNAS(JZ,JY,JX)                   !total solute NaSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRF1P(JZ,JY,JX)                   !total solute FeHPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRF2P(JZ,JY,JX)                   !total solute FeH2PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRC0P(JZ,JY,JX)                   !total solute CaPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRC1P(JZ,JY,JX)                   !total solute CaHPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRC2P(JZ,JY,JX)                   !total solute CaH2PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRM1P(JZ,JY,JX)                   !total solute MgHPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRF1B(JZ,JY,JX)                   !total solute FeHPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRF2B(JZ,JY,JX)                   !total solute FeH2PO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRC0B(JZ,JY,JX)                   !total solute CaPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRC1B(JZ,JY,JX)                   !total solute CaHPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRC2B(JZ,JY,JX)                   !total solute CaH2PO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRM1B(JZ,JY,JX)                   !total solute MgHPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRXN4(0:JZ,JY,JX)                 !total adsorbed NH4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRXNB(JZ,JY,JX)                   !total adsorbed NH4 transformation band, [mol d-2 h-1]
  real(r8) :: TRXHY(JZ,JY,JX)                   !total adsorbed H transformation, [mol d-2 h-1]
  real(r8) :: TRXAL(JZ,JY,JX)                   !total adsorbed Al transformation, [mol d-2 h-1]
  real(r8) :: TRXCA(JZ,JY,JX)                   !total adsorbed Ca transformation, [mol d-2 h-1]
  real(r8) :: TRXMG(JZ,JY,JX)                   !total adsorbed Mg transformation, [mol d-2 h-1]
  real(r8) :: TRXNA(JZ,JY,JX)                   !total adsorbed Na transformation, [mol d-2 h-1]
  real(r8) :: TRXKA(JZ,JY,JX)                   !total adsorbed K transformation, [mol d-2 h-1]
  real(r8) :: TRXHC(JZ,JY,JX)                   !total adsorbed COOH transformation, [mol d-2 h-1]
  real(r8) :: TRXAL2(JZ,JY,JX)                  !total adsorbed AlOH2 transformation, [mol d-2 h-1]
  real(r8) :: TRKAS(JZ,JY,JX)                   !total solute KSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRXFE(JZ,JY,JX)                   !total Fe adsorption
  real(r8) :: TRXFE2(JZ,JY,JX)                  !total FeOH2 adsorption

  real(r8) :: TRXH0(0:JZ,JY,JX)                 !total adsorbed OH- transformation non-band, [mol d-2 h-1]
  real(r8) :: TRXH1(0:JZ,JY,JX)                 !total adsorbed OH transformation non-band, [mol d-2 h-1]
  real(r8) :: TRXH2(0:JZ,JY,JX)                 !total adsorbed OH2 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRX1P(0:JZ,JY,JX)                 !total adsorbed HPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRX2P(0:JZ,JY,JX)                 !total adsorbed H2PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRBH0(JZ,JY,JX)                   !total adsorbed OH- transformation band, [mol d-2 h-1]
  real(r8) :: TRBH1(JZ,JY,JX)                   !total adsorbed OH transformation band, [mol d-2 h-1]
  real(r8) :: TRBH2(JZ,JY,JX)                   !total adsorbed OH2 transformation band, [mol d-2 h-1]
  real(r8) :: TRB1P(JZ,JY,JX)                   !total adsorbed HPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRB2P(JZ,JY,JX)                   !total adsorbed H2PO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRCPMB(JZ,JY,JX)                  !total precipitated apatite transformation band, [mol d-2 h-1]
  real(r8) :: TBCO2(JZ,JY,JX)                   !total solute CO2 transformation boundary, [mol d-2 h-1]
  real(r8) :: TBION(0:JZ,JY,JX)                 !total solute ion transformation boundary, [mol d-2 h-1]
  real(r8) :: TRNO2(0:JZ,JY,JX)                 !total solute NO2 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRN2B(JZ,JY,JX)                   !total solute NO2 transformation band, [mol d-2 h-1]
  real(r8) :: TRN3G(0:JZ,JY,JX)                 !total gaseous NH3 transformation, [mol d-2 h-1]

  real(r8) :: TRALOH(JZ,JY,JX)                  !total precipitated AlOH3 transformation, [mol d-2 h-1]
  real(r8) :: TRFEOH(JZ,JY,JX)                  !total precipitated FeOH3 transformation, [mol d-2 h-1]
  real(r8) :: TRCACO(JZ,JY,JX)                  !total precipitated CaCO3 transformation, [mol d-2 h-1]
  real(r8) :: TRCASO(JZ,JY,JX)                  !total precipitated CaSO4 transformation, [mol d-2 h-1]
  real(r8) :: TRALPO(0:JZ,JY,JX)                !total precipitated AlPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRFEPO(0:JZ,JY,JX)                !total precipitated FePO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRCAPD(0:JZ,JY,JX)                !total precipitated CaHPO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRCAPH(0:JZ,JY,JX)                !total precipitated CaH2PO4 transformation non-band, [mol d-2 h-1]
  real(r8) :: TRCAPM(0:JZ,JY,JX)                !total precipitated apatite transformation non-band, [mol d-2 h-1]
  real(r8) :: TRALPB(JZ,JY,JX)                  !total precipitated AlPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRFEPB(JZ,JY,JX)                  !total precipitated FePO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRCPDB(JZ,JY,JX)                  !total precipitated CaHPO4 transformation band, [mol d-2 h-1]
  real(r8) :: TRCPHB(JZ,JY,JX)                  !total precipitated CaH2PO4 transformation band, [mol d-2 h-1]

  real(r8) :: XCOBLS(JS,JY,JX)                  !wet deposition of CO2, [g d-2 h-1]
  real(r8) :: XCHBLS(JS,JY,JX)                  !wet deposition of CH4, [g d-2 h-1]
  real(r8) :: XOXBLS(JS,JY,JX)                  !wet deposition of O2, [g d-2 h-1]
  real(r8) :: XNGBLS(JS,JY,JX)                  !wet deposition of N2, [g d-2 h-1]
  real(r8) :: XN2BLS(JS,JY,JX)                  !wet deposition of N2O, [g d-2 h-1]
  real(r8) :: XN4BLW(JS,JY,JX)                  !wet deposition of NH4, [g d-2 h-1]
  real(r8) :: XN3BLW(JS,JY,JX)                  !wet deposition of NH3, [g d-2 h-1]
  real(r8) :: XNOBLW(JS,JY,JX)                  !wet deposition of NO3, [g d-2 h-1]
  real(r8) :: XH1PBS(JS,JY,JX)                  !wet deposition of HPO4, [g d-2 h-1]
  real(r8) :: XH2PBS(JS,JY,JX)                  !wet deposition of H2PO4, [g d-2 h-1]
  real(r8) :: XALBLS(JS,JY,JX)                  !wet deposition of Al, [g d-2 h-1]
  real(r8) :: XFEBLS(JS,JY,JX)                  !wet deposition of Fe, [g d-2 h-1]
  real(r8) :: XHYBLS(JS,JY,JX)                  !wet deposition of H, [g d-2 h-1]
  real(r8) :: XCABLS(JS,JY,JX)                  !wet deposition of Ca, [g d-2 h-1]
  real(r8) :: XMGBLS(JS,JY,JX)                  !wet deposition of Mg, [g d-2 h-1]
  real(r8) :: XNABLS(JS,JY,JX)                  !wet deposition of Na, [g d-2 h-1]
  real(r8) :: XKABLS(JS,JY,JX)                  !wet deposition of K, [g d-2 h-1]
  real(r8) :: XOHBLS(JS,JY,JX)                  !wet deposition of OH, [g d-2 h-1]
  real(r8) :: XSOBLS(JS,JY,JX)                  !wet deposition of SO4, [g d-2 h-1]
  real(r8) :: XCLBLS(JS,JY,JX)                  !wet deposition of Cl, [g d-2 h-1]
  real(r8) :: XC3BLS(JS,JY,JX)                  !wet deposition of CO3, [g d-2 h-1]
  real(r8) :: XHCBLS(JS,JY,JX)                  !wet deposition of HCO3, [g d-2 h-1]
  real(r8) :: XAL1BS(JS,JY,JX)                  !wet deposition of AlOH, [g d-2 h-1]
  real(r8) :: XAL2BS(JS,JY,JX)                  !wet deposition of AlOH2, [g d-2 h-1]
  real(r8) :: XAL3BS(JS,JY,JX)                  !wet deposition of AlOH3, [g d-2 h-1]
  real(r8) :: XAL4BS(JS,JY,JX)                  !wet deposition of AlOH4, [g d-2 h-1]
  real(r8) :: XALSBS(JS,JY,JX)                  !wet deposition of AlSO4, [g d-2 h-1]
  real(r8) :: XFE1BS(JS,JY,JX)                  !wet deposition of FeOH, [g d-2 h-1]
  real(r8) :: XFE2BS(JS,JY,JX)                  !wet deposition of FeOH2, [g d-2 h-1]
  real(r8) :: XFE3BS(JS,JY,JX)                  !wet deposition of FeOH3, [g d-2 h-1]
  real(r8) :: XFE4BS(JS,JY,JX)                  !wet deposition of FeOH4, [g d-2 h-1]
  real(r8) :: XFESBS(JS,JY,JX)                  !wet deposition of FeSO4, [g d-2 h-1]
  real(r8) :: XCAOBS(JS,JY,JX)                  !wet deposition of CaOH, [g d-2 h-1]
  real(r8) :: XCACBS(JS,JY,JX)                  !wet deposition of CaCO3, [g d-2 h-1]
  real(r8) :: XCAHBS(JS,JY,JX)                  !wet deposition of CaHCO3, [g d-2 h-1]
  real(r8) :: XCASBS(JS,JY,JX)                  !wet deposition of CaSO4, [g d-2 h-1]
  real(r8) :: XMGOBS(JS,JY,JX)                  !wet deposition of MgOH, [g d-2 h-1]
  real(r8) :: XMGCBS(JS,JY,JX)                  !wet deposition of MgCO3, [g d-2 h-1]
  real(r8) :: XHGBLS(JS,JY,JX)                  !wet deposition of H2, [g d-2 h-1]
  real(r8) :: XMGHBS(JS,JY,JX)                  !wet deposition of MgHCO3, [g d-2 h-1]
  real(r8) :: XMGSBS(JS,JY,JX)                  !wet deposition of MgSO4, [g d-2 h-1]
  real(r8) :: XNACBS(JS,JY,JX)                  !wet deposition of NaCO3, [g d-2 h-1]
  real(r8) :: XNASBS(JS,JY,JX)                  !wet deposition of NaSO4, [g d-2 h-1]
  real(r8) :: XKASBS(JS,JY,JX)                  !wet deposition of KSO4, [g d-2 h-1]
  real(r8) :: XH0PBS(JS,JY,JX)                  !wet deposition of PO4, [g d-2 h-1]
  real(r8) :: XH3PBS(JS,JY,JX)                  !wet deposition of H3PO4, [g d-2 h-1]
  real(r8) :: XF1PBS(JS,JY,JX)                  !wet deposition of FeHPO4, [g d-2 h-1]
  real(r8) :: XF2PBS(JS,JY,JX)                  !wet deposition of FeH2PO4, [g d-2 h-1]
  real(r8) :: XC0PBS(JS,JY,JX)                  !wet deposition of CaPO4, [g d-2 h-1]
  real(r8) :: XC1PBS(JS,JY,JX)                  !wet deposition of CHPO4, [g d-2 h-1]
  real(r8) :: XC2PBS(JS,JY,JX)                  !wet deposition of CaH2PO4, [g d-2 h-1]
  real(r8) :: XM1PBS(JS,JY,JX)                  !wet deposition of MgHPO4, [g d-2 h-1]

end module AqueChemDatatype
