
      real(r8) :: ORGC(0:JZ,JY,JX),OMC(3,7,0:5,0:JZ,JY,JX) &
      ,OMN(3,7,0:5,0:JZ,JY,JX),OMP(3,7,0:5,0:JZ,JY,JX) &
      ,ORC(2,0:4,0:JZ,JY,JX),ORN(2,0:4,0:JZ,JY,JX),ORP(2,0:4,0:JZ,JY,JX) &
      ,OQC(0:4,0:JZ,JY,JX),OQN(0:4,0:JZ,JY,JX),OQP(0:4,0:JZ,JY,JX) &
      ,OQA(0:4,0:JZ,JY,JX),OQCH(0:4,0:JZ,JY,JX),OQNH(0:4,0:JZ,JY,JX) &
      ,OQPH(0:4,0:JZ,JY,JX),OQAH(0:4,0:JZ,JY,JX),OHC(0:4,0:JZ,JY,JX) &
      ,OHN(0:4,0:JZ,JY,JX),OHP(0:4,0:JZ,JY,JX),OSC(4,0:4,0:JZ,JY,JX) &
      ,OSN(4,0:4,0:JZ,JY,JX),OSP(4,0:4,0:JZ,JY,JX),OHA(0:4,0:JZ,JY,JX) &
      ,ZNH4FA(0:JZ,JY,JX),ZNH3FA(0:JZ,JY,JX),ZNHUFA(0:JZ,JY,JX) &
      ,ZNO3FA(0:JZ,JY,JX),ZNH4FB(0:JZ,JY,JX),ZNH3FB(0:JZ,JY,JX) &
      ,ZNHUFB(0:JZ,JY,JX),ZNO3FB(0:JZ,JY,JX),ZNO2B(0:JZ,JY,JX) &
      ,ZNH4S(0:JZ,JY,JX),ZNH3S(0:JZ,JY,JX),ZNO3S(0:JZ,JY,JX) &
      ,H2PO4(0:JZ,JY,JX),ZNH4B(0:JZ,JY,JX),ZNH3B(0:JZ,JY,JX) &
      ,ZNO3B(0:JZ,JY,JX),H2POB(0:JZ,JY,JX),ZNO2S(0:JZ,JY,JX) &
      ,ZNH3G(JZ,JY,JX),Z2GG(JZ,JY,JX),Z2GS(0:JZ,JY,JX),Z2OG(JZ,JY,JX) &
      ,Z2OS(0:JZ,JY,JX),ZNH4SH(JZ,JY,JX),ZNH3SH(JZ,JY,JX) &
      ,ZNO3SH(JZ,JY,JX),H2PO4H(JZ,JY,JX),ZNH4BH(JZ,JY,JX) &
      ,ZNH3BH(JZ,JY,JX),ZNO3BH(JZ,JY,JX),H2POBH(JZ,JY,JX) &
      ,ZNO2SH(JZ,JY,JX),Z2GSH(JZ,JY,JX),Z2OSH(JZ,JY,JX) &
      ,ZNO2BH(JZ,JY,JX),RC0(0:5,JY,JX),ORGCX(0:JZ,JY,JX) &
      ,TOQCK(0:JZ,JY,JX),ORGN(0:JZ,JY,JX),ORGR(0:JZ,JY,JX) &
      ,ZNFNI(0:JZ,JY,JX),ZNFN0(0:JZ,JY,JX) &
      ,ZNHUI(0:JZ,JY,JX),ZNHU0(0:JZ,JY,JX),H1PO4(0:JZ,JY,JX) &
      ,H1POB(0:JZ,JY,JX),H1PO4H(JZ,JY,JX),H1POBH(JZ,JY,JX)


      COMMON/BLK13A/ORGC,OMC &
      ,OMN,OMP &
      ,ORC,ORN,ORP &
      ,OQC,OQN,OQP &
      ,OQA,OQCH,OQNH &
      ,OQPH,OQAH,OHC &
      ,OHN,OHP,OSC &
      ,OSN,OSP,OHA &
      ,ZNH4FA,ZNH3FA,ZNHUFA &
      ,ZNO3FA,ZNH4FB,ZNH3FB &
      ,ZNHUFB,ZNO3FB,ZNO2B &
      ,ZNH4S,ZNH3S,ZNO3S &
      ,H2PO4,ZNH4B,ZNH3B &
      ,ZNO3B,H2POB,ZNO2S &
      ,ZNH3G,Z2GG,Z2GS,Z2OG &
      ,Z2OS,ZNH4SH,ZNH3SH &
      ,ZNO3SH,H2PO4H,ZNH4BH &
      ,ZNH3BH,ZNO3BH,H2POBH &
      ,ZNO2SH,Z2GSH,Z2OSH &
      ,ZNO2BH,RC0,ORGCX &
      ,TOQCK,ORGN,ORGR &
      ,ZNFNI,ZNFN0 &
      ,ZNHUI,ZNHU0,H1PO4 &
      ,H1POB,H1PO4H,H1POBH
