
      real(r8) :: RUPNH4(2,JZ,JP,JY,JX),RUPNHB(2,JZ,JP,JY,JX) &
      ,RUPNO3(2,JZ,JP,JY,JX),RUPNOB(2,JZ,JP,JY,JX),RUPH2P(2,JZ,JP,JY,JX) &
      ,RUPH2B(2,JZ,JP,JY,JX),RUONH4(2,JZ,JP,JY,JX),RUONHB(2,JZ,JP,JY,JX) &
      ,RUONO3(2,JZ,JP,JY,JX),RUONOB(2,JZ,JP,JY,JX),RUOH2P(2,JZ,JP,JY,JX) &
      ,RUOH2B(2,JZ,JP,JY,JX),RUCNH4(2,JZ,JP,JY,JX),RUCNHB(2,JZ,JP,JY,JX) &
      ,RUCNO3(2,JZ,JP,JY,JX),RUCNOB(2,JZ,JP,JY,JX),RUCH2P(2,JZ,JP,JY,JX) &
      ,RUCH2B(2,JZ,JP,JY,JX),RUPNF(JZ,JP,JY,JX),RUPHGS(2,JZ,JP,JY,JX) &
      ,RUPH1P(2,JZ,JP,JY,JX),RUOH1P(2,JZ,JP,JY,JX),RUCH1P(2,JZ,JP,JY,JX) &
      ,RUPH1B(2,JZ,JP,JY,JX),RUOH1B(2,JZ,JP,JY,JX),RUCH1B(2,JZ,JP,JY,JX) &
      ,VOLWP(JP,JY,JX),RCO2N(2,JZ,JP,JY,JX),RDFOMC(2,0:4,JZ,JP,JY,JX) &
      ,RDFOMN(2,0:4,JZ,JP,JY,JX),RDFOMP(2,0:4,JZ,JP,JY,JX) &
      ,RUNNHP(2,JZ,JP,JY,JX),RUNNOP(2,JZ,JP,JY,JX),RUPP2P(2,JZ,JP,JY,JX) &
      ,RUNNBP(2,JZ,JP,JY,JX),RUNNXP(2,JZ,JP,JY,JX),RUPP2B(2,JZ,JP,JY,JX) &
      ,RNH3Z(JP,JY,JX),RNH3B(JC,JP,JY,JX),WFR(2,JZ,JP,JY,JX) &
      ,RHGFLA(2,JZ,JP,JY,JX),RHGDFA(2,JZ,JP,JY,JX),H2GA(2,JZ,JP,JY,JX) &
      ,H2GP(2,JZ,JP,JY,JX),RH2GZ(JP,JY,JX),RUPP1P(2,JZ,JP,JY,JX) &
      ,RUPP1B(2,JZ,JP,JY,JX)


      COMMON/BLK12B/RUPNH4,RUPNHB &
      ,RUPNO3,RUPNOB,RUPH2P &
      ,RUPH2B,RUONH4,RUONHB &
      ,RUONO3,RUONOB,RUOH2P &
      ,RUOH2B,RUCNH4,RUCNHB &
      ,RUCNO3,RUCNOB,RUCH2P &
      ,RUCH2B,RUPNF,RUPHGS &
      ,RUPH1P,RUOH1P,RUCH1P &
      ,RUPH1B,RUOH1B,RUCH1B &
      ,VOLWP,RCO2N,RDFOMC &
      ,RDFOMN,RDFOMP &
      ,RUNNHP,RUNNOP,RUPP2P &
      ,RUNNBP,RUNNXP,RUPP2B &
      ,RNH3Z,RNH3B,WFR &
      ,RHGFLA,RHGDFA,H2GA &
      ,H2GP,RH2GZ,RUPP1P &
      ,RUPP1B
