
      real(r8) :: CFOSC(4,0:4,0:JZ,JY,JX),CNOSC(4,0:4,0:JZ,JY,JX) &
      ,CPOSC(4,0:4,0:JZ,JY,JX),XOQCS(0:4,0:JZ,JY,JX) &
      ,XOQNS(0:4,0:JZ,JY,JX),XOQPS(0:4,0:JZ,JY,JX),XOQAS(0:4,0:JZ,JY,JX) &
      ,XNH4S(0:JZ,JY,JX),XNO3S(0:JZ,JY,JX) &
      ,XH2PS(0:JZ,JY,JX),XNH4B(0:JZ,JY,JX),XNO3B(0:JZ,JY,JX) &
      ,XN2GS(0:JZ,JY,JX),XH2BS(0:JZ,JY,JX),VLNH4(0:JZ,JY,JX) &
      ,VLNHB(0:JZ,JY,JX),VLNO3(0:JZ,JY,JX),VLNOB(0:JZ,JY,JX) &
      ,VLPO4(0:JZ,JY,JX),VLPOB(0:JZ,JY,JX),WDNHB(JZ,JY,JX) &
      ,DPNHB(JZ,JY,JX),WDNOB(JZ,JY,JX),DPNOB(JZ,JY,JX),WDPOB(JZ,JY,JX) &
      ,DPPOB(JZ,JY,JX),DPNH4(JY,JX),DPNO3(JY,JX),DPPO4(JY,JX) &
      ,FL(2),H2GG(JZ,JY,JX),RVMXC(0:JZ,JY,JX),RVMBC(0:JZ,JY,JX) &
      ,CH2GG(0:JZ,JY,JX),XCODFR(JY,JX),XCHDFR(JY,JX),XOXDFR(JY,JX) &
      ,XNGDFR(JY,JX),XN2DFR(JY,JX),XN3DFR(JY,JX),XHGDFR(JY,JX) &
      ,XCOBBL(JZ,JY,JX),XCHBBL(JZ,JY,JX),XOXBBL(JZ,JY,JX) &
      ,XNGBBL(JZ,JY,JX),XN2BBL(JZ,JY,JX),XN3BBL(JZ,JY,JX) &
      ,XNBBBL(JZ,JY,JX),XHGBBL(JZ,JY,JX),XH1PS(0:JZ,JY,JX) &
      ,CFOMC(2,JZ,JY,JX),EPOC(0:JZ,JY,JX),EHUM(0:JZ,JY,JX) &
      ,XH1BS(0:JZ,JY,JX),H2GSH(JZ,JY,JX),XZHYS(0:JZ,JY,JX)

      COMMON/BLK13C/CFOSC,CNOSC &
      ,CPOSC,XOQCS &
      ,XOQNS,XOQPS,XOQAS &
      ,XNH4S,XNO3S &
      ,XH2PS,XNH4B,XNO3B &
      ,XN2GS,XH2BS,VLNH4 &
      ,VLNHB,VLNO3,VLNOB &
      ,VLPO4,VLPOB,WDNHB &
      ,DPNHB,WDNOB,DPNOB,WDPOB &
      ,DPPOB,DPNH4,DPNO3,DPPO4 &
      ,FL,H2GG,RVMXC,RVMBC &
      ,CH2GG,XCODFR,XCHDFR,XOXDFR &
      ,XNGDFR,XN2DFR,XN3DFR,XHGDFR &
      ,XCOBBL,XCHBBL,XOXBBL &
      ,XNGBBL,XN2BBL,XN3BBL &
      ,XNBBBL,XHGBBL,XH1PS,CFOMC &
      ,EPOC,EHUM,XH1BS &
      ,H2GSH,XZHYS
