
      real(r8) :: O2I(JP,JY,JX),CO2I(JP,JY,JX),DCO2(JP,JY,JX) &
      ,CO2Q(JP,JY,JX),CO2L(JP,JY,JX),O2L(JP,JY,JX),SCO2(JP,JY,JX) &
      ,SO2(JP,JY,JX),XKCO2L(JP,JY,JX),XKCO2O(JP,JY,JX),TFN3(JP,JY,JX) &
      ,TFN4(JZ,JP,JY,JX),SURFB(4,JZ,JC,JP,JY,JX),TCC(JP,JY,JX) &
      ,TCG(JP,JY,JX),TKC(JP,JY,JX),ARSTK(JZ,JC,JP,JY,JX),TKG(JP,JY,JX) &
      ,DTKC(JP,JY,JX),CFOPC(0:5,4,JP,JY,JX),CHILL(JP,JY,JX) &
      ,DMVL(2,JP,JY,JX),RRAD1X(2,JP,JY,JX),RRAD2X(2,JP,JY,JX) &
      ,RTAR1X(2,JP,JY,JX),RTAR2X(2,JP,JY,JX),FLWC(JP,JY,JX) &
      ,VOLWC(JP,JY,JX),PARDIF(4,4,JZ,JP,JY,JX),PAR(4,4,JZ,JP,JY,JX) &
      ,RADC(JP,JY,JX),RADP(JP,JY,JX),FRADP(JP,JY,JX) &
      ,SURF(4,JZ,25,JC,JP,JY,JX),SURFX(4,JZ,25,JC,JP,JY,JX) &
      ,VCGRO(25,JC,JP,JY,JX),VGRO(25,JC,JP,JY,JX),COMPL(25,JC,JP,JY,JX) &
      ,ETGRO(25,JC,JP,JY,JX),CBXN(25,JC,JP,JY,JX),FMOL(JP,JY,JX) &
      ,CPOOL3(25,JC,JP,JY,JX),CO2B(25,JC,JP,JY,JX) &
      ,VCGR4(25,JC,JP,JY,JX),VGRO4(25,JC,JP,JY,JX),ETGR4(25,JC,JP,JY,JX) &
      ,CBXN4(25,JC,JP,JY,JX),CPOOL4(25,JC,JP,JY,JX),HCOB(25,JC,JP,JY,JX) &
      ,ARLFP(JP,JY,JX),ARSTP(JP,JY,JX),ARLFS(JP,JY,JX),ZC(JP,JY,JX) &
      ,FDBK(JC,JP,JY,JX),FDBK4(25,JC,JP,JY,JX),FDBKX(JC,JP,JY,JX)


      COMMON/BLK1G/O2I,CO2I,DCO2 &
      ,CO2Q,CO2L,O2L,SCO2 &
      ,SO2,XKCO2L,XKCO2O,TFN3 &
      ,TFN4,SURFB,TCC &
      ,TCG,TKC,ARSTK,TKG &
      ,DTKC,CFOPC,CHILL &
      ,DMVL,RRAD1X,RRAD2X &
      ,RTAR1X,RTAR2X,FLWC &
      ,VOLWC,PARDIF,PAR &
      ,RADC,RADP,FRADP &
      ,SURF,SURFX &
      ,VCGRO,VGRO,COMPL &
      ,ETGRO,CBXN,FMOL &
      ,CPOOL3,CO2B &
      ,VCGR4,VGRO4,ETGR4 &
      ,CBXN4,CPOOL4,HCOB &
      ,ARLFP,ARSTP,ARLFS,ZC &
      ,FDBK,FDBK4,FDBKX
