
      real(r8) :: RCZLX(JC,JP,JY,JX),RCPLX(JC,JP,JY,JX) &
      ,RCCLX(JC,JP,JY,JX),WGLFX(JC,JP,JY,JX) &
      ,WGLFNX(JC,JP,JY,JX),WGLFPX(JC,JP,JY,JX),ARLFZ(JC,JP,JY,JX) &
      ,RCZSX(JC,JP,JY,JX),RCPSX(JC,JP,JY,JX),RCCSX(JC,JP,JY,JX) &
      ,WGSHEX(JC,JP,JY,JX),WGSHNX(JC,JP,JY,JX) &
      ,WGSHPX(JC,JP,JY,JX),HTSHEX(JC,JP,JY,JX) &
      ,WTSTXB(JC,JP,JY,JX),WTSTXN(JC,JP,JY,JX),WTSTXP(JC,JP,JY,JX)


      COMMON/BLK1S/RCZLX,RCPLX &
      ,RCCLX,WGLFX &
      ,WGLFNX,WGLFPX,ARLFZ &
      ,RCZSX,RCPSX,RCCSX &
      ,WGSHEX,WGSHNX &
      ,WGSHPX,HTSHEX &
      ,WTSTXB,WTSTXN,WTSTXP
