
      real(r8) :: ZMGOH(JZ,JY,JX),ZMGCH(JZ,JY,JX),ZMGHH(JZ,JY,JX) &
      ,ZMGSH(JZ,JY,JX),ZNACH(JZ,JY,JX),ZNASH(JZ,JY,JX),ZKASH(JZ,JY,JX) &
      ,H0PO4H(JZ,JY,JX),H3PO4H(JZ,JY,JX) &
      ,ZFE1PH(JZ,JY,JX),ZFE2PH(JZ,JY,JX),ZCA0PH(JZ,JY,JX) &
      ,ZCA1PH(JZ,JY,JX),ZCA2PH(JZ,JY,JX),ZMG1PH(JZ,JY,JX) &
      ,H0POBH(JZ,JY,JX),H3POBH(JZ,JY,JX) &
      ,ZFE1BH(JZ,JY,JX),ZFE2BH(JZ,JY,JX),ZCA0BH(JZ,JY,JX) &
      ,ZCA1BH(JZ,JY,JX),ZCA2BH(JZ,JY,JX),ZMG1BH(JZ,JY,JX)


      COMMON/BLK19C/ZMGOH,ZMGCH,ZMGHH &
      ,ZMGSH,ZNACH,ZNASH,ZKASH &
      ,H0PO4H,H3PO4H &
      ,ZFE1PH,ZFE2PH,ZCA0PH &
      ,ZCA1PH,ZCA2PH,ZMG1PH &
      ,H0POBH,H3POBH &
      ,ZFE1BH,ZFE2BH,ZCA0BH &
      ,ZCA1BH,ZCA2BH,ZMG1BH
