
      real(r8) :: PARR(JY,JX),PARG(60,JY,JX),FLWM(60,3,JD,JV,JH) &
      ,FLWHM(60,3,JD,JV,JH),QRMN(60,2,2,JV,JH),QSM(60,2,JV,JH) &
      ,VOLWM(60,0:JZ,JY,JX),VOLWHM(60,JZ,JY,JX),VOLPM(60,0:JZ,JY,JX) &
      ,FILM(60,0:JZ,JY,JX),ENGYPM(60,JY,JX),XVOLTM(60,JY,JX) &
      ,XVOLWM(60,JY,JX),XVOLIM(60,JY,JX),ROXSK(60,0:JZ,JY,JX) &
      ,FLWRM(60,JY,JX),FLPM(60,JZ,JY,JX),FINHM(60,JZ,JY,JX) &
      ,THETPM(60,0:JZ,JY,JX),TORT(60,0:JZ,JY,JX),TORTH(60,JZ,JY,JX) &
      ,FLQRM(60,JY,JX),FLQSM(60,JY,JX),FLQHM(60,JY,JX) &
      ,FLQWM(60,JS,JY,JX),VHCPWM(60,JS,JY,JX),DFGS(60,0:JZ,JY,JX) &
      ,QRM(60,JV,JH),QRV(60,JY,JX)
      integer :: IFLBM(60,2,2,JY,JX)


      COMMON/BLK10/PARR,PARG,FLWM &
      ,FLWHM,QRMN,QSM &
      ,VOLWM,VOLWHM,VOLPM &
      ,FILM,ENGYPM,XVOLTM &
      ,XVOLWM,XVOLIM,ROXSK &
      ,FLWRM,FLPM,FINHM &
      ,THETPM,TORT,TORTH &
      ,FLQRM,FLQSM,FLQHM &
      ,FLQWM,VHCPWM,DFGS &
      ,QRM,QRV,IFLBM
