
      real(r8) :: XNO2S(0:JZ,JY,JX),CNH4S(0:JZ,JY,JX) &
      ,CNH3S(0:JZ,JY,JX),CNO3S(0:JZ,JY,JX),CPO4S(JZ,JY,JX) &
      ,CNH4B(0:JZ,JY,JX),CNH3B(0:JZ,JY,JX),CNO3B(0:JZ,JY,JX) &
      ,CPO4B(0:JZ,JY,JX),CNO2S(0:JZ,JY,JX),CNH3G(0:JZ,JY,JX) &
      ,CZ2GG(0:JZ,JY,JX),CZ2GS(0:JZ,JY,JX),CZ2OG(0:JZ,JY,JX) &
      ,CZ2OS(0:JZ,JY,JX),OXYG(JZ,JY,JX),OXYS(0:JZ,JY,JX) &
      ,OXYSH(JZ,JY,JX),CO2G(JZ,JY,JX),CO2S(0:JZ,JY,JX) &
      ,CO2SH(JZ,JY,JX),CH4G(JZ,JY,JX),CH4S(0:JZ,JY,JX) &
      ,CH4SH(JZ,JY,JX),COXYG(0:JZ,JY,JX),CCH4G(0:JZ,JY,JX) &
      ,COXYS(0:JZ,JY,JX),CCO2G(0:JZ,JY,JX),CCO2S(0:JZ,JY,JX) &
      ,CCH4S(0:JZ,JY,JX),RUPOXO(0:JZ,JY,JX),RCO2O(0:JZ,JY,JX) &
      ,RCH4O(0:JZ,JY,JX),RH2GO(0:JZ,JY,JX),RN2G(0:JZ,JY,JX) &
      ,RN2O(0:JZ,JY,JX),CH2P4(0:JZ,JY,JX),CH2P4B(0:JZ,JY,JX) &
      ,XCODFG(0:JZ,JY,JX),XCHDFG(0:JZ,JY,JX),XOXDFG(0:JZ,JY,JX) &
      ,XNGDFG(0:JZ,JY,JX),XN2DFG(0:JZ,JY,JX),XN3DFG(0:JZ,JY,JX) &
      ,XNBDFG(0:JZ,JY,JX),XHGDFG(0:JZ,JY,JX),XCODFS(JY,JX) &
      ,XCHDFS(JY,JX),XOXDFS(JY,JX),XNGDFS(JY,JX),XN2DFS(JY,JX) &
      ,XN3DFS(JY,JX),XNBDFS(JY,JX),XHGDFS(JY,JX),RCO2F(0:JZ,JY,JX) &
      ,H2GS(0:JZ,JY,JX),CH2GS(0:JZ,JY,JX) &
      ,RCH4L(0:JZ,JY,JX),ROXYF(0:JZ,JY,JX),ROXYL(0:JZ,JY,JX) &
      ,RCH4F(0:JZ,JY,JX),CH1P4(0:JZ,JY,JX),CH1P4B(0:JZ,JY,JX) &
      ,CNO2B(0:JZ,JY,JX),XNO2B(0:JZ,JY,JX) &
      ,OSA(4,0:4,0:JZ,JY,JX) 



      COMMON/BLK13B/XNO2S,CNH4S &
      ,CNH3S,CNO3S,CPO4S &
      ,CNH4B,CNH3B,CNO3B &
      ,CPO4B,CNO2S,CNH3G &
      ,CZ2GG,CZ2GS,CZ2OG &
      ,CZ2OS,OXYG,OXYS &
      ,OXYSH,CO2G,CO2S &
      ,CO2SH,CH4G,CH4S &
      ,CH4SH,COXYG,CCH4G &
      ,COXYS,CCO2G,CCO2S &
      ,CCH4S,RUPOXO,RCO2O &
      ,RCH4O,RH2GO,RN2G &
      ,RN2O,CH2P4,CH2P4B &
      ,XCODFG,XCHDFG,XOXDFG &
      ,XNGDFG,XN2DFG,XN3DFG &
      ,XNBDFG ,XHGDFG,XCODFS &
      ,XCHDFS,XOXDFS,XNGDFS,XN2DFS &
      ,XN3DFS,XNBDFS,XHGDFS,RCO2F &
      ,H2GS,CH2GS &
      ,RCH4L,ROXYF,ROXYL &
      ,RCH4F,CH1P4,CH1P4B &
      ,CNO2B,XNO2B &
      ,OSA
