
      real(r8) :: ZAL(0:JZ,JY,JX),ZFE(0:JZ,JY,JX),ZHY(0:JZ,JY,JX) &
      ,ZCA(0:JZ,JY,JX),ZMG(0:JZ,JY,JX),ZNA(0:JZ,JY,JX),ZKA(0:JZ,JY,JX) &
      ,ZOH(0:JZ,JY,JX),ZSO4(0:JZ,JY,JX),ZCL(0:JZ,JY,JX),ZCO3(0:JZ,JY,JX) &
      ,ZHCO3(0:JZ,JY,JX),ZALOH1(0:JZ,JY,JX),ZALOH2(0:JZ,JY,JX) &
      ,ZALOH3(0:JZ,JY,JX),ZALOH4(0:JZ,JY,JX),ZALS(0:JZ,JY,JX) &
      ,ZFEOH1(0:JZ,JY,JX),ZFEOH2(0:JZ,JY,JX),ZFEOH3(0:JZ,JY,JX) &
      ,ZFEOH4(0:JZ,JY,JX),ZFES(0:JZ,JY,JX),ZCAO(0:JZ,JY,JX) &
      ,ZCAC(0:JZ,JY,JX),ZCAH(0:JZ,JY,JX),ZCAS(0:JZ,JY,JX) &
      ,ZMGO(0:JZ,JY,JX),ZMGC(0:JZ,JY,JX),ZMGH(0:JZ,JY,JX) &
      ,ZMGS(0:JZ,JY,JX),ZNAC(0:JZ,JY,JX) &
      ,ZNAS(0:JZ,JY,JX),ZKAS(0:JZ,JY,JX),H0PO4(0:JZ,JY,JX) &
      ,H3PO4(0:JZ,JY,JX),ZFE1P(0:JZ,JY,JX) &
      ,ZFE2P(0:JZ,JY,JX),ZCA0P(0:JZ,JY,JX),ZCA1P(0:JZ,JY,JX) &
      ,ZCA2P(0:JZ,JY,JX),ZMG1P(0:JZ,JY,JX),H0POB(JZ,JY,JX) &
      ,H3POB(JZ,JY,JX),ZFE1PB(JZ,JY,JX),ZFE2PB(JZ,JY,JX) &
      ,ZCA0PB(JZ,JY,JX),ZCA1PB(JZ,JY,JX),ZCA2PB(JZ,JY,JX) &
      ,ZMG1PB(JZ,JY,JX),XN4(0:JZ,JY,JX),XNB(0:JZ,JY,JX) &
      ,XHY(JZ,JY,JX),XAL(JZ,JY,JX),XCA(JZ,JY,JX),XMG(JZ,JY,JX) &
      ,XNA(JZ,JY,JX),XKA(JZ,JY,JX),XHC(JZ,JY,JX),XALO2(JZ,JY,JX) &
      ,XOH0(0:JZ,JY,JX),XOH1(0:JZ,JY,JX),XOH2(0:JZ,JY,JX) &
      ,XH1P(0:JZ,JY,JX),XH2P(0:JZ,JY,JX),XOH0B(0:JZ,JY,JX) &
      ,XFE(JZ,JY,JX),XFEO2(JZ,JY,JX)


      COMMON/BLK19A/ZAL,ZFE,ZHY &
      ,ZCA,ZMG,ZNA,ZKA &
      ,ZOH,ZSO4,ZCL,ZCO3 &
      ,ZHCO3,ZALOH1,ZALOH2 &
      ,ZALOH3,ZALOH4,ZALS &
      ,ZFEOH1,ZFEOH2,ZFEOH3 &
      ,ZFEOH4,ZFES,ZCAO &
      ,ZCAC,ZCAH,ZCAS &
      ,ZMGO,ZMGC,ZMGH &
      ,ZMGS,ZNAC &
      ,ZNAS,ZKAS,H0PO4 &
      ,H3PO4,ZFE1P &
      ,ZFE2P,ZCA0P,ZCA1P &
      ,ZCA2P,ZMG1P,H0POB &
      ,H3POB,ZFE1PB,ZFE2PB &
      ,ZCA0PB,ZCA1PB,ZCA2PB &
      ,ZMG1PB,XN4,XNB &
      ,XHY,XAL,XCA,XMG &
      ,XNA,XKA,XHC,XALO2 &
      ,XOH0,XOH1,XOH2 &
      ,XH1P,XH2P,XOH0B &
      ,XFE,XFEO2
