
      real(r8) :: ZLSGL(0:JZ,JY,JX),ZHSGL(JZ,JY,JX),ZNSGL(0:JZ,JY,JX) &
      ,ZOSGL(0:JZ,JY,JX),POSGL(0:JZ,JY,JX),OCSGL(0:JZ,JY,JX) &
      ,ONSGL(0:JZ,JY,JX),OPSGL(0:JZ,JY,JX),OASGL(0:JZ,JY,JX) &
      ,Z2SGL(JZ,JY,JX),ZVSGL(0:JZ,JY,JX) &
      ,WGSGL(JZ,JY,JX),WGSGW(JS,JY,JX),WGSGR(JY,JX),WGSGA(JY,JX) &
      ,SCO2L(0:JZ,JY,JX),SOXYL(0:JZ,JY,JX),SCH4L(0:JZ,JY,JX) &
      ,SN2OL(0:JZ,JY,JX),SN2GL(0:JZ,JY,JX),SNH3L(0:JZ,JY,JX) &
      ,SH2GL(0:JZ,JY,JX),PSISE(0:JZ,JY,JX),PSISA(0:JZ,JY,JX) &
      ,PSISO(0:JZ,JY,JX),PSISH(0:JZ,JY,JX),THETX,THETPI,DENSI,DENSJ &
      ,THETY(0:JZ,JY,JX),THETS(0:JZ,JY,JX),VOLQ(0:JZ,JY,JX) &
      ,TFNQ(0:JZ,JY,JX),HGSGL(JZ,JY,JX),HLSGL(0:JZ,JY,JX) &
      ,THAWR(JY,JX),HTHAWR(JY,JX),FLSW(JS,JY,JX),FLSWH(JS,JY,JX) &
      ,HFLSW(JS,JY,JX),FLSWR(JS,JY,JX),HFLSWR(JS,JY,JX)


      COMMON/BLK11B/ZLSGL,ZHSGL,ZNSGL &
      ,ZOSGL,POSGL,OCSGL &
      ,ONSGL,OPSGL,OASGL &
      ,Z2SGL,ZVSGL &
      ,WGSGL,WGSGW,WGSGR,WGSGA &
      ,SCO2L,SOXYL,SCH4L &
      ,SN2OL,SN2GL,SNH3L &
      ,SH2GL,PSISE,PSISA &
      ,PSISO,PSISH,THETX,THETPI,DENSI,DENSJ &
      ,THETY,THETS,VOLQ &
      ,TFNQ,HGSGL,HLSGL &
      ,THAWR,HTHAWR,FLSW,FLSWH &
      ,HFLSW,FLSWR,HFLSWR
