
      real(r8) :: XNO2S(0:JZ,JY,JX),RUPOXO(0:JZ,JY,JX),RCO2O(0:JZ,JY,JX) &
      ,RCH4O(0:JZ,JY,JX),RH2GO(0:JZ,JY,JX),RN2G(0:JZ,JY,JX) &
      ,RN2O(0:JZ,JY,JX) &
      ,XCODFG(0:JZ,JY,JX),XCHDFG(0:JZ,JY,JX),XOXDFG(0:JZ,JY,JX) &
      ,XNGDFG(0:JZ,JY,JX),XN2DFG(0:JZ,JY,JX),XN3DFG(0:JZ,JY,JX) &
      ,XNBDFG(0:JZ,JY,JX),XHGDFG(0:JZ,JY,JX),XCODFS(JY,JX) &
      ,XCHDFS(JY,JX),XOXDFS(JY,JX),XNGDFS(JY,JX),XN2DFS(JY,JX) &
      ,XN3DFS(JY,JX),XNBDFS(JY,JX),XHGDFS(JY,JX),RCO2F(0:JZ,JY,JX) &
      ,RCH4L(0:JZ,JY,JX),ROXYF(0:JZ,JY,JX),ROXYL(0:JZ,JY,JX) &
      ,RCH4F(0:JZ,JY,JX),XNO2B(0:JZ,JY,JX)



      COMMON/BLK13B/XNO2S &
      ,RUPOXO,RCO2O &
      ,RCH4O,RH2GO,RN2G,RN2O&
      ,XCODFG,XCHDFG,XOXDFG &
      ,XNGDFG,XN2DFG,XN3DFG &
      ,XNBDFG ,XHGDFG,XCODFS &
      ,XCHDFS,XOXDFS,XNGDFS,XN2DFS &
      ,XN3DFS,XNBDFS,XHGDFS,RCO2F &
      ,RCH4L,ROXYF,ROXYL &
      ,RCH4F,XNO2B
