
      real(r8) :: XQRAL(2,2,JV,JH),XQRFE(2,2,JV,JH),XQRHY(2,2,JV,JH) &
      ,XQRCA(2,2,JV,JH),XQRMG(2,2,JV,JH),XQRNA(2,2,JV,JH) &
      ,XQRKA(2,2,JV,JH),XQROH(2,2,JV,JH),XQRSO(2,2,JV,JH) &
      ,XQRCL(2,2,JV,JH),XQRC3(2,2,JV,JH),XQRHC(2,2,JV,JH) &
      ,XQRAL1(2,2,JV,JH),XQRAL2(2,2,JV,JH),XQRAL3(2,2,JV,JH) &
      ,XQRAL4(2,2,JV,JH),XQRALS(2,2,JV,JH),XQRFE1(2,2,JV,JH) &
      ,XQRFE2(2,2,JV,JH),XQRFE3(2,2,JV,JH),XQRFE4(2,2,JV,JH) &
      ,XQRFES(2,2,JV,JH),XQRCAO(2,2,JV,JH),XQRCAC(2,2,JV,JH) &
      ,XQRCAH(2,2,JV,JH),XQRCAS(2,2,JV,JH),XQRMGO(2,2,JV,JH) &
      ,XQRMGC(2,2,JV,JH),XQRMGH(2,2,JV,JH),XQRMGS(2,2,JV,JH) &
      ,XQRNAC(2,2,JV,JH),XQRNAS(2,2,JV,JH),XQRKAS(2,2,JV,JH) &
      ,XQRH0P(2,2,JV,JH),XQRH3P(2,2,JV,JH),XQRF1P(2,2,JV,JH) &
      ,XQRF2P(2,2,JV,JH),XQRC0P(2,2,JV,JH),XQRC1P(2,2,JV,JH) &
      ,XQRC2P(2,2,JV,JH),XQRM1P(2,2,JV,JH) &
      ,XQSAL(2,JV,JH),XQSFE(2,JV,JH),XQSHY(2,JV,JH) &
      ,XQSCA(2,JV,JH),XQSMG(2,JV,JH),XQSNA(2,JV,JH),XQSKA(2,JV,JH) &
      ,XQSOH(2,JV,JH),XQSSO(2,JV,JH),XQSCL(2,JV,JH),XQSC3(2,JV,JH) &
      ,XQSHC(2,JV,JH),XQSAL1(2,JV,JH),XQSAL2(2,JV,JH),XQSAL3(2,JV,JH) &
      ,XQSAL4(2,JV,JH),XQSALS(2,JV,JH),XQSFE1(2,JV,JH),XQSFE2(2,JV,JH) &
      ,XQSFE3(2,JV,JH),XQSFE4(2,JV,JH),XQSFES(2,JV,JH),XQSCAO(2,JV,JH) &
      ,XQSCAC(2,JV,JH),XQSCAH(2,JV,JH),XQSCAS(2,JV,JH),XQSMGO(2,JV,JH) &
      ,XQSMGC(2,JV,JH),XQSMGH(2,JV,JH),XQSMGS(2,JV,JH),XQSNAC(2,JV,JH) &
      ,XQSNAS(2,JV,JH),XQSKAS(2,JV,JH),XQSH0P(2,JV,JH),XQSH1P(2,JV,JH) &
      ,XQSH3P(2,JV,JH),XQSF1P(2,JV,JH),XQSF2P(2,JV,JH),XQSC0P(2,JV,JH) &
      ,XQSC1P(2,JV,JH),XQSC2P(2,JV,JH),XQSM1P(2,JV,JH)


      COMMON/BLK20A/XQRAL,XQRFE,XQRHY &
      ,XQRCA,XQRMG,XQRNA &
      ,XQRKA,XQROH,XQRSO &
      ,XQRCL,XQRC3,XQRHC &
      ,XQRAL1,XQRAL2,XQRAL3 &
      ,XQRAL4,XQRALS,XQRFE1 &
      ,XQRFE2,XQRFE3,XQRFE4 &
      ,XQRFES,XQRCAO,XQRCAC &
      ,XQRCAH,XQRCAS,XQRMGO &
      ,XQRMGC,XQRMGH,XQRMGS &
      ,XQRNAC,XQRNAS,XQRKAS &
      ,XQRH0P,XQRH3P,XQRF1P &
      ,XQRF2P,XQRC0P,XQRC1P &
      ,XQRC2P,XQRM1P &
      ,XQSAL,XQSFE,XQSHY &
      ,XQSCA,XQSMG,XQSNA,XQSKA &
      ,XQSOH,XQSSO,XQSCL,XQSC3 &
      ,XQSHC,XQSAL1,XQSAL2,XQSAL3 &
      ,XQSAL4,XQSALS,XQSFE1,XQSFE2 &
      ,XQSFE3,XQSFE4,XQSFES,XQSCAO &
      ,XQSCAC,XQSCAH,XQSCAS,XQSMGO &
      ,XQSMGC,XQSMGH,XQSMGS,XQSNAC &
      ,XQSNAS,XQSKAS,XQSH0P,XQSH1P &
      ,XQSH3P,XQSF1P,XQSF2P,XQSC0P &
      ,XQSC1P,XQSC2P,XQSM1P
