
      real(r8) :: XSANER(2,2,JV,JH),XSILER(2,2,JV,JH) &
      ,XCLAER(2,2,JV,JH) &
      ,XCECER(2,2,JV,JH),XAECER(2,2,JV,JH),XNH4ER(2,2,JV,JH) &
      ,XNH3ER(2,2,JV,JH),XNHUER(2,2,JV,JH),XNO3ER(2,2,JV,JH) &
      ,XNH4EB(2,2,JV,JH),XNH3EB(2,2,JV,JH),XNHUEB(2,2,JV,JH) &
      ,XNO3EB(2,2,JV,JH),XN4ER(2,2,JV,JH),XNBER(2,2,JV,JH) &
      ,XHYER(2,2,JV,JH),XALER(2,2,JV,JH),XCAER(2,2,JV,JH) &
      ,XMGER(2,2,JV,JH),XNAER(2,2,JV,JH),XKAER(2,2,JV,JH) &
      ,XHCER(2,2,JV,JH),XAL2ER(2,2,JV,JH),XOH0ER(2,2,JV,JH) &
      ,XOH1ER(2,2,JV,JH),XOH2ER(2,2,JV,JH),XH1PER(2,2,JV,JH) &
      ,XH2PER(2,2,JV,JH),XOH0EB(2,2,JV,JH),XOH1EB(2,2,JV,JH) &
      ,XOH2EB(2,2,JV,JH),XH1PEB(2,2,JV,JH),XH2PEB(2,2,JV,JH) &
      ,PALOER(2,2,JV,JH),PFEOER(2,2,JV,JH),PCACER(2,2,JV,JH) &
      ,PCASER(2,2,JV,JH),PALPER(2,2,JV,JH),PFEPER(2,2,JV,JH) &
      ,PCPDER(2,2,JV,JH),PCPHER(2,2,JV,JH),PCPMER(2,2,JV,JH) &
      ,PALPEB(2,2,JV,JH),PFEPEB(2,2,JV,JH),PCPDEB(2,2,JV,JH) &
      ,PCPHEB(2,2,JV,JH),PCPMEB(2,2,JV,JH),XFE2ER(2,2,JV,JH) &
      ,XSEDER(2,2,JV,JH),XFEER(2,2,JV,JH) &
      ,OMCER(3,7,0:5,2,2,JV,JH),OMNER(3,7,0:5,2,2,JV,JH) &
      ,ORCER(2,0:4,2,2,JV,JH),ORNER(2,0:4,2,2,JV,JH) &
      ,ORPER(2,0:4,2,2,JV,JH),OHCER(0:4,2,2,JV,JH) &
      ,OHNER(0:4,2,2,JV,JH),OHPER(0:4,2,2,JV,JH) &
      ,OHAER(0:4,2,2,JV,JH),OSCER(4,0:4,2,2,JV,JH) &
      ,OSAER(4,0:4,2,2,JV,JH),OSNER(4,0:4,2,2,JV,JH) &
      ,OSPER(4,0:4,2,2,JV,JH),OMPER(3,7,0:5,2,2,JV,JH)


      COMMON/BLK20F/XSANER,XSILER &
      ,XCLAER &
      ,XCECER,XAECER,XNH4ER &
      ,XNH3ER,XNHUER,XNO3ER &
      ,XNH4EB,XNH3EB,XNHUEB &
      ,XNO3EB,XN4ER,XNBER &
      ,XHYER,XALER,XCAER &
      ,XMGER,XNAER,XKAER &
      ,XHCER,XAL2ER,XOH0ER &
      ,XOH1ER,XOH2ER,XH1PER &
      ,XH2PER,XOH0EB,XOH1EB &
      ,XOH2EB,XH1PEB,XH2PEB &
      ,PALOER,PFEOER,PCACER &
      ,PCASER,PALPER,PFEPER &
      ,PCPDER,PCPHER,PCPMER &
      ,PALPEB,PFEPEB,PCPDEB &
      ,PCPHEB,PCPMEB,XFE2ER &
      ,XSEDER,XFEER &
      ,OMCER,OMNER &
      ,ORCER,ORNER &
      ,ORPER,OHCER &
      ,OHNER,OHPER &
      ,OHAER,OSCER &
      ,OSAER,OSNER &
      ,OSPER,OMPER
