
      real(r8) :: XH0PXS(JZ,JY,JX) &
      ,XH3PXS(JZ,JY,JX),XF1PXS(JZ,JY,JX),XF2PXS(JZ,JY,JX) &
      ,XC0PXS(JZ,JY,JX),XC1PXS(JZ,JY,JX),XC2PXS(JZ,JY,JX) &
      ,XM1PXS(JZ,JY,JX),XH0BXB(JZ,JY,JX) &
      ,XH3BXB(JZ,JY,JX),XF1BXB(JZ,JY,JX),XF2BXB(JZ,JY,JX) &
      ,XC0BXB(JZ,JY,JX),XC1BXB(JZ,JY,JX),XC2BXB(JZ,JY,JX) &
      ,XM1BXB(JZ,JY,JX),XNXFXB(JZ,JY,JX)


      COMMON/BLK20E/XH0PXS &
      ,XH3PXS,XF1PXS,XF2PXS &
      ,XC0PXS,XC1PXS,XC2PXS &
      ,XM1PXS,XH0BXB &
      ,XH3BXB,XF1BXB,XF2BXB &
      ,XC0BXB,XC1BXB,XC2BXB &
      ,XM1BXB,XNXFXB
