
      real(r8) :: XMGHBS(JS,JY,JX),XMGSBS(JS,JY,JX) &
      ,XNACBS(JS,JY,JX),XNASBS(JS,JY,JX),XKASBS(JS,JY,JX) &
      ,XH0PBS(JS,JY,JX),XH3PBS(JS,JY,JX),XF1PBS(JS,JY,JX) &
      ,XF2PBS(JS,JY,JX),XC0PBS(JS,JY,JX),XC1PBS(JS,JY,JX) &
      ,XC2PBS(JS,JY,JX),XM1PBS(JS,JY,JX)


      COMMON/BLK22C/XMGHBS,XMGSBS &
      ,XNACBS,XNASBS,XKASBS &
      ,XH0PBS,XH3PBS,XF1PBS &
      ,XF2PBS,XC0PBS,XC1PBS &
      ,XC2PBS,XM1PBS
