
      real(r8) :: XALFLS(3,0:JD,JV,JH),XFEFLS(3,0:JD,JV,JH) &
      ,XHYFLS(3,0:JD,JV,JH),XCAFLS(3,0:JD,JV,JH),XMGFLS(3,0:JD,JV,JH) &
      ,XNAFLS(3,0:JD,JV,JH),XKAFLS(3,0:JD,JV,JH),XOHFLS(3,0:JD,JV,JH) &
      ,XSOFLS(3,0:JD,JV,JH),XCLFLS(3,0:JD,JV,JH),XC3FLS(3,0:JD,JV,JH) &
      ,XHCFLS(3,0:JD,JV,JH),XAL1FS(3,0:JD,JV,JH),XAL2FS(3,0:JD,JV,JH) &
      ,XAL3FS(3,0:JD,JV,JH),XAL4FS(3,0:JD,JV,JH),XALSFS(3,0:JD,JV,JH) &
      ,XFE1FS(3,0:JD,JV,JH),XFE2FS(3,0:JD,JV,JH) &
      ,XFE3FS(3,0:JD,JV,JH),XFE4FS(3,0:JD,JV,JH),XFESFS(3,0:JD,JV,JH) &
      ,XCAOFS(3,0:JD,JV,JH),XCACFS(3,0:JD,JV,JH),XCAHFS(3,0:JD,JV,JH) &
      ,XCASFS(3,0:JD,JV,JH),XMGOFS(3,0:JD,JV,JH),XMGCFS(3,0:JD,JV,JH) &
      ,XMGHFS(3,0:JD,JV,JH),XMGSFS(3,0:JD,JV,JH),XNACFS(3,0:JD,JV,JH) &
      ,XNASFS(3,0:JD,JV,JH),XKASFS(3,0:JD,JV,JH),XH0PFS(3,0:JD,JV,JH) &
      ,XH3PFS(3,0:JD,JV,JH),XF1PFS(3,0:JD,JV,JH) &
      ,XF2PFS(3,0:JD,JV,JH),XC0PFS(3,0:JD,JV,JH),XC1PFS(3,0:JD,JV,JH) &
      ,XC2PFS(3,0:JD,JV,JH),XM1PFS(3,0:JD,JV,JH),XH0BFB(3,0:JD,JV,JH) &
      ,XH3BFB(3,0:JD,JV,JH),XF1BFB(3,0:JD,JV,JH) &
      ,XF2BFB(3,0:JD,JV,JH),XC0BFB(3,0:JD,JV,JH),XC1BFB(3,0:JD,JV,JH) &
      ,XC2BFB(3,0:JD,JV,JH),XM1BFB(3,0:JD,JV,JH)


      COMMON/BLK20B/XALFLS,XFEFLS &
      ,XHYFLS,XCAFLS,XMGFLS &
      ,XNAFLS,XKAFLS,XOHFLS &
      ,XSOFLS,XCLFLS,XC3FLS &
      ,XHCFLS,XAL1FS,XAL2FS &
      ,XAL3FS,XAL4FS,XALSFS &
      ,XFE1FS,XFE2FS &
      ,XFE3FS,XFE4FS,XFESFS &
      ,XCAOFS,XCACFS,XCAHFS &
      ,XCASFS,XMGOFS,XMGCFS &
      ,XMGHFS,XMGSFS,XNACFS &
      ,XNASFS,XKASFS,XH0PFS &
      ,XH3PFS,XF1PFS &
      ,XF2PFS,XC0PFS,XC1PFS &
      ,XC2PFS,XM1PFS,XH0BFB &
      ,XH3BFB,XF1BFB &
      ,XF2BFB,XC0BFB,XC1BFB &
      ,XC2BFB,XM1BFB
