
      real(r8) :: TRN4S(0:JZ,JY,JX),TRN3S(0:JZ,JY,JX),TRN4B(JZ,JY,JX) &
      ,TRNO3(0:JZ,JY,JX),TRN3B(JZ,JY,JX),TRNOB(JZ,JY,JX),TRAL(JZ,JY,JX) &
      ,TRFE(JZ,JY,JX),TRHY(JZ,JY,JX),TRCA(JZ,JY,JX),TRMG(JZ,JY,JX) &
      ,TRNA(JZ,JY,JX),TRKA(JZ,JY,JX),TROH(JZ,JY,JX),TRSO4(JZ,JY,JX) &
      ,TRCO3(JZ,JY,JX),TRHCO(JZ,JY,JX),TRCO2(JZ,JY,JX),TRH2O(0:JZ,JY,JX) &
      ,TRAL1(JZ,JY,JX),TRAL2(JZ,JY,JX),TRAL3(JZ,JY,JX),TRAL4(JZ,JY,JX) &
      ,TRALS(JZ,JY,JX),TRFE1(JZ,JY,JX),TRFE2(JZ,JY,JX),TRFE3(JZ,JY,JX) &
      ,TRFE4(JZ,JY,JX),TRFES(JZ,JY,JX),TRCAO(JZ,JY,JX),TRCAC(JZ,JY,JX) &
      ,TRCAH(JZ,JY,JX),TRCAS(JZ,JY,JX),TRMGO(JZ,JY,JX),TRMGC(JZ,JY,JX) &
      ,TRMGH(JZ,JY,JX),TRMGS(JZ,JY,JX),TRNAC(JZ,JY,JX),TRNAS(JZ,JY,JX) &
      ,TRH0P(JZ,JY,JX),TRH1P(0:JZ,JY,JX),TRH2P(0:JZ,JY,JX) &
      ,TRH3P(JZ,JY,JX),TRF1P(JZ,JY,JX),TRF2P(JZ,JY,JX),TRC0P(JZ,JY,JX) &
      ,TRC1P(JZ,JY,JX),TRC2P(JZ,JY,JX),TRM1P(JZ,JY,JX),TRH0B(JZ,JY,JX) &
      ,TRH1B(JZ,JY,JX),TRH2B(JZ,JY,JX),TRH3B(JZ,JY,JX),TRF1B(JZ,JY,JX) &
      ,TRF2B(JZ,JY,JX),TRC0B(JZ,JY,JX),TRC1B(JZ,JY,JX),TRC2B(JZ,JY,JX) &
      ,TRM1B(JZ,JY,JX),TRXN4(0:JZ,JY,JX),TRXNB(JZ,JY,JX),TRXHY(JZ,JY,JX) &
      ,TRXAL(JZ,JY,JX),TRXCA(JZ,JY,JX),TRXMG(JZ,JY,JX),TRXNA(JZ,JY,JX) &
      ,TRXKA(JZ,JY,JX),TRXHC(JZ,JY,JX),TRXAL2(JZ,JY,JX),TRKAS(JZ,JY,JX) &
      ,TRXFE(JZ,JY,JX),TRXFE2(JZ,JY,JX)


      COMMON/BLK21A/TRN4S,TRN3S,TRN4B &
      ,TRNO3,TRN3B,TRNOB,TRAL &
      ,TRFE,TRHY,TRCA,TRMG &
      ,TRNA,TRKA,TROH,TRSO4 &
      ,TRCO3,TRHCO,TRCO2,TRH2O &
      ,TRAL1,TRAL2,TRAL3,TRAL4 &
      ,TRALS,TRFE1,TRFE2,TRFE3 &
      ,TRFE4,TRFES,TRCAO,TRCAC &
      ,TRCAH,TRCAS,TRMGO,TRMGC &
      ,TRMGH,TRMGS,TRNAC,TRNAS &
      ,TRH0P,TRH1P,TRH2P &
      ,TRH3P,TRF1P,TRF2P,TRC0P &
      ,TRC1P,TRC2P,TRM1P,TRH0B &
      ,TRH1B,TRH2B,TRH3B,TRF1B &
      ,TRF2B,TRC0B,TRC1B,TRC2B &
      ,TRM1B,TRXN4,TRXNB,TRXHY &
      ,TRXAL,TRXCA,TRXMG,TRXNA &
      ,TRXKA,TRXHC,TRXAL2,TRKAS &
      ,TRXFE,TRXFE2
