
      real(r8) :: BETA(4,4),BETX(4,4) &
      ,TAU0(JC+1,JY,JX),TAUS(JC+1,JY,JX),FRADG(JY,JX),RADG(JY,JX) &
      ,THRMCX(JY,JX),THRMGX(JY,JX),ARLFX(JY,JX),ARSTX(JY,JX) &
      ,CNETX(JY,JX),ZT(JY,JX),ZL(0:JC,JY,JX)


      COMMON/BLK5/BETA,BETX &
      ,TAU0,TAUS,FRADG,RADG &
      ,THRMCX,THRMGX,ARLFX,ARSTX &
      ,CNETX,ZT,ZL
