
      real(r8) :: FORGC,FVLWB &
      ,FCH4F,POROQ,TFND(0:JZ,JY,JX),FCI,WPI &
      ,DISP(3,JD,JV,JH),OXKM,PSIHY

      COMMON/BLK8B/FORGC,FVLWB &
      ,FCH4F,POROQ,TFND,FCI,WPI &
      ,DISP,OXKM,PSIHY
