
      real(r8) :: CNH4(JZ,JY,JX),CNO3(JZ,JY,JX),CPO4(JZ,JY,JX),CAL(JZ,JY,JX) &
      ,CFE(JZ,JY,JX),CCA(JZ,JY,JX),CMG(JZ,JY,JX),CNA(JZ,JY,JX) &
      ,CKA(JZ,JY,JX),CSO4(JZ,JY,JX),CCL(JZ,JY,JX),CALOH(JZ,JY,JX) &
      ,CFEOH(JZ,JY,JX),CCACO(JZ,JY,JX),CCASO(JZ,JY,JX),CALPO(JZ,JY,JX) &
      ,CFEPO(JZ,JY,JX),CCAPD(JZ,JY,JX),CCAPH(JZ,JY,JX),SED(JY,JX) &
      ,GKC4(JZ,JY,JX),GKCH(JZ,JY,JX),GKCA(JZ,JY,JX),GKCM(JZ,JY,JX) &
      ,GKCN(JZ,JY,JX),GKCK(JZ,JY,JX)&
      ,DETS(JY,JX),DETE(JY,JX),CER(JY,JX),XER(JY,JX) &
      ,PTDSNU(JY,JX),VLS(JY,JX)



      COMMON/BLK8A/CNH4,CNO3,CPO4,CAL &
      ,CFE,CCA,CMG,CNA &
      ,CKA,CSO4,CCL,CALOH &
      ,CFEOH,CCACO,CCASO,CALPO &
      ,CFEPO,CCAPD,CCAPH,SED &
      ,GKC4,GKCH,GKCA,GKCM &
      ,GKCN,GKCK&
      ,DETS,DETE,CER,XER &
      ,PTDSNU,VLS
