
      real(r8) :: ALBX(JY,JX),DPTH(JZ,JY,JX),DLYR(3,0:JZ,JY,JX) &
      ,POROS(0:JZ,JY,JX),PSL(0:JZ,JY,JX),FCL(0:JZ,JY,JX) &
      ,WPL(0:JZ,JY,JX),PSD(0:JZ,JY,JX),FCD(0:JZ,JY,JX),VOLX(0:JZ,JY,JX) &
      ,VOLY(0:JZ,JY,JX),BKVL(0:JZ,JY,JX),SRP(0:JZ,JY,JX),FORGC,FVLWB &
      ,FCH4F,CNRH(0:4),CPRH(0:4),DIST(3,JD,JV,JH),XDPTH(3,JZ,JY,JX) &
      ,POROQ,TFND(0:JZ,JY,JX),FCI,WPI,POROS0(JY,JX),FSLOPE(2,JY,JX) &
      ,PSIMS(JY,JX),PSIMX(JY,JX),PSIMN(JY,JX),PSISD(JY,JX),PSIMD(JY,JX) &
      ,SAND(JZ,JY,JX),SILT(JZ,JY,JX),CLAY(JZ,JY,JX),CDPTHZ(0:JZ,JY,JX) &
      ,DPTHZ(JZ,JY,JX),AREA(3,0:JZ,JY,JX),DISP(3,JD,JV,JH),OXKM,PSIHY &
      ,DLYRI(3,0:JZ,JY,JX),OMCI(3,0:4),OMCF(7),OMCA(7),BKVLNM(JY,JX) &
      ,BKVLNU(JY,JX),VOLAI(0:JZ,JY,JX)
      integer :: IUTYP(JY,JX),IXTYP(2,JY,JX),IYTYP(0:2,366,JY,JX)


      COMMON/BLK8B/ALBX,DPTH,DLYR &
      ,POROS,PSL,FCL &
      ,WPL,PSD,FCD,VOLX &
      ,VOLY,BKVL,SRP,FORGC,FVLWB &
      ,FCH4F,CNRH,CPRH,DIST,XDPTH &
      ,POROQ,TFND,FCI,WPI,POROS0,FSLOPE &
      ,PSIMS,PSIMX,PSIMN,PSISD,PSIMD &
      ,SAND,SILT,CLAY,CDPTHZ &
      ,DPTHZ,AREA,DISP,OXKM,PSIHY &
      ,DLYRI,OMCI,OMCF,OMCA,BKVLNM &
      ,BKVLNU,VOLAI,IUTYP,IXTYP &
      ,IYTYP
