
      real(r8) :: DRAD(12),DTMPX(12),DTMPN(12),DHUM(12),DPREC(12) &
      ,DIRRI(12),DWIND(12),DCO2E(12),DCN4R(12),DCNOR(12),TDIRI(JY,JX,12) &
      ,TDTPX(JY,JX,12),TDTPN(JY,JX,12),TDRAD(JY,JX,12),TDHUM(JY,JX,12) &
      ,TDPRC(JY,JX,12),TDWND(JY,JX,12),TDCO2(JY,JX,12),TDCN4(JY,JX,12) &
      ,TDCNO(JY,JX,12),TAREA,XCORP(JY,JX),ZERO,ZERO2,ZEROS(JY,JX) &
      ,ZEROP(JP,JY,JX),ZEROQ(JP,JY,JX),ZEROL(JP,JY,JX),XNPX,XNPA,XNPB &
      ,XNPC,XNPH,XNPT,XNPG,XNPR,XNPD,XNPS,XNPY,XNPZ,XNPQ,XNPV &
      ,DOY,DYLM(JY,JX),ZEROS2(JY,JX)

      integer :: IGO,IDAYR,IYRC,IYRR,NYR,ITERM,IFIN,NCN(JY,JX),NPX,NPY,NPH,NPT,NPG &
      ,NPR,NPS,JOUT,IOUT,KOUT,IOLD,ILAST,IRUN,IBEGIN,ISTART,IEND &
      ,LYRX,LYRC,LSG(JZ,JY,JX),NP(JY,JX) &
      ,NP0(JY,JX),LYRG

      logical :: lverb,do_rgres


      COMMON/BLKC/DRAD,DTMPX,DTMPN,DHUM,DPREC &
      ,DIRRI,DWIND,DCO2E,DCN4R,DCNOR,TDIRI &
      ,TDTPX,TDTPN,TDRAD,TDHUM &
      ,TDPRC,TDWND,TDCO2,TDCN4 &
      ,TDCNO,TAREA,XCORP,ZERO,ZERO2,ZEROS &
      ,ZEROP,ZEROQ,ZEROL,XNPX,XNPA,XNPB &
      ,XNPC,XNPH,XNPT,XNPG,XNPR,XNPD,XNPS,XNPY,XNPZ,XNPQ,XNPV &
      ,DOY,DYLM,ZEROS2 &
      ,IGO,IDAYR,IYRC,IYRR,NYR,ITERM,IFIN,NCN,NPX,NPY,NPH,NPT,NPG &
      ,NPR,NPS,JOUT,IOUT,KOUT,IOLD,ILAST,IRUN,IBEGIN,ISTART,IEND &
      ,LYRX,LYRC,LSG,NP &
      ,NP0,LYRG &
      ,lverb,do_rgres
