module CanopyDataType

  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridConsts
  implicit none
  public
  save
  character(len=*), private, parameter :: mod_filename = __FILE__

  real(r8) :: ALBP(JP,JY,JX)                    !canopy PAR albedo , [-]
  real(r8) :: TAUP(JP,JY,JX)                    !canopy PAR transmissivity , [-]
  real(r8) :: ABSR(JP,JY,JX)                    !canopy shortwave absorptivity , [-]
  real(r8) :: ABSP(JP,JY,JX)                    !canopy PAR absorptivity , [-]

! canopy auxillary variables
! stomata
  real(r8) :: RSMX(JP,JY,JX)                    !maximum stomatal resistance to vapor, [s m-1]
  real(r8) :: RCMX(JP,JY,JX)                    !maximum stomatal resistance to CO2, [s h-1]
  real(r8) :: RSMH(JP,JY,JX)                    !maximum stomatal resistance to vapor, [s h-1]
  real(r8) :: RCS(JP,JY,JX)                     !shape parameter for calculating stomatal resistance from turgor pressure, [-]
  real(r8) :: RC(JP,JY,JX)                      !canopy stomatal resistance, [h m-1]
  real(r8) :: RSMN(JP,JY,JX)                    !canopy minimum stomatal resistance, [s m-1]
  real(r8) :: RAC(JY,JX)                        !canopy boundary layer resistance, [m h-1]

! photosynthesis characteristics
  real(r8) :: O2I(JP,JY,JX)                     !leaf gaseous O2 concentration, [umol m-3]
  real(r8) :: CO2I(JP,JY,JX)                    !leaf gaseous CO2 concentration, [umol m-3]
  real(r8) :: FMOL(JP,JY,JX)                    !total gas concentration, [mol m-3]
  real(r8) :: DCO2(JP,JY,JX)                    !gaesous CO2 concentration difference across stomates, [umol m-3]
  real(r8) :: CO2Q(JP,JY,JX)                    !canopy gaesous CO2 concentration , [umol mol-1]
  real(r8) :: CO2L(JP,JY,JX)                    !leaf aqueous CO2 concentration, [uM]
  real(r8) :: O2L(JP,JY,JX)                     !leaf aqueous O2 concentration, [uM]
  real(r8) :: SCO2(JP,JY,JX)                    !leaf CO2 solubility, [uM /umol mol-1]
  real(r8) :: SO2(JP,JY,JX)                     !leaf O2 solubility, [uM /umol mol-1]

  real(r8) :: XKCO2L(JP,JY,JX)                  !leaf aqueous CO2 Km no O2, [uM]
  real(r8) :: XKCO2O(JP,JY,JX)                  !leaf aqueous CO2 Km ambient O2, [uM]
  real(r8) :: CHILL(JP,JY,JX)                   !chilling effect on CO2 fixation, [-]
  real(r8) :: VCGRO(JNODS,JC,JP,JY,JX)             !maximum dark carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: VGRO(JNODS,JC,JP,JY,JX)              !carboxylation rate, [umol m-2 s-1]
  real(r8) :: COMPL(JNODS,JC,JP,JY,JX)             !CO2 compensation point, [uM]
  real(r8) :: ETGRO(JNODS,JC,JP,JY,JX)             !maximum light carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: CBXN(JNODS,JC,JP,JY,JX)              !carboxylation efficiency, [umol umol-1]
  real(r8) :: CO2B(JNODS,JC,JP,JY,JX)              !bundle sheath nonstructural C3 content in C4 photosynthesis, [g d-2]
  real(r8) :: VCGR4(JNODS,JC,JP,JY,JX)             !maximum dark C4 carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: VGRO4(JNODS,JC,JP,JY,JX)             !C4 carboxylation rate, [umol m-2 s-1]
  real(r8) :: ETGR4(JNODS,JC,JP,JY,JX)             !maximum  light C4 carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: CBXN4(JNODS,JC,JP,JY,JX)             !C4 carboxylation efficiency, [umol umol-1]
  real(r8) :: CPOOL4(JNODS,JC,JP,JY,JX)            !leaf nonstructural C4 content in C4 photosynthesis, [g d-2]
  real(r8) :: HCOB(JNODS,JC,JP,JY,JX)              !bundle sheath nonstructural C3 content in C4 photosynthesis, [g d-2]
  real(r8) :: FDBK(JC,JP,JY,JX)                 !branch down-regulation of CO2 fixation, [-]
  real(r8) :: FDBK4(JNODS,JC,JP,JY,JX)             !down-regulation of C4 photosynthesis, [-]
  real(r8) :: FDBKX(JC,JP,JY,JX)                !down-regulation of C4 photosynthesis, [-]
  real(r8) :: CNETX(JY,JX)                      !total net canopy CO2 exchange, [g d-2 h-1]
  real(r8) :: VCMX(JP,JY,JX)                    !rubisco carboxylase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: VOMX(JP,JY,JX)                    !rubisco oxygenase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: VCMX4(JP,JY,JX)                   !PEP carboxylase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: XKCO2(JP,JY,JX)                   !Km for rubisco carboxylase activity, [uM]
  real(r8) :: XKO2(JP,JY,JX)                    !Km for rubisco oxygenase activity, [uM]
  real(r8) :: XKCO24(JP,JY,JX)                  !Km for PEP carboxylase activity, [uM]
  real(r8) :: RUBP(JP,JY,JX)                    !leaf rubisco content, [g g-1]
  real(r8) :: PEPC(JP,JY,JX)                    !leaf PEP carboxylase content, [g g-1]
  real(r8) :: ETMX(JP,JY,JX)                    !cholorophyll activity , [umol g-1 h-1 at 25 oC]
  real(r8) :: CHL(JP,JY,JX)                     !leaf C3 chlorophyll content, [g g-1]
  real(r8) :: CHL4(JP,JY,JX)                    !leaf C4 chlorophyll content, [g g-1]
  real(r8) :: FCO2(JP,JY,JX)                    !Ci:Ca ratio, [-]


!canopy physical property, water + energy
  real(r8) :: RAD1(JP,JY,JX)                    !canopy net radiation , [MJ d-2 h-1]
  real(r8) :: THRM1(JP,JY,JX)                   !canopy longwave radiation , [MJ d-2 h-1]
  real(r8) :: RADC(JP,JY,JX)                    !canopy absorbed shortwave radiation , [MJ d-2 h-1]
  real(r8) :: RADP(JP,JY,JX)                    !canopy absorbed PAR , [umol m-2 s-1]
  real(r8) :: FRADP(JP,JY,JX)                   !fraction of incoming PAR absorbed by canopy, [-]
  real(r8) :: TAU0(JC+1,JY,JX)                  !fraction of radiation transmitted by canopy layer, [-]
  real(r8) :: TAUS(JC+1,JY,JX)                  !fraction of radiation intercepted by canopy layer, [-]
  real(r8) :: FRADG(JY,JX)                      !fraction of radiation intercepted by ground surface, [-]
  real(r8) :: RADG(JY,JX)                       !radiation intercepted by ground surface, [MJ m-2 h-1]
  real(r8) :: THRMCX(JY,JX)                     !longwave radiation emitted by canopy, [MJ m-2 h-1]
  real(r8) :: THRMGX(JY,JX)                     !longwave radiation emitted by ground surface, [MJ m-2 h-1]
  real(r8) :: TVOLWC(JY,JX)                     !canopy surface water content, [m3 d-2]
  real(r8) :: TFLWCI(JY,JX)                     !net ice transfer to canopy, [MJ d-2 t-1]
  real(r8) :: TFLWC(JY,JX)                      !net water transfer to canopy, [MJ d-2 t-1]
  real(r8) :: EFLXC(JP,JY,JX)                   !canopy latent heat flux, [MJ d-2 h-1]
  real(r8) :: SFLXC(JP,JY,JX)                   !canopy sensible heat flux, [MJ d-2 h-1]
  real(r8) :: HFLXC(JP,JY,JX)                   !canopy storage heat flux, [MJ d-2 h-1]
  real(r8) :: ENGYX(JP,JY,JX)                   !canopy heat storage from previous time step, [MJ d-2]
  real(r8) :: VHCPC(JP,JY,JX)                   !canopy heat capacity, [MJ d-2 K-1]
  real(r8) :: PSILT(JP,JY,JX)                   !canopy total water potential , [Mpa]
  real(r8) :: PSILG(JP,JY,JX)                   !canopy turgor water potential, [Mpa]
  real(r8) :: PSILO(JP,JY,JX)                   !canopy osmotic water potential, [Mpa]
  real(r8) :: RA(JP,JY,JX)                      !canopy boundary layer resistance, [h m-1]
  real(r8) :: EP(JP,JY,JX)                      !canopy transpiration, [m2 d-2 h-1]
  real(r8) :: EVAPC(JP,JY,JX)                   !canopy evaporation, [m2 d-2 h-1]
  real(r8) :: VOLWP(JP,JY,JX)                   !canopy water content, [m3 d-2]
  real(r8) :: TEVAPP(JY,JX)                     !total canopy evaporation + transpiration, [m3 d-2]
  real(r8) :: TEVAPC(JY,JX)                     !total canopy evaporation, [m3 d-2]
  real(r8) :: TENGYC(JY,JX)                     !total canopy heat content, [MJ  d-2]
  real(r8) :: THFLXC(JY,JX)                     !total canopy heat flux, [MJ  d-2]
  real(r8) :: TVOLWP(JY,JX)                     !total canopy water content, [m3 d-2]
  real(r8) :: THRMC(JY,JX)                      !total canopy LW emission, [MJ d-2 h-1]
  real(r8) :: ALBR(JP,JY,JX)                    !canopy shortwave albedo , [-]
  real(r8) :: TAUR(JP,JY,JX)                    !canopy shortwave transmissivity , [-]
  real(r8) :: FLWC(JP,JY,JX)                    !water flux into canopy, [m3 d-2 h-1]
  real(r8) :: VOLWC(JP,JY,JX)                   !canopy surface water content, [m3 d-2]
  real(r8) :: TKC(JP,JY,JX)                     !canopy temperature, [K]
  real(r8) :: TCC(JP,JY,JX)                     !canopy temperature, [oC]
  real(r8) :: DTKC(JP,JY,JX)                    !change in canopy temperature, [K]
  real(r8) :: TKCZ(JP,JY,JX)                    !canopy temperature, [K]
!bgc rates
  real(r8) :: CPOOL3(JNODS,JC,JP,JY,JX)            !minimum sink strength for nonstructural C transfer, [g d-2]

  real(r8) :: RSETC(JP,JY,JX)                   !effect of canopy C status on seed set , []
  real(r8) :: RSETN(JP,JY,JX)                   !effect of canopy N status on seed set , []
  real(r8) :: RSETP(JP,JY,JX)                   !effect of canopy P status on seed set , []
  real(r8) :: WGLFT(JC,JY,JX)                   !total leaf mass, [g d-2]

!Carbon
  real(r8) :: CFOPC(0:5,4,JP,JY,JX)             !litter kinetic fraction, [-]
  real(r8) :: CFOPN(0:5,4,JP,JY,JX)             !litterfall kinetic N fraction, [-]
  real(r8) :: CFOPP(0:5,4,JP,JY,JX)             !litter P kinetic fraction, [-]

  real(r8) :: WTSHT(JP,JY,JX)                   !canopy shoot C, [g d-2]
  real(r8) :: WTLF(JP,JY,JX)                    !canopy leaf C, [g d-2]
  real(r8) :: WTSHE(JP,JY,JX)                   !canopy sheath C , [g d-2]
  real(r8) :: WTSTK(JP,JY,JX)                   !canopy stalk C, [g d-2]
  real(r8) :: WVSTK(JP,JY,JX)                   !canopy active stalk C, [g d-2]
  real(r8) :: WTRSV(JP,JY,JX)                   !canopy reserve C, [g d-2]
  real(r8) :: WTHSK(JP,JY,JX)                   !canopy husk C, [g d-2]
  real(r8) :: WTEAR(JP,JY,JX)                   !canopy ear C, [g d-2]
  real(r8) :: WTGR(JP,JY,JX)                    !canopy grain C, [g d-2]
  real(r8) :: WTLS(JP,JY,JX)                    !canopy leaf + sheath C, [g d-2]
  real(r8) :: ARLFV(JC,JP,JY,JX)                !canopy layer leaf area, [m2 d-2]
  real(r8) :: CNET(JP,JY,JX)                    !canopy net CO2 exchange, [g d-2 h-1]
  real(r8) :: WGLFV(JC,JP,JY,JX)                !canopy layer leaf C, [g d-2]
  real(r8) :: CPOOLP(JP,JY,JX)                  !canopy nonstructural C, [g d-2]
  real(r8) :: CCPOLP(JP,JY,JX)                  !canopy nonstructural C concentration, [g d-2]
  real(r8) :: ARSTV(JC,JP,JY,JX)                !canopy layer stem area, [m2 d-2]
  real(r8) :: CPOLNP(JP,JY,JX)                  !canopy nodule nonstructural C, [g d-2]
  real(r8) :: WTSHN(JP,JY,JX)                   !canopy  N, [g d-2]
  real(r8) :: ZPOOLP(JP,JY,JX)                  !canopy  nonstructural N, [g d-2]
  real(r8) :: WTLFN(JP,JY,JX)                   !canopy leaf N, [g d-2]
  real(r8) :: WTSHEN(JP,JY,JX)                  !canopy sheath N, [g d-2]
  real(r8) :: WTSTKN(JP,JY,JX)                  !canopy stalk N, [g d-2]
  real(r8) :: WTRSVN(JP,JY,JX)                  !canopy reserve N, [g d-2]
  real(r8) :: WTHSKN(JP,JY,JX)                  !canopy husk N, [g d-2]
  real(r8) :: WTEARN(JP,JY,JX)                  !canopy ear N, [g d-2]
  real(r8) :: WTGRNN(JP,JY,JX)                  !canopy grain N, [g d-2]
  real(r8) :: CZPOLP(JP,JY,JX)                  !canopy nonstructural N concentration, [g g-1]
  real(r8) :: ZPOLNP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]
  real(r8) :: CPPOLP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]
  real(r8) :: WTNDN(JP,JY,JX)                   !total canopy nodule N, [g d-2]
  real(r8) :: WTSHP(JP,JY,JX)                   !canopy total P, [g d-2]
  real(r8) :: PPOOLP(JP,JY,JX)                  !canopy nonstructural P, [g d-2]
  real(r8) :: WTLFP(JP,JY,JX)                   !canopy leaf P, [g d-2]
  real(r8) :: WTSHEP(JP,JY,JX)                  !canopy sheath P, [g d-2]
  real(r8) :: WTSTKP(JP,JY,JX)                  !canopy stalk P, [g d-2]
  real(r8) :: WTRSVP(JP,JY,JX)                  !canopy reserve P, [g d-2]
  real(r8) :: WTHSKP(JP,JY,JX)                  !canopy husk P, [g d-2]
  real(r8) :: WTEARP(JP,JY,JX)                  !canopy ear P, [g d-2]
  real(r8) :: WTGRNP(JP,JY,JX)                  !canopy grain P, [g d-2]
  real(r8) :: PPOLNP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]

  real(r8) :: WVSTKB(JC,JP,JY,JX)               !branch active stalk C, [g d-2]
  real(r8) :: CPOOL(JC,JP,JY,JX)                !branch nonstructural C, [g d-2]
  real(r8) :: WTLSB(JC,JP,JY,JX)                !branch leaf + sheath C, [g d-2]
  real(r8) :: WTSHTB(JC,JP,JY,JX)               !branch shoot C, [g d-2]
  real(r8) :: WTLFB(JC,JP,JY,JX)                !branch leaf C, [g d-2]
  real(r8) :: WTSHEB(JC,JP,JY,JX)               !branch sheath C , [g d-2]
  real(r8) :: WTSTKB(JC,JP,JY,JX)               !branch stalk C, [g d-2]
  real(r8) :: WTRSVB(JC,JP,JY,JX)               !branch reserve C, [g d-2]
  real(r8) :: WTHSKB(JC,JP,JY,JX)               !branch husk C, [g d-2]
  real(r8) :: WTEARB(JC,JP,JY,JX)               !branch ear C, [g d-2]
  real(r8) :: WTGRB(JC,JP,JY,JX)                !branch grain C, [g d-2]
  real(r8) :: CCPOLB(JC,JP,JY,JX)               !branch nonstructural C concentration, [g d-2]
  real(r8) :: CPOLNB(JC,JP,JY,JX)               !branch nodule nonstructural C, [g d-2]
  real(r8) :: WTNDB(JC,JP,JY,JX)                !branch nodule C, [g d-2]
  real(r8) :: WGSHEX(JC,JP,JY,JX)               !branch sheath structural C, [g d-2]
  real(r8) :: WTSTXB(JC,JP,JY,JX)               !branch stalk structural C, [g d-2]
  real(r8) :: WGLFX(JC,JP,JY,JX)                !branch leaf structural C, [g d-2]
  real(r8) :: WGLFPX(JC,JP,JY,JX)               !branch leaf structural P, [g d-2]
  real(r8) :: WGSHPX(JC,JP,JY,JX)               !branch sheath structural P, [g d-2]
  real(r8) :: WTSTXP(JC,JP,JY,JX)               !branch stalk structural P, [g d-2]
  real(r8) :: WTSHTN(JC,JP,JY,JX)               !branch N, [g d-2]
  real(r8) :: WTLFBN(JC,JP,JY,JX)               !branch leaf N, [g d-2]
  real(r8) :: WTSHBN(JC,JP,JY,JX)               !branch sheath N, [g d-2]
  real(r8) :: WTSTBN(JC,JP,JY,JX)               !branch stalk N, [g d-2]
  real(r8) :: WTRSBN(JC,JP,JY,JX)               !branch reserve N, [g d-2]
  real(r8) :: WTHSBN(JC,JP,JY,JX)               !branch husk N, [g d-2]
  real(r8) :: WTEABN(JC,JP,JY,JX)               !branch ear N, [g d-2]
  real(r8) :: WTGRBN(JC,JP,JY,JX)               !branch grain N, [g d-2]
  real(r8) :: ZPOOL(JC,JP,JY,JX)                !branch  nonstructural N, [g d-2]
  real(r8) :: CZPOLB(JC,JP,JY,JX)               !branch nonstructural N concentration, [g g-1]
  real(r8) :: ZPOLNB(JC,JP,JY,JX)               !branch nonstructural N concentration, [g g-1]
  real(r8) :: PPOLNB(JC,JP,JY,JX)               !branch nonstructural P concentration, [g g-1]
  real(r8) :: WTNDBN(JC,JP,JY,JX)               !branch nodule N, [g d-2]
  real(r8) :: WGSHNX(JC,JP,JY,JX)               !branch sheath structural N, [g d-2]
  real(r8) :: WTSTXN(JC,JP,JY,JX)               !branch stalk structural N, [g d-2]
  real(r8) :: WGLFNX(JC,JP,JY,JX)               !branch leaf structural N, [g d-2]
  real(r8) :: WTSHTP(JC,JP,JY,JX)               !branch total P, [g d-2]
  real(r8) :: WTLFBP(JC,JP,JY,JX)               !branch leaf P, [g d-2]
  real(r8) :: WTSHBP(JC,JP,JY,JX)               !branch sheath P, [g d-2]
  real(r8) :: WTSTBP(JC,JP,JY,JX)               !branch stalk P, [g d-2]
  real(r8) :: WTRSBP(JC,JP,JY,JX)               !branch reserve P, [g d-2]
  real(r8) :: WTHSBP(JC,JP,JY,JX)               !branch husk P, [g d-2]
  real(r8) :: WTEABP(JC,JP,JY,JX)               !branch ear P, [g d-2]
  real(r8) :: WTGRBP(JC,JP,JY,JX)               !branch grain P, [g d-2]
  real(r8) :: PPOOL(JC,JP,JY,JX)                !branch nonstructural P, [g d-2]
  real(r8) :: CPPOLB(JC,JP,JY,JX)               !branch nonstructural P concentration, [g g-1]
  real(r8) :: WTNDBP(JC,JP,JY,JX)               !branch nodule P, [g d-2]

  real(r8) :: WGLF(0:JNODS,JC,JP,JY,JX)            !leaf C, [g d-2]
  real(r8) :: WGSHE(0:JNODS,JC,JP,JY,JX)           !sheath C , [g d-2]
  real(r8) :: WGNODE(0:JNODS,JC,JP,JY,JX)          !internode C, [g d-2]
  real(r8) :: WGLFL(JC,0:JNODS,JC,JP,JY,JX)        !layer leaf C, [g d-2]
  real(r8) :: ARLFL(JC,0:JNODS,JC,JP,JY,JX)        !layer leaf area, [m2 d-2]
  real(r8) :: WGLFLN(JC,0:JNODS,JC,JP,JY,JX)       !layer leaf N, [g d-2]
  real(r8) :: WSLF(0:JNODS,JC,JP,JY,JX)            !layer leaf protein C, [g d-2]
  real(r8) :: WSSHE(0:JNODS,JC,JP,JY,JX)           !layer sheath protein C, [g d-2]
  real(r8) :: WGLFN(0:JNODS,JC,JP,JY,JX)           !leaf N, [g d-2]
  real(r8) :: WGSHN(0:JNODS,JC,JP,JY,JX)           !sheath N, [g d-2]
  real(r8) :: WGNODN(0:JNODS,JC,JP,JY,JX)          !internode N, [g d-2]

  real(r8) :: CCPLNP(JP,JY,JX)                  !nodule nonstructural C, [g d-2]
  real(r8) :: GRWTB(JC,JP,JY,JX)                !maximum grain C during grain fill, [g d-2]
  real(r8) :: WTSTDG(4,JP,JY,JX)                !standing dead C fraction, [g d-2]
  real(r8) :: WTSTG(JP,JY,JX)                   !standing dead C, [g d-2]

!Nitrogen


  real(r8) :: WTSTDN(4,JP,JY,JX)                !standing dead N fraction, [g d-2]
  real(r8) :: WTSTGN(JP,JY,JX)                  !standing dead N , [g d-2]


!Phosphorus


  real(r8) :: WGLFP(0:JNODS,JC,JP,JY,JX)           !leaf P, [g d-2]
  real(r8) :: WGSHP(0:JNODS,JC,JP,JY,JX)           !sheath P, [g d-2]
  real(r8) :: WGNODP(0:JNODS,JC,JP,JY,JX)          !nodule P, [g d-2]
  real(r8) :: WGLFLP(JC,0:JNODS,JC,JP,JY,JX)       !leaf layer P, [g d-2]
  real(r8) :: WTSTDP(4,JP,JY,JX)                !standing dead P fraction, [g d-2]
  real(r8) :: WTSTGP(JP,JY,JX)                  !standing dead P , [g d-2]
  real(r8) :: WTNDP(JP,JY,JX)                   !total nodule P, [g d-2]


!storage
  real(r8) :: WTRVC(JP,JY,JX)                   !plant stored nonstructural C, [g d-2]
  real(r8) :: WTRVX(JP,JY,JX)                   !plant stored nonstructural C at planting, [g d-2]
  real(r8) :: WTRVN(JP,JY,JX)                   !plant stored nonstructural N, [g d-2]
  real(r8) :: WTRVP(JP,JY,JX)                   !plant stored nonstructural P, [g d-2]
  REAL(R8) :: WTSHTA(JP,JY,JX)                  !landscape average canopy shoot C, [g d-2]

end module CanopyDataType
