module ClimForcDataType
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridDataType
implicit none
    real(r8) :: DECLIN
    real(r8) :: RMAX       !maximum hourly radiation,	[MJ m-2 h-1]
    real(r8) :: TAVG1      !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: TAVG2      !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: TAVG3      !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: AMP1       !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: AMP2       !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: AMP3       !parameter to calculate hourly  air temperature from daily value	[oC]
    real(r8) :: VAVG1      !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: VAVG2      !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: VAVG3      !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: VMP1       !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: VMP2       !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: VMP3       !parameter to calculate hourly  vapor pressure from daily value	[kPa]
    real(r8) :: SAZI                              !solar azimuth of solar angle
    real(r8) :: SCOS                              !cosine of solar angle
    real(r8) :: DOY                               !day of year

  real(r8) :: TMPX(366)                         !maximum daily air temperature, [oC]
  real(r8) :: TMPN(366)                         !minimum daily air temperature, [oC]
  real(r8) :: SRAD(366)                         !daily solar radiation, [MJ m-2 d-1]
  real(r8) :: RAIN(366)                         !daily precipitation, [mm d-1 ]
  real(r8) :: WIND(366)                         !daily wind travel, [m d-1]
  real(r8) :: DWPT(2,366)                       !daily dewpoint temperature, [oC]
  real(r8) :: TMPH(24,366)                      !hourly air temperature, [oC]
  real(r8) :: SRADH(24,366)                     !hourly solar radiation, [MJ m-2 h-1]
  real(r8) :: RAINH(24,366)                     !hourly precipitation, [mm h-1]
  real(r8) :: WINDH(24,366)                     !hourly wind speed, [m h-1]
  real(r8) :: DWPTH(24,366)                     !hourly dewpoint temperature, [oC]
  real(r8) :: TCA(JY,JX)                        !air temperature, [oC]
  real(r8) :: TKA(JY,JX)                        !air temperature, [K]
  real(r8) :: UA(JY,JX)                         !wind speed, [m h-1]
  real(r8) :: VPA(JY,JX)                        !vapor concentration, [m3 m-3]
  real(r8) :: VPK(JY,JX)                        !vapor pressure, [kPa]
  real(r8) :: DYLN(JY,JX)                       !daylength, [h]
  real(r8) :: DYLX(JY,JX)                       !daylength of previous day, [h]
  real(r8) :: DYLM(JY,JX)                       !maximum daylength, [h]
  real(r8) :: OMEGAG(4,JY,JX)                   !sine of solar beam on leaf surface, [-]

  real(r8) :: THS(JY,JX)                        !sky longwave radiation , [MJ d-2 h-1]
  real(r8) :: TRAD(JY,JX)                       !total daily solar radiation, [MJ d-1]
  real(r8) :: TAMX(JY,JX)                       !daily maximum air temperature , [oC]
  real(r8) :: TAMN(JY,JX)                       !daily minimum air temperature , [oC]
  real(r8) :: HUDX(JY,JX)                       !daily maximum vapor pressure , [kPa]
  real(r8) :: HUDN(JY,JX)                       !daily minimum vapor pressure , [kPa]
  real(r8) :: TWIND(JY,JX)                      !total daily wind travel, [m d-1]
  real(r8) :: TRAI(JY,JX)                       !total daily precipitation, [m d-1]
  real(r8) :: THSX(JY,JX)                       !sky longwave radiation , [MJ m-2 h-1]
  real(r8) :: OFFSET(JY,JX)                     !offset for calculating temperature in Arrhenius curves, [oC]
  real(r8) :: WDPTHD(366,JY,JX)

  real(r8) :: PRECD(JY,JX)                      !precipitation at ground surface used to calculate soil erosion, [m h-1]
  real(r8) :: PRECB(JY,JX)                      !precipitation at ground surface used to calculate soil erosion, [m h-1]

  real(r8) :: CO2EI(JY,JX)                      !initial atmospheric CO2 concentration, [umol mol-1]
  real(r8) :: CCO2EI(JY,JX)                     !initial atmospheric CO2 concentration, [g m-3]
  real(r8) :: OXYE(JY,JX)                       !atmospheric O2 concentration, [umol mol-1]
  real(r8) :: COXYE(JY,JX)                      !atmospheric O2 concentration, [g m-3]
  real(r8) :: Z2OE(JY,JX)                       !atmospheric N2O concentration, [umol mol-1]
  real(r8) :: CZ2OE(JY,JX)                      !atmospheric N2O concentration, [g m-3]
  real(r8) :: Z2GE(JY,JX)                       !atmospheric N2 concentration, [umol mol-1]
  real(r8) :: CZ2GE(JY,JX)                      !atmospheric N2 concentration, [g m-3]
  real(r8) :: ZNH3E(JY,JX)                      !atmospheric NH3 concentration, [umol mol-1]
  real(r8) :: CNH3E(JY,JX)                      !atmospheric NH3 concentration, [g m-3]
  real(r8) :: CH4E(JY,JX)                       !atmospheric CH4 concentration, [umol mol-1]
  real(r8) :: CCH4E(JY,JX)                      !atmospheric CH4 concentration, [g m-3]
  real(r8) :: H2GE(JY,JX)                       !atmospheric H2 concentration, [umol mol-1]
  real(r8) :: CH2GE(JY,JX)                      !atmospheric H2 concentration, [g m-3]
  real(r8) :: ZNOON(JY,JX)                      !time of solar noon, [h]
  real(r8) :: CO2E(JY,JX)                       !atmospheric CO2 concentration, [umol mol-1]
  real(r8) :: CCO2E(JY,JX)                      !atmospheric CO2 concentration, [g m-3]
  real(r8) :: RADS(JY,JX)                       !direct shortwave radiation, [W m-2]
  real(r8) :: RADY(JY,JX)                       !diffuse shortwave radiation, [W m-2]
  real(r8) :: RAPS(JY,JX)                       !direct PAR, [umol m-2 s-1]
  real(r8) :: RAPY(JY,JX)                       !diffuse PAR, [umol m-2 s-1]
  real(r8) :: SSIN(JY,JX)                       !sine of solar angle, [-]
  real(r8) :: SSINN(JY,JX)                      !sine of solar angle next hour, [-]

  real(r8) :: XRADH(24,366)                     !longwave radiation (MJ m-2 h-1)
  real(r8) :: TLEX(JY,JX)                       !total latent heat flux x boundary layer resistance, [MJ m-1]
  real(r8) :: TSHX(JY,JX)                       !total sensible heat flux x boundary layer resistance, [MJ m-1]
  real(r8) :: TLEC(JY,JX)                       !total latent heat flux x boundary layer resistance, [MJ m-1]
  real(r8) :: TSHC(JY,JX)                       !total sensible heat flux x boundary layer resistance, [MJ m-1]
  real(r8) :: DPTHSK(JY,JX)                     !depth of soil heat sink/source, [m]
  real(r8) :: TKSD(JY,JX)                       !temperature of soil heat sink/source, [oC]
  real(r8) :: ATCAI(JY,JX)                      !initial mean annual air temperature, [oC]
  real(r8) :: RAD(JY,JX)                        !shortwave radiation in solar beam, [MJ m-2 h-1]
  real(r8) :: RAP(JY,JX)                        !PAR radiation in solar beam, [umol m-2 s-1]
  real(r8) :: ATCA(JY,JX)                       !mean annual air temperature, [oC]
  real(r8) :: ATCS(JY,JX)                       !mean annual soil temperature, [oC]
  real(r8) :: ATKA(JY,JX)                       !mean annual air temperature, [K]
  real(r8) :: ATKS(JY,JX)                       !mean annual soil temperature, [K]



  real(r8) :: PRECR(JY,JX)                      !rainfall, [m3 d-2 h-1]
  real(r8) :: PRECW(JY,JX)                      !snowfall, [m3 d-2 h-1]
  real(r8) :: PRECQ(JY,JX)                      !rainfall + snowfall, [m3 d-2 h-1]
  real(r8) :: PRECA(JY,JX)                      !rainfall + irrigation, [m3 d-2 h-1]
  real(r8) :: ENGYP(JY,JX)                      !cumulative rainfall energy impact on soil surface
  real(r8) :: PHR(JY,JX)                        !precipitation pH, [-]
  real(r8) :: CN4RI(JY,JX)                      !precipitation initial NH4 concentration, [g m-3]
  real(r8) :: CNORI(JY,JX)                      !precipitation initial NO3 concentration, [g m-3]
  real(r8) :: CN4R(JY,JX)                       !precipitation  NH4 concentration, [g m-3]
  real(r8) :: CN3R(JY,JX)                       !precipitation  NH3 concentration, [g m-3]
  real(r8) :: CNOR(JY,JX)                       !precipitation  NO3 concentration, [g m-3]
  real(r8) :: CPOR(JY,JX)                       !precipitation  H2PO4 concentration, [g m-3]
  real(r8) :: CALR(JY,JX)                       !precipitation  Al concentration, [g m-3]
  real(r8) :: CFER(JY,JX)                       !precipitation  Fe concentration, [g m-3]
  real(r8) :: CHYR(JY,JX)                       !precipitation  H concentration, [g m-3]
  real(r8) :: CCAR(JY,JX)                       !precipitation  Ca concentration, [g m-3]
  real(r8) :: CMGR(JY,JX)                       !precipitation  Mg concentration, [g m-3]
  real(r8) :: CNAR(JY,JX)                       !precipitation  Na concentration, [g m-3]
  real(r8) :: CKAR(JY,JX)                       !precipitation  K concentration, [g m-3]
  real(r8) :: COHR(JY,JX)                       !precipitation  OH concentration, [g m-3]
  real(r8) :: CSOR(JY,JX)                       !precipitation  SO4 concentration, [g m-3]
  real(r8) :: CCLR(JY,JX)                       !precipitation  Cl concentration, [g m-3]
  real(r8) :: CC3R(JY,JX)                       !precipitation  CO3 concentration, [g m-3]
  real(r8) :: CHCR(JY,JX)                       !precipitation  HCO3 concentration, [g m-3]
  real(r8) :: CCHR(JY,JX)                       !precipitation  CH4 concentration, [g m-3]
  real(r8) :: CAL1R(JY,JX)                      !precipitation  AlOH concentration, [g m-3]
  real(r8) :: CAL2R(JY,JX)                      !precipitation  AlOH2 concentration, [g m-3]
  real(r8) :: CAL3R(JY,JX)                      !precipitation  AlOH3 concentration, [g m-3]
  real(r8) :: CAL4R(JY,JX)                      !precipitation  AlOH4 concentration, [g m-3]
  real(r8) :: CALSR(JY,JX)                      !precipitation  AlSO4 concentration, [g m-3]
  real(r8) :: CFE1R(JY,JX)                      !precipitation  FeOH concentration, [g m-3]
  real(r8) :: CFE2R(JY,JX)                      !precipitation  FeOH2 concentration, [g m-3]
  real(r8) :: CFE3R(JY,JX)                      !precipitation  FeOH3 concentration, [g m-3]
  real(r8) :: CFE4R(JY,JX)                      !precipitation  FeOH4 concentration, [g m-3]
  real(r8) :: CFESR(JY,JX)                      !precipitation  FeSO4 concentration, [g m-3]
  real(r8) :: CCAOR(JY,JX)                      !precipitation  CaOH concentration, [g m-3]
  real(r8) :: CCACR(JY,JX)                      !precipitation  CaCO3 concentration, [g m-3]
  real(r8) :: CCAHR(JY,JX)                      !precipitation  CaHCO3 concentration, [g m-3]
  real(r8) :: CCASR(JY,JX)                      !precipitation  CaSO4 concentration, [g m-3]
  real(r8) :: CMGOR(JY,JX)                      !precipitation  MgOH concentration, [g m-3]
  real(r8) :: CMGCR(JY,JX)                      !precipitation  MgCO3 concentration, [g m-3]
  real(r8) :: CMGHR(JY,JX)                      !precipitation  MgHCO3 concentration, [g m-3]
  real(r8) :: CMGSR(JY,JX)                      !precipitation  MgSO4 concentration, [g m-3]
  real(r8) :: CNACR(JY,JX)                      !precipitation  NaCO3 concentration, [g m-3]
  real(r8) :: CNASR(JY,JX)                      !precipitation  NaSO4 concentration, [g m-3]
  real(r8) :: CKASR(JY,JX)                      !precipitation  K concentration, [g m-3]
  real(r8) :: CH0PR(JY,JX)                      !precipitation  PO4 concentration, [g m-3]
  real(r8) :: CH1PR(JY,JX)                      !precipitation  HPO4 concentration, [g m-3]
  real(r8) :: CH3PR(JY,JX)                      !precipitation  H3PO4 concentration, [g m-3]
  real(r8) :: CF1PR(JY,JX)                      !precipitation  FeHPO4 concentration, [g m-3]
  real(r8) :: CF2PR(JY,JX)                      !precipitation  FeH2PO4 concentration, [g m-3]
  real(r8) :: CC0PR(JY,JX)                      !precipitation  CaPO4 concentration, [g m-3]
  real(r8) :: CC1PR(JY,JX)                      !precipitation  CaHPO4 concentration, [g m-3]
  real(r8) :: CC2PR(JY,JX)                      !precipitation  CaH2PO4 concentration, [g m-3]
  real(r8) :: CM1PR(JY,JX)                      !precipitation  MgHPO4 concentration, [g m-3]
  real(r8) :: CCOR(JY,JX)                       !precipitation  CO2 concentration, [g m-3]
  real(r8) :: COXR(JY,JX)                       !precipitation  O2 concentration, [g m-3]
  real(r8) :: CNNR(JY,JX)                       !precipitation  N2 concentration, [g m-3]
  real(r8) :: CN2R(JY,JX)                       !precipitation  N2O concentration, [g m-3]

  real(r8) :: DRAD(12)                          !change factor for radiation, [-]
  real(r8) :: DTMPX(12)                         !change factor for maximum temperature, [-]
  real(r8) :: DTMPN(12)                         !change factor for minimum temperature, [-]
  real(r8) :: DHUM(12)                          !change factor for humidity, [-]
  real(r8) :: DPREC(12)                         !change factor for precipitation, [-]
  real(r8) :: DWIND(12)                         !change factor for wind speed, [-]
  real(r8) :: DCO2E(12)                         !change factor for atmospheric CO2 concentration, [-]
  real(r8) :: DCN4R(12)                         !change factor for NH4 in precipitation, [-]
  real(r8) :: DCNOR(12)                         !change factor for NO3 in precipitation, [-]
  real(r8) :: TDTPX(JY,JX,12)                   !accumulated change  for maximum temperature, [-]
  real(r8) :: TDTPN(JY,JX,12)                   !accumulated change  for minimum temperature, [-]
  real(r8) :: TDRAD(JY,JX,12)                   !accumulated change  for radiation, [-]
  real(r8) :: TDHUM(JY,JX,12)                   !accumulated change  for humidity, [-]
  real(r8) :: TDPRC(JY,JX,12)                   !accumulated change  for precipitation, [-]
  real(r8) :: TDWND(JY,JX,12)                   !accumulated change  for wind speed, [-]
  real(r8) :: TDCO2(JY,JX,12)                   !accumulated change  for atmospheric CO2 concentration, [-]
  real(r8) :: TDCN4(JY,JX,12)                   !accumulated change  for NH4 in precipitation, [-]
  real(r8) :: TDCNO(JY,JX,12)                   !accumulated change  for NO3 in precipitation, [-]

end module ClimForcDataType
