
      CHARACTER(len=16):: DATA(30),DATAC(30,250,250) &
      ,DATAP(JP,JY,JX),DATAM(JP,JY,JX),DATAX(JP),DATAY(JP) &
      ,DATAZ(JP,JY,JX),OUTS(10),OUTP(10),OUTFILS(10,JY,JX) &
      ,OUTFILP(10,JP,JY,JX)
      CHARACTER(len=3) :: CHOICE(102,20)
      CHARACTER(len=8) :: CDATE
      CHARACTER(len=80):: PREFIX


      COMMON/FILEC/DATA,DATAC,DATAP,DATAM,DATAX,DATAY,DATAZ &
      ,OUTS,OUTP,OUTFILS,OUTFILP,CHOICE,CDATE,PREFIX
