module Hist1Mod
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use fileUtil, only : open_safe
  use GridConsts
  use GridDataType
  use EcoSIMCtrlDataType
  use EcosimConst
  use EcoSIMHistMod
  use FlagDataType
  use PlantTraitDataType
  use PlantDataRateType
  use ClimForcDataType
  use CanopyDataType
  use RootDataType
  use SOMDataType
  use SoilPhysDataType
  use SoilHeatDatatype
  use SoilWaterDataType
  use SnowDataType
  use ChemTranspDataType
  use PlantMngmtDataType
  use EcosimBGCFluxType
  use SoilPropertyDataType
  use SoilBGCDataType
  use AqueChemDatatype
  use SurfSoilDataType
  implicit none

  private
  character(len=*),private, parameter :: mod_filename = __FILE__
  public :: fouts,foutp, outpd, outph, outsd, outsh
  contains
!!!!!!!!!!!!!!!!!!!!
!IF(K.EQ.1)HEAD(M)=1000.0*URAIN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)     converts cumulative precip from m to mm
!IF(K.EQ.1)HEAD(M)=RAD(NY,NX)*277.8     converts radiation in MJ m-2 h-1 to W m-2
!IF(K.EQ.1)HEAD(M)=HCO2G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*23.14815     converts  CO2 flux from g C m-2 h-1  to umol m-2 s-1
!IF(K.EQ.4)HEAD(M)=HOXYG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*8.68056      converts O2 flux from g O m-2 h-1 to umol m-2 s-1

!IF(K.EQ.55)HEAD(M)=RC(NZ,NY,NX)*1.56*3600.0   converts canopy stomatal resistance from h m-1 for H2O to s m-1 for CO2
!IF(K.EQ.56)HEAD(M)=RA(NZ,NY,NX)*1.34*3600.0   converts canopy boundary layer resistance from h m-1 for H2O to s m-1 for CO2
!!!!!!!!!!!!!!!!!!!!




=WTSHTE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !canopy shoot C, SHOOT_C
=WTLFE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !canopy leaf C, LEAF_C
=WTSHEE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !canopy sheath C, SHTH_C
=WTSTKE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !STALK_C
=WTRSVE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !RESERVE_C
=(WTHSKE(ielmc,NZ,NY,NX)+WTEARE(ielmc,NZ,NY,NX))/AREA(3,NU(NY,NX),NY,NX) !REPRO_C, reproduction C
=WTGRE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !GRAIN_C
=WTRTE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !ROOT_C
=WTNDE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !NDL_C, nodule C
=WTRVE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !STORED_C
=GRNO(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !GRAIN_NO., grain number
=ARLFP(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !LAI
=CARBN(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !GPP, gC/m2
=TEUPTK(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX) !EXUD_C, plant C exudation, gC/m2
=TESNC(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !LITTER_C, total plant litterfall C, gC/m2
=TESN0(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !SF_LIT_C, plant literfall to surface, gC/m2
=TCO2T(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !AUTO_RESP, total plant autotrophic respiration, gC/m2
=TCO2A(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !ABV_GRD_RESP, abovebround plant autotrophic respiration, gC/m2
=CEPOLP(ielmc,NZ,NY,NX)                         ![SOL._C], canopy nonstructural C concentration, gC/m2
=HVSTE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !HVST_C
=RTDNP(1,1:JZ,NZ,NY,NX)*PP(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !DNS_RT, root layer length density, m m^-3

=BALE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !C_BALANCE
=WTSTGE(ielmc,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX) !STG_DEAD_C
=VCO2F(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX) !FIRE_CO2
=VCH4F(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX) !FIRE_CH4
=ZNPP(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !NPP
=ZC(NZ,NY,NX)                            !CAN_HT, canopy height, m
=PP(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !POPN, plant population, 1/m2

=-CTRAN(NZ,NY,NX)*1000.0/AREA(3,NU(NY,NX),NY,NX)  !TRANSPN, mm/m2, total transpiration
=WSTR(NZ,NY,NX)                          !WTR_STRESS, plant water stress
=OSTR(NZ,NY,NX)                          !OSTR, plant oxygen stress
!
!     DAILY PLANT N OUTPUT
!
=WTSHTE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !SHOOT_N
=WTLFE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !LEAF_N
=WTSHEE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !SHTH_N
=WTSTKE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !STALK_N
=WTRSVE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !RESERVE_N
=(WTHSKE(ielmn,NZ,NY,NX)+WTEARE(ielmn,NZ,NY,NX))/AREA(3,NU(NY,NX),NY,NX)  !HUSK_N
=WTGRE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !GRAIN_N
=WTRTE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !ROOT_N
=WTNDE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !NDL_N
=WTRVE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !STORED_N
=TEUPTK(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !UPTK_N
=TESNC(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !LITTER_N
=TZUPFX(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !TL_N_FIXED

=CZPOLP(NZ,NY,NX)   ![SOL_N]
=(WTLFN(NZ,NY,NX)+EPOOLP(ielmn,NZ,NY,NX))/(WTLF(NZ,NY,NX)+EPOOLP(ielmc,NZ,NY,NX))  !N_STRESS, NC ratio

=CPPOLP(NZ,NY,NX)  ![SOL_P]

=(WTLFP(NZ,NY,NX)+EPOOLP(ielmp,NZ,NY,NX))/(WTLF(NZ,NY,NX)+EPOOLP(ielmc,NZ,NY,NX))  !'P_STRESS', PC ratio

=TNH3C(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !NH3_FLUX
=HVSTE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !HVST_N
=BALE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !N_BALANCE
=WTSTGE(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !STG_DEAD_N
=VNH3F(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !FIRE_N
=TESN0(ielmn,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !SF_LIT_N

=WTSHTE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !SHOOT_P
=WTLFE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !LEAF_P
=WTSHEE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !SHTH_P
=WTSTKE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !STALK_P
=WTRSVE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !RESERVE_P
=(WTHSKE(ielmp,NZ,NY,NX)+WTEARE(ielmp,NZ,NY,NX))/AREA(3,NU(NY,NX),NY,NX)  !HUSK_P
=WTGRE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !GRAIN_P
=WTRTE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !ROOT_P
=WTNDE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !NDL_P, nodule P
=WTRVE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !STORED_P
=TEUPTK(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !UPTK_P
=TESNC(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !LITTER_P
=CPPOLP(NZ,NY,NX)                          ![SOL_P]

cancp(NZ,NY,NX)=(WTLFP(NZ,NY,NX)+EPOOLP(ielmp,NZ,NY,NX))/(WTLF(NZ,NY,NX)+EPOOLP(ielmc,NZ,NY,NX))  !P_STRESS

=HVSTE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !HVST_P
=BALE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !P_BALANCE
WTSTGPXY(NZ,NY,NX)=WTSTGE(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !STG_DEAD_P
VPO4FXY(NZ,NY,NX)=VPO4F(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !FIRE_P
TPSN0XY(NZ,NY,NX)=TESN0(ielmp,NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !SF_LIT_P, surface P litterfall
!


growth_state(NZ,NY,NX)  !GROWTH_STG

  function growth_state(NZ,NY,NX)result(CHEAD)

  implicit none

  integer :: KN
  character(len=16) :: CHEAD
  D2030: DO KN=10,0,-1
   IF(KN.EQ.0)THEN
     CHEAD='  PLANTING'
   ELSE
     IF(IDAY(KN,NB1(NZ,NY,NX),NZ,NY,NX).EQ.0)CYCLE
     SELECT CASE(KN)
     CASE (1)
       CHEAD='  EMERGENCE'
     CASE (2)
       CHEAD='  FLORAL_INIT.'
     CASE (3)
       CHEAD='  JOINTING'
     CASE (4)
       CHEAD='  ELONGATION'
     CASE (5)
       CHEAD='  HEADING'
     CASE (6)
       CHEAD='  ANTHESIS'
     CASE (7)
       CHEAD='  SEED_FILL'
     CASE (8)
       CHEAD='  SEED_NO._SET'
     CASE (9)
       CHEAD='  SEED_MASS_SET'
     CASE (10)
       CHEAD='  END_SEED_FILL'
     CASE DEFAULT
     END SELECT
   ENDDO D2030

  end function growth_state

=NBR(NZ,NY,NX)   !BRANCH_NO.
=VSTG(NB1(NZ,NY,NX),NZ,NY,NX)  !NODE_NO.
=FDBK(NB1(NZ,NY,NX),NZ,NY,NX)  !RUB_ACTVN

CANNC(NZ,NY,NC)=(WTLFN(NZ,NY,NX)+EPOOLP(ielmn,NZ,NY,NX))/(WTLF(NZ,NY,NX)+EPOOLP(ielmc,NZ,NY,NX))  !LEAF_N/C

CANPC(NZ,NY,NX)=(WTLFP(NZ,NY,NX)+EPOOLP(ielmp,NZ,NY,NX))/(WTLF(NZ,NY,NX)+EPOOLP(ielmc,NZ,NY,NX))  !LEAF_P/C
=PSILZ(NZ,NY,NX) !MIN_LWP
=OSTR(NZ,NY,NX)  !'O2_STRESS'
=TFN3(NZ,NY,NX)  !'TEMP_STRESS'


CNETXY(NZ,NY,NX)=CNET(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)*23.148  !umol m-2 s-1, 23.148=1e6/12.
CARBNXY(NZ,NY,NX)=CARBN(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)
TCO2AXY(NZ,NY,NX)=TCO2A(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)
=CEPOLP(ielmc,NZ,NY,NX)
RCXY(NZ,NY,NX)=RC(NZ,NY,NX)*1.56*3600.0
RAXY(NZ,NY,NX)=RA(NZ,NY,NX)*1.34*3600.0
CO2Q(NZ,NY,NX)!canopy gaseous CO2 (ppmv)
ARLFSXY(NZ,NY,NX)=ARLFS(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)


PSILT(NZ,NY,NX)  !'PSI_CAN', canopy total water pontential, MPa
PSILG(NZ,NY,NX)  !'TURG_CAN', Canopy turgor potential, MPa
RC(NZ,JY,JX)=RC(NZ,NY,NX)*3600.0_r8  !'STOM_RSC', canopy stomatal resistance, s m^-1
RAXY(NZ,JY,JX)=RA(NZ,NY,NX)*3600.0_r8 !'BLYR_RSC', canopy boundary layer resistance, s m^-1
EPXY(NZ,JY,JX)=EP(NZ,NY,NX)*1000.0_r8/AREA(3,NU(NY,NX),NY,NX) !'TRANSPN', canopy transpiration mm H2O/m2/h
OSTR(NZ,JY,JX) !O2_STRESS,plant O2 stress indicator

PSIRT(1,1:JZ,NZ,NY,NX)  !PSI_RT

=UPNH4(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !'NH4_UPTK'
=UPNO3(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !'NO3_UPTK'
=UPNF(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !'N2_FIXN'
=CZPOLP(NZ,NY,NX) ![TNN] canopy nonstructural N concentration, [g g-1]
=RNH3C(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !'NH3_FLUX'

!UP_NH4, plant uptake of NH4
RUPNH4XY(1:JZ,NZ,NY,NX)=(RUPNH4(1,15,NZ,NY,NX)+RUPNH4(2,15,NZ,NY,NX) &
                        +RUPNHB(1,15,NZ,NY,NX)+RUPNHB(2,15,NZ,NY,NX))/AREA(3,15,NY,NX)

!UP_NO3, plant uptake of NO3
RUPNO3XY(1:JZ,NZ,NY,NX)=(RUPNO3(1,15,NZ,NY,NX)+RUPNO3(2,15,NZ,NY,NX) &
                        +RUPNOB(1,15,NZ,NY,NX)+RUPNOB(2,15,NZ,NY,NX))/AREA(3,15,NY,NX)


UPH2P(NZ,NY,NX)=UPH2P(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !PO4_UPTK
CPPOLP(NZ,NY,NX)  ![TNP]

!UP_PO4
RUPHP(1:JZ,NZ,NY,NX)=(RUPH2P(1,1:JZ,NZ,NY,NX)+RUPH2P(2,1:JZ,NZ,NY,NX) &
                        +RUPH2B(1,15,NZ,NY,NX)+RUPH2B(2,15,NZ,NY,NX))/AREA(3,15,NY,NX)

!canopy radiation
RAD1XY(NZ,NY,NX)=277.8*RAD1(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !CAN_RN
EFLXCXY(NZ,NY,NX)=277.8*EFLXC(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !CAN_LE
SFLXCXY(NZ,NY,NX)=277.8*SFLXC(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !CAN_H
HFLXCXY(NZ,NY,NX)=277.8*HFLXC(NZ,NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !CAN_G
!=TCC(NZ,NY,NX)   !CAN_TEMP, canopy temperature
!=TFN3(NZ,NY,NX)  !TEMP_FN, tempreature function

URSDCXY(NY,NX)=URSDC(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UORGCXY(NY,NX)=UORGC(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UORGFXY(NY,NX)=UORGF(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UXCSNXY(NY,NX)=UXCSN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCO2GXY(NY,NX)=UCO2G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UOXYGXY(NY,NX)=UOXYG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCOPXY(NY,NX)=UCOP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
TOMTXY(NY,NX)=TOMT(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCH4GXY(NY,NX)=UCH4G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
!=UDOCQ(NY,NX)/TAREA
!=UDOCD(NY,NX)/TAREA
!=UDICQ(NY,NX)/TAREA
!=UDICD(NY,NX)/TAREA
CO2E(NY,NX)
TNBPXY(NY,NX)=TNBP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCO2FXY(JY,JX)=UCO2F(NY,NX)/AREA(3,NU(NY,NX),NY,NX)

ORGC(0:JZ,JY,JX)=ORGC(15,NY,NX)/AREA(3,NU(NY,NX),NY,NX)

UH2GGXY(NY,NX)=UH2GG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
XHVSTCXY(NY,NX)=XHVSTE(ielmc,NY,NX)/AREA(3,NU(NY,NX),NY,NX)
ARLFCXY(JY,JX)=ARLFC(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
TGPPXY(NY,NX)=TGPP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
TRAUXY(NY,NX)=TRAU(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
TNPPXY(JY,JX)=TNPP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
THREXY(JY,JX)=THRE(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCH4FXY(JY,JX)=UCH4F(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UCO2SXY(JY,JX)=UCO2S(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
WTSTGTXY(JY,JX)=WTSTGT(NY,NX)/AREA(3,NU(NY,NX),NY,NX)

!URAINXY(JY,JX)=1000.0*URAIN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
!UEVAPXY(JY,JX)=1000.0*UEVAP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
!=1000.0*URUN(NY,NX)/TAREA
!UVOLWXY(JY,JX)=1000.0*UVOLW(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !mm H2O /m2
!=1000.0*UVOLO(NY,NX)/TAREA
DPTHSXY(JY,JX)=1000.0*DPTHS(NY,NX)

THETWZ(1:JZ,NY,NX)
THETWZS(JY,JX)=THETWZ(0,NY,NX)
THETIZ(1:JZ,NY,NX)

THETIZS(JY,JX)=THETIZ(0,NY,NX)

PSISMXY(1:JZ,JY,JX)=PSISM(11,NY,NX)+PSISO(11,NY,NX)
=USEDOU(NY,NX)*1000.0/TAREA
PSISMXY(0,JY,JX)=PSISM(0,NY,NX)
!thickness of litter layer
DLYR0(JY,JX)=-CDPTH(NU(NY,NX)-1,NY,NX)+DLYR(3,0,NY,NX)
DPTHAXY(JY,JX)=-(DPTHA(NY,NX)-CDPTH(NU(NY,NX)-1,NY,NX))
DPTHTXY(JY,JX)=-(DPTHT(NY,NX)-CDPTH(NU(NY,NX)-1,NY,NX))
!
URSDNXY(NY,NX)=URSDN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UORGNXY(NY,NX)=UORGN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UFERTNXY(NY,NX)=UFERTN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UXZSNXY(NY,NX)=UXZSN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UNH4XY(NY,NX)=UNH4(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UNO3XY(JY,JX)=UNO3(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
!=UDONQ(NY,NX)/TAREA
!=UDOND(NY,NX)/TAREA
!=UDINQ(NY,NX)/TAREA
!=UDIND(NY,NX)/TAREA
UN2OGXY(NY,NX)=UN2OG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UNH3GXY(NY,NX)=UNH3G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
UN2GSXY(NY,NX)=UN2GS(NY,NX)/AREA(3,NU(NY,NX),NY,NX)
                  TONTXY(NY,NX)=TONT(NY,NX)/AREA(3,NU(NY,NX),NY,NX)

!NH4, total bioavailable NH4 in soil, disolved and sorped
NH4XS(1:JZ,JY,JX)=(ZNH4S(15,NY,NX)+ZNH4B(15,NY,NX)+14.0*(XN4(15,NY,NX)+XNB(15,NY,NX)))/BKVL(15,NY,NX)
!NO3, nitrate in soil
ZNOXS(1:JZ,JY,JX)=(ZNO3S(15,NY,NX)+ZNO3B(15,NY,NX)+ZNO2S(15,NY,NX)+ZNO2B(15,NY,NX))/BKVL(15,NY,NX)

!NH4 in litter
NH4XS(0:JZ,JY,JX)=(ZNH4S(0,NY,NX)+14.0*XN4(0,NY,NX))/BKVL(0,NY,NX)
!NO3 in litter
ZNOXS(0,JY,JX)=(ZNO3S(0,NY,NX)+ZNO2S(0,NY,NX))/BKVL(0,NY,NX)

XHVSTNXY(NY,NX)=XHVSTE(ielmn,NY,NX)/AREA(3,NU(NY,NX),NY,NX)    !ECO_HVST_N
TRINH4XY(NY,NX)=-TRINH4(NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !NET_N_MIN
UNH3FXY(NY,NX)=UNH3F(NY,NX)/AREA(3,NU(NY,NX),NY,NX)      !FIRE_N
UN2GGXY(NY,NX)=UN2GG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)      !N2_FLUX

URSDPXY(NY,NX)=URSDP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !RESIDUE_P
UORGPXY(NY,NX)=UORGP(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !HUMUS_P
UFERTPXY(NY,NX)=UFERTP(NY,NX)/AREA(3,NU(NY,NX),NY,NX) !FERTZR_P
UXPSNXY(NY,NX)=UXPSN(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !NET_PL_EXCH_P
UPO4XY(JY,JX)=UPO4(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !EXCH_PO4, integrated bioavailable P in soil
UDOPQXY(NY,NX)=UDOPQ(NY,NX)/TAREA  !SUR_DOP+SED_FLX, landscape
UDOPDXY(NY,NX)=UDOPD(NY,NX)/TAREA  !SUB_DOP_FLX
!=UDIPQ(NY,NX)/TAREA   !SUR_DIP_FLX, surface
!=UDIPD(NY,NX)/TAREA   !SUB_DIP_FLX, subsurface

UPP4XY(JY,JX)=UPP4(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !PRECIP_P
TOPTXY(NY,NX)=TOPT(NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !MICRO_P
UPO4FXY(NY,NX)=UPO4F(NY,NX)/AREA(3,NU(NY,NX),NY,NX) !FIRE_P

!PO4 in soil, H1PO4 plus H2PO4
HXPO4(1:JZ,JY,JX)=(H1PO4(1:JZ,NY,NX)+H1POB(0:JZ,NY,NX)+H2PO4(0:JZ,NY,NX)+H2POB(0:JZ,NY,NX))/VOLW(0:JZ,NY,NX)

!EXCH_P in soil
XHPS(1:JZ)=31.0*(XH1P(1:JZ,NY,NX)+XH2P(1:JZ,NY,NX)+XH1PB(1:JZ,NY,NX)+XH2PB(1:JZ,NY,NX))/BKVL(1:JZ,NY,NX)

!PO4_RES, PO4 in surface litter
H2PO4XY(0,JY,JX)=H2PO4(0,NY,NX)/BKVL(0,NY,NX)


XHPS(JY,JX)=31.0*(XH1P(NY,NX)+XH2P(NY,NX))/BKVL(NY,NX)  !EXCH_P_RES in surface litter
XHVSTPXY(NY,NX)=XHVSTE(ielmp,NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !ECO_HVST_P
TRIPO4XY(NY,NX)=-TRIPO4(NY,NX)/AREA(3,NU(NY,NX),NY,NX)  !NET_P_MIN

!total
TRAD(NY,NX)  !radiation, 'RADN'
TAMX(NY,NX)  !daily maximum air temperature,'TMAX_AIR'
TAMN(NY,NX)  !daily minimum air temperature, 'TMIN_AIR'
HUDX(NY,NX)  !daily maximum vapor pressure , 'HMAX_AIR', [kPa]
HUDN(NY,NX)  !daily minimum vapor pressure , 'HMIN_AIR', [kPa]
TWIND(NY,NX)*0.001  !distance wind travels m/day, WIND
TRAI(NY,NX)  !PRECN

TMIN_SOIL
TSMX(1:JZ,JY,JX)  !TMAX_SOIL
TSMN(1:JZ,JY,JX)  !TMIN_SOIL


TSMX(0,JY,JX)  !TMAX_LITTER
TSMN(0,JY,JX)  !TMIN_LITTER
ECND(JZ,JY,JX)  !ECND
UIONOU(NY,NX)/TAREA  !TTL_SALT_DISCHG


HCO2GXY(NY,NX)=HCO2G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*23.14815  !SOIL_CO2_FLUX
TCNETXY(NY,NX)=TCNET(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*23.14815  !ECO_CO2_FLUX
HCH4GXY(NY,NX)=HCH4G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*23.14815  !CH4_FLUX
HOXYGXY(NY,NX)=HOXYG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)*8.68056   !O2_FLUX
CCO2S(0,NY,NX)  !CO2_LIT
CCO2S(1:JZ,NY,NX)  !CO2_soil,

CCH4S(1:JZ,NY,NX)  !CH4_soil

COXYS(0,NY,NX)  !O2_LIT
COXYS(1:JZ,NY,NX)  !O2_soil

TEVAPGXY(NY,NX)=TEVAPG(NY,NX)*1000.0/AREA(3,NU(NY,NX),NY,NX)  !EVAPN, mm H2O/h/m2
WQRHXY(NY,NX)=-WQRH(NY,NX)*1000.0/TAREA            !RUNOFF
USEDOUXY(NY,NX)=USEDOU(NY,NX)*1000.0/TAREA         !SEDIMENT
UVOLWXY(NY,NX)=UVOLW(NY,NX)*1000.0/AREA(3,NU(NY,NX),NY,NX)  !TTL_SWC
HVOLOXY(NY,NX)=HVOLO(NY,NX)*1000.0/TAREA  !DISCHG

VOLWSXY(NY,NX)=AMAX1(1.0E-64,(VOLSS(NY,NX)+VOLIS(NY,NX) &
                    *DENSI+VOLWS(NY,NX))*1000.0/AREA(3,NU(NY,NX),NY,NX))  !SNOWPACK, mm H2O equiv/m2
THETWZ(0:JZ,NY,NX)  !WTR_soil
THETWZ(0,NY,NX)  !WTR_LIT

THETIZ(JZ,NY,NX) !ICE_soil
THETIZ(0,NY,NX) !ICE_LIT


DPTHAXY(NY,NX)=-(DPTHA(NY,NX)-CDPTH(NU(NY,NX)-1,NY,NX))   !ACTV_LYR, active layer depth from soil surface, negative in soil
DPTHTXY(NY,NX)=-(DPTHT(NY,NX)-CDPTH(NU(NY,NX)-1,NY,NX))   !WTR_TBL, water table relative to soil surface (negative in soil)
!
!     HOURLY SOIL N OUTPUT
!
HN2OGXY(NY,NX)=HN2OG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !N2O_FLUX
HN2GGXY(NY,NX)=HN2GG(NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !N2G_FLUX, gaseous N2 flux at soil surface
HNH3GXY(NY,NX)=HNH3G(NY,NX)/AREA(3,NU(NY,NX),NY,NX)   !NH3_FLUX
UDINQ(NY,NX)   !SURF_N_FLUX
UDIND(NY,NX)   !SUBS_N_FLUX

CNH3S(0,NY,NX)    !NH3_LIT
CZ2OS(0,NY,NX)    !N2O_LIT,
CNH3S(1:JZ,NY,NX)  !NH3_soil, concentration of dissolved NH3 in soil micropore
CZ2OS(1:JZ,NY,NX)  !N2O_soil, concentration of dissolved N2O in soil micropore

!
!     HOURLY SOIL P OUTPUT
!
! TAREA is landscape area
UDIPQ(NY,NX)   !SURF_P_FLUX
UDIPD(NY,NX)   !SUBS_P_FLUX

                  RADXY(NY,NX)=RAD(NY,NX)*277.8  !SOL_RADN
                  TCA(NY,NX)  !AIR_TEMP
                  VPK(NY,NX)  !HUM
UAXY(JY,JX)       UAXY(NY,NX)=UA(NY,NX)/3600.0_r8   !convert into m/s, WIND
PRECXY(JY,JX)     PRECXY(NY,NX)=(PRECR(NY,NX)+PRECW(NY,NX))*1000.0/AREA(3,NU(NY,NX),NY,NX)  !PREC
HEATI(JY,JX)      HEATIXY(NY,NX)=HEATI(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !SOIL_RN
HEATEXY(JY,JX)    HEATEXY(NY,NX)=HEATE(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !SOIL_LE
HEATSXY(JY,JX)    HEATSXY(NY,NX)=HEATS(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !SOIL_H
HEATHVXY(JY,JX)   HEATHVXY(NY,NX)=-(HEATH(NY,NX)-HEATV(NY,NX))*277.8/AREA(3,NU(NY,NX),NY,NX)  !SOIL_G
TRNXY(JY,JX)      TRNXY(NY,NX)=TRN(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !ECO_RN
TLEXY(JY,JX)      TLEXY(NY,NX)=TLE(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !ECO_LE
TSHXY(JY,JX)      TSHXY(NY,NX)=TSH(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !ECO_H
TGHXY(JY,JX)      TGHXY(NY,NX)=TGH(NY,NX)*277.8/AREA(3,NU(NY,NX),NY,NX)  !ECO_G
TCS(1:JZ,JY,JX)   !TEMP_soil
TCS(0,JY,JX)   !TEMP_LITTER
TCW(1,NY,NX)   !TEMP_SNOW, temperature of snow surface

end module Hist1Mod
