module PlantDataStateType

  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridDataType
  implicit none
  public
  save

  !state variables
!Carbon
  real(r8) :: CFOPC(0:5,4,JP,JY,JX)             !litter kinetic fraction, [-]
  real(r8) :: WTSHT(JP,JY,JX)                   !canopy shoot C, [g d-2]
  real(r8) :: WTLF(JP,JY,JX)                    !canopy leaf C, [g d-2]
  real(r8) :: WTSHE(JP,JY,JX)                   !canopy sheath C , [g d-2]
  real(r8) :: WTSTK(JP,JY,JX)                   !canopy stalk C, [g d-2]
  real(r8) :: WVSTK(JP,JY,JX)                   !canopy active stalk C, [g d-2]
  real(r8) :: WTRSV(JP,JY,JX)                   !canopy reserve C, [g d-2]
  real(r8) :: WTHSK(JP,JY,JX)                   !canopy husk C, [g d-2]
  real(r8) :: WTEAR(JP,JY,JX)                   !canopy ear C, [g d-2]
  real(r8) :: WTGR(JP,JY,JX)                    !canopy grain C, [g d-2]
  real(r8) :: WTLS(JP,JY,JX)                    !canopy leaf + sheath C, [g d-2]
  real(r8) :: WVSTKB(JC,JP,JY,JX)               !branch active stalk C, [g d-2]
  real(r8) :: CPOOL(JC,JP,JY,JX)                !branch nonstructural C, [g d-2]
  real(r8) :: WTLSB(JC,JP,JY,JX)                !branch leaf + sheath C, [g d-2]
  real(r8) :: WTSHTB(JC,JP,JY,JX)               !branch shoot C, [g d-2]
  real(r8) :: WTLFB(JC,JP,JY,JX)                !branch leaf C, [g d-2]
  real(r8) :: WTSHEB(JC,JP,JY,JX)               !branch sheath C , [g d-2]
  real(r8) :: WTSTKB(JC,JP,JY,JX)               !branch stalk C, [g d-2]
  real(r8) :: WTRSVB(JC,JP,JY,JX)               !branch reserve C, [g d-2]
  real(r8) :: WTHSKB(JC,JP,JY,JX)               !branch husk C, [g d-2]
  real(r8) :: WTEARB(JC,JP,JY,JX)               !branch ear C, [g d-2]
  real(r8) :: WTGRB(JC,JP,JY,JX)                !branch grain C, [g d-2]
  real(r8) :: WGLF(0:25,JC,JP,JY,JX)            !leaf C, [g d-2]
  real(r8) :: WGSHE(0:25,JC,JP,JY,JX)           !sheath C , [g d-2]
  real(r8) :: WGNODE(0:25,JC,JP,JY,JX)          !internode C, [g d-2]
  real(r8) :: CCPLNP(JP,JY,JX)                  !nodule nonstructural C, [g d-2]
  real(r8) :: GRWTB(JC,JP,JY,JX)                !maximum grain C during grain fill, [g d-2]
  real(r8) :: ARLFV(JZ,JP,JY,JX)                !canopy layer leaf area, [m2 d-2]
  real(r8) :: WGLFL(JZ,0:25,JC,JP,JY,JX)        !layer leaf C, [g d-2]
  real(r8) :: ARLFL(JZ,0:25,JC,JP,JY,JX)        !layer leaf area, [m2 d-2]
  real(r8) :: WSLF(0:25,JC,JP,JY,JX)            !layer leaf protein C, [g d-2]
  real(r8) :: WSSHE(0:25,JC,JP,JY,JX)           !layer sheath protein C, [g d-2]
  real(r8) :: CSNC(4,0:1,0:JZ,JP,JY,JX)         !plant litterfall C, [g d-2]
  real(r8) :: CNET(JP,JY,JX)                    !canopy net CO2 exchange, [g d-2 h-1]
  real(r8) :: WGLFV(JZ,JP,JY,JX)                !canopy layer leaf C, [g d-2]
  real(r8) :: CPOOLP(JP,JY,JX)                  !canopy nonstructural C, [g d-2]
  real(r8) :: CCPOLP(JP,JY,JX)                  !canopy nonstructural C concentration, [g d-2]
  real(r8) :: CCPOLB(JC,JP,JY,JX)               !branch nonstructural C concentration, [g d-2]
  real(r8) :: ARSTV(JZ,JP,JY,JX)                !canopy layer stem area, [m2 d-2]
  real(r8) :: WTSTDG(4,JP,JY,JX)                !standing dead C fraction, [g d-2]
  real(r8) :: WTSTG(JP,JY,JX)                   !standing dead C, [g d-2]
  real(r8) :: CPOLNB(JC,JP,JY,JX)               !branch nodule nonstructural C, [g d-2]
  real(r8) :: CPOLNP(JP,JY,JX)                  !canopy nodule nonstructural C, [g d-2]
  real(r8) :: WTNDB(JC,JP,JY,JX)                !branch nodule C, [g d-2]
  real(r8) :: WGSHEX(JC,JP,JY,JX)               !branch sheath structural C, [g d-2]
  real(r8) :: WTSTXB(JC,JP,JY,JX)               !branch stalk structural C, [g d-2]
  real(r8) :: WGLFX(JC,JP,JY,JX)                !branch leaf structural C, [g d-2]
  real(r8) :: WGLFPX(JC,JP,JY,JX)               !branch leaf structural P, [g d-2]
  real(r8) :: WGSHPX(JC,JP,JY,JX)               !branch sheath structural P, [g d-2]
  real(r8) :: WTSTXP(JC,JP,JY,JX)               !branch stalk structural P, [g d-2]

!root
  real(r8) :: WTRTA(JP,JY,JX)                   !root C per plant, [g p-1]
  real(r8) :: WTRT(JP,JY,JX)                    !plant root C, [g d-2]
  real(r8) :: WTRTS(JP,JY,JX)                   !plant root structural C, [g d-2]
  real(r8) :: WSRTL(2,JZ,JP,JY,JX)              !root layer protein C, [g d-2]
  real(r8) :: WTRT1(2,JZ,JC,JP,JY,JX)           !root layer C primary axes, [g d-2]
  real(r8) :: WTRT2(2,JZ,JC,JP,JY,JX)           !root layer C secondary axes, [g d-2]
  real(r8) :: WTRTD(2,JZ,JP,JY,JX)              !root layer C, [g d-2]
  real(r8) :: WTNDL(JZ,JP,JY,JX)                !root layer nodule mass, [g d-2]
  real(r8) :: WTND(JP,JY,JX)                    !root total nodule mass, [g d-2]
  real(r8) :: WTRTL(2,JZ,JP,JY,JX)              !root layer structural C, [g d-2]
  real(r8) :: CPOOLR(2,JZ,JP,JY,JX)             !root  layer nonstructural C, [g d-2]
  real(r8) :: CCPOLR(2,JZ,JP,JY,JX)             !root  layer nonstructural C concentration, [g g-1]
  real(r8) :: RTWT1(2,JC,JP,JY,JX)              !root C primary axes, [g d-2]
  real(r8) :: CWSRTL(2,JZ,JP,JY,JX)             !root layer protein C concentration, [g g-1]
!Nitrogen
  real(r8) :: CFOPN(0:5,4,JP,JY,JX)             !litterfall kinetic N fraction, [-]
  real(r8) :: WTSHN(JP,JY,JX)                   !canopy  N, [g d-2]
  real(r8) :: ZPOOLP(JP,JY,JX)                  !canopy  nonstructural N, [g d-2]
  real(r8) :: WTLFN(JP,JY,JX)                   !canopy leaf N, [g d-2]
  real(r8) :: WTSHEN(JP,JY,JX)                  !canopy sheath N, [g d-2]
  real(r8) :: WTSTKN(JP,JY,JX)                  !canopy stalk N, [g d-2]
  real(r8) :: WTRSVN(JP,JY,JX)                  !canopy reserve N, [g d-2]
  real(r8) :: WTHSKN(JP,JY,JX)                  !canopy husk N, [g d-2]
  real(r8) :: WTEARN(JP,JY,JX)                  !canopy ear N, [g d-2]
  real(r8) :: WTGRNN(JP,JY,JX)                  !canopy grain N, [g d-2]
  real(r8) :: WTSHTN(JC,JP,JY,JX)               !branch N, [g d-2]
  real(r8) :: WTLFBN(JC,JP,JY,JX)               !branch leaf N, [g d-2]
  real(r8) :: WTSHBN(JC,JP,JY,JX)               !branch sheath N, [g d-2]
  real(r8) :: WTSTBN(JC,JP,JY,JX)               !branch stalk N, [g d-2]
  real(r8) :: WTRSBN(JC,JP,JY,JX)               !branch reserve N, [g d-2]
  real(r8) :: WTHSBN(JC,JP,JY,JX)               !branch husk N, [g d-2]
  real(r8) :: WTEABN(JC,JP,JY,JX)               !branch ear N, [g d-2]
  real(r8) :: WTGRBN(JC,JP,JY,JX)               !branch grain N, [g d-2]
  real(r8) :: ZPOOL(JC,JP,JY,JX)                !branch  nonstructural N, [g d-2]
  real(r8) :: WGLFN(0:25,JC,JP,JY,JX)           !leaf N, [g d-2]
  real(r8) :: WGSHN(0:25,JC,JP,JY,JX)           !sheath N, [g d-2]
  real(r8) :: WGNODN(0:25,JC,JP,JY,JX)          !internode N, [g d-2]
  real(r8) :: WGLFLN(JZ,0:25,JC,JP,JY,JX)       !layer leaf N, [g d-2]
  real(r8) :: CZPOLP(JP,JY,JX)                  !canopy nonstructural N concentration, [g g-1]
  real(r8) :: CZPOLB(JC,JP,JY,JX)               !branch nonstructural N concentration, [g g-1]
  real(r8) :: WTSTDN(4,JP,JY,JX)                !standing dead N fraction, [g d-2]
  real(r8) :: WTSTGN(JP,JY,JX)                  !standing dead N , [g d-2]
  real(r8) :: ZPOLNB(JC,JP,JY,JX)               !branch nonstructural N concentration, [g g-1]
  real(r8) :: ZPOLNP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]
  real(r8) :: WTNDBN(JC,JP,JY,JX)               !branch nodule N, [g d-2]
  real(r8) :: WGSHNX(JC,JP,JY,JX)               !branch sheath structural N, [g d-2]
  real(r8) :: WTSTXN(JC,JP,JY,JX)               !branch stalk structural N, [g d-2]
  real(r8) :: WGLFNX(JC,JP,JY,JX)               !branch leaf structural N, [g d-2]

!root
  real(r8) :: ZPOOLR(2,JZ,JP,JY,JX)             !root layer nonstructural N, [g d-2]
  real(r8) :: CZPOLR(2,JZ,JP,JY,JX)             !root layer nonstructural N concentration, [g g-1]
  real(r8) :: WTRTN(JP,JY,JX)                   !total root N , [g d-2]
  real(r8) :: WTRT1N(2,JZ,JC,JP,JY,JX)          !root layer N primary axes, [g d-2]
  real(r8) :: WTRT2N(2,JZ,JC,JP,JY,JX)          !root layer N secondary axes, [g d-2]
  real(r8) :: WTNDLN(JZ,JP,JY,JX)               !root layer nodule N, [g d-2]
  real(r8) :: RTWT1N(2,JC,JP,JY,JX)             !root N primary axes, [g d-2]
  real(r8) :: WTNDN(JP,JY,JX)                   !total nodule N, [g d-2]
  real(r8) :: ZPOOLN(JZ,JP,JY,JX)               !nodule nonstructural N, [g d-2]
  real(r8) :: ZSNC(4,0:1,0:JZ,JP,JY,JX)         !litterfall N flux, [g d-2 h-1]


!Phosphorus
  real(r8) :: CFOPP(0:5,4,JP,JY,JX)             !litter P kinetic fraction, [-]
  real(r8) :: WTSHP(JP,JY,JX)                   !canopy total P, [g d-2]
  real(r8) :: PPOOLP(JP,JY,JX)                  !canopy nonstructural P, [g d-2]
  real(r8) :: WTLFP(JP,JY,JX)                   !canopy leaf P, [g d-2]
  real(r8) :: WTSHEP(JP,JY,JX)                  !canopy sheath P, [g d-2]
  real(r8) :: WTSTKP(JP,JY,JX)                  !canopy stalk P, [g d-2]
  real(r8) :: WTRSVP(JP,JY,JX)                  !canopy reserve P, [g d-2]
  real(r8) :: WTHSKP(JP,JY,JX)                  !canopy husk P, [g d-2]
  real(r8) :: WTEARP(JP,JY,JX)                  !canopy ear P, [g d-2]
  real(r8) :: WTGRNP(JP,JY,JX)                  !canopy grain P, [g d-2]
  real(r8) :: WTSHTP(JC,JP,JY,JX)               !branch total P, [g d-2]
  real(r8) :: WTLFBP(JC,JP,JY,JX)               !branch leaf P, [g d-2]
  real(r8) :: WTSHBP(JC,JP,JY,JX)               !branch sheath P, [g d-2]
  real(r8) :: WTSTBP(JC,JP,JY,JX)               !branch stalk P, [g d-2]
  real(r8) :: WTRSBP(JC,JP,JY,JX)               !branch reserve P, [g d-2]
  real(r8) :: WTHSBP(JC,JP,JY,JX)               !branch husk P, [g d-2]
  real(r8) :: WTEABP(JC,JP,JY,JX)               !branch ear P, [g d-2]
  real(r8) :: WTGRBP(JC,JP,JY,JX)               !branch grain P, [g d-2]
  real(r8) :: PPOOL(JC,JP,JY,JX)                !branch nonstructural P, [g d-2]
  real(r8) :: WGLFP(0:25,JC,JP,JY,JX)           !leaf P, [g d-2]
  real(r8) :: WGSHP(0:25,JC,JP,JY,JX)           !sheath P, [g d-2]
  real(r8) :: WGNODP(0:25,JC,JP,JY,JX)          !nodule P, [g d-2]
  real(r8) :: WGLFLP(JZ,0:25,JC,JP,JY,JX)       !leaf layer P, [g d-2]
  real(r8) :: CPPOLP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]
  real(r8) :: CPPOLB(JC,JP,JY,JX)               !branch nonstructural P concentration, [g g-1]
  real(r8) :: WTSTDP(4,JP,JY,JX)                !standing dead P fraction, [g d-2]
  real(r8) :: WTSTGP(JP,JY,JX)                  !standing dead P , [g d-2]
  real(r8) :: PPOLNB(JC,JP,JY,JX)               !branch nonstructural P concentration, [g g-1]
  real(r8) :: PPOLNP(JP,JY,JX)                  !canopy nonstructural P concentration, [g g-1]
  real(r8) :: WTNDBP(JC,JP,JY,JX)               !branch nodule P, [g d-2]
! root
  real(r8) :: PPOOLR(2,JZ,JP,JY,JX)             !root layer nonstructural P, [g d-2]
  real(r8) :: CPPOLR(2,JZ,JP,JY,JX)             !root layer nonstructural P concentration, [g g-1]
  real(r8) :: WTRTP(JP,JY,JX)                   !root total P, [g d-2]
  real(r8) :: WTRT1P(2,JZ,JC,JP,JY,JX)          !root layer P primary axes, [g d-2]
  real(r8) :: WTRT2P(2,JZ,JC,JP,JY,JX)          !root layer P secondary axes, [g d-2]
  real(r8) :: WTNDLP(JZ,JP,JY,JX)               !root layer nodule P, [g d-2]
  real(r8) :: RTWT1P(2,JC,JP,JY,JX)             !root P primary axes, [g d-2]

  real(r8) :: WTNDP(JP,JY,JX)                   !total nodule P, [g d-2]
  real(r8) :: PPOOLN(JZ,JP,JY,JX)               !nodule layer nonstructural P, [g d-2]
  real(r8) :: PSNC(4,0:1,0:JZ,JP,JY,JX)         !litterfall P flux, [g d-2 h-1]

!storage
  real(r8) :: WTRVC(JP,JY,JX)                   !plant stored nonstructural C, [g d-2]
  real(r8) :: WTRVX(JP,JY,JX)                   !plant stored nonstructural C at planting, [g d-2]
  real(r8) :: WTRVN(JP,JY,JX)                   !plant stored nonstructural N, [g d-2]
  real(r8) :: WTRVP(JP,JY,JX)                   !plant stored nonstructural P, [g d-2]

  real(r8) :: CPOOLN(JZ,JP,JY,JX)               !root  layer nonstructural N, [g d-2]
! root properties
  real(r8) :: HTCTL(JP,JY,JX)                   !cotyledon height, [m]
  real(r8) :: RTLGP(2,JZ,JP,JY,JX)              !root layer length per plant, [m p-1]
  real(r8) :: RTLG1(2,JZ,JC,JP,JY,JX)           !root layer length primary axes, [m d-2]
  real(r8) :: RTLG2(2,JZ,JC,JP,JY,JX)           !root layer length secondary axes, [m d-2]
  real(r8) :: RTDNP(2,JZ,JP,JY,JX)              !root layer length density, [m m-3]
  real(r8) :: RTN1(2,JZ,JP,JY,JX)               !root layer number primary axes, [d-2]
  real(r8) :: RTNL(2,JZ,JP,JY,JX)               !root layer number axes, [d-2]
  real(r8) :: RTN2(2,JZ,JC,JP,JY,JX)            !root layer number secondary axes, [d-2]
  real(r8) :: RTLGA(2,JZ,JP,JY,JX)              !root layer average length, [m]
  real(r8) :: RTARP(2,JZ,JP,JY,JX)              !root layer area per plant, [m p-1]
  real(r8) :: RTVLW(2,JZ,JP,JY,JX)              !root layer volume water, [m2 d-2]
  real(r8) :: RRAD1(2,JZ,JP,JY,JX)              !root layer diameter primary axes, [m ]
  real(r8) :: RTVLP(2,JZ,JP,JY,JX)              !root layer volume air, [m2 d-2]
  real(r8) :: RTDP1(2,JZ,JP,JY,JX)              !root layer depth, [m]
  real(r8) :: RRAD2(2,JZ,JP,JY,JX)              !root layer diameter secondary axes, [m ]
  real(r8) :: RTLG1X(2,JP,JY,JX)                !specific root length primary axes, [m g-1]
  real(r8) :: RTLG2X(2,JP,JY,JX)                !specific root length secondary axes, [m g-1]

! canopy auxillary variables
  real(r8) :: TKCZ(JP,JY,JX)                    !canopy temperature, [K]
  real(r8) :: RAZ(JP,JY,JX)                     !canopy roughness height, [m]
  real(r8) :: HTSTZ(JP,JY,JX)                   !canopy height, [m]
  real(r8) :: ARLF(0:25,JC,JP,JY,JX)            !leaf area, [m2 d-2]
  real(r8) :: HTSHE(0:25,JC,JP,JY,JX)           !sheath height, [m]
  real(r8) :: HTNODE(0:25,JC,JP,JY,JX)          !internode height, [m]
  real(r8) :: ARLFB(JC,JP,JY,JX)                !branch leaf area, [m2 d-2]
  real(r8) :: ARLFZ(JC,JP,JY,JX)                !branch leaf area, [m2 d-2]
  real(r8) :: HTSHEX(JC,JP,JY,JX)               !branch height, [m]
  real(r8) :: GRNOB(JC,JP,JY,JX)                !branch grain number, [d-2]
  real(r8) :: GRNXB(JC,JP,JY,JX)                !branch potential grain number, [d-2]
  real(r8) :: GRNO(JP,JY,JX)                    !canopy grain number, [d-2]
  real(r8) :: PP(JP,JY,JX)                      !plant population, [d-2]
  real(r8) :: HTNODX(0:25,JC,JP,JY,JX)          !internode height, [m]

end module PlantDataStateType
