module PlantDataRateType

  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridConsts
  implicit none
  character(len=*), private, parameter :: mod_filename = __FILE__

  real(r8) :: TCNET(JY,JX)                      !total canopy net CO2 exchange, [g d-2 h-1]
  real(r8) :: RNH3C(JP,JY,JX)                   !canopy NH3 flux, [g d-2 h-1]
  real(r8) :: TNH3C(JP,JY,JX)                   !total canopy NH3 flux, [g d-2 ]
  real(r8) :: TZSN0(JP,JY,JX)                   !total surface litterfall N, [g d-2]
  real(r8) :: TPSN0(JP,JY,JX)                   !total surface litterfall P, [g d-2]
  real(r8) :: TCSN0(JP,JY,JX)                   !total surface litterfall C, [g d-2]

  real(r8) :: RDFOMC(2,0:jcplx1,JZ,JP,JY,JX)         !root uptake (+ve) - exudation (-ve) of DOC, [g d-2 h-1]
  real(r8) :: RDFOMN(2,0:jcplx1,JZ,JP,JY,JX)         !root uptake (+ve) - exudation (-ve) of DON, [g d-2 h-1]
  real(r8) :: RDFOMP(2,0:jcplx1,JZ,JP,JY,JX)         !root uptake (+ve) - exudation (-ve) of DOP, [g d-2 h-1]
  real(r8) :: RUPNH4(2,JZ,JP,JY,JX)             !root uptake of NH4 non-band, [g d-2 h-1]
  real(r8) :: RUPNHB(2,JZ,JP,JY,JX)             !root uptake of NH4 band, [g d-2 h-1]
  real(r8) :: RUPNO3(2,JZ,JP,JY,JX)             !root uptake of NO3 non-band, [g d-2 h-1]
  real(r8) :: RUPNOB(2,JZ,JP,JY,JX)             !root uptake of NO3 band, [g d-2 h-1]
  real(r8) :: RUPH2P(2,JZ,JP,JY,JX)             !root uptake of PO4 non-band, [g d-2 h-1]
  real(r8) :: RUPH2B(2,JZ,JP,JY,JX)             !root uptake of PO4 band, [g d-2 h-1]
  real(r8) :: RUPNF(JZ,JP,JY,JX)                !root N2 fixation, [g d-2 h-1]
  real(r8) :: RUPHGS(2,JZ,JP,JY,JX)             !aqueous H2 flux from roots to soil water, [g d-2 h-1]
  real(r8) :: RUPH1P(2,JZ,JP,JY,JX)             !root uptake HPO4 non-band
  real(r8) :: RUPH1B(2,JZ,JP,JY,JX)             !root uptake of HPO4 band
  real(r8) :: RUPP2P(2,JZ,JP,JY,JX)             !root uptake of H2PO4 non-band
  real(r8) :: RUPP2B(2,JZ,JP,JY,JX)             !root uptake of H2PO4 band
  real(r8) :: RUPP1P(2,JZ,JP,JY,JX)             !HPO4 demand in non-band by each root population
  real(r8) :: RUPP1B(2,JZ,JP,JY,JX)             !HPO4 demand in band by each root population
  real(r8) :: RCZLX(JC,JP,JY,JX)                !N translocated from leaf during senescence, [g d-2 h-1]
  real(r8) :: RCPLX(JC,JP,JY,JX)                !P translocated from leaf during senescence, [g d-2 h-1]
  real(r8) :: RCCLX(JC,JP,JY,JX)                !C translocated from leaf during senescence, [g d-2 h-1]
  real(r8) :: RCZSX(JC,JP,JY,JX)                !N translocated from sheath during senescence, [g d-2 h-1]
  real(r8) :: RCPSX(JC,JP,JY,JX)                !P translocated from sheath during senescence, [g d-2 h-1]
  real(r8) :: RCCSX(JC,JP,JY,JX)                !C translocated from sheath during senescence, [g d-2 h-1]

  real(r8) :: CARBN(JP,JY,JX)                   !total gross CO2 fixation, [g d-2 ]
  real(r8) :: TCSNC(JP,JY,JX)                   !total plant C litterfall , [g d-2 ]
  real(r8) :: TZSNC(JP,JY,JX)                   !total plant N litterfall , [g d-2 ]
  real(r8) :: TPSNC(JP,JY,JX)                   !total plant P litterfall , [g d-2 ]
  real(r8) :: TZUPFX(JP,JY,JX)                  !total plant N2 fixation, [g d-2 ]
  real(r8) :: TCO2T(JP,JY,JX)                   !total plant respiration, [g d-2 ]
  real(r8) :: BALC(JP,JY,JX)                    !plant C balance, [g d-2]
  real(r8) :: BALN(JP,JY,JX)                    !plant N balance, [g d-2]
  real(r8) :: BALP(JP,JY,JX)                    !plant P balance, [g d-2]
  real(r8) :: HCSNC(JP,JY,JX)                   !plant C litterfall, [g d-2 h-1]
  real(r8) :: HZSNC(JP,JY,JX)                   !plant N litterfall, [g d-2 h-1]
  real(r8) :: HPSNC(JP,JY,JX)                   !plant C litterfall, [g d-2 h-1]
  real(r8) :: PSNC(4,0:1,0:JZ,JP,JY,JX)         !litterfall P flux, [g d-2 h-1]
  real(r8) :: ZSNC(4,0:1,0:JZ,JP,JY,JX)         !litterfall N flux, [g d-2 h-1]
  real(r8) :: CSNC(4,0:1,0:JZ,JP,JY,JX)         !plant litterfall C, [g d-2 h-1]
  real(r8) :: ZNPP(JP,JY,JX)                    !total net primary productivity, [g d-2]
  real(r8) :: CTRAN(JP,JY,JX)                   !total transpiration, [m d-2]
  real(r8) :: TCO2A(JP,JY,JX)                   !total autotrophic respiration, [g d-2 ]

  real(r8) :: HVSTC(JP,JY,JX)                   !plant C harvest, [g d-2 ]
  real(r8) :: HVSTN(JP,JY,JX)                   !plant N harvest, [g d-2 ]
  real(r8) :: HVSTP(JP,JY,JX)                   !plant P harvest, [g d-2 ]
  real(r8) :: THVSTC(JP,JY,JX)                  !total plant C harvest, [g d-2 ]
  real(r8) :: THVSTN(JP,JY,JX)                  !total plant N harvest, [g d-2 ]
  real(r8) :: THVSTP(JP,JY,JX)                  !total plant P harvest, [g d-2 ]
  real(r8) :: VCO2F(JP,JY,JX)                   !plant CO2 emission from fire, [g d-2 ]
  real(r8) :: VCH4F(JP,JY,JX)                   !plant CH4 emission from fire, [g d-2 ]
  real(r8) :: VOXYF(JP,JY,JX)                   !plant O2 uptake from fire, [g d-2 ]
  real(r8) :: VNH3F(JP,JY,JX)                   !plant NH3 emission from fire, [g d-2 ]
  real(r8) :: VN2OF(JP,JY,JX)                   !plant N2O emission from fire, [g d-2 ]
  real(r8) :: VPO4F(JP,JY,JX)                   !plant PO4 emission from fire, [g d-2 ]

  real(r8) :: ROXYP(2,JZ,JP,JY,JX)              !root  O2 demand from respiration, [g d-2 h-1]
  real(r8) :: RCOFLA(2,JZ,JP,JY,JX)             !gaseous CO2 flux through roots, [g d-2 h-1]
  real(r8) :: ROXFLA(2,JZ,JP,JY,JX)             !gaseous O2 flux through roots, [g d-2 h-1]
  real(r8) :: RCHFLA(2,JZ,JP,JY,JX)             !gaseous CH4 flux through roots, [g d-2 h-1]
  real(r8) :: RN2FLA(2,JZ,JP,JY,JX)             !gaseous N2O flux through roots, [g d-2 h-1]
  real(r8) :: RNHFLA(2,JZ,JP,JY,JX)             !gaseous NH3 flux through roots, [g d-2 h-1]
  real(r8) :: RCODFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) CO2 flux in roots, [g d-2 h-1]
  real(r8) :: ROXDFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) O2 flux in roots, [g d-2 h-1]
  real(r8) :: RCHDFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) CH4 flux in roots, [g d-2 h-1]
  real(r8) :: RN2DFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) N2O flux in roots, [g d-2 h-1]
  real(r8) :: RNHDFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) NH3 flux in roots, [g d-2 h-1]
  real(r8) :: RCO2S(2,JZ,JP,JY,JX)              !aqueous CO2 flux from roots to soil water, [g d-2 h-1]
  real(r8) :: RUPOXS(2,JZ,JP,JY,JX)             !aqueous O2 flux from roots to soil water, [g d-2 h-1]
  real(r8) :: RUPCHS(2,JZ,JP,JY,JX)             !aqueous CH4 flux from roots to soil water, [g d-2 h-1]
  real(r8) :: RUPN2S(2,JZ,JP,JY,JX)             !aqueous N2O flux from roots to soil water, [g d-2 h-1]
  real(r8) :: RUPN3S(2,JZ,JP,JY,JX)             !aqueous NH3 flux from roots to soil water non-band, [g d-2 h-1]
  real(r8) :: RUPN3B(2,JZ,JP,JY,JX)             !aqueous NH3 flux from roots to soil water band, [g d-2 h-1]
  real(r8) :: RCO2P(2,JZ,JP,JY,JX)              !aqueous CO2 flux from roots to root water , [g d-2 h-1]
  real(r8) :: RUPOXP(2,JZ,JP,JY,JX)             !aqueous O2 flux from roots to root water , [g d-2 h-1]
  real(r8) :: RCO2M(2,JZ,JP,JY,JX)              !root respiration unconstrained by O2, [g d-2 h-1]
  real(r8) :: RCO2A(2,JZ,JP,JY,JX)              !root respiration constrained by O2, [g d-2 h-1]
  real(r8) :: UPOMC(JP,JY,JX)                   !total root uptake (+ve) - exudation (-ve) of DOC, [g d-2 h-1]
  real(r8) :: UPOMN(JP,JY,JX)                   !total root uptake (+ve) - exudation (-ve) of DON, [g d-2 h-1]
  real(r8) :: UPOMP(JP,JY,JX)                   !total root uptake (+ve) - exudation (-ve) of DOP, [g d-2 h-1]
  real(r8) :: UPNH4(JP,JY,JX)                   !total root uptake of NH4, [g d-2 h-1]
  real(r8) :: UPNO3(JP,JY,JX)                   !total root uptake of NO3, [g d-2 h-1]
  real(r8) :: UPH2P(JP,JY,JX)                   !total root uptake of PO4, [g d-2 h-1]
  real(r8) :: UPH1P(JP,JY,JX)                   !total root uptake of HPO4, [g d-2 h-1]
  real(r8) :: UPNF(JP,JY,JX)                    !total root N2 fixation, [g d-2 h-1]
  real(r8) :: RCO2Z(JP,JY,JX)                   !gaseous CO2 flux fron root disturbance, [g d-2 h-1]
  real(r8) :: ROXYZ(JP,JY,JX)                   !gaseous O2 flux fron root disturbance, [g d-2 h-1]
  real(r8) :: RCH4Z(JP,JY,JX)                   !gaseous CH4 flux fron root disturbance, [g d-2 h-1]
  real(r8) :: RN2OZ(JP,JY,JX)                   !gaseous N2O flux fron root disturbance, [g d-2 h-1]

  real(r8) :: RUONH4(2,JZ,JP,JY,JX)             !root uptake of NH4 non-band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUONHB(2,JZ,JP,JY,JX)             !root uptake of NH4 band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUONO3(2,JZ,JP,JY,JX)             !root uptake of NO3 non-band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUONOB(2,JZ,JP,JY,JX)             !root uptake of NO3 band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUOH2P(2,JZ,JP,JY,JX)             !root uptake of PO4 non-band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUOH2B(2,JZ,JP,JY,JX)             !root uptake of PO4 band unconstrained by O2, [g d-2 h-1]
  real(r8) :: RUCNH4(2,JZ,JP,JY,JX)             !root uptake of NH4 non-band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUCNHB(2,JZ,JP,JY,JX)             !root uptake of NH4 band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUCNO3(2,JZ,JP,JY,JX)             !root uptake of NO3 non-band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUCNOB(2,JZ,JP,JY,JX)             !root uptake of NO3 band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUCH2P(2,JZ,JP,JY,JX)             !root uptake of PO4 non-band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUCH2B(2,JZ,JP,JY,JX)             !root uptake of PO4 band unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUOH1P(2,JZ,JP,JY,JX)             !root HPO4 uptake in non-band unlimited by O2
  real(r8) :: RUCH1P(2,JZ,JP,JY,JX)             !root HPO4 uptake in non-band unlimited by nonstructural C
  real(r8) :: RUOH1B(2,JZ,JP,JY,JX)             !root HPO4 uptake in band unlimited by O2
  real(r8) :: RUCH1B(2,JZ,JP,JY,JX)             !root HPO4 uptake in band unlimited by nonstructural C
  real(r8) :: RCO2N(2,JZ,JP,JY,JX)              !root CO2 efflux unconstrained by root nonstructural C, [g d-2 h-1]
  real(r8) :: RUNNHP(2,JZ,JP,JY,JX)             !root uptake of NH4 non-band unconstrained by NH4, [g d-2 h-1]
  real(r8) :: RUNNOP(2,JZ,JP,JY,JX)             !root uptake of NH4 band unconstrained by NH4, [g d-2 h-1]
  real(r8) :: RUNNBP(2,JZ,JP,JY,JX)             !root uptake of NO3 band unconstrained by NO3, [g d-2 h-1]
  real(r8) :: RUNNXP(2,JZ,JP,JY,JX)             !root uptake of NO3 non-band unconstrained by NO3, [g d-2 h-1]
  real(r8) :: RNH3Z(JP,JY,JX)                   !gaseous NH3 flux fron root disturbance non-band, [g d-2 h-1]
  real(r8) :: RNH3B(JC,JP,JY,JX)                !gaseous NH3 flux fron root disturbance band, [g d-2 h-1]
  real(r8) :: WFR(2,JZ,JP,JY,JX)                !O2 constraint to root respiration, []
  real(r8) :: RHGFLA(2,JZ,JP,JY,JX)             !gaseous H2 flux through roots, [g d-2 h-1]
  real(r8) :: RHGDFA(2,JZ,JP,JY,JX)             !dissolution (+ve) - volatilization (-ve) H2 flux in roots, [g d-2 h-1]

  real(r8) :: RH2GZ(JP,JY,JX)                   !gaseous H2 flux fron root disturbance, [g d-2 h-1]
  real(r8) :: TPUPTK(JP,JY,JX)                  !total net root P uptake (+ve) - exudation (-ve), [g d-2 ]
  real(r8) :: HCUPTK(JP,JY,JX)                  !net root C uptake (+ve) - exudation (-ve), [g d-2 h-1]
  real(r8) :: HZUPTK(JP,JY,JX)                  !net root N uptake (+ve) - exudation (-ve), [g d-2 h-1]
  real(r8) :: HPUPTK(JP,JY,JX)                  !net root P uptake (+ve) - exudation (-ve), [g d-2 h-1]
  real(r8) :: TCUPTK(JP,JY,JX)                  !total net root C uptake (+ve) - exudation (-ve), [g d-2 ]
  real(r8) :: TZUPTK(JP,JY,JX)                  !total net root N uptake (+ve) - exudation (-ve), [g d-2 ]

  real(r8) :: TUPWTR(0:JZ,JY,JX)                !total root water uptake, [m3 d-2]
  real(r8) :: TUPHT(0:JZ,JY,JX)                 !total root heat uptake, [MJ d-2]
  real(r8) :: TCOFLA(JZ,JY,JX)                  !total internal root CO2 flux , [g d-2 h-1]
  real(r8) :: TOXFLA(JZ,JY,JX)                  !total internal root O2 flux , [g d-2 h-1]
  real(r8) :: TCHFLA(JZ,JY,JX)                  !total internal root CH4 flux , [g d-2 h-1]
  real(r8) :: TN2FLA(JZ,JY,JX)                  !total internal root N2O flux , [g d-2 h-1]
  real(r8) :: TNHFLA(JZ,JY,JX)                  !total internal root NH3 flux , [g d-2 h-1]
  real(r8) :: TLCO2P(JZ,JY,JX)                  !total root internal CO2 flux, [g d-2 h-1]
  real(r8) :: TLOXYP(JZ,JY,JX)                  !total root internal O2 flux, [g d-2 h-1]
  real(r8) :: TLCH4P(JZ,JY,JX)                  !total root internal CH4 flux, [g d-2 h-1]
  real(r8) :: TLN2OP(JZ,JY,JX)                  !total root internal N2O flux, [g d-2 h-1]
  real(r8) :: TLNH3P(JZ,JY,JX)                  !total root internal NH3 flux, [g d-2 h-1]
  real(r8) :: TCO2S(JZ,JY,JX)                   !total root-soil CO2 flux, [g d-2 h-1]
  real(r8) :: TUPOXS(JZ,JY,JX)                  !total root-soil O2 flux, [g d-2 h-1]
  real(r8) :: TUPCHS(JZ,JY,JX)                  !total root-soil CH4 flux, [g d-2 h-1]
  real(r8) :: TUPN2S(JZ,JY,JX)                  !total root-soil N2O flux, [g d-2 h-1]
  real(r8) :: TUPN3S(JZ,JY,JX)                  !total root-soil NH3 flux non-band, [g d-2 h-1]
  real(r8) :: TUPNH4(JZ,JY,JX)                  !total root-soil NH4 flux non-band, [g d-2 h-1]
  real(r8) :: TUPNO3(JZ,JY,JX)                  !total root-soil NO3 flux non-band, [g d-2 h-1]
  real(r8) :: TUPH2P(JZ,JY,JX)                  !total root-soil PO4 flux non-band, [g d-2 h-1]
  real(r8) :: TUPN3B(JZ,JY,JX)                  !total root-soil NH3 flux band, [g d-2 h-1]
  real(r8) :: TUPNHB(JZ,JY,JX)                  !total root-soil NH4 flux band, [g d-2 h-1]
  real(r8) :: TUPNOB(JZ,JY,JX)                  !total root-soil NO3 flux band, [g d-2 h-1]
  real(r8) :: TUPH2B(JZ,JY,JX)                  !total root-soil PO4 flux band, [g d-2 h-1]
  real(r8) :: TUPNF(JZ,JY,JX)                   !total root N2 fixation, [g d-2 h-1]
  real(r8) :: TDFOMC(0:jcplx1,JZ,JY,JX)              !total root C exchange, [g d-2 h-1]
  real(r8) :: TDFOMN(0:jcplx1,JZ,JY,JX)              !total root N exchange, [g d-2 h-1]
  real(r8) :: TDFOMP(0:jcplx1,JZ,JY,JX)              !total root P exchange, [g d-2 h-1]

  real(r8) :: TCO2P(JZ,JY,JX)                   !total root CO2 flux, [g d-2 h-1]
  real(r8) :: TUPOXP(JZ,JY,JX)                  !total root internal O2 flux, [g d-2 h-1]
  real(r8) :: RTDNT(JZ,JY,JX)                   !total root length density, [m m-3]
  real(r8) :: TUPH1P(JZ,JY,JX)                  !soil-root exch of HPO4 in non-band
  real(r8) :: TUPH1B(JZ,JY,JX)                  !soil-root exch of HPO4 in band
  real(r8) :: ROXYX(0:JZ,JY,JX)                 !total root + microbial O2 uptake, [g d-2 h-1]
  real(r8) :: ROXYY(0:JZ,JY,JX)                 !total root + microbial O2 uptake, [g d-2 h-1]
  real(r8) :: RNH4X(0:JZ,JY,JX)                 !total root + microbial NH4 uptake non-band, [g d-2 h-1]
  real(r8) :: RNH4Y(0:JZ,JY,JX)                 !total root + microbial NH4 uptake non-band, [g d-2 h-1]
  real(r8) :: RNO3X(0:JZ,JY,JX)                 !total root + microbial NO3 uptake non-band, [g d-2 h-1]
  real(r8) :: RNO3Y(0:JZ,JY,JX)                 !total root + microbial NO3 uptake non-band, [g d-2 h-1]
  real(r8) :: RNO2X(0:JZ,JY,JX)                 !total root + microbial NO2 uptake non-band, [g d-2 h-1]
  real(r8) :: RNO2Y(0:JZ,JY,JX)                 !total root + microbial NO2 uptake non-band, [g d-2 h-1]
  real(r8) :: RPO4X(0:JZ,JY,JX)                 !total root + microbial PO4 uptake non-band, [g d-2 h-1]
  real(r8) :: RPO4Y(0:JZ,JY,JX)                 !total root + microbial PO4 uptake non-band, [g d-2 h-1]
  real(r8) :: RN2OX(0:JZ,JY,JX)                 !total root + microbial N2O uptake , [g d-2 h-1]
  real(r8) :: RN2OY(0:JZ,JY,JX)                 !total root + microbial N2O uptake, [g d-2 h-1]
  real(r8) :: RNHBX(0:JZ,JY,JX)                 !total root + microbial NH4 uptake band, [g d-2 h-1]
  real(r8) :: RNHBY(0:JZ,JY,JX)                 !total root + microbial NH4 uptake band, [g d-2 h-1]
  real(r8) :: RN3BX(0:JZ,JY,JX)                 !total root + microbial NO3 uptake band, [g d-2 h-1]
  real(r8) :: RN3BY(0:JZ,JY,JX)                 !total root + microbial NO3 uptake band, [g d-2 h-1]
  real(r8) :: RN2BX(0:JZ,JY,JX)                 !total root + microbial NO2 uptake band, [g d-2 h-1]
  real(r8) :: RN2BY(0:JZ,JY,JX)                 !total root + microbial NO2 uptake band, [g d-2 h-1]
  real(r8) :: RPOBX(0:JZ,JY,JX)                 !total root + microbial PO4 uptake band, [g d-2 h-1]
  real(r8) :: RPOBY(0:JZ,JY,JX)                 !total root + microbial PO4 uptake band, [g d-2 h-1]
  real(r8) :: ROQCX(0:jcplx1,0:JZ,JY,JX)             !total root + microbial DOC uptake, [g d-2 h-1]
  real(r8) :: ROQCY(0:jcplx1,0:JZ,JY,JX)             !total root + microbial DOC uptake, [g d-2 h-1]
  real(r8) :: ROQAX(0:jcplx1,0:JZ,JY,JX)             !total root + microbial acetate uptake, [g d-2 h-1]
  real(r8) :: ROQAY(0:jcplx1,0:JZ,JY,JX)             !total root + microbial acetate uptake, [g d-2 h-1]
  real(r8) :: TH2GZ(JY,JX)                      !total root H2 flux, [g d-2]
  real(r8) :: TUPHGS(JZ,JY,JX)                  !total root-soil H2 flux, [g d-2 h-1]
  real(r8) :: THGFLA(JZ,JY,JX)                  !total root-atmosphere H2 flux, [g d-2 h-1]
  real(r8) :: TLH2GP(JZ,JY,JX)                  !total root-soil H2 flux, [g d-2 h-1]

end module PlantDataRateType
