module PlantDataCharType

!
!!
! data types of plant characteristics
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridDataType
  implicit none
  character(len=*), private, parameter :: mod_filename = __FILE__

! canopy auxillary variables

  real(r8) :: DMVL(2,JP,JY,JX)                  !root volume:mass ratio, [m3 g-1]
  real(r8) :: RRAD1X(2,JP,JY,JX)                !root diameter primary axes, [m]
  real(r8) :: RRAD2X(2,JP,JY,JX)                !root diameter secondary axes, [m]
  real(r8) :: RTAR1X(2,JP,JY,JX)                !root cross-sectional area primary axes, [m2]
  real(r8) :: RTAR2X(2,JP,JY,JX)                !root  cross-sectional area  secondary axes, [m2]

  real(r8) :: TFN4(JZ,JP,JY,JX)                 !root layer temperature growth functiom, [-]

! photosynthesis characteristics
  real(r8) :: O2I(JP,JY,JX)                     !leaf gaseous O2 concentration, [umol m-3]
  real(r8) :: CO2I(JP,JY,JX)                    !leaf gaseous CO2 concentration, [umol m-3]
  real(r8) :: DCO2(JP,JY,JX)                    !gaesous CO2 concentration difference across stomates, [umol m-3]
  real(r8) :: CO2Q(JP,JY,JX)                    !canopy gaesous CO2 concentration , [umol mol-1]
  real(r8) :: CO2L(JP,JY,JX)                    !leaf aqueous CO2 concentration, [uM]
  real(r8) :: O2L(JP,JY,JX)                     !leaf aqueous O2 concentration, [uM]
  real(r8) :: SCO2(JP,JY,JX)                    !leaf CO2 solubility, [uM /umol mol-1]
  real(r8) :: SO2(JP,JY,JX)                     !leaf O2 solubility, [uM /umol mol-1]
  real(r8) :: XKCO2L(JP,JY,JX)                  !leaf aqueous CO2 Km no O2, [uM]
  real(r8) :: XKCO2O(JP,JY,JX)                  !leaf aqueous CO2 Km ambient O2, [uM]
  real(r8) :: TFN3(JP,JY,JX)                    !canopy temperature growth functiom, [-]
  real(r8) :: SURFB(4,JZ,JC,JP,JY,JX)           !stem surface area, [m2 d-2]
  real(r8) :: TCC(JP,JY,JX)                     !canopy temperature, [oC]
  real(r8) :: TCG(JP,JY,JX)                     !canopy growth temperature, [oC]
  real(r8) :: TKC(JP,JY,JX)                     !canopy temperature, [K]
  real(r8) :: ARSTK(JZ,JC,JP,JY,JX)             !stem layer area, [m2 d-2]
  real(r8) :: TKG(JP,JY,JX)                     !canopy growth temperature, [K]
  real(r8) :: DTKC(JP,JY,JX)                    !change in canopy temperature, [K]
  real(r8) :: CHILL(JP,JY,JX)                   !chilling effect on CO2 fixation, [-]
  real(r8) :: FLWC(JP,JY,JX)                    !water flux into canopy, [m3 d-2 h-1]
  real(r8) :: VOLWC(JP,JY,JX)                   !canopy surface water content, [m3 d-2]
  real(r8) :: PARDIF(4,4,JZ,JP,JY,JX)           !diffuse incoming PAR, [umol m-2 s-1]
  real(r8) :: PAR(4,4,JZ,JP,JY,JX)              !direct incoming PAR, [umol m-2 s-1]
  real(r8) :: RADC(JP,JY,JX)                    !canopy absorbed shortwave radiation , [MJ d-2 h-1]
  real(r8) :: RADP(JP,JY,JX)                    !canopy absorbed PAR , [umol m-2 s-1]
  real(r8) :: FRADP(JP,JY,JX)                   !fraction of incoming PAR absorbed by canopy, [-]
  real(r8) :: SURF(4,JZ,25,JC,JP,JY,JX)         !leaf surface area, [m2 d-2]
  real(r8) :: SURFX(4,JZ,25,JC,JP,JY,JX)        !leaf irradiated surface area, [m2 d-2]
  real(r8) :: VCGRO(25,JC,JP,JY,JX)             !maximum dark carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: VGRO(25,JC,JP,JY,JX)              !carboxylation rate, [umol m-2 s-1]
  real(r8) :: COMPL(25,JC,JP,JY,JX)             !CO2 compensation point, [uM]
  real(r8) :: ETGRO(25,JC,JP,JY,JX)             !maximum light carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: CBXN(25,JC,JP,JY,JX)              !carboxylation efficiency, [umol umol-1]
  real(r8) :: FMOL(JP,JY,JX)                    !total gas concentration, [mol m-3]
  real(r8) :: CPOOL3(25,JC,JP,JY,JX)            !minimum sink strength for nonstructural C transfer, [g d-2]
  real(r8) :: CO2B(25,JC,JP,JY,JX)              !bundle sheath nonstructural C3 content in C4 photosynthesis, [g d-2]
  real(r8) :: VCGR4(25,JC,JP,JY,JX)             !maximum dark C4 carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: VGRO4(25,JC,JP,JY,JX)             !C4 carboxylation rate, [umol m-2 s-1]
  real(r8) :: ETGR4(25,JC,JP,JY,JX)             !maximum  light C4 carboxylation rate under saturating CO2, [umol m-2 s-1]
  real(r8) :: CBXN4(25,JC,JP,JY,JX)             !C4 carboxylation efficiency, [umol umol-1]
  real(r8) :: CPOOL4(25,JC,JP,JY,JX)            !leaf nonstructural C4 content in C4 photosynthesis, [g d-2]
  real(r8) :: HCOB(25,JC,JP,JY,JX)              !bundle sheath nonstructural C3 content in C4 photosynthesis, [g d-2]
  real(r8) :: ARLFP(JP,JY,JX)                   !plant leaf area, [m2 d-2]
  real(r8) :: ARSTP(JP,JY,JX)                   !plant stem area, [m2 d-2]
  real(r8) :: ARLFS(JP,JY,JX)                   !plant leaf area, [m2 d-2]
  real(r8) :: ZC(JP,JY,JX)                      !canopy height, [m]
  real(r8) :: FDBK(JC,JP,JY,JX)                 !branch down-regulation of CO2 fixation, [-]
  real(r8) :: FDBK4(25,JC,JP,JY,JX)             !down-regulation of C4 photosynthesis, [-]
  real(r8) :: FDBKX(JC,JP,JY,JX)                !down-regulation of C4 photosynthesis, [-]

  real(r8) :: BETA(4,4)                         !sine of direct solar radiation on leaf surface, [-]
  real(r8) :: BETX(4,4)                         !sine of direct solar radiation on leaf surface/sine of direct solar radiation, [-]
  real(r8) :: TAU0(JC+1,JY,JX)                  !fraction of radiation transmitted by canopy layer, [-]
  real(r8) :: TAUS(JC+1,JY,JX)                  !fraction of radiation intercepted by canopy layer, [-]
  real(r8) :: FRADG(JY,JX)                      !fraction of radiation intercepted by ground surface, [-]
  real(r8) :: RADG(JY,JX)                       !radiation intercepted by ground surface, [MJ m-2 h-1]
  real(r8) :: THRMCX(JY,JX)                     !longwave radiation emitted by canopy, [MJ m-2 h-1]
  real(r8) :: THRMGX(JY,JX)                     !longwave radiation emitted by ground surface, [MJ m-2 h-1]
  real(r8) :: ARLFX(JY,JX)                      !total canopy leaf area, [m2 d-2]
  real(r8) :: ARSTX(JY,JX)                      !total canopy stem area, [m2 d-2]
  real(r8) :: CNETX(JY,JX)                      !total net canopy CO2 exchange, [g d-2 h-1]
  real(r8) :: ZT(JY,JX)                         !canopy height , [m]
  real(r8) :: ZL(0:JC,JY,JX)                    !canopy layer height , [m]

  real(r8) :: CNLF(JP,JY,JX)                    !maximum leaf N:C ratio, [g g-1]
  real(r8) :: CNSHE(JP,JY,JX)                   !sheath N:C ratio, [g g-1]
  real(r8) :: CNSTK(JP,JY,JX)                   !stalk N:C ratio, [g g-1]
  real(r8) :: CNRSV(JP,JY,JX)                   !reserve N:C ratio, [g g-1]
  real(r8) :: CNHSK(JP,JY,JX)                   !husk N:C ratio, [g g-1]
  real(r8) :: CNEAR(JP,JY,JX)                   !ear N:C ratio, [g g-1]
  real(r8) :: CNGR(JP,JY,JX)                    !grain N:C ratio, [g g-1]
  real(r8) :: CNRT(JP,JY,JX)                    !root N:C ratio, [g g-1]
  real(r8) :: CNND(JP,JY,JX)                    !nodule N:C ratio, [g g-1]
  real(r8) :: CPLF(JP,JY,JX)                    !maximum leaf P:C ratio, [g g-1]
  real(r8) :: CPSHE(JP,JY,JX)                   !sheath P:C ratio, [g g-1]
  real(r8) :: CPSTK(JP,JY,JX)                   !stalk P:C ratio, [g g-1]
  real(r8) :: CPRSV(JP,JY,JX)                   !reserve P:C ratio, [g g-1]
  real(r8) :: CPHSK(JP,JY,JX)                   !husk P:C ratio, [g g-1]
  real(r8) :: CPEAR(JP,JY,JX)                   !ear P:C ratio, [g g-1]
  real(r8) :: CPGR(JP,JY,JX)                    !grain P:C ratio, [g g-1]
  real(r8) :: CPRT(JP,JY,JX)                    !root P:C ratio, [g g-1]
  real(r8) :: CPND(JP,JY,JX)                    !nodule P:C ratio, [g g-1]
  real(r8) :: VCMX(JP,JY,JX)                    !rubisco carboxylase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: VOMX(JP,JY,JX)                    !rubisco oxygenase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: VCMX4(JP,JY,JX)                   !PEP carboxylase activity, [umol g-1 h-1 at 25 oC]
  real(r8) :: XKCO2(JP,JY,JX)                   !Km for rubisco carboxylase activity, [uM]
  real(r8) :: XKO2(JP,JY,JX)                    !Km for rubisco oxygenase activity, [uM]
  real(r8) :: XKCO24(JP,JY,JX)                  !Km for PEP carboxylase activity, [uM]
  real(r8) :: RUBP(JP,JY,JX)                    !leaf rubisco content, [g g-1]
  real(r8) :: PEPC(JP,JY,JX)                    !leaf PEP carboxylase content, [g g-1]
  real(r8) :: ETMX(JP,JY,JX)                    !cholorophyll activity , [umol g-1 h-1 at 25 oC]
  real(r8) :: CHL(JP,JY,JX)                     !leaf C3 chlorophyll content, [g g-1]
  real(r8) :: CHL4(JP,JY,JX)                    !leaf C4 chlorophyll content, [g g-1]

  real(r8) :: FCO2(JP,JY,JX)                    !Ci:Ca ratio, [-]
  real(r8) :: RSMX(JP,JY,JX)                    !maximum stomatal resistance to vapor, [s m-1]
  real(r8) :: RCMX(JP,JY,JX)                    !maximum stomatal resistance to CO2, [s h-1]
  real(r8) :: RSMH(JP,JY,JX)                    !maximum stomatal resistance to vapor, [s h-1]
  real(r8) :: CLASS(4,JP,JY,JX)                 !fractionction of leaves in different angle classes, [-]

  real(r8) :: PORT(2,JP,JY,JX)                  !root porosity, [m3 m-3]
  real(r8) :: RSRR(2,JP,JY,JX)                  !root radial resistivity, [MPa h m-2]
  real(r8) :: RSRA(2,JP,JY,JX)                  !root axial resistivity, [MPa h m-4]
  real(r8) :: PTSHT(JP,JY,JX)                   !shoot-root rate constant for nonstructural C exchange, [h-1]
  real(r8) :: UPMXZH(2,JP,JY,JX)                !maximum root NH4 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMZH(2,JP,JY,JX)                !Km for root NH4 uptake, [g m-3]
  real(r8) :: UPMNZH(2,JP,JY,JX)                !minimum NH4 concentration for root NH4 uptake, [g m-3]
  real(r8) :: UPMXZO(2,JP,JY,JX)                !maximum root NO3 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMZO(2,JP,JY,JX)                !Km for root NO3 uptake, [g m-3]
  real(r8) :: UPMNZO(2,JP,JY,JX)                !minimum NO3 concentration for root NH4 uptake, [g m-3]
  real(r8) :: UPMXPO(2,JP,JY,JX)                !maximum root PO4 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMPO(2,JP,JY,JX)                !Km for root PO4 uptake, [g m-3]
  real(r8) :: UPMNPO(2,JP,JY,JX)                !minimum PO4 concentration for root NH4 uptake, [g m-3]
  real(r8) :: RRADP(2,JP,JY,JX)                 !root internal radius, [m]
  real(r8) :: CNRTS(JP,JY,JX)                   !root N:C ratio x root growth yield, [-]
  real(r8) :: CPRTS(JP,JY,JX)                   !root P:C ratio x root growth yield, [-]


  real(r8) :: ALBR(JP,JY,JX)                    !canopy shortwave albedo , [-]
  real(r8) :: ALBP(JP,JY,JX)                    !canopy PAR albedo , [-]
  real(r8) :: TAUR(JP,JY,JX)                    !canopy shortwave transmissivity , [-]
  real(r8) :: TAUP(JP,JY,JX)                    !canopy PAR transmissivity , [-]
  real(r8) :: ABSR(JP,JY,JX)                    !canopy shortwave absorptivity , [-]
  real(r8) :: ABSP(JP,JY,JX)                    !canopy PAR absorptivity , [-]


  real(r8) :: OSMO(JP,JY,JX)                    !canopy osmotic potential when canopy water potential = 0 MPa, [MPa]
  real(r8) :: RCS(JP,JY,JX)                     !shape parameter for calculating stomatal resistance from turgor pressure, [-]
  real(r8) :: RRAD1M(2,JP,JY,JX)                !maximum radius of primary roots, [m]
  real(r8) :: RRAD2M(2,JP,JY,JX)                !maximum radius of secondary roots, [m]
  real(r8) :: TCX(JP,JY,JX)                     !threshold temperature for autumn leafoff/hardening, [oC]
  real(r8) :: ZTYPI(JP,JY,JX)                   !intial plant thermal adaptation zone, [-]
  real(r8) :: ZTYP(JP,JY,JX)                    !plant thermal adaptation zone, [-]

  real(r8) :: GROUPI(JP,JY,JX)                  !acclimated plant maturity group, [-]
  real(r8) :: PPI(JP,JY,JX)                     !initial plant population, [m-2]
  real(r8) :: GROUPX(JP,JY,JX)                  !initial plant maturity group, [-]
  real(r8) :: RTFQ(JP,JY,JX)                    !root brancing frequency, [m-1]
  real(r8) :: SDPTH(JP,JY,JX)                   !seeding depth, [m]
  real(r8) :: SDVL(JP,JY,JX)                    !seed volume, [m3 ]
  real(r8) :: SDLG(JP,JY,JX)                    !seed length, [m]
  real(r8) :: SDAR(JP,JY,JX)                    !seed surface area, [m2]
  real(r8) :: ANGBR(JP,JY,JX)                   !branching angle, [degree from horizontal]
  real(r8) :: ANGSH(JP,JY,JX)                   !sheath angle, [degree from horizontal]
  real(r8) :: CNWS(JP,JY,JX)                    !C:N ratio in remobilizable nonstructural biomass, [-]
  real(r8) :: CPWS(JP,JY,JX)                    !C:P ratio in remobilizable nonstructural biomass, [-]
  real(r8) :: CWSRT(JP,JY,JX)                   !fraction of remobilizable nonstructural biomass in root, [-]
  real(r8) :: WTSTDI(JP,JY,JX)                  !initial standing dead C, [g C m-2]
  real(r8) :: PPX(JP,JY,JX)                     !plant population, [m-2]
  real(r8) :: PORTX(2,JP,JY,JX)                 !power function of root porosity used to calculate root gaseous diffusivity, [-]
  real(r8) :: WSTR(JP,JY,JX)                    !plant water stress indicator, []
  real(r8) :: OSTR(JP,JY,JX)                    !plant O2 stress indicator, []
  real(r8) :: PPT(JY,JX)                        !total plant population, [d-2]
  integer :: IFLGT(JY,JX)                       !number of active PFT
end module PlantDataCharType
