module RootDataType

!
!!
! data types of plant characteristics
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridConsts
  implicit none
  character(len=*), private, parameter :: mod_filename = __FILE__

  integer :: NRT(JP,JY,JX)                      !root primary axis number, [-]
  integer :: NINR(JC,JP,JY,JX)                  !maximum soil layer number for root axes, [-]
  integer :: IDTHR(JP,JY,JX)                    !flag to detect root system death , [-]
  integer :: NIX(JP,JY,JX)                      !maximum soil layer number for all root axes, [-]
  integer :: NI(JP,JY,JX)                       !maximum soil layer number for all root axes, [-]
  real(r8) :: DMRT(JP,JY,JX)                    !root growth yield, [g g-1]
  real(r8) :: PR(JP,JY,JX)                      !threshold root nonstructural C content for initiating new root axis, [g g-1]
  real(r8) :: CWSRT(JP,JY,JX)                   !fraction of remobilizable nonstructural biomass in root, [-]
  real(r8) :: DMVL(2,JP,JY,JX)                  !root volume:mass ratio, [m3 g-1]
  real(r8) :: RRAD1X(2,JP,JY,JX)                !root diameter primary axes, [m]
  real(r8) :: RRAD2X(2,JP,JY,JX)                !root diameter secondary axes, [m]
  real(r8) :: RTAR1X(2,JP,JY,JX)                !root cross-sectional area primary axes, [m2]
  real(r8) :: RTAR2X(2,JP,JY,JX)                !root  cross-sectional area  secondary axes, [m2]
  real(r8) :: TFN4(JZ,JP,JY,JX)                 !root layer temperature growth functiom, [-]
  real(r8) :: CNRT(JP,JY,JX)                    !root N:C ratio, [g g-1]
  real(r8) :: CPRT(JP,JY,JX)                    !root P:C ratio, [g g-1]
  real(r8) :: PORT(2,JP,JY,JX)                  !root porosity, [m3 m-3]
  real(r8) :: RSRR(2,JP,JY,JX)                  !root radial resistivity, [MPa h m-2]
  real(r8) :: RSRA(2,JP,JY,JX)                  !root axial resistivity, [MPa h m-4]
  real(r8) :: PTSHT(JP,JY,JX)                   !shoot-root rate constant for nonstructural C exchange, [h-1]
  real(r8) :: UPMXZH(2,JP,JY,JX)                !maximum root NH4 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMZH(2,JP,JY,JX)                !Km for root NH4 uptake, [g m-3]
  real(r8) :: UPMNZH(2,JP,JY,JX)                !minimum NH4 concentration for root NH4 uptake, [g m-3]
  real(r8) :: UPMXZO(2,JP,JY,JX)                !maximum root NO3 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMZO(2,JP,JY,JX)                !Km for root NO3 uptake, [g m-3]
  real(r8) :: UPMNZO(2,JP,JY,JX)                !minimum NO3 concentration for root NH4 uptake, [g m-3]
  real(r8) :: UPMXPO(2,JP,JY,JX)                !maximum root PO4 uptake rate, [g m-2 h-1]
  real(r8) :: UPKMPO(2,JP,JY,JX)                !Km for root PO4 uptake, [g m-3]
  real(r8) :: UPMNPO(2,JP,JY,JX)                !minimum PO4 concentration for root NH4 uptake, [g m-3]
  real(r8) :: RRADP(2,JP,JY,JX)                 !root internal radius, [m]
  real(r8) :: CNRTS(JP,JY,JX)                   !root N:C ratio x root growth yield, [-]
  real(r8) :: CPRTS(JP,JY,JX)                   !root P:C ratio x root growth yield, [-]
  real(r8) :: RRAD1M(2,JP,JY,JX)                !maximum radius of primary roots, [m]
  real(r8) :: RRAD2M(2,JP,JY,JX)                !maximum radius of secondary roots, [m]
  real(r8) :: RTFQ(JP,JY,JX)                    !root brancing frequency, [m-1]
  real(r8) :: PORTX(2,JP,JY,JX)                 !power function of root porosity used to calculate root gaseous diffusivity, [-]
! root
  real(r8) :: PPOOLR(2,JZ,JP,JY,JX)             !root layer nonstructural P, [g d-2]
  real(r8) :: CPPOLR(2,JZ,JP,JY,JX)             !root layer nonstructural P concentration, [g g-1]
  real(r8) :: WTRTP(JP,JY,JX)                   !root total P, [g d-2]
  real(r8) :: WTRT1P(2,JZ,JC,JP,JY,JX)          !root layer P primary axes, [g d-2]
  real(r8) :: WTRT2P(2,JZ,JC,JP,JY,JX)          !root layer P secondary axes, [g d-2]
  real(r8) :: WTNDLP(JZ,JP,JY,JX)               !root layer nodule P, [g d-2]
  real(r8) :: PPOOLN(JZ,JP,JY,JX)               !nodule layer nonstructural P, [g d-2]
  real(r8) :: ZPOOLN(JZ,JP,JY,JX)               !root nodule nonstructural N, [g d-2]
  real(r8) :: RTWT1P(2,JC,JP,JY,JX)             !root P primary axes, [g d-2]
  real(r8) :: ZPOOLR(2,JZ,JP,JY,JX)             !root layer nonstructural N, [g d-2]
  real(r8) :: CZPOLR(2,JZ,JP,JY,JX)             !root layer nonstructural N concentration, [g g-1]
  real(r8) :: WTRTN(JP,JY,JX)                   !total root N , [g d-2]
  real(r8) :: WTRT1N(2,JZ,JC,JP,JY,JX)          !root layer N primary axes, [g d-2]
  real(r8) :: WTRT2N(2,JZ,JC,JP,JY,JX)          !root layer N secondary axes, [g d-2]
  real(r8) :: WTNDLN(JZ,JP,JY,JX)               !root layer nodule N, [g d-2]
  real(r8) :: RTWT1N(2,JC,JP,JY,JX)             !root N primary axes, [g d-2]
  real(r8) :: CPOOLN(JZ,JP,JY,JX)               !root  layer nonstructural N, [g d-2]
  real(r8) :: RTLGP(2,JZ,JP,JY,JX)              !root layer length per plant, [m p-1]
  real(r8) :: RTLG1(2,JZ,JC,JP,JY,JX)           !root layer length primary axes, [m d-2]
  real(r8) :: RTLG2(2,JZ,JC,JP,JY,JX)           !root layer length secondary axes, [m d-2]
  real(r8) :: RTDNP(2,JZ,JP,JY,JX)              !root layer length density, [m m-3]
  real(r8) :: RTN1(2,JZ,JP,JY,JX)               !root layer number primary axes, [d-2]
  real(r8) :: RTNL(2,JZ,JP,JY,JX)               !root layer number axes, [d-2]
  real(r8) :: RTN2(2,JZ,JC,JP,JY,JX)            !root layer number secondary axes, [d-2]
  real(r8) :: RTLGA(2,JZ,JP,JY,JX)              !root layer average length, [m]
  real(r8) :: RTARP(2,JZ,JP,JY,JX)              !root layer area per plant, [m p-1]
  real(r8) :: RTVLW(2,JZ,JP,JY,JX)              !root layer volume water, [m2 d-2]
  real(r8) :: RRAD1(2,JZ,JP,JY,JX)              !root layer diameter primary axes, [m ]
  real(r8) :: RTVLP(2,JZ,JP,JY,JX)              !root layer volume air, [m2 d-2]
  real(r8) :: RTDP1(2,JC,JP,JY,JX)              !root layer depth, [m]
  real(r8) :: RRAD2(2,JZ,JP,JY,JX)              !root layer diameter secondary axes, [m ]
  real(r8) :: RTLG1X(2,JP,JY,JX)                !specific root length primary axes, [m g-1]
  real(r8) :: RTLG2X(2,JP,JY,JX)                !specific root length secondary axes, [m g-1]

  real(r8) :: UPWTR(2,JZ,JP,JY,JX)              !root water uptake, [m2 d-2 h-1]
  real(r8) :: PSIRT(2,JZ,JP,JY,JX)              !root total water potential , [Mpa]
  real(r8) :: PSIRO(2,JZ,JP,JY,JX)              !root osmotic water potential , [Mpa]
  real(r8) :: PSIRG(2,JZ,JP,JY,JX)              !root turgor water potential , [Mpa]
  real(r8) :: CO2A(2,JZ,JP,JY,JX)               !root gaseous CO2 content, [g d-2 ]
  real(r8) :: OXYA(2,JZ,JP,JY,JX)               !root gaseous O2 content, [g d-2 ]
  real(r8) :: CH4A(2,JZ,JP,JY,JX)               !root gaseous CH4 content, [g d-2 ]
  real(r8) :: Z2OA(2,JZ,JP,JY,JX)               !root gaseous N2O content, [g d-2 ]
  real(r8) :: ZH3A(2,JZ,JP,JY,JX)               !root gaseous NH3 content, [g d-2 ]
  real(r8) :: CO2P(2,JZ,JP,JY,JX)               !root aqueous CO2 content, [g d-2 ]
  real(r8) :: OXYP(2,JZ,JP,JY,JX)               !root aqueous O2 content, [g d-2 ]
  real(r8) :: CH4P(2,JZ,JP,JY,JX)               !root aqueous CH4 content, [g d-2 ]
  real(r8) :: Z2OP(2,JZ,JP,JY,JX)               !root aqueous N2O content, [g d-2 ]
  real(r8) :: ZH3P(2,JZ,JP,JY,JX)               !root aqueous NH3 content, [g d-2 ]
  real(r8) :: TCO2Z(JY,JX)                      !total root CO2 content, [g d-2]
  real(r8) :: TOXYZ(JY,JX)                      !total root O2 content, [g d-2]
  real(r8) :: TCH4Z(JY,JX)                      !total root CH4 content, [g d-2]
  real(r8) :: TN2OZ(JY,JX)                      !total root N2O content, [g d-2]
  real(r8) :: TNH3Z(JY,JX)                      !total root NH3 content, [g d-2]
  real(r8) :: H2GA(2,JZ,JP,JY,JX)               !gaseous H2 content of roots, [g d-2]
  real(r8) :: H2GP(2,JZ,JP,JY,JX)               !aqueous H2 content of roots, [g d-2]

  real(r8) :: WTRTA(JP,JY,JX)                   !root C per plant, [g p-1]
  real(r8) :: WTRT(JP,JY,JX)                    !plant root C, [g d-2]
  real(r8) :: WTRTS(JP,JY,JX)                   !plant root structural C, [g d-2]
  real(r8) :: WSRTL(2,JZ,JP,JY,JX)              !root layer protein C, [g d-2]
  real(r8) :: WTRT1(2,JZ,JC,JP,JY,JX)           !root layer C primary axes, [g d-2]
  real(r8) :: WTRT2(2,JZ,JC,JP,JY,JX)           !root layer C secondary axes, [g d-2]
  real(r8) :: WTRTD(2,JZ,JP,JY,JX)              !root layer C, [g d-2]
  real(r8) :: WTNDL(JZ,JP,JY,JX)                !root layer nodule mass, [g d-2]
  real(r8) :: WTND(JP,JY,JX)                    !root total nodule mass, [g d-2]
  real(r8) :: WTRTL(2,JZ,JP,JY,JX)              !root layer structural C, [g d-2]
  real(r8) :: CPOOLR(2,JZ,JP,JY,JX)             !root  layer nonstructural C, [g d-2]
  real(r8) :: CCPOLR(2,JZ,JP,JY,JX)             !root  layer nonstructural C concentration, [g g-1]
  real(r8) :: RTWT1(2,JC,JP,JY,JX)              !root C primary axes, [g d-2]
  real(r8) :: CWSRTL(2,JZ,JP,JY,JX)             !root layer protein C concentration, [g g-1]
end module RootDataType
