module SoilBGCDataType

!
! USES:
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridDataType
implicit none
! biological and chemical rates
  real(r8) :: XNO2S(0:JZ,JY,JX)                 !total NO2 exchange, [g d-2 h-1]
  real(r8) :: RUPOXO(0:JZ,JY,JX)                !microbial O2 uptake, [g d-2 h-1]
  real(r8) :: RCO2O(0:JZ,JY,JX)                 !microbial net CO2 exchange, [g d-2 h-1]
  real(r8) :: RCH4O(0:JZ,JY,JX)                 !microbial net CH4 exchange, [g d-2 h-1]
  real(r8) :: RH2GO(0:JZ,JY,JX)                 !microbial net H2 exchange, [g d-2 h-1]
  real(r8) :: RN2G(0:JZ,JY,JX)                  !microbial net N2 exchange, [g d-2 h-1]
  real(r8) :: RN2O(0:JZ,JY,JX)                  !microbial net N2O exchange, [g d-2 h-1]
  real(r8) :: XNO2B(0:JZ,JY,JX)
  real(r8) :: XNH4B(0:JZ,JY,JX)                 !net microbial NH4 exchange band, [g d-2 h-1]
  real(r8) :: XNO3B(0:JZ,JY,JX)                 !net microbial NO3 exchange band, [g d-2 h-1]
  real(r8) :: XH2BS(0:JZ,JY,JX)                 !net microbial PO4 exchange band, [g d-2 h-1]
  real(r8) :: XH1BS(0:JZ,JY,JX)
  real(r8) :: XN2GS(0:JZ,JY,JX)                 !net microbial N2 exchange, [g d-2 h-1]
  real(r8) :: XH1PS(0:JZ,JY,JX)
  real(r8) :: XH2PS(0:JZ,JY,JX)                 !net microbial PO4 exchange nonband, [g d-2 h-1]
  real(r8) :: XNH4S(0:JZ,JY,JX)                 !net microbial NH4 exchange non-band, [g d-2 h-1]
  real(r8) :: XNO3S(0:JZ,JY,JX)                 !net microbial NO3 exchange non-band, [g d-2 h-1]
  real(r8) :: XOQCS(0:4,0:JZ,JY,JX)             !net microbial DOC flux, [g d-2 h-1]
  real(r8) :: XOQNS(0:4,0:JZ,JY,JX)             !net microbial DON flux, [g d-2 h-1]
  real(r8) :: XOQPS(0:4,0:JZ,JY,JX)             !net microbial DOP flux, [g d-2 h-1]
  real(r8) :: XOQAS(0:4,0:JZ,JY,JX)             !net microbial acetate flux, [g d-2 h-1]
  real(r8) :: TOQCK(0:JZ,JY,JX)
  real(r8) :: VOLQ(0:JZ,JY,JX)                  !soil water volume occupied by microial biomass, [m3 m-3]
  real(r8) :: TFNQ(0:JZ,JY,JX)                  !constraints of temperature and water potential on microbial activity, []
  real(r8) :: CSNT(4,0:1,0:JZ,JY,JX)            !total litterfall C, [g d-2 h-1]
  real(r8) :: ZSNT(4,0:1,0:JZ,JY,JX)            !total litterfall N, [g d-2 h-1]
  real(r8) :: PSNT(4,0:1,0:JZ,JY,JX)            !total litterfall P, [g d-2 h-1]

  real(r8) :: VLNH4(0:JZ,JY,JX)                 !NH4 non-band volume fracrion, []
  real(r8) :: VLNHB(0:JZ,JY,JX)                 !NH4 band volume fracrion, []
  real(r8) :: VLNO3(0:JZ,JY,JX)                 !NO3 non-band volume fracrion, []
  real(r8) :: VLNOB(0:JZ,JY,JX)                 !NO3 band volume fracrion, []
  real(r8) :: VLPO4(0:JZ,JY,JX)                 !PO4 non-band volume fracrion, []
  real(r8) :: VLPOB(0:JZ,JY,JX)                 !PO4 band volume fracrion, []
  real(r8) :: WDNHB(JZ,JY,JX)                   !width of NH4 band, [m]
  real(r8) :: DPNHB(JZ,JY,JX)                   !depth of NH4 band, [m]
  real(r8) :: WDNOB(JZ,JY,JX)                   !width of NO3 band, [m]
  real(r8) :: DPNOB(JZ,JY,JX)                   !depth of NO4 band, [m]
  real(r8) :: WDPOB(JZ,JY,JX)                   !width of PO4 band, [m]
  real(r8) :: DPPOB(JZ,JY,JX)                   !depth of PO4 band, [m]
  real(r8) :: DPNH4(JY,JX)                      !total depth of NH4 band, [m]
  real(r8) :: DPNO3(JY,JX)                      !total depth of NO3 band, [m]
  real(r8) :: DPPO4(JY,JX)                      !total depth of PO4 band, [m]
  real(r8) :: RVMXC(0:JZ,JY,JX)                 !total chemodenitrification N2O uptake non-band unconstrained by N2O, [g d-2 h-1]
  real(r8) :: RVMBC(0:JZ,JY,JX)                 !total chemodenitrification N2O uptake band unconstrained by N2O, [g d-2 h-1]
  real(r8) :: XCODFR(JY,JX)                     !soil surface CO2 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XCHDFR(JY,JX)                     !soil surface CH4 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XOXDFR(JY,JX)                     !soil surface O2 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XNGDFR(JY,JX)                     !soil surface N2 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XN2DFR(JY,JX)                     !soil surface N2O dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XN3DFR(JY,JX)                     !soil surface NH3 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XHGDFR(JY,JX)                     !soil surface H2 dissolution (+ve) - volatilization (-ve), [g d-2 h-1]
  real(r8) :: XCOBBL(JZ,JY,JX)                  !CO2 bubbling, [g d-2 h-1]
  real(r8) :: XCHBBL(JZ,JY,JX)                  !CH4 bubbling, [g d-2 h-1]
  real(r8) :: XOXBBL(JZ,JY,JX)                  !O2 bubbling, [g d-2 h-1]
  real(r8) :: XNGBBL(JZ,JY,JX)                  !N2 bubbling, [g d-2 h-1]
  real(r8) :: XN2BBL(JZ,JY,JX)                  !N2O bubbling, [g d-2 h-1]
  real(r8) :: XN3BBL(JZ,JY,JX)                  !NH3 bubbling non-band, [g d-2 h-1]
  real(r8) :: XNBBBL(JZ,JY,JX)                  !NH3 bubbling band, [g d-2 h-1]
  real(r8) :: XHGBBL(JZ,JY,JX)                  !H2 bubbling, [g d-2 h-1]
  real(r8) :: XZHYS(0:JZ,JY,JX)                 !total H+ production


  real(r8) :: FLW(3,JD,JV,JH)                   !water flux micropore, [m3 d-2 h-1]
  real(r8) :: FLWH(3,JD,JV,JH)                  !water flux macropore, [m3 d-2 h-1]
  real(r8) :: HFLW(3,JD,JV,JH)                  !convective heat flux micropore, [MJ d-2 h-1]
  real(r8) :: XCOFLS(3,0:JD,JV,JH)              !aqueous CO2 flux micropore, [g d-2 h-1]
  real(r8) :: XCHFLS(3,0:JD,JV,JH)              !aqueous CH4 flux micropore, [g d-2 h-1]
  real(r8) :: XOXFLS(3,0:JD,JV,JH)              !aqueous O2 flux micropore, [g d-2 h-1]
  real(r8) :: XNGFLS(3,0:JD,JV,JH)              !aqueous N2 flux micropore, [g d-2 h-1]
  real(r8) :: XN2FLS(3,0:JD,JV,JH)              !aqueous N2O flux micropore, [g d-2 h-1]
  real(r8) :: XHGFLS(3,0:JD,JV,JH)              !aqueous H2 flux micropore, [g d-2 h-1]
  real(r8) :: XN4FLW(3,0:JD,JV,JH)              !aqueous NH4 flux non-band micropore, [g d-2 h-1]
  real(r8) :: XN3FLW(3,0:JD,JV,JH)              !aqueous NH3 flux non-band micropore, [g d-2 h-1]
  real(r8) :: XNOFLW(3,0:JD,JV,JH)              !aqueous NO3 flux non-band micropore, [g d-2 h-1]
  real(r8) :: XH2PFS(3,0:JD,JV,JH)              !aqueous PO4 flux non-band micropore, [g d-2 h-1]
  real(r8) :: XNXFLS(3,0:JD,JV,JH)              !aqueous NO2 flux non-band micropore, [g d-2 h-1]
  real(r8) :: XN4FLB(3,JD,JV,JH)                !aqueous NH4 flux band micropore, [g d-2 h-1]
  real(r8) :: XN3FLB(3,JD,JV,JH)                !aqueous NH3 flux band micropore, [g d-2 h-1]
  real(r8) :: XNOFLB(3,JD,JV,JH)                !aqueous NO3 flux band micropore, [g d-2 h-1]
  real(r8) :: XH2BFB(3,JD,JV,JH)                !aqueous PO4 flux band micropore, [g d-2 h-1]
  real(r8) :: XNXFLB(3,JD,JV,JH)                !aqueous NO2 flux band micropore, [g d-2 h-1]
  real(r8) :: XOCFLS(0:4,3,0:JD,JV,JH)          !DOC flux micropore, [g d-2 h-1]
  real(r8) :: XONFLS(0:4,3,0:JD,JV,JH)          !DON flux micropore, [g d-2 h-1]
  real(r8) :: XCHFLG(3,0:JD,JV,JH)              !gaseous CH4 flux, [g d-2 h-1]
  real(r8) :: XOAFLS(0:4,3,0:JD,JV,JH)          !aqueous acetate flux, [g d-2 h-1]
  real(r8) :: XCOFLG(3,JD,JV,JH)                !gaseous CO2 flux, [g d-2 h-1]
  real(r8) :: XOPFLS(0:4,3,0:JD,JV,JH)          !DOP flux micropore, [g d-2 h-1]
  real(r8) :: XOXFLG(3,JD,JV,JH)                !gaseous O24 flux, [g d-2 h-1]
  real(r8) :: XNGFLG(3,JD,JV,JH)                !gaseous N2 flux, [g d-2 h-1]
  real(r8) :: XHGFLG(3,JD,JV,JH)                !gaseous H2 flux, [g d-2 h-1]
  real(r8) :: XN2FLG(3,JD,JV,JH)                !gaseous N2O flux, [g d-2 h-1]
  real(r8) :: XN3FLG(3,JD,JV,JH)                !gaseous NH3 flux, [g d-2 h-1]
  real(r8) :: XH1PFS(3,0:JD,JV,JH)              !total HPO4 in micropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH1BFB(3,0:JD,JV,JH)              !total HPO4 in micropore water flux band, [mol d-2 h-1]
  real(r8) :: XCOFHS(3,JD,JV,JH)                !aqueous CO2 flux macropore, [g d-2 h-1]
  real(r8) :: XCHFHS(3,JD,JV,JH)                !aqueous CH4 flux macropore, [g d-2 h-1]
  real(r8) :: XOXFHS(3,JD,JV,JH)                !aqueous O2 flux macropore, [g d-2 h-1]
  real(r8) :: XNGFHS(3,JD,JV,JH)                !aqueous N2 flux macropore, [g d-2 h-1]
  real(r8) :: XN2FHS(3,JD,JV,JH)                !aqueous N2O flux macropore, [g d-2 h-1]
  real(r8) :: XHGFHS(3,JD,JV,JH)                !aqueous H2 flux macropore, [g d-2 h-1]
  real(r8) :: XN4FHW(3,JD,JV,JH)                !aqueous NH4 flux non-band macropore, [g d-2 h-1]
  real(r8) :: XN3FHW(3,JD,JV,JH)                !aqueous NH3 flux non-band macropore, [g d-2 h-1]
  real(r8) :: XNOFHW(3,JD,JV,JH)                !aqueous NO3 flux non-band macropore, [g d-2 h-1]
  real(r8) :: XH2PHS(3,JD,JV,JH)                !aqueous PO4 flux non-band macropore, [g d-2 h-1]
  real(r8) :: XNXFHS(3,JD,JV,JH)                !aqueous NO2 flux non-band macropore, [g d-2 h-1]
  real(r8) :: XN4FHB(3,JD,JV,JH)                !aqueous NH4 flux band macropore, [g d-2 h-1]
  real(r8) :: XN3FHB(3,JD,JV,JH)                !aqueous NH3 flux band macropore, [g d-2 h-1]
  real(r8) :: XNOFHB(3,JD,JV,JH)                !aqueous NO3 flux band macropore, [g d-2 h-1]
  real(r8) :: XNXFHB(3,0:JD,JV,JH)              !aqueous PO4 flux band macropore, [g d-2 h-1]
  real(r8) :: XH2BHB(3,JD,JV,JH)                !aqueous NO2 flux band macropore, [g d-2 h-1]
  real(r8) :: XOCFHS(0:4,3,JD,JV,JH)            !DOC flux macropore, [g d-2 h-1]
  real(r8) :: XONFHS(0:4,3,JD,JV,JH)            !DON flux macropore, [g d-2 h-1]
  real(r8) :: XOPFHS(0:4,3,JD,JV,JH)            !DOP flux macropore, [g d-2 h-1]
  real(r8) :: XOAFHS(0:4,3,JD,JV,JH)            !acetate flux macropore, [g d-2 h-1]
  real(r8) :: XH1PHS(3,JD,JV,JH)                !total HPO4 in macropore water flux non-band, [mol d-2 h-1]
  real(r8) :: XH1BHB(3,JD,JV,JH)                !total HPO4 in macropore water flux band, [mol d-2 h-1]

  real(r8) :: GPP(JY,JX)                        !gross primary productivity, [g d-2 h-1]
  real(r8) :: TCCAN(JY,JX)                      !total net CO2 fixation
  real(r8) :: ZCSNC(JY,JX)                      !total litterfall C, [g d-2 h-1]
  real(r8) :: ZZSNC(JY,JX)                      !total litterfall N, [g d-2 h-1]
  real(r8) :: ZPSNC(JY,JX)                      !total litterfall P, [g d-2 h-1]
  real(r8) :: RECO(JY,JX)                       !ecosystem respiration, [g d-2 h-1]

end module SoilBGCDataType
