module SoluteChemDataType
  use data_kind_mod, only : r8 => SHR_KIND_R8

  implicit none
  public
  CHARACTER(LEN=*), private, PARAMETER :: MOD_FILENAME=__FILE__
  real(r8) :: BKVLX
  real(r8) :: VOLWPO
  real(r8) :: CH2P1  !current concentration of H2PO4(-) in non-band soils
  real(r8) :: CH2PB  !current concentration of H2PO4(-) in band soils
  real(r8) :: PCAPH1 !
  real(r8) :: VOLWBK
  real(r8) :: CH1P1
  real(r8) :: CH1PB
  real(r8) :: CN31
  real(r8) :: CN41
  real(r8) :: CN3B
  real(r8) :: CN4B
  real(r8) :: PALPO1
  real(r8) :: PALPOB
  real(r8) :: PCAPD1
  real(r8) :: PCAPDB
  real(r8) :: PCAPHB
  real(r8) :: PCAPM1
  real(r8) :: PCAPMB
  real(r8) :: PFEPO1
  real(r8) :: PFEPOB
  real(r8) :: RH2P
  real(r8) :: RNH4
  real(r8) :: RPALPX
  real(r8) :: RPCADX
  real(r8) :: RPCAHX
  real(r8) :: RPCAMX
  real(r8) :: RPFEPX
  real(r8) :: RXN4
  real(r8) :: VOLWNB
  real(r8) :: VOLWNH
  real(r8) :: VOLWPB
  real(r8) :: X1P1B
  real(r8) :: X2P1B
  real(r8) :: XH11B
  real(r8) :: XH21B
  real(r8) :: XH1P1
  real(r8) :: XH2P1
  real(r8) :: XN41
  real(r8) :: XN4B
  real(r8) :: XOH11
  real(r8) :: XOH21
  real(r8) :: XOH01
  real(r8) :: XH01B
  real(r8) :: VOLWNO
  real(r8) :: VOLWNZ

  type, public :: solutedtype
    real(r8) :: CCO21
    real(r8) :: CCH41
    real(r8) :: COXY1
    real(r8) :: CZ2G1
    real(r8) :: CZ2O1
    real(r8) :: CN41
    real(r8) :: CN31
    real(r8) :: CAL1
    real(r8) :: CFE1
    real(r8) :: CHY1
    real(r8) :: CCA1
    real(r8) :: CMG1
    real(r8) :: CNA1
    real(r8) :: CKA1
    real(r8) :: COH1
    real(r8) :: CSO41
    real(r8) :: CCL1
    real(r8) :: CCO31
    real(r8) :: CHCO31
    real(r8) :: CALO1
    real(r8) :: CALO2
    real(r8) :: CALO3
    real(r8) :: CALO4
    real(r8) :: CALS1
    real(r8) :: CFEO1
    real(r8) :: CFEO2
    real(r8) :: CFEO3
    real(r8) :: CFEO4
    real(r8) :: CFES1
    real(r8) :: CCAO1
    real(r8) :: CCAC1
    real(r8) :: CCAH1
    real(r8) :: CCAS1
    real(r8) :: CMGO1
    real(r8) :: CMGC1
    real(r8) :: CMGH1
    real(r8) :: CMGS1
    real(r8) :: CNAC1
    real(r8) :: CNAS1
    real(r8) :: CKAS1
    real(r8) :: CH0P1
    real(r8) :: CH1P1
    real(r8) :: CH2P1
    real(r8) :: CH3P1
    real(r8) :: CF1P1
    real(r8) :: CF2P1
    real(r8) :: CC0P1
    real(r8) :: CC1P1
    real(r8) :: CC2P1
    real(r8) :: CM1P1
    real(r8) :: CSTR1
    real(r8) :: CCO2M
    real(r8) :: CCH4M
    real(r8) :: COXYM
    real(r8) :: CZ2GM
    real(r8) :: CZ2OM
    real(r8) :: CN4Z
    real(r8) :: CNOZ
    real(r8) :: CNAZ
    real(r8) :: CKAZ
    real(r8) :: CSOZ
    real(r8) :: CCLZ
    real(r8) :: CNOX
    real(r8) :: CCASOX
    real(r8) :: CN4X
    real(r8) :: CPOZ
    real(r8) :: CALZ
    real(r8) :: CFEZ
    real(r8) :: CCAZ
    real(r8) :: CMGZ
    real(r8) :: CALX
    real(r8) :: CFEX
    real(r8) :: CCAX
    real(r8) :: CMGX
    real(r8) :: CNAX
    real(r8) :: CKAX
    real(r8) :: CSOX
    real(r8) :: CCLX
    real(r8) :: CALPOX
    real(r8) :: CFEPOX
    real(r8) :: CCAPDX
    real(r8) :: CCAPHX
    real(r8) :: CALOHX
    real(r8) :: CFEOHX
    real(r8) :: CCACOX
    real(r8) :: XN41
    real(r8) :: XHY1
    real(r8) :: XAL1
    real(r8) :: XFE1
    real(r8) :: XCA1
    real(r8) :: PCAPH1
    real(r8) :: XMG1
    real(r8) :: XNA1
    real(r8) :: XKA1
    real(r8) :: XHC1
    real(r8) :: XALO21
    real(r8) :: XFEO21
    real(r8) :: XOH01
    real(r8) :: XOH11
    real(r8) :: XOH21
    real(r8) :: XH1P1
    real(r8) :: XH2P1
    real(r8) :: PALOH1
    real(r8) :: PFEOH1
    real(r8) :: PCACO1
    real(r8) :: PCASO1
    real(r8) :: PALPO1
    real(r8) :: PFEPO1
    real(r8) :: PCAPD1
    real(r8) :: FH2O
    real(r8) :: ATCA
    real(r8) :: XAEC
    real(r8) :: CEC
    real(r8) :: ORGC
    real(r8) :: VLPO4
    real(r8) :: XCEC
    real(r8) :: GKC4
    real(r8) :: GKCA
    real(r8) :: GKCH
    real(r8) :: GKCK
    real(r8) :: GKCN
    real(r8) :: GKCM
    real(r8) :: ZEROS
    real(r8) :: VOLW
  end type solutedtype
end module SoluteChemDataType
