module SurfaceFluxMod
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridDataType
  use TransfrDataMod
  use SoilBGCDataType
  use SoilWaterDataType
  use EcoSIMCtrlDataType
  use SurfLitterDataType
  use AqueChemDatatype
  use SnowDataType
  use EcoSimConst
  use ChemTranspDataType
  use ClimForcDataType
  use EcoSIMSolverPar
  use LandSurfDataType
  use SurfSoilDataType
  use SoilPropertyDataType
implicit none
  private
  CHARACTER(LEN=*), PARAMETER :: MOD_FILENAME=__FILE__
  real(r8), parameter :: XFRS=0.05_r8
  real(r8) :: COXYS2,CZ2GS2,CZ2OS2,CH2GS2,CNH3S2,CNH4S2,CNO3S2
  real(r8) :: CNO2S2,CP14S2,CPO4S2,CCH4S2,CCO2S2
  real(r8) :: CNH3B2,CNH4B2,CNO2B2,CP14B2,CPO4B2,CNO3B2
  real(r8) :: RCODXS,RCHDXS,ROXDXS,RNGDXS,RN2DXS,RN3DXS,RNBDXS,RHGDXS
  real(r8) :: CCH4S1,COXYS1,CZ2GS1,CZ2OS1,CH2GS1,CNH4S1
  real(r8) :: CNH3S1,CNO3S1,CNO2S1,CP14S1,CPO4S1,CCO2S1
  real(r8) :: RCODXR,RCHDXR,ROXDXR,RNGDXR,RN2DXR,RN3DXR,RHGDXR
  real(r8) :: DFVCOS,DFVCHS,DFVOXS
  real(r8) :: DFVNGS,DFVN2S,DFVHGS,DFVNH4,DFVNH3,DFVNO3,DFVNO2
  real(r8) :: DFVP14,DFVPO4,DFVN4B,DFVN3B,DFVNOB,DFVN2B,DFVP1B
  real(r8) :: DFVPOB,DFVCOG,DFVCHG,DFVOXG,DFVNGG
  real(r8) :: RFLCOS,RFLCHS,RFLNGS,RFLN2S,RFLOXS
  real(r8) :: RFLHGS,RFLNH4,RFLNH3,RFLNO3,RFLNO2,RFLP14,RFLPO4
  real(r8) :: RFLN4B,RFLN3B,RFLNOB,RFLN2B,RFLP1B,RFLPOB,RFLCOG
  real(r8) :: RFLCHG,RFLOXG,RFLNGG,RFLN2G,RFLN3G,RFLH2G
  real(r8) :: RCOFLS1,RCHFLS1,RNGFLS1,RN2FLS1,ROXFLS1
  real(r8) :: RN4FLW1,RN3FLW1,RNOFLW1
  real(r8) :: RCOFLS0,RCHFLS0,RN2FLS0,ROXFLS0,RNGFLS0
  real(r8) :: RN4FLB1,RN3FLB1,RNOFLB1,RH1BFB1,RH2BFB1
  real(r8) :: RN4FLW0,RN3FLW0,RNOFLW0,RH1PFS0,RH2PFS0
  real(r8) :: RH1PFS1,RH2PFS1

  public :: SoluteFluxSurface
  public :: SurfaceGasVolatilDissol
  public :: GasDiffusionConvection
  public :: SoluteFluxSnowpack
contains


!------------------------------------------------------------------------------------------

  subroutine SoluteFluxSurface(M,NY,NX,NHE,NHW,NVS,NVN,FLQM)
  implicit none
  integer, intent(in) :: NY,NX,M
  integer, intent(in) :: NHE,NHW,NVS,NVN
  real(r8),intent(out) :: FLQM(3,JD,JV,JH)
  real(r8) :: FLWRM1
!     VOLWM,VOLWHM,VOLPM,FLPM=micropore,macropore water volume, air volume and change in air volume
!     FLWM,FLWHM=water flux into soil micropore,macropore from watsub.f
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!     FLVM,FLM=air,water flux in gas flux calculations
!     XNPT=1/number of cycles NPH-1 for gas flux calculations
!
  VOLWMA(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*VLNH4(NU(NY,NX),NY,NX)
  VOLWMB(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*VLNHB(NU(NY,NX),NY,NX)
  VOLWXA(NU(NY,NX),NY,NX)=14.0_r8*VOLWMA(NU(NY,NX),NY,NX)
  VOLWXB(NU(NY,NX),NY,NX)=14.0_r8*VOLWMB(NU(NY,NX),NY,NX)
  VOLPMA(NU(NY,NX),NY,NX)=VOLPM(M,NU(NY,NX),NY,NX)*VLNH4(NU(NY,NX),NY,NX)
  VOLPMB(NU(NY,NX),NY,NX)=VOLPM(M,NU(NY,NX),NY,NX)*VLNHB(NU(NY,NX),NY,NX)
  FLVM(NU(NY,NX),NY,NX)=FLPM(M,NU(NY,NX),NY,NX)*XNPT
  FLQM(3,NU(NY,NX),NY,NX)=(FLWM(M,3,NU(NY,NX),NY,NX)+FLWHM(M,3,NU(NY,NX),NY,NX))*XNPT
!
!     SURFACE EXCHANGE OF AQUEOUS CO2, CH4, O2, N2, NH3
!     THROUGH VOLATILIZATION-DISSOLUTION FROM AQUEOUS
!     DIFFUSIVITIES IN SURFACE RESIDUE
!
!     VOLT,DLYR,AREA=litter volume, thickness, area
!     VOLWM=micropore water-filled porosity from watsub.f
!     TORT=tortuosity from hour1.f
!     *SGL*=solute diffusivity
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     DFGS*=effective solute diffusivity
!     CO2S,CH4S,OXYS,Z2GS,Z2OS,H2GS=aqueous CO2,CH4,O2,N2,N2O,H2 in litter
!     OQC,OQN,OQP,OQA=DOC,DON,DOP,acetate in litter
!     ZNH4S,ZNH3S,ZNO3S,ZNO2S,H1PO4,H2PO4=aqueous NH4,NH3,NO3,NO2,HPO4,H2PO4 in litter
!     C*1=solute concentration in litter
!
  call LitterAtmosExchange(M,NY,NX)

  call SoilAtmosExchange(M,NY,NX)

!     CONVECTIVE SOLUTE EXCHANGE BETWEEN RESIDUE AND SOIL SURFACE
!
  call ConvectiveSurfaceSoluteFlux(M,NY,NX,FLWRM1)
!
!     DIFFUSIVE FLUXES OF GASES AND SOLUTES BETWEEN RESIDUE AND
!     SOIL SURFACE FROM AQUEOUS DIFFUSIVITIES
!     AND CONCENTRATION DIFFERENCES
!
  call DiffusiveFluxAtSoilSurface(M,NY,NX,FLWRM1)

!     DIFFUSIVE FLUXES BETWEEN CURRENT AND ADJACENT GRID CELL
!     MICROPORES
!
!
!     TOTAL MICROPORE AND MACROPORE SOLUTE TRANSPORT FLUXES BETWEEN
!     ADJACENT GRID CELLS = CONVECTIVE + DIFFUSIVE FLUXES
!
  call TotalPoreFluxAdjacentCell(NY,NX)

!     MACROPORE-MICROPORE CONVECTIVE SOLUTE EXCHANGE IN SOIL
!     SURFACE LAYER FROM WATER EXCHANGE IN 'WATSUB' AND
!     FROM MACROPORE OR MICROPORE SOLUTE CONCENTRATIONS
!
  call MacroMicroTransfer(M,NY,NX)

!
!     SOLUTE TRANSPORT FROM WATER OVERLAND FLOW
!     IN 'WATSUB' AND FROM SOLUTE CONCENTRATIONS
!     IN SOIL SURFACE LAYER
!
  call OverlandFlowSnowdriftTransport(M,NY,NX,NHE,NHW,NVS,NVN)
  end subroutine SoluteFluxSurface

!------------------------------------------------------------------------------------------

  subroutine ConvectiveSurfaceSoluteFlux(M,NY,NX,FLWRM1)
  implicit none

  integer, intent(in) :: M, NY, NX
  real(r8),intent(out) :: FLWRM1
  REAL(R8) :: VFLW
  integer :: K

  FLWRM1=FLWRM(M,NY,NX)
!
!     FLWRM=litter-soil water flux from watsub.f
!
!     IF WATER FLUX FROM 'WATSUB' IS FROM RESIDUE TO
!     SOIL SURFACE THEN CONVECTIVE TRANSPORT IS THE PRODUCT
!     OF WATER FLUX AND MICROPORE GAS OR SOLUTE CONCENTRATIONS
!     IN RESIDUE
!
!     VOLWM=litter water volume
!     RFL*=soil-litter convective solute flux
!     *S2=litter solute content
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!
  IF(FLWRM1.GT.0.0_r8)THEN
    IF(VOLWM(M,0,NY,NX).GT.ZEROS2(NY,NX))THEN
      VFLW=AMAX1(0.0_r8,AMIN1(VFLWX,FLWRM1/VOLWM(M,0,NY,NX)))
    ELSE
      VFLW=VFLWX
    ENDIF
    DO  K=0,jcplx1
      RFLOC(K)=VFLW*AMAX1(0.0_r8,OQC2(K,0,NY,NX))
      RFLON(K)=VFLW*AMAX1(0.0_r8,OQN2(K,0,NY,NX))
      RFLOP(K)=VFLW*AMAX1(0.0_r8,OQP2(K,0,NY,NX))
      RFLOA(K)=VFLW*AMAX1(0.0_r8,OQA2(K,0,NY,NX))
    ENDDO
    RFLCOS=VFLW*AMAX1(0.0_r8,CO2S2(0,NY,NX))
    RFLCHS=VFLW*AMAX1(0.0_r8,CH4S2(0,NY,NX))
    RFLOXS=VFLW*AMAX1(0.0_r8,OXYS2(0,NY,NX))
    RFLNGS=VFLW*AMAX1(0.0_r8,Z2GS2(0,NY,NX))
    RFLN2S=VFLW*AMAX1(0.0_r8,Z2OS2(0,NY,NX))
    RFLHGS=VFLW*AMAX1(0.0_r8,H2GS2(0,NY,NX))
    RFLNH4=VFLW*AMAX1(0.0_r8,ZNH4S2(0,NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNH3=VFLW*AMAX1(0.0_r8,ZNH3S2(0,NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNO3=VFLW*AMAX1(0.0_r8,ZNO3S2(0,NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLNO2=VFLW*AMAX1(0.0_r8,ZNO2S2(0,NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLP14=VFLW*AMAX1(0.0_r8,H1PO42(0,NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLPO4=VFLW*AMAX1(0.0_r8,H2PO42(0,NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLN4B=VFLW*AMAX1(0.0_r8,ZNH4S2(0,NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLN3B=VFLW*AMAX1(0.0_r8,ZNH3S2(0,NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLNOB=VFLW*AMAX1(0.0_r8,ZNO3S2(0,NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLN2B=VFLW*AMAX1(0.0_r8,ZNO2S2(0,NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLP1B=VFLW*AMAX1(0.0_r8,H1PO42(0,NY,NX))*VLPOB(NU(NY,NX),NY,NX)
    RFLPOB=VFLW*AMAX1(0.0_r8,H2PO42(0,NY,NX))*VLPOB(NU(NY,NX),NY,NX)
!
!     IF WATER FLUX FROM 'WATSUB' IS TO RESIDUE FROM
!     SOIL SURFACE THEN CONVECTIVE TRANSPORT IS THE PRODUCT
!     OF WATER FLUX AND MICROPORE GAS OR SOLUTE CONCENTRATIONS
!     IN SOIL SURFACE
!
!     VOLWM=micropore water-filled porosity from watsub.f
!     RFL*=soil-litter convective solute flux
!     *S2=soil solute content
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!
  ELSE
    IF(VOLWM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      VFLW=AMIN1(0.0_r8,AMAX1(-VFLWX,FLWRM1/VOLWM(M,NU(NY,NX),NY,NX)))
    ELSE
      VFLW=-VFLWX
    ENDIF
    DO K=0,jcplx1
      RFLOC(K)=VFLW*AMAX1(0.0_r8,OQC2(K,NU(NY,NX),NY,NX))
      RFLON(K)=VFLW*AMAX1(0.0_r8,OQN2(K,NU(NY,NX),NY,NX))
      RFLOP(K)=VFLW*AMAX1(0.0_r8,OQP2(K,NU(NY,NX),NY,NX))
      RFLOA(K)=VFLW*AMAX1(0.0_r8,OQA2(K,NU(NY,NX),NY,NX))
    ENDDO
    RFLCOS=VFLW*AMAX1(0.0_r8,CO2S2(NU(NY,NX),NY,NX))
    RFLCHS=VFLW*AMAX1(0.0_r8,CH4S2(NU(NY,NX),NY,NX))
    RFLOXS=VFLW*AMAX1(0.0_r8,OXYS2(NU(NY,NX),NY,NX))
    RFLNGS=VFLW*AMAX1(0.0_r8,Z2GS2(NU(NY,NX),NY,NX))
    RFLN2S=VFLW*AMAX1(0.0_r8,Z2OS2(NU(NY,NX),NY,NX))
    RFLHGS=VFLW*AMAX1(0.0_r8,H2GS2(NU(NY,NX),NY,NX))
    RFLNH4=VFLW*AMAX1(0.0_r8,ZNH4S2(NU(NY,NX),NY,NX))
    RFLNH3=VFLW*AMAX1(0.0_r8,ZNH3S2(NU(NY,NX),NY,NX))
    RFLNO3=VFLW*AMAX1(0.0_r8,ZNO3S2(NU(NY,NX),NY,NX))
    RFLNO2=VFLW*AMAX1(0.0_r8,ZNO2S2(NU(NY,NX),NY,NX))
    RFLP14=VFLW*AMAX1(0.0_r8,H1PO42(NU(NY,NX),NY,NX))
    RFLPO4=VFLW*AMAX1(0.0_r8,H2PO42(NU(NY,NX),NY,NX))
    RFLN4B=VFLW*AMAX1(0.0_r8,ZNH4B2(NU(NY,NX),NY,NX))
    RFLN3B=VFLW*AMAX1(0.0_r8,ZNH3B2(NU(NY,NX),NY,NX))
    RFLNOB=VFLW*AMAX1(0.0_r8,ZNO3B2(NU(NY,NX),NY,NX))
    RFLN2B=VFLW*AMAX1(0.0_r8,ZNO2B2(NU(NY,NX),NY,NX))
    RFLP1B=VFLW*AMAX1(0.0_r8,H1POB2(NU(NY,NX),NY,NX))
    RFLPOB=VFLW*AMAX1(0.0_r8,H2POB2(NU(NY,NX),NY,NX))
  ENDIF
  end subroutine ConvectiveSurfaceSoluteFlux
!------------------------------------------------------------------------------------------

  subroutine DiffusiveFluxAtSoilSurface(M,NY,NX,FLWRM1)
  implicit none

  integer, intent(in) :: M, NY, NX
  real(r8), intent(in) :: FLWRM1
  real(r8) :: TORT0,TORT1
  real(r8) :: DLYR0,DLYR1
  real(r8) :: DIFCQ,DIFCS,DIFHG,DIFN2,DIFNG,DISPN
  real(r8) :: DIFOS,DIFOC,DIFON,DIFOP,DIFOA,DIFNH,DIFNO,DIFPO
  real(r8) :: DIFOC0,DIFON0,DIFOP0,DIFOA0,DIFNH0
  real(r8) :: DIFNO0,DIFPO0,DIFCS0,DIFCQ0,DIFOS0,DIFNG0,DIFN20
  real(r8) :: DIFPO1,DIFCS1,DIFCQ1,DIFOS1,DIFNG1,DIFN21,DIFHG1
  real(r8) :: DIFHG0,DIFOC1,DIFON1,DIFOP1,DIFOA1,DIFNH1,DIFNO1
  integer :: K
!
!     VOLT,DLYR,AREA=soil surface volume, thickness, area
!     VOLWM=micropore water-filled porosity from watsub.f
!
  IF((VOLT(0,NY,NX).GT.ZEROS2(NY,NX).AND.VOLWM(M,0,NY,NX).GT.ZEROS2(NY,NX)) &
    .AND.(VOLWM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX)))THEN
!
!     DIFFUSIVITIES IN RESIDUE AND SOIL SURFACE
!
!     DLYR0,DLYR1=litter, soil surface thickness
!     TORT=tortuosity from hour1.f
!     CVRD,BARE=litter cover fraction,1-CVRD
!     DISP=dispersivity parameter
!     FLWRM=litter-soil water flux from watsub.f
!     DIF*0,DIF*1=aqueous diffusivity-dispersivity in litter, soil surface
!     *SGL*=solute diffusivity from hour1.f
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     DIF*=aqueous diffusivity-dispersivity between litter and soil surface
!
    DLYR0=AMAX1(ZERO2,DLYR(3,0,NY,NX))
    TORT0=TORT(M,0,NY,NX)/DLYR0*CVRD(NY,NX)
    DLYR1=AMAX1(ZERO2,DLYR(3,NU(NY,NX),NY,NX))
    TORT1=TORT(M,NU(NY,NX),NY,NX)/DLYR1
    DISPN=DISP(3,NU(NY,NX),NY,NX)*AMIN1(VFLWX,ABS(FLWRM1/AREA(3,NU(NY,NX),NY,NX)))
    DIFOC0=(OCSGL2(0,NY,NX)*TORT0+DISPN)
    DIFON0=(ONSGL2(0,NY,NX)*TORT0+DISPN)
    DIFOP0=(OPSGL2(0,NY,NX)*TORT0+DISPN)
    DIFOA0=(OASGL2(0,NY,NX)*TORT0+DISPN)
    DIFNH0=(ZNSGL2(0,NY,NX)*TORT0+DISPN)
    DIFNO0=(ZOSGL2(0,NY,NX)*TORT0+DISPN)
    DIFPO0=(POSGL2(0,NY,NX)*TORT0+DISPN)
    DIFCS0=(CLSGL2(0,NY,NX)*TORT0+DISPN)
    DIFCQ0=(CQSGL2(0,NY,NX)*TORT0+DISPN)
    DIFOS0=(OLSGL2(0,NY,NX)*TORT0+DISPN)
    DIFNG0=(ZLSGL2(0,NY,NX)*TORT0+DISPN)
    DIFN20=(ZVSGL2(0,NY,NX)*TORT0+DISPN)
    DIFHG0=(HLSGL2(0,NY,NX)*TORT0+DISPN)
    DIFOC1=(OCSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFON1=(ONSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFOP1=(OPSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFOA1=(OASGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFNH1=(ZNSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFNO1=(ZOSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFPO1=(POSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFCS1=(CLSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFCQ1=(CQSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFOS1=(OLSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFNG1=(ZLSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFN21=(ZVSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFHG1=(HLSGL2(NU(NY,NX),NY,NX)*TORT1+DISPN)
    DIFOC=DIFOC0*DIFOC1/(DIFOC0+DIFOC1)*AREA(3,NU(NY,NX),NY,NX)
    DIFON=DIFON0*DIFON1/(DIFON0+DIFON1)*AREA(3,NU(NY,NX),NY,NX)
    DIFOP=DIFOP0*DIFOP1/(DIFOP0+DIFOP1)*AREA(3,NU(NY,NX),NY,NX)
    DIFOA=DIFOA0*DIFOA1/(DIFOA0+DIFOA1)*AREA(3,NU(NY,NX),NY,NX)
    DIFNH=DIFNH0*DIFNH1/(DIFNH0+DIFNH1)*AREA(3,NU(NY,NX),NY,NX)
    DIFNO=DIFNO0*DIFNO1/(DIFNO0+DIFNO1)*AREA(3,NU(NY,NX),NY,NX)
    DIFPO=DIFPO0*DIFPO1/(DIFPO0+DIFPO1)*AREA(3,NU(NY,NX),NY,NX)
    DIFCS=DIFCS0*DIFCS1/(DIFCS0+DIFCS1)*AREA(3,NU(NY,NX),NY,NX)
    DIFCQ=DIFCQ0*DIFCQ1/(DIFCQ0+DIFCQ1)*AREA(3,NU(NY,NX),NY,NX)
    DIFOS=DIFOS0*DIFOS1/(DIFOS0+DIFOS1)*AREA(3,NU(NY,NX),NY,NX)
    DIFNG=DIFNG0*DIFNG1/(DIFNG0+DIFNG1)*AREA(3,NU(NY,NX),NY,NX)
    DIFN2=DIFN20*DIFN21/(DIFN20+DIFN21)*AREA(3,NU(NY,NX),NY,NX)
    DIFHG=DIFHG0*DIFHG1/(DIFHG0+DIFHG1)*AREA(3,NU(NY,NX),NY,NX)
!     DFV*S,DFV*B=diffusive solute flux between litter and soil surface in non-band,band
!     DIF*=aqueous diffusivity-dispersivity between litter and soil surface
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     C*1,C*2=solute concentration in litter,soil surface
!
    DO  K=0,jcplx1
      DFVOC(K)=DIFOC*(COQC1(K)-COQC2(K))
      DFVON(K)=DIFON*(COQN1(K)-COQN2(K))
      DFVOP(K)=DIFOP*(COQP1(K)-COQP2(K))
      DFVOA(K)=DIFOA*(COQA1(K)-COQA2(K))
    ENDDO
    DFVCOS=DIFCS*(CCO2S1-CCO2S2)
    DFVCHS=DIFCQ*(CCH4S1-CCH4S2)
    DFVOXS=DIFOS*(COXYS1-COXYS2)
    DFVNGS=DIFNG*(CZ2GS1-CZ2GS2)
    DFVN2S=DIFN2*(CZ2OS1-CZ2OS2)
    DFVHGS=DIFHG*(CH2GS1-CH2GS2)
    DFVNH4=DIFNH*(CNH4S1-CNH4S2)*VLNH4(NU(NY,NX),NY,NX)
    DFVNH3=DIFNH*(CNH3S1-CNH3S2)*VLNH4(NU(NY,NX),NY,NX)
    DFVNO3=DIFNO*(CNO3S1-CNO3S2)*VLNO3(NU(NY,NX),NY,NX)
    DFVNO2=DIFNO*(CNO2S1-CNO2S2)*VLNO3(NU(NY,NX),NY,NX)
    DFVP14=DIFPO*(CP14S1-CP14S2)*VLPO4(NU(NY,NX),NY,NX)
    DFVPO4=DIFPO*(CPO4S1-CPO4S2)*VLPO4(NU(NY,NX),NY,NX)
    DFVN4B=DIFNH*(CNH4S1-CNH4B2)*VLNHB(NU(NY,NX),NY,NX)
    DFVN3B=DIFNH*(CNH3S1-CNH3B2)*VLNHB(NU(NY,NX),NY,NX)
    DFVNOB=DIFNO*(CNO3S1-CNO3B2)*VLNOB(NU(NY,NX),NY,NX)
    DFVN2B=DIFNO*(CNO2S1-CNO2B2)*VLNOB(NU(NY,NX),NY,NX)
    DFVP1B=DIFPO*(CP14S1-CP14B2)*VLPOB(NU(NY,NX),NY,NX)
    DFVPOB=DIFPO*(CPO4S1-CPO4B2)*VLPOB(NU(NY,NX),NY,NX)
  ELSE
    DO  K=0,jcplx1
      DFVOC(K)=0.0_r8
      DFVON(K)=0.0_r8
      DFVOP(K)=0.0_r8
      DFVOA(K)=0.0_r8
    ENDDO
    DFVCOS=0.0_r8
    DFVCHS=0.0_r8
    DFVOXS=0.0_r8
    DFVNGS=0.0_r8
    DFVN2S=0.0_r8
    DFVHGS=0.0_r8
    DFVNH4=0.0_r8
    DFVNH3=0.0_r8
    DFVNO3=0.0_r8
    DFVNO2=0.0_r8
    DFVP14=0.0_r8
    DFVPO4=0.0_r8
    DFVN4B=0.0_r8
    DFVN3B=0.0_r8
    DFVNOB=0.0_r8
    DFVN2B=0.0_r8
    DFVP1B=0.0_r8
    DFVPOB=0.0_r8
  ENDIF
  end subroutine DiffusiveFluxAtSoilSurface


!------------------------------------------------------------------------------------------

  subroutine TotalPoreFluxAdjacentCell(NY,NX)
  implicit none

  integer, intent(in) :: NY, NX

  integer :: K
!     R*FLS=convective + diffusive solute flux between litter, soil surface
!     R*FLW,R*FLB=convective + diffusive solute flux into soil in non-band,band
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     R*FL0,R*FL1=convective flux into surface litter, soil surface
!     RFL*=convective flux between surface litter and soil surface
!     DFV*=diffusive solute flux between litter and soil surface
!
  DO K=0,2
    ROCFLS(K,3,0,NY,NX)=ROCFL0(K,NY,NX)-RFLOC(K)-DFVOC(K)
    RONFLS(K,3,0,NY,NX)=RONFL0(K,NY,NX)-RFLON(K)-DFVON(K)
    ROPFLS(K,3,0,NY,NX)=ROPFL0(K,NY,NX)-RFLOP(K)-DFVOP(K)
    ROAFLS(K,3,0,NY,NX)=ROAFL0(K,NY,NX)-RFLOA(K)-DFVOA(K)
    ROCFLS(K,3,NU(NY,NX),NY,NX)=ROCFL1(K,NY,NX)+RFLOC(K)+DFVOC(K)
    RONFLS(K,3,NU(NY,NX),NY,NX)=RONFL1(K,NY,NX)+RFLON(K)+DFVON(K)
    ROPFLS(K,3,NU(NY,NX),NY,NX)=ROPFL1(K,NY,NX)+RFLOP(K)+DFVOP(K)
    ROAFLS(K,3,NU(NY,NX),NY,NX)=ROAFL1(K,NY,NX)+RFLOA(K)+DFVOA(K)
  ENDDO
  RCOFLS(3,0,NY,NX)=RCOFL0(NY,NX)+RCOFLS0-RFLCOS-DFVCOS
  RCHFLS(3,0,NY,NX)=RCHFL0(NY,NX)+RCHFLS0-RFLCHS-DFVCHS
  ROXFLS(3,0,NY,NX)=ROXFL0(NY,NX)+ROXFLS0-RFLOXS-DFVOXS
  RNGFLS(3,0,NY,NX)=RNGFL0(NY,NX)+RNGFLS0-RFLNGS-DFVNGS
  RN2FLS(3,0,NY,NX)=RN2FL0(NY,NX)+RN2FLS0-RFLN2S-DFVN2S
  RHGFLS(3,0,NY,NX)=RHGFL0(NY,NX)-RFLHGS-DFVHGS
  RN4FLW(3,0,NY,NX)=RN4FL0(NY,NX)+RN4FLW0-RFLNH4-DFVNH4-RFLN4B-DFVN4B
  RN3FLW(3,0,NY,NX)=RN3FL0(NY,NX)+RN3FLW0-RFLNH3-DFVNH3-RFLN3B-DFVN3B
  RNOFLW(3,0,NY,NX)=RNOFL0(NY,NX)+RNOFLW0-RFLNO3-DFVNO3-RFLNOB-DFVNOB
  RNXFLS(3,0,NY,NX)=RNXFL0(NY,NX)-RFLNO2-DFVNO2-RFLN2B-DFVN2B
  RH1PFS(3,0,NY,NX)=RH1PF0(NY,NX)+RH1PFS0-RFLP14-DFVP14-RFLP1B-DFVP1B
  RH2PFS(3,0,NY,NX)=RH2PF0(NY,NX)+RH2PFS0-RFLPO4-DFVPO4-RFLPOB-DFVPOB
  RCOFLS(3,NU(NY,NX),NY,NX)=RCOFL1(NY,NX)+RCOFLS1+RFLCOS+DFVCOS
  RCHFLS(3,NU(NY,NX),NY,NX)=RCHFL1(NY,NX)+RCHFLS1+RFLCHS+DFVCHS
  ROXFLS(3,NU(NY,NX),NY,NX)=ROXFL1(NY,NX)+ROXFLS1+RFLOXS+DFVOXS
  RNGFLS(3,NU(NY,NX),NY,NX)=RNGFL1(NY,NX)+RNGFLS1+RFLNGS+DFVNGS
  RN2FLS(3,NU(NY,NX),NY,NX)=RN2FL1(NY,NX)+RN2FLS1+RFLN2S+DFVN2S
  RHGFLS(3,NU(NY,NX),NY,NX)=RHGFL1(NY,NX)+RFLHGS+DFVHGS
  RN4FLW(3,NU(NY,NX),NY,NX)=RN4FL1(NY,NX)+RN4FLW1+RFLNH4+DFVNH4
  RN3FLW(3,NU(NY,NX),NY,NX)=RN3FL1(NY,NX)+RN3FLW1+RFLNH3+DFVNH3
  RNOFLW(3,NU(NY,NX),NY,NX)=RNOFL1(NY,NX)+RNOFLW1+RFLNO3+DFVNO3
  RNXFLS(3,NU(NY,NX),NY,NX)=RNXFL1(NY,NX)+RFLNO2+DFVNO2
  RH1PFS(3,NU(NY,NX),NY,NX)=RH1PF1(NY,NX)+RH1PFS1+RFLP14+DFVP14
  RH2PFS(3,NU(NY,NX),NY,NX)=RH2PF1(NY,NX)+RH2PFS1+RFLPO4+DFVPO4
  RN4FLB(3,NU(NY,NX),NY,NX)=RN4FL2(NY,NX)+RN4FLB1+RFLN4B+DFVN4B
  RN3FLB(3,NU(NY,NX),NY,NX)=RN3FL2(NY,NX)+RN3FLB1+RFLN3B+DFVN3B
  RNOFLB(3,NU(NY,NX),NY,NX)=RNOFL2(NY,NX)+RNOFLB1+RFLNOB+DFVNOB
  RNXFLB(3,NU(NY,NX),NY,NX)=RNXFL2(NY,NX)+RFLN2B+DFVN2B
  RH1BFB(3,NU(NY,NX),NY,NX)=RH1BF2(NY,NX)+RH1BFB1+RFLP1B+DFVP1B
  RH2BFB(3,NU(NY,NX),NY,NX)=RH2BF2(NY,NX)+RH2BFB1+RFLPOB+DFVPOB
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*FLS=hourly convective + diffusive solute flux
!     X*FLW,X*FLB= hourly convective + diffusive solute flux in non-band,band
!
  DO K=0,2
    XOCFLS(K,3,0,NY,NX)=XOCFLS(K,3,0,NY,NX)-RFLOC(K)-DFVOC(K)
    XONFLS(K,3,0,NY,NX)=XONFLS(K,3,0,NY,NX)-RFLON(K)-DFVON(K)
    XOPFLS(K,3,0,NY,NX)=XOPFLS(K,3,0,NY,NX)-RFLOP(K)-DFVOP(K)
    XOAFLS(K,3,0,NY,NX)=XOAFLS(K,3,0,NY,NX)-RFLOA(K)-DFVOA(K)
    XOCFLS(K,3,NU(NY,NX),NY,NX)=XOCFLS(K,3,NU(NY,NX),NY,NX)+RFLOC(K)+DFVOC(K)
    XONFLS(K,3,NU(NY,NX),NY,NX)=XONFLS(K,3,NU(NY,NX),NY,NX)+RFLON(K)+DFVON(K)
    XOPFLS(K,3,NU(NY,NX),NY,NX)=XOPFLS(K,3,NU(NY,NX),NY,NX)+RFLOP(K)+DFVOP(K)
    XOAFLS(K,3,NU(NY,NX),NY,NX)=XOAFLS(K,3,NU(NY,NX),NY,NX)+RFLOA(K)+DFVOA(K)
  ENDDO
  XCOFLS(3,0,NY,NX)=XCOFLS(3,0,NY,NX)+RCOFLS0-RFLCOS-DFVCOS
  XCHFLS(3,0,NY,NX)=XCHFLS(3,0,NY,NX)+RCHFLS0-RFLCHS-DFVCHS
  XOXFLS(3,0,NY,NX)=XOXFLS(3,0,NY,NX)+ROXFLS0-RFLOXS-DFVOXS
  XNGFLS(3,0,NY,NX)=XNGFLS(3,0,NY,NX)+RNGFLS0-RFLNGS-DFVNGS
  XN2FLS(3,0,NY,NX)=XN2FLS(3,0,NY,NX)+RN2FLS0-RFLN2S-DFVN2S
  XHGFLS(3,0,NY,NX)=XHGFLS(3,0,NY,NX)-RFLHGS-DFVHGS
  XN4FLW(3,0,NY,NX)=XN4FLW(3,0,NY,NX)+RN4FLW0-RFLNH4-DFVNH4-RFLN4B-DFVN4B
  XN3FLW(3,0,NY,NX)=XN3FLW(3,0,NY,NX)+RN3FLW0-RFLNH3-DFVNH3-RFLN3B-DFVN3B
  XNOFLW(3,0,NY,NX)=XNOFLW(3,0,NY,NX)+RNOFLW0-RFLNO3-DFVNO3-RFLNOB-DFVNOB
  XNXFLS(3,0,NY,NX)=XNXFLS(3,0,NY,NX)-RFLNO2-DFVNO2-RFLN2B-DFVN2B
  XH1PFS(3,0,NY,NX)=XH1PFS(3,0,NY,NX)+RH1PFS0-RFLP14-DFVP14-RFLP1B-DFVP1B
  XH2PFS(3,0,NY,NX)=XH2PFS(3,0,NY,NX)+RH2PFS0-RFLPO4-DFVPO4-RFLPOB-DFVPOB
  XCOFLS(3,NU(NY,NX),NY,NX)=XCOFLS(3,NU(NY,NX),NY,NX)+RCOFLS1+RFLCOS+DFVCOS
  XCHFLS(3,NU(NY,NX),NY,NX)=XCHFLS(3,NU(NY,NX),NY,NX)+RCHFLS1+RFLCHS+DFVCHS
  XOXFLS(3,NU(NY,NX),NY,NX)=XOXFLS(3,NU(NY,NX),NY,NX)+ROXFLS1+RFLOXS+DFVOXS
  XNGFLS(3,NU(NY,NX),NY,NX)=XNGFLS(3,NU(NY,NX),NY,NX)+RNGFLS1+RFLNGS+DFVNGS
  XN2FLS(3,NU(NY,NX),NY,NX)=XN2FLS(3,NU(NY,NX),NY,NX)+RN2FLS1+RFLN2S+DFVN2S
  XHGFLS(3,NU(NY,NX),NY,NX)=XHGFLS(3,NU(NY,NX),NY,NX)+RFLHGS+DFVHGS
  XN4FLW(3,NU(NY,NX),NY,NX)=XN4FLW(3,NU(NY,NX),NY,NX)+RN4FLW1+RFLNH4+DFVNH4
  XN3FLW(3,NU(NY,NX),NY,NX)=XN3FLW(3,NU(NY,NX),NY,NX)+RN3FLW1+RFLNH3+DFVNH3
  XNOFLW(3,NU(NY,NX),NY,NX)=XNOFLW(3,NU(NY,NX),NY,NX)+RNOFLW1+RFLNO3+DFVNO3
  XNXFLS(3,NU(NY,NX),NY,NX)=XNXFLS(3,NU(NY,NX),NY,NX)+RFLNO2+DFVNO2
  XH1PFS(3,NU(NY,NX),NY,NX)=XH1PFS(3,NU(NY,NX),NY,NX)+RH1PFS1+RFLP14+DFVP14
  XH2PFS(3,NU(NY,NX),NY,NX)=XH2PFS(3,NU(NY,NX),NY,NX)+RH2PFS1+RFLPO4+DFVPO4
  XN4FLB(3,NU(NY,NX),NY,NX)=XN4FLB(3,NU(NY,NX),NY,NX)+RN4FLB1+RFLN4B+DFVN4B
  XN3FLB(3,NU(NY,NX),NY,NX)=XN3FLB(3,NU(NY,NX),NY,NX)+RN3FLB1+RFLN3B+DFVN3B
  XNOFLB(3,NU(NY,NX),NY,NX)=XNOFLB(3,NU(NY,NX),NY,NX)+RNOFLB1+RFLNOB+DFVNOB
  XNXFLB(3,NU(NY,NX),NY,NX)=XNXFLB(3,NU(NY,NX),NY,NX)+RFLN2B+DFVN2B
  XH1BFB(3,NU(NY,NX),NY,NX)=XH1BFB(3,NU(NY,NX),NY,NX)+RH1BFB1+RFLP1B+DFVP1B
  XH2BFB(3,NU(NY,NX),NY,NX)=XH2BFB(3,NU(NY,NX),NY,NX)+RH2BFB1+RFLPOB+DFVPOB
  end subroutine TotalPoreFluxAdjacentCell
!------------------------------------------------------------------------------------------

  subroutine MacroMicroTransfer(M,NY,NX)
  implicit none

  integer, intent(in) :: M, NY, NX
  integer :: K
  real(r8) :: VFLW
  real(r8) :: VOLWHS,VOLWT

!
!     FINHM=macro-micropore water transfer from watsub.f
!     VOLWM,VOLWHM=micropore,macropore water volume
!     RFL*=convective macropore-micropore solute transfer
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     *H2,*2=macropore,micropore solute content
!
!     MACROPORE TO MICROPORE TRANSFER
!
  IF(FINHM(M,NU(NY,NX),NY,NX).GT.0.0_r8)THEN
    IF(VOLWHM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      VFLW=AMAX1(0.0_r8,AMIN1(VFLWX,FINHM(M,NU(NY,NX),NY,NX) &
      /VOLWHM(M,NU(NY,NX),NY,NX)))
    ELSE
      VFLW=VFLWX
    ENDIF
    DO  K=0,jcplx1
      RFLOC(K)=VFLW*AMAX1(0.0_r8,OQCH2(K,NU(NY,NX),NY,NX))
      RFLON(K)=VFLW*AMAX1(0.0_r8,OQNH2(K,NU(NY,NX),NY,NX))
      RFLOP(K)=VFLW*AMAX1(0.0_r8,OQPH2(K,NU(NY,NX),NY,NX))
      RFLOA(K)=VFLW*AMAX1(0.0_r8,OQAH2(K,NU(NY,NX),NY,NX))
    ENDDO
    RFLCOS=VFLW*AMAX1(0.0_r8,CO2SH2(NU(NY,NX),NY,NX))
    RFLCHS=VFLW*AMAX1(0.0_r8,CH4SH2(NU(NY,NX),NY,NX))
    RFLOXS=VFLW*AMAX1(0.0_r8,OXYSH2(NU(NY,NX),NY,NX))
    RFLNGS=VFLW*AMAX1(0.0_r8,Z2GSH2(NU(NY,NX),NY,NX))
    RFLN2S=VFLW*AMAX1(0.0_r8,Z2OSH2(NU(NY,NX),NY,NX))
    RFLHGS=VFLW*AMAX1(0.0_r8,H2GSH2(NU(NY,NX),NY,NX))
    RFLNH4=VFLW*AMAX1(0.0_r8,ZNH4H2(NU(NY,NX),NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNH3=VFLW*AMAX1(0.0_r8,ZNH3H2(NU(NY,NX),NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNO3=VFLW*AMAX1(0.0_r8,ZNO3H2(NU(NY,NX),NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLNO2=VFLW*AMAX1(0.0_r8,ZNO2H2(NU(NY,NX),NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLP14=VFLW*AMAX1(0.0_r8,H1P4H2(NU(NY,NX),NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLPO4=VFLW*AMAX1(0.0_r8,H2P4H2(NU(NY,NX),NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLN4B=VFLW*AMAX1(0.0_r8,ZN4BH2(NU(NY,NX),NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLN3B=VFLW*AMAX1(0.0_r8,ZN3BH2(NU(NY,NX),NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLNOB=VFLW*AMAX1(0.0_r8,ZNOBH2(NU(NY,NX),NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLN2B=VFLW*AMAX1(0.0_r8,ZN2BH2(NU(NY,NX),NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLP1B=VFLW*AMAX1(0.0_r8,H1PBH2(NU(NY,NX),NY,NX))*VLPOB(NU(NY,NX),NY,NX)
    RFLPOB=VFLW*AMAX1(0.0_r8,H2PBH2(NU(NY,NX),NY,NX))*VLPOB(NU(NY,NX),NY,NX)
!
!     MICROPORE TO MACROPORE TRANSFER
!
  ELSEIF(FINHM(M,NU(NY,NX),NY,NX).LT.0.0_r8)THEN
    IF(VOLWM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      VFLW=AMIN1(0.0_r8,AMAX1(-VFLWX,FINHM(M,NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX)))
    ELSE
      VFLW=-VFLWX
    ENDIF
    DO  K=0,jcplx1
      RFLOC(K)=VFLW*AMAX1(0.0_r8,OQC2(K,NU(NY,NX),NY,NX))
      RFLON(K)=VFLW*AMAX1(0.0_r8,OQN2(K,NU(NY,NX),NY,NX))
      RFLOP(K)=VFLW*AMAX1(0.0_r8,OQP2(K,NU(NY,NX),NY,NX))
      RFLOA(K)=VFLW*AMAX1(0.0_r8,OQA2(K,NU(NY,NX),NY,NX))
    ENDDO
    RFLCOS=VFLW*AMAX1(0.0_r8,CO2S2(NU(NY,NX),NY,NX))
    RFLCHS=VFLW*AMAX1(0.0_r8,CH4S2(NU(NY,NX),NY,NX))
    RFLOXS=VFLW*AMAX1(0.0_r8,OXYS2(NU(NY,NX),NY,NX))
    RFLNGS=VFLW*AMAX1(0.0_r8,Z2GS2(NU(NY,NX),NY,NX))
    RFLN2S=VFLW*AMAX1(0.0_r8,Z2OS2(NU(NY,NX),NY,NX))
    RFLHGS=VFLW*AMAX1(0.0_r8,H2GS2(NU(NY,NX),NY,NX))
    RFLNH4=VFLW*AMAX1(0.0_r8,ZNH4S2(NU(NY,NX),NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNH3=VFLW*AMAX1(0.0_r8,ZNH3S2(NU(NY,NX),NY,NX))*VLNH4(NU(NY,NX),NY,NX)
    RFLNO3=VFLW*AMAX1(0.0_r8,ZNO3S2(NU(NY,NX),NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLNO2=VFLW*AMAX1(0.0_r8,ZNO2S2(NU(NY,NX),NY,NX))*VLNO3(NU(NY,NX),NY,NX)
    RFLP14=VFLW*AMAX1(0.0_r8,H1PO42(NU(NY,NX),NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLPO4=VFLW*AMAX1(0.0_r8,H2PO42(NU(NY,NX),NY,NX))*VLPO4(NU(NY,NX),NY,NX)
    RFLN4B=VFLW*AMAX1(0.0_r8,ZNH4B2(NU(NY,NX),NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLN3B=VFLW*AMAX1(0.0_r8,ZNH3B2(NU(NY,NX),NY,NX))*VLNHB(NU(NY,NX),NY,NX)
    RFLNOB=VFLW*AMAX1(0.0_r8,ZNO3B2(NU(NY,NX),NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLN2B=VFLW*AMAX1(0.0_r8,ZNO2B2(NU(NY,NX),NY,NX))*VLNOB(NU(NY,NX),NY,NX)
    RFLP1B=VFLW*AMAX1(0.0_r8,H1POB2(NU(NY,NX),NY,NX))*VLPOB(NU(NY,NX),NY,NX)
    RFLPOB=VFLW*AMAX1(0.0_r8,H2POB2(NU(NY,NX),NY,NX))*VLPOB(NU(NY,NX),NY,NX)
!
!     NO MACROPORE TO MICROPORE TRANSFER
!
  ELSE
    DO  K=0,jcplx1
      RFLOC(K)=0.0_r8
      RFLON(K)=0.0_r8
      RFLOP(K)=0.0_r8
      RFLOA(K)=0.0_r8
    ENDDO
    RFLCOS=0.0_r8
    RFLCHS=0.0_r8
    RFLOXS=0.0_r8
    RFLNGS=0.0_r8
    RFLN2S=0.0_r8
    RFLHGS=0.0_r8
    RFLNH4=0.0_r8
    RFLNH3=0.0_r8
    RFLNO3=0.0_r8
    RFLNO2=0.0_r8
    RFLP14=0.0_r8
    RFLPO4=0.0_r8
    RFLN4B=0.0_r8
    RFLN3B=0.0_r8
    RFLNOB=0.0_r8
    RFLN2B=0.0_r8
    RFLP1B=0.0_r8
    RFLPOB=0.0_r8
  ENDIF
!
!     DIFFUSIVE FLUXES OF SOLUTES BETWEEN MICROPORES AND
!     MACROPORES FROM AQUEOUS DIFFUSIVITIES AND CONCENTRATION DIFFERENCES
!
!     VOLWM,VOLWHM=micropore,macropore water volume
!     XFRS*VOLT=maximum macropore volume for solute transfer
!     DFV*=diffusive macropore-micropore solute transfer
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!     XNPH=1/no. of cycles h-1 for water, heat and solute flux calculations
!     *H2,*2=macropore,micropore solute content
!
  IF(VOLWHM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
    VOLWHS=AMIN1(XFRS*VOLT(NU(NY,NX),NY,NX),VOLWHM(M,NU(NY,NX),NY,NX))
    VOLWT=VOLWM(M,NU(NY,NX),NY,NX)+VOLWHS
    DO  K=0,jcplx1
      DFVOC(K)=XNPH*(AMAX1(0.0_r8,OQCH2(K,NU(NY,NX),NY,NX))*VOLWM(M,NU(NY,NX),NY,NX) &
        -AMAX1(0.0_r8,OQC2(K,NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
      DFVON(K)=XNPH*(AMAX1(0.0_r8,OQNH2(K,NU(NY,NX),NY,NX))*VOLWM(M,NU(NY,NX),NY,NX) &
        -AMAX1(0.0_r8,OQN2(K,NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
      DFVOP(K)=XNPH*(AMAX1(0.0_r8,OQPH2(K,NU(NY,NX),NY,NX))*VOLWM(M,NU(NY,NX),NY,NX) &
        -AMAX1(0.0_r8,OQP2(K,NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
      DFVOA(K)=XNPH*(AMAX1(0.0_r8,OQAH2(K,NU(NY,NX),NY,NX))*VOLWM(M,NU(NY,NX),NY,NX) &
        -AMAX1(0.0_r8,OQA2(K,NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    ENDDO
    DFVCOS=XNPH*(AMAX1(0.0_r8,CO2SH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,CO2S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVCHS=XNPH*(AMAX1(0.0_r8,CH4SH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,CH4S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVOXS=XNPH*(AMAX1(0.0_r8,OXYSH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,OXYS2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVNGS=XNPH*(AMAX1(0.0_r8,Z2GSH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,Z2GS2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVN2S=XNPH*(AMAX1(0.0_r8,Z2OSH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,Z2OS2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVHGS=XNPH*(AMAX1(0.0_r8,H2GSH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,H2GS2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT
    DFVNH4=XNPH*(AMAX1(0.0_r8,ZNH4H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNH4S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNH4(NU(NY,NX),NY,NX)
    DFVNH3=XNPH*(AMAX1(0.0_r8,ZNH3H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNH3S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNH4(NU(NY,NX),NY,NX)
    DFVNO3=XNPH*(AMAX1(0.0_r8,ZNO3H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNO3S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNO3(NU(NY,NX),NY,NX)
    DFVNO2=XNPH*(AMAX1(0.0_r8,ZNO2H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNO2S2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNO3(NU(NY,NX),NY,NX)
    DFVP14=XNPH*(AMAX1(0.0_r8,H1P4H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,H1PO42(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLPO4(NU(NY,NX),NY,NX)
    DFVPO4=XNPH*(AMAX1(0.0_r8,H2P4H2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,H2PO42(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLPO4(NU(NY,NX),NY,NX)
    DFVN4B=XNPH*(AMAX1(0.0_r8,ZN4BH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNH4B2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNHB(NU(NY,NX),NY,NX)
    DFVN3B=XNPH*(AMAX1(0.0_r8,ZN3BH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNH3B2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNHB(NU(NY,NX),NY,NX)
    DFVNOB=XNPH*(AMAX1(0.0_r8,ZNOBH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNO3B2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNOB(NU(NY,NX),NY,NX)
    DFVN2B=XNPH*(AMAX1(0.0_r8,ZN2BH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,ZNO2B2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLNOB(NU(NY,NX),NY,NX)
    DFVP1B=XNPH*(AMAX1(0.0_r8,H1PBH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,H1POB2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLPOB(NU(NY,NX),NY,NX)
    DFVPOB=XNPH*(AMAX1(0.0_r8,H2PBH2(NU(NY,NX),NY,NX)) &
      *VOLWM(M,NU(NY,NX),NY,NX) &
      -AMAX1(0.0_r8,H2POB2(NU(NY,NX),NY,NX))*VOLWHS)/VOLWT &
      *VLPOB(NU(NY,NX),NY,NX)
  ELSE
    DO  K=0,jcplx1
      DFVOC(K)=0.0_r8
      DFVON(K)=0.0_r8
      DFVOP(K)=0.0_r8
      DFVOA(K)=0.0_r8
    ENDDO
    DFVCOS=0.0_r8
    DFVCHS=0.0_r8
    DFVOXS=0.0_r8
    DFVNGS=0.0_r8
    DFVN2S=0.0_r8
    DFVHGS=0.0_r8
    DFVNH4=0.0_r8
    DFVNH3=0.0_r8
    DFVNO3=0.0_r8
    DFVNO2=0.0_r8
    DFVP14=0.0_r8
    DFVPO4=0.0_r8
    DFVN4B=0.0_r8
    DFVN3B=0.0_r8
    DFVNOB=0.0_r8
    DFVN2B=0.0_r8
    DFVP1B=0.0_r8
    DFVPOB=0.0_r8
  ENDIF
!
!     TOTAL CONVECTIVE +DIFFUSIVE TRANSFER BETWEEN MACROPOES AND MICROPORES
!
!     R*FXS=convective + diffusive solute flux between macropores and micropores
!     RFL*=convective flux between macropores and micropores
!     DFV*=diffusive solute flux between macropores and micropores
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!
  DO  K=0,jcplx1
    ROCFXS(K,NU(NY,NX),NY,NX)=RFLOC(K)+DFVOC(K)
    RONFXS(K,NU(NY,NX),NY,NX)=RFLON(K)+DFVON(K)
    ROPFXS(K,NU(NY,NX),NY,NX)=RFLOP(K)+DFVOP(K)
    ROAFXS(K,NU(NY,NX),NY,NX)=RFLOA(K)+DFVOA(K)
  ENDDO
  RCOFXS(NU(NY,NX),NY,NX)=RFLCOS+DFVCOS
  RCHFXS(NU(NY,NX),NY,NX)=RFLCHS+DFVCHS
  ROXFXS(NU(NY,NX),NY,NX)=RFLOXS+DFVOXS
  RNGFXS(NU(NY,NX),NY,NX)=RFLNGS+DFVNGS
  RN2FXS(NU(NY,NX),NY,NX)=RFLN2S+DFVN2S
  RHGFXS(NU(NY,NX),NY,NX)=RFLHGS+DFVHGS
  RN4FXW(NU(NY,NX),NY,NX)=RFLNH4+DFVNH4
  RN3FXW(NU(NY,NX),NY,NX)=RFLNH3+DFVNH3
  RNOFXW(NU(NY,NX),NY,NX)=RFLNO3+DFVNO3
  RNXFXS(NU(NY,NX),NY,NX)=RFLNO2+DFVNO2
  RH1PXS(NU(NY,NX),NY,NX)=RFLP14+DFVP14
  RH2PXS(NU(NY,NX),NY,NX)=RFLPO4+DFVPO4
  RN4FXB(NU(NY,NX),NY,NX)=RFLN4B+DFVN4B
  RN3FXB(NU(NY,NX),NY,NX)=RFLN3B+DFVN3B
  RNOFXB(NU(NY,NX),NY,NX)=RFLNOB+DFVNOB
  RNXFXB(NU(NY,NX),NY,NX)=RFLN2B+DFVN2B
  RH1BXB(NU(NY,NX),NY,NX)=RFLP1B+DFVP1B
  RH2BXB(NU(NY,NX),NY,NX)=RFLPOB+DFVPOB
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*FXS=hourly convective + diffusive solute flux between macropores and micropores
!     R*FXS=total convective + diffusive solute flux between macropores and micropores
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!
  DO  K=0,jcplx1
    XOCFXS(K,NU(NY,NX),NY,NX)=XOCFXS(K,NU(NY,NX),NY,NX)+ROCFXS(K,NU(NY,NX),NY,NX)
    XONFXS(K,NU(NY,NX),NY,NX)=XONFXS(K,NU(NY,NX),NY,NX)+RONFXS(K,NU(NY,NX),NY,NX)
    XOPFXS(K,NU(NY,NX),NY,NX)=XOPFXS(K,NU(NY,NX),NY,NX)+ROPFXS(K,NU(NY,NX),NY,NX)
    XOAFXS(K,NU(NY,NX),NY,NX)=XOAFXS(K,NU(NY,NX),NY,NX)+ROAFXS(K,NU(NY,NX),NY,NX)
  ENDDO
  XCOFXS(NU(NY,NX),NY,NX)=XCOFXS(NU(NY,NX),NY,NX)+RCOFXS(NU(NY,NX),NY,NX)
  XCHFXS(NU(NY,NX),NY,NX)=XCHFXS(NU(NY,NX),NY,NX)+RCHFXS(NU(NY,NX),NY,NX)
  XOXFXS(NU(NY,NX),NY,NX)=XOXFXS(NU(NY,NX),NY,NX)+ROXFXS(NU(NY,NX),NY,NX)
  XNGFXS(NU(NY,NX),NY,NX)=XNGFXS(NU(NY,NX),NY,NX)+RNGFXS(NU(NY,NX),NY,NX)
  XN2FXS(NU(NY,NX),NY,NX)=XN2FXS(NU(NY,NX),NY,NX)+RN2FXS(NU(NY,NX),NY,NX)
  XHGFXS(NU(NY,NX),NY,NX)=XHGFXS(NU(NY,NX),NY,NX)+RHGFXS(NU(NY,NX),NY,NX)
  XN4FXW(NU(NY,NX),NY,NX)=XN4FXW(NU(NY,NX),NY,NX)+RN4FXW(NU(NY,NX),NY,NX)
  XN3FXW(NU(NY,NX),NY,NX)=XN3FXW(NU(NY,NX),NY,NX)+RN3FXW(NU(NY,NX),NY,NX)
  XNOFXW(NU(NY,NX),NY,NX)=XNOFXW(NU(NY,NX),NY,NX)+RNOFXW(NU(NY,NX),NY,NX)
  XNXFXS(NU(NY,NX),NY,NX)=XNXFXS(NU(NY,NX),NY,NX)+RNXFXS(NU(NY,NX),NY,NX)
  XH1PXS(NU(NY,NX),NY,NX)=XH1PXS(NU(NY,NX),NY,NX)+RH1PXS(NU(NY,NX),NY,NX)
  XH2PXS(NU(NY,NX),NY,NX)=XH2PXS(NU(NY,NX),NY,NX)+RH2PXS(NU(NY,NX),NY,NX)
  XN4FXB(NU(NY,NX),NY,NX)=XN4FXB(NU(NY,NX),NY,NX)+RN4FXB(NU(NY,NX),NY,NX)
  XN3FXB(NU(NY,NX),NY,NX)=XN3FXB(NU(NY,NX),NY,NX)+RN3FXB(NU(NY,NX),NY,NX)
  XNOFXB(NU(NY,NX),NY,NX)=XNOFXB(NU(NY,NX),NY,NX)+RNOFXB(NU(NY,NX),NY,NX)
  XNXFXB(NU(NY,NX),NY,NX)=XNXFXB(NU(NY,NX),NY,NX)+RNXFXB(NU(NY,NX),NY,NX)
  XH1BXB(NU(NY,NX),NY,NX)=XH1BXB(NU(NY,NX),NY,NX)+RH1BXB(NU(NY,NX),NY,NX)
  XH2BXB(NU(NY,NX),NY,NX)=XH2BXB(NU(NY,NX),NY,NX)+RH2BXB(NU(NY,NX),NY,NX)
!
  end subroutine MacroMicroTransfer
!------------------------------------------------------------------------------------------

  subroutine OverlandFlowSnowdriftTransport(M,NY,NX,NHE,NHW,NVS,NVN)
  implicit none

  integer, intent(in) :: M, NY, NX, NHE, NHW, NVS, NVN
  real(r8) :: FQRM,VFLW
  integer :: K,N,NN,N1,N2,N4,N5,N4B,N5B
!     QRM=runoff from watsub.f
!     RQR*=solute in runoff
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VOLWM=litter water volume from watsub.f
!     *S2=litter solute content
!     N2,N1=NY,NX of source grid cell
!     N5,N4=NY,NX of destination grid cell
!     X*QRS=accumulated hourly solute in runoff
!
  N1=NX
  N2=NY
  IF(QRM(M,N2,N1).GT.ZEROS(N2,N1))THEN
    IF(VOLWM(M,0,N2,N1).GT.ZEROS2(N2,N1))THEN
      VFLW=AMIN1(VFLWX,QRM(M,N2,N1)/VOLWM(M,0,N2,N1))
    ELSE
      VFLW=VFLWX
    ENDIF
    DO  K=0,jcplx1
      RQROC0(K,N2,N1)=VFLW*AMAX1(0.0_r8,OQC2(K,0,N2,N1))
      RQRON0(K,N2,N1)=VFLW*AMAX1(0.0_r8,OQN2(K,0,N2,N1))
      RQROP0(K,N2,N1)=VFLW*AMAX1(0.0_r8,OQP2(K,0,N2,N1))
      RQROA0(K,N2,N1)=VFLW*AMAX1(0.0_r8,OQA2(K,0,N2,N1))
    ENDDO
    RQRCOS0(N2,N1)=VFLW*AMAX1(0.0_r8,CO2S2(0,N2,N1))
    RQRCHS0(N2,N1)=VFLW*AMAX1(0.0_r8,CH4S2(0,N2,N1))
    RQROXS0(N2,N1)=VFLW*AMAX1(0.0_r8,OXYS2(0,N2,N1))
    RQRNGS0(N2,N1)=VFLW*AMAX1(0.0_r8,Z2GS2(0,N2,N1))
    RQRN2S0(N2,N1)=VFLW*AMAX1(0.0_r8,Z2OS2(0,N2,N1))
    RQRHGS0(N2,N1)=VFLW*AMAX1(0.0_r8,H2GS2(0,N2,N1))
    RQRNH40(N2,N1)=VFLW*AMAX1(0.0_r8,ZNH4S2(0,N2,N1))
    RQRNH30(N2,N1)=VFLW*AMAX1(0.0_r8,ZNH3S2(0,N2,N1))
    RQRNO30(N2,N1)=VFLW*AMAX1(0.0_r8,ZNO3S2(0,N2,N1))
    RQRNO20(N2,N1)=VFLW*AMAX1(0.0_r8,ZNO2S2(0,N2,N1))
    RQRH1P0(N2,N1)=VFLW*AMAX1(0.0_r8,H1PO42(0,N2,N1))
    RQRH2P0(N2,N1)=VFLW*AMAX1(0.0_r8,H2PO42(0,N2,N1))
  ELSE
    DO K=0,jcplx1
      RQROC0(K,N2,N1)=0.0_r8
      RQRON0(K,N2,N1)=0.0_r8
      RQROP0(K,N2,N1)=0.0_r8
      RQROA0(K,N2,N1)=0.0_r8
    ENDDO
    RQRCOS0(N2,N1)=0.0_r8
    RQRCHS0(N2,N1)=0.0_r8
    RQROXS0(N2,N1)=0.0_r8
    RQRNGS0(N2,N1)=0.0_r8
    RQRN2S0(N2,N1)=0.0_r8
    RQRHGS0(N2,N1)=0.0_r8
    RQRNH40(N2,N1)=0.0_r8
    RQRNH30(N2,N1)=0.0_r8
    RQRNO30(N2,N1)=0.0_r8
    RQRNO20(N2,N1)=0.0_r8
    RQRH1P0(N2,N1)=0.0_r8
    RQRH2P0(N2,N1)=0.0_r8
  ENDIF
!
!     LOCATE INTERNAL BOUNDARIES BETWEEN ADJACENT GRID CELLS
!
  DO 4310 N=1,2
    DO 4305 NN=1,2
      IF(N.EQ.1)THEN
        IF(NX.EQ.NHE.AND.NN.EQ.1.OR.NX.EQ.NHW.AND.NN.EQ.2)THEN
          cycle
        ELSE
          N4=NX+1
          N5=NY
          N4B=NX-1
          N5B=NY
        ENDIF
      ELSEIF(N.EQ.2)THEN
        IF(NY.EQ.NVS.AND.NN.EQ.1.OR.NY.EQ.NVN.AND.NN.EQ.2)THEN
          cycle
        ELSE
          N4=NX
          N5=NY+1
          N4B=NX
          N5B=NY-1
        ENDIF
      ENDIF
!
!     QRM=runoff from watsub.f
!     RQR*=solute in runoff
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VOLWM=litter water volume from watsub.f
!     *S2=litter solute content
!
!     IF OVERLAND FLOW IS FROM CURRENT TO ADJACENT GRID CELL
!
      IF(QRM(M,N2,N1).GT.ZEROS(N2,N1))THEN
        IF(NN.EQ.1)THEN
          FQRM=QRMN(M,N,2,N5,N4)/QRM(M,N2,N1)
          DO  K=0,jcplx1
            RQROC(K,N,2,N5,N4)=RQROC0(K,N2,N1)*FQRM
            RQRON(K,N,2,N5,N4)=RQRON0(K,N2,N1)*FQRM
            RQROP(K,N,2,N5,N4)=RQROP0(K,N2,N1)*FQRM
            RQROA(K,N,2,N5,N4)=RQROA0(K,N2,N1)*FQRM
          ENDDO
          RQRCOS(N,2,N5,N4)=RQRCOS0(N2,N1)*FQRM
          RQRCHS(N,2,N5,N4)=RQRCHS0(N2,N1)*FQRM
          RQROXS(N,2,N5,N4)=RQROXS0(N2,N1)*FQRM
          RQRNGS(N,2,N5,N4)=RQRNGS0(N2,N1)*FQRM
          RQRN2S(N,2,N5,N4)=RQRN2S0(N2,N1)*FQRM
          RQRHGS(N,2,N5,N4)=RQRHGS0(N2,N1)*FQRM
          RQRNH4(N,2,N5,N4)=RQRNH40(N2,N1)*FQRM
          RQRNH3(N,2,N5,N4)=RQRNH30(N2,N1)*FQRM
          RQRNO3(N,2,N5,N4)=RQRNO30(N2,N1)*FQRM
          RQRNO2(N,2,N5,N4)=RQRNO20(N2,N1)*FQRM
          RQRH1P(N,2,N5,N4)=RQRH1P0(N2,N1)*FQRM
          RQRH2P(N,2,N5,N4)=RQRH2P0(N2,N1)*FQRM
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     XQR*=hourly solute in runoff
!     RQR*=solute in runoff
!
          DO  K=0,jcplx1
            XOCQRS(K,N,2,N5,N4)=XOCQRS(K,N,2,N5,N4)+RQROC(K,N,2,N5,N4)
            XONQRS(K,N,2,N5,N4)=XONQRS(K,N,2,N5,N4)+RQRON(K,N,2,N5,N4)
            XOPQRS(K,N,2,N5,N4)=XOPQRS(K,N,2,N5,N4)+RQROP(K,N,2,N5,N4)
            XOAQRS(K,N,2,N5,N4)=XOAQRS(K,N,2,N5,N4)+RQROA(K,N,2,N5,N4)
          ENDDO
          XCOQRS(N,2,N5,N4)=XCOQRS(N,2,N5,N4)+RQRCOS(N,2,N5,N4)
          XCHQRS(N,2,N5,N4)=XCHQRS(N,2,N5,N4)+RQRCHS(N,2,N5,N4)
          XOXQRS(N,2,N5,N4)=XOXQRS(N,2,N5,N4)+RQROXS(N,2,N5,N4)
          XNGQRS(N,2,N5,N4)=XNGQRS(N,2,N5,N4)+RQRNGS(N,2,N5,N4)
          XN2QRS(N,2,N5,N4)=XN2QRS(N,2,N5,N4)+RQRN2S(N,2,N5,N4)
          XHGQRS(N,2,N5,N4)=XHGQRS(N,2,N5,N4)+RQRHGS(N,2,N5,N4)
          XN4QRW(N,2,N5,N4)=XN4QRW(N,2,N5,N4)+RQRNH4(N,2,N5,N4)
          XN3QRW(N,2,N5,N4)=XN3QRW(N,2,N5,N4)+RQRNH3(N,2,N5,N4)
          XNOQRW(N,2,N5,N4)=XNOQRW(N,2,N5,N4)+RQRNO3(N,2,N5,N4)
          XNXQRS(N,2,N5,N4)=XNXQRS(N,2,N5,N4)+RQRNO2(N,2,N5,N4)
          XP1QRW(N,2,N5,N4)=XP1QRW(N,2,N5,N4)+RQRH1P(N,2,N5,N4)
          XP4QRW(N,2,N5,N4)=XP4QRW(N,2,N5,N4)+RQRH2P(N,2,N5,N4)
        ELSE
          DO K=0,jcplx1
            RQROC(K,N,2,N5,N4)=0.0_r8
            RQRON(K,N,2,N5,N4)=0.0_r8
            RQROP(K,N,2,N5,N4)=0.0_r8
            RQROA(K,N,2,N5,N4)=0.0_r8
          ENDDO
          RQRCOS(N,2,N5,N4)=0.0_r8
          RQRCHS(N,2,N5,N4)=0.0_r8
          RQROXS(N,2,N5,N4)=0.0_r8
          RQRNGS(N,2,N5,N4)=0.0_r8
          RQRN2S(N,2,N5,N4)=0.0_r8
          RQRHGS(N,2,N5,N4)=0.0_r8
          RQRNH4(N,2,N5,N4)=0.0_r8
          RQRNH3(N,2,N5,N4)=0.0_r8
          RQRNO3(N,2,N5,N4)=0.0_r8
          RQRNO2(N,2,N5,N4)=0.0_r8
          RQRH1P(N,2,N5,N4)=0.0_r8
          RQRH2P(N,2,N5,N4)=0.0_r8
        ENDIF
!
!     IF OVERLAND FLOW IS FROM CURRENT TO ADJACENT GRID CELL
!
        IF(NN.EQ.2)THEN
          IF(N4B.GT.0.AND.N5B.GT.0)THEN
            FQRM=QRMN(M,N,1,N5B,N4B)/QRM(M,N2,N1)
            DO  K=0,jcplx1
              RQROC(K,N,1,N5B,N4B)=RQROC0(K,N2,N1)*FQRM
              RQRON(K,N,1,N5B,N4B)=RQRON0(K,N2,N1)*FQRM
              RQROP(K,N,1,N5B,N4B)=RQROP0(K,N2,N1)*FQRM
              RQROA(K,N,1,N5B,N4B)=RQROA0(K,N2,N1)*FQRM
            ENDDO
            RQRCOS(N,1,N5B,N4B)=RQRCOS0(N2,N1)*FQRM
            RQRCHS(N,1,N5B,N4B)=RQRCHS0(N2,N1)*FQRM
            RQROXS(N,1,N5B,N4B)=RQROXS0(N2,N1)*FQRM
            RQRNGS(N,1,N5B,N4B)=RQRNGS0(N2,N1)*FQRM
            RQRN2S(N,1,N5B,N4B)=RQRN2S0(N2,N1)*FQRM
            RQRHGS(N,1,N5B,N4B)=RQRHGS0(N2,N1)*FQRM
            RQRNH4(N,1,N5B,N4B)=RQRNH40(N2,N1)*FQRM
            RQRNH3(N,1,N5B,N4B)=RQRNH30(N2,N1)*FQRM
            RQRNO3(N,1,N5B,N4B)=RQRNO30(N2,N1)*FQRM
            RQRNO2(N,1,N5B,N4B)=RQRNO20(N2,N1)*FQRM
            RQRH1P(N,1,N5B,N4B)=RQRH1P0(N2,N1)*FQRM
            RQRH2P(N,1,N5B,N4B)=RQRH2P0(N2,N1)*FQRM
            DO K=0,jcplx1
              XOCQRS(K,N,1,N5B,N4B)=XOCQRS(K,N,1,N5B,N4B)+RQROC(K,N,1,N5B,N4B)
              XONQRS(K,N,1,N5B,N4B)=XONQRS(K,N,1,N5B,N4B)+RQRON(K,N,1,N5B,N4B)
              XOPQRS(K,N,1,N5B,N4B)=XOPQRS(K,N,1,N5B,N4B)+RQROP(K,N,1,N5B,N4B)
              XOAQRS(K,N,1,N5B,N4B)=XOAQRS(K,N,1,N5B,N4B)+RQROA(K,N,1,N5B,N4B)
            ENDDO
            XCOQRS(N,1,N5B,N4B)=XCOQRS(N,1,N5B,N4B)+RQRCOS(N,1,N5B,N4B)
            XCHQRS(N,1,N5B,N4B)=XCHQRS(N,1,N5B,N4B)+RQRCHS(N,1,N5B,N4B)
            XOXQRS(N,1,N5B,N4B)=XOXQRS(N,1,N5B,N4B)+RQROXS(N,1,N5B,N4B)
            XNGQRS(N,1,N5B,N4B)=XNGQRS(N,1,N5B,N4B)+RQRNGS(N,1,N5B,N4B)
            XN2QRS(N,1,N5B,N4B)=XN2QRS(N,1,N5B,N4B)+RQRN2S(N,1,N5B,N4B)
            XHGQRS(N,1,N5B,N4B)=XHGQRS(N,1,N5B,N4B)+RQRHGS(N,1,N5B,N4B)
            XN4QRW(N,1,N5B,N4B)=XN4QRW(N,1,N5B,N4B)+RQRNH4(N,1,N5B,N4B)
            XN3QRW(N,1,N5B,N4B)=XN3QRW(N,1,N5B,N4B)+RQRNH3(N,1,N5B,N4B)
            XNOQRW(N,1,N5B,N4B)=XNOQRW(N,1,N5B,N4B)+RQRNO3(N,1,N5B,N4B)
            XNXQRS(N,1,N5B,N4B)=XNXQRS(N,1,N5B,N4B)+RQRNO2(N,1,N5B,N4B)
            XP1QRW(N,1,N5B,N4B)=XP1QRW(N,1,N5B,N4B)+RQRH1P(N,1,N5B,N4B)
            XP4QRW(N,1,N5B,N4B)=XP4QRW(N,1,N5B,N4B)+RQRH2P(N,1,N5B,N4B)
          ELSE
            DO  K=0,jcplx1
              RQROC(K,N,1,N5B,N4B)=0.0_r8
              RQRON(K,N,1,N5B,N4B)=0.0_r8
              RQROP(K,N,1,N5B,N4B)=0.0_r8
              RQROA(K,N,1,N5B,N4B)=0.0_r8
            ENDDO
            RQRCOS(N,1,N5B,N4B)=0.0_r8
            RQRCHS(N,1,N5B,N4B)=0.0_r8
            RQROXS(N,1,N5B,N4B)=0.0_r8
            RQRNGS(N,1,N5B,N4B)=0.0_r8
            RQRN2S(N,1,N5B,N4B)=0.0_r8
            RQRHGS(N,1,N5B,N4B)=0.0_r8
            RQRNH4(N,1,N5B,N4B)=0.0_r8
            RQRNH3(N,1,N5B,N4B)=0.0_r8
            RQRNO3(N,1,N5B,N4B)=0.0_r8
            RQRNO2(N,1,N5B,N4B)=0.0_r8
            RQRH1P(N,1,N5B,N4B)=0.0_r8
            RQRH2P(N,1,N5B,N4B)=0.0_r8
          ENDIF
        ENDIF
      ELSE
        DO K=0,jcplx1
          RQROC(K,N,2,N5,N4)=0.0_r8
          RQRON(K,N,2,N5,N4)=0.0_r8
          RQROP(K,N,2,N5,N4)=0.0_r8
          RQROA(K,N,2,N5,N4)=0.0_r8
        ENDDO
        RQRCOS(N,2,N5,N4)=0.0_r8
        RQRCHS(N,2,N5,N4)=0.0_r8
        RQROXS(N,2,N5,N4)=0.0_r8
        RQRNGS(N,2,N5,N4)=0.0_r8
        RQRN2S(N,2,N5,N4)=0.0_r8
        RQRHGS(N,2,N5,N4)=0.0_r8
        RQRNH4(N,2,N5,N4)=0.0_r8
        RQRNH3(N,2,N5,N4)=0.0_r8
        RQRNO3(N,2,N5,N4)=0.0_r8
        RQRNO2(N,2,N5,N4)=0.0_r8
        RQRH1P(N,2,N5,N4)=0.0_r8
        RQRH2P(N,2,N5,N4)=0.0_r8
        IF(N4B.GT.0.AND.N5B.GT.0)THEN
          DO  K=0,jcplx1
            RQROC(K,N,1,N5B,N4B)=0.0_r8
            RQRON(K,N,1,N5B,N4B)=0.0_r8
            RQROP(K,N,1,N5B,N4B)=0.0_r8
            RQROA(K,N,1,N5B,N4B)=0.0_r8
          ENDDO
          RQRCOS(N,1,N5B,N4B)=0.0_r8
          RQRCHS(N,1,N5B,N4B)=0.0_r8
          RQROXS(N,1,N5B,N4B)=0.0_r8
          RQRNGS(N,1,N5B,N4B)=0.0_r8
          RQRN2S(N,1,N5B,N4B)=0.0_r8
          RQRHGS(N,1,N5B,N4B)=0.0_r8
          RQRNH4(N,1,N5B,N4B)=0.0_r8
          RQRNH3(N,1,N5B,N4B)=0.0_r8
          RQRNO3(N,1,N5B,N4B)=0.0_r8
          RQRNO2(N,1,N5B,N4B)=0.0_r8
          RQRH1P(N,1,N5B,N4B)=0.0_r8
          RQRH2P(N,1,N5B,N4B)=0.0_r8
        ENDIF
      ENDIF
!
!     SNOW DRIFT
!
!     subroutine SnowdriftTransport(M)
!
!     QSM=snow transfer from watsub.f
!     RQS*=solute flux in snow transfer
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     VOLS=volume of snowpack from watsub.f
!     *W2=solute content of snowpack
!
      IF(NN.EQ.1)THEN
!
!     IF NO SNOW DRIFT THEN NO TRANSPORT
!
        IF(ABS(QSM(M,N,N5,N4)).LE.ZEROS2(N2,N1))THEN
          RQSCOS(N,N5,N4)=0.0_r8
          RQSCHS(N,N5,N4)=0.0_r8
          RQSOXS(N,N5,N4)=0.0_r8
          RQSNGS(N,N5,N4)=0.0_r8
          RQSN2S(N,N5,N4)=0.0_r8
          RQSNH4(N,N5,N4)=0.0_r8
          RQSNH3(N,N5,N4)=0.0_r8
          RQSNO3(N,N5,N4)=0.0_r8
          RQSH1P(N,N5,N4)=0.0_r8
          RQSH2P(N,N5,N4)=0.0_r8
    !
!     IF DRIFT IS FROM CURRENT TO ADJACENT GRID CELL
!
        ELSEIF(QSM(M,N,N5,N4).GT.ZEROS2(N2,N1))THEN
          IF(VOLS(N2,N1).GT.ZEROS2(N2,N1))THEN
            VFLW=AMAX1(0.0_r8,AMIN1(VFLWX,QSM(M,N,N5,N4)/VOLS(N2,N1)))
          ELSE
            VFLW=VFLWX
          ENDIF
          RQSCOS(N,N5,N4)=VFLW*AMAX1(0.0_r8,CO2W2(1,N2,N1))
          RQSCHS(N,N5,N4)=VFLW*AMAX1(0.0_r8,CH4W2(1,N2,N1))
          RQSOXS(N,N5,N4)=VFLW*AMAX1(0.0_r8,OXYW2(1,N2,N1))
          RQSNGS(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZNGW2(1,N2,N1))
          RQSN2S(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN2W2(1,N2,N1))
          RQSNH4(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN4W2(1,N2,N1))
          RQSNH3(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN3W2(1,N2,N1))
          RQSNO3(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZNOW2(1,N2,N1))
          RQSH1P(N,N5,N4)=VFLW*AMAX1(0.0_r8,Z1PW2(1,N2,N1))
          RQSH2P(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZHPW2(1,N2,N1))
!
!     IF DRIFT IS TO CURRENT FROM ADJACENT GRID CELL
!
        ELSEIF(QSM(M,N,N5,N4).LT.-ZEROS2(N2,N1))THEN
          IF(VOLS(N5,N4).GT.ZEROS2(N5,N4))THEN
            VFLW=AMIN1(0.0_r8,AMAX1(-VFLWX,QSM(M,N,N5,N4)/VOLS(N5,N4)))
          ELSE
            VFLW=-VFLWX
          ENDIF
          RQSCOS(N,N5,N4)=VFLW*AMAX1(0.0_r8,CO2W2(1,N5,N4))
          RQSCHS(N,N5,N4)=VFLW*AMAX1(0.0_r8,CH4W2(1,N5,N4))
          RQSOXS(N,N5,N4)=VFLW*AMAX1(0.0_r8,OXYW2(1,N5,N4))
          RQSNGS(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZNGW2(1,N5,N4))
          RQSN2S(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN2W2(1,N5,N4))
          RQSNH4(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN4W2(1,N5,N4))
          RQSNH3(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZN3W2(1,N5,N4))
          RQSNO3(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZNOW2(1,N5,N4))
          RQSH1P(N,N5,N4)=VFLW*AMAX1(0.0_r8,Z1PW2(1,N5,N4))
          RQSH2P(N,N5,N4)=VFLW*AMAX1(0.0_r8,ZHPW2(1,N5,N4))
        ENDIF
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*QSS=hourly solute in snow flux
!     RQS*=solute in snow flux
!
        XCOQSS(N,N5,N4)=XCOQSS(N,N5,N4)+RQSCOS(N,N5,N4)
        XCHQSS(N,N5,N4)=XCHQSS(N,N5,N4)+RQSCHS(N,N5,N4)
        XOXQSS(N,N5,N4)=XOXQSS(N,N5,N4)+RQSOXS(N,N5,N4)
        XNGQSS(N,N5,N4)=XNGQSS(N,N5,N4)+RQSNGS(N,N5,N4)
        XN2QSS(N,N5,N4)=XN2QSS(N,N5,N4)+RQSN2S(N,N5,N4)
        XN4QSS(N,N5,N4)=XN4QSS(N,N5,N4)+RQSNH4(N,N5,N4)
        XN3QSS(N,N5,N4)=XN3QSS(N,N5,N4)+RQSNH3(N,N5,N4)
        XNOQSS(N,N5,N4)=XNOQSS(N,N5,N4)+RQSNO3(N,N5,N4)
        XP1QSS(N,N5,N4)=XP1QSS(N,N5,N4)+RQSH1P(N,N5,N4)
        XP4QSS(N,N5,N4)=XP4QSS(N,N5,N4)+RQSH2P(N,N5,N4)
      ENDIF
4305  CONTINUE
4310  CONTINUE
  end subroutine OverlandFlowSnowdriftTransport
!------------------------------------------------------------------------------------------

  subroutine SurfaceGasVolatilDissol(M,NY,NX)
  implicit none

  integer, intent(in) :: M,NY, NX
  real(r8) :: VOLHGR(JY,JX),VOLN3R(JY,JX)
  real(r8) :: VOLN2R(JY,JX),VOLOXR(JY,JX)
  real(r8) :: VOLCOR(JY,JX),VOLCHR(JY,JX)
  real(r8) :: VOLNGR(JY,JX)
  real(r8) :: CNH3S0,CNH4S0,CO2G0,CH4G0
  real(r8) :: Z2GG0,Z2OG0,ZN3G0,H2GG0,OXYG0
!
!     VOLT=litter volume from hour1.f
!     VOLWM,VOLPM=micropore water volume, air volume from watsub.f
!     VOLW*=equivalent aqueous volume for gas
!     S*L=solubility of gas in water from hour1.f
!     C*G=gas concentration
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     R*DFG=surface gas volatilization
!     DFGS=rate constant for air-water gas exchange from watsub.f
!     *S2=litter solute content
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     R*DXR=gas exchange between atmosphere and surface litter water for gas flux calculations
!
  IF(VOLT(0,NY,NX).GT.ZEROS2(NY,NX) &
    .AND.VOLPM(M,0,NY,NX).GT.ZEROS2(NY,NX) &
    .AND.VOLWM(M,0,NY,NX).GT.ZEROS2(NY,NX))THEN
    VOLWCO(0,NY,NX)=VOLWM(M,0,NY,NX)*SCO2L(0,NY,NX)
    VOLWCH(0,NY,NX)=VOLWM(M,0,NY,NX)*SCH4L(0,NY,NX)
    VOLWOX(0,NY,NX)=VOLWM(M,0,NY,NX)*SOXYL(0,NY,NX)
    VOLWNG(0,NY,NX)=VOLWM(M,0,NY,NX)*SN2GL(0,NY,NX)
    VOLWN2(0,NY,NX)=VOLWM(M,0,NY,NX)*SN2OL(0,NY,NX)
    VOLWN3(0,NY,NX)=VOLWM(M,0,NY,NX)*SNH3L(0,NY,NX)
    VOLWHG(0,NY,NX)=VOLWM(M,0,NY,NX)*SH2GL(0,NY,NX)
    VOLWXA(0,NY,NX)=14.0_r8*VOLWM(M,0,NY,NX)
    CO2G0=CCO2G(0,NY,NX)*VOLPM(M,0,NY,NX)
    CH4G0=CCH4G(0,NY,NX)*VOLPM(M,0,NY,NX)
    OXYG0=COXYG(0,NY,NX)*VOLPM(M,0,NY,NX)
    Z2GG0=CZ2GG(0,NY,NX)*VOLPM(M,0,NY,NX)
    Z2OG0=CZ2OG(0,NY,NX)*VOLPM(M,0,NY,NX)
    ZN3G0=CNH3G(0,NY,NX)*VOLPM(M,0,NY,NX)
    H2GG0=CH2GG(0,NY,NX)*VOLPM(M,0,NY,NX)
    VOLCOR(NY,NX)=VOLWCO(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLCHR(NY,NX)=VOLWCH(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLOXR(NY,NX)=VOLWOX(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLNGR(NY,NX)=VOLWNG(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLN2R(NY,NX)=VOLWN2(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLN3R(NY,NX)=VOLWN3(0,NY,NX)+VOLPM(M,0,NY,NX)
    VOLHGR(NY,NX)=VOLWHG(0,NY,NX)+VOLPM(M,0,NY,NX)
    RCODFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),CO2G0)*VOLWCO(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),CO2S2(0,NY,NX)+RCODXR) &
      *VOLPM(M,0,NY,NX))/VOLCOR(NY,NX)
    RCHDFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),CH4G0)*VOLWCH(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),CH4S2(0,NY,NX)+RCHDXR) &
      *VOLPM(M,0,NY,NX))/VOLCHR(NY,NX)
    ROXDFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),OXYG0)*VOLWOX(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),OXYS2(0,NY,NX)+ROXDXR) &
      *VOLPM(M,0,NY,NX))/VOLOXR(NY,NX)
    RNGDFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),Z2GG0)*VOLWNG(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),Z2GS2(0,NY,NX)+RNGDXR) &
      *VOLPM(M,0,NY,NX))/VOLNGR(NY,NX)
    RN2DFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),Z2OG0)*VOLWN2(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),Z2OS2(0,NY,NX)+RN2DXR) &
      *VOLPM(M,0,NY,NX))/VOLN2R(NY,NX)
    RN3DFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),ZN3G0)*VOLWN3(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),ZNH3S2(0,NY,NX)+RN3DXR) &
      *VOLPM(M,0,NY,NX))/VOLN3R(NY,NX)
    CNH3S0=AMAX1(0.0_r8,(ZNH3S2(0,NY,NX)+RN3DFG(0,NY,NX)))/VOLWXA(0,NY,NX)
    CNH4S0=AMAX1(0.0_r8,ZNH4S2(0,NY,NX))/VOLWXA(0,NY,NX)
    RHGDFG(0,NY,NX)=DFGS(M,0,NY,NX) &
      *(AMAX1(ZEROS(NY,NX),H2GG0)*VOLWHG(0,NY,NX) &
      -AMAX1(ZEROS(NY,NX),H2GS2(0,NY,NX)+RHGDXR) &
      *VOLPM(M,0,NY,NX))/VOLHGR(NY,NX)

!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*DFG=hourly surface gas volatilization
!     R*DFG=surface gas volatilization
!
    XCODFG(0,NY,NX)=XCODFG(0,NY,NX)+RCODFG(0,NY,NX)
    XCHDFG(0,NY,NX)=XCHDFG(0,NY,NX)+RCHDFG(0,NY,NX)
    XOXDFG(0,NY,NX)=XOXDFG(0,NY,NX)+ROXDFG(0,NY,NX)
    XNGDFG(0,NY,NX)=XNGDFG(0,NY,NX)+RNGDFG(0,NY,NX)
    XN2DFG(0,NY,NX)=XN2DFG(0,NY,NX)+RN2DFG(0,NY,NX)
    XN3DFG(0,NY,NX)=XN3DFG(0,NY,NX)+RN3DFG(0,NY,NX)
    XHGDFG(0,NY,NX)=XHGDFG(0,NY,NX)+RHGDFG(0,NY,NX)
  ELSE
    RCODFG(0,NY,NX)=0.0_r8
    RCHDFG(0,NY,NX)=0.0_r8
    ROXDFG(0,NY,NX)=0.0_r8
    RNGDFG(0,NY,NX)=0.0_r8
    RN2DFG(0,NY,NX)=0.0_r8
    RN3DFG(0,NY,NX)=0.0_r8
    RHGDFG(0,NY,NX)=0.0_r8
  ENDIF
  end subroutine SurfaceGasVolatilDissol

!------------------------------------------------------------------------------------------

  subroutine GasDiffusionConvection(M,NY,NX,FLQM)
  implicit none

  integer, intent(in) :: M, NY, NX
  real(r8),intent(in) :: FLQM(3,JD,JV,JH)
  real(r8) :: VFLW
  real(r8) :: VOLHGT(JY,JX),VOLNBT(JY,JX)
  real(r8) :: VOLN3T(JY,JX),VOLN2T(JY,JX)
  real(r8) :: VOLCOT(JY,JX),VOLCHT(JY,JX)
  real(r8) :: VOLOXT(JY,JX),VOLNGT(JY,JX)
  real(r8) :: CNH3S0,CCH4G2,CH2GG2
  real(r8) :: CNH3B0,CNH4B0,CNH4S0
  real(r8) :: CCO2G2,COXYG2,CZ2GG2,CZ2OG2,CNH3G2
  real(r8) :: DFVHGG,DFVN3G,DFVN2G,DFLG2
  real(r8) :: DNH3GQ,DH2GGQ
  real(r8) :: DFVCOG,DFVCHG,DFVOXG,DFVNGG
  real(r8) :: DCO2GQ,DCH4GQ,DOXYGQ,DZ2GGQ,DZ2OGQ
  real(r8) :: RFLCOG,RFLCHG,RFLOXG,RFLNGG,RFLN2G,RFLN3G,RFLH2G
!
!     THETPM=air-filled porosity from watsub.f
!     BKDS=bulk density
!
  IF(THETPM(M,NU(NY,NX),NY,NX).GT.THETX.AND.BKDS(NU(NY,NX),NY,NX).GT.ZERO)THEN
!
!     GASEOUS DIFFUSIVITIES
!
!     DFLG2=air-filled porosity effect on gaseous diffusivity
!     POROQ=Penman Water Linear Reduction tortuosity from starts.f
!     POROS=total porosity
!     DLYR=soil layer thickness
!     D*G=gaseous diffusivity in soil
!     *SGL2= gaseous diffusivity in air
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!
    DFLG2=AMAX1(0.0_r8,THETPM(M,NU(NY,NX),NY,NX))*POROQ &
      *THETPM(M,NU(NY,NX),NY,NX)/POROS(NU(NY,NX),NY,NX) &
      *AREA(3,NU(NY,NX),NY,NX)/AMAX1(ZERO2,DLYR(3,NU(NY,NX),NY,NX))
    DCO2G(3,NU(NY,NX),NY,NX)=DFLG2*CGSGL2(NU(NY,NX),NY,NX)
    DCH4G(3,NU(NY,NX),NY,NX)=DFLG2*CHSGL2(NU(NY,NX),NY,NX)
    DOXYG(3,NU(NY,NX),NY,NX)=DFLG2*OGSGL2(NU(NY,NX),NY,NX)
    DZ2GG(3,NU(NY,NX),NY,NX)=DFLG2*ZGSGL2(NU(NY,NX),NY,NX)
    DZ2OG(3,NU(NY,NX),NY,NX)=DFLG2*Z2SGL2(NU(NY,NX),NY,NX)
    DNH3G(3,NU(NY,NX),NY,NX)=DFLG2*ZHSGL2(NU(NY,NX),NY,NX)
    DH2GG(3,NU(NY,NX),NY,NX)=DFLG2*HGSGL2(NU(NY,NX),NY,NX)
!
!     SURFACE GAS CONCENTRATIONS
!
!     C*G2=gaseous concentration
!     *G2=gaseous content
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     VOLPM=air-filled porosity
!
    CCO2G2=AMAX1(0.0_r8,CO2G2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    CCH4G2=AMAX1(0.0_r8,CH4G2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    COXYG2=AMAX1(0.0_r8,OXYG2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    CZ2GG2=AMAX1(0.0_r8,Z2GG2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    CZ2OG2=AMAX1(0.0_r8,Z2OG2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    CNH3G2=AMAX1(0.0_r8,ZN3G2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
    CH2GG2=AMAX1(0.0_r8,H2GG2(NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX))
!
!     EQUILIBRIUM CONCENTRATIONS AT SOIL SURFACE AT WHICH
!     GASEOUS DIFFUSION THROUGH SOIL SURFACE LAYER = GASEOUS
!     DIFFUSION THROUGH ATMOSPHERE BOUNDARY LAYER CALCULATED
!     FROM GASEOUS DIFFUSIVITY AND BOUNDARY LAYER CONDUCTANCE
!
!     D*GQ=gaseous diffusivity between soil surface and atmosphere
!     D*G=gaseous diffusivity in soil
!     PARG*=boundary layer conductance above soil surface
!     DFV*G=diffusive gas flux
!     C*E=atmospheric gas concentration from hour1.f
!     C*G2=gaseous concentration
!
    DCO2GQ=DCO2G(3,NU(NY,NX),NY,NX)*PARGCO(NY,NX)/(DCO2G(3,NU(NY,NX),NY,NX)+PARGCO(NY,NX))
    DCH4GQ=DCH4G(3,NU(NY,NX),NY,NX)*PARGCH(NY,NX)/(DCH4G(3,NU(NY,NX),NY,NX)+PARGCH(NY,NX))
    DOXYGQ=DOXYG(3,NU(NY,NX),NY,NX)*PARGOX(NY,NX)/(DOXYG(3,NU(NY,NX),NY,NX)+PARGOX(NY,NX))
    DZ2GGQ=DZ2GG(3,NU(NY,NX),NY,NX)*PARGNG(NY,NX)/(DZ2GG(3,NU(NY,NX),NY,NX)+PARGNG(NY,NX))
    DZ2OGQ=DZ2OG(3,NU(NY,NX),NY,NX)*PARGN2(NY,NX)/(DZ2OG(3,NU(NY,NX),NY,NX)+PARGN2(NY,NX))
    DNH3GQ=DNH3G(3,NU(NY,NX),NY,NX)*PARGN3(NY,NX)/(DNH3G(3,NU(NY,NX),NY,NX)+PARGN3(NY,NX))
    DH2GGQ=DH2GG(3,NU(NY,NX),NY,NX)*PARGH2(NY,NX)/(DH2GG(3,NU(NY,NX),NY,NX)+PARGH2(NY,NX))
    DFVCOG=DCO2GQ*(CCO2E(NY,NX)-CCO2G2)
    DFVCHG=DCH4GQ*(CCH4E(NY,NX)-CCH4G2)
    DFVOXG=DOXYGQ*(COXYE(NY,NX)-COXYG2)
    DFVNGG=DZ2GGQ*(CZ2GE(NY,NX)-CZ2GG2)
    DFVN2G=DZ2OGQ*(CZ2OE(NY,NX)-CZ2OG2)
    DFVN3G=DNH3GQ*(CNH3E(NY,NX)-CNH3G2)
    DFVHGG=DH2GGQ*(CH2GE(NY,NX)-CH2GG2)
!
!     CONVECTIVE GAS TRANSFER DRIVEN BY SURFACE WATER FLUXES
!     FROM 'WATSUB' AND GAS CONCENTRATIONS IN THE SOIL SURFACE
!     OR THE ATMOSPHERE DEPENDING ON WATER FLUX DIRECTION
!
!     FLQM=total water flux into soil micropore+macropore from watsub.f
!     VOLPM=air-filled porosity
!     RFL*G=convective gas flux
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     *G2=gaseous content
!     C*E=atmospheric gas concentration from hour1.f
!
    IF(FLQM(3,NU(NY,NX),NY,NX).GT.0.0_r8)THEN
      IF(VOLPM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
        VFLW=-AMAX1(0.0_r8,AMIN1(VFLWX,FLQM(3,NU(NY,NX),NY,NX)/VOLPM(M,NU(NY,NX),NY,NX)))
      ELSE
        VFLW=-VFLWX
      ENDIF
      RFLCOG=VFLW*AMAX1(0.0_r8,CO2G2(NU(NY,NX),NY,NX))
      RFLCHG=VFLW*AMAX1(0.0_r8,CH4G2(NU(NY,NX),NY,NX))
      RFLOXG=VFLW*AMAX1(0.0_r8,OXYG2(NU(NY,NX),NY,NX))
      RFLNGG=VFLW*AMAX1(0.0_r8,Z2GG2(NU(NY,NX),NY,NX))
      RFLN2G=VFLW*AMAX1(0.0_r8,Z2OG2(NU(NY,NX),NY,NX))
      RFLN3G=VFLW*AMAX1(0.0_r8,ZN3G2(NU(NY,NX),NY,NX))
      RFLH2G=VFLW*AMAX1(0.0_r8,H2GG2(NU(NY,NX),NY,NX))
    ELSE
      RFLCOG=-FLQM(3,NU(NY,NX),NY,NX)*CCO2E(NY,NX)
      RFLCHG=-FLQM(3,NU(NY,NX),NY,NX)*CCH4E(NY,NX)
      RFLOXG=-FLQM(3,NU(NY,NX),NY,NX)*COXYE(NY,NX)
      RFLNGG=-FLQM(3,NU(NY,NX),NY,NX)*CZ2GE(NY,NX)
      RFLN2G=-FLQM(3,NU(NY,NX),NY,NX)*CZ2OE(NY,NX)
      RFLN3G=-FLQM(3,NU(NY,NX),NY,NX)*CNH3E(NY,NX)
      RFLH2G=-FLQM(3,NU(NY,NX),NY,NX)*CH2GE(NY,NX)
    ENDIF
!
!     TOTAL SOIL GAS FLUX FROM DIFFUSIVE + CONVECTIVE FLUX
!
!     R*FLG=convective+diffusive gas flux
!     gas code:*CO*=CO2,*OX*=O2,*CH*=CH4,*NG*=N2,*N2*=N2O,*NH*=NH3,*HG*=H2
!     DFV*G=diffusive gas flux
!     RFL*G=convective gas flux
!
    RCOFLG(3,NU(NY,NX),NY,NX)=DFVCOG+RFLCOG
    RCHFLG(3,NU(NY,NX),NY,NX)=DFVCHG+RFLCHG
    ROXFLG(3,NU(NY,NX),NY,NX)=DFVOXG+RFLOXG
    RNGFLG(3,NU(NY,NX),NY,NX)=DFVNGG+RFLNGG
    RN2FLG(3,NU(NY,NX),NY,NX)=DFVN2G+RFLN2G
    RN3FLG(3,NU(NY,NX),NY,NX)=DFVN3G+RFLN3G
    RHGFLG(3,NU(NY,NX),NY,NX)=DFVHGG+RFLH2G
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*FLG=hourly convective+diffusive gas flux
!
    XCOFLG(3,NU(NY,NX),NY,NX)=XCOFLG(3,NU(NY,NX),NY,NX)+RCOFLG(3,NU(NY,NX),NY,NX)
    XCHFLG(3,NU(NY,NX),NY,NX)=XCHFLG(3,NU(NY,NX),NY,NX)+RCHFLG(3,NU(NY,NX),NY,NX)
    XOXFLG(3,NU(NY,NX),NY,NX)=XOXFLG(3,NU(NY,NX),NY,NX)+ROXFLG(3,NU(NY,NX),NY,NX)
    XNGFLG(3,NU(NY,NX),NY,NX)=XNGFLG(3,NU(NY,NX),NY,NX)+RNGFLG(3,NU(NY,NX),NY,NX)
    XN2FLG(3,NU(NY,NX),NY,NX)=XN2FLG(3,NU(NY,NX),NY,NX)+RN2FLG(3,NU(NY,NX),NY,NX)
    XN3FLG(3,NU(NY,NX),NY,NX)=XN3FLG(3,NU(NY,NX),NY,NX)+RN3FLG(3,NU(NY,NX),NY,NX)
    XHGFLG(3,NU(NY,NX),NY,NX)=XHGFLG(3,NU(NY,NX),NY,NX)+RHGFLG(3,NU(NY,NX),NY,NX)

!     VOLWM=micropore water-filled porosity from watsub.f
!     VOLW*=equivalent aqueous volume for gas
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     S*L=solubility of gas in water from hour1.f
!     VOLPM=air-filled porosity
!     R*DFG=water-air gas flux
!     DFGS=rate constant for air-water gas exchange from watsub.f
!     *G2,*S2=gaseous,aqueous gas content
!     R*DXS=gas exchange between atmosphere and soil surface water
!
    IF(VOLWM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      VOLWCO(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SCO2L(NU(NY,NX),NY,NX)
      VOLWCH(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SCH4L(NU(NY,NX),NY,NX)
      VOLWOX(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SOXYL(NU(NY,NX),NY,NX)
      VOLWNG(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SN2GL(NU(NY,NX),NY,NX)
      VOLWN2(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SN2OL(NU(NY,NX),NY,NX)
      VOLWN3(NU(NY,NX),NY,NX)=VOLWMA(NU(NY,NX),NY,NX)*SNH3L(NU(NY,NX),NY,NX)
      VOLWNB(NU(NY,NX),NY,NX)=VOLWMB(NU(NY,NX),NY,NX)*SNH3L(NU(NY,NX),NY,NX)
      VOLWHG(NU(NY,NX),NY,NX)=VOLWM(M,NU(NY,NX),NY,NX)*SH2GL(NU(NY,NX),NY,NX)
      VOLCOT(NY,NX)=VOLWCO(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      VOLCHT(NY,NX)=VOLWCH(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      VOLOXT(NY,NX)=VOLWOX(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      VOLNGT(NY,NX)=VOLWNG(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      VOLN2T(NY,NX)=VOLWN2(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      VOLN3T(NY,NX)=VOLWN3(NU(NY,NX),NY,NX)+VOLPMA(NU(NY,NX),NY,NX)
      VOLNBT(NY,NX)=VOLWNB(NU(NY,NX),NY,NX)+VOLPMB(NU(NY,NX),NY,NX)
      VOLHGT(NY,NX)=VOLWHG(NU(NY,NX),NY,NX)+VOLPM(M,NU(NY,NX),NY,NX)
      RCODFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),CO2G2(NU(NY,NX),NY,NX)) &
        *VOLWCO(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,CO2S2(NU(NY,NX),NY,NX)+RCODXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLCOT(NY,NX)
      RCHDFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),CH4G2(NU(NY,NX),NY,NX)) &
        *VOLWCH(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,CH4S2(NU(NY,NX),NY,NX)+RCHDXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLCHT(NY,NX)
      ROXDFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),OXYG2(NU(NY,NX),NY,NX)) &
        *VOLWOX(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,OXYS2(NU(NY,NX),NY,NX)+ROXDXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLOXT(NY,NX)
      RNGDFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),Z2GG2(NU(NY,NX),NY,NX)) &
        *VOLWNG(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,Z2GS2(NU(NY,NX),NY,NX)+RNGDXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLNGT(NY,NX)
      RN2DFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),Z2OG2(NU(NY,NX),NY,NX)) &
        *VOLWN2(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,Z2OS2(NU(NY,NX),NY,NX)+RN2DXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLN2T(NY,NX)
      IF(VOLN3T(NY,NX).GT.ZEROS2(NY,NX).AND.VOLWXA(NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
        RN3DFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
          *(AMAX1(ZEROS(NY,NX),ZN3G2(NU(NY,NX),NY,NX)) &
          *VOLWN3(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
          ,ZNH3S2(NU(NY,NX),NY,NX)+RN3DXS) &
          *VOLPMA(NU(NY,NX),NY,NX))/VOLN3T(NY,NX)
        CNH3S0=AMAX1(0.0_r8,(ZNH3S2(NU(NY,NX),NY,NX) &
          +RN3DFG(NU(NY,NX),NY,NX))/VOLWXA(NU(NY,NX),NY,NX))
        CNH4S0=AMAX1(0.0_r8,ZNH4S2(NU(NY,NX),NY,NX))/VOLWXA(NU(NY,NX),NY,NX)
      ELSE
        RN3DFG(NU(NY,NX),NY,NX)=0.0_r8
      ENDIF
      IF(VOLNBT(NY,NX).GT.ZEROS2(NY,NX).AND.VOLWXB(NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
        RNBDFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
          *(AMAX1(ZEROS(NY,NX),ZN3G2(NU(NY,NX),NY,NX)) &
          *VOLWNB(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
          ,ZNH3B2(NU(NY,NX),NY,NX)+RNBDXS) &
          *VOLPMB(NU(NY,NX),NY,NX))/VOLNBT(NY,NX)
        CNH3B0=AMAX1(0.0_r8,(ZNH3B2(NU(NY,NX),NY,NX) &
          +RNBDFG(NU(NY,NX),NY,NX))/VOLWXB(NU(NY,NX),NY,NX))
        CNH4B0=AMAX1(0.0_r8,ZNH4B2(NU(NY,NX),NY,NX))/VOLWXB(NU(NY,NX),NY,NX)
      ELSE
        RNBDFG(NU(NY,NX),NY,NX)=0.0_r8
      ENDIF
      RHGDFG(NU(NY,NX),NY,NX)=DFGS(M,NU(NY,NX),NY,NX) &
        *(AMAX1(ZEROS(NY,NX),H2GG2(NU(NY,NX),NY,NX)) &
        *VOLWHG(NU(NY,NX),NY,NX)-AMAX1(ZEROS(NY,NX) &
        ,H2GS2(NU(NY,NX),NY,NX)+RHGDXS) &
        *VOLPM(M,NU(NY,NX),NY,NX))/VOLHGT(NY,NX)

!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
!     X*DFG=hourly water-air gas flux
!
      XCODFG(NU(NY,NX),NY,NX)=XCODFG(NU(NY,NX),NY,NX)+RCODFG(NU(NY,NX),NY,NX)
      XCHDFG(NU(NY,NX),NY,NX)=XCHDFG(NU(NY,NX),NY,NX)+RCHDFG(NU(NY,NX),NY,NX)
      XOXDFG(NU(NY,NX),NY,NX)=XOXDFG(NU(NY,NX),NY,NX)+ROXDFG(NU(NY,NX),NY,NX)
      XNGDFG(NU(NY,NX),NY,NX)=XNGDFG(NU(NY,NX),NY,NX)+RNGDFG(NU(NY,NX),NY,NX)
      XN2DFG(NU(NY,NX),NY,NX)=XN2DFG(NU(NY,NX),NY,NX)+RN2DFG(NU(NY,NX),NY,NX)
      XN3DFG(NU(NY,NX),NY,NX)=XN3DFG(NU(NY,NX),NY,NX)+RN3DFG(NU(NY,NX),NY,NX)
      XNBDFG(NU(NY,NX),NY,NX)=XNBDFG(NU(NY,NX),NY,NX)+RNBDFG(NU(NY,NX),NY,NX)
      XHGDFG(NU(NY,NX),NY,NX)=XHGDFG(NU(NY,NX),NY,NX)+RHGDFG(NU(NY,NX),NY,NX)
    ELSE
      RCODFG(NU(NY,NX),NY,NX)=0.0_r8
      RCHDFG(NU(NY,NX),NY,NX)=0.0_r8
      ROXDFG(NU(NY,NX),NY,NX)=0.0_r8
      RNGDFG(NU(NY,NX),NY,NX)=0.0_r8
      RN2DFG(NU(NY,NX),NY,NX)=0.0_r8
      RN3DFG(NU(NY,NX),NY,NX)=0.0_r8
      RNBDFG(NU(NY,NX),NY,NX)=0.0_r8
      RHGDFG(NU(NY,NX),NY,NX)=0.0_r8
    ENDIF
  ELSE
    RCOFLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RCHFLG(3,NU(NY,NX),NY,NX)=0.0_r8
    ROXFLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RNGFLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RN2FLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RN3FLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RHGFLG(3,NU(NY,NX),NY,NX)=0.0_r8
    RCODFG(NU(NY,NX),NY,NX)=0.0_r8
    RCHDFG(NU(NY,NX),NY,NX)=0.0_r8
    ROXDFG(NU(NY,NX),NY,NX)=0.0_r8
    RN2DFG(NU(NY,NX),NY,NX)=0.0_r8
    RNGDFG(NU(NY,NX),NY,NX)=0.0_r8
    RN3DFG(NU(NY,NX),NY,NX)=0.0_r8
    RNBDFG(NU(NY,NX),NY,NX)=0.0_r8
    RHGDFG(NU(NY,NX),NY,NX)=0.0_r8
  ENDIF
  end subroutine GasDiffusionConvection



!------------------------------------------------------------------------------------------

  subroutine LitterAtmosExchange(M,NY,NX)
  implicit none
  integer, intent(in) :: NY,NX,M
  integer :: K

  real(r8) :: CCH4GQ,CCO2GQ,CH2GGQ,COXYGQ,CZ2GGQ,CZ2OGQ,CZN3GQ
  real(r8) :: DFGSCH,DFGSCO,DFGSHL,DFGSN2,DFGSN3,DFGSNG,DFGSOX
  real(r8) :: DLYR0,TORT0

  IF(VOLT(0,NY,NX).GT.ZEROS2(NY,NX).AND.VOLWM(M,0,NY,NX).GT.ZEROS2(NY,NX))THEN
    DLYR0=AMAX1(ZERO2,DLYR(3,0,NY,NX)) !vertical layer thickness
    TORT0=TORT(M,0,NY,NX)*AREA(3,NU(NY,NX),NY,NX)/(0.5_r8*DLYR0)*CVRD(NY,NX)
    DFGSCO=CLSGL2(0,NY,NX)*TORT0
    DFGSCH=CQSGL2(0,NY,NX)*TORT0
    DFGSOX=OLSGL2(0,NY,NX)*TORT0
    DFGSNG=ZLSGL2(0,NY,NX)*TORT0
    DFGSN2=ZNSGL2(0,NY,NX)*TORT0
    DFGSN3=ZVSGL2(0,NY,NX)*TORT0
    DFGSHL=HLSGL2(0,NY,NX)*TORT0
    DO  K=0,jcplx1
      COQC1(K)=AMAX1(0.0_r8,OQC2(K,0,NY,NX)/VOLWM(M,0,NY,NX))
      COQN1(K)=AMAX1(0.0_r8,OQN2(K,0,NY,NX)/VOLWM(M,0,NY,NX))
      COQP1(K)=AMAX1(0.0_r8,OQP2(K,0,NY,NX)/VOLWM(M,0,NY,NX))
      COQA1(K)=AMAX1(0.0_r8,OQA2(K,0,NY,NX)/VOLWM(M,0,NY,NX))
    ENDDO
    CCO2S1=AMAX1(0.0_r8,CO2S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CCH4S1=AMAX1(0.0_r8,CH4S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    COXYS1=AMAX1(0.0_r8,OXYS2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CZ2GS1=AMAX1(0.0_r8,Z2GS2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CZ2OS1=AMAX1(0.0_r8,Z2OS2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CH2GS1=AMAX1(0.0_r8,H2GS2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CNH4S1=AMAX1(0.0_r8,ZNH4S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CNH3S1=AMAX1(0.0_r8,ZNH3S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CNO3S1=AMAX1(0.0_r8,ZNO3S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CNO2S1=AMAX1(0.0_r8,ZNO2S2(0,NY,NX)/VOLWM(M,0,NY,NX))
    CP14S1=AMAX1(0.0_r8,H1PO42(0,NY,NX)/VOLWM(M,0,NY,NX))
    CPO4S1=AMAX1(0.0_r8,H2PO42(0,NY,NX)/VOLWM(M,0,NY,NX))
!
!     EQUILIBRIUM CONCENTRATIONS AT RESIDUE SURFACE AT WHICH
!     AQUEOUS DIFFUSION THROUGH RESIDUE SURFACE LAYER = GASEOUS
!     DIFFUSION THROUGH ATMOSPHERE BOUNDARY LAYER CALCULATED
!     FROM AQUEOUS DIFFUSIVITY AND BOUNDARY LAYER CONDUCTANCE
!
!     PARR=boundary layer conductance above litter surface from watsub.f
!     C*E=atmospheric gas concentration from hour1.f
!     C*Q=equilibrium gas concentration at litter surface
!     S*L=solubility of gas in water from hour1.f
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     DFGS*=effective solute diffusivity
!
    CCO2GQ=(PARR(NY,NX)*CCO2E(NY,NX)*SCO2L(0,NY,NX)+DFGSCO*CCO2S1)/(DFGSCO+PARR(NY,NX))
    CCH4GQ=(PARR(NY,NX)*CCH4E(NY,NX)*SCH4L(0,NY,NX)+DFGSCH*CCH4S1)/(DFGSCH+PARR(NY,NX))
    COXYGQ=(PARR(NY,NX)*COXYE(NY,NX)*SOXYL(0,NY,NX)+DFGSOX*COXYS1)/(DFGSOX+PARR(NY,NX))
    CZ2GGQ=(PARR(NY,NX)*CZ2GE(NY,NX)*SN2GL(0,NY,NX)+DFGSNG*CZ2GS1)/(DFGSNG+PARR(NY,NX))
    CZ2OGQ=(PARR(NY,NX)*CZ2OE(NY,NX)*SN2OL(0,NY,NX)+DFGSN2*CZ2OS1)/(DFGSN2+PARR(NY,NX))
    CZN3GQ=(PARR(NY,NX)*CNH3E(NY,NX)*SNH3L(0,NY,NX)+DFGSN3*CNH3S1)/(DFGSN3+PARR(NY,NX))
    CH2GGQ=(PARR(NY,NX)*CH2GE(NY,NX)*SH2GL(0,NY,NX)+DFGSHL*CH2GS1)/(DFGSHL+PARR(NY,NX))
!
!     SURFACE VOLATILIZATION-DISSOLUTION FROM DIFFERENCES
!     BETWEEN ATMOSPHERIC AND RESIDUE SURFACE EQUILIBRIUM
!     CONCENTRATIONS
!
!     R*DFR,X*DFR=current,hourly gas exchange between atmosphere and surface litter water
!     gas code: *CO*=CO2,*CH*=CH4,*OX*=O2,*NG*=N2,*N2*=N2O,*N3*=NH3,*HG*=H2
!     C*E=atmospheric gas concentration from hour1.f
!     C*Q=equilibrium gas concentration at litter surface
!     VOLWM=litter water volume
!     DFGS*=effective solute diffusivity
!     XNPT=1/number of cycles NPH-1 for gas flux calculations
!     R*DXR=R*DFR for gas flux calculations
!
    RCODFR(NY,NX)=(CCO2GQ-CCO2S1)*AMIN1(VOLWM(M,0,NY,NX),DFGSCO)
    RCHDFR(NY,NX)=(CCH4GQ-CCH4S1)*AMIN1(VOLWM(M,0,NY,NX),DFGSCH)
    ROXDFR(NY,NX)=(COXYGQ-COXYS1)*AMIN1(VOLWM(M,0,NY,NX),DFGSOX)
    RNGDFR(NY,NX)=(CZ2GGQ-CZ2GS1)*AMIN1(VOLWM(M,0,NY,NX),DFGSNG)
    RN2DFR(NY,NX)=(CZ2OGQ-CZ2OS1)*AMIN1(VOLWM(M,0,NY,NX),DFGSN2)
    RN3DFR(NY,NX)=(CZN3GQ-CNH3S1)*AMIN1(VOLWM(M,0,NY,NX),DFGSN3)
    RHGDFR(NY,NX)=(CH2GGQ-CH2GS1)*AMIN1(VOLWM(M,0,NY,NX),DFGSHL)
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
    XCODFR(NY,NX)=XCODFR(NY,NX)+RCODFR(NY,NX)
    XCHDFR(NY,NX)=XCHDFR(NY,NX)+RCHDFR(NY,NX)
    XOXDFR(NY,NX)=XOXDFR(NY,NX)+ROXDFR(NY,NX)
    XNGDFR(NY,NX)=XNGDFR(NY,NX)+RNGDFR(NY,NX)
    XN2DFR(NY,NX)=XN2DFR(NY,NX)+RN2DFR(NY,NX)
    XN3DFR(NY,NX)=XN3DFR(NY,NX)+RN3DFR(NY,NX)
    XHGDFR(NY,NX)=XHGDFR(NY,NX)+RHGDFR(NY,NX)

  ELSE
    RCODFR(NY,NX)=0.0_r8
    RCHDFR(NY,NX)=0.0_r8
    ROXDFR(NY,NX)=0.0_r8
    RNGDFR(NY,NX)=0.0_r8
    RN2DFR(NY,NX)=0.0_r8
    RN3DFR(NY,NX)=0.0_r8
    RHGDFR(NY,NX)=0.0_r8
  ENDIF
  RCODXR=RCODFR(NY,NX)*XNPT
  RCHDXR=RCHDFR(NY,NX)*XNPT
  ROXDXR=ROXDFR(NY,NX)*XNPT
  RNGDXR=RNGDFR(NY,NX)*XNPT
  RN2DXR=RN2DFR(NY,NX)*XNPT
  RN3DXR=RN3DFR(NY,NX)*XNPT
  RHGDXR=RHGDFR(NY,NX)*XNPT
  end subroutine LitterAtmosExchange
!------------------------------------------------------------------------------------------
  subroutine SoilAtmosExchange(M,NY,NX)

  implicit none
  integer, intent(in) :: M,NY,NX

  real(r8) :: CCH4GQ,CCO2GQ,CH2GGQ,COXYGQ,CZ2GGQ,CZ2OGQ,CZN3BQ,CZN3GQ
  real(r8) :: DFGSCH,DFGSCO,DFGSHL,DFGSN2,DFGSN3,DFGSNG,DFGSOX
  real(r8) :: DLYR1,TORT1,VOLWOA,VOLWOB,VOLWPA,VOLWPB
  integer  :: K
!
!     SURFACE EXCHANGE OF AQUEOUS CO2, CH4, O2, N2, NH3
!     THROUGH VOLATILIZATION-DISSOLUTION FROM AQUEOUS
!     DIFFUSIVITIES IN SURFACE SOIL LAYER
!
!     VOLWM=micropore water-filled porosity from watsub.f
!     TORT=tortuosity from hour1.f
!     *SGL*=solute diffusivity
!     solute code:CO=CO2,CH=CH4,OX=O2,NG=N2,N2=N2O,HG=H2
!             :OC=DOC,ON=DON,OP=DOP,OA=acetate
!             :NH4=NH4,NH3=NH3,NO3=NO3,NO2=NO2,P14=HPO4,PO4=H2PO4 in non-band
!             :N4B=NH4,N3B=NH3,NOB=NO3,N2B=NO2,P1B=HPO4,POB=H2PO4 in band
!     DFGS*=effective solute diffusivity
!     C*2=solute concentration in soil surface
!     CO2S,CH4S,OXYS,Z2GS,Z2OS,H2GS=aqueous CO2,CH4,O2,N2,N2O,H2 in soil
!     OQC,OQN,OQP,OQA=DOC,DON,DOP,acetate in litter
!     ZNH4S,ZNH3S,ZNO3S,ZNO2S,H1PO4,H2PO4=aqueous NH4,NH3,NO3,NO2,HPO4,H2PO4 in non-band micropores
!     ZNH4B,ZNH3B,ZNO3B,ZNO2B,H1POB,H2POB=aqueous NH4,NH3,NO3,NO2,HPO4,H2PO4 in band micropores
!
  IF(VOLWM(M,NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
    VOLWOA=VOLWM(M,NU(NY,NX),NY,NX)*VLNO3(NU(NY,NX),NY,NX)
    VOLWOB=VOLWM(M,NU(NY,NX),NY,NX)*VLNOB(NU(NY,NX),NY,NX)
    VOLWPA=VOLWM(M,NU(NY,NX),NY,NX)*VLPO4(NU(NY,NX),NY,NX)
    VOLWPB=VOLWM(M,NU(NY,NX),NY,NX)*VLPOB(NU(NY,NX),NY,NX)
    DLYR1=AMAX1(ZERO2,DLYR(3,NU(NY,NX),NY,NX))
    TORT1=TORT(M,NU(NY,NX),NY,NX)*AREA(3,NU(NY,NX),NY,NX)/(0.5*DLYR1)
    DFGSCO=CLSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSCH=CQSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSOX=OLSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSNG=ZLSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSN2=ZNSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSN3=ZVSGL2(NU(NY,NX),NY,NX)*TORT1
    DFGSHL=HLSGL2(NU(NY,NX),NY,NX)*TORT1
    DO  K=0,jcplx1
      COQC2(K)=AMAX1(0.0_r8,OQC2(K,NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
      COQN2(K)=AMAX1(0.0_r8,OQN2(K,NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
      COQP2(K)=AMAX1(0.0_r8,OQP2(K,NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
      COQA2(K)=AMAX1(0.0_r8,OQA2(K,NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    ENDDO
    CCO2S2=AMAX1(0.0_r8,CO2S2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    CCH4S2=AMAX1(0.0_r8,CH4S2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    COXYS2=AMAX1(0.0_r8,OXYS2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    CZ2GS2=AMAX1(0.0_r8,Z2GS2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    CZ2OS2=AMAX1(0.0_r8,Z2OS2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    CH2GS2=AMAX1(0.0_r8,H2GS2(NU(NY,NX),NY,NX)/VOLWM(M,NU(NY,NX),NY,NX))
    IF(VOLWMA(NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      CNH3S2=AMAX1(0.0_r8,ZNH3S2(NU(NY,NX),NY,NX)/VOLWMA(NU(NY,NX),NY,NX))
      CNH4S2=AMAX1(0.0_r8,ZNH4S2(NU(NY,NX),NY,NX)/VOLWMA(NU(NY,NX),NY,NX))
    ELSE
      CNH3S2=0.0_r8
      CNH4S2=0.0_r8
    ENDIF
    IF(VOLWOA.GT.ZEROS2(NY,NX))THEN
      CNO3S2=AMAX1(0.0_r8,ZNO3S2(NU(NY,NX),NY,NX)/VOLWOA)
      CNO2S2=AMAX1(0.0_r8,ZNO2S2(NU(NY,NX),NY,NX)/VOLWOA)
    ELSE
      CNO3S2=0.0_r8
      CNO2S2=0.0_r8
    ENDIF
    IF(VOLWPA.GT.ZEROS2(NY,NX))THEN
      CP14S2=AMAX1(0.0_r8,H1PO42(NU(NY,NX),NY,NX)/VOLWPA)
      CPO4S2=AMAX1(0.0_r8,H2PO42(NU(NY,NX),NY,NX)/VOLWPA)
    ELSE
      CP14S2=0.0_r8
      CPO4S2=0.0_r8
    ENDIF
    IF(VOLWMB(NU(NY,NX),NY,NX).GT.ZEROS2(NY,NX))THEN
      CNH3B2=AMAX1(0.0_r8,ZNH3B2(NU(NY,NX),NY,NX)/VOLWMB(NU(NY,NX),NY,NX))
      CNH4B2=AMAX1(0.0_r8,ZNH4B2(NU(NY,NX),NY,NX)/VOLWMB(NU(NY,NX),NY,NX))
    ELSE
      CNH3B2=CNH3S2
      CNH4B2=CNH4S2
    ENDIF
    IF(VOLWOB.GT.ZEROS2(NY,NX))THEN
      CNO3B2=AMAX1(0.0_r8,ZNO3B2(NU(NY,NX),NY,NX)/VOLWOB)
      CNO2B2=AMAX1(0.0_r8,ZNO2B2(NU(NY,NX),NY,NX)/VOLWOB)
    ELSE
      CNO3B2=CNO3S2
      CNO2B2=CNO2S2
    ENDIF
    IF(VOLWPB.GT.ZEROS2(NY,NX))THEN
      CP14B2=AMAX1(0.0_r8,H1POB2(NU(NY,NX),NY,NX)/VOLWPB)
      CPO4B2=AMAX1(0.0_r8,H2POB2(NU(NY,NX),NY,NX)/VOLWPB)
    ELSE
      CP14B2=CP14S2
      CPO4B2=CPO4S2
    ENDIF
!
!     EQUILIBRIUM CONCENTRATIONS AT SOIL SURFACE AT WHICH
!     AQUEOUS DIFFUSION THROUGH SOIL SURFACE LAYER = GASEOUS
!     DIFFUSION THROUGH ATMOSPHERE BOUNDARY LAYER CALCULATED
!     FROM AQUEOUS DIFFUSIVITY AND BOUNDARY LAYER CONDUCTANCE
!
!     PARG=boundary layer conductance above soil surface from watsub.f
!     C*E=atmospheric gas concentration from hour1.f
!     C*Q=equilibrium gas concentration at soil surface
!     S*L=solubility of gas in water from hour1.f
!     gas code:*CO2*=CO2,*OXY*=O2,*CH4*=CH4,*Z2G*=N2,*Z2O*=N2O
!             :*ZN3*=NH3,*H2G*=H2
!     DFGS*=effective solute diffusivity
!
    CCO2GQ=(PARG(M,NY,NX)*CCO2E(NY,NX)*SCO2L(NU(NY,NX),NY,NX) &
      +DFGSCO*CCO2S2)/(DFGSCO+PARG(M,NY,NX))
    CCH4GQ=(PARG(M,NY,NX)*CCH4E(NY,NX)*SCH4L(NU(NY,NX),NY,NX) &
      +DFGSCH*CCH4S2)/(DFGSCH+PARG(M,NY,NX))
    COXYGQ=(PARG(M,NY,NX)*COXYE(NY,NX)*SOXYL(NU(NY,NX),NY,NX) &
      +DFGSOX*COXYS2)/(DFGSOX+PARG(M,NY,NX))
    CZ2GGQ=(PARG(M,NY,NX)*CZ2GE(NY,NX)*SN2GL(NU(NY,NX),NY,NX) &
      +DFGSNG*CZ2GS2)/(DFGSNG+PARG(M,NY,NX))
    CZ2OGQ=(PARG(M,NY,NX)*CZ2OE(NY,NX)*SN2OL(NU(NY,NX),NY,NX) &
      +DFGSN2*CZ2OS2)/(DFGSN2+PARG(M,NY,NX))
    CZN3GQ=(PARG(M,NY,NX)*CNH3E(NY,NX)*SNH3L(NU(NY,NX),NY,NX) &
      +DFGSN3*CNH3S2)/(DFGSN3+PARG(M,NY,NX))
    CZN3BQ=(PARG(M,NY,NX)*CNH3E(NY,NX)*SNH3L(NU(NY,NX),NY,NX) &
      +DFGSN3*CNH3B2)/(DFGSN3+PARG(M,NY,NX))
    CH2GGQ=(PARG(M,NY,NX)*CH2GE(NY,NX)*SH2GL(NU(NY,NX),NY,NX) &
      +DFGSHL*CH2GS2)/(DFGSHL+PARG(M,NY,NX))
!
!     SURFACE VOLATILIZATION-DISSOLUTION FROM DIFFERENCES
!     BETWEEN ATMOSPHERIC AND SOIL SURFACE EQUILIBRIUM
!     CONCENTRATIONS
!
!     R*DFS,X*DFS=current,cumulative gas exchange between atmosphere and soil surface water
!     gas code:*CO*=CO2,*CH*=CH4,*OX*=O2,*NG*=N2,*N2*=N2O,*N3*=NH3,*HG*=H2
!     C*E=atmospheric gas concentration from hour1.f
!     C*Q=equilibrium gas concentration at soil surface
!     VOLWM=litter water volume
!     DFGS*=effective solute diffusivity
!     XNPT=1/number of cycles NPH-1 for gas flux calculations
!     R*DXS=R*DFS for gas flux calculations
!
    RCODFS(NY,NX)=(CCO2GQ-CCO2S2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSCO)
    RCHDFS(NY,NX)=(CCH4GQ-CCH4S2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSCH)
    ROXDFS(NY,NX)=(COXYGQ-COXYS2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSOX)
    RNGDFS(NY,NX)=(CZ2GGQ-CZ2GS2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSNG)
    RN2DFS(NY,NX)=(CZ2OGQ-CZ2OS2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSN2)
    RN3DFS(NY,NX)=(CZN3GQ-CNH3S2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX)*VLNH4(NU(NY,NX),NY,NX),DFGSN3)
    RNBDFS(NY,NX)=(CZN3BQ-CNH3B2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX)*VLNHB(NU(NY,NX),NY,NX),DFGSN3)
    RHGDFS(NY,NX)=(CH2GGQ-CH2GS2)*AMIN1(VOLWM(M,NU(NY,NX),NY,NX),DFGSHL)
!
!     ACCUMULATE HOURLY FLUXES FOR USE IN REDIST.F
!
    XCODFS(NY,NX)=XCODFS(NY,NX)+RCODFS(NY,NX)
    XCHDFS(NY,NX)=XCHDFS(NY,NX)+RCHDFS(NY,NX)
    XOXDFS(NY,NX)=XOXDFS(NY,NX)+ROXDFS(NY,NX)
    XNGDFS(NY,NX)=XNGDFS(NY,NX)+RNGDFS(NY,NX)
    XN2DFS(NY,NX)=XN2DFS(NY,NX)+RN2DFS(NY,NX)
    XN3DFS(NY,NX)=XN3DFS(NY,NX)+RN3DFS(NY,NX)
    XNBDFS(NY,NX)=XNBDFS(NY,NX)+RNBDFS(NY,NX)
    XHGDFS(NY,NX)=XHGDFS(NY,NX)+RHGDFS(NY,NX)

  ELSE
    RCODFS(NY,NX)=0.0_r8
    RCHDFS(NY,NX)=0.0_r8
    ROXDFS(NY,NX)=0.0_r8
    RNGDFS(NY,NX)=0.0_r8
    RN2DFS(NY,NX)=0.0_r8
    RN3DFS(NY,NX)=0.0_r8
    RNBDFS(NY,NX)=0.0_r8
    RHGDFS(NY,NX)=0.0_r8
  ENDIF
  RCODXS=RCODFS(NY,NX)*XNPT
  RCHDXS=RCHDFS(NY,NX)*XNPT
  ROXDXS=ROXDFS(NY,NX)*XNPT
  RNGDXS=RNGDFS(NY,NX)*XNPT
  RN2DXS=RN2DFS(NY,NX)*XNPT
  RN3DXS=RN3DFS(NY,NX)*XNPT
  RNBDXS=RNBDFS(NY,NX)*XNPT
  RHGDXS=RHGDFS(NY,NX)*XNPT
  end subroutine SoilAtmosExchange
!------------------------------------------------------------------------------------------

  subroutine SoluteFluxSnowpack(M,NY,NX)

  implicit none

  integer, intent(in) :: M, NY, NX
  integer :: ICHKL,L,L2
  real(r8) :: VFLWS,VFLWW,VFLWR
  real(r8) :: VFLWNOB,VFLWNO3,VFLWNHB
  real(r8) :: VFLWNH4,VFLWPO4,VFLWPOB
!
!     VHCPWM,VHCPWX=current,minimum volumetric heat capacity of snowpack
!     VOLWSL=snowpack water content
!     FLQWM=snowpack water flux
!     R*BLS=solute flux in snowpack
!     X*BLS=hourly solute flux in snowpack
!     CO2W,CH4W,OXYW,ZNGW,ZN2W,ZN4W,ZN3W,ZNOW,Z1PW,ZHPW=CO2,CH4,O2,N2,N2O,H2 content in snowpack
!
  ICHKL=0
  DO  L=1,JS
    IF(VHCPWM(M,L,NY,NX).GT.VHCPWX(NY,NX))THEN
      L2=MIN(JS,L+1)
      IF(L.LT.JS.AND.VHCPWM(M,L2,NY,NX).GT.VHCPWX(NY,NX))THEN
        IF(VOLWSL(L,NY,NX).GT.ZEROS2(NY,NX))THEN
          VFLWW=AMAX1(0.0_r8,AMIN1(1.0,FLQWM(M,L2,NY,NX)/VOLWSL(L,NY,NX)))
        ELSE
          VFLWW=1.0
        ENDIF
        RCOBLS(L2,NY,NX)=CO2W2(L,NY,NX)*VFLWW
        RCHBLS(L2,NY,NX)=CH4W2(L,NY,NX)*VFLWW
        ROXBLS(L2,NY,NX)=OXYW2(L,NY,NX)*VFLWW
        RNGBLS(L2,NY,NX)=ZNGW2(L,NY,NX)*VFLWW
        RN2BLS(L2,NY,NX)=ZN2W2(L,NY,NX)*VFLWW
        RN4BLW(L2,NY,NX)=ZN4W2(L,NY,NX)*VFLWW
        RN3BLW(L2,NY,NX)=ZN3W2(L,NY,NX)*VFLWW
        RNOBLW(L2,NY,NX)=ZNOW2(L,NY,NX)*VFLWW
        RH1PBS(L2,NY,NX)=Z1PW2(L,NY,NX)*VFLWW
        RH2PBS(L2,NY,NX)=ZHPW2(L,NY,NX)*VFLWW
        XCOBLS(L2,NY,NX)=XCOBLS(L2,NY,NX)+RCOBLS(L2,NY,NX)
        XCHBLS(L2,NY,NX)=XCHBLS(L2,NY,NX)+RCHBLS(L2,NY,NX)
        XOXBLS(L2,NY,NX)=XOXBLS(L2,NY,NX)+ROXBLS(L2,NY,NX)
        XNGBLS(L2,NY,NX)=XNGBLS(L2,NY,NX)+RNGBLS(L2,NY,NX)
        XN2BLS(L2,NY,NX)=XN2BLS(L2,NY,NX)+RN2BLS(L2,NY,NX)
        XN4BLW(L2,NY,NX)=XN4BLW(L2,NY,NX)+RN4BLW(L2,NY,NX)
        XN3BLW(L2,NY,NX)=XN3BLW(L2,NY,NX)+RN3BLW(L2,NY,NX)
        XNOBLW(L2,NY,NX)=XNOBLW(L2,NY,NX)+RNOBLW(L2,NY,NX)
        XH1PBS(L2,NY,NX)=XH1PBS(L2,NY,NX)+RH1PBS(L2,NY,NX)
        XH2PBS(L2,NY,NX)=XH2PBS(L2,NY,NX)+RH2PBS(L2,NY,NX)
      ELSE
        IF(L.LT.JS)THEN
          RCOBLS(L2,NY,NX)=0.0_r8
          RCHBLS(L2,NY,NX)=0.0_r8
          ROXBLS(L2,NY,NX)=0.0_r8
          RNGBLS(L2,NY,NX)=0.0_r8
          RN2BLS(L2,NY,NX)=0.0_r8
          RN4BLW(L2,NY,NX)=0.0_r8
          RN3BLW(L2,NY,NX)=0.0_r8
          RNOBLW(L2,NY,NX)=0.0_r8
          RH1PBS(L2,NY,NX)=0.0_r8
          RH2PBS(L2,NY,NX)=0.0_r8
        ENDIF
!
!     SNOWPACK SOLUTE DISCHARGE TO SURFACE LITTER, SOIL SURFACE
!
!     VOLWSL=snowpack water content
!     FLQRM,FLQSM,FLQHM=total water flux to litter,soil micropore,macropore
!     CVRD,BARE=litter cover fraction,1-CVRD
!     VLNH4,VLNO3,VLPO4=non-band NH4,NO3,PO4 volume fraction
!     VLNHB,VLNOB,VLPOB=band NH4,NO3,PO4 volume fraction
!     R*S0=solute flux to surface litter
!     R*S1,R*B1=solute flux to soil surface non-band,band
!     CO2W,CH4W,OXYW,ZNGW,ZN2W,ZN4W,ZN3W,ZNOW,Z1PW,ZHPW=CO2,CH4,O2,N2,N2O,H2 content in snowpack
!
        IF(ICHKL.EQ.0)THEN
          IF(VOLWSL(L,NY,NX).GT.ZEROS2(NY,NX))THEN
            VFLWR=AMAX1(0.0_r8,AMIN1(1.0,FLQRM(M,NY,NX)/VOLWSL(L,NY,NX)))
            VFLWS=AMAX1(0.0_r8,AMIN1(1.0,(FLQSM(M,NY,NX)+FLQHM(M,NY,NX))/VOLWSL(L,NY,NX)))
          ELSE
            VFLWR=CVRD(NY,NX)
            VFLWS=BARE(NY,NX)
          ENDIF
          VFLWNH4=VFLWS*VLNH4(NU(NY,NX),NY,NX)
          VFLWNHB=VFLWS*VLNHB(NU(NY,NX),NY,NX)
          VFLWNO3=VFLWS*VLNO3(NU(NY,NX),NY,NX)
          VFLWNOB=VFLWS*VLNOB(NU(NY,NX),NY,NX)
          VFLWPO4=VFLWS*VLPO4(NU(NY,NX),NY,NX)
          VFLWPOB=VFLWS*VLPOB(NU(NY,NX),NY,NX)
          RCOFLS0=CO2W2(L,NY,NX)*VFLWR
          RCHFLS0=CH4W2(L,NY,NX)*VFLWR
          ROXFLS0=OXYW2(L,NY,NX)*VFLWR
          RNGFLS0=ZNGW2(L,NY,NX)*VFLWR
          RN2FLS0=ZN2W2(L,NY,NX)*VFLWR
          RN4FLW0=ZN4W2(L,NY,NX)*VFLWR
          RN3FLW0=ZN3W2(L,NY,NX)*VFLWR
          RNOFLW0=ZNOW2(L,NY,NX)*VFLWR
          RH1PFS0=Z1PW2(L,NY,NX)*VFLWR
          RH2PFS0=ZHPW2(L,NY,NX)*VFLWR
          RCOFLS1=CO2W2(L,NY,NX)*VFLWS
          RCHFLS1=CH4W2(L,NY,NX)*VFLWS
          ROXFLS1=OXYW2(L,NY,NX)*VFLWS
          RNGFLS1=ZNGW2(L,NY,NX)*VFLWS
          RN2FLS1=ZN2W2(L,NY,NX)*VFLWS
          RN4FLW1=ZN4W2(L,NY,NX)*VFLWNH4
          RN3FLW1=ZN3W2(L,NY,NX)*VFLWNH4
          RNOFLW1=ZNOW2(L,NY,NX)*VFLWNO3
          RH1PFS1=Z1PW2(L,NY,NX)*VFLWPO4
          RH2PFS1=ZHPW2(L,NY,NX)*VFLWPO4
          RN4FLB1=ZN4W2(L,NY,NX)*VFLWNHB
          RN3FLB1=ZN3W2(L,NY,NX)*VFLWNHB
          RNOFLB1=ZNOW2(L,NY,NX)*VFLWNOB
          RH1BFB1=Z1PW2(L,NY,NX)*VFLWPOB
          RH2BFB1=ZHPW2(L,NY,NX)*VFLWPOB
          ICHKL=1
        ENDIF
      ENDIF
    ELSE
      RCOFLS0=0.0_r8
      RCHFLS0=0.0_r8
      ROXFLS0=0.0_r8
      RNGFLS0=0.0_r8
      RN2FLS0=0.0_r8
      RN4FLW0=0.0_r8
      RN3FLW0=0.0_r8
      RNOFLW0=0.0_r8
      RH1PFS0=0.0_r8
      RH2PFS0=0.0_r8
      RCOFLS1=0.0_r8
      RCHFLS1=0.0_r8
      ROXFLS1=0.0_r8
      RNGFLS1=0.0_r8
      RN2FLS1=0.0_r8
      RN4FLW1=0.0_r8
      RN3FLW1=0.0_r8
      RNOFLW1=0.0_r8
      RH1PFS1=0.0_r8
      RH2PFS1=0.0_r8
      RN4FLB1=0.0_r8
      RN3FLB1=0.0_r8
      RNOFLB1=0.0_r8
      RH1BFB1=0.0_r8
      RH2BFB1=0.0_r8
    ENDIF
  ENDDO
  end subroutine SoluteFluxSnowpack

end module SurfaceFluxMod
