module TransfrDataMod
  use data_kind_mod, only : r8 => SHR_KIND_R8
  use GridConsts
implicit none
  public
  CHARACTER(LEN=*),private,PARAMETER :: MOD_FILENAME=__FILE__
  real(r8), parameter :: XFRS=0.05_r8
  real(r8),allocatable :: RFLOC(:)
  real(r8),allocatable :: RFLON(:)
  real(r8),allocatable :: RFLOP(:)
  real(r8),allocatable :: RFLOA(:)
  real(r8),allocatable :: DFVOC(:)
  real(r8),allocatable :: DFVON(:)
  real(r8),allocatable :: DFVOP(:)
  real(r8),allocatable :: DFVOA(:)
  real(r8),allocatable :: DFHOC(:)
  real(r8),allocatable :: DFHON(:)
  real(r8),allocatable :: DFHOP(:)
  real(r8),allocatable :: DFHOA(:)
  real(r8),allocatable :: COQC1(:)
  real(r8),allocatable :: COQC2(:)
  real(r8),allocatable :: COQN1(:)
  real(r8),allocatable :: COQN2(:)
  real(r8),allocatable :: COQP1(:)
  real(r8),allocatable :: COQP2(:)
  real(r8),allocatable :: COQA1(:)
  real(r8),allocatable :: COQA2(:)
  real(r8), allocatable :: OQC2(:,:,:,:)
  real(r8), allocatable :: OQN2(:,:,:,:)
  real(r8), allocatable :: OQP2(:,:,:,:)
  real(r8), allocatable :: OQA2(:,:,:,:)
  real(r8), allocatable :: ROCFLS(:,:,:,:,:)
  real(r8), allocatable :: RONFLS(:,:,:,:,:)
  real(r8), allocatable :: ROPFLS(:,:,:,:,:)
  real(r8), allocatable :: ROAFLS(:,:,:,:,:)
  real(r8), allocatable :: ROCFHS(:,:,:,:,:)
  real(r8), allocatable :: RONFHS(:,:,:,:,:)
  real(r8), allocatable :: ROPFHS(:,:,:,:,:)
  real(r8), allocatable :: ROAFHS(:,:,:,:,:)
  real(r8), allocatable :: TOCFLS(:,:,:,:)
  real(r8), allocatable :: TONFLS(:,:,:,:)
  real(r8), allocatable :: TOPFLS(:,:,:,:)
  real(r8), allocatable :: TOAFLS(:,:,:,:)
  real(r8), allocatable :: ROCSK2(:,:,:,:)
  real(r8), allocatable :: RONSK2(:,:,:,:)
  real(r8), allocatable :: ROPSK2(:,:,:,:)
  real(r8), allocatable :: ROASK2(:,:,:,:)

  real(r8), allocatable :: RQROC0(:,:,:)
  real(r8), allocatable :: RQRON0(:,:,:)
  real(r8), allocatable :: RQROA0(:,:,:)
  real(r8), allocatable :: RQROP0(:,:,:)

  real(r8) :: RCOBLS(JS,JY,JX),RCHBLS(JS,JY,JX)
  real(r8) :: ROXBLS(JS,JY,JX),RNGBLS(JS,JY,JX),RN2BLS(JS,JY,JX)
  real(r8) :: RN4BLW(JS,JY,JX),RN3BLW(JS,JY,JX),RNOBLW(JS,JY,JX)
  real(r8) :: RH1PBS(JS,JY,JX),RH2PBS(JS,JY,JX)

  real(r8) :: ROCFL0(0:2,JY,JX),RONFL0(0:2,JY,JX),ROPFL0(0:2,JY,JX)
  real(r8) :: ROAFL0(0:2,JY,JX),ROCFL1(0:2,JY,JX),RONFL1(0:2,JY,JX)
  real(r8) :: ROPFL1(0:2,JY,JX),ROAFL1(0:2,JY,JX),RCOFL0(JY,JX),RCHFL0(JY,JX)
  real(r8) :: ROXFL0(JY,JX),RNGFL0(JY,JX),RN2FL0(JY,JX),RHGFL0(JY,JX)
  real(r8) :: RN4FL0(JY,JX),RN3FL0(JY,JX),RNOFL0(JY,JX),RNXFL0(JY,JX)
  real(r8) :: RH2PF0(JY,JX),RCOFL1(JY,JX),RCHFL1(JY,JX),ROXFL1(JY,JX)
  real(r8) :: RNGFL1(JY,JX),RN2FL1(JY,JX),RHGFL1(JY,JX),RN4FL1(JY,JX)
  real(r8) :: RN3FL1(JY,JX),RNOFL1(JY,JX),RNXFL1(JY,JX),RH2PF1(JY,JX)
  real(r8) :: RN4FL2(JY,JX),RN3FL2(JY,JX),RNOFL2(JY,JX),RNXFL2(JY,JX)
  real(r8) :: RH2BF2(JY,JX),RH1PF0(JY,JX),RH1PF1(JY,JX),RH1BF2(JY,JX)
  real(r8) :: ROCFXS(0:4,JZ,JY,JX),RONFXS(0:4,JZ,JY,JX)
  real(r8) :: ROPFXS(0:4,JZ,JY,JX),ROAFXS(0:4,JZ,JY,JX),RCOFXS(JZ,JY,JX)
  real(r8) :: RCHFXS(JZ,JY,JX),ROXFXS(JZ,JY,JX)
  real(r8) :: RNGFXS(JZ,JY,JX),RN2FXS(JZ,JY,JX),RN4FXW(JZ,JY,JX)
  real(r8) :: RN3FXW(JZ,JY,JX),RNOFXW(JZ,JY,JX),RH2PXS(JZ,JY,JX)
  real(r8) :: RN4FXB(JZ,JY,JX),RN3FXB(JZ,JY,JX),RNOFXB(JZ,JY,JX)
  real(r8) :: RH2BXB(JZ,JY,JX),RNXFXS(JZ,JY,JX),RNXFXB(JZ,JY,JX)
  real(r8) :: RH1PXS(JZ,JY,JX),RH1BXB(JZ,JY,JX)
  real(r8) :: CLSGL2(0:JZ,JY,JX),CQSGL2(0:JZ,JY,JX),POSGL2(0:JZ,JY,JX)
  real(r8) :: OLSGL2(0:JZ,JY,JX),ZNSGL2(0:JZ,JY,JX),ZLSGL2(0:JZ,JY,JX)
  real(r8) :: ZVSGL2(0:JZ,JY,JX),HLSGL2(0:JZ,JY,JX),ZOSGL2(0:JZ,JY,JX)

  real(r8) :: RCODFG(0:JZ,JY,JX)  !CO2 volatilization/dissolution within soil layer	g d-2 t-1
  real(r8) :: RCHDFG(0:JZ,JY,JX)  !CH4 volatilization/dissolution within soil layer	g d-2 t-1
  real(r8) :: ROXDFG(0:JZ,JY,JX)  !O2 volatilization/dissolution within soil layer	g d-2 t-1
  real(r8) :: RNGDFG(0:JZ,JY,JX)  !N2 volatilization/dissolution within soil layer	g d-2 t-1
  real(r8) :: RN2DFG(0:JZ,JY,JX)  !N2O volatilization/dissolution within soil layer	g d-2 t-1
  real(r8) :: RN3DFG(0:JZ,JY,JX)  !NH3 volatilization/dissolution within soil layer non-band	g d-2 t-1
  real(r8) :: RNBDFG(0:JZ,JY,JX)  !NH3 volatilization/dissolution within soil layer band	g d-2 t-1
  real(r8) :: TQROC(0:4,JY,JX)
  real(r8) :: TQRON(0:4,JY,JX),TQROP(0:4,JY,JX),TQROA(0:4,JY,JX)
  real(r8) :: TQRCHS(JY,JX),TQROXS(JY,JX),TQRNGS(JY,JX),TQRN2S(JY,JX)
  real(r8) :: TQRNH4(JY,JX),TQRNH3(JY,JX),TQRNO3(JY,JX),TQRH2P(JY,JX)
  real(r8) :: TQRNO2(JY,JX),TQRHGS(JY,JX),TQSCOS(JY,JX),TQRCOS(JY,JX)
  real(r8) :: TQSCHS(JY,JX),TQSOXS(JY,JX),TQSNGS(JY,JX),TQSN2S(JY,JX)
  real(r8) :: TQSNH4(JY,JX),TQSNH3(JY,JX),TQSNO3(JY,JX),TQSH1P(JY,JX)
  real(r8) :: TQSH2P(JY,JX),TCOFLS(JZ,JY,JX)
  real(r8) :: TCHFLS(JZ,JY,JX),TOXFLS(JZ,JY,JX),TNGFLS(JZ,JY,JX)
  real(r8) :: TN2FLS(JZ,JY,JX),TN4FLW(JZ,JY,JX),TN3FLW(JZ,JY,JX)
  real(r8) :: TNOFLW(JZ,JY,JX),TH2PFS(JZ,JY,JX),TN4FLB(JZ,JY,JX)
  real(r8) :: TN3FLB(JZ,JY,JX),TNOFLB(JZ,JY,JX),TH2BFB(JZ,JY,JX)
  real(r8) :: TNXFLS(JZ,JY,JX),TCOFLG(JZ,JY,JX),TCHFLG(JZ,JY,JX)
  real(r8) :: TOXFLG(JZ,JY,JX),TNGFLG(JZ,JY,JX),TN2FLG(JZ,JY,JX)
  real(r8) :: TQRH1P(JY,JX),TH1PFS(JZ,JY,JX),TH1BFB(JZ,JY,JX)
  real(r8) :: DCO2G(3,JZ,JY,JX),DCH4G(3,JZ,JY,JX)
  real(r8) :: DOXYG(3,JZ,JY,JX),DZ2GG(3,JZ,JY,JX),DZ2OG(3,JZ,JY,JX)
  real(r8) :: DNH3G(3,JZ,JY,JX),VOLWCO(0:JZ,JY,JX),VOLWCH(0:JZ,JY,JX)
  real(r8) :: VOLWOX(0:JZ,JY,JX),VOLWNG(0:JZ,JY,JX),VOLWN2(0:JZ,JY,JX)
  real(r8) :: VOLWN3(0:JZ,JY,JX),VOLWNB(0:JZ,JY,JX),VOLWHG(0:JZ,JY,JX)
  real(r8) :: HGSGL2(JZ,JY,JX),DH2GG(3,JZ,JY,JX),RHGFXS(JZ,JY,JX)
  real(r8) :: THGFHS(JZ,JY,JX),THGFLG(JZ,JY,JX),FLVM(JZ,JY,JX)
  real(r8) :: THETH2(JZ,JY,JX),THETHL(JZ,JY,JX),VOLPMA(JZ,JY,JX)
  real(r8) :: VOLPMB(JZ,JY,JX),VOLWMA(JZ,JY,JX),VOLWMB(JZ,JY,JX)
  real(r8) :: VOLWXA(0:JZ,JY,JX),VOLWXB(JZ,JY,JX),PARGCO(JY,JX)
  real(r8) :: PARGCH(JY,JX),PARGOX(JY,JX),PARGNG(JY,JX)
  real(r8) :: PARGN2(JY,JX),PARGN3(JY,JX),PARGH2(JY,JX)

  real(r8) :: RCOSK2(0:JZ,JY,JX),ROXSK2(0:JZ,JY,JX),RCHSK2(0:JZ,JY,JX)
  real(r8) :: RNGSK2(0:JZ,JY,JX),RN2SK2(0:JZ,JY,JX),RN4SK2(0:JZ,JY,JX)
  real(r8) :: RN3SK2(0:JZ,JY,JX),RNOSK2(0:JZ,JY,JX),RHPSK2(0:JZ,JY,JX)
  real(r8) :: R4BSK2(JZ,JY,JX),R3BSK2(JZ,JY,JX),RNBSK2(JZ,JY,JX)
  real(r8) :: RHBSK2(JZ,JY,JX),RNXSK2(0:JZ,JY,JX),RNZSK2(JZ,JY,JX)
  real(r8) :: RHGSK2(0:JZ,JY,JX),RNHSK2(0:JZ,JY,JX),R1PSK2(0:JZ,JY,JX)

  real(r8) :: TN3FLG(JZ,JY,JX),RCOBBL(JZ,JY,JX)
  real(r8) :: RCHBBL(JZ,JY,JX),ROXBBL(JZ,JY,JX),RNGBBL(JZ,JY,JX)
  real(r8) :: RN2BBL(JZ,JY,JX),RN3BBL(JZ,JY,JX),RNBBBL(JZ,JY,JX)
  real(r8) :: RHGBBL(JZ,JY,JX)

  real(r8) :: RQRCOS0(JV,JH),RQRCHS0(JV,JH)
  real(r8) :: RQROXS0(JV,JH),RQRNGS0(JV,JH),RQRN2S0(JV,JH)
  real(r8) :: RQRHGS0(JV,JH),RQRNH40(JV,JH),RQRNH30(JV,JH)
  real(r8) :: RQRNO30(JV,JH),RQRNO20(JV,JH),RQRH2P0(JV,JH)
  real(r8) :: RQRH1P0(JV,JH)
  real(r8) :: OQNH2(0:4,JZ,JY,JX),OQPH2(0:4,JZ,JY,JX),OQAH2(0:4,JZ,JY,JX)
  real(r8) :: TOCFHS(0:4,JZ,JY,JX),TONFHS(0:4,JZ,JY,JX),TOPFHS(0:4,JZ,JY,JX)
  real(r8) :: TOAFHS(0:4,JZ,JY,JX),TCOFHS(JZ,JY,JX),TCHFHS(JZ,JY,JX)
  real(r8) :: TOXFHS(JZ,JY,JX),TNGFHS(JZ,JY,JX),TN2FHS(JZ,JY,JX)
  real(r8) :: TN4FHW(JZ,JY,JX),TN3FHW(JZ,JY,JX),TNOFHW(JZ,JY,JX)
  real(r8) :: TH2PHS(JZ,JY,JX),TN4FHB(JZ,JY,JX),TN3FHB(JZ,JY,JX)
  real(r8) :: TNOFHB(JZ,JY,JX),TH2BHB(JZ,JY,JX),TNXFHS(JZ,JY,JX)
  real(r8) :: ZNO2B2(JZ,JY,JX),ZN2BH2(JZ,JY,JX),TNXFLB(JZ,JY,JX)
  real(r8) :: TNXFHB(JZ,JY,JX),H1P4H2(JZ,JY,JX),H1PBH2(JZ,JY,JX)
  real(r8) :: TH1PHS(JZ,JY,JX),TH1BHB(JZ,JY,JX)
  REAL(R8) :: H1PO42(0:JZ,JY,JX),H1POB2(0:JZ,JY,JX)
  real(r8) :: OCSGL2(0:JZ,JY,JX),ONSGL2(0:JZ,JY,JX)
  real(r8) :: OPSGL2(0:JZ,JY,JX),OASGL2(0:JZ,JY,JX)
  real(r8) :: CO2W2(JS,JY,JX),CH4W2(JS,JY,JX),OXYW2(JS,JY,JX),ZNGW2(JS,JY,JX)
  real(r8) :: ZN2W2(JS,JY,JX),ZN4W2(JS,JY,JX),ZN3W2(JS,JY,JX),ZNOW2(JS,JY,JX)
  real(r8) :: ZHPW2(JS,JY,JX),Z1PW2(JS,JY,JX)
  real(r8) :: TCOBLS(JS,JY,JX)
  real(r8) :: TCHBLS(JS,JY,JX),TOXBLS(JS,JY,JX),TNGBLS(JS,JY,JX)
  real(r8) :: TN2BLS(JS,JY,JX),TN4BLW(JS,JY,JX),TN3BLW(JS,JY,JX)
  real(r8) :: TNOBLW(JS,JY,JX),TH1PBS(JS,JY,JX),TH2PBS(JS,JY,JX)
  real(r8) :: RQROP(0:4,2,2,JV,JH),RQROA(0:4,2,2,JV,JH),RQRCOS(2,2,JV,JH)
  real(r8) :: RQRCHS(2,2,JV,JH),RQROXS(2,2,JV,JH),RQRNGS(2,2,JV,JH)
  real(r8) :: RQRN2S(2,2,JV,JH),RQRHGS(2,2,JV,JH),RQRNH4(2,2,JV,JH)
  real(r8) :: RCODFS(JY,JX),RCHDFS(JY,JX),ROXDFS(JY,JX)
  real(r8) :: RNGDFS(JY,JX),RN2DFS(JY,JX),RN3DFS(JY,JX),RNBDFS(JY,JX)
  real(r8) :: RHGDFS(JY,JX),RCODFR(JY,JX),RCHDFR(JY,JX),ROXDFR(JY,JX)
  real(r8) :: RNGDFR(JY,JX),RN2DFR(JY,JX),RN3DFR(JY,JX),RHGDFR(JY,JX)
  real(r8) :: R1BSK2(JZ,JY,JX),RQROC(0:4,2,2,JV,JH),RQRON(0:4,2,2,JV,JH)

  real(r8) :: ZNH4S2(0:JZ,JY,JX),ZNH4B2(0:JZ,JY,JX),ZNH3S2(0:JZ,JY,JX)
  real(r8) :: ZNH3B2(0:JZ,JY,JX),ZNO3S2(0:JZ,JY,JX),ZNO3B2(0:JZ,JY,JX)
  real(r8) :: H2PO42(0:JZ,JY,JX),H2POB2(0:JZ,JY,JX),ZNO2S2(0:JZ,JY,JX)
  real(r8) :: CGSGL2(JZ,JY,JX),CHSGL2(JZ,JY,JX),OGSGL2(JZ,JY,JX)
  real(r8) :: ZGSGL2(JZ,JY,JX),Z2SGL2(JZ,JY,JX),ZHSGL2(JZ,JY,JX)
  real(r8) :: CO2SH2(JZ,JY,JX),CH4SH2(JZ,JY,JX),OXYSH2(JZ,JY,JX)
  real(r8) :: Z2GSH2(JZ,JY,JX),Z2OSH2(JZ,JY,JX),ZNH4H2(JZ,JY,JX)
  real(r8) :: ZN4BH2(JZ,JY,JX),ZNH3H2(JZ,JY,JX),ZN3BH2(JZ,JY,JX)
  real(r8) :: ZNO3H2(JZ,JY,JX),ZNOBH2(JZ,JY,JX),H2P4H2(JZ,JY,JX)
  real(r8) :: H2PBH2(JZ,JY,JX),ZNO2H2(JZ,JY,JX),OQCH2(0:4,JZ,JY,JX)

  real(r8) :: CH4G2(JZ,JY,JX),CH4S2(0:JZ,JY,JX),OXYG2(JZ,JY,JX)
  real(r8) :: OXYS2(0:JZ,JY,JX),Z2GG2(JZ,JY,JX),Z2GS2(0:JZ,JY,JX)
  real(r8) :: Z2OG2(JZ,JY,JX),Z2OS2(0:JZ,JY,JX),ZN3G2(0:JZ,JY,JX)
  real(r8) :: CO2G2(JZ,JY,JX),CO2S2(0:JZ,JY,JX)
  real(r8) :: H2GG2(JZ,JY,JX),H2GS2(0:JZ,JY,JX),H2GSH2(JZ,JY,JX)
  real(r8) :: RQSH2P(2,JV,JH),RQSH1P(2,JV,JH)
  real(r8) :: RQSCOS(2,JV,JH),RQSCHS(2,JV,JH),RQSOXS(2,JV,JH)
  real(r8) :: RQRH2P(2,2,JV,JH),RQRH1P(2,2,JV,JH)
  real(r8) :: RHGFLG(3,JD,JV,JH),THGFLS(JZ,JY,JX)
  real(r8) :: ROXFLG(3,JD,JV,JH),RN3FLG(3,JD,JV,JH),RCOFLG(3,JD,JV,JH)
  real(r8) :: RNXFHS(3,JD,JV,JH),RNXFHB(3,JD,JV,JH),RH1PFS(3,0:JD,JV,JH)
  real(r8) :: RH1BFB(3,0:JD,JV,JH),RH1PHS(3,JD,JV,JH),RH1BHB(3,JD,JV,JH)
  real(r8) :: RCHFLG(3,JD,JV,JH),RNGFLG(3,JD,JV,JH),RN2FLG(3,JD,JV,JH)
  real(r8) :: RN3FHB(3,JD,JV,JH),RNOFHB(3,JD,JV,JH),RH2BHB(3,JD,JV,JH)
  real(r8) :: RNOFHW(3,JD,JV,JH),RH2PHS(3,JD,JV,JH),RN4FHB(3,JD,JV,JH)
  real(r8) :: RN2FHS(3,JD,JV,JH),RN4FHW(3,JD,JV,JH),RN3FHW(3,JD,JV,JH)
  real(r8) :: RHGDFG(0:JZ,JY,JX),RHGFHS(3,JD,JV,JH)
  real(r8) :: RCHFHS(3,JD,JV,JH),ROXFHS(3,JD,JV,JH),RNGFHS(3,JD,JV,JH)
  real(r8) :: RQRNH3(2,2,JV,JH),RQRNO3(2,2,JV,JH),RQRNO2(2,2,JV,JH)
  real(r8) :: RQSNGS(2,JV,JH),RQSN2S(2,JV,JH),RQSNH4(2,JV,JH)
  real(r8) :: RQSNH3(2,JV,JH),RQSNO3(2,JV,JH)
  real(r8) :: RCOFLS(3,0:JD,JV,JH),RCHFLS(3,0:JD,JV,JH)
  real(r8) :: ROXFLS(3,0:JD,JV,JH),RNGFLS(3,0:JD,JV,JH),RN2FLS(3,0:JD,JV,JH)
  real(r8) :: RHGFLS(3,0:JD,JV,JH),RN4FLW(3,0:JD,JV,JH),RN3FLW(3,0:JD,JV,JH)
  real(r8) :: RNOFLW(3,0:JD,JV,JH),RNXFLS(3,0:JD,JV,JH),RH2PFS(3,0:JD,JV,JH)
  real(r8) :: RN4FLB(3,0:JD,JV,JH),RN3FLB(3,0:JD,JV,JH),RNOFLB(3,0:JD,JV,JH)
  real(r8) :: RNXFLB(3,0:JD,JV,JH),RH2BFB(3,0:JD,JV,JH),RCOFHS(3,JD,JV,JH)


  real(r8),parameter :: VFLWX=0.5
end module TransfrDataMod
