      real(r8) :: OFFST(JP,JY,JX),RRAD1M(2,JP,JY,JX),RRAD2M(2,JP,JY,JX)
     2,TCZ(JP,JY,JX),PORT(2,JP,JY,JX),PR(JP,JY,JX),RSRR(2,JP,JY,JX)
     3,RSRA(2,JP,JY,JX),PTSHT(JP,JY,JX),UPMXZH(2,JP,JY,JX)
     4,UPKMZH(2,JP,JY,JX),UPMNZH(2,JP,JY,JX),UPMXZO(2,JP,JY,JX)
     5,UPKMZO(2,JP,JY,JX),UPMNZO(2,JP,JY,JX),UPMXPO(2,JP,JY,JX)
     6,UPKMPO(2,JP,JY,JX),UPMNPO(2,JP,JY,JX),RRADP(2,JP,JY,JX)
     7,CNRTS(JP,JY,JX),CPRTS(JP,JY,JX),ALBR(JP,JY,JX),ALBP(JP,JY,JX)
     8,TAUR(JP,JY,JX),TAUP(JP,JY,JX),ABSR(JP,JY,JX),ABSP(JP,JY,JX)
     9,TCX(JP,JY,JX),ZTYPI(JP,JY,JX),TCZD,TCXD
     1,ZTYP(JP,JY,JX)
      integer :: ICTYP(JP,JY,JX),IGTYP(JP,JY,JX),ISTYP(JP,JY,JX)
     2,IDTYP(JP,JY,JX),NNOD(JP,JY,JX),INTYP(JP,JY,JX),IWTYP(JP,JY,JX)
     3,IPTYP(JP,JY,JX),IBTYP(JP,JY,JX),IRTYP(JP,JY,JX),MY(JP,JY,JX)

      COMMON/BLK9B/OFFST,RRAD1M,RRAD2M
     2,TCZ,PORT,PR,RSRR
     3,RSRA,PTSHT,UPMXZH
     4,UPKMZH,UPMNZH,UPMXZO
     5,UPKMZO,UPMNZO,UPMXPO
     6,UPKMPO,UPMNPO,RRADP
     7,CNRTS,CPRTS,ALBR,ALBP
     8,TAUR,TAUP,ABSR,ABSP
     9,TCX,ZTYPI,TCZD,TCXD
     1,ZTYP,ICTYP,IGTYP,ISTYP
     2,IDTYP,NNOD,INTYP,IWTYP
     3,IPTYP,IBTYP,IRTYP,MY
