module PlantAPIData
  use data_kind_mod, only : r8 => SHR_KIND_R8
implicit none
  integer  :: JP1,JSA1,jcplx11,JLA1
  integer  :: JC1,JZ1,JLI1,JNODS1
!begin_data
  real(r8) :: TYSINs1
  real(r8) :: ALBSs1
  real(r8) :: ALATs1
  real(r8) :: ATCAs1
  real(r8) :: ALBXs1
  real(r8) :: ARLSSs1
  real(r8) :: ARLFCs1
  real(r8) :: ALTs1
  real(r8) :: VOLWSs1
  real(r8) :: CCO2EIs1
  real(r8) :: CO2EIs1
  real(r8) :: COXYEs1
  real(r8) :: RABs1
  real(r8) :: VOLSSs1
  real(r8) :: TSHCs1
  real(r8) :: CNETXs1
  real(r8) :: ZNOONs1
  real(r8) :: GAZIs1
  real(r8) :: GCOSs1
  real(r8) :: CO2Es1
  real(r8) :: CCO2Es1
  real(r8) :: CCH4Es1
  real(r8) :: CZ2OEs1
  real(r8) :: CH2GEs1
  real(r8) :: CNH3Es1
  real(r8) :: DYLXs1
  real(r8) :: RAP0s1
  real(r8) :: RADYs1
  real(r8) :: RADSs1
  real(r8) :: RAPYs1
  real(r8) :: RAPSs1
  real(r8) :: DYLNs1
  real(r8) :: DPTHSs1
  real(r8) :: DYLMs1
  real(r8) :: ZSs1
  real(r8) :: OXYEs1
  real(r8) :: PPTs1
  real(r8) :: RIBs1
  real(r8) :: RECOs1
  real(r8) :: POROS1s1
  real(r8) :: UAs1
  real(r8) :: TGHs1
  real(r8) :: TBALCs1
  real(r8) :: TBALNs1
  real(r8) :: TBALPs1
  real(r8) :: Z0s1
  real(r8) :: VHCPWXs1
  real(r8) :: VHCPW1s1
  real(r8) :: TCCANs1
  real(r8) :: TCH4Zs1
  real(r8) :: TENGYCs1
  real(r8) :: THRMCs1
  real(r8) :: TEVAPPs1
  real(r8) :: TCO2Zs1
  real(r8) :: TEVAPCs1
  real(r8) :: TH2GZs1
  real(r8) :: THFLXCs1
  real(r8) :: TRNs1
  real(r8) :: RAD0s1
  real(r8) :: FRADGs1
  real(r8) :: TRAPCs1
  real(r8) :: RADGs1
  real(r8) :: GSINs1
  real(r8) :: TN2OZs1
  real(r8) :: TLEs1
  real(r8) :: TOXYZs1
  real(r8) :: TNH3Zs1
  real(r8) :: TVOLWPs1
  real(r8) :: SSINNs1
  real(r8) :: SSINs1
  real(r8) :: ZZSNCs1
  real(r8) :: ZPSNCs1
  real(r8) :: ZCSNCs1
  real(r8) :: VOLISs1
  real(r8) :: WTSTGTs1
  real(r8) :: ARSTCs1
  real(r8) :: TKWs1
  real(r8) :: TVOLWCs1
  real(r8) :: TSHs1
  real(r8) :: TNBPs1
  real(r8) :: TGPPs1
  real(r8) :: TKAs1
  real(r8) :: TLECs1
  real(r8) :: THRMGXs1
  real(r8) :: THSs1
  real(r8) :: TRAUs1
  real(r8) :: UVOLOs1
  real(r8) :: VPAs1
  real(r8) :: XHVSTCs1
  real(r8) :: XHVSTNs1
  real(r8) :: XHVSTPs1
  real(r8) :: XCORPs1
  real(r8) :: ZEROS2s1
  real(r8) :: ZEROSs1
  real(r8) :: ZEROs1
  real(r8) :: ZERO2s1
  real(r8) :: ZRs1     !canopy surface roughness height, [m]
  real(r8) :: ZTs1     !canopy height , [m]
  real(r8) :: ZDs1     !zero plane displacement height, [m]
  integer :: IYTYPs1
  integer :: IETYPs1
  integer :: IFLGTs1
  integer :: NLs1
  integer :: NP0s1
  integer :: NJs1
  integer :: NPs1
  integer :: NUs1
  integer :: LYRCs1
  integer :: IYRCs1                    !current year
!  real(r8) :: AREA3Us1
  real(r8) :: DCORPs1
  real(r8) :: VOLWOUs1
  integer :: ITILLs1
  real(r8), allocatable :: AREA3s1(:)    !soil thickness
  integer,  allocatable :: IDTHs1(:)     !flag for species death
  integer,  allocatable :: IYR0s1(:)     !year of planting
  integer,  allocatable :: IDAYXs1(:)    !!alternate day of planting
  integer,  allocatable :: IYRXs1(:)     !alternate year of planting
  integer,  allocatable :: IYRYs1(:)     !alternate year of harvest
  integer,  allocatable :: INTYPs1(:)    !N2 fixation type
  integer,  allocatable :: IFLGCs1(:)    !flag for living pft
  integer,  allocatable :: IDAY0s1(:)    !day of planting
  integer,  allocatable :: IDAYHs1(:)    !day of harvest
  integer,  allocatable :: IYRHs1(:)     !year of harvest
  integer,  allocatable :: IWTYPs1(:)    !climate signal for phenological progress: none, temperature, water stress
  integer,  allocatable :: IHVSTs1(:)    !type of harvest
  integer,  allocatable :: JHVSTs1(:)    !flag for stand replacing disturbance
  integer,  allocatable :: IBTYPs1(:)    !phenologically-driven above-ground turnover: all, foliar only, none
  integer,  allocatable :: IDTHPs1(:)    !flag to detect canopy death
  integer,  allocatable :: ISTYPs1(:)    !plant growth habit: annual or perennial
  integer,  allocatable :: ICTYPs1(:)    !plant photosynthetic type (C3 or C4)
  integer,  allocatable :: IDTHRs1(:)    !flag to detect root system death
  integer,  allocatable :: NB1s1(:)      !number of main branch
  integer,  allocatable :: NIs1(:)       !maximum soil layer number for all root axes
  integer,  allocatable :: NRTs1(:)      !root primary axis number
  integer,  allocatable :: NNODs1(:)     !number of concurrently growing nodes
  integer,  allocatable :: NBTs1(:)      !branch number
  integer,  allocatable :: MYs1(:)
  integer,  allocatable :: NGs1(:)
  integer,  allocatable :: NBRs1(:)
  integer,  allocatable :: NIXs1(:)
  integer,  allocatable :: IDTYPs1(:)
  integer,  allocatable :: IPTYPs1(:)
  integer,  allocatable :: IGTYPs1(:)
  integer,  allocatable :: IFLGIs1(:)
  integer,  allocatable :: IDATAs1(:)
  real(r8), allocatable :: FERTs1(:)
  real(r8), allocatable :: TDFOMCs1(:,:)
  real(r8), allocatable :: TDFOMPs1(:,:)
  real(r8), allocatable :: TDFOMNs1(:,:)
  real(r8), allocatable :: RUPNFs1(:,:)
  real(r8), allocatable :: ARLFTs1(:)
  real(r8), allocatable :: ARLFSs1(:)
  real(r8), allocatable :: RCSs1(:)
  real(r8), allocatable :: TAUSs1(:)
  real(r8), allocatable :: TAU0s1(:)
  real(r8), allocatable :: ANGBRs1(:)
  real(r8), allocatable :: SSL1s1(:)
  real(r8), allocatable :: SNL1s1(:)
  real(r8), allocatable :: CPEARs1(:)
  real(r8), allocatable :: DMSHEs1(:)
  real(r8), allocatable :: ABSRs1(:)
  real(r8), allocatable :: ABSPs1(:)
  real(r8), allocatable :: CPHSKs1(:)
  real(r8), allocatable :: DMSTKs1(:)
  real(r8), allocatable :: DMHSKs1(:)
  real(r8), allocatable :: DMRSVs1(:)
  real(r8), allocatable :: DMGRs1(:)
  real(r8), allocatable :: DMEARs1(:)
  real(r8), allocatable :: OMEGAGs1(:)
  real(r8), allocatable :: CNHSKs1(:)
  real(r8), allocatable :: CNRSVs1(:)
  real(r8), allocatable :: CNEARs1(:)
  real(r8), allocatable :: CPRSVs1(:)
  real(r8), allocatable :: ANGSHs1(:)
  real(r8), allocatable :: SLA1s1(:)
  real(r8), allocatable :: FCO2s1(:)
  real(r8), allocatable :: ZCOSs1(:)
  real(r8), allocatable :: XKO2s1(:)
  real(r8), allocatable :: CPO4Ss1(:)
  real(r8), allocatable :: CNDUs1(:)
  real(r8), allocatable :: WGLFTs1(:)
  real(r8), allocatable :: ARSTTs1(:)
  real(r8), allocatable :: CGSGLs1(:)
  real(r8), allocatable :: CHSGLs1(:)
  real(r8), allocatable :: HGSGLs1(:)
  real(r8), allocatable :: OGSGLs1(:)
  real(r8), allocatable :: ETMXs1(:)
  real(r8), allocatable :: TAURs1(:)
  real(r8), allocatable :: TAUPs1(:)
  real(r8), allocatable :: CHLs1(:)
  real(r8), allocatable :: PEPCs1(:)
  real(r8), allocatable :: CHL4s1(:)
  real(r8), allocatable :: RADCs1(:)
  real(r8), allocatable :: RUBPs1(:)
  real(r8), allocatable :: VCMX4s1(:)
  real(r8), allocatable :: VOMXs1(:)
  real(r8), allocatable :: VCMXs1(:)
  real(r8), allocatable :: XKCO2s1(:)
  real(r8), allocatable :: WTSTDIs1(:)
  real(r8), allocatable :: TCCs1(:)
  real(r8), allocatable :: CPGRs1(:)
  real(r8), allocatable :: DTKCs1(:)
  real(r8), allocatable :: ENGYXs1(:)
  real(r8), allocatable :: TKCs1(:)
  real(r8), allocatable :: PSILOs1(:)
  real(r8), allocatable :: OSMOs1(:)
  real(r8), allocatable :: TCO2As1(:)
  real(r8), allocatable :: CTRANs1(:)
  real(r8), allocatable :: CNSTKs1(:)
  real(r8), allocatable :: ZTYPs1(:)
  real(r8), allocatable :: ZTYPIs1(:)
  real(r8), allocatable :: HTCs1(:)
  real(r8), allocatable :: SSTXs1(:)
  real(r8), allocatable :: RSCSs1(:)
  real(r8), allocatable :: Z2SGLs1(:)
  real(r8), allocatable :: ZHSGLs1(:)
  real(r8), allocatable :: BKDSs1(:)
  real(r8), allocatable :: CH2P4s1(:)
  real(r8), allocatable :: CH1P4Bs1(:)
  real(r8), allocatable :: CH2P4Bs1(:)
  real(r8), allocatable :: CNO3Ss1(:)
  real(r8), allocatable :: CH1P4s1(:)
  real(r8), allocatable :: CNO3Bs1(:)
  real(r8), allocatable :: CNH4Ss1(:)
  real(r8), allocatable :: CNH4Bs1(:)
  real(r8), allocatable :: CO2Gs1(:)
  real(r8), allocatable :: CO2Ss1(:)
  real(r8), allocatable :: CH4Ss1(:)
  real(r8), allocatable :: CCH4Ss1(:)
  real(r8), allocatable :: CZ2OSs1(:)
  real(r8), allocatable :: CNH3Ss1(:)
  real(r8), allocatable :: CNH3Bs1(:)
  real(r8), allocatable :: CH2GSs1(:)
  real(r8), allocatable :: CLSGLs1(:)
  real(r8), allocatable :: CQSGLs1(:)
  real(r8), allocatable :: CCH4Gs1(:)
  real(r8), allocatable :: CZ2OGs1(:)
  real(r8), allocatable :: CNH3Gs1(:)
  real(r8), allocatable :: CH2GGs1(:)
  real(r8), allocatable :: CORGCs1(:)
  real(r8), allocatable :: RSMHs1(:)
  real(r8), allocatable :: CFs1(:)
  real(r8), allocatable :: CDPTHZs1(:)
  real(r8), allocatable :: PPIs1(:)
  real(r8), allocatable :: PPZs1(:)
  real(r8), allocatable :: PPXs1(:)
  real(r8), allocatable :: DPTHZs1(:)
  real(r8), allocatable :: CFIs1(:)
  real(r8), allocatable :: WTRTs1(:)
  real(r8), allocatable :: FMPRs1(:)
  real(r8), allocatable :: FWODBs1(:)
  real(r8), allocatable :: ALBRs1(:)
  real(r8), allocatable :: ALBPs1(:)
  real(r8), allocatable :: FWODLNs1(:)
  real(r8), allocatable :: FWODLPs1(:)
  real(r8), allocatable :: FWODSPs1(:)
  real(r8), allocatable :: FWODSNs1(:)
  real(r8), allocatable :: FWODRNs1(:)
  real(r8), allocatable :: FWODRPs1(:)
  real(r8), allocatable :: FWODRs1(:)
  real(r8), allocatable :: FWOODs1(:)
  real(r8), allocatable :: FVRNs1(:)
  real(r8), allocatable :: FWOODNs1(:)
  real(r8), allocatable :: FWOODPs1(:)
  real(r8), allocatable :: H1PO4s1(:)
  real(r8), allocatable :: H2PO4s1(:)
  real(r8), allocatable :: H1POBs1(:)
  real(r8), allocatable :: H2POBs1(:)
  real(r8), allocatable :: H2GSs1(:)
  real(r8), allocatable :: HLSGLs1(:)
  real(r8), allocatable :: OXYGs1(:)
  real(r8), allocatable :: OXYSs1(:)
  real(r8), allocatable :: OLSGLs1(:)
  real(r8), allocatable :: POSGLs1(:)
  real(r8), allocatable :: PSISTs1(:)
  real(r8), allocatable :: RPO4Ys1(:)
  real(r8), allocatable :: RPOBYs1(:)
  real(r8), allocatable :: RP14Ys1(:)
  real(r8), allocatable :: RP1BYs1(:)
  real(r8), allocatable :: RNO3Ys1(:)
  real(r8), allocatable :: RNH4Ys1(:)
  real(r8), allocatable :: RNHBYs1(:)
  real(r8), allocatable :: RN3BYs1(:)
  real(r8), allocatable :: ROXYFs1(:)
  real(r8), allocatable :: RCO2Fs1(:)
  real(r8), allocatable :: ROXYLs1(:)
  real(r8), allocatable :: ROXYYs1(:)
  real(r8), allocatable :: SCO2Ls1(:)
  real(r8), allocatable :: PSILZs1(:)
  real(r8), allocatable :: RSMNs1(:)
  real(r8), allocatable :: DLYR3s1(:)
  real(r8), allocatable :: XKCO2Os1(:)
  real(r8), allocatable :: XKCO2Ls1(:)
  real(r8), allocatable :: WTRTSs1(:)
  real(r8), allocatable :: WTRTSNs1(:)
  real(r8), allocatable :: WTRTSPs1(:)
  real(r8), allocatable :: THRM1s1(:)
  real(r8), allocatable :: SFLXCs1(:)
  real(r8), allocatable :: RCs1(:)
  real(r8), allocatable :: TKCZs1(:)
  real(r8), allocatable :: RAs1(:)
  real(r8), allocatable :: SO2s1(:)
  real(r8), allocatable :: RAD1s1(:)
  real(r8), allocatable :: SOXYLs1(:)
  real(r8), allocatable :: SCH4Ls1(:)
  real(r8), allocatable :: SN2OLs1(:)
  real(r8), allocatable :: SNH3Ls1(:)
  real(r8), allocatable :: SH2GLs1(:)
  real(r8), allocatable :: THETWs1(:)
  real(r8), allocatable :: THETYs1(:)
  real(r8), allocatable :: TKSs1(:)
  real(r8), allocatable :: TFNDs1(:)
  real(r8), allocatable :: VOLXs1(:)
  real(r8), allocatable :: VLPOBs1(:)
  real(r8), allocatable :: VLNO3s1(:)
  real(r8), allocatable :: VLPO4s1(:)
  real(r8), allocatable :: VOLYs1(:)
  real(r8), allocatable :: VOLIs1(:)
  real(r8), allocatable :: VOLWs1(:)
  real(r8), allocatable :: VOLAs1(:)
  real(r8), allocatable :: VLNOBs1(:)
  real(r8), allocatable :: VLNH4s1(:)
  real(r8), allocatable :: VLNHBs1(:)
  real(r8), allocatable :: ZOSGLs1(:)
  real(r8), allocatable :: ZLs1(:)
  real(r8), allocatable :: ZNO3Ss1(:)
  real(r8), allocatable :: ZNO3Bs1(:)
  real(r8), allocatable :: ZNSGLs1(:)
  real(r8), allocatable :: ZNH4Ss1(:)
  real(r8), allocatable :: ZNH4Bs1(:)
  real(r8), allocatable :: Z2OSs1(:)
  real(r8), allocatable :: ZNH3Ss1(:)
  real(r8), allocatable :: ZNH3Bs1(:)
  real(r8), allocatable :: ZVSGLs1(:)
  real(r8), allocatable :: RP1BXs1(:)
  real(r8), allocatable :: RNO3Xs1(:)
  real(r8), allocatable :: RNH4Xs1(:)
  real(r8), allocatable :: RN3BXs1(:)
  real(r8), allocatable :: RPO4Xs1(:)
  real(r8), allocatable :: RPOBXs1(:)
  real(r8), allocatable :: TUPNO3s1(:)
  real(r8), allocatable :: TUPH2Bs1(:)
  real(r8), allocatable :: TUPH1Bs1(:)
  real(r8), allocatable :: TUPN2Ss1(:)
  real(r8), allocatable :: TCO2Ss1(:)
  real(r8), allocatable :: TCO2Ps1(:)
  real(r8), allocatable :: TUPOXPs1(:)
  real(r8), allocatable :: THGFLAs1(:)
  real(r8), allocatable :: TLH2GPs1(:)
  real(r8), allocatable :: TCHFLAs1(:)
  real(r8), allocatable :: TLCH4Ps1(:)
  real(r8), allocatable :: TLCO2Ps1(:)
  real(r8), allocatable :: TLNH3Ps1(:)
  real(r8), allocatable :: TUPHTs1(:)
  real(r8), allocatable :: TUPWTRs1(:)
  real(r8), allocatable :: RTDNTs1(:)
  real(r8), allocatable :: TUPNFs1(:)
  real(r8), allocatable :: TLOXYPs1(:)
  real(r8), allocatable :: TLN2OPs1(:)
  real(r8), allocatable :: TCOFLAs1(:)
  real(r8), allocatable :: TNHFLAs1(:)
  real(r8), allocatable :: TOXFLAs1(:)
  real(r8), allocatable :: TN2FLAs1(:)
  real(r8), allocatable :: TUPOXSs1(:)
  real(r8), allocatable :: TUPHGSs1(:)
  real(r8), allocatable :: TUPCHSs1(:)
  real(r8), allocatable :: TUPN3Bs1(:)
  real(r8), allocatable :: TUPN3Ss1(:)
  real(r8), allocatable :: TUPH2Ps1(:)
  real(r8), allocatable :: TUPH1Ps1(:)
  real(r8), allocatable :: TUPNH4s1(:)
  real(r8), allocatable :: TUPNHBs1(:)
  real(r8), allocatable :: TUPNOBs1(:)
  real(r8), allocatable :: ROXYXs1(:)
  real(r8), allocatable :: RNHBXs1(:)
  real(r8), allocatable :: RP14Xs1(:)
  real(r8), allocatable :: CSNTs1(:,:,:)
  real(r8), allocatable :: ZSNTs1(:,:,:)
  real(r8), allocatable :: PSNTs1(:,:,:)
  real(r8), allocatable :: RDFOMCs1(:,:,:,:)
  real(r8), allocatable :: RDFOMNs1(:,:,:,:)
  real(r8), allocatable :: RDFOMPs1(:,:,:,:)
  real(r8), allocatable :: FOSRHs1(:,:)
  real(r8), allocatable :: OQCs1(:,:)
  real(r8), allocatable :: OQNs1(:,:)
  real(r8), allocatable :: OQPs1(:,:)
  real(r8), allocatable :: XOQCSs1(:,:)
  real(r8), allocatable :: XOQNSs1(:,:)
  real(r8), allocatable :: XOQPSs1(:,:)
  real(r8), allocatable :: FLWCs1(:)
  real(r8), allocatable :: EHVSTs1(:,:,:)
  real(r8), allocatable :: HVSTs1(:)
  real(r8), allocatable :: THINs1(:)
  real(r8), allocatable :: ARSTPs1(:)
  real(r8), allocatable :: ARLFPs1(:)
  real(r8), allocatable :: BALCs1(:)
  real(r8), allocatable :: BALNs1(:)
  real(r8), allocatable :: BALPs1(:)
  real(r8), allocatable :: CO2Is1(:)
  real(r8), allocatable :: CCPOLPs1(:)
  real(r8), allocatable :: CPOOLPs1(:)
  real(r8), allocatable :: CPOLNPs1(:)
  real(r8), allocatable :: CCPLNPs1(:)
  real(r8), allocatable :: CZPOLPs1(:)
  real(r8), allocatable :: CPPOLPs1(:)
  real(r8), allocatable :: CTCs1(:)
  real(r8), allocatable :: CNETs1(:)
  real(r8), allocatable :: CPRTSs1(:)
  real(r8), allocatable :: CNRTSs1(:)
  real(r8), allocatable :: CARBNs1(:)
  real(r8), allocatable :: CNNDs1(:)
  real(r8), allocatable :: CPNDs1(:)
  real(r8), allocatable :: CNRTs1(:)
  real(r8), allocatable :: RSMXs1(:)
  real(r8), allocatable :: CPRTs1(:)
  real(r8), allocatable :: CNWSs1(:)
  real(r8), allocatable :: CPWSs1(:)
  real(r8), allocatable :: CFXs1(:)
  real(r8), allocatable :: CWSRTs1(:)
  real(r8), allocatable :: DCO2s1(:)
  character(len=16), allocatable :: DATAPs1(:)
  CHARACTER(len=16), allocatable :: DATAs1(:)
  real(r8), allocatable :: DMNDs1(:)
  real(r8), allocatable :: DMRTs1(:)
  real(r8), allocatable :: FMOLs1(:)
  real(r8), allocatable :: FNODs1(:)
  real(r8), allocatable :: GROUPIs1(:)
  real(r8), allocatable :: HTCTLs1(:)
  real(r8), allocatable :: HCSNCs1(:)
  real(r8), allocatable :: HZSNCs1(:)
  real(r8), allocatable :: HPSNCs1(:)
  real(r8), allocatable :: HVSTCs1(:)
  real(r8), allocatable :: HVSTNs1(:)
  real(r8), allocatable :: HVSTPs1(:)
  real(r8), allocatable :: HCUPTKs1(:)
  real(r8), allocatable :: HZUPTKs1(:)
  real(r8), allocatable :: HPUPTKs1(:)
  real(r8), allocatable :: HTSTZs1(:)
  real(r8), allocatable :: OFFSTs1(:)
  real(r8), allocatable :: OSTRs1(:)
  real(r8), allocatable :: PPs1(:)
  real(r8), allocatable :: PSILTs1(:)
  real(r8), allocatable :: PBs1(:)
  real(r8), allocatable :: PRs1(:)
  real(r8), allocatable :: PPOOLPs1(:)
  real(r8), allocatable :: PPOLNPs1(:)
  real(r8), allocatable :: PSILGs1(:)
  real(r8), allocatable :: RCMXs1(:)
  real(r8), allocatable :: RCO2Zs1(:)
  real(r8), allocatable :: ROXYZs1(:)
  real(r8), allocatable :: RCH4Zs1(:)
  real(r8), allocatable :: RN2OZs1(:)
  real(r8), allocatable :: RNH3Zs1(:)
  real(r8), allocatable :: RH2GZs1(:)
  real(r8), allocatable :: RSETCs1(:)
  real(r8), allocatable :: RSETNs1(:)
  real(r8), allocatable :: RSETPs1(:)
  real(r8), allocatable :: RTFQs1(:)
  real(r8), allocatable :: RAZs1(:)
  real(r8), allocatable :: CHILLs1(:)
  real(r8), allocatable :: CPSTKs1(:)
  real(r8), allocatable :: SCO2s1(:)
  real(r8), allocatable :: CO2Qs1(:)
  real(r8), allocatable :: O2Ls1(:)
  real(r8), allocatable :: EVAPCs1(:)
  real(r8), allocatable :: HFLXCs1(:)
  real(r8), allocatable :: GRNOs1(:)
  real(r8), allocatable :: EFLXCs1(:)
  real(r8), allocatable :: CO2Ls1(:)
  real(r8), allocatable :: SDPTHs1(:)
  real(r8), allocatable :: SDPTHIs1(:)
  real(r8), allocatable :: SDLGs1(:)
  real(r8), allocatable :: SDVLs1(:)
  real(r8), allocatable :: SDARs1(:)
  real(r8), allocatable :: TCZs1(:)
  real(r8), allocatable :: TCGs1(:)
  real(r8), allocatable :: TCXs1(:)
  real(r8), allocatable :: TKGs1(:)
  real(r8), allocatable :: TFN3s1(:)
  real(r8), allocatable :: TCSN0s1(:)
  real(r8), allocatable :: TZSN0s1(:)
  real(r8), allocatable :: TPSN0s1(:)
  real(r8), allocatable :: TCSNCs1(:)
  real(r8), allocatable :: TZSNCs1(:)
  real(r8), allocatable :: TPSNCs1(:)
  real(r8), allocatable :: TCO2Ts1(:)
  real(r8), allocatable :: TCUPTKs1(:)
  real(r8), allocatable :: THVSTCs1(:)
  real(r8), allocatable :: TNH3Cs1(:)
  real(r8), allocatable :: TZUPTKs1(:)
  real(r8), allocatable :: THVSTNs1(:)
  real(r8), allocatable :: TZUPFXs1(:)
  real(r8), allocatable :: TPUPTKs1(:)
  real(r8), allocatable :: THVSTPs1(:)
  real(r8), allocatable :: UPOMCs1(:)
  real(r8), allocatable :: UPNFs1(:)
  real(r8), allocatable :: UPNO3s1(:)
  real(r8), allocatable :: UPNH4s1(:)
  real(r8), allocatable :: UPOMNs1(:)
  real(r8), allocatable :: UPH1Ps1(:)
  real(r8), allocatable :: UPH2Ps1(:)
  real(r8), allocatable :: UPOMPs1(:)
  real(r8), allocatable :: VOLWCs1(:)
  real(r8), allocatable :: VHCPCs1(:)
  real(r8), allocatable :: VCH4Fs1(:)
  real(r8), allocatable :: VCO2Fs1(:)
  real(r8), allocatable :: VN2OFs1(:)
  real(r8), allocatable :: VNH3Fs1(:)
  real(r8), allocatable :: VPO4Fs1(:)
  real(r8), allocatable :: VOLWPs1(:)
  real(r8), allocatable :: WSTRs1(:)
  real(r8), allocatable :: WTRVXs1(:)
  real(r8), allocatable :: WTRVCs1(:)
  real(r8), allocatable :: WTLSs1(:)
  real(r8), allocatable :: WTSHTs1(:)
  real(r8), allocatable :: WTSHTAs1(:)
  real(r8), allocatable :: WTSTGs1(:)
  real(r8), allocatable :: WTSTGNs1(:)
  real(r8), allocatable :: WTSTGPs1(:)
  real(r8), allocatable :: WTNDs1(:)
  real(r8), allocatable :: WTRTts1(:)
  real(r8), allocatable :: WTNDNs1(:)
  real(r8), allocatable :: WTRTNs1(:)
  real(r8), allocatable :: WTSHNs1(:)
  real(r8), allocatable :: WTRVNs1(:)
  real(r8), allocatable :: WTNDPs1(:)
  real(r8), allocatable :: WTRTPs1(:)
  real(r8), allocatable :: WTSHPs1(:)
  real(r8), allocatable :: WTRVPs1(:)
  real(r8), allocatable :: XKCO24s1(:)
  real(r8), allocatable :: XTLIs1(:)
  real(r8), allocatable :: XRNIs1(:)
  real(r8), allocatable :: XRLAs1(:)
  real(r8), allocatable :: XDLs1(:)
  real(r8), allocatable :: XPPDs1(:)
  real(r8), allocatable :: ZPOOLPs1(:)
  real(r8), allocatable :: ZPOLNPs1(:)
  real(r8), allocatable :: ZEROLs1(:)
  real(r8), allocatable :: ZEROPs1(:)
  real(r8), allocatable :: O2Is1(:)
  real(r8), allocatable :: ZEROQs1(:)
  real(r8), allocatable :: ZCs1(:)
  real(r8), allocatable :: ZNPPs1(:)
  real(r8), allocatable :: CLASSs1(:,:)
  real(r8), allocatable :: ATRPs1(:,:)
  real(r8), allocatable :: ARLFZs1(:,:)
  real(r8), allocatable :: ARLFBs1(:,:)
  real(r8), allocatable :: CPOOLs1(:,:)
  real(r8), allocatable :: CPOLNBs1(:,:)
  real(r8), allocatable :: CCPOLBs1(:,:)
  real(r8), allocatable :: CZPOLBs1(:,:)
  real(r8), allocatable :: CPPOLBs1(:,:)
  real(r8), allocatable :: DGSTGIs1(:,:)
  real(r8), allocatable :: DGSTGFs1(:,:)
  real(r8), allocatable :: FLG4s1(:,:)
  real(r8), allocatable :: FDBKs1(:,:)
  real(r8), allocatable :: FDBKXs1(:,:)
  real(r8), allocatable :: FLGZs1(:,:)
  real(r8), allocatable :: GROUPs1(:,:)
  real(r8), allocatable :: GSTGIs1(:,:)
  real(r8), allocatable :: GSTGFs1(:,:)
  real(r8), allocatable :: GRNXBs1(:,:)
  real(r8), allocatable :: GRNOBs1(:,:)
  real(r8), allocatable :: GRWTBs1(:,:)
  real(r8), allocatable :: HTSHEXs1(:,:)
  integer,  allocatable :: IDTHBs1(:,:)
  integer,  allocatable :: IFLGPs1(:,:)
  integer,  allocatable :: IFLGFs1(:,:)
  integer,  allocatable :: IFLGEs1(:,:)
  integer,  allocatable :: IFLGAs1(:,:)
  integer,  allocatable :: IFLGGs1(:,:)
  integer,  allocatable :: IFLGRs1(:,:)
  integer,  allocatable :: IFLGQs1(:,:)
  integer,  allocatable :: KVSTGs1(:,:)
  integer,  allocatable :: KLEAFs1(:,:)
  integer,  allocatable :: KVSTGNs1(:,:)
  integer,  allocatable :: KLEAFXs1(:,:)
  integer,  allocatable :: NBTBs1(:,:)
  integer,  allocatable :: IDAYs1(:,:,:)
  integer,  allocatable :: IDAYYs1(:)
  integer,  allocatable :: NINRs1(:,:)
  real(r8), allocatable :: PSTGs1(:,:)
  real(r8), allocatable :: PSTGIs1(:,:)
  real(r8), allocatable :: PSTGFs1(:,:)
  real(r8), allocatable :: PPOOLs1(:,:)
  real(r8), allocatable :: PPOLNBs1(:,:)
  real(r8), allocatable :: RCCLXs1(:,:)
  real(r8), allocatable :: RCZLXs1(:,:)
  real(r8), allocatable :: RCPLXs1(:,:)
  real(r8), allocatable :: RCCSXs1(:,:)
  real(r8), allocatable :: RCZSXs1(:,:)
  real(r8), allocatable :: RCPSXs1(:,:)
  real(r8), allocatable :: RNH3Bs1(:,:)
  real(r8), allocatable :: TGSTGIs1(:,:)
  real(r8), allocatable :: TGSTGFs1(:,:)
  real(r8), allocatable :: VSTGXs1(:,:)
  real(r8), allocatable :: VSTGs1(:,:)
  real(r8), allocatable :: VRNYs1(:,:)
  real(r8), allocatable :: VRNZs1(:,:)
  real(r8), allocatable :: VRNSs1(:,:)
  real(r8), allocatable :: VRNLs1(:,:)
  real(r8), allocatable :: VRNFs1(:,:)
  real(r8), allocatable :: VRNXs1(:,:)
  real(r8), allocatable :: WTLSBs1(:,:)
  real(r8), allocatable :: WTRSVBs1(:,:)
  real(r8), allocatable :: WTLFBs1(:,:)
  real(r8), allocatable :: WTNDBs1(:,:)
  real(r8), allocatable :: WTSHEBs1(:,:)
  real(r8), allocatable :: WTEARBs1(:,:)
  real(r8), allocatable :: WTHSKBs1(:,:)
  real(r8), allocatable :: WTRSBNs1(:,:)
  real(r8), allocatable :: WTLFBNs1(:,:)
  real(r8), allocatable :: WTNDBNs1(:,:)
  real(r8), allocatable :: WTSHBNs1(:,:)
  real(r8), allocatable :: WTEABNs1(:,:)
  real(r8), allocatable :: WTHSBNs1(:,:)
  real(r8), allocatable :: WTRSBPs1(:,:)
  real(r8), allocatable :: WTLFBPs1(:,:)
  real(r8), allocatable :: WTNDBPs1(:,:)
  real(r8), allocatable :: WTSHBPs1(:,:)
  real(r8), allocatable :: WTEABPs1(:,:)
  real(r8), allocatable :: WTHSBPs1(:,:)
  real(r8), allocatable :: WTGRBs1(:,:)
  real(r8), allocatable :: WTGRBNs1(:,:)
  real(r8), allocatable :: WTGRBPs1(:,:)
  real(r8), allocatable :: WTSTKBs1(:,:)
  real(r8), allocatable :: WTSTBNs1(:,:)
  real(r8), allocatable :: WTSTBPs1(:,:)
  real(r8), allocatable :: WTSHTBs1(:,:)
  real(r8), allocatable :: WTSHTNs1(:,:)
  real(r8), allocatable :: WTSHTPs1(:,:)
  real(r8), allocatable :: WGLFXs1(:,:)
  real(r8), allocatable :: WGLFNXs1(:,:)
  real(r8), allocatable :: WGLFPXs1(:,:)
  real(r8), allocatable :: WGSHEXs1(:,:)
  real(r8), allocatable :: WGSHNXs1(:,:)
  real(r8), allocatable :: WGSHPXs1(:,:)
  real(r8), allocatable :: WTSTXBs1(:,:)
  real(r8), allocatable :: WTSTXNs1(:,:)
  real(r8), allocatable :: WTSTXPs1(:,:)
  real(r8), allocatable :: WVSTKBs1(:,:)
  real(r8), allocatable :: ZPOOLs1(:,:)
  real(r8), allocatable :: ZPOLNBs1(:,:)
  real(r8), allocatable :: SURFs1(:,:,:,:,:)
  real(r8), allocatable :: SURFXs1(:,:,:,:,:)
  real(r8), allocatable :: CPOOL3s1(:,:,:)
  real(r8), allocatable :: CPOOL4s1(:,:,:)
  real(r8), allocatable :: CO2Bs1(:,:,:)
  real(r8), allocatable :: COMPLs1(:,:,:)
  real(r8), allocatable :: CBXNs1(:,:,:)
  real(r8), allocatable :: OMEGAs1(:,:,:)
  integer,  allocatable :: IALBYs1(:,:,:)
  real(r8), allocatable :: OMEGXs1(:,:,:)
  real(r8), allocatable :: CBXN4s1(:,:,:)
  real(r8), allocatable :: ETGROs1(:,:,:)
  real(r8), allocatable :: ETGR4s1(:,:,:)
  real(r8), allocatable :: FDBK4s1(:,:,:)
  real(r8), allocatable :: HCOBs1(:,:,:)
  real(r8), allocatable :: VCGROs1(:,:,:)
  real(r8), allocatable :: VGROs1(:,:,:)
  real(r8), allocatable :: VCGR4s1(:,:,:)
  real(r8), allocatable :: VGRO4s1(:,:,:)
  real(r8), allocatable :: ARLF1s1(:,:,:)
  real(r8), allocatable :: HTNODXs1(:,:,:)
  real(r8), allocatable :: HTSHEs1(:,:,:)
  real(r8), allocatable :: HTNODEs1(:,:,:)
  real(r8), allocatable :: WGNODEs1(:,:,:)
  real(r8), allocatable :: WGNODNs1(:,:,:)
  real(r8), allocatable :: WGNODPs1(:,:,:)
  real(r8), allocatable :: WGLFs1(:,:,:)
  real(r8), allocatable :: WGLFNs1(:,:,:)
  real(r8), allocatable :: WGLFPs1(:,:,:)
  real(r8), allocatable :: WSLFs1(:,:,:)
  real(r8), allocatable :: WGSHEs1(:,:,:)
  real(r8), allocatable :: WGSHNs1(:,:,:)
  real(r8), allocatable :: WGSHPs1(:,:,:)
  real(r8), allocatable :: WSSHEs1(:,:,:)
  real(r8), allocatable :: SURFBs1(:,:,:,:)
  real(r8), allocatable :: ARLFLs1(:,:,:,:)
  real(r8), allocatable :: WGLFLs1(:,:,:,:)
  real(r8), allocatable :: WGLFLNs1(:,:,:,:)
  real(r8), allocatable :: WGLFLPs1(:,:,:,:)
  real(r8), allocatable :: ARSTKs1(:,:,:)
  real(r8), allocatable :: CPOOLRs1(:,:,:)
  real(r8), allocatable :: CCPOLRs1(:,:,:)
  real(r8), allocatable :: CZPOLRs1(:,:,:)
  real(r8), allocatable :: CPPOLRs1(:,:,:)
  real(r8), allocatable :: CO2Ps1(:,:,:)
  real(r8), allocatable :: CO2As1(:,:,:)
  real(r8), allocatable :: CH4Ps1(:,:,:)
  real(r8), allocatable :: CH4As1(:,:,:)
  real(r8), allocatable :: CWSRTLs1(:,:,:)
  real(r8), allocatable :: H2GPs1(:,:,:)
  real(r8), allocatable :: H2GAs1(:,:,:)
  real(r8), allocatable :: OXYPs1(:,:,:)
  real(r8), allocatable :: OXYAs1(:,:,:)
  real(r8), allocatable :: PSIRTs1(:,:,:)
  real(r8), allocatable :: PSIROs1(:,:,:)
  real(r8), allocatable :: PSIRGs1(:,:,:)
  real(r8), allocatable :: PPOOLRs1(:,:,:)
  real(r8), allocatable :: RUPNHBs1(:,:,:)
  real(r8), allocatable :: RUPNH4s1(:,:,:)
  real(r8), allocatable :: RUPH2Ps1(:,:,:)
  real(r8), allocatable :: RUPNOBs1(:,:,:)
  real(r8), allocatable :: RUPNO3s1(:,:,:)
  real(r8), allocatable :: RUPH1Bs1(:,:,:)
  real(r8), allocatable :: RUPH1Ps1(:,:,:)
  real(r8), allocatable :: RUPH2Bs1(:,:,:)
  real(r8), allocatable :: RUONHBs1(:,:,:)
  real(r8), allocatable :: RUONH4s1(:,:,:)
  real(r8), allocatable :: RUOH2Ps1(:,:,:)
  real(r8), allocatable :: RUONOBs1(:,:,:)
  real(r8), allocatable :: RUONO3s1(:,:,:)
  real(r8), allocatable :: RUOH1Bs1(:,:,:)
  real(r8), allocatable :: RUOH1Ps1(:,:,:)
  real(r8), allocatable :: RUOH2Bs1(:,:,:)
  real(r8), allocatable :: RUCNHBs1(:,:,:)
  real(r8), allocatable :: RUCNH4s1(:,:,:)
  real(r8), allocatable :: RUCH2Ps1(:,:,:)
  real(r8), allocatable :: RUCNOBs1(:,:,:)
  real(r8), allocatable :: RUCNO3s1(:,:,:)
  real(r8), allocatable :: RUCH1Bs1(:,:,:)
  real(r8), allocatable :: RUCH1Ps1(:,:,:)
  real(r8), allocatable :: RUCH2Bs1(:,:,:)
  real(r8), allocatable :: RCO2Ms1(:,:,:)
  real(r8), allocatable :: RCO2Ns1(:,:,:)
  real(r8), allocatable :: RCO2As1(:,:,:)
  real(r8), allocatable :: RTN1s1(:,:,:)
  real(r8), allocatable :: RTNLs1(:,:,:)
  real(r8), allocatable :: RTLGPs1(:,:,:)
  real(r8), allocatable :: RTDNPs1(:,:,:)
  real(r8), allocatable :: RTVLPs1(:,:,:)
  real(r8), allocatable :: RTVLWs1(:,:,:)
  real(r8), allocatable :: RRAD1s1(:,:,:)
  real(r8), allocatable :: RRAD2s1(:,:,:)
  real(r8), allocatable :: RTARPs1(:,:,:)
  real(r8), allocatable :: RTLGAs1(:,:,:)
  real(r8), allocatable :: RCO2Ps1(:,:,:)
  real(r8), allocatable :: RUPOXPs1(:,:,:)
  real(r8), allocatable :: RCO2Ss1(:,:,:)
  real(r8), allocatable :: RUPOXSs1(:,:,:)
  real(r8), allocatable :: RUPCHSs1(:,:,:)
  real(r8), allocatable :: RUPN2Ss1(:,:,:)
  real(r8), allocatable :: RUPN3Ss1(:,:,:)
  real(r8), allocatable :: RUPN3Bs1(:,:,:)
  real(r8), allocatable :: RUPHGSs1(:,:,:)
  real(r8), allocatable :: RCOFLAs1(:,:,:)
  real(r8), allocatable :: ROXFLAs1(:,:,:)
  real(r8), allocatable :: RCHFLAs1(:,:,:)
  real(r8), allocatable :: RN2FLAs1(:,:,:)
  real(r8), allocatable :: RNHFLAs1(:,:,:)
  real(r8), allocatable :: RHGFLAs1(:,:,:)
  real(r8), allocatable :: RCODFAs1(:,:,:)
  real(r8), allocatable :: ROXDFAs1(:,:,:)
  real(r8), allocatable :: RCHDFAs1(:,:,:)
  real(r8), allocatable :: RN2DFAs1(:,:,:)
  real(r8), allocatable :: RNHDFAs1(:,:,:)
  real(r8), allocatable :: RHGDFAs1(:,:,:)
  real(r8), allocatable :: ROXYPs1(:,:,:)
  real(r8), allocatable :: RUNNHPs1(:,:,:)
  real(r8), allocatable :: RUNNBPs1(:,:,:)
  real(r8), allocatable :: RUNNOPs1(:,:,:)
  real(r8), allocatable :: RUNNXPs1(:,:,:)
  real(r8), allocatable :: RUPP2Ps1(:,:,:)
  real(r8), allocatable :: RUPP2Bs1(:,:,:)
  real(r8), allocatable :: RUPP1Ps1(:,:,:)
  real(r8), allocatable :: RUPP1Bs1(:,:,:)
  real(r8), allocatable :: UPWTRs1(:,:,:)
  real(r8), allocatable :: WFRs1(:,:,:)
  real(r8), allocatable :: WTRTLs1(:,:,:)
  real(r8), allocatable :: WTRTDs1(:,:,:)
  real(r8), allocatable :: WSRTLs1(:,:,:)
  real(r8), allocatable :: ZPOOLRs1(:,:,:)
  real(r8), allocatable :: Z2OPs1(:,:,:)
  real(r8), allocatable :: Z2OAs1(:,:,:)
  real(r8), allocatable :: ZH3Ps1(:,:,:)
  real(r8), allocatable :: ZH3As1(:,:,:)
  real(r8), allocatable :: CPOOLNs1(:,:)
  real(r8), allocatable :: PPOOLNs1(:,:)
  real(r8), allocatable :: TFN4s1(:,:)
  real(r8), allocatable :: WTNDLNs1(:,:)
  real(r8), allocatable :: WTNDLs1(:,:)
  real(r8), allocatable :: WTNDLPs1(:,:)
  real(r8), allocatable :: ZPOOLNs1(:,:)
  real(r8), allocatable :: ARSTVs1(:,:)
  real(r8), allocatable :: ARLFVs1(:,:)
  real(r8), allocatable :: WGLFVs1(:,:)
  real(r8), allocatable :: DMVLs1(:,:)
  real(r8), allocatable :: PORTs1(:,:)
  real(r8), allocatable :: PORTXs1(:,:)
  real(r8), allocatable :: RTAR2Xs1(:,:)
  real(r8), allocatable :: RTAR1Xs1(:,:)
  real(r8), allocatable :: RRAD1Xs1(:,:)
  real(r8), allocatable :: RRAD2Xs1(:,:)
  real(r8), allocatable :: GRDMs1(:)
  real(r8), allocatable :: VOXYFs1(:)
  real(r8), allocatable :: WTGRNNs1(:)
  real(r8), allocatable :: WTSHEPs1(:)
  real(r8), allocatable :: WVSTKs1(:)
  real(r8), allocatable :: CNLFs1(:)
  real(r8), allocatable :: WTLFPs1(:)
  real(r8), allocatable :: PTSHTs1(:)
  real(r8), allocatable :: WTLFs1(:)
  real(r8), allocatable :: EPs1(:)
  real(r8), allocatable :: WDLFs1(:)
  real(r8), allocatable :: GRMXs1(:)
  real(r8), allocatable :: GFILLs1(:)
  integer, allocatable :: IRTYPs1(:)
  real(r8), allocatable :: STMXs1(:)
  real(r8), allocatable :: SDMXs1(:)
  real(r8), allocatable :: DMLFs1(:)
  real(r8), allocatable :: ZSINs1(:)
  real(r8), allocatable :: RADPs1(:)
  real(r8), allocatable :: FRADPs1(:)
  real(r8), allocatable :: WTSHEs1(:)
  real(r8), allocatable :: CNGRs1(:)
  real(r8), allocatable :: WTSTKs1(:)
  real(r8), allocatable :: CPLFs1(:)
  real(r8), allocatable :: CPSHEs1(:)
  real(r8), allocatable :: CNSHEs1(:)
  real(r8), allocatable :: WTRSVs1(:)
  real(r8), allocatable :: WTEARNs1(:)
  real(r8), allocatable :: WTLFNs1(:)
  real(r8), allocatable :: WTRSVNs1(:)
  real(r8), allocatable :: WTSHENs1(:)
  real(r8), allocatable :: WTHSKNs1(:)
  real(r8), allocatable :: WTHSKs1(:)
  real(r8), allocatable :: WTRTAs1(:)
  real(r8), allocatable :: WTGRs1(:)
  real(r8), allocatable :: WTEARs1(:)
  real(r8), allocatable :: RNH3Cs1(:)
  real(r8), allocatable :: WTSTKPs1(:)
  real(r8), allocatable :: WTRSVPs1(:)
  real(r8), allocatable :: WTEARPs1(:)
  real(r8), allocatable :: WTHSKPs1(:)
  real(r8), allocatable :: WTSTKNs1(:)
  real(r8), allocatable :: WTGRNPs1(:)
  real(r8), allocatable :: RTLG1Xs1(:,:)
  real(r8), allocatable :: RRADPs1(:,:)
  real(r8), allocatable :: RTLG2Xs1(:,:)
  real(r8), allocatable :: RSRRs1(:,:)
  real(r8), allocatable :: RSRAs1(:,:)
  real(r8), allocatable :: RRAD1Ms1(:,:)
  real(r8), allocatable :: RRAD2Ms1(:,:)
  real(r8), allocatable :: UPMNPOs1(:,:)
  real(r8), allocatable :: UPMXPOs1(:,:)
  real(r8), allocatable :: UPKMPOs1(:,:)
  real(r8), allocatable :: UPMNZOs1(:,:)
  real(r8), allocatable :: UPMXZOs1(:,:)
  real(r8), allocatable :: UPKMZOs1(:,:)
  real(r8), allocatable :: UPMNZHs1(:,:)
  real(r8), allocatable :: UPMXZHs1(:,:)
  real(r8), allocatable :: UPKMZHs1(:,:)
  real(r8), allocatable :: RTLG1s1(:,:,:,:)
  real(r8), allocatable :: RTLG2s1(:,:,:,:)
  real(r8), allocatable :: RTN2s1(:,:,:,:)
  real(r8), allocatable :: WTRT2s1(:,:,:,:)
  real(r8), allocatable :: WTRT1s1(:,:,:,:)
  real(r8), allocatable :: WTRT2Ns1(:,:,:,:)
  real(r8), allocatable :: WTRT1Ns1(:,:,:,:)
  real(r8), allocatable :: WTRT2Ps1(:,:,:,:)
  real(r8), allocatable :: WTRT1Ps1(:,:,:,:)
  real(r8), allocatable :: RTDP1s1(:,:,:)
  real(r8), allocatable :: RTWT1s1(:,:,:)
  real(r8), allocatable :: RTWT1Ns1(:,:,:)
  real(r8), allocatable :: RTWT1Ps1(:,:,:)
  real(r8), allocatable :: WTSTDGs1(:,:)
  real(r8), allocatable :: WTSTDNs1(:,:)
  real(r8), allocatable :: WTSTDPs1(:,:)
  real(r8), allocatable :: CSNCs1(:,:,:,:)
  real(r8), allocatable :: PSNCs1(:,:,:,:)
  real(r8), allocatable :: ZSNCs1(:,:,:,:)
  real(r8), allocatable :: CFOPCs1(:,:,:)
  real(r8), allocatable :: CFOPNs1(:,:,:)
  real(r8), allocatable :: CFOPPs1(:,:,:)
  real(r8), allocatable :: PARs1(:,:,:,:)
  real(r8), allocatable :: PARDIFs1(:,:,:,:)
  real(r8), allocatable :: VOLWMs1(:,:)
  real(r8), allocatable :: VOLPMs1(:,:)
  real(r8), allocatable :: TORTs1(:,:)
  real(r8), allocatable :: FILMs1(:,:)
  real(r8), allocatable :: ROXSKs1(:,:)
  real(r8), allocatable :: THETPMs1(:,:)
  real(r8), allocatable :: DFGSs1(:,:)


  contains
  subroutine InitPlantAPIData(JZ,JC,JP,JSA,jcplx1,JLI,JLA,JNODS)

  implicit none
  integer, intent(in) :: JZ,JC,JP,JSA,JCplx1,JLI,JNODS,JLA

  JZ1=JZ
  JC1=JC
  JP1=JP
  JLA1=JLA
  JSA1=JSA
  jcplx11=jcplx1
  JLI1=JLI
  JNODS1=JNODS
  call InitAllocate()
  end subroutine InitPlantAPIData
!----------------------------------------------------------------------
  subroutine InitAllocate()
  implicit none
  allocate(IDTHs1(JP1))
  allocate(FCO2s1(JP1))
  allocate(ZCOSs1(JLI1))
  allocate(XKO2s1(JP1))
  allocate(WTRTs1(JP1))
  allocate(IDTHPs1(JP1))
  allocate(IYR0s1(JP1))
  allocate(INTYPs1(JP1))
  allocate(IYRXs1(JP1))
  allocate(IYRYs1(JP1))
  allocate(IDAYXs1(JP1))
  allocate(IFLGCs1(JP1))
  allocate(IDAY0s1(JP1))
  allocate(IDAYHs1(JP1))
  allocate(IYRHs1(JP1))
  allocate(IHVSTs1(JP1))
  allocate(IWTYPs1(JP1))
  allocate(JHVSTs1(JP1))
  allocate(NB1s1(JP1))
  allocate(IDTYPs1(JP1))
  allocate(ISTYPs1(JP1))
  allocate(IDTHRs1(JP1))
  allocate(IBTYPs1(JP1))
  allocate(NBTs1(JP1))
  allocate(MYs1(JP1))
  allocate(NBRs1(JP1))
  allocate(NIXs1(JP1))
  allocate(NGs1(JP1))
  allocate(NIs1(JP1))
  allocate(IPTYPs1(JP1))
  allocate(IDATAs1(60))
  allocate(IFLGIs1(JP1))
  allocate(ICTYPs1(JP1))
  allocate(IGTYPs1(JP1))
  allocate(ARLFSs1(JP1))
  allocate(RCSs1(JP1))
  allocate(FERTs1(1:20))
  allocate(WGLFTs1(JC1))
  allocate(ARLFTs1(JC1))
  allocate(ARSTTs1(JC1))
  allocate(TAUSs1(JC1+1))
  allocate(TAU0s1(JC1+1))
  allocate(DLYR3s1(0:JZ1))
  allocate(CPO4Ss1(JZ1))
  allocate(SNL1s1(JP1))
  allocate(CPEARs1(JP1))
  allocate(CPRSVs1(JP1))
  allocate(CNRSVs1(JP1))
  allocate(CPHSKs1(JP1))
  allocate(DMSHEs1(JP1))
  allocate(ABSRs1(JP1))
  allocate(ABSPs1(JP1))
  allocate(DMHSKs1(JP1))
  allocate(DMSTKs1(JP1))
  allocate(DMRSVs1(JP1))
  allocate(DMEARs1(JP1))
  allocate(ALBRs1(JP1))
  allocate(ALBPs1(JP1))
  allocate(OMEGAGs1(JSA1))
  allocate(DMGRs1(JP1))
  allocate(CNHSKs1(JP1))
  allocate(CNEARs1(JP1))
  allocate(ANGSHs1(JP1))
  allocate(SSL1s1(JP1))
  allocate(SLA1s1(JP1))
  allocate(ANGBRs1(JP1))
  allocate(CNDUs1(JZ1))
  allocate(CGSGLs1(JZ1))
  allocate(CHSGLs1(JZ1))
  allocate(HGSGLs1(JZ1))
  allocate(OGSGLs1(JZ1))
  allocate(RSCSs1(JZ1))
  allocate(Z2SGLs1(JZ1))
  allocate(ZHSGLs1(JZ1))
  allocate(BKDSs1(0:JZ1))
  allocate(CH2P4s1(0:JZ1))
  allocate(CH1P4Bs1(0:JZ1))
  allocate(CH2P4Bs1(0:JZ1))
  allocate(CNO3Ss1(0:JZ1))
  allocate(CH1P4s1(0:JZ1))
  allocate(CNO3Bs1(0:JZ1))
  allocate(CNH4Ss1(0:JZ1))
  allocate(CNH4Bs1(0:JZ1))
  allocate(CO2Gs1(0:JZ1))
  allocate(CO2Ss1(0:JZ1))
  allocate(CH4Ss1(0:JZ1))
  allocate(CCH4Ss1(0:JZ1))
  allocate(CZ2OSs1(0:JZ1))
  allocate(CNH3Ss1(0:JZ1))
  allocate(CNH3Bs1(0:JZ1))
  allocate(CH2GSs1(0:JZ1))
  allocate(CLSGLs1(0:JZ1))
  allocate(CQSGLs1(0:JZ1))
  allocate(CCH4Gs1(0:JZ1))
  allocate(CZ2OGs1(0:JZ1))
  allocate(CNH3Gs1(0:JZ1))
  allocate(CH2GGs1(0:JZ1))
  allocate(CORGCs1(0:JZ1))
  allocate(CDPTHZs1(0:JZ1))
  allocate(DPTHZs1(0:JZ1))
  allocate(FMPRs1(0:JZ1))
  allocate(FVRNs1(0:5))
  allocate(FWOODs1(0:1))
  allocate(FWODLPs1(0:1))
  allocate(FWODLNs1(0:1))
  allocate(FWODRs1(0:1))
  allocate(FWODSPs1(0:1))
  allocate(FWODBs1(0:1))
  allocate(FWODSNs1(0:1))
  allocate(FWODRNs1(0:1))
  allocate(FWODRPs1(0:1))
  allocate(FWOODNs1(0:1))
  allocate(FWOODPs1(0:1))
  allocate(H1PO4s1(0:JZ1))
  allocate(H2PO4s1(0:JZ1))
  allocate(H1POBs1(0:JZ1))
  allocate(H2POBs1(0:JZ1))
  allocate(H2GSs1(0:JZ1))
  allocate(HLSGLs1(0:JZ1))
  allocate(OXYGs1(0:JZ1))
  allocate(OXYSs1(0:JZ1))
  allocate(OLSGLs1(0:JZ1))
  allocate(POSGLs1(0:JZ1))
  allocate(PSISTs1(0:JZ1))
  allocate(RPO4Ys1(0:JZ1))
  allocate(RPOBYs1(0:JZ1))
  allocate(RP14Ys1(0:JZ1))
  allocate(RP1BYs1(0:JZ1))
  allocate(RNO3Ys1(0:JZ1))
  allocate(RNH4Ys1(0:JZ1))
  allocate(RNHBYs1(0:JZ1))
  allocate(RN3BYs1(0:JZ1))
  allocate(ROXYFs1(0:JZ1))
  allocate(RCO2Fs1(0:JZ1))
  allocate(ROXYLs1(0:JZ1))
  allocate(ROXYYs1(0:JZ1))
  allocate(SCO2Ls1(0:JZ1))
  allocate(SOXYLs1(0:JZ1))
  allocate(SCH4Ls1(0:JZ1))
  allocate(SN2OLs1(0:JZ1))
  allocate(SNH3Ls1(0:JZ1))
  allocate(SH2GLs1(0:JZ1))
  allocate(THETWs1(0:JZ1))
  allocate(THETYs1(0:JZ1))
  allocate(TKSs1(0:JZ1))
  allocate(TFNDs1(0:JZ1))
  allocate(VOLXs1(0:JZ1))
  allocate(VLPOBs1(0:JZ1))
  allocate(VLNO3s1(0:JZ1))
  allocate(VLPO4s1(0:JZ1))
  allocate(VOLYs1(0:JZ1))
  allocate(VOLIs1(0:JZ1))
  allocate(VOLWs1(0:JZ1))
  allocate(VOLAs1(0:JZ1))
  allocate(VLNOBs1(0:JZ1))
  allocate(VLNH4s1(0:JZ1))
  allocate(VLNHBs1(0:JZ1))
  allocate(ZOSGLs1(0:JZ1))
  allocate(ZLs1(0:JC1))
  allocate(AREA3s1(0:JZ1))
  allocate(ZNO3Ss1(0:JZ1))
  allocate(ZNO3Bs1(0:JZ1))
  allocate(ZNSGLs1(0:JZ1))
  allocate(ZNH4Ss1(0:JZ1))
  allocate(ZNH4Bs1(0:JZ1))
  allocate(Z2OSs1(0:JZ1))
  allocate(ZNH3Ss1(0:JZ1))
  allocate(ZNH3Bs1(0:JZ1))
  allocate(ZVSGLs1(0:JZ1))
  allocate(RP1BXs1(0:JZ1))
  allocate(RNO3Xs1(0:JZ1))
  allocate(RPO4Xs1(0:JZ1))
  allocate(RNH4Xs1(0:JZ1))
  allocate(ROXYXs1(0:JZ1))
  allocate(RPOBXs1(0:JZ1))
  allocate(RN3BXs1(0:JZ1))
  allocate(RNHBXs1(0:JZ1))
  allocate(RP14Xs1(0:JZ1))
  allocate(TUPN3Bs1(JZ1))
  allocate(TUPH1Bs1(JZ1))
  allocate(TUPN3Ss1(JZ1))
  allocate(TUPHGSs1(JZ1))
  allocate(TUPOXPs1(JZ1))
  allocate(TNHFLAs1(JZ1))
  allocate(TCOFLAs1(JZ1))
  allocate(TN2FLAs1(JZ1))
  allocate(TOXFLAs1(JZ1))
  allocate(TCHFLAs1(JZ1))
  allocate(TLCH4Ps1(JZ1))
  allocate(TLOXYPs1(JZ1))
  allocate(TLNH3Ps1(JZ1))
  allocate(TLCO2Ps1(JZ1))
  allocate(TLN2OPs1(JZ1))
  allocate(TLH2GPs1(JZ1))
  allocate(THGFLAs1(JZ1))
  allocate(TUPOXSs1(JZ1))
  allocate(TCO2Ps1(JZ1))
  allocate(TUPN2Ss1(JZ1))
  allocate(TUPCHSs1(JZ1))
  allocate(TUPNH4s1(JZ1))
  allocate(TCO2Ss1(JZ1))
  allocate(TUPNO3s1(JZ1))
  allocate(TUPH2Ps1(JZ1))
  allocate(TUPH2Bs1(JZ1))
  allocate(TUPH1Ps1(JZ1))
  allocate(RTDNTs1(JZ1))
  allocate(TUPNFs1(JZ1))
  allocate(TUPNHBs1(JZ1))
  allocate(TUPNOBs1(JZ1))
  allocate(TUPHTs1(0:JZ1))
  allocate(TUPWTRs1(0:JZ1))
  allocate(TDFOMCs1(0:jcplx11,JZ1))
  allocate(TDFOMNs1(0:jcplx11,JZ1))
  allocate(TDFOMPs1(0:jcplx11,JZ1))
  allocate(CSNTs1(jcplx11,0:1,0:JZ1))
  allocate(ZSNTs1(jcplx11,0:1,0:JZ1))
  allocate(PSNTs1(jcplx11,0:1,0:JZ1))
  allocate(RDFOMCs1(2,0:jcplx11,0:JZ1,JP1))
  allocate(RDFOMNs1(2,0:jcplx11,0:JZ1,JP1))
  allocate(RDFOMPs1(2,0:jcplx11,0:JZ1,JP1))
  allocate(FOSRHs1(0:jcplx11,0:JZ1))
  allocate(OQCs1(0:jcplx11,0:JZ1))
  allocate(OQNs1(0:jcplx11,0:JZ1))
  allocate(OQPs1(0:jcplx11,0:JZ1))
  allocate(XOQCSs1(0:jcplx11,0:JZ1))
  allocate(XOQNSs1(0:jcplx11,0:JZ1))
  allocate(XOQPSs1(0:jcplx11,0:JZ1))
  allocate(FLWCs1(JP1))
  allocate(EHVSTs1(1:2,1:4,JP1))
  allocate(HVSTs1(JP1))
  allocate(THINs1(JP1))
  allocate(ARSTPs1(JP1))
  allocate(ARLFPs1(JP1))
  allocate(BALCs1(JP1))
  allocate(BALNs1(JP1))
  allocate(BALPs1(JP1))
  allocate(CO2Is1(JP1))
  allocate(PPIs1(JP1))
  allocate(PPZs1(JP1))
  allocate(CFs1(JP1))
  allocate(PPXs1(JP1))
  allocate(RSMHs1(JP1))
  allocate(SSTXs1(JP1))
  allocate(CCPOLPs1(JP1))
  allocate(CPOOLPs1(JP1))
  allocate(CPOLNPs1(JP1))
  allocate(CCPLNPs1(JP1))
  allocate(CZPOLPs1(JP1))
  allocate(CPPOLPs1(JP1))
  allocate(ZTYPs1(JP1))
  allocate(ZTYPIs1(JP1))
  allocate(CTCs1(JP1))
  allocate(CNETs1(JP1))
  allocate(CPRTSs1(JP1))
  allocate(CNRTSs1(JP1))
  allocate(CARBNs1(JP1))
  allocate(CNNDs1(JP1))
  allocate(CPNDs1(JP1))
  allocate(CNRTs1(JP1))
  allocate(RSMXs1(JP1))
  allocate(CWSRTs1(JP1))
  allocate(CFIs1(JP1))
  allocate(NRTs1(JP1))
  allocate(NNODs1(JP1))
  allocate(CPRTs1(JP1))
  allocate(CNWSs1(JP1))
  allocate(CPWSs1(JP1))
  allocate(CFXs1(JP1))
  allocate(DCO2s1(JP1))
  allocate(DATAPs1(JP1))
  allocate(DATAs1(30))
  allocate(DMNDs1(JP1))
  allocate(DMRTs1(JP1))
  allocate(FMOLs1(JP1))
  allocate(FNODs1(JP1))
  allocate(GROUPIs1(JP1))
  allocate(HTCTLs1(JP1))
  allocate(HCSNCs1(JP1))
  allocate(HZSNCs1(JP1))
  allocate(HPSNCs1(JP1))
  allocate(HVSTCs1(JP1))
  allocate(HVSTNs1(JP1))
  allocate(HVSTPs1(JP1))
  allocate(HCUPTKs1(JP1))
  allocate(HZUPTKs1(JP1))
  allocate(HPUPTKs1(JP1))
  allocate(HTSTZs1(JP1))
  allocate(OFFSTs1(JP1))
  allocate(OSTRs1(JP1))
  allocate(PPs1(JP1))
  allocate(PSILTs1(JP1))
  allocate(PBs1(JP1))
  allocate(PRs1(JP1))
  allocate(PPOOLPs1(JP1))
  allocate(PPOLNPs1(JP1))
  allocate(HTCs1(JP1))
  allocate(PSILGs1(JP1))
  allocate(RCMXs1(JP1))
  allocate(RCO2Zs1(JP1))
  allocate(ROXYZs1(JP1))
  allocate(RCH4Zs1(JP1))
  allocate(RN2OZs1(JP1))
  allocate(RNH3Zs1(JP1))
  allocate(RH2GZs1(JP1))
  allocate(RSETCs1(JP1))
  allocate(RSETNs1(JP1))
  allocate(RSETPs1(JP1))
  allocate(RTFQs1(JP1))
  allocate(RAZs1(JP1))
  allocate(SCO2s1(JP1))
  allocate(CO2Qs1(JP1))
  allocate(CO2Ls1(JP1))
  allocate(RAD1s1(JP1))
  allocate(PSILZs1(JP1))
  allocate(RSMNs1(JP1))
  allocate(ETMXs1(JP1))
  allocate(CHLs1(JP1))
  allocate(TAUPs1(JP1))
  allocate(TAURs1(JP1))
  allocate(PEPCs1(JP1))
  allocate(CHL4s1(JP1))
  allocate(RADCs1(JP1))
  allocate(VCMX4s1(JP1))
  allocate(RUBPs1(JP1))
  allocate(VCMXs1(JP1))
  allocate(VOMXs1(JP1))
  allocate(XKCO2Ls1(JP1))
  allocate(XKCO2Os1(JP1))
  allocate(WTRTSs1(JP1))
  allocate(WTRTSNs1(JP1))
  allocate(WTRTSPs1(JP1))
  allocate(TKCZs1(JP1))
  allocate(SFLXCs1(JP1))
  allocate(THRM1s1(JP1))
  allocate(SO2s1(JP1))
  allocate(RAs1(JP1))
  allocate(RCs1(JP1))
  allocate(O2Ls1(JP1))
  allocate(EVAPCs1(JP1))
  allocate(HFLXCs1(JP1))
  allocate(GRNOs1(JP1))
  allocate(EFLXCs1(JP1))
  allocate(SDPTHs1(JP1))
  allocate(SDPTHIs1(JP1))
  allocate(SDLGs1(JP1))
  allocate(SDVLs1(JP1))
  allocate(SDARs1(JP1))
  allocate(TCZs1(JP1))
  allocate(TCGs1(JP1))
  allocate(TCXs1(JP1))
  allocate(TKGs1(JP1))
  allocate(TFN3s1(JP1))
  allocate(XKCO2s1(JP1))
  allocate(TCSN0s1(JP1))
  allocate(TZSN0s1(JP1))
  allocate(TPSN0s1(JP1))
  allocate(TCSNCs1(JP1))
  allocate(TZSNCs1(JP1))
  allocate(TPSNCs1(JP1))
  allocate(TCO2Ts1(JP1))
  allocate(TCUPTKs1(JP1))
  allocate(THVSTCs1(JP1))
  allocate(TNH3Cs1(JP1))
  allocate(TZUPTKs1(JP1))
  allocate(THVSTNs1(JP1))
  allocate(TZUPFXs1(JP1))
  allocate(TPUPTKs1(JP1))
  allocate(THVSTPs1(JP1))
  allocate(UPOMCs1(JP1))
  allocate(UPNFs1(JP1))
  allocate(UPNO3s1(JP1))
  allocate(UPNH4s1(JP1))
  allocate(UPOMNs1(JP1))
  allocate(UPH1Ps1(JP1))
  allocate(UPH2Ps1(JP1))
  allocate(UPOMPs1(JP1))
  allocate(VOLWCs1(JP1))
  allocate(VHCPCs1(JP1))
  allocate(VCH4Fs1(JP1))
  allocate(VCO2Fs1(JP1))
  allocate(VN2OFs1(JP1))
  allocate(VNH3Fs1(JP1))
  allocate(VPO4Fs1(JP1))
  allocate(VOLWPs1(JP1))
  allocate(WSTRs1(JP1))
  allocate(WTRVXs1(JP1))
  allocate(WTRVCs1(JP1))
  allocate(WTLSs1(JP1))
  allocate(WTSHTs1(JP1))
  allocate(WTSHTAs1(JP1))
  allocate(WTSTGs1(JP1))
  allocate(WTSTKPs1(JP1))
  allocate(WTRTAs1(JP1))
  allocate(RNH3Cs1(JP1))
  allocate(VOXYFs1(JP1))
  allocate(WTSHEPs1(JP1))
  allocate(WTLFPs1(JP1))
  allocate(WTLFs1(JP1))
  allocate(CNGRs1(JP1))
  allocate(CPSTKs1(JP1))
  allocate(WDLFs1(JP1))
  allocate(DMLFs1(JP1))
  allocate(GFILLs1(JP1))
  allocate(STMXs1(JP1))
  allocate(SDMXs1(JP1))
  allocate(EPs1(JP1))
  allocate(IRTYPs1(JP1))
  allocate(GRMXs1(JP1))
  allocate(ZSINs1(JLI1))
  allocate(RADPs1(JP1))
  allocate(FRADPs1(JP1))
  allocate(WTSHEs1(JP1))
  allocate(WTSTKs1(JP1))
  allocate(CPLFs1(JP1))
  allocate(CPSHEs1(JP1))
  allocate(WVSTKs1(JP1))
  allocate(PTSHTs1(JP1))
  allocate(CNLFs1(JP1))
  allocate(CNSHEs1(JP1))
  allocate(WTEARNs1(JP1))
  allocate(WTRSVs1(JP1))
  allocate(WTGRs1(JP1))
  allocate(WTLFNs1(JP1))
  allocate(WTSHENs1(JP1))
  allocate(WTRSVNs1(JP1))
  allocate(WTHSKNs1(JP1))
  allocate(WTHSKs1(JP1))
  allocate(WTSTDIs1(JP1))
  allocate(TCCs1(JP1))
  allocate(ENGYXs1(JP1))
  allocate(CPGRs1(JP1))
  allocate(DTKCs1(JP1))
  allocate(TKCs1(JP1))
  allocate(OSMOs1(JP1))
  allocate(TCO2As1(JP1))
  allocate(PSILOs1(JP1))
  allocate(CNSTKs1(JP1))
  allocate(WTEARs1(JP1))
  allocate(CTRANs1(JP1))
  allocate(WTGRNNs1(JP1))
  allocate(WTRSVPs1(JP1))
  allocate(WTHSKPs1(JP1))
  allocate(WTSTKNs1(JP1))
  allocate(WTEARPs1(JP1))
  allocate(WTGRNPs1(JP1))
  allocate(CHILLs1(JP1))
  allocate(WTSTGNs1(JP1))
  allocate(GRDMs1(JP1))
  allocate(WTSTGPs1(JP1))
  allocate(WTNDs1(JP1))
  allocate(WTRTts1(JP1))
  allocate(WTNDNs1(JP1))
  allocate(WTRTNs1(JP1))
  allocate(WTSHNs1(JP1))
  allocate(WTRVNs1(JP1))
  allocate(WTNDPs1(JP1))
  allocate(WTRTPs1(JP1))
  allocate(WTSHPs1(JP1))
  allocate(WTRVPs1(JP1))
  allocate(XKCO24s1(JP1))
  allocate(XTLIs1(JP1))
  allocate(XRNIs1(JP1))
  allocate(XRLAs1(JP1))
  allocate(XDLs1(JP1))
  allocate(XPPDs1(JP1))
  allocate(ZPOOLPs1(JP1))
  allocate(ZPOLNPs1(JP1))
  allocate(ZEROLs1(JP1))
  allocate(ZEROPs1(JP1))
  allocate(O2Is1(JP1))
  allocate(ZEROQs1(JP1))
  allocate(ZCs1(JP1))
  allocate(ZNPPs1(JP1))
  allocate(CLASSs1(JLI1,JP1))
  allocate(ATRPs1(JC1,JP1))
  allocate(ARLFZs1(JC1,JP1))
  allocate(ARLFBs1(JC1,JP1))
  allocate(CPOOLs1(JC1,JP1))
  allocate(CPOLNBs1(JC1,JP1))
  allocate(CCPOLBs1(JC1,JP1))
  allocate(CZPOLBs1(JC1,JP1))
  allocate(CPPOLBs1(JC1,JP1))
  allocate(DGSTGIs1(JC1,JP1))
  allocate(DGSTGFs1(JC1,JP1))
  allocate(FLG4s1(JC1,JP1))
  allocate(FDBKs1(JC1,JP1))
  allocate(FDBKXs1(JC1,JP1))
  allocate(FLGZs1(JC1,JP1))
  allocate(GROUPs1(JC1,JP1))
  allocate(GSTGIs1(JC1,JP1))
  allocate(GSTGFs1(JC1,JP1))
  allocate(GRNXBs1(JC1,JP1))
  allocate(GRNOBs1(JC1,JP1))
  allocate(GRWTBs1(JC1,JP1))
  allocate(HTSHEXs1(JC1,JP1))
  allocate(IDTHBs1(JC1,JP1))
  allocate(IFLGPs1(JC1,JP1))
  allocate(IFLGFs1(JC1,JP1))
  allocate(IFLGEs1(JC1,JP1))
  allocate(IFLGAs1(JC1,JP1))
  allocate(IFLGGs1(JC1,JP1))
  allocate(IFLGRs1(JC1,JP1))
  allocate(IFLGQs1(JC1,JP1))
  allocate(KVSTGs1(JC1,JP1))
  allocate(KLEAFs1(JC1,JP1))
  allocate(KVSTGNs1(JC1,JP1))
  allocate(KLEAFXs1(JC1,JP1))
  allocate(NBTBs1(JC1,JP1))
  allocate(IDAYs1(10,JC1,JP1))
  allocate(IDAYYs1(JP1))
  allocate(NINRs1(JC1,JP1))
  allocate(PSTGs1(JC1,JP1))
  allocate(PSTGIs1(JC1,JP1))
  allocate(PSTGFs1(JC1,JP1))
  allocate(PPOOLs1(JC1,JP1))
  allocate(PPOLNBs1(JC1,JP1))
  allocate(RCCLXs1(JC1,JP1))
  allocate(RCZLXs1(JC1,JP1))
  allocate(RCPLXs1(JC1,JP1))
  allocate(RCCSXs1(JC1,JP1))
  allocate(RCZSXs1(JC1,JP1))
  allocate(RCPSXs1(JC1,JP1))
  allocate(RNH3Bs1(JC1,JP1))
  allocate(TGSTGIs1(JC1,JP1))
  allocate(TGSTGFs1(JC1,JP1))
  allocate(VSTGXs1(JC1,JP1))
  allocate(VSTGs1(JC1,JP1))
  allocate(VRNYs1(JC1,JP1))
  allocate(VRNZs1(JC1,JP1))
  allocate(VRNSs1(JC1,JP1))
  allocate(VRNLs1(JC1,JP1))
  allocate(VRNFs1(JC1,JP1))
  allocate(VRNXs1(JC1,JP1))
  allocate(WTLSBs1(JC1,JP1))
  allocate(WTRSVBs1(JC1,JP1))
  allocate(WTLFBs1(JC1,JP1))
  allocate(WTNDBs1(JC1,JP1))
  allocate(WTSHEBs1(JC1,JP1))
  allocate(WTEARBs1(JC1,JP1))
  allocate(WTHSKBs1(JC1,JP1))
  allocate(WTRSBNs1(JC1,JP1))
  allocate(WTLFBNs1(JC1,JP1))
  allocate(WTNDBNs1(JC1,JP1))
  allocate(WTSHBNs1(JC1,JP1))
  allocate(WTEABNs1(JC1,JP1))
  allocate(WTHSBNs1(JC1,JP1))
  allocate(WTRSBPs1(JC1,JP1))
  allocate(WTLFBPs1(JC1,JP1))
  allocate(WTNDBPs1(JC1,JP1))
  allocate(WTSHBPs1(JC1,JP1))
  allocate(WTEABPs1(JC1,JP1))
  allocate(WTHSBPs1(JC1,JP1))
  allocate(WTGRBs1(JC1,JP1))
  allocate(WTGRBNs1(JC1,JP1))
  allocate(WTGRBPs1(JC1,JP1))
  allocate(WTSTKBs1(JC1,JP1))
  allocate(WTSTBNs1(JC1,JP1))
  allocate(WTSTBPs1(JC1,JP1))
  allocate(WTSHTBs1(JC1,JP1))
  allocate(WTSHTNs1(JC1,JP1))
  allocate(WTSHTPs1(JC1,JP1))
  allocate(WGLFXs1(JC1,JP1))
  allocate(WGLFNXs1(JC1,JP1))
  allocate(WGLFPXs1(JC1,JP1))
  allocate(WGSHEXs1(JC1,JP1))
  allocate(WGSHNXs1(JC1,JP1))
  allocate(WGSHPXs1(JC1,JP1))
  allocate(WTSTXBs1(JC1,JP1))
  allocate(WTSTXNs1(JC1,JP1))
  allocate(WTSTXPs1(JC1,JP1))
  allocate(WVSTKBs1(JC1,JP1))
  allocate(ZPOOLs1(JC1,JP1))
  allocate(ZPOLNBs1(JC1,JP1))
  allocate(OMEGAs1(JSA1,JLI1,JLA1))
  allocate(IALBYs1(JSA1,JLI1,JLA1))
  allocate(OMEGXs1(JSA1,JLI1,JLA1))
  allocate(SURFs1(JLI1,JC1,JNODS1,JC1,JP1))
  allocate(SURFXs1(JLI1,JC1,JNODS1,JC1,JP1))
  allocate(CPOOL3s1(JNODS1,JC1,JP1))
  allocate(CPOOL4s1(JNODS1,JC1,JP1))
  allocate(CO2Bs1(JNODS1,JC1,JP1))
  allocate(COMPLs1(JNODS1,JC1,JP1))
  allocate(CBXNs1(JNODS1,JC1,JP1))
  allocate(CBXN4s1(JNODS1,JC1,JP1))
  allocate(ETGROs1(JNODS1,JC1,JP1))
  allocate(ETGR4s1(JNODS1,JC1,JP1))
  allocate(FDBK4s1(JNODS1,JC1,JP1))
  allocate(HCOBs1(JNODS1,JC1,JP1))
  allocate(VCGROs1(JNODS1,JC1,JP1))
  allocate(VGROs1(JNODS1,JC1,JP1))
  allocate(VCGR4s1(JNODS1,JC1,JP1))
  allocate(VGRO4s1(JNODS1,JC1,JP1))
  allocate(ARLF1s1(0:JNODS1,JC1,JP1))
  allocate(HTNODXs1(0:JNODS1,JC1,JP1))
  allocate(HTSHEs1(0:JNODS1,JC1,JP1))
  allocate(HTNODEs1(0:JNODS1,JC1,JP1))
  allocate(WGNODEs1(0:JNODS1,JC1,JP1))
  allocate(WGNODNs1(0:JNODS1,JC1,JP1))
  allocate(WGNODPs1(0:JNODS1,JC1,JP1))
  allocate(WGLFs1(0:JNODS1,JC1,JP1))
  allocate(WGLFNs1(0:JNODS1,JC1,JP1))
  allocate(WGLFPs1(0:JNODS1,JC1,JP1))
  allocate(WSLFs1(0:JNODS1,JC1,JP1))
  allocate(WGSHEs1(0:JNODS1,JC1,JP1))
  allocate(WGSHNs1(0:JNODS1,JC1,JP1))
  allocate(WGSHPs1(0:JNODS1,JC1,JP1))
  allocate(WSSHEs1(0:JNODS1,JC1,JP1))
  allocate(SURFBs1(JLI1,JC1,JC1,JP1))
  allocate(ARLFLs1(JC1,0:JNODS1,JC1,JP1))
  allocate(WGLFLs1(JC1,0:JNODS1,JC1,JP1))
  allocate(WGLFLNs1(JC1,0:JNODS1,JC1,JP1))
  allocate(WGLFLPs1(JC1,0:JNODS1,JC1,JP1))
  allocate(ARSTKs1(JC1,JC1,JP1))
  allocate(CPOOLRs1(2,JZ1,JP1))
  allocate(CCPOLRs1(2,JZ1,JP1))
  allocate(CZPOLRs1(2,JZ1,JP1))
  allocate(CPPOLRs1(2,JZ1,JP1))
  allocate(CO2Ps1(2,JZ1,JP1))
  allocate(CO2As1(2,JZ1,JP1))
  allocate(CH4Ps1(2,JZ1,JP1))
  allocate(CH4As1(2,JZ1,JP1))
  allocate(CWSRTLs1(2,JZ1,JP1))
  allocate(H2GPs1(2,JZ1,JP1))
  allocate(H2GAs1(2,JZ1,JP1))
  allocate(OXYPs1(2,JZ1,JP1))
  allocate(OXYAs1(2,JZ1,JP1))
  allocate(PSIRTs1(2,JZ1,JP1))
  allocate(PSIROs1(2,JZ1,JP1))
  allocate(PSIRGs1(2,JZ1,JP1))
  allocate(PPOOLRs1(2,JZ1,JP1))
  allocate(RUPNHBs1(2,JZ1,JP1))
  allocate(RUPNH4s1(2,JZ1,JP1))
  allocate(RUPH2Ps1(2,JZ1,JP1))
  allocate(RUPNOBs1(2,JZ1,JP1))
  allocate(RUPNO3s1(2,JZ1,JP1))
  allocate(RUPH1Bs1(2,JZ1,JP1))
  allocate(RUPH1Ps1(2,JZ1,JP1))
  allocate(RUPH2Bs1(2,JZ1,JP1))
  allocate(RUONHBs1(2,JZ1,JP1))
  allocate(RUONH4s1(2,JZ1,JP1))
  allocate(RUOH2Ps1(2,JZ1,JP1))
  allocate(RUONOBs1(2,JZ1,JP1))
  allocate(RUONO3s1(2,JZ1,JP1))
  allocate(RUOH1Bs1(2,JZ1,JP1))
  allocate(RUOH1Ps1(2,JZ1,JP1))
  allocate(RUOH2Bs1(2,JZ1,JP1))
  allocate(RUCNHBs1(2,JZ1,JP1))
  allocate(RUCNH4s1(2,JZ1,JP1))
  allocate(RUCH2Ps1(2,JZ1,JP1))
  allocate(RUCNOBs1(2,JZ1,JP1))
  allocate(RUCNO3s1(2,JZ1,JP1))
  allocate(RUCH1Bs1(2,JZ1,JP1))
  allocate(RUCH1Ps1(2,JZ1,JP1))
  allocate(RUCH2Bs1(2,JZ1,JP1))
  allocate(RCO2Ms1(2,JZ1,JP1))
  allocate(RCO2Ns1(2,JZ1,JP1))
  allocate(RCO2As1(2,JZ1,JP1))
  allocate(RTN1s1(2,JZ1,JP1))
  allocate(RTNLs1(2,JZ1,JP1))
  allocate(RTLGPs1(2,JZ1,JP1))
  allocate(RTDNPs1(2,JZ1,JP1))
  allocate(RTVLPs1(2,JZ1,JP1))
  allocate(RTVLWs1(2,JZ1,JP1))
  allocate(RRAD1s1(2,JZ1,JP1))
  allocate(RRAD2s1(2,JZ1,JP1))
  allocate(RTARPs1(2,JZ1,JP1))
  allocate(RTLGAs1(2,JZ1,JP1))
  allocate(RCO2Ps1(2,JZ1,JP1))
  allocate(RUPOXPs1(2,JZ1,JP1))
  allocate(RCO2Ss1(2,JZ1,JP1))
  allocate(RUPOXSs1(2,JZ1,JP1))
  allocate(RUPCHSs1(2,JZ1,JP1))
  allocate(RUPN2Ss1(2,JZ1,JP1))
  allocate(RUPN3Ss1(2,JZ1,JP1))
  allocate(RUPN3Bs1(2,JZ1,JP1))
  allocate(RUPHGSs1(2,JZ1,JP1))
  allocate(RCOFLAs1(2,JZ1,JP1))
  allocate(ROXFLAs1(2,JZ1,JP1))
  allocate(RCHFLAs1(2,JZ1,JP1))
  allocate(RN2FLAs1(2,JZ1,JP1))
  allocate(RNHFLAs1(2,JZ1,JP1))
  allocate(RHGFLAs1(2,JZ1,JP1))
  allocate(RCODFAs1(2,JZ1,JP1))
  allocate(ROXDFAs1(2,JZ1,JP1))
  allocate(RCHDFAs1(2,JZ1,JP1))
  allocate(RN2DFAs1(2,JZ1,JP1))
  allocate(RNHDFAs1(2,JZ1,JP1))
  allocate(RHGDFAs1(2,JZ1,JP1))
  allocate(ROXYPs1(2,JZ1,JP1))
  allocate(RUNNHPs1(2,JZ1,JP1))
  allocate(RUNNBPs1(2,JZ1,JP1))
  allocate(RUNNOPs1(2,JZ1,JP1))
  allocate(RUNNXPs1(2,JZ1,JP1))
  allocate(RUPP2Ps1(2,JZ1,JP1))
  allocate(RUPP2Bs1(2,JZ1,JP1))
  allocate(RUPP1Ps1(2,JZ1,JP1))
  allocate(RUPP1Bs1(2,JZ1,JP1))
  allocate(UPWTRs1(2,JZ1,JP1))
  allocate(WFRs1(2,JZ1,JP1))
  allocate(WTRTLs1(2,JZ1,JP1))
  allocate(WTRTDs1(2,JZ1,JP1))
  allocate(WSRTLs1(2,JZ1,JP1))
  allocate(ZPOOLRs1(2,JZ1,JP1))
  allocate(Z2OPs1(2,JZ1,JP1))
  allocate(Z2OAs1(2,JZ1,JP1))
  allocate(ZH3Ps1(2,JZ1,JP1))
  allocate(ZH3As1(2,JZ1,JP1))
  allocate(CPOOLNs1(JZ1,JP1))
  allocate(RUPNFs1(JZ1,JP1))
  allocate(PPOOLNs1(JZ1,JP1))
  allocate(TFN4s1(JZ1,JP1))
  allocate(WTNDLNs1(JZ1,JP1))
  allocate(WTNDLs1(JZ1,JP1))
  allocate(WTNDLPs1(JZ1,JP1))
  allocate(ZPOOLNs1(JZ1,JP1))
  allocate(ARSTVs1(JC1,JP1))
  allocate(ARLFVs1(JC1,JP1))
  allocate(WGLFVs1(JC1,JP1))
  allocate(DMVLs1(2,JP1))
  allocate(PORTs1(2,JP1))
  allocate(PORTXs1(2,JP1))
  allocate(RTAR2Xs1(2,JP1))
  allocate(RTAR1Xs1(2,JP1))
  allocate(RRAD1Xs1(2,JP1))
  allocate(RRAD2Xs1(2,JP1))
  allocate(RTLG1Xs1(2,JP1))
  allocate(RRADPs1(2,JP1))
  allocate(RTLG2Xs1(2,JP1))
  allocate(RSRRs1(2,JP1))
  allocate(RSRAs1(2,JP1))
  allocate(RRAD1Ms1(2,JP1))
  allocate(RRAD2Ms1(2,JP1))
  allocate(UPMNPOs1(2,JP1))
  allocate(UPMXPOs1(2,JP1))
  allocate(UPKMPOs1(2,JP1))
  allocate(UPMNZOs1(2,JP1))
  allocate(UPMXZOs1(2,JP1))
  allocate(UPKMZOs1(2,JP1))
  allocate(UPMNZHs1(2,JP1))
  allocate(UPMXZHs1(2,JP1))
  allocate(UPKMZHs1(2,JP1))
  allocate(RTLG1s1(2,JZ1,JC1,JP1))
  allocate(RTLG2s1(2,JZ1,JC1,JP1))
  allocate(RTN2s1(2,JZ1,JC1,JP1))
  allocate(WTRT2s1(2,JZ1,JC1,JP1))
  allocate(WTRT1s1(2,JZ1,JC1,JP1))
  allocate(WTRT2Ns1(2,JZ1,JC1,JP1))
  allocate(WTRT1Ns1(2,JZ1,JC1,JP1))
  allocate(WTRT2Ps1(2,JZ1,JC1,JP1))
  allocate(WTRT1Ps1(2,JZ1,JC1,JP1))
  allocate(RTDP1s1(2,JC1,JP1))
  allocate(RTWT1s1(2,JC1,JP1))
  allocate(RTWT1Ns1(2,JC1,JP1))
  allocate(RTWT1Ps1(2,JC1,JP1))
  allocate(WTSTDGs1(4,JP1))
  allocate(WTSTDNs1(4,JP1))
  allocate(WTSTDPs1(4,JP1))
  allocate(CSNCs1(4,0:1,0:JZ1,JP1))
  allocate(PSNCs1(4,0:1,0:JZ1,JP1))
  allocate(ZSNCs1(4,0:1,0:JZ1,JP1))
  allocate(CFOPCs1(0:5,4,JP1))
  allocate(CFOPNs1(0:5,4,JP1))
  allocate(CFOPPs1(0:5,4,JP1))
  allocate(PARs1(JLI1,JSA1,JC1,JP1))
  allocate(PARDIFs1(JLI1,JSA1,JC1,JP1))
  allocate(VOLWMs1(60,0:JZ1))
  allocate(VOLPMs1(60,0:JZ1))
  allocate(TORTs1(60,0:JZ1))
  allocate(FILMs1(60,0:JZ1))
  allocate(ROXSKs1(60,0:JZ1))
  allocate(THETPMs1(60,0:JZ1))
  allocate(DFGSs1(60,0:JZ1))
  end subroutine InitAllocate
!----------------------------------------------------------------------
  subroutine DestructPlantAPIData
  implicit none
  if(allocated(WTRTs1))deallocate(WTRTs1)
  if(allocated(ZCOSs1))deallocate(ZCOSs1)
  if(allocated(FCO2s1))deallocate(FCO2s1)
  if(allocated(XKO2s1))deallocate(XKO2s1)
  if(allocated(IDTHs1))deallocate(IDTHs1)
  if(allocated(IYR0s1))deallocate(IYR0s1)
  if(allocated(INTYPs1))deallocate(INTYPs1)
  if(allocated(IDAYXs1))deallocate(IDAYXs1)
  if(allocated(IYRYs1))deallocate(IYRYs1)
  if(allocated(IYRXs1))deallocate(IYRXs1)
  if(allocated(IFLGCs1))deallocate(IFLGCs1)
  if(allocated(IDAY0s1))deallocate(IDAY0s1)
  if(allocated(IDAYHs1))deallocate(IDAYHs1)
  if(allocated(IYRHs1))deallocate(IYRHs1)
  if(allocated(IHVSTs1))deallocate(IHVSTs1)
  if(allocated(IWTYPs1))deallocate(IWTYPs1)
  if(allocated(JHVSTs1))deallocate(JHVSTs1)
  if(allocated(ISTYPs1))deallocate(ISTYPs1)
  if(allocated(MYs1)) deallocate(MYs1)
  if(allocated(NBRs1)) deallocate(NBRs1)
  if(allocated(NIs1)) deallocate(NIs1)
  if(allocated(NGs1)) deallocate(NGs1)
  if(allocated(NIXs1))deallocate(NIXs1)
  if(allocated(IDTYPs1))deallocate(IDTYPs1)
  if(allocated(IPTYPs1))deallocate(IPTYPs1)
  if(allocated(IDATAs1))deallocate(IDATAs1)
  if(allocated(IGTYPs1))deallocate(IGTYPs1)
  if(allocated(IFLGIs1))deallocate(IFLGIs1)
  if(allocated(ICTYPs1))deallocate(ICTYPs1)
  if(allocated(DATAs1))deallocate(DATAs1)
  if(allocated(NB1s1)) deallocate(NB1s1)
  if(allocated(FERTs1))deallocate(FERTs1)
  if(allocated(WGLFTs1))deallocate(WGLFTs1)
  if(allocated(ARSTTs1))deallocate(ARSTTs1)
  if(allocated(ARLFTs1))deallocate(ARLFTs1)
  if(allocated(ARLFSs1))deallocate(ARLFSs1)
  if(allocated(RCSs1))deallocate(RCSs1)
  if(allocated(TAUSs1))deallocate(TAUSs1)
  if(allocated(TAU0s1))deallocate(TAU0s1)
  if(allocated(SNL1s1))deallocate(SNL1s1)
  if(allocated(CPEARs1))deallocate(CPEARs1)
  if(allocated(CPHSKs1))deallocate(CPHSKs1)
  if(allocated(DMSHEs1))deallocate(DMSHEs1)
  if(allocated(ABSRs1))deallocate(ABSRs1)
  if(allocated(ABSPs1))deallocate(ABSPs1)
  if(allocated(DMSTKs1))deallocate(DMSTKs1)
  if(allocated(DMGRs1))deallocate(DMGRs1)
  if(allocated(DMRSVs1))deallocate(DMRSVs1)
  if(allocated(CNHSKs1))deallocate(CNHSKs1)
  if(allocated(DMEARs1))deallocate(DMEARs1)
  if(allocated(ALBPs1))deallocate(ALBPs1)
  if(allocated(ALBRs1))deallocate(ALBRs1)
  if(allocated(OMEGAGs1))deallocate(OMEGAGs1)
  if(allocated(DMHSKs1))deallocate(DMHSKs1)
  if(allocated(CNEARs1))deallocate(CNEARs1)
  if(allocated(CNRSVs1))deallocate(CNRSVs1)
  if(allocated(CPRSVs1))deallocate(CPRSVs1)
  if(allocated(ANGSHs1))deallocate(ANGSHs1)
  if(allocated(SSL1s1))deallocate(SSL1s1)
  if(allocated(SLA1s1))deallocate(SLA1s1)
  if(allocated(ANGBRs1))deallocate(ANGBRs1)
  if(allocated(CPO4Ss1))deallocate(CPO4Ss1)
  if(allocated(CNDUs1))deallocate(CNDUs1)
  if(allocated(CGSGLs1))deallocate(CGSGLs1)
  if(allocated(CHSGLs1))deallocate(CHSGLs1)
  if(allocated(HGSGLs1))deallocate(HGSGLs1)
  if(allocated(OGSGLs1))deallocate(OGSGLs1)
  if(allocated(ETMXs1))deallocate(ETMXs1)
  if(allocated(VCMXs1))deallocate(VCMXs1)
  if(allocated(PEPCs1))deallocate(PEPCs1)
  if(allocated(CHLs1))deallocate(CHLs1)
  if(allocated(TAURs1))deallocate(TAURs1)
  if(allocated(TAUPs1))deallocate(TAUPs1)
  if(allocated(CHL4s1))deallocate(CHL4s1)
  if(allocated(RADCs1))deallocate(RADCs1)
  if(allocated(VCMX4s1))deallocate(VCMX4s1)
  if(allocated(RUBPs1))deallocate(RUBPs1)
  if(allocated(VOMXs1))deallocate(VOMXs1)
  if(allocated(XKCO2s1))deallocate(XKCO2s1)
  if(allocated(ZTYPs1))deallocate(ZTYPs1)
  if(allocated(ZTYPIs1))deallocate(ZTYPIs1)
  if(allocated(GRDMs1))deallocate(GRDMs1)
  if(allocated(HTCs1))deallocate(HTCs1)
  if(allocated(SSTXs1)) deallocate(SSTXs1)
  if(allocated(RSCSs1))deallocate(RSCSs1)
  if(allocated(Z2SGLs1))deallocate(Z2SGLs1)
  if(allocated(ZHSGLs1))deallocate(ZHSGLs1)
  if(allocated(BKDSs1))deallocate(BKDSs1)
  if(allocated(CH2P4s1))deallocate(CH2P4s1)
  if(allocated(CH1P4Bs1))deallocate(CH1P4Bs1)
  if(allocated(CH2P4Bs1))deallocate(CH2P4Bs1)
  if(allocated(CNO3Ss1))deallocate(CNO3Ss1)
  if(allocated(CH1P4s1))deallocate(CH1P4s1)
  if(allocated(CNO3Bs1))deallocate(CNO3Bs1)
  if(allocated(CNH4Ss1))deallocate(CNH4Ss1)
  if(allocated(CNH4Bs1))deallocate(CNH4Bs1)
  if(allocated(CO2Gs1))deallocate(CO2Gs1)
  if(allocated(CO2Ss1))deallocate(CO2Ss1)
  if(allocated(CH4Ss1))deallocate(CH4Ss1)
  if(allocated(CCH4Ss1))deallocate(CCH4Ss1)
  if(allocated(CZ2OSs1))deallocate(CZ2OSs1)
  if(allocated(CNH3Ss1))deallocate(CNH3Ss1)
  if(allocated(CNH3Bs1))deallocate(CNH3Bs1)
  if(allocated(CH2GSs1))deallocate(CH2GSs1)
  if(allocated(CLSGLs1))deallocate(CLSGLs1)
  if(allocated(CQSGLs1))deallocate(CQSGLs1)
  if(allocated(CCH4Gs1))deallocate(CCH4Gs1)
  if(allocated(CZ2OGs1))deallocate(CZ2OGs1)
  if(allocated(CNH3Gs1))deallocate(CNH3Gs1)
  if(allocated(CH2GGs1))deallocate(CH2GGs1)
  if(allocated(CORGCs1))deallocate(CORGCs1)
  if(allocated(CDPTHZs1))deallocate(CDPTHZs1)
  if(allocated(RSMHs1)) deallocate(RSMHs1)
  if(allocated(CFIs1)) deallocate(CFIs1)
  if(allocated(PPIs1)) deallocate(PPIs1)
  if(allocated(PPZs1)) deallocate(PPZs1)
  if(allocated(CFs1))  deallocate(CFs1)
  if(allocated(PPXs1)) deallocate(PPXs1)
  if(allocated(DPTHZs1))deallocate(DPTHZs1)
  if(allocated(FMPRs1))deallocate(FMPRs1)
  if(allocated(FWODLPs1))deallocate(FWODLPs1)
  if(allocated(FWODLNs1))deallocate(FWODLNs1)
  if(allocated(FWOODs1))deallocate(FWOODs1)
  if(allocated(FVRNs1))deallocate(FVRNs1)
  if(allocated(FWOODPs1))deallocate(FWOODPs1)
  if(allocated(FWOODNs1))deallocate(FWOODNs1)
  if(allocated(FWODRs1))deallocate(FWODRs1)
  if(allocated(FWODRNs1))deallocate(FWODRNs1)
  if(allocated(FWODSNs1))deallocate(FWODSNs1)
  if(allocated(FWODSPs1))deallocate(FWODSPs1)
  if(allocated(FWODBs1))deallocate(FWODBs1)
  if(allocated(FWODRPs1))deallocate(FWODRPs1)
  if(allocated(H1PO4s1))deallocate(H1PO4s1)
  if(allocated(H2PO4s1))deallocate(H2PO4s1)
  if(allocated(H1POBs1))deallocate(H1POBs1)
  if(allocated(H2POBs1))deallocate(H2POBs1)
  if(allocated(H2GSs1))deallocate(H2GSs1)
  if(allocated(HLSGLs1))deallocate(HLSGLs1)
  if(allocated(OXYGs1))deallocate(OXYGs1)
  if(allocated(OXYSs1))deallocate(OXYSs1)
  if(allocated(OLSGLs1))deallocate(OLSGLs1)
  if(allocated(POSGLs1))deallocate(POSGLs1)
  if(allocated(PSISTs1))deallocate(PSISTs1)
  if(allocated(RPO4Ys1))deallocate(RPO4Ys1)
  if(allocated(RPOBYs1))deallocate(RPOBYs1)
  if(allocated(RP14Ys1))deallocate(RP14Ys1)
  if(allocated(RP1BYs1))deallocate(RP1BYs1)
  if(allocated(RNO3Ys1))deallocate(RNO3Ys1)
  if(allocated(RNH4Ys1))deallocate(RNH4Ys1)
  if(allocated(RNHBYs1))deallocate(RNHBYs1)
  if(allocated(RN3BYs1))deallocate(RN3BYs1)
  if(allocated(ROXYFs1))deallocate(ROXYFs1)
  if(allocated(RCO2Fs1))deallocate(RCO2Fs1)
  if(allocated(ROXYLs1))deallocate(ROXYLs1)
  if(allocated(ROXYYs1))deallocate(ROXYYs1)
  if(allocated(SCO2Ls1))deallocate(SCO2Ls1)
  if(allocated(O2Ls1))deallocate(O2Ls1)
  if(allocated(DLYR3s1))deallocate(DLYR3s1)
  if(allocated(RSMNs1))deallocate(RSMNs1)
  if(allocated(XKCO2Os1))deallocate(XKCO2Os1)
  if(allocated(WTRTSs1))deallocate(WTRTSs1)
  if(allocated(WTRTSNs1))deallocate(WTRTSNs1)
  if(allocated(WTRTSPs1))deallocate(WTRTSPs1)
  if(allocated(WTRTts1))deallocate(WTRTts1)
  if(allocated(XKCO2Ls1))deallocate(XKCO2Ls1)
  if(allocated(TKCZs1))deallocate(TKCZs1)
  if(allocated(THRM1s1))deallocate(THRM1s1)
  if(allocated(SO2s1))deallocate(SO2s1)
  if(allocated(RCs1))deallocate(RCs1)
  if(allocated(RAs1))deallocate(RAs1)
  if(allocated(SFLXCs1))deallocate(SFLXCs1)
  if(allocated(PSILZs1))deallocate(PSILZs1)
  if(allocated(SOXYLs1))deallocate(SOXYLs1)
  if(allocated(SCH4Ls1))deallocate(SCH4Ls1)
  if(allocated(SN2OLs1))deallocate(SN2OLs1)
  if(allocated(SNH3Ls1))deallocate(SNH3Ls1)
  if(allocated(SH2GLs1))deallocate(SH2GLs1)
  if(allocated(THETWs1))deallocate(THETWs1)
  if(allocated(THETYs1))deallocate(THETYs1)
  if(allocated(TKSs1))deallocate(TKSs1)
  if(allocated(TFNDs1))deallocate(TFNDs1)
  if(allocated(VOLXs1))deallocate(VOLXs1)
  if(allocated(VLPOBs1))deallocate(VLPOBs1)
  if(allocated(VLNO3s1))deallocate(VLNO3s1)
  if(allocated(VLPO4s1))deallocate(VLPO4s1)
  if(allocated(VOLYs1))deallocate(VOLYs1)
  if(allocated(VOLIs1))deallocate(VOLIs1)
  if(allocated(VOLWs1))deallocate(VOLWs1)
  if(allocated(VOLAs1))deallocate(VOLAs1)
  if(allocated(VLNOBs1))deallocate(VLNOBs1)
  if(allocated(VLNH4s1))deallocate(VLNH4s1)
  if(allocated(VLNHBs1))deallocate(VLNHBs1)
  if(allocated(ZOSGLs1))deallocate(ZOSGLs1)
  if(allocated(ZLs1))deallocate(ZLs1)
  if(allocated(AREA3s1))deallocate(AREA3s1)
  if(allocated(ZNO3Ss1))deallocate(ZNO3Ss1)
  if(allocated(ZNO3Bs1))deallocate(ZNO3Bs1)
  if(allocated(ZNSGLs1))deallocate(ZNSGLs1)
  if(allocated(ZNH4Ss1))deallocate(ZNH4Ss1)
  if(allocated(ZNH4Bs1))deallocate(ZNH4Bs1)
  if(allocated(Z2OSs1))deallocate(Z2OSs1)
  if(allocated(ZNH3Ss1))deallocate(ZNH3Ss1)
  if(allocated(ZNH3Bs1))deallocate(ZNH3Bs1)
  if(allocated(ZVSGLs1))deallocate(ZVSGLs1)
  if(allocated(RP1BXs1))deallocate(RP1BXs1)
  if(allocated(RNO3Xs1))deallocate(RNO3Xs1)
  if(allocated(RP14Xs1))deallocate(RP14Xs1)
  if(allocated(RNH4Xs1))deallocate(RNH4Xs1)
  if(allocated(ROXYXs1))deallocate(ROXYXs1)
  if(allocated(RPO4Xs1))deallocate(RPO4Xs1)
  if(allocated(RNHBXs1))deallocate(RNHBXs1)
  if(allocated(RN3BXs1))deallocate(RN3BXs1)
  if(allocated(RPOBXs1))deallocate(RPOBXs1)
  if(allocated(TCO2Ss1))deallocate(TCO2Ss1)
  if(allocated(TUPNH4s1))deallocate(TUPNH4s1)
  if(allocated(TUPN2Ss1))deallocate(TUPN2Ss1)
  if(allocated(TUPOXPs1))deallocate(TUPOXPs1)
  if(allocated(TUPOXSs1))deallocate(TUPOXSs1)
  if(allocated(TCO2Ps1))deallocate(TCO2Ps1)
  if(allocated(THGFLAs1))deallocate(THGFLAs1)
  if(allocated(TN2FLAs1))deallocate(TN2FLAs1)
  if(allocated(TNHFLAs1))deallocate(TNHFLAs1)
  if(allocated(TCOFLAs1))deallocate(TCOFLAs1)
  if(allocated(TOXFLAs1))deallocate(TOXFLAs1)
  if(allocated(TCHFLAs1))deallocate(TCHFLAs1)
  if(allocated(TLCH4Ps1))deallocate(TLCH4Ps1)
  if(allocated(TLCO2Ps1))deallocate(TLCO2Ps1)
  if(allocated(TLNH3Ps1))deallocate(TLNH3Ps1)
  if(allocated(TUPHTs1))deallocate(TUPHTs1)
  if(allocated(RTDNTs1))deallocate(RTDNTs1)
  if(allocated(TUPNFs1))deallocate(TUPNFs1)
  if(allocated(TDFOMPs1))deallocate(TDFOMPs1)
  if(allocated(TDFOMNs1))deallocate(TDFOMNs1)
  if(allocated(TDFOMCs1))deallocate(TDFOMCs1)
  if(allocated(TUPWTRs1))deallocate(TUPWTRs1)
  if(allocated(TLOXYPs1))deallocate(TLOXYPs1)
  if(allocated(TLN2OPs1))deallocate(TLN2OPs1)
  if(allocated(TUPHGSs1))deallocate(TUPHGSs1)
  if(allocated(TLH2GPs1))deallocate(TLH2GPs1)
  if(allocated(TUPCHSs1))deallocate(TUPCHSs1)
  if(allocated(TUPN3Ss1))deallocate(TUPN3Ss1)
  if(allocated(TUPN3Bs1))deallocate(TUPN3Bs1)
  if(allocated(TUPH1Bs1))deallocate(TUPH1Bs1)
  if(allocated(TUPNO3s1))deallocate(TUPNO3s1)
  if(allocated(TUPH1Ps1))deallocate(TUPH1Ps1)
  if(allocated(TUPNOBs1))deallocate(TUPNOBs1)
  if(allocated(TUPNHBs1))deallocate(TUPNHBs1)
  if(allocated(TUPH2Ps1))deallocate(TUPH2Ps1)
  if(allocated(TUPH2Bs1))deallocate(TUPH2Bs1)
  if(allocated(RDFOMCs1))deallocate(RDFOMCs1)
  if(allocated(CSNTs1))deallocate(CSNTs1)
  if(allocated(ZSNTs1))deallocate(ZSNTs1)
  if(allocated(PSNTs1))deallocate(PSNTs1)
  if(allocated(RDFOMNs1))deallocate(RDFOMNs1)
  if(allocated(RDFOMPs1))deallocate(RDFOMPs1)
  if(allocated(FOSRHs1))deallocate(FOSRHs1)
  if(allocated(OQCs1))deallocate(OQCs1)
  if(allocated(OQNs1))deallocate(OQNs1)
  if(allocated(OQPs1))deallocate(OQPs1)
  if(allocated(XOQCSs1))deallocate(XOQCSs1)
  if(allocated(XOQNSs1))deallocate(XOQNSs1)
  if(allocated(XOQPSs1))deallocate(XOQPSs1)
  if(allocated(FLWCs1))deallocate(FLWCs1)
  if(allocated(EHVSTs1))deallocate(EHVSTs1)
  if(allocated(HVSTs1))deallocate(HVSTs1)
  if(allocated(THINs1))deallocate(THINs1)
  if(allocated(ARSTPs1))deallocate(ARSTPs1)
  if(allocated(ARLFPs1))deallocate(ARLFPs1)
  if(allocated(BALCs1))deallocate(BALCs1)
  if(allocated(BALNs1))deallocate(BALNs1)
  if(allocated(BALPs1))deallocate(BALPs1)
  if(allocated(CO2Is1))deallocate(CO2Is1)
  if(allocated(CCPOLPs1))deallocate(CCPOLPs1)
  if(allocated(CPOOLPs1))deallocate(CPOOLPs1)
  if(allocated(CPOLNPs1))deallocate(CPOLNPs1)
  if(allocated(CCPLNPs1))deallocate(CCPLNPs1)
  if(allocated(CZPOLPs1))deallocate(CZPOLPs1)
  if(allocated(CPPOLPs1))deallocate(CPPOLPs1)
  if(allocated(CTCs1))deallocate(CTCs1)
  if(allocated(CNETs1))deallocate(CNETs1)
  if(allocated(CPRTSs1))deallocate(CPRTSs1)
  if(allocated(CNRTSs1))deallocate(CNRTSs1)
  if(allocated(CARBNs1))deallocate(CARBNs1)
  if(allocated(CNNDs1))deallocate(CNNDs1)
  if(allocated(CPNDs1))deallocate(CPNDs1)
  if(allocated(CNRTs1))deallocate(CNRTs1)
  if(allocated(CWSRTs1))deallocate(CWSRTs1)
  if(allocated(RSMXs1))deallocate(RSMXs1)
  if(allocated(NRTs1)) deallocate(NRTs1)
  if(allocated(NNODs1))deallocate(NNODs1)
  if(allocated(IDTHPs1))deallocate(IDTHPs1)
  if(allocated(CPRTs1))deallocate(CPRTs1)
  if(allocated(CNWSs1))deallocate(CNWSs1)
  if(allocated(CPWSs1))deallocate(CPWSs1)
  if(allocated(CFXs1))deallocate(CFXs1)
  if(allocated(DCO2s1))deallocate(DCO2s1)
  if(allocated(DATAPs1))deallocate(DATAPs1)
  if(allocated(IDTHRs1))deallocate(IDTHRs1)
  if(allocated(IBTYPs1))deallocate(IBTYPs1)
  if(allocated(NBTs1)) deallocate(NBTs1)
  if(allocated(DMNDs1))deallocate(DMNDs1)
  if(allocated(DMRTs1))deallocate(DMRTs1)
  if(allocated(FMOLs1))deallocate(FMOLs1)
  if(allocated(FNODs1))deallocate(FNODs1)
  if(allocated(GROUPIs1))deallocate(GROUPIs1)
  if(allocated(HTCTLs1))deallocate(HTCTLs1)
  if(allocated(HCSNCs1))deallocate(HCSNCs1)
  if(allocated(HZSNCs1))deallocate(HZSNCs1)
  if(allocated(HPSNCs1))deallocate(HPSNCs1)
  if(allocated(HVSTCs1))deallocate(HVSTCs1)
  if(allocated(HVSTNs1))deallocate(HVSTNs1)
  if(allocated(HVSTPs1))deallocate(HVSTPs1)
  if(allocated(HCUPTKs1))deallocate(HCUPTKs1)
  if(allocated(HZUPTKs1))deallocate(HZUPTKs1)
  if(allocated(HPUPTKs1))deallocate(HPUPTKs1)
  if(allocated(HTSTZs1))deallocate(HTSTZs1)
  if(allocated(OFFSTs1))deallocate(OFFSTs1)
  if(allocated(OSTRs1))deallocate(OSTRs1)
  if(allocated(PPs1))deallocate(PPs1)
  if(allocated(PSILTs1))deallocate(PSILTs1)
  if(allocated(PBs1))deallocate(PBs1)
  if(allocated(PRs1))deallocate(PRs1)
  if(allocated(PPOOLPs1))deallocate(PPOOLPs1)
  if(allocated(PPOLNPs1))deallocate(PPOLNPs1)
  if(allocated(PSILGs1))deallocate(PSILGs1)
  if(allocated(RCMXs1))deallocate(RCMXs1)
  if(allocated(RCO2Zs1))deallocate(RCO2Zs1)
  if(allocated(ROXYZs1))deallocate(ROXYZs1)
  if(allocated(RCH4Zs1))deallocate(RCH4Zs1)
  if(allocated(RN2OZs1))deallocate(RN2OZs1)
  if(allocated(RNH3Zs1))deallocate(RNH3Zs1)
  if(allocated(RH2GZs1))deallocate(RH2GZs1)
  if(allocated(RSETCs1))deallocate(RSETCs1)
  if(allocated(RSETNs1))deallocate(RSETNs1)
  if(allocated(RSETPs1))deallocate(RSETPs1)
  if(allocated(RTFQs1))deallocate(RTFQs1)
  if(allocated(RAZs1))deallocate(RAZs1)
  if(allocated(SCO2s1))deallocate(SCO2s1)
  if(allocated(CO2Qs1))deallocate(CO2Qs1)
  if(allocated(EVAPCs1))deallocate(EVAPCs1)
  if(allocated(HFLXCs1))deallocate(HFLXCs1)
  if(allocated(EFLXCs1))deallocate(EFLXCs1)
  if(allocated(GRNOs1))deallocate(GRNOs1)
  if(allocated(CO2Ls1))deallocate(CO2Ls1)
  if(allocated(SDPTHs1))deallocate(SDPTHs1)
  if(allocated(SDPTHIs1))deallocate(SDPTHIs1)
  if(allocated(SDLGs1))deallocate(SDLGs1)
  if(allocated(SDVLs1))deallocate(SDVLs1)
  if(allocated(SDARs1))deallocate(SDARs1)
  if(allocated(TCZs1))deallocate(TCZs1)
  if(allocated(TCGs1))deallocate(TCGs1)
  if(allocated(TCXs1))deallocate(TCXs1)
  if(allocated(TKGs1))deallocate(TKGs1)
  if(allocated(TFN3s1))deallocate(TFN3s1)
  if(allocated(TCSN0s1))deallocate(TCSN0s1)
  if(allocated(TZSN0s1))deallocate(TZSN0s1)
  if(allocated(TPSN0s1))deallocate(TPSN0s1)
  if(allocated(TCSNCs1))deallocate(TCSNCs1)
  if(allocated(TZSNCs1))deallocate(TZSNCs1)
  if(allocated(TPSNCs1))deallocate(TPSNCs1)
  if(allocated(TCO2Ts1))deallocate(TCO2Ts1)
  if(allocated(TCUPTKs1))deallocate(TCUPTKs1)
  if(allocated(THVSTCs1))deallocate(THVSTCs1)
  if(allocated(TNH3Cs1))deallocate(TNH3Cs1)
  if(allocated(TZUPTKs1))deallocate(TZUPTKs1)
  if(allocated(THVSTNs1))deallocate(THVSTNs1)
  if(allocated(TZUPFXs1))deallocate(TZUPFXs1)
  if(allocated(TPUPTKs1))deallocate(TPUPTKs1)
  if(allocated(THVSTPs1))deallocate(THVSTPs1)
  if(allocated(UPOMCs1))deallocate(UPOMCs1)
  if(allocated(UPNFs1))deallocate(UPNFs1)
  if(allocated(UPNO3s1))deallocate(UPNO3s1)
  if(allocated(UPNH4s1))deallocate(UPNH4s1)
  if(allocated(UPOMNs1))deallocate(UPOMNs1)
  if(allocated(UPH1Ps1))deallocate(UPH1Ps1)
  if(allocated(UPH2Ps1))deallocate(UPH2Ps1)
  if(allocated(UPOMPs1))deallocate(UPOMPs1)
  if(allocated(VOLWCs1))deallocate(VOLWCs1)
  if(allocated(VHCPCs1))deallocate(VHCPCs1)
  if(allocated(VCH4Fs1))deallocate(VCH4Fs1)
  if(allocated(VCO2Fs1))deallocate(VCO2Fs1)
  if(allocated(VN2OFs1))deallocate(VN2OFs1)
  if(allocated(VNH3Fs1))deallocate(VNH3Fs1)
  if(allocated(VPO4Fs1))deallocate(VPO4Fs1)
  if(allocated(VOLWPs1))deallocate(VOLWPs1)
  if(allocated(WSTRs1))deallocate(WSTRs1)
  if(allocated(WTRVXs1))deallocate(WTRVXs1)
  if(allocated(WTRVCs1))deallocate(WTRVCs1)
  if(allocated(WTLSs1))deallocate(WTLSs1)
  if(allocated(WTSHTs1))deallocate(WTSHTs1)
  if(allocated(WTSHTAs1))deallocate(WTSHTAs1)
  if(allocated(WTSTGs1))deallocate(WTSTGs1)
  if(allocated(WTSTGNs1))deallocate(WTSTGNs1)
  if(allocated(WTSTGPs1))deallocate(WTSTGPs1)
  if(allocated(WTNDs1))deallocate(WTNDs1)
  if(allocated(WTNDNs1))deallocate(WTNDNs1)
  if(allocated(WTRTNs1))deallocate(WTRTNs1)
  if(allocated(WTSHNs1))deallocate(WTSHNs1)
  if(allocated(WTRVNs1))deallocate(WTRVNs1)
  if(allocated(WTNDPs1))deallocate(WTNDPs1)
  if(allocated(WTRTPs1))deallocate(WTRTPs1)
  if(allocated(WTSHPs1))deallocate(WTSHPs1)
  if(allocated(WTRVPs1))deallocate(WTRVPs1)
  if(allocated(XKCO24s1))deallocate(XKCO24s1)
  if(allocated(XTLIs1))deallocate(XTLIs1)
  if(allocated(XRNIs1))deallocate(XRNIs1)
  if(allocated(XRLAs1))deallocate(XRLAs1)
  if(allocated(XDLs1))deallocate(XDLs1)
  if(allocated(XPPDs1))deallocate(XPPDs1)
  if(allocated(ZPOOLPs1))deallocate(ZPOOLPs1)
  if(allocated(ZPOLNPs1))deallocate(ZPOLNPs1)
  if(allocated(ZEROLs1))deallocate(ZEROLs1)
  if(allocated(ZEROPs1))deallocate(ZEROPs1)
  if(allocated(ZEROQs1))deallocate(ZEROQs1)
  if(allocated(ZCs1))deallocate(ZCs1)
  if(allocated(O2Is1))deallocate(O2Is1)
  if(allocated(ZNPPs1))deallocate(ZNPPs1)
  if(allocated(CLASSs1))deallocate(CLASSs1)
  if(allocated(ATRPs1))deallocate(ATRPs1)
  if(allocated(ARLFZs1))deallocate(ARLFZs1)
  if(allocated(ARLFBs1))deallocate(ARLFBs1)
  if(allocated(CPOOLs1))deallocate(CPOOLs1)
  if(allocated(CPOLNBs1))deallocate(CPOLNBs1)
  if(allocated(CCPOLBs1))deallocate(CCPOLBs1)
  if(allocated(CZPOLBs1))deallocate(CZPOLBs1)
  if(allocated(CPPOLBs1))deallocate(CPPOLBs1)
  if(allocated(DGSTGIs1))deallocate(DGSTGIs1)
  if(allocated(DGSTGFs1))deallocate(DGSTGFs1)
  if(allocated(FLG4s1))deallocate(FLG4s1)
  if(allocated(FDBKs1))deallocate(FDBKs1)
  if(allocated(FDBKXs1))deallocate(FDBKXs1)
  if(allocated(FLGZs1))deallocate(FLGZs1)
  if(allocated(GROUPs1))deallocate(GROUPs1)
  if(allocated(GSTGIs1))deallocate(GSTGIs1)
  if(allocated(GSTGFs1))deallocate(GSTGFs1)
  if(allocated(GRNXBs1))deallocate(GRNXBs1)
  if(allocated(GRNOBs1))deallocate(GRNOBs1)
  if(allocated(GRWTBs1))deallocate(GRWTBs1)
  if(allocated(HTSHEXs1))deallocate(HTSHEXs1)
  if(allocated(IDTHBs1))deallocate(IDTHBs1)
  if(allocated(IFLGPs1))deallocate(IFLGPs1)
  if(allocated(IFLGFs1))deallocate(IFLGFs1)
  if(allocated(IFLGEs1))deallocate(IFLGEs1)
  if(allocated(IFLGAs1))deallocate(IFLGAs1)
  if(allocated(IFLGGs1))deallocate(IFLGGs1)
  if(allocated(IFLGRs1))deallocate(IFLGRs1)
  if(allocated(IFLGQs1))deallocate(IFLGQs1)
  if(allocated(KVSTGs1))deallocate(KVSTGs1)
  if(allocated(KLEAFs1))deallocate(KLEAFs1)
  if(allocated(KVSTGNs1))deallocate(KVSTGNs1)
  if(allocated(KLEAFXs1))deallocate(KLEAFXs1)
  if(allocated(NBTBs1))deallocate(NBTBs1)
  if(allocated(IDAYs1))deallocate(IDAYs1)
  if(allocated(IDAYYs1))deallocate(IDAYYs1)
  if(allocated(NINRs1))deallocate(NINRs1)
  if(allocated(PSTGs1))deallocate(PSTGs1)
  if(allocated(PSTGIs1))deallocate(PSTGIs1)
  if(allocated(PSTGFs1))deallocate(PSTGFs1)
  if(allocated(PPOOLs1))deallocate(PPOOLs1)
  if(allocated(PPOLNBs1))deallocate(PPOLNBs1)
  if(allocated(RCCLXs1))deallocate(RCCLXs1)
  if(allocated(RCZLXs1))deallocate(RCZLXs1)
  if(allocated(RCPLXs1))deallocate(RCPLXs1)
  if(allocated(RCCSXs1))deallocate(RCCSXs1)
  if(allocated(RCZSXs1))deallocate(RCZSXs1)
  if(allocated(RCPSXs1))deallocate(RCPSXs1)
  if(allocated(RNH3Bs1))deallocate(RNH3Bs1)
  if(allocated(TGSTGIs1))deallocate(TGSTGIs1)
  if(allocated(TGSTGFs1))deallocate(TGSTGFs1)
  if(allocated(VSTGXs1))deallocate(VSTGXs1)
  if(allocated(VSTGs1))deallocate(VSTGs1)
  if(allocated(VRNYs1))deallocate(VRNYs1)
  if(allocated(VRNZs1))deallocate(VRNZs1)
  if(allocated(VRNSs1))deallocate(VRNSs1)
  if(allocated(VRNLs1))deallocate(VRNLs1)
  if(allocated(VRNFs1))deallocate(VRNFs1)
  if(allocated(VRNXs1))deallocate(VRNXs1)
  if(allocated(WTLSBs1))deallocate(WTLSBs1)
  if(allocated(WTRSVBs1))deallocate(WTRSVBs1)
  if(allocated(WTLFBs1))deallocate(WTLFBs1)
  if(allocated(WTNDBs1))deallocate(WTNDBs1)
  if(allocated(WTSHEBs1))deallocate(WTSHEBs1)
  if(allocated(WTEARBs1))deallocate(WTEARBs1)
  if(allocated(WTHSKBs1))deallocate(WTHSKBs1)
  if(allocated(WTRSBNs1))deallocate(WTRSBNs1)
  if(allocated(WTLFBNs1))deallocate(WTLFBNs1)
  if(allocated(WTNDBNs1))deallocate(WTNDBNs1)
  if(allocated(WTSHBNs1))deallocate(WTSHBNs1)
  if(allocated(WTEABNs1))deallocate(WTEABNs1)
  if(allocated(WTHSBNs1))deallocate(WTHSBNs1)
  if(allocated(WTRSBPs1))deallocate(WTRSBPs1)
  if(allocated(WTLFBPs1))deallocate(WTLFBPs1)
  if(allocated(WTNDBPs1))deallocate(WTNDBPs1)
  if(allocated(WTSHBPs1))deallocate(WTSHBPs1)
  if(allocated(WTEABPs1))deallocate(WTEABPs1)
  if(allocated(WTHSBPs1))deallocate(WTHSBPs1)
  if(allocated(WTGRBs1))deallocate(WTGRBs1)
  if(allocated(WTGRBNs1))deallocate(WTGRBNs1)
  if(allocated(WTGRBPs1))deallocate(WTGRBPs1)
  if(allocated(WTSTKBs1))deallocate(WTSTKBs1)
  if(allocated(WTSTBNs1))deallocate(WTSTBNs1)
  if(allocated(WTSTBPs1))deallocate(WTSTBPs1)
  if(allocated(WTSHTBs1))deallocate(WTSHTBs1)
  if(allocated(WTSHTNs1))deallocate(WTSHTNs1)
  if(allocated(WTSHTPs1))deallocate(WTSHTPs1)
  if(allocated(WGLFXs1))deallocate(WGLFXs1)
  if(allocated(WGLFNXs1))deallocate(WGLFNXs1)
  if(allocated(WGLFPXs1))deallocate(WGLFPXs1)
  if(allocated(WGSHEXs1))deallocate(WGSHEXs1)
  if(allocated(WGSHNXs1))deallocate(WGSHNXs1)
  if(allocated(WGSHPXs1))deallocate(WGSHPXs1)
  if(allocated(WTSTXBs1))deallocate(WTSTXBs1)
  if(allocated(WTSTXNs1))deallocate(WTSTXNs1)
  if(allocated(WTSTXPs1))deallocate(WTSTXPs1)
  if(allocated(WVSTKBs1))deallocate(WVSTKBs1)
  if(allocated(ZPOOLs1))deallocate(ZPOOLs1)
  if(allocated(ZPOLNBs1))deallocate(ZPOLNBs1)
  if(allocated(SURFs1))deallocate(SURFs1)
  if(allocated(SURFXs1))deallocate(SURFXs1)
  if(allocated(CPOOL3s1))deallocate(CPOOL3s1)
  if(allocated(CPOOL4s1))deallocate(CPOOL4s1)
  if(allocated(OMEGAs1))deallocate(OMEGAs1)
  if(allocated(IALBYs1))deallocate(IALBYs1)
  if(allocated(OMEGXs1))deallocate(OMEGXs1)
  if(allocated(CO2Bs1))deallocate(CO2Bs1)
  if(allocated(COMPLs1))deallocate(COMPLs1)
  if(allocated(CBXNs1))deallocate(CBXNs1)
  if(allocated(CBXN4s1))deallocate(CBXN4s1)
  if(allocated(ETGROs1))deallocate(ETGROs1)
  if(allocated(ETGR4s1))deallocate(ETGR4s1)
  if(allocated(FDBK4s1))deallocate(FDBK4s1)
  if(allocated(HCOBs1))deallocate(HCOBs1)
  if(allocated(VCGROs1))deallocate(VCGROs1)
  if(allocated(VGROs1))deallocate(VGROs1)
  if(allocated(VCGR4s1))deallocate(VCGR4s1)
  if(allocated(VGRO4s1))deallocate(VGRO4s1)
  if(allocated(ARLF1s1))deallocate(ARLF1s1)
  if(allocated(HTNODXs1))deallocate(HTNODXs1)
  if(allocated(HTSHEs1))deallocate(HTSHEs1)
  if(allocated(HTNODEs1))deallocate(HTNODEs1)
  if(allocated(WGNODEs1))deallocate(WGNODEs1)
  if(allocated(WGNODNs1))deallocate(WGNODNs1)
  if(allocated(WGNODPs1))deallocate(WGNODPs1)
  if(allocated(WGLFs1))deallocate(WGLFs1)
  if(allocated(WGLFNs1))deallocate(WGLFNs1)
  if(allocated(WGLFPs1))deallocate(WGLFPs1)
  if(allocated(WSLFs1))deallocate(WSLFs1)
  if(allocated(WGSHEs1))deallocate(WGSHEs1)
  if(allocated(WGSHNs1))deallocate(WGSHNs1)
  if(allocated(WGSHPs1))deallocate(WGSHPs1)
  if(allocated(WSSHEs1))deallocate(WSSHEs1)
  if(allocated(SURFBs1))deallocate(SURFBs1)
  if(allocated(ARLFLs1))deallocate(ARLFLs1)
  if(allocated(WGLFLs1))deallocate(WGLFLs1)
  if(allocated(WGLFLNs1))deallocate(WGLFLNs1)
  if(allocated(WGLFLPs1))deallocate(WGLFLPs1)
  if(allocated(ARSTKs1))deallocate(ARSTKs1)
  if(allocated(WTSTDIs1))deallocate(WTSTDIs1)
  if(allocated(OSMOs1))deallocate(OSMOs1)
  if(allocated(TCCs1))deallocate(TCCs1)
  if(allocated(DTKCs1))deallocate(DTKCs1)
  if(allocated(TKCs1))deallocate(TKCs1)
  if(allocated(WTRT1s1))deallocate(WTRT1s1)
  if(allocated(CPGRs1))deallocate(CPGRs1)
  if(allocated(ENGYXs1))deallocate(ENGYXs1)
  if(allocated(PSILOs1))deallocate(PSILOs1)
  if(allocated(CNSTKs1))deallocate(CNSTKs1)
  if(allocated(CTRANs1))deallocate(CTRANs1)
  if(allocated(CHILLs1))deallocate(CHILLs1)
  if(allocated(TCO2As1))deallocate(TCO2As1)
  if(allocated(CPSTKs1))deallocate(CPSTKs1)
  if(allocated(CPOOLRs1))deallocate(CPOOLRs1)
  if(allocated(CCPOLRs1))deallocate(CCPOLRs1)
  if(allocated(CZPOLRs1))deallocate(CZPOLRs1)
  if(allocated(CPPOLRs1))deallocate(CPPOLRs1)
  if(allocated(CO2Ps1))deallocate(CO2Ps1)
  if(allocated(CO2As1))deallocate(CO2As1)
  if(allocated(CH4Ps1))deallocate(CH4Ps1)
  if(allocated(CH4As1))deallocate(CH4As1)
  if(allocated(CWSRTLs1))deallocate(CWSRTLs1)
  if(allocated(H2GPs1))deallocate(H2GPs1)
  if(allocated(H2GAs1))deallocate(H2GAs1)
  if(allocated(OXYPs1))deallocate(OXYPs1)
  if(allocated(OXYAs1))deallocate(OXYAs1)
  if(allocated(PSIRTs1))deallocate(PSIRTs1)
  if(allocated(PSIROs1))deallocate(PSIROs1)
  if(allocated(PSIRGs1))deallocate(PSIRGs1)
  if(allocated(PPOOLRs1))deallocate(PPOOLRs1)
  if(allocated(RUPNHBs1))deallocate(RUPNHBs1)
  if(allocated(RUPNH4s1))deallocate(RUPNH4s1)
  if(allocated(RUPH2Ps1))deallocate(RUPH2Ps1)
  if(allocated(RUPNOBs1))deallocate(RUPNOBs1)
  if(allocated(RUPNO3s1))deallocate(RUPNO3s1)
  if(allocated(RUPH1Bs1))deallocate(RUPH1Bs1)
  if(allocated(RUPH1Ps1))deallocate(RUPH1Ps1)
  if(allocated(RUPH2Bs1))deallocate(RUPH2Bs1)
  if(allocated(RUONHBs1))deallocate(RUONHBs1)
  if(allocated(RUONH4s1))deallocate(RUONH4s1)
  if(allocated(RUOH2Ps1))deallocate(RUOH2Ps1)
  if(allocated(RUONOBs1))deallocate(RUONOBs1)
  if(allocated(RUONO3s1))deallocate(RUONO3s1)
  if(allocated(RUOH1Bs1))deallocate(RUOH1Bs1)
  if(allocated(RUOH1Ps1))deallocate(RUOH1Ps1)
  if(allocated(RUOH2Bs1))deallocate(RUOH2Bs1)
  if(allocated(RUCNHBs1))deallocate(RUCNHBs1)
  if(allocated(RUCNH4s1))deallocate(RUCNH4s1)
  if(allocated(RUCH2Ps1))deallocate(RUCH2Ps1)
  if(allocated(RUCNOBs1))deallocate(RUCNOBs1)
  if(allocated(RUCNO3s1))deallocate(RUCNO3s1)
  if(allocated(RUCH1Bs1))deallocate(RUCH1Bs1)
  if(allocated(RUCH1Ps1))deallocate(RUCH1Ps1)
  if(allocated(RUCH2Bs1))deallocate(RUCH2Bs1)
  if(allocated(RCO2Ms1))deallocate(RCO2Ms1)
  if(allocated(RCO2Ns1))deallocate(RCO2Ns1)
  if(allocated(RCO2As1))deallocate(RCO2As1)
  if(allocated(RTN1s1))deallocate(RTN1s1)
  if(allocated(RTNLs1))deallocate(RTNLs1)
  if(allocated(RTLGPs1))deallocate(RTLGPs1)
  if(allocated(RTDNPs1))deallocate(RTDNPs1)
  if(allocated(RTVLPs1))deallocate(RTVLPs1)
  if(allocated(RTVLWs1))deallocate(RTVLWs1)
  if(allocated(RRAD1s1))deallocate(RRAD1s1)
  if(allocated(RAD1s1))deallocate(RAD1s1)
  if(allocated(RRAD2s1))deallocate(RRAD2s1)
  if(allocated(RTARPs1))deallocate(RTARPs1)
  if(allocated(RTLGAs1))deallocate(RTLGAs1)
  if(allocated(RCO2Ps1))deallocate(RCO2Ps1)
  if(allocated(RUPOXPs1))deallocate(RUPOXPs1)
  if(allocated(RCO2Ss1))deallocate(RCO2Ss1)
  if(allocated(RUPOXSs1))deallocate(RUPOXSs1)
  if(allocated(RUPCHSs1))deallocate(RUPCHSs1)
  if(allocated(RUPN2Ss1))deallocate(RUPN2Ss1)
  if(allocated(RUPN3Ss1))deallocate(RUPN3Ss1)
  if(allocated(RUPN3Bs1))deallocate(RUPN3Bs1)
  if(allocated(RUPHGSs1))deallocate(RUPHGSs1)
  if(allocated(RCOFLAs1))deallocate(RCOFLAs1)
  if(allocated(ROXFLAs1))deallocate(ROXFLAs1)
  if(allocated(RCHFLAs1))deallocate(RCHFLAs1)
  if(allocated(RN2FLAs1))deallocate(RN2FLAs1)
  if(allocated(RNHFLAs1))deallocate(RNHFLAs1)
  if(allocated(RHGFLAs1))deallocate(RHGFLAs1)
  if(allocated(RCODFAs1))deallocate(RCODFAs1)
  if(allocated(ROXDFAs1))deallocate(ROXDFAs1)
  if(allocated(RCHDFAs1))deallocate(RCHDFAs1)
  if(allocated(RN2DFAs1))deallocate(RN2DFAs1)
  if(allocated(RNHDFAs1))deallocate(RNHDFAs1)
  if(allocated(RHGDFAs1))deallocate(RHGDFAs1)
  if(allocated(ROXYPs1))deallocate(ROXYPs1)
  if(allocated(RUNNHPs1))deallocate(RUNNHPs1)
  if(allocated(RUNNBPs1))deallocate(RUNNBPs1)
  if(allocated(RUNNOPs1))deallocate(RUNNOPs1)
  if(allocated(RUNNXPs1))deallocate(RUNNXPs1)
  if(allocated(RUPP2Ps1))deallocate(RUPP2Ps1)
  if(allocated(RUPP2Bs1))deallocate(RUPP2Bs1)
  if(allocated(RUPP1Ps1))deallocate(RUPP1Ps1)
  if(allocated(RUPP1Bs1))deallocate(RUPP1Bs1)
  if(allocated(UPWTRs1))deallocate(UPWTRs1)
  if(allocated(WFRs1))deallocate(WFRs1)
  if(allocated(WTRTLs1))deallocate(WTRTLs1)
  if(allocated(WTRTDs1))deallocate(WTRTDs1)
  if(allocated(WSRTLs1))deallocate(WSRTLs1)
  if(allocated(ZPOOLRs1))deallocate(ZPOOLRs1)
  if(allocated(Z2OPs1))deallocate(Z2OPs1)
  if(allocated(Z2OAs1))deallocate(Z2OAs1)
  if(allocated(ZH3Ps1))deallocate(ZH3Ps1)
  if(allocated(ZH3As1))deallocate(ZH3As1)
  if(allocated(CPOOLNs1))deallocate(CPOOLNs1)
  if(allocated(RUPNFs1))deallocate(RUPNFs1)
  if(allocated(PPOOLNs1))deallocate(PPOOLNs1)
  if(allocated(TFN4s1))deallocate(TFN4s1)
  if(allocated(WTNDLNs1))deallocate(WTNDLNs1)
  if(allocated(WTNDLs1))deallocate(WTNDLs1)
  if(allocated(WTNDLPs1))deallocate(WTNDLPs1)
  if(allocated(ZPOOLNs1))deallocate(ZPOOLNs1)
  if(allocated(ARSTVs1))deallocate(ARSTVs1)
  if(allocated(ARLFVs1))deallocate(ARLFVs1)
  if(allocated(WGLFVs1))deallocate(WGLFVs1)
  if(allocated(DMVLs1))deallocate(DMVLs1)
  if(allocated(PORTs1))deallocate(PORTs1)
  if(allocated(PORTXs1))deallocate(PORTXs1)
  if(allocated(RTAR2Xs1))deallocate(RTAR2Xs1)
  if(allocated(RTAR1Xs1))deallocate(RTAR1Xs1)
  if(allocated(RRAD1Xs1))deallocate(RRAD1Xs1)
  if(allocated(RRAD2Xs1))deallocate(RRAD2Xs1)
  if(allocated(WTRTAs1))deallocate(WTRTAs1)
  if(allocated(VOXYFs1))deallocate(VOXYFs1)
  if(allocated(WTSHEPs1))deallocate(WTSHEPs1)
  if(allocated(WTLFPs1))deallocate(WTLFPs1)
  if(allocated(CNGRs1))deallocate(CNGRs1)
  if(allocated(FRADPs1))deallocate(FRADPs1)
  if(allocated(EPs1))deallocate(EPs1)
  if(allocated(ZSINs1))deallocate(ZSINs1)
  if(allocated(WDLFs1))deallocate(WDLFs1)
  if(allocated(DMLFs1))deallocate(DMLFs1)
  if(allocated(GFILLs1))deallocate(GFILLs1)
  if(allocated(IRTYPs1))deallocate(IRTYPs1)
  if(allocated(STMXs1))deallocate(STMXs1)
  if(allocated(SDMXs1))deallocate(SDMXs1)
  if(allocated(GRMXs1))deallocate(GRMXs1)
  if(allocated(RADPs1))deallocate(RADPs1)
  if(allocated(WTLFs1))deallocate(WTLFs1)
  if(allocated(WTSHEs1))deallocate(WTSHEs1)
  if(allocated(CNLFs1))deallocate(CNLFs1)
  if(allocated(WVSTKs1))deallocate(WVSTKs1)
  if(allocated(PTSHTs1))deallocate(PTSHTs1)
  if(allocated(WTRSVs1))deallocate(WTRSVs1)
  if(allocated(WTSTKs1))deallocate(WTSTKs1)
  if(allocated(CPLFs1))deallocate(CPLFs1)
  if(allocated(CPSHEs1))deallocate(CPSHEs1)
  if(allocated(CNSHEs1))deallocate(CNSHEs1)
  if(allocated(WTEARNs1))deallocate(WTEARNs1)
  if(allocated(WTGRs1))deallocate(WTGRs1)
  if(allocated(WTSHENs1))deallocate(WTSHENs1)
  if(allocated(WTRSVNs1))deallocate(WTRSVNs1)
  if(allocated(WTLFNs1))deallocate(WTLFNs1)
  if(allocated(WTHSKNs1))deallocate(WTHSKNs1)
  if(allocated(WTEARs1))deallocate(WTEARs1)
  if(allocated(WTHSKs1))deallocate(WTHSKs1)
  if(allocated(WTGRNNs1))deallocate(WTGRNNs1)
  if(allocated(RNH3Cs1))deallocate(RNH3Cs1)
  if(allocated(WTSTKPs1))deallocate(WTSTKPs1)
  if(allocated(WTRSVPs1))deallocate(WTRSVPs1)
  if(allocated(WTHSKPs1))deallocate(WTHSKPs1)
  if(allocated(WTEARPs1))deallocate(WTEARPs1)
  if(allocated(WTGRNPs1)) deallocate(WTGRNPs1)
  if(allocated(WTSTKNs1)) deallocate(WTSTKNs1)
  if(allocated(RTLG1Xs1))deallocate(RTLG1Xs1)
  if(allocated(RRADPs1))deallocate(RRADPs1)
  if(allocated(RTLG2Xs1))deallocate(RTLG2Xs1)
  if(allocated(RSRRs1))deallocate(RSRRs1)
  if(allocated(RSRAs1))deallocate(RSRAs1)
  if(allocated(RRAD1Ms1))deallocate(RRAD1Ms1)
  if(allocated(RRAD2Ms1))deallocate(RRAD2Ms1)
  if(allocated(UPMNPOs1))deallocate(UPMNPOs1)
  if(allocated(UPMXPOs1))deallocate(UPMXPOs1)
  if(allocated(UPKMPOs1))deallocate(UPKMPOs1)
  if(allocated(UPMNZOs1))deallocate(UPMNZOs1)
  if(allocated(UPMXZOs1))deallocate(UPMXZOs1)
  if(allocated(UPKMZOs1))deallocate(UPKMZOs1)
  if(allocated(UPMNZHs1))deallocate(UPMNZHs1)
  if(allocated(UPMXZHs1))deallocate(UPMXZHs1)
  if(allocated(UPKMZHs1))deallocate(UPKMZHs1)
  if(allocated(RTLG1s1))deallocate(RTLG1s1)
  if(allocated(RTLG2s1))deallocate(RTLG2s1)
  if(allocated(RTN2s1))deallocate(RTN2s1)
  if(allocated(WTRT2s1))deallocate(WTRT2s1)
  if(allocated(WTRT2Ns1))deallocate(WTRT2Ns1)
  if(allocated(WTRT1Ns1))deallocate(WTRT1Ns1)
  if(allocated(WTRT2Ps1))deallocate(WTRT2Ps1)
  if(allocated(WTRT1Ps1))deallocate(WTRT1Ps1)
  if(allocated(RTDP1s1))deallocate(RTDP1s1)
  if(allocated(RTWT1s1))deallocate(RTWT1s1)
  if(allocated(RTWT1Ns1))deallocate(RTWT1Ns1)
  if(allocated(RTWT1Ps1))deallocate(RTWT1Ps1)
  if(allocated(WTSTDGs1))deallocate(WTSTDGs1)
  if(allocated(WTSTDNs1))deallocate(WTSTDNs1)
  if(allocated(WTSTDPs1))deallocate(WTSTDPs1)
  if(allocated(CSNCs1))deallocate(CSNCs1)
  if(allocated(PSNCs1))deallocate(PSNCs1)
  if(allocated(ZSNCs1))deallocate(ZSNCs1)
  if(allocated(CFOPCs1))deallocate(CFOPCs1)
  if(allocated(CFOPNs1))deallocate(CFOPNs1)
  if(allocated(CFOPPs1))deallocate(CFOPPs1)
  if(allocated(PARs1))deallocate(PARs1)
  if(allocated(PARDIFs1))deallocate(PARDIFs1)
  if(allocated(VOLWMs1))deallocate(VOLWMs1)
  if(allocated(VOLPMs1))deallocate(VOLPMs1)
  if(allocated(TORTs1))deallocate(TORTs1)
  if(allocated(FILMs1))deallocate(FILMs1)
  if(allocated(ROXSKs1))deallocate(ROXSKs1)
  if(allocated(THETPMs1))deallocate(THETPMs1)
  if(allocated(DFGSs1))deallocate(DFGSs1)
  end subroutine DestructPlantAPIData
end module PlantAPIData
