submodule (HistDataType) HistAllocateColumn
  use data_const_mod, only: spval => DAT_CONST_SPVAL
  use GridConsts, only: JZ
  use EcoSIMCtrlMod, only: lmicrobeMLdiag
  implicit none
contains

  module procedure allocate_hist_columns
    integer :: beg_col, end_col, beg_ptc, end_ptc

    beg_col=1; end_col=bounds%ncols
    beg_ptc=1; end_ptc=bounds%npfts

  if(lmicrobeMLdiag)then
    allocate(this%h1d_TEMP60cm_col(beg_col:end_col)) ;this%h1d_TEMP60cm_col(:)=spval
    allocate(this%h1d_THETW60cm_col(beg_col:end_col)); this%h1d_THETW60cm_col(:)=spval
    allocate(this%h1d_O2wConc60cm_col(beg_col:end_col)) ; this%h1d_O2wConc60cm_col(:)=spval
    allocate(this%h1d_AcetConc60cm_col(beg_col:end_col)); this%h1d_AcetConc60cm_col(:)=spval
    allocate(this%h1d_H2wConc60cm_col(beg_col:end_col)); this%h1d_H2wConc60cm_col(:)=spval
    allocate(this%h1d_CH4wConc60cm_col(beg_col:end_col)); this%h1d_CH4wConc60cm_col(:)=spval
    allocate(this%h1d_DOCConc60cm_col(beg_col:end_col)); this%h1d_DOCConc60cm_col(:)=spval
    allocate(this%h1d_AcetMGC60cm_col(beg_col:end_col)); this%h1d_AcetMGC60cm_col(:)=spval
    allocate(this%h1d_H2MGC60cm_col(beg_col:end_col)); this%h1d_H2MGC60cm_col(:)=spval
    allocate(this%h1d_FermC60cm_col(beg_col:end_col)); this%h1d_FermC60cm_col(:)=spval
    allocate(this%h1d_AeroMOC60cm_col(beg_col:end_col)); this%h1d_AeroMOC60cm_col(:)=spval
    allocate(this%h1d_AeroHRFungC60cm_col(beg_col:end_col)); this%h1d_AeroHRFungC60cm_col(:)=spval
    allocate(this%h1d_AeroHRBactC60cm_col(beg_col:end_col)); this%h1d_AeroHRBactC60cm_col(:)=spval
    allocate(this%h1d_RAeroCH4Oxi60cm_col(beg_col:end_col)); this%h1d_RAeroCH4Oxi60cm_col(:)=spval
    allocate(this%h1d_RCH4ProdAcet60cm_col(beg_col:end_col)); this%h1d_RCH4ProdAcet60cm_col(:)=spval
    allocate(this%h1d_RCH4ProdHG60cm_col(beg_col:end_col)); this%h1d_RCH4ProdHG60cm_col(:)=spval
    allocate(this%h1d_RFerment60cm_col(beg_col:end_col)); this%h1d_RFerment60cm_col(:)=spval
    allocate(this%h1d_RCO2Ht60cm_col(beg_col:end_col)); this%h1d_RCO2Ht60cm_col(:)=spval
    allocate(this%h1d_TEMP30cm_col(beg_col:end_col)) ; this%h1d_TEMP30cm_col(:)=spval
    allocate(this%h1d_THETW30cm_col(beg_col:end_col)); this%h1d_THETW30cm_col(:)=spval
    allocate(this%h1d_O2wConc30cm_col(beg_col:end_col)); this%h1d_O2wConc30cm_col(:)=spval
    allocate(this%h1d_AcetConc30cm_col(beg_col:end_col)); this%h1d_AcetConc30cm_col(:)=spval
    allocate(this%h1d_H2wConc30cm_col(beg_col:end_col)); this%h1d_H2wConc30cm_col(:)=spval
    allocate(this%h1d_CH4wConc30cm_col(beg_col:end_col)); this%h1d_CH4wConc30cm_col(:)=spval
    allocate(this%h1d_DOCConc30cm_col(beg_col:end_col)); this%h1d_DOCConc30cm_col(:)=spval
    allocate(this%h1d_AcetMGC30cm_col(beg_col:end_col)); this%h1d_AcetMGC30cm_col(:)=spval
    allocate(this%h1d_H2MGC30cm_col(beg_col:end_col)); this%h1d_H2MGC30cm_col(:)=spval
    allocate(this%h1d_FermC30cm_col(beg_col:end_col)); this%h1d_FermC30cm_col(:)=spval
    allocate(this%h1d_AeroMOC30cm_col(beg_col:end_col)); this%h1d_AeroMOC30cm_col(:)=spval
    allocate(this%h1d_AeroHRFungC30cm_col(beg_col:end_col)); this%h1d_AeroHRFungC30cm_col(:)=spval
    allocate(this%h1d_AeroHRBactC30cm_col(beg_col:end_col));this%h1d_AeroHRBactC30cm_col(:)=spval
    allocate(this%h1d_RAeroCH4Oxi30cm_col(beg_col:end_col)); this%h1d_RAeroCH4Oxi30cm_col(:)=spval
    allocate(this%h1d_RCH4ProdAcet30cm_col(beg_col:end_col)); this%h1d_RCH4ProdAcet30cm_col(:)=spval
    allocate(this%h1d_RCH4ProdHG30cm_col(beg_col:end_col)); this%h1d_RCH4ProdHG30cm_col(:)=spval
    allocate(this%h1d_RFerment30cm_col(beg_col:end_col)); this%h1d_RFerment30cm_col(:)=spval
    allocate(this%h1d_RCO2Ht30cm_col(beg_col:end_col)); this%h1d_RCO2Ht30cm_col(:)=spval
  endif

  allocate(this%h1D_cumFIRE_CO2_col(beg_col:end_col)) ;this%h1D_cumFIRE_CO2_col(:)=spval
  allocate(this%h1D_cumFIRE_CH4_col(beg_col:end_col)) ;this%h1D_cumFIRE_CH4_col(:)=spval
  allocate(this%h1D_cNH4_LITR_col(beg_col:end_col)) ;this%h1D_cNH4_LITR_col(:)=spval
  allocate(this%h1D_cNO3_LITR_col(beg_col:end_col)) ;this%h1D_cNO3_LITR_col(:)=spval
  allocate(this%h1D_ECO_HVST_C_col(beg_col:end_col));this%h1D_ECO_HVST_C_col(:)=spval
  allocate(this%h1D_ECO_HVST_N_col(beg_col:end_col));this%h1D_ECO_HVST_N_col(:)=spval
  allocate(this%h1D_ECO_HVST_P_col(beg_col:end_col));this%h1D_ECO_HVST_P_col(:)=spval
  allocate(this%h1D_NET_N_MIN_col(beg_col:end_col)) ;this%h1D_NET_N_MIN_col(:) =spval
  allocate(this%h1D_tLITR_P_col(beg_col:end_col)); this%h1D_tLITR_P_col(:)=spval
  allocate(this%h1D_HUMUS_C_col(beg_col:end_col))  ;this%h1D_HUMUS_C_col(:)=spval
  allocate(this%h1D_HUMUS_N_col(beg_col:end_col))  ;this%h1D_HUMUS_N_col(:)=spval
  allocate(this%h1D_HUMUS_P_col(beg_col:end_col))  ;this%h1D_HUMUS_P_col(:)=spval
  allocate(this%h1D_AMENDED_P_col(beg_col:end_col));this%h1D_AMENDED_P_col(:)=spval
  allocate(this%h1D_tLITRf_C_FLX_col(beg_col:end_col))  ;this%h1D_tLITRf_C_FLX_col(:)=spval
  allocate(this%h1D_tLITRf_N_FLX_col(beg_col:end_col))  ;this%h1D_tLITRf_N_FLX_col(:)=spval
  allocate(this%h1D_tLITRf_P_FLX_col(beg_col:end_col))  ;this%h1D_tLITRf_P_FLX_col(:)=spval
  allocate(this%h1D_tEXCH_PO4_col(beg_col:end_col))     ;this%h1D_tEXCH_PO4_col(:)=spval
  allocate(this%h1D_SUR_DOP_FLX_col(beg_col:end_col))   ;this%h1D_SUR_DOP_FLX_col(:)=spval
  allocate(this%h1D_SUB_DOP_FLX_col(beg_col:end_col))   ;this%h1D_SUB_DOP_FLX_col(:)=spval
  allocate(this%h1D_SUR_DIP_FLX_col(beg_col:end_col))   ;this%h1D_SUR_DIP_FLX_col(:)=spval
  allocate(this%h1D_SUB_DIP_FLX_col(beg_col:end_col))   ;this%h1D_SUB_DIP_FLX_col(:)=spval
  allocate(this%h1D_HeatFlx2Grnd_col(beg_col:end_col))     ;this%h1D_HeatFlx2Grnd_col(:)=spval
  allocate(this%h1D_CumDryDepoOM_col(beg_col:end_col)); this%h1D_CumDryDepoOM_col(:)=spval
  allocate(this%h1D_cyanoBactC_col(beg_col:end_col)); this%h1D_cyanoBactC_col(:)=spval
  allocate(this%h1D_RadSW_Grnd_col(beg_col:end_col)); this%h1D_RadSW_Grnd_col(:)=spval
  allocate(this%h1D_RadPAR_Grnd_col(beg_col:end_col)); this%h1D_RadPAR_Grnd_col(:)=spval
  allocate(this%h1D_RadPAR2Soil_col(beg_col:end_col)); this%h1D_RadPAR2Soil_col(:)=spval
  allocate(this%h1D_RadPAR2LitR_col(beg_col:end_col)); this%h1D_RadPAR2LitR_col(:)=spval
  allocate(this%h1D_CanSWRad_col(beg_col:end_col)); this%h1D_CanSWRad_col(:)=spval
  allocate(this%h1D_Qinfl2soi_col(beg_col:end_col))     ;this%h1D_Qinfl2soi_col(:)=spval
  allocate(this%h1D_Qdrain_col(beg_col:end_col))       ; this%h1D_Qdrain_col(:)=spval
  allocate(this%h2D_QDrainloss_vr(beg_col:end_col,1:JZ)); this%h2D_QDrainloss_vr=spval
  allocate(this%h2D_FermOXYI_vr(beg_col:end_col,1:JZ)); this%h2D_FermOXYI_vr=spval
  allocate(this%h1D_tSALT_DISCHG_FLX_col(beg_col:end_col)) ;this%h1D_tSALT_DISCHG_FLX_col(:)=spval
  allocate(this%h1D_SUR_DON_FLX_col(beg_col:end_col))    ;this%h1D_SUR_DON_FLX_col(:)=spval
  allocate(this%h1D_SUB_DON_FLX_col(beg_col:end_col))    ;this%h1D_SUB_DON_FLX_col(:)=spval
  allocate(this%h1D_SUR_DIN_FLX_col(beg_col:end_col))    ;this%h1D_SUR_DIN_FLX_col(:)=spval
  allocate(this%h1D_SUB_DIN_FLX_col(beg_col:end_col))    ;this%h1D_SUB_DIN_FLX_col(:)=spval
  allocate(this%h1D_SUR_DOC_FLX_col(beg_col:end_col))    ;this%h1D_SUR_DOC_FLX_col(:)=spval
  allocate(this%h1D_SUB_DOC_FLX_col(beg_col:end_col))    ;this%h1D_SUB_DOC_FLX_col(:)=spval
  allocate(this%h1D_SUR_DIC_FLX_col(beg_col:end_col))    ;this%h1D_SUR_DIC_FLX_col(:)=spval
  allocate(this%h1D_SUB_DIC_FLX_col(beg_col:end_col))    ;this%h1D_SUB_DIC_FLX_col(:)=spval
  allocate(this%h1D_SnowCanopy_col(beg_col:end_col)) ; this%h1D_SnowCanopy_col(:)=spval
  allocate(this%h1D_tPREC_P_col(beg_col:end_col))      ;this%h1D_tPREC_P_col(:)=spval
  allocate(this%h1D_tMICRO_P_col(beg_col:end_col))       ;this%h1D_tMICRO_P_col(:)=spval
  allocate(this%h1D_PO4_FIRE_col(beg_col:end_col))       ;this%h1D_PO4_FIRE_col(:)=spval
  allocate(this%h1D_cPO4_LITR_col(beg_col:end_col))      ;this%h1D_cPO4_LITR_col(:)=spval
  allocate(this%h1D_cEXCH_P_LITR_col(beg_col:end_col))   ;this%h1D_cEXCH_P_LITR_col(:)=spval
  allocate(this%h1D_NET_P_MIN_col(beg_col:end_col))      ;this%h1D_NET_P_MIN_col(:)=spval
  allocate(this%h1D_N2_SEMIS_FLX_col(beg_col:end_col))   ;this%h1D_N2_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_NH3_SEMIS_FLX_col(beg_col:end_col))  ;this%h1D_NH3_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_H2_SEMIS_FLX_col(beg_col:end_col))   ;this%h1D_H2_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_PSI_SURF_col(beg_col:end_col))       ;this%h1D_PSI_SURF_col(:)=spval
  allocate(this%h1D_SURF_ELEV_col(beg_col:end_col))      ;this%h1D_SURF_ELEV_col(:)=spval
  allocate(this%h1D_tLITR_C_col(beg_col:end_col));this%h1D_tLITR_C_col(:)=spval
  allocate(this%h1D_tLITR_N_col(beg_col:end_col));this%h1D_tLITR_N_col(:)=spval
  allocate(this%h1D_RootAR_col(beg_col:end_col)); this%h1D_RootAR_col(:)=spval
  allocate(this%h1D_RootCO2Relez_col(beg_col:end_col)); this%h1D_RootCO2Relez_col(:)=spval
  allocate(this%h1D_tRAD_col(beg_col:end_col)); this%h1D_tRAD_col(:)=spval
  allocate(this%h2D_BotDEPZ_vr(beg_col:end_col,1:JZ)); this%h2D_BotDEPZ_vr(:,:)=spval
  allocate(this%h1D_AMENDED_N_col(beg_col:end_col))       ;this%h1D_AMENDED_N_col(:)=spval
  allocate(this%h1D_tNH4X_col(beg_col:end_col))           ;this%h1D_tNH4X_col(:)=spval
  allocate(this%h1D_tNO3_col(beg_col:end_col))            ;this%h1D_tNO3_col(:)=spval
  allocate(this%h1D_tMICRO_N_col(beg_col:end_col))        ;this%h1D_tMICRO_N_col(:)=spval
  allocate(this%h1D_TEMP_LITR_col(beg_col:end_col))       ;this%h1D_TEMP_LITR_col(:)=spval
  allocate(this%h1D_TEMP_surf_col(beg_col:end_col))       ;this%h1D_TEMP_surf_col(:)=spval
  allocate(this%h1D_TEMP_SNOW_col(beg_col:end_col))       ;this%h1D_TEMP_SNOW_col(:)=spval
  allocate(this%h1D_FracBySnow_col(beg_col:end_col))      ;this%h1D_FracBySnow_col(:)=spval
  allocate(this%h1D_FracByLitr_col(beg_col:end_col))      ;this%h1D_FracByLitr_col(:)=spval
  allocate(this%h1D_AMENDED_C_col(beg_col:end_col))       ;this%h1D_AMENDED_C_col(:)=spval
  allocate(this%h1D_tMICRO_C_col(beg_col:end_col))        ;this%h1D_tMICRO_C_col(:)=spval
  allocate(this%h1D_tSoilOrgC_col(beg_col:end_col))       ;this%h1D_tSoilOrgC_col(:)=spval
  allocate(this%h1D_tSoilOrgN_col(beg_col:end_col))       ;this%h1D_tSoilOrgN_col(:)=spval
  allocate(this%h1D_tSoilOrgP_col(beg_col:end_col))       ;this%h1D_tSoilOrgP_col(:)=spval
  allocate(this%h1D_OMC_LITR_col(beg_col:end_col))        ;this%h1D_OMC_LITR_col(:)=spval
  allocate(this%h1D_OMN_LITR_col(beg_col:end_col))        ;this%h1D_OMN_LITR_col(:)=spval
  allocate(this%h1D_OMP_LITR_col(beg_col:end_col))        ;this%h1D_OMP_LITR_col(:)=spval
  allocate(this%h1D_Ar_mass_col(beg_col:end_col))         ;this%h1D_Ar_mass_col(:) = spval
  allocate(this%h1D_CO2_mass_col(beg_col:end_col))         ;this%h1D_CO2_mass_col(:) = spval
  allocate(this%h1D_Gchem_CO2_prod_col(beg_col:end_col)) ; this%h1D_Gchem_CO2_prod_col(:)=spval
  allocate(this%h1D_Ar_soilMass_col(beg_col:end_col))     ;this%h1D_Ar_soilMass_col(:)=spval
  allocate(this%h1D_ATM_CO2_col(beg_col:end_col))         ;this%h1D_ATM_CO2_col(:)=spval
  allocate(this%h1D_ATM_CH4_col(beg_col:end_col))         ;this%h1D_ATM_CH4_col(:)=spval
  allocate(this%h1D_NBP_col(beg_col:end_col))             ;this%h1D_NBP_col(:)=spval
  allocate(this%h1D_CO2_WetDep_FLX_col(beg_col:end_col)) ; this%h1D_CO2_WetDep_FLX_col(:)=spval
  allocate(this%h1D_RootN_Fix_col(beg_col:end_col)); this%h1D_RootN_Fix_col(:)=spval
  allocate(this%h1D_Ar_WetDep_FLX_col(beg_col:end_col)) ; this%h1D_Ar_WetDep_FLX_col(:)=spval
  allocate(this%h1D_RootXO2_flx_col(beg_col:end_col)); this%h1D_RootXO2_flx_col(:)=spval
  allocate(this%h1D_RUNOFF_FLX_col(beg_col:end_col)) ; this%h1D_RUNOFF_FLX_col(:)=spval
  allocate(this%h1D_SEDIMENT_FLX_col(beg_col:end_col))    ;this%h1D_SEDIMENT_FLX_col(:)=spval
  allocate(this%h1D_QDISCHG_FLX_col(beg_col:end_col))      ;this%h1D_QDISCHG_FLX_col(:)=spval
  allocate(this%h1D_HeatDISCHG_FLX_col(beg_col:end_col))  ; this%h1D_HeatDISCHG_FLX_col(:)=spval
  allocate(this%h1D_ECO_LAI_col(beg_col:end_col))         ;this%h1D_ECO_LAI_col(:)=spval
  allocate(this%h1D_ECO_SAI_col(beg_col:end_col))         ;this%h1D_ECO_SAI_col(:)=spval
  allocate(this%h1D_Eco_GPP_CumYr_col(beg_col:end_col))         ;this%h1D_Eco_GPP_CumYr_col(:)=spval
  allocate(this%h1D_ECO_RA_col(beg_col:end_col))          ;this%h1D_ECO_RA_col(:)=spval
  allocate(this%h1D_Eco_NPP_CumYr_col(beg_col:end_col))         ;this%h1D_Eco_NPP_CumYr_col(:)=spval
  allocate(this%h1D_Eco_HR_CumYr_col(beg_col:end_col))          ;this%h1D_Eco_HR_CumYr_col(:)=spval
  allocate(this%h1D_Eco_HR_CO2_col(beg_col:end_col));  this%h1D_Eco_HR_CO2_col(:)=spval
  allocate(this%h1D_Eco_HR_CO2_litr_col(beg_col:end_col));  this%h1D_Eco_HR_CO2_litr_col(:)=spval
!  allocate(this%h1D_Eco_HR_CH4_col(beg_col:end_col));  this%h1D_Eco_HR_CH4_col(:)=spval
  allocate(this%h1D_tDIC_col(beg_col:end_col))            ;this%h1D_tDIC_col=spval
  allocate(this%h1D_tSTANDING_DEAD_C_col(beg_col:end_col));this%h1D_tSTANDING_DEAD_C_col=spval
  allocate(this%h1D_tSTANDING_DEAD_N_col(beg_col:end_col));this%h1D_tSTANDING_DEAD_N_col=spval
  allocate(this%h1D_tSTANDING_DEAD_P_col(beg_col:end_col));this%h1D_tSTANDING_DEAD_P_col=spval
  allocate(this%h1D_tPRECIP_col(beg_col:end_col))          ;this%h1D_tPRECIP_col(:)=spval
  allocate(this%h1D_ECO_ET_col(beg_col:end_col))              ;this%h1D_ECO_ET_col(:)=spval
  allocate(this%h1D_trcg_NH3_cumerr_col(beg_col:end_col)); this%h1D_trcg_NH3_cumerr_col(:)=spval
  allocate(this%h1D_trcg_H2_cumerr_col(beg_col:end_col)); this%h1D_trcg_H2_cumerr_col(:)=spval
  allocate(this%h1D_trcg_Ar_cumerr_col(beg_col:end_col)); this%h1D_trcg_Ar_cumerr_col(:)=spval
  allocate(this%h1D_trcg_N2_cumerr_col(beg_col:end_col)); this%h1D_trcg_N2_cumerr_col(:)=spval
  allocate(this%h1D_trcg_O2_cumerr_col(beg_col:end_col)); this%h1D_trcg_O2_cumerr_col(:)=spval
  allocate(this%h1D_trcg_CO2_cumerr_col(beg_col:end_col)); this%h1D_trcg_CO2_cumerr_col(:)=spval
  allocate(this%h1D_trcg_CH4_cumerr_col(beg_col:end_col)); this%h1D_trcg_CH4_cumerr_col(:)=spval
  allocate(this%h1d_CAN_NEE_col(beg_col:end_col))        ; this%h1d_CAN_NEE_col(:)=spval
  allocate(this%h1D_ECO_RADSW_col(beg_col:end_col))       ; this%h1D_ECO_RADSW_col(:)=spval
  allocate(this%h1D_N2O_LITR_col(beg_col:end_col))        ;this%h1D_N2O_LITR_col(:)=spval
  allocate(this%h1D_NH3_LITR_col(beg_col:end_col))        ;this%h1D_NH3_LITR_col(:)=spval
  allocate(this%h1D_SOL_RADN_col(beg_col:end_col))        ;this%h1D_SOL_RADN_col(:)=spval
  allocate(this%h1D_AIR_TEMP_col(beg_col:end_col))        ;this%h1D_AIR_TEMP_col(:)=spval
  allocate(this%h1D_FreeNFix_col(beg_col:end_col))       ;this%h1D_FreeNFix_col(:)=spval
  allocate(this%h1D_PATM_col(beg_col:end_col))            ;this%h1D_PATM_col(:)=spval
  allocate(this%h1D_HUM_col(beg_col:end_col))             ;this%h1D_HUM_col(:)=spval
  allocate(this%h1D_WIND_col(beg_col:end_col))            ;this%h1D_WIND_col(:)=spval
  allocate(this%h1D_PREC_col(beg_col:end_col))            ;this%h1D_PREC_col(:)=spval
  allocate(this%h1D_Snofall_col(beg_col:end_col))         ;this%h1D_Snofall_col(:)=spval
  allocate(this%h1D_SOIL_RN_col(beg_col:end_col))         ;this%h1D_SOIL_RN_col(:)=spval
  allocate(this%h1D_LWSky_col(beg_col:end_col))           ;this%h1D_LWSky_col(:)=spval
  allocate(this%h1D_SOIL_LE_col(beg_col:end_col))         ;this%h1D_SOIL_LE_col(:)=spval
  allocate(this%h1D_SOIL_H_col(beg_col:end_col))          ;this%h1D_SOIL_H_col(:)=spval
  allocate(this%h1D_SOIL_G_col(beg_col:end_col))          ;this%h1D_SOIL_G_col(:)=spval
  allocate(this%h1D_ECO_RN_col(beg_col:end_col))          ;this%h1D_ECO_RN_col(:)=spval
  allocate(this%h1D_ECO_LE_col(beg_col:end_col))          ;this%h1D_ECO_LE_col(:)=spval
  allocate(this%h1D_Eco_HeatSen_col(beg_col:end_col))        ;this%h1D_Eco_HeatSen_col(:)=spval
  allocate(this%h1D_ECO_Heat2G_col(beg_col:end_col))           ;this%h1D_ECO_Heat2G_col(:)=spval
  allocate(this%h1D_O2_LITR_col(beg_col:end_col))         ;this%h1D_O2_LITR_col(:)=spval
  allocate(this%h1D_MIN_LWP_ptc(beg_ptc:end_ptc))         ;this%h1D_MIN_LWP_ptc(:)=spval
  allocate(this%h1D_SLA_ptc(beg_ptc:end_ptc)); this%h1D_SLA_ptc(:)=spval
  allocate(this%h1D_CO2_SEMIS_FLX_col(beg_col:end_col))    ;this%h1D_CO2_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_AR_SEMIS_FLX_col(beg_col:end_col))     ;this%h1D_AR_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_ECO_CO2_FLX_col(beg_col:end_col))     ;this%h1D_ECO_CO2_FLX_col(:)=spval
  allocate(this%h1D_CH4_SEMIS_FLX_col(beg_col:end_col))         ;this%h1D_CH4_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_CH4_EBU_flx_col(beg_col:end_col))     ;this%h1D_CH4_EBU_flx_col(:)=spval
  allocate(this%h1D_Ar_EBU_flx_col(beg_col:end_col))      ;this%h1D_Ar_EBU_flx_col(:)=spval
  allocate(this%h1D_CO2_TPR_err_col(beg_col:end_col))    ; this%h1D_CO2_TPR_err_col(:)=spval
  allocate(this%h1D_Ar_TPR_err_col(beg_col:end_col))     ;this%h1D_Ar_TPR_err_col(:)=spval
  allocate(this%h1D_CO2_Drain_flx_col(beg_col:end_col))  ; this%h1D_CO2_Drain_flx_col(:)=spval
  allocate(this%h1D_CO2_hydloss_flx_col(beg_col:end_col));  this%h1D_CO2_hydloss_flx_col(:)=spval
  allocate(this%h1D_NH3_hydloss_flx_col(beg_col:end_col)); this%h1D_NH3_hydloss_flx_col(:)=spval
  allocate(this%h1D_NO3_hydloss_flx_col(beg_col:end_col)); this%h1D_NO3_hydloss_flx_col(:)=spval
  allocate(this%h1D_CH4_PLTROOT_flx_col(beg_col:end_col)) ;this%h1D_CH4_PLTROOT_flx_col(:)=spval
  allocate(this%h1D_AR_PLTROOT_flx_col(beg_col:end_col)); this%h1D_AR_PLTROOT_flx_col(:)=spval
  allocate(this%h1D_CO2_PLTROOT_flx_col(beg_col:end_col)) ;this%h1D_CO2_PLTROOT_flx_col(:)=spval
  allocate(this%h1D_O2_PLTROOT_flx_col(beg_col:end_col)) ;this%h1D_O2_PLTROOT_flx_col(:)=spval
  allocate(this%h1D_VPQ_col(beg_col:end_col)); this%h1D_VPQ_col(:)=spval
  allocate(this%h1D_TKQ_col(beg_col:end_col));this%h1D_TKQ_col(:)=spval
  allocate(this%h1D_CO2_DIF_flx_col(beg_col:end_col)); this%h1D_CO2_DIF_flx_col(:)=spval
  allocate(this%h1D_O2_DIF_flx_col(beg_col:end_col)); this%h1D_O2_DIF_flx_col(:)=spval
  allocate(this%h1D_CH4_DIF_flx_col(beg_col:end_col)); this%h1D_CH4_DIF_flx_col(:)=spval
  allocate(this%h1D_NH3_DIF_flx_col(beg_col:end_col)); this%h1D_NH3_DIF_flx_col(:)=spval
  allocate(this%h1D_Ar_DIF_flx_col(beg_col:end_col)); this%h1D_Ar_DIF_flx_col(:)=spval
  allocate(this%h1D_RoughnessLength_col(beg_col:end_col)); this%h1D_RoughnessLength_col(:)=spval
  allocate(this%h1D_ZeroPlaneDisplacem_col(beg_col:end_col)); this%h1D_ZeroPlaneDisplacem_col(:)=spval
  allocate(this%h1D_O2_SEMIS_FLX_col(beg_col:end_col))          ;this%h1D_O2_SEMIS_FLX_col(:)=spval
  allocate(this%h1D_CO2_LITR_col(beg_col:end_col))        ;this%h1D_CO2_LITR_col(:)=spval
  allocate(this%h1D_EVAPG_col(beg_col:end_col))           ;this%h1D_EVAPG_col(:)=spval
  allocate(this%h1D_CondGasXSurf_col(beg_col:end_col)); this%h1D_CondGasXSurf_col(:)=spval
  allocate(this%h1D_CANET_col(beg_col:end_col))           ;this%h1D_CANET_col(:)=spval
  allocate(this%h1D_CanopyEvap_col(beg_col:end_col)) ; this%h1D_CanopyEvap_col(:)=spval
  allocate(this%h1D_PAR_col(beg_col:end_col))             ;this%h1D_PAR_col(:)=spval
  allocate(this%h1D_Root1stTipSinkWt_ptc(beg_ptc:end_ptc)); this%h1D_Root1stTipSinkWt_ptc(:)=spval
  allocate(this%h1D_NWetDep_flx_col(beg_col:end_col)); this%h1D_NWetDep_flx_col(:)=spval
  allocate(this%h1d_fPAR_col(beg_col:end_col));   this%h1d_fPAR_col(:)=spval
  allocate(this%h1D_tSWC_col(beg_col:end_col))            ;this%h1D_tSWC_col(:)=spval
  allocate(this%h1D_tHeat_col(beg_col:end_col))           ;this%h1D_tHeat_col(:)=spval
  allocate(this%h1D_SNOWPACK_col(beg_col:end_col))        ;this%h1D_SNOWPACK_col(:)=spval
  allocate(this%h1D_SNOWDENS_col(beg_col:end_col))        ;this%h1D_SNOWDENS_col(:)=spval
  allocate(this%h1D_SURF_WTR_col(beg_col:end_col))        ;this%h1D_SURF_WTR_col(:)=spval
  allocate(this%h1D_ThetaW_litr_col(beg_col:end_col))    ;this%h1D_ThetaW_litr_col(:)=spval
  allocate(this%h1D_ThetaI_litr_col(beg_col:end_col))    ;this%h1D_ThetaI_litr_col(:)=spval
  allocate(this%h1D_SURF_ICE_col(beg_col:end_col))        ;this%h1D_SURF_ICE_col(:)=spval
  allocate(this%h1D_ACTV_LYR_col(beg_col:end_col))        ;this%h1D_ACTV_LYR_col(:)=spval
  allocate(this%h1D_WTR_TBL_col(beg_col:end_col))         ;this%h1D_WTR_TBL_col(:)=spval
  allocate(this%h1D_N2O_SEMIS_FLX_col(beg_col:end_col))        ;this%h1D_N2O_SEMIS_FLX_col(:)=spval
  end procedure allocate_hist_columns

end submodule HistAllocateColumn
