module SoluteChemDataType
  use data_kind_mod, only : r8 => DAT_KIND_R8

  implicit none
  public
  CHARACTER(LEN=*), private, PARAMETER :: MOD_FILENAME=__FILE__

  type, public :: solutedtype
    real(r8) :: CCO21
    real(r8) :: CCH41
    real(r8) :: COXY1
    real(r8) :: CZ2G1
    real(r8) :: CZ2O1
    real(r8) :: CN41
    real(r8) :: CN31
    real(r8) :: CAL1
    real(r8) :: CFE1
    real(r8) :: CHY1
    real(r8) :: CCA1
    real(r8) :: CMG1
    real(r8) :: CNA1
    real(r8) :: CKA1
    real(r8) :: COH1
    real(r8) :: CSO41
    real(r8) :: CCL1
    real(r8) :: CCO31
    real(r8) :: CHCO31
    real(r8) :: CALO1
    real(r8) :: CALO2
    real(r8) :: CALO3
    real(r8) :: CALO4
    real(r8) :: CALS1
    real(r8) :: CFEO1
    real(r8) :: CFEO2
    real(r8) :: CFEO3
    real(r8) :: CFEO4
    real(r8) :: CFES1
    real(r8) :: CCAO1
    real(r8) :: CCAC1
    real(r8) :: CCAH1
    real(r8) :: CCAS1
    real(r8) :: CMGO1
    real(r8) :: CMGC1
    real(r8) :: CMGH1
    real(r8) :: CMGS1
    real(r8) :: CNAC1
    real(r8) :: CNAS1
    real(r8) :: CKAS1
    real(r8) :: CH0P1
    real(r8) :: CH1P1
    real(r8) :: CH2P1
    real(r8) :: CH3P1
    real(r8) :: CF1P1
    real(r8) :: CF2P1
    real(r8) :: CC0P1
    real(r8) :: CC1P1
    real(r8) :: CC2P1
    real(r8) :: CM1P1
    real(r8) :: CSTR1
    real(r8) :: CCO2M
    real(r8) :: CCH4M
    real(r8) :: COXYM
    real(r8) :: CZ2GM
    real(r8) :: CZ2OM
    real(r8) :: CN4Z
    real(r8) :: CNOZ
    real(r8) :: CNAZ
    real(r8) :: CKAZ
    real(r8) :: CSOZ
    real(r8) :: CCLZ
    real(r8) :: CNOX
    real(r8) :: CCASOX
    real(r8) :: CN4X
    real(r8) :: CPOZ
    real(r8) :: CALZ
    real(r8) :: CFEZ
    real(r8) :: CCAZ
    real(r8) :: CMGZ
    real(r8) :: CALX
    real(r8) :: CFEX
    real(r8) :: CCAX
    real(r8) :: CMGX
    real(r8) :: CNAX
    real(r8) :: CKAX
    real(r8) :: CSOX
    real(r8) :: CCLX
    real(r8) :: CALPOX
    real(r8) :: CFEPOX
    real(r8) :: CCAPDX
    real(r8) :: CCAPHX
    real(r8) :: CALOHX
    real(r8) :: CFEOHX
    real(r8) :: CCACOX
    real(r8) :: XN41
    real(r8) :: XHY1
    real(r8) :: XAL1
    real(r8) :: XFE1
    real(r8) :: XCA1
    real(r8) :: PCAPH1
    real(r8) :: XMG1
    real(r8) :: XNA1
    real(r8) :: XKA1
    real(r8) :: XHC1
    real(r8) :: XALO21
    real(r8) :: XFEO21
    real(r8) :: XOH01
    real(r8) :: XOH11
    real(r8) :: XOH21
    real(r8) :: XH1P1
    real(r8) :: XH2P1
    real(r8) :: PALOH1
    real(r8) :: PFEOH1
    real(r8) :: PCACO1
    real(r8) :: PCASO1
    real(r8) :: PALPO1
    real(r8) :: PFEPO1
    real(r8) :: PCAPD1
    real(r8) :: FH2O
    real(r8) :: ATCA
    real(r8) :: XAEC
    real(r8) :: CEC
    real(r8) :: ORGC
    real(r8) :: VLPO4
    real(r8) :: XCEC
    real(r8) :: GKC4
    real(r8) :: GKCA
    real(r8) :: GKCH
    real(r8) :: GKCK
    real(r8) :: GKCN
    real(r8) :: GKCM
    real(r8) :: ZEROS
    real(r8) :: VLWatMicP
  end type solutedtype

  type, public :: solute_flx_type
    real(r8) :: TRN4S
    real(r8) :: TRN4B
    real(r8) :: TRN3S
    real(r8) :: TRN3B
    real(r8) :: TRH1P
    real(r8) :: TRH2P
    real(r8) :: TRH1B
    real(r8) :: TRH2B
    real(r8) :: TRXN4
    real(r8) :: TRXNB
    real(r8) :: TRXH1
    real(r8) :: TRXH2
    real(r8) :: TRX1P
    real(r8) :: TRX2P
    real(r8) :: TRBH1
    real(r8) :: TRBH2
    real(r8) :: TRB1P
    real(r8) :: TRB2P
    real(r8) :: TRALPO
    real(r8) :: TRFEPO
    real(r8) :: TRCAPD
    real(r8) :: TRCAPH
    real(r8) :: TRCAPM
    real(r8) :: TRALPB
    real(r8) :: TRFEPB
    real(r8) :: TRCPDB
    real(r8) :: TRCPHB
    real(r8) :: TRCPMB
    real(r8) :: TRAL
    real(r8) :: TRFE
    real(r8) :: TRHY
    real(r8) :: TRCA
    real(r8) :: TRMG
    real(r8) :: TRNA
    real(r8) :: TRKA
    real(r8) :: TROH
    real(r8) :: TRSO4
    real(r8) :: TRCO3
    real(r8) :: TRHCO
    real(r8) :: TRCO2
    real(r8) :: TRAL1
    real(r8) :: TRAL2
    real(r8) :: TRAL3
    real(r8) :: TRAL4
    real(r8) :: TRALS
    real(r8) :: TRFE1
    real(r8) :: TRFE2
    real(r8) :: TRFE3
    real(r8) :: TRFE4
    real(r8) :: TRFES
    real(r8) :: TRCAO
    real(r8) :: TRCAC
    real(r8) :: TRCAH
    real(r8) :: TRCAS
    real(r8) :: TRMGO
    real(r8) :: TRMGC
    real(r8) :: TRMGH
    real(r8) :: TRMGS
    real(r8) :: TRNAC
    real(r8) :: TRNAS
    real(r8) :: TRKAS
    real(r8) :: TRH0P
    real(r8) :: TRH3P
    real(r8) :: TRF1P
    real(r8) :: TRF2P
    real(r8) :: TRC0P
    real(r8) :: TRC1P
    real(r8) :: TRC2P
    real(r8) :: TRM1P
    real(r8) :: TRH0B
    real(r8) :: TRH3B
    real(r8) :: TRF1B
    real(r8) :: TRF2B
    real(r8) :: TRC0B
    real(r8) :: TRC1B
    real(r8) :: TRC2B
    real(r8) :: TRM1B
    real(r8) :: TRXHY
    real(r8) :: TRXAL
    real(r8) :: TRXFE
    real(r8) :: TRXCA
    real(r8) :: TRXMG
    real(r8) :: TRXNA
    real(r8) :: TRXKA
    real(r8) :: TRXHC
    real(r8) :: TRXAL2
    real(r8) :: TRXFE2
    real(r8) :: TRXH0
    real(r8) :: TRBH0
    real(r8) :: TRALOH
    real(r8) :: TRFEOH
    real(r8) :: TRCACO
    real(r8) :: TRCASO
    real(r8) :: TRH2O
    real(r8) :: TBION
    real(r8) :: TBCO2
  contains
    procedure, public :: SetZero
  end type solute_flx_type

  type, public :: chem_var_type
  real(r8) :: CH1P1
  real(r8) :: CH1PB
  real(r8) :: CH2P1
  real(r8) :: CH2PB
  real(r8) :: CN31
  real(r8) :: CN3B
  real(r8) :: CN41
  real(r8) :: CN4B
  real(r8) :: PALPO1
  real(r8) :: PALPOB
  real(r8) :: PCAPD1
  real(r8) :: PCAPDB
  real(r8) :: PCAPH1
  real(r8) :: PCAPHB
  real(r8) :: PCAPM1
  real(r8) :: PCAPMB
  real(r8) :: PFEPO1
  real(r8) :: PFEPOB
  real(r8) :: SoilMicPMassLayerX
  real(r8) :: VLWatMicPNB
  real(r8) :: VLWatMicPNH
  real(r8) :: VLWatMicPPB
  real(r8) :: VLWatMicPPO
  real(r8) :: XCEC
  real(r8) :: PH
  real(r8) :: CAL
  real(r8) :: CFE
  real(r8) :: VLWatMicPM
  real(r8) :: ZMG
  real(r8) :: ZNA
  real(r8) :: ZKA
  real(r8) :: CCO2S
  real(r8) :: CCA
  real(r8) :: SoilMicPMassLayer
  real(r8) :: XAEC
  real(r8) :: GKC4
  real(r8) :: GKCA
  real(r8) :: GKCH
  real(r8) :: GKCM
  real(r8) :: GKCK
  real(r8) :: GKCN
  real(r8) :: ZNO3S
  real(r8) :: ZNO3B
  real(r8) :: XZHYS
  real(r8) :: ZHY
  real(r8) :: ZOH
  real(r8) :: ZAL
  real(r8) :: ZFE
  real(r8) :: ZCA
  real(r8) :: ZSO4
  real(r8) :: ZCL
  real(r8) :: ZCO3
  real(r8) :: ZHCO3
  real(r8) :: CO2S
  real(r8) :: ZALOH1
  real(r8) :: ZALOH2
  real(r8) :: ZALOH3
  real(r8) :: ZALOH4
  real(r8) :: ZALS
  real(r8) :: ZFEOH1
  real(r8) :: ZFEOH2
  real(r8) :: ZFEOH3
  real(r8) :: ZFEOH4
  real(r8) :: ZFES
  real(r8) :: ZCAO
  real(r8) :: ZCAC
  real(r8) :: ZCAH
  real(r8) :: ZCAS
  real(r8) :: ZMGO
  real(r8) :: ZMGC
  real(r8) :: ZMGH
  real(r8) :: ZMGS
  real(r8) :: ZNAC
  real(r8) :: ZNAS
  real(r8) :: ZKAS
  real(r8) :: H0PO4
  real(r8) :: H3PO4
  real(r8) :: ZFE1P
  real(r8) :: ZFE2P
  real(r8) :: ZCA0P
  real(r8) :: ZCA1P
  real(r8) :: ZCA2P
  real(r8) :: ZMG1P
  real(r8) :: H0POB
  real(r8) :: H3POB
  real(r8) :: ZFE1PB
  real(r8) :: ZFE2PB
  real(r8) :: ZCA0PB
  real(r8) :: ZCA1PB
  real(r8) :: ZCA2PB
  real(r8) :: ZMG1PB
  real(r8) :: XHY
  real(r8) :: XAL
  real(r8) :: XFE
  real(r8) :: XCA
  real(r8) :: XMG
  real(r8) :: XNA
  real(r8) :: XKA
  real(r8) :: XHC
  real(r8) :: XALO2
  real(r8) :: XFEO2
  real(r8) :: ORGC
  real(r8) :: PALOH
  real(r8) :: PFEOH
  real(r8) :: PCACO
  real(r8) :: PCASO
  real(r8) :: VLPOB
  real(r8) :: VLPO4
  real(r8) :: VLNOB
  real(r8) :: VLNO3
  real(r8) :: VLNH4
  real(r8) :: VLNHB
  real(r8) :: X1P1B
  real(r8) :: X2P1B
  real(r8) :: XH11B
  real(r8) :: XH1P1
  real(r8) :: XH21B
  real(r8) :: XH2P1
  real(r8) :: XN41
  real(r8) :: XN4B
  real(r8) :: XOH11
  real(r8) :: XOH21
  real(r8) :: XH01B
  real(r8) :: XOH01
  real(r8) :: VLWatMicPNZ
  real(r8) :: VLWatMicPNO
  real(r8) :: BKVLNH
  real(r8) :: BKVLNB
  real(r8) :: BKVLPO
  real(r8) :: BKVLPB
  real(r8) :: BKVLNO
  real(r8) :: BKVLNZ
  end type chem_var_type
contains

  subroutine SetZero(solflx)
  implicit none
  class(solute_flx_type)  :: solflx

  solflx%TRN4S = 0._r8
  solflx%TRN4B = 0._r8
  solflx%TRN3S = 0._r8
  solflx%TRN3B = 0._r8
  solflx%TRH1P = 0._r8
  solflx%TRH2P = 0._r8
  solflx%TRH1B = 0._r8
  solflx%TRH2B = 0._r8
  solflx%TRXN4 = 0._r8
  solflx%TRXNB = 0._r8
  solflx%TRXH1 = 0._r8
  solflx%TRXH2 = 0._r8
  solflx%TRX1P = 0._r8
  solflx%TRX2P = 0._r8
  solflx%TRBH1 = 0._r8
  solflx%TRBH2 = 0._r8
  solflx%TRB1P = 0._r8
  solflx%TRB2P = 0._r8
  solflx%TRALPO= 0._r8
  solflx%TRFEPO= 0._r8
  solflx%TRCAPD= 0._r8
  solflx%TRCAPH= 0._r8
  solflx%TRCAPM= 0._r8
  solflx%TRALPB= 0._r8
  solflx%TRFEPB= 0._r8
  solflx%TRCPDB= 0._r8
  solflx%TRCPHB= 0._r8
  solflx%TRCPMB= 0._r8
  solflx%TRAL  = 0._r8
  solflx%TRFE  = 0._r8
  solflx%TRHY  = 0._r8
  solflx%TRCA  = 0._r8
  solflx%TRMG  = 0._r8
  solflx%TRNA  = 0._r8
  solflx%TRKA  = 0._r8
  solflx%TROH  = 0._r8
  solflx%TRSO4 = 0._r8
  solflx%TRCO3 = 0._r8
  solflx%TRHCO = 0._r8
  solflx%TRCO2 = 0._r8
  solflx%TRAL1 = 0._r8
  solflx%TRAL2 = 0._r8
  solflx%TRAL3 = 0._r8
  solflx%TRAL4 = 0._r8
  solflx%TRALS = 0._r8
  solflx%TRFE1 = 0._r8
  solflx%TRFE2 = 0._r8
  solflx%TRFE3 = 0._r8
  solflx%TRFE4 = 0._r8
  solflx%TRFES = 0._r8
  solflx%TRCAO = 0._r8
  solflx%TRCAC = 0._r8
  solflx%TRCAH = 0._r8
  solflx%TRCAS = 0._r8
  solflx%TRMGO = 0._r8
  solflx%TRMGC = 0._r8
  solflx%TRMGH = 0._r8
  solflx%TRMGS = 0._r8
  solflx%TRNAC = 0._r8
  solflx%TRNAS = 0._r8
  solflx%TRKAS = 0._r8
  solflx%TRH0P = 0._r8
  solflx%TRH3P = 0._r8
  solflx%TRF1P = 0._r8
  solflx%TRF2P = 0._r8
  solflx%TRC0P = 0._r8
  solflx%TRC1P = 0._r8
  solflx%TRC2P = 0._r8
  solflx%TRM1P = 0._r8
  solflx%TRH0B = 0._r8
  solflx%TRH3B = 0._r8
  solflx%TRF1B = 0._r8
  solflx%TRF2B = 0._r8
  solflx%TRC0B = 0._r8
  solflx%TRC1B = 0._r8
  solflx%TRC2B = 0._r8
  solflx%TRM1B = 0._r8
  solflx%TRXHY = 0._r8
  solflx%TRXAL = 0._r8
  solflx%TRXFE = 0._r8
  solflx%TRXCA = 0._r8
  solflx%TRXMG = 0._r8
  solflx%TRXNA = 0._r8
  solflx%TRXKA = 0._r8
  solflx%TRXHC = 0._r8
  solflx%TRXAL2= 0._r8
  solflx%TRXFE2= 0._r8
  solflx%TRXH0 = 0._r8
  solflx%TRBH0 = 0._r8
  solflx%TRALOH= 0._r8
  solflx%TRFEOH= 0._r8
  solflx%TRCACO= 0._r8
  solflx%TRCASO= 0._r8
  solflx%TRH2O = 0._r8
  solflx%TBION = 0._r8
  solflx%TBCO2 = 0._r8

  end subroutine SetZero
end module SoluteChemDataType
